[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AcceptOrRejectEndpointConnections = []
AddCustomIngressPort = []
AddEipV2 = []
AddEndpointPermissions = []
AddEngressEipV2 = []
AddIngressEipV2 = []
AddingBackendInstancesV2 = []
AssociateAppsForAppQuota = []
AssociateCertificate = []
AssociateCertificateV2 = []
AssociateDomain = []
AssociateDomainV2 = []
AssociateRequestThrottlingPolicy = []
AssociateRequestThrottlingPolicyV2 = []
AssociateSignatureKey = []
AssociateSignatureKeyV2 = []
AttachApiToPlugin = []
AttachPluginToApi = []
BatchAssociateCertsV2 = []
BatchAssociateDomainsV2 = []
BatchCreateOrDeleteInstanceTags = []
BatchDeleteAclV2 = []
BatchDeleteApiAclBindingV2 = []
BatchDisableMembers = []
BatchDisassociateCertsV2 = []
BatchDisassociateDomainsV2 = []
BatchDisassociateThrottlingPolicyV2 = []
BatchEnableMembers = []
BatchPublishOrOfflineApiV2 = []
CancelingAuthorization = []
CancelingAuthorizationV2 = []
ChangeApiVersionV2 = []
CheckAnApp = []
CheckApiGroupsV2 = []
CheckApisV2 = []
CheckAppV2 = []
CreateAclStrategyV2 = []
CreateAnApp = []
CreateAnAppV2 = []
CreateApi = []
CreateApiAclBindingV2 = []
CreateApiGroup = []
CreateApiGroupV2 = []
CreateApiV2 = []
CreateAppCodeAutoV2 = []
CreateAppCodeV2 = []
CreateAppQuota = []
CreateAuthorizingApps = []
CreateAuthorizingAppsV2 = []
CreateCertificateV2 = []
CreateCustomAuthorizerV2 = []
CreateEnvironment = []
CreateEnvironmentV2 = []
CreateEnvironmentVariable = []
CreateEnvironmentVariableV2 = []
CreateFeatureV2 = []
CreateGatewayResponseV2 = []
CreateInstanceV2 = []
CreateMemberGroup = []
CreateOrDeletePublishRecordForApiV2 = []
CreateOrder = []
CreatePlugin = []
CreatePostPayResizeOrder = []
CreatePrepayResize = []
CreateRequestThrottlingPolicy = []
CreateRequestThrottlingPolicyV2 = []
CreateSignatureKey = []
CreateSignatureKeyV2 = []
CreateSpecialThrottlingConfiguration = []
CreateSpecialThrottlingConfigurationV2 = []
CreateVpcChannelV2 = []
DebugApiV2 = []
DeleteAclV2 = []
DeleteAnApp = []
DeleteApi = []
DeleteApiAclBindingV2 = []
DeleteApiByVersionIdV2 = []
DeleteApiGroup = []
DeleteApiGroupV2 = []
DeleteApiV2 = []
DeleteAppAcl = []
DeleteAppCodeV2 = []
DeleteAppQuota = []
DeleteAppV2 = []
DeleteBackendInstanceV2 = []
DeleteCertificateV2 = []
DeleteCustomAuthorizerV2 = []
DeleteCustomIngressPort = []
DeleteEndpointPermissions = []
DeleteEnvironment = []
DeleteEnvironmentV2 = []
DeleteEnvironmentVariable = []
DeleteEnvironmentVariableV2 = []
DeleteGatewayResponseTypeV2 = []
DeleteGatewayResponseV2 = []
DeleteInstancesV2 = []
DeleteMemberGroup = []
DeletePlugin = []
DeleteRequestThrottlingPolicy = []
DeleteRequestThrottlingPolicyV2 = []
full = ["AcceptOrRejectEndpointConnections", "AddCustomIngressPort", "AddEipV2", "AddEndpointPermissions", "AddEngressEipV2", "AddingBackendInstancesV2", "AddIngressEipV2", "AssociateAppsForAppQuota", "AssociateCertificate", "AssociateCertificateV2", "AssociateDomain", "AssociateDomainV2", "AssociateRequestThrottlingPolicy", "AssociateRequestThrottlingPolicyV2", "AssociateSignatureKey", "AssociateSignatureKeyV2", "AttachApiToPlugin", "AttachPluginToApi", "BatchAssociateCertsV2", "BatchAssociateDomainsV2", "BatchCreateOrDeleteInstanceTags", "BatchDeleteAclV2", "BatchDeleteApiAclBindingV2", "BatchDisableMembers", "BatchDisassociateCertsV2", "BatchDisassociateDomainsV2", "BatchDisassociateThrottlingPolicyV2", "BatchEnableMembers", "BatchPublishOrOfflineApiV2", "CancelingAuthorization", "CancelingAuthorizationV2", "ChangeApiVersionV2", "CheckAnApp", "CheckApiGroupsV2", "CheckApisV2", "CheckAppV2", "CreateAclStrategyV2", "CreateAnApp", "CreateAnAppV2", "CreateApi", "CreateApiAclBindingV2", "CreateApiGroup", "CreateApiGroupV2", "CreateApiV2", "CreateAppCodeAutoV2", "CreateAppCodeV2", "CreateAppQuota", "CreateAuthorizingApps", "CreateAuthorizingAppsV2", "CreateCertificateV2", "CreateCustomAuthorizerV2", "CreateEnvironment", "CreateEnvironmentV2", "CreateEnvironmentVariable", "CreateEnvironmentVariableV2", "CreateFeatureV2", "CreateGatewayResponseV2", "CreateInstanceV2", "CreateMemberGroup", "CreateOrDeletePublishRecordForApiV2", "CreateOrder", "CreatePlugin", "CreatePostPayResizeOrder", "CreatePrepayResize", "CreateRequestThrottlingPolicy", "CreateRequestThrottlingPolicyV2", "CreateSignatureKey", "CreateSignatureKeyV2", "CreateSpecialThrottlingConfiguration", "CreateSpecialThrottlingConfigurationV2", "CreateVpcChannelV2", "DebugApiV2", "DeleteAclV2", "DeleteAnApp", "DeleteApi", "DeleteApiAclBindingV2", "DeleteApiByVersionIdV2", "DeleteApiGroup", "DeleteApiGroupV2", "DeleteApiV2", "DeleteAppAcl", "DeleteAppCodeV2", "DeleteAppQuota", "DeleteAppV2", "DeleteBackendInstanceV2", "DeleteCertificateV2", "DeleteCustomAuthorizerV2", "DeleteCustomIngressPort", "DeleteEndpointPermissions", "DeleteEnvironment", "DeleteEnvironmentV2", "DeleteEnvironmentVariable", "DeleteEnvironmentVariableV2", "DeleteGatewayResponseTypeV2", "DeleteGatewayResponseV2", "DeleteInstancesV2", "DeleteMemberGroup", "DeletePlugin", "DeleteRequestThrottlingPolicy", "DeleteRequestThrottlingPolicyV2"]

[lib]
name = "huawei_cloud_api_definitions_APIG"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-APIG"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
