#[cfg(feature = "AttachExtServerVolume")]
pub mod AttachExtServerVolume;
#[cfg(feature = "AttachExtSharedVolume")]
pub mod AttachExtSharedVolume;
#[cfg(feature = "AttachServerInterface")]
pub mod AttachServerInterface;
#[cfg(feature = "AttachServerVolume")]
pub mod AttachServerVolume;
#[cfg(feature = "BatchAddExtServerNics")]
pub mod BatchAddExtServerNics;
#[cfg(feature = "BatchDeleteExtServerNics")]
pub mod BatchDeleteExtServerNics;
#[cfg(feature = "BatchExecuteExtServerTags")]
pub mod BatchExecuteExtServerTags;
#[cfg(feature = "BatchResetExtServersPwd")]
pub mod BatchResetExtServersPwd;
#[cfg(feature = "BatchResizeExtLiveServer")]
pub mod BatchResizeExtLiveServer;
#[cfg(feature = "BatchResizeExtServer")]
pub mod BatchResizeExtServer;
#[cfg(feature = "BatchUpdateExtServersName")]
pub mod BatchUpdateExtServersName;
#[cfg(feature = "CloneExtServer")]
pub mod CloneExtServer;
#[cfg(feature = "CreateAggregate")]
pub mod CreateAggregate;
#[cfg(feature = "CreateExtServerGroup")]
pub mod CreateExtServerGroup;
#[cfg(feature = "CreateExtServers")]
pub mod CreateExtServers;
#[cfg(feature = "CreateFloatingIp")]
pub mod CreateFloatingIp;
#[cfg(feature = "CreateKeypair")]
pub mod CreateKeypair;
#[cfg(feature = "CreateSecurityGroup")]
pub mod CreateSecurityGroup;
#[cfg(feature = "CreateSecurityRule")]
pub mod CreateSecurityRule;
#[cfg(feature = "CreateServers")]
pub mod CreateServers;
#[cfg(feature = "CreateVolume")]
pub mod CreateVolume;
#[cfg(feature = "DeleteAggregate")]
pub mod DeleteAggregate;
#[cfg(feature = "DeleteExtServerGroup")]
pub mod DeleteExtServerGroup;
#[cfg(feature = "DeleteExtServerMetaItem")]
pub mod DeleteExtServerMetaItem;
#[cfg(feature = "DeleteExtServerPassword")]
pub mod DeleteExtServerPassword;
#[cfg(feature = "DeleteExtServers")]
pub mod DeleteExtServers;
#[cfg(feature = "DeleteFloatingIp")]
pub mod DeleteFloatingIp;
#[cfg(feature = "DeleteInstanceSnapshot")]
pub mod DeleteInstanceSnapshot;
#[cfg(feature = "DeleteKeypair")]
pub mod DeleteKeypair;
#[cfg(feature = "DeleteSecurityRule")]
pub mod DeleteSecurityRule;
#[cfg(feature = "DeleteServerMetaItem")]
pub mod DeleteServerMetaItem;
#[cfg(feature = "DeleteServerTag")]
pub mod DeleteServerTag;
#[cfg(feature = "DeleteServerTags")]
pub mod DeleteServerTags;
#[cfg(feature = "DeleteVolume")]
pub mod DeleteVolume;
#[cfg(feature = "DetachExtServerVolume")]
pub mod DetachExtServerVolume;
#[cfg(feature = "DetachServerInterface")]
pub mod DetachServerInterface;
#[cfg(feature = "ExecuteAggregateAction")]
pub mod ExecuteAggregateAction;
#[cfg(feature = "ExecuteExtServerAction")]
pub mod ExecuteExtServerAction;
#[cfg(feature = "ExecuteServerAction")]
pub mod ExecuteServerAction;
#[cfg(feature = "ExecuteServerChangeOs")]
pub mod ExecuteServerChangeOs;
#[cfg(feature = "ExecuteServerMonitor")]
pub mod ExecuteServerMonitor;
#[cfg(feature = "ExecuteServerReinstallOs")]
pub mod ExecuteServerReinstallOs;
#[cfg(feature = "ListAggregates")]
pub mod ListAggregates;
#[cfg(feature = "ListApiVersions")]
pub mod ListApiVersions;
#[cfg(feature = "ListAvailabilityZone")]
pub mod ListAvailabilityZone;
#[cfg(feature = "ListExtAvailabilityZoneDetail")]
pub mod ListExtAvailabilityZoneDetail;
#[cfg(feature = "ListExtFlavors")]
pub mod ListExtFlavors;
#[cfg(feature = "ListExtHypervisorsDetail")]
pub mod ListExtHypervisorsDetail;
#[cfg(feature = "ListExtResizeFlavors")]
pub mod ListExtResizeFlavors;
#[cfg(feature = "ListExtServerGroups")]
pub mod ListExtServerGroups;
#[cfg(feature = "ListExtServers")]
pub mod ListExtServers;
#[cfg(feature = "ListExtServersDetails")]
pub mod ListExtServersDetails;
#[cfg(feature = "ListExtServerVolumeAttachments")]
pub mod ListExtServerVolumeAttachments;
#[cfg(feature = "ListFloatingIpPools")]
pub mod ListFloatingIpPools;
#[cfg(feature = "ListFloatingIps")]
pub mod ListFloatingIps;
#[cfg(feature = "ListHypervisors")]
pub mod ListHypervisors;
#[cfg(feature = "ListImageDetails")]
pub mod ListImageDetails;
#[cfg(feature = "ListImages")]
pub mod ListImages;
#[cfg(feature = "ListKeypairs")]
pub mod ListKeypairs;
#[cfg(feature = "ListNetworks")]
pub mod ListNetworks;
#[cfg(feature = "ListSecurityGroups")]
pub mod ListSecurityGroups;
#[cfg(feature = "ListServerActions")]
pub mod ListServerActions;
#[cfg(feature = "ListServerDiskInfos")]
pub mod ListServerDiskInfos;
#[cfg(feature = "ListServerIPs")]
pub mod ListServerIPs;
#[cfg(feature = "ListServers")]
pub mod ListServers;
#[cfg(feature = "ListServersdetails")]
pub mod ListServersdetails;
#[cfg(feature = "ListServerSecurityGroup")]
pub mod ListServerSecurityGroup;
#[cfg(feature = "ListServerTags")]
pub mod ListServerTags;
#[cfg(feature = "ListVolumes")]
pub mod ListVolumes;
#[cfg(feature = "ListVolumesDetails")]
pub mod ListVolumesDetails;
#[cfg(feature = "ModifyExtServerGroupMember")]
pub mod ModifyExtServerGroupMember;
#[cfg(feature = "NovaClearWindowsServerPassword")]
pub mod NovaClearWindowsServerPassword;
#[cfg(feature = "NovaCreateFlavor")]
pub mod NovaCreateFlavor;
#[cfg(feature = "NovaCreateServerGroup")]
pub mod NovaCreateServerGroup;
#[cfg(feature = "NovaCreateSnapshot")]
pub mod NovaCreateSnapshot;
#[cfg(feature = "NovaDeleteFlavor")]
pub mod NovaDeleteFlavor;
#[cfg(feature = "NovaDeleteImage")]
pub mod NovaDeleteImage;
#[cfg(feature = "NovaDeleteSecurutyGroup")]
pub mod NovaDeleteSecurutyGroup;
#[cfg(feature = "NovaDeleteServer")]
pub mod NovaDeleteServer;
#[cfg(feature = "NovaDeleteServerGroup")]
pub mod NovaDeleteServerGroup;
#[cfg(feature = "NovaDeleteSnapshot")]
pub mod NovaDeleteSnapshot;
#[cfg(feature = "NovaDetachServerVolume")]
pub mod NovaDetachServerVolume;
#[cfg(feature = "NovaListFlavors")]
pub mod NovaListFlavors;
#[cfg(feature = "NovaListFlavorsDetail")]
pub mod NovaListFlavorsDetail;
#[cfg(feature = "NovaListServerGroups")]
pub mod NovaListServerGroups;
#[cfg(feature = "NovaListServerInterfaces")]
pub mod NovaListServerInterfaces;
#[cfg(feature = "NovaSetFlavorExtraSpecs")]
pub mod NovaSetFlavorExtraSpecs;
#[cfg(feature = "NovaShowApiVersion")]
pub mod NovaShowApiVersion;
#[cfg(feature = "NovaShowFlavor")]
pub mod NovaShowFlavor;
#[cfg(feature = "NovaShowFlavorExtraSpecs")]
pub mod NovaShowFlavorExtraSpecs;
#[cfg(feature = "NovaShowServerGroupDetail")]
pub mod NovaShowServerGroupDetail;
#[cfg(feature = "NovaShowServerInterfaceDetail")]
pub mod NovaShowServerInterfaceDetail;
#[cfg(feature = "NovaShowServerVolume")]
pub mod NovaShowServerVolume;
#[cfg(feature = "NovaShowSnapshot")]
pub mod NovaShowSnapshot;
#[cfg(feature = "NovaShowTenantQuotas")]
pub mod NovaShowTenantQuotas;
#[cfg(feature = "NovaShowWindowsServerPassword")]
pub mod NovaShowWindowsServerPassword;
#[cfg(feature = "ResetExtServerPwd")]
pub mod ResetExtServerPwd;
#[cfg(feature = "ResizeExtLiveServer")]
pub mod ResizeExtLiveServer;
#[cfg(feature = "ResizeExtServer")]
pub mod ResizeExtServer;
#[cfg(feature = "SetExtServerAutoRecovery")]
pub mod SetExtServerAutoRecovery;
