[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddTagToAsset = []
AddWorkSpaceUsers = []
AssociateClassificationToEntity = []
AssociateSecurityLevelToEntitie = []
AuthorizeActionApiToInstance = []
AuthorizeApiToInstance = []
BatchApproveApply = []
BatchAssociateClassificationToEntities = []
BatchAssociateSecurityLevelToEntities = []
BatchDeleteSecurityDataClassificationRule = []
BatchDeleteSecurityPermissionSetMembers = []
BatchDeleteSecurityPermissionSetPermissions = []
BatchDeleteTemplates = []
BatchOffline = []
BatchPublish = []
BatchSyncMetadata = []
ChangeCatalog = []
ChangeResource = []
ChangeSubjects = []
CheckDimensionStatus = []
CheckFactLogicTableStatus = []
ConfirmApprovals = []
ConfirmMessage = []
CountAllModels = []
CountOverviews = []
CountStandards = []
CountTableModels = []
CreateApi = []
CreateApp = []
CreateApprover = []
CreateBizMetric = []
CreateCatalog = []
CreateCodeTable = []
CreateConnections = []
CreateDirectory = []
CreateFactoryJob = []
CreateFactorySupplementDataInstance = []
CreateManagerWorkSpace = []
CreateOrUpdateAsset = []
CreateSecurityDataClassificationRule = []
CreateSecurityPermissionSet = []
CreateSecurityPermissionSetMember = []
CreateSecurityPermissionSetPermission = []
CreateServiceCatalog = []
CreateStandard = []
CreateStandardTemplate = []
CreateSubject = []
CreateSubjectNew = []
CreateTableModel = []
CreateTask = []
CreateTemplate = []
CreateWorkspace = []
DebugApi = []
DebugDataconnection = []
DeleteApi = []
DeleteApp = []
DeleteApprover = []
DeleteAsset = []
DeleteBizMetric = []
DeleteCatalog = []
DeleteClassificationFromEntities = []
DeleteCodeTable = []
DeleteDataconnection = []
DeleteDirectory = []
DeleteSecurityDataClassificationRule = []
DeleteSecurityLevelFromEntity = []
DeleteSecurityPermissionSet = []
DeleteServiceCatalog = []
DeleteStandard = []
DeleteStandardTemplate = []
DeleteSubject = []
DeleteSubjectNew = []
DeleteTableModel = []
DeleteTaskInfo = []
DeleteWorkspaces = []
DeleteWorkspaceusers = []
ExecuteApiToInstance = []
ExecuteTaskAction = []
ImportCatalogs = []
ImportLineage = []
ImportModels = []
ImportResult = []
InitializeStandardTemplate = []
ListAggregationLogicTables = []
ListAllCatalogList = []
ListAllStandards = []
ListAllTables = []
ListApiCatalogList = []
ListApiTopN = []
ListApicGroups = []
ListApicInstances = []
ListApis = []
ListApisTop = []
ListApply = []
ListApprovers = []
ListApps = []
ListAppsTop = []
ListBizMetricDimensions = []
ListBizMetricOwners = []
ListBizMetrics = []
full = ["AddTagToAsset", "AddWorkSpaceUsers", "AssociateClassificationToEntity", "AssociateSecurityLevelToEntitie", "AuthorizeActionApiToInstance", "AuthorizeApiToInstance", "BatchApproveApply", "BatchAssociateClassificationToEntities", "BatchAssociateSecurityLevelToEntities", "BatchDeleteSecurityDataClassificationRule", "BatchDeleteSecurityPermissionSetMembers", "BatchDeleteSecurityPermissionSetPermissions", "BatchDeleteTemplates", "BatchOffline", "BatchPublish", "BatchSyncMetadata", "ChangeCatalog", "ChangeResource", "ChangeSubjects", "CheckDimensionStatus", "CheckFactLogicTableStatus", "ConfirmApprovals", "ConfirmMessage", "CountAllModels", "CountOverviews", "CountStandards", "CountTableModels", "CreateApi", "CreateApp", "CreateApprover", "CreateBizMetric", "CreateCatalog", "CreateCodeTable", "CreateConnections", "CreateDirectory", "CreateFactoryJob", "CreateFactorySupplementDataInstance", "CreateManagerWorkSpace", "CreateOrUpdateAsset", "CreateSecurityDataClassificationRule", "CreateSecurityPermissionSet", "CreateSecurityPermissionSetMember", "CreateSecurityPermissionSetPermission", "CreateServiceCatalog", "CreateStandard", "CreateStandardTemplate", "CreateSubject", "CreateSubjectNew", "CreateTableModel", "CreateTask", "CreateTemplate", "CreateWorkspace", "DebugApi", "DebugDataconnection", "DeleteApi", "DeleteApp", "DeleteApprover", "DeleteAsset", "DeleteBizMetric", "DeleteCatalog", "DeleteClassificationFromEntities", "DeleteCodeTable", "DeleteDataconnection", "DeleteDirectory", "DeleteSecurityDataClassificationRule", "DeleteSecurityLevelFromEntity", "DeleteSecurityPermissionSet", "DeleteServiceCatalog", "DeleteStandard", "DeleteStandardTemplate", "DeleteSubject", "DeleteSubjectNew", "DeleteTableModel", "DeleteTaskInfo", "DeleteWorkspaces", "DeleteWorkspaceusers", "ExecuteApiToInstance", "ExecuteTaskAction", "ImportCatalogs", "ImportLineage", "ImportModels", "ImportResult", "InitializeStandardTemplate", "ListAggregationLogicTables", "ListAllCatalogList", "ListAllStandards", "ListAllTables", "ListApiCatalogList", "ListApicGroups", "ListApicInstances", "ListApis", "ListApisTop", "ListApiTopN", "ListApply", "ListApprovers", "ListApps", "ListAppsTop", "ListBizMetricDimensions", "ListBizMetricOwners", "ListBizMetrics"]

[lib]
name = "huawei_cloud_api_definitions_DataArtsStudio"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-DataArtsStudio"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "0.1.1"
