[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddDesignEntityTags = []
AddTagToAsset = []
AddWorkSpaceUsers = []
AssociateClassificationToEntity = []
AssociateSecurityLevelToEntitie = []
AuthorizeActionApiToInstance = []
AuthorizeApiToInstance = []
BatchApproveApply = []
BatchAssociateClassificationToEntities = []
BatchAssociateSecurityLevelToEntities = []
BatchDeleteSecurityDataClassificationRule = []
BatchDeleteSecurityPermissionSetMembers = []
BatchDeleteSecurityPermissionSetPermissions = []
BatchDeleteSecuritySecrecyLevels = []
BatchDeleteTemplates = []
BatchOffline = []
BatchPublish = []
BatchSyncMetadata = []
BatchUpdateSecurityDlfDataWareHouses = []
CancelFactoryPackages = []
ChangeCatalog = []
ChangeResource = []
ChangeSubjects = []
CheckDimensionStatus = []
CheckFactLogicTableStatus = []
ConfirmApprovals = []
ConfirmMessage = []
CountAllModels = []
CountOverviews = []
CountStandards = []
CountTableModels = []
CreateApi = []
CreateApp = []
CreateApprover = []
CreateBizMetric = []
CreateCatalog = []
CreateCodeTable = []
CreateConnections = []
CreateDesignAggregationLogicTable = []
CreateDesignAtomicIndex = []
CreateDirectory = []
CreateFactorySupplementDataInstance = []
CreateManagerWorkSpace = []
CreateOrUpdateAsset = []
CreateOrUpdateEntities = []
CreateSecurityDataClassificationRule = []
CreateSecurityPermissionSet = []
CreateSecurityPermissionSetMember = []
CreateSecurityPermissionSetPermission = []
CreateSecuritySecrecyLevel = []
CreateServiceCatalog = []
CreateStandard = []
CreateStandardTemplate = []
CreateSubject = []
CreateSubjectNew = []
CreateTableModel = []
CreateTask = []
CreateTemplate = []
CreateWorkspace = []
DebugApi = []
DebugDataconnection = []
DebugSecurityDlfDataWareHouses = []
DeleteApi = []
DeleteApp = []
DeleteApprover = []
DeleteAsset = []
DeleteBizMetric = []
DeleteCatalog = []
DeleteClassificationFromEntities = []
DeleteCodeTable = []
DeleteDataconnection = []
DeleteDesignAggregationLogicTable = []
DeleteDesignAtomicIndex = []
DeleteDesignLatestApproval = []
DeleteDirectory = []
DeleteSecurityDataClassificationRule = []
DeleteSecurityLevelFromEntity = []
DeleteSecurityPermissionSet = []
DeleteSecuritySecrecyLevel = []
DeleteServiceCatalog = []
DeleteStandard = []
DeleteStandardTemplate = []
DeleteSubject = []
DeleteSubjectNew = []
DeleteTableModel = []
DeleteTaskInfo = []
DeleteWorkspaces = []
DeleteWorkspaceusers = []
DeployFactoryPackages = []
ExecuteApiToInstance = []
ExecuteTaskAction = []
ExportDesignModelTableDdl = []
ExportDesignModels = []
ExportDesignResult = []
ImportCatalogs = []
ImportLineage = []
ImportModels = []
ImportResult = []
InitializeStandardTemplate = []
ListAggregationLogicTables = []
full = ["AddDesignEntityTags", "AddTagToAsset", "AddWorkSpaceUsers", "AssociateClassificationToEntity", "AssociateSecurityLevelToEntitie", "AuthorizeActionApiToInstance", "AuthorizeApiToInstance", "BatchApproveApply", "BatchAssociateClassificationToEntities", "BatchAssociateSecurityLevelToEntities", "BatchDeleteSecurityDataClassificationRule", "BatchDeleteSecurityPermissionSetMembers", "BatchDeleteSecurityPermissionSetPermissions", "BatchDeleteSecuritySecrecyLevels", "BatchDeleteTemplates", "BatchOffline", "BatchPublish", "BatchSyncMetadata", "BatchUpdateSecurityDlfDataWareHouses", "CancelFactoryPackages", "ChangeCatalog", "ChangeResource", "ChangeSubjects", "CheckDimensionStatus", "CheckFactLogicTableStatus", "ConfirmApprovals", "ConfirmMessage", "CountAllModels", "CountOverviews", "CountStandards", "CountTableModels", "CreateApi", "CreateApp", "CreateApprover", "CreateBizMetric", "CreateCatalog", "CreateCodeTable", "CreateConnections", "CreateDesignAggregationLogicTable", "CreateDesignAtomicIndex", "CreateDirectory", "CreateFactorySupplementDataInstance", "CreateManagerWorkSpace", "CreateOrUpdateAsset", "CreateOrUpdateEntities", "CreateSecurityDataClassificationRule", "CreateSecurityPermissionSet", "CreateSecurityPermissionSetMember", "CreateSecurityPermissionSetPermission", "CreateSecuritySecrecyLevel", "CreateServiceCatalog", "CreateStandard", "CreateStandardTemplate", "CreateSubject", "CreateSubjectNew", "CreateTableModel", "CreateTask", "CreateTemplate", "CreateWorkspace", "DebugApi", "DebugDataconnection", "DebugSecurityDlfDataWareHouses", "DeleteApi", "DeleteApp", "DeleteApprover", "DeleteAsset", "DeleteBizMetric", "DeleteCatalog", "DeleteClassificationFromEntities", "DeleteCodeTable", "DeleteDataconnection", "DeleteDesignAggregationLogicTable", "DeleteDesignAtomicIndex", "DeleteDesignLatestApproval", "DeleteDirectory", "DeleteSecurityDataClassificationRule", "DeleteSecurityLevelFromEntity", "DeleteSecurityPermissionSet", "DeleteSecuritySecrecyLevel", "DeleteServiceCatalog", "DeleteStandard", "DeleteStandardTemplate", "DeleteSubject", "DeleteSubjectNew", "DeleteTableModel", "DeleteTaskInfo", "DeleteWorkspaces", "DeleteWorkspaceusers", "DeployFactoryPackages", "ExecuteApiToInstance", "ExecuteTaskAction", "ExportDesignModels", "ExportDesignModelTableDdl", "ExportDesignResult", "ImportCatalogs", "ImportLineage", "ImportModels", "ImportResult", "InitializeStandardTemplate", "ListAggregationLogicTables"]

[lib]
name = "huawei_cloud_api_definitions_DataArtsStudio"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-DataArtsStudio"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
