#[cfg(feature = "AddEmailTemplate")]
pub mod AddEmailTemplate;
#[cfg(feature = "AddFullSqlTask")]
pub mod AddFullSqlTask;
#[cfg(feature = "AddInstanceGroup")]
pub mod AddInstanceGroup;
#[cfg(feature = "AddInstanceToGroup")]
pub mod AddInstanceToGroup;
#[cfg(feature = "AddSqlLimitingRecordNew")]
pub mod AddSqlLimitingRecordNew;
#[cfg(feature = "AddTasksNew")]
pub mod AddTasksNew;
#[cfg(feature = "BatchAddFullSqlTasks")]
pub mod BatchAddFullSqlTasks;
#[cfg(feature = "BatchDeleteConnectionNew")]
pub mod BatchDeleteConnectionNew;
#[cfg(feature = "BatchSendEmail")]
pub mod BatchSendEmail;
#[cfg(feature = "BatchSetSqlSwitchNew")]
pub mod BatchSetSqlSwitchNew;
#[cfg(feature = "BatchSubscribeReport")]
pub mod BatchSubscribeReport;
#[cfg(feature = "CancelConnectionProcess")]
pub mod CancelConnectionProcess;
#[cfg(feature = "CancelShareConnections")]
pub mod CancelShareConnections;
#[cfg(feature = "CancelShareNew")]
pub mod CancelShareNew;
#[cfg(feature = "ChangeChargeMode")]
pub mod ChangeChargeMode;
#[cfg(feature = "ChangeDeadLockSwitchNew")]
pub mod ChangeDeadLockSwitchNew;
#[cfg(feature = "ChangeFullDeadLockSwitch")]
pub mod ChangeFullDeadLockSwitch;
#[cfg(feature = "ChangePaymentModeNew")]
pub mod ChangePaymentModeNew;
#[cfg(feature = "ChangeQuotaNew")]
pub mod ChangeQuotaNew;
#[cfg(feature = "ChangeSqlLimitSwitchStatus")]
pub mod ChangeSqlLimitSwitchStatus;
#[cfg(feature = "ChangeSqlSwitch")]
pub mod ChangeSqlSwitch;
#[cfg(feature = "ChangeTransactionSwitchStatus")]
pub mod ChangeTransactionSwitchStatus;
#[cfg(feature = "CheckCredential")]
pub mod CheckCredential;
#[cfg(feature = "CheckCredentialForBatchInspection")]
pub mod CheckCredentialForBatchInspection;
#[cfg(feature = "CheckHealthReportTask")]
pub mod CheckHealthReportTask;
#[cfg(feature = "CreateBinlogTask")]
pub mod CreateBinlogTask;
#[cfg(feature = "CreateDbsConnection")]
pub mod CreateDbsConnection;
#[cfg(feature = "CreateFullSqlBucket")]
pub mod CreateFullSqlBucket;
#[cfg(feature = "CreateHealthReportTask")]
pub mod CreateHealthReportTask;
#[cfg(feature = "CreateHistoryTransactionExportTask")]
pub mod CreateHistoryTransactionExportTask;
#[cfg(feature = "CreateIndexUsageExportTaskNew")]
pub mod CreateIndexUsageExportTaskNew;
#[cfg(feature = "CreateInstanceConnection")]
pub mod CreateInstanceConnection;
#[cfg(feature = "CreateInstanceHealthReportTaskNew")]
pub mod CreateInstanceHealthReportTaskNew;
#[cfg(feature = "CreateShareConnections")]
pub mod CreateShareConnections;
#[cfg(feature = "CreateSnapshots")]
pub mod CreateSnapshots;
#[cfg(feature = "CreateSpaceAnalysisTask")]
pub mod CreateSpaceAnalysisTask;
#[cfg(feature = "CreateSqlLimitRules")]
pub mod CreateSqlLimitRules;
#[cfg(feature = "CreateTuning")]
pub mod CreateTuning;
#[cfg(feature = "CreateWdrReport")]
pub mod CreateWdrReport;
#[cfg(feature = "DeleteBinlogTask")]
pub mod DeleteBinlogTask;
#[cfg(feature = "DeleteDbObjNew")]
pub mod DeleteDbObjNew;
#[cfg(feature = "DeleteDbUser")]
pub mod DeleteDbUser;
#[cfg(feature = "DeleteEmailTemplate")]
pub mod DeleteEmailTemplate;
#[cfg(feature = "DeleteExportTaskNew")]
pub mod DeleteExportTaskNew;
#[cfg(feature = "DeleteFullSqlExportTaskObsFile")]
pub mod DeleteFullSqlExportTaskObsFile;
#[cfg(feature = "DeleteHistoryTransactionExportTask")]
pub mod DeleteHistoryTransactionExportTask;
#[cfg(feature = "DeleteInstanceGroup")]
pub mod DeleteInstanceGroup;
#[cfg(feature = "DeleteProcess")]
pub mod DeleteProcess;
#[cfg(feature = "DeleteSqlLimitRules")]
pub mod DeleteSqlLimitRules;
#[cfg(feature = "EnableQuota")]
pub mod EnableQuota;
#[cfg(feature = "ExecuteExportTask")]
pub mod ExecuteExportTask;
#[cfg(feature = "ExecuteFormatSql")]
pub mod ExecuteFormatSql;
#[cfg(feature = "ExecuteImportTask")]
pub mod ExecuteImportTask;
#[cfg(feature = "ExecuteLoginConnectionNew")]
pub mod ExecuteLoginConnectionNew;
#[cfg(feature = "ExecuteSplitSql")]
pub mod ExecuteSplitSql;
#[cfg(feature = "ExecuteTestConnectionNew")]
pub mod ExecuteTestConnectionNew;
#[cfg(feature = "ExecuteTuning")]
pub mod ExecuteTuning;
#[cfg(feature = "ExportFullSqlDetails")]
pub mod ExportFullSqlDetails;
#[cfg(feature = "ExportInstanceListNew")]
pub mod ExportInstanceListNew;
#[cfg(feature = "ExportSlowQueryLogs")]
pub mod ExportSlowQueryLogs;
#[cfg(feature = "ExportSlowSqlStatistics")]
pub mod ExportSlowSqlStatistics;
#[cfg(feature = "ExportSlowSqlTemplatesDetails")]
pub mod ExportSlowSqlTemplatesDetails;
#[cfg(feature = "ExportSlowSqlTrendDetails")]
pub mod ExportSlowSqlTrendDetails;
#[cfg(feature = "ExportSqlStatements")]
pub mod ExportSqlStatements;
#[cfg(feature = "ExportTopRiskInstances")]
pub mod ExportTopRiskInstances;
#[cfg(feature = "ExportTopSqlTemplatesDetails")]
pub mod ExportTopSqlTemplatesDetails;
#[cfg(feature = "ExportTopSqlTrendDetails")]
pub mod ExportTopSqlTrendDetails;
#[cfg(feature = "ImportExportObsObjects")]
pub mod ImportExportObsObjects;
#[cfg(feature = "InvokeWdrReport")]
pub mod InvokeWdrReport;
#[cfg(feature = "ListAllTypeInstances")]
pub mod ListAllTypeInstances;
#[cfg(feature = "ListApiVersions")]
pub mod ListApiVersions;
#[cfg(feature = "ListAutoIncrementUsage")]
pub mod ListAutoIncrementUsage;
#[cfg(feature = "ListBinlogExports")]
pub mod ListBinlogExports;
#[cfg(feature = "ListBinlogFiles")]
pub mod ListBinlogFiles;
#[cfg(feature = "ListCloudDbaInstances")]
pub mod ListCloudDbaInstances;
#[cfg(feature = "ListConnectionProcesses")]
pub mod ListConnectionProcesses;
#[cfg(feature = "ListConnections")]
pub mod ListConnections;
#[cfg(feature = "ListDatabaseObjects")]
pub mod ListDatabaseObjects;
#[cfg(feature = "ListDbNames")]
pub mod ListDbNames;
#[cfg(feature = "ListDbUsers")]
pub mod ListDbUsers;
#[cfg(feature = "ListDeadLockDatabases")]
pub mod ListDeadLockDatabases;
#[cfg(feature = "ListDeadLockDetail")]
pub mod ListDeadLockDetail;
#[cfg(feature = "ListEmailRecord")]
pub mod ListEmailRecord;
#[cfg(feature = "ListEmailTemplate")]
pub mod ListEmailTemplate;
#[cfg(feature = "ListFullDeadLocks")]
pub mod ListFullDeadLocks;
#[cfg(feature = "ListFullSqlExportTasks")]
pub mod ListFullSqlExportTasks;
#[cfg(feature = "ListFullSqlTasks")]
pub mod ListFullSqlTasks;
#[cfg(feature = "ListHealthReportTask")]
pub mod ListHealthReportTask;
#[cfg(feature = "ListHistoryTransactionExportTask")]
pub mod ListHistoryTransactionExportTask;
#[cfg(feature = "ListInnodbLocks")]
pub mod ListInnodbLocks;
#[cfg(feature = "ListInspectionReport")]
pub mod ListInspectionReport;
#[cfg(feature = "ListInstanceDistribution")]
pub mod ListInstanceDistribution;
#[cfg(feature = "ListInstanceGroup")]
pub mod ListInstanceGroup;
#[cfg(feature = "ListInstanceHealthReportTasks")]
pub mod ListInstanceHealthReportTasks;
#[cfg(feature = "ListInstanceMultiNodesSingleMetric")]
pub mod ListInstanceMultiNodesSingleMetric;
#[cfg(feature = "ListInstanceNodesInfo")]
pub mod ListInstanceNodesInfo;
#[cfg(feature = "ListInstanceTopSlowLog")]
pub mod ListInstanceTopSlowLog;
#[cfg(feature = "ListLockBlockingDb")]
pub mod ListLockBlockingDb;
#[cfg(feature = "ListLockBlockingDetail")]
pub mod ListLockBlockingDetail;
#[cfg(feature = "ListLockBlockingRelationship")]
pub mod ListLockBlockingRelationship;
