#[cfg(feature = "AddEmailTemplate")]
pub mod AddEmailTemplate;
#[cfg(feature = "AddFullSqlTask")]
pub mod AddFullSqlTask;
#[cfg(feature = "AddInstanceGroup")]
pub mod AddInstanceGroup;
#[cfg(feature = "AddInstanceToGroup")]
pub mod AddInstanceToGroup;
#[cfg(feature = "AddSqlLimitingRecordNew")]
pub mod AddSqlLimitingRecordNew;
#[cfg(feature = "BatchDeleteConnectionNew")]
pub mod BatchDeleteConnectionNew;
#[cfg(feature = "BatchSendEmail")]
pub mod BatchSendEmail;
#[cfg(feature = "BatchSubscribeReport")]
pub mod BatchSubscribeReport;
#[cfg(feature = "CancelShareConnections")]
pub mod CancelShareConnections;
#[cfg(feature = "CancelShareNew")]
pub mod CancelShareNew;
#[cfg(feature = "ChangeChargeMode")]
pub mod ChangeChargeMode;
#[cfg(feature = "ChangeFullDeadLockSwitch")]
pub mod ChangeFullDeadLockSwitch;
#[cfg(feature = "ChangeSqlLimitSwitchStatus")]
pub mod ChangeSqlLimitSwitchStatus;
#[cfg(feature = "ChangeSqlSwitch")]
pub mod ChangeSqlSwitch;
#[cfg(feature = "ChangeTransactionSwitchStatus")]
pub mod ChangeTransactionSwitchStatus;
#[cfg(feature = "CheckCredential")]
pub mod CheckCredential;
#[cfg(feature = "CheckCredentialForBatchInspection")]
pub mod CheckCredentialForBatchInspection;
#[cfg(feature = "CreateHealthReportTask")]
pub mod CreateHealthReportTask;
#[cfg(feature = "CreateHistoryTransactionExportTask")]
pub mod CreateHistoryTransactionExportTask;
#[cfg(feature = "CreateInstanceConnection")]
pub mod CreateInstanceConnection;
#[cfg(feature = "CreateShareConnections")]
pub mod CreateShareConnections;
#[cfg(feature = "CreateSnapshots")]
pub mod CreateSnapshots;
#[cfg(feature = "CreateSpaceAnalysisTask")]
pub mod CreateSpaceAnalysisTask;
#[cfg(feature = "CreateSqlLimitRules")]
pub mod CreateSqlLimitRules;
#[cfg(feature = "CreateTuning")]
pub mod CreateTuning;
#[cfg(feature = "DeleteDbUser")]
pub mod DeleteDbUser;
#[cfg(feature = "DeleteEmailTemplate")]
pub mod DeleteEmailTemplate;
#[cfg(feature = "DeleteHistoryTransactionExportTask")]
pub mod DeleteHistoryTransactionExportTask;
#[cfg(feature = "DeleteInstanceGroup")]
pub mod DeleteInstanceGroup;
#[cfg(feature = "DeleteProcess")]
pub mod DeleteProcess;
#[cfg(feature = "DeleteSqlLimitRules")]
pub mod DeleteSqlLimitRules;
#[cfg(feature = "ExportFullSqlDetails")]
pub mod ExportFullSqlDetails;
#[cfg(feature = "ExportSlowQueryLogs")]
pub mod ExportSlowQueryLogs;
#[cfg(feature = "ExportSlowSqlStatistics")]
pub mod ExportSlowSqlStatistics;
#[cfg(feature = "ExportSlowSqlTemplatesDetails")]
pub mod ExportSlowSqlTemplatesDetails;
#[cfg(feature = "ExportSlowSqlTrendDetails")]
pub mod ExportSlowSqlTrendDetails;
#[cfg(feature = "ExportSqlStatements")]
pub mod ExportSqlStatements;
#[cfg(feature = "ExportTopRiskInstances")]
pub mod ExportTopRiskInstances;
#[cfg(feature = "ExportTopSqlTemplatesDetails")]
pub mod ExportTopSqlTemplatesDetails;
#[cfg(feature = "ExportTopSqlTrendDetails")]
pub mod ExportTopSqlTrendDetails;
#[cfg(feature = "ListApiVersions")]
pub mod ListApiVersions;
#[cfg(feature = "ListAutoIncrementUsage")]
pub mod ListAutoIncrementUsage;
#[cfg(feature = "ListCloudDbaInstances")]
pub mod ListCloudDbaInstances;
#[cfg(feature = "ListConnections")]
pub mod ListConnections;
#[cfg(feature = "ListDbNames")]
pub mod ListDbNames;
#[cfg(feature = "ListDbUsers")]
pub mod ListDbUsers;
#[cfg(feature = "ListEmailRecord")]
pub mod ListEmailRecord;
#[cfg(feature = "ListEmailTemplate")]
pub mod ListEmailTemplate;
#[cfg(feature = "ListFullSqlTasks")]
pub mod ListFullSqlTasks;
#[cfg(feature = "ListHealthReportTask")]
pub mod ListHealthReportTask;
#[cfg(feature = "ListHistoryTransactionExportTask")]
pub mod ListHistoryTransactionExportTask;
#[cfg(feature = "ListInnodbLocks")]
pub mod ListInnodbLocks;
#[cfg(feature = "ListInspectionReport")]
pub mod ListInspectionReport;
#[cfg(feature = "ListInstanceDistribution")]
pub mod ListInstanceDistribution;
#[cfg(feature = "ListInstanceGroup")]
pub mod ListInstanceGroup;
#[cfg(feature = "ListInstanceMultiNodesSingleMetric")]
pub mod ListInstanceMultiNodesSingleMetric;
#[cfg(feature = "ListInstanceNodesInfo")]
pub mod ListInstanceNodesInfo;
#[cfg(feature = "ListInstanceTopSlowLog")]
pub mod ListInstanceTopSlowLog;
#[cfg(feature = "ListLockBlockingDb")]
pub mod ListLockBlockingDb;
#[cfg(feature = "ListLockBlockingDetail")]
pub mod ListLockBlockingDetail;
#[cfg(feature = "ListLockBlockingRelationship")]
pub mod ListLockBlockingRelationship;
#[cfg(feature = "ListMetadataLocks")]
pub mod ListMetadataLocks;
#[cfg(feature = "ListProcesses")]
pub mod ListProcesses;
#[cfg(feature = "ListRiskItems")]
pub mod ListRiskItems;
#[cfg(feature = "ListRiskTrend")]
pub mod ListRiskTrend;
#[cfg(feature = "ListSnapshots")]
pub mod ListSnapshots;
#[cfg(feature = "ListSpaceAnalysis")]
pub mod ListSpaceAnalysis;
#[cfg(feature = "ListSqlLimitRules")]
pub mod ListSqlLimitRules;
#[cfg(feature = "ListTopSlowLog")]
pub mod ListTopSlowLog;
#[cfg(feature = "ListTransactions")]
pub mod ListTransactions;
#[cfg(feature = "LoginBuiltInAccount")]
pub mod LoginBuiltInAccount;
#[cfg(feature = "LogoffBuiltInAccount")]
pub mod LogoffBuiltInAccount;
#[cfg(feature = "ParseDeadLock")]
pub mod ParseDeadLock;
#[cfg(feature = "ParseSqlLimitRules")]
pub mod ParseSqlLimitRules;
#[cfg(feature = "RegisterDbUser")]
pub mod RegisterDbUser;
#[cfg(feature = "SaveCredential")]
pub mod SaveCredential;
#[cfg(feature = "SaveCredentialForBatchInspection")]
pub mod SaveCredentialForBatchInspection;
#[cfg(feature = "SetLockBlockingSwitch")]
pub mod SetLockBlockingSwitch;
#[cfg(feature = "SetThresholdForMetric")]
pub mod SetThresholdForMetric;
#[cfg(feature = "ShowAnalysisSessionResult")]
pub mod ShowAnalysisSessionResult;
#[cfg(feature = "ShowAnalysisSessionStatus")]
pub mod ShowAnalysisSessionStatus;
#[cfg(feature = "ShowApiVersion")]
pub mod ShowApiVersion;
#[cfg(feature = "ShowClouddbaGetSearchPathFlagNew")]
pub mod ShowClouddbaGetSearchPathFlagNew;
#[cfg(feature = "ShowCredential")]
pub mod ShowCredential;
#[cfg(feature = "ShowDasCloudDbaPrice")]
pub mod ShowDasCloudDbaPrice;
#[cfg(feature = "ShowDasRecommendSqlLimitRule")]
pub mod ShowDasRecommendSqlLimitRule;
#[cfg(feature = "ShowDbUser")]
pub mod ShowDbUser;
#[cfg(feature = "ShowDeadLockAnalysisResult")]
pub mod ShowDeadLockAnalysisResult;
#[cfg(feature = "ShowDeadLockSwitchNew")]
pub mod ShowDeadLockSwitchNew;
#[cfg(feature = "ShowDeadLockTopology")]
pub mod ShowDeadLockTopology;
#[cfg(feature = "ShowExportTaskInfo")]
pub mod ShowExportTaskInfo;
#[cfg(feature = "ShowFullDeadLockList")]
pub mod ShowFullDeadLockList;
#[cfg(feature = "ShowFullDeadLockSwitch")]
pub mod ShowFullDeadLockSwitch;
#[cfg(feature = "ShowFullDeadLockSwitchNew")]
pub mod ShowFullDeadLockSwitchNew;
#[cfg(feature = "ShowGlobalPrivacyNew")]
pub mod ShowGlobalPrivacyNew;
#[cfg(feature = "ShowHealthReportSettings")]
pub mod ShowHealthReportSettings;
#[cfg(feature = "ShowHistoryTransactionExportTaskInfo")]
pub mod ShowHistoryTransactionExportTaskInfo;
#[cfg(feature = "ShowHistoryTransactionSwitchNew")]
pub mod ShowHistoryTransactionSwitchNew;
#[cfg(feature = "ShowIndexUsageSwitchNew")]
pub mod ShowIndexUsageSwitchNew;
#[cfg(feature = "ShowInstanceHealthReport")]
pub mod ShowInstanceHealthReport;
