#[cfg(feature = "BatchCreateResourceTags")]
pub mod BatchCreateResourceTags;
#[cfg(feature = "BatchDeleteResourceTags")]
pub mod BatchDeleteResourceTags;
#[cfg(feature = "CheckObsBuckets")]
pub mod CheckObsBuckets;
#[cfg(feature = "CreateNotification")]
pub mod CreateNotification;
#[cfg(feature = "CreateTracker")]
pub mod CreateTracker;
#[cfg(feature = "DeleteNotification")]
pub mod DeleteNotification;
#[cfg(feature = "DeleteTracker")]
pub mod DeleteTracker;
#[cfg(feature = "ListNotifications")]
pub mod ListNotifications;
#[cfg(feature = "ListOperations")]
pub mod ListOperations;
#[cfg(feature = "ListQuotas")]
pub mod ListQuotas;
#[cfg(feature = "ListTraceResources")]
pub mod ListTraceResources;
#[cfg(feature = "ListTraces")]
pub mod ListTraces;
#[cfg(feature = "ListTrackers")]
pub mod ListTrackers;
#[cfg(feature = "ListUserResources")]
pub mod ListUserResources;
#[cfg(feature = "UpdateNotification")]
pub mod UpdateNotification;
#[cfg(feature = "UpdateTracker")]
pub mod UpdateTracker;
