[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
CreateAkskCertificate = []
CreateDeviceCertificate = []
CreateDeviceChannel = []
CreateStream = []
CreateSubscription = []
DeleteAkskCertificate = []
DeleteDevice = []
DeleteDeviceCertificate = []
DeleteStream = []
ListAkskCertificates = []
ListBucket = []
ListDevices = []
ListDevicesCertificates = []
ListLongTermOfflineDevices = []
ListNotSendDataDevices = []
ListNvrChannels = []
ListPastOnlineDevices = []
ListShortTermOfflineDevices = []
ListStreamInfos = []
ListStreams = []
ListStreamsAddresses = []
ListSubscriptions = []
ListTodayDroppedDevices = []
ListTodayNewOnlineDevices = []
ListTodayPacketReceivedRateDevices = []
UpdateAksk = []
UpdateAuthority = []
UpdateDeviceCertificate = []
UpdateDeviceChannel = []
UpdateDeviceChannelStrategy = []
UpdateNvrDeviceChannel = []
UpdateRetention = []
UpdateStream = []
full = ["CreateAkskCertificate", "CreateDeviceCertificate", "CreateDeviceChannel", "CreateStream", "CreateSubscription", "DeleteAkskCertificate", "DeleteDevice", "DeleteDeviceCertificate", "DeleteStream", "ListAkskCertificates", "ListBucket", "ListDevices", "ListDevicesCertificates", "ListLongTermOfflineDevices", "ListNotSendDataDevices", "ListNvrChannels", "ListPastOnlineDevices", "ListShortTermOfflineDevices", "ListStreamInfos", "ListStreams", "ListStreamsAddresses", "ListSubscriptions", "ListTodayDroppedDevices", "ListTodayNewOnlineDevices", "ListTodayPacketReceivedRateDevices", "UpdateAksk", "UpdateAuthority", "UpdateDeviceCertificate", "UpdateDeviceChannel", "UpdateDeviceChannelStrategy", "UpdateNvrDeviceChannel", "UpdateRetention", "UpdateStream"]

[lib]
name = "huawei_cloud_api_definitions_VIS"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-VIS"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "0.1.0"
