#[cfg(feature = "AddProtectedInstanceNic")]
pub mod AddProtectedInstanceNic;
#[cfg(feature = "AddProtectedInstanceTags")]
pub mod AddProtectedInstanceTags;
#[cfg(feature = "AttachProtectedInstanceReplication")]
pub mod AttachProtectedInstanceReplication;
#[cfg(feature = "BatchAddTags")]
pub mod BatchAddTags;
#[cfg(feature = "BatchCreateProtectedInstances")]
pub mod BatchCreateProtectedInstances;
#[cfg(feature = "BatchDeleteProtectedInstances")]
pub mod BatchDeleteProtectedInstances;
#[cfg(feature = "BatchDeleteTags")]
pub mod BatchDeleteTags;
#[cfg(feature = "CreateDisasterRecoveryDrill")]
pub mod CreateDisasterRecoveryDrill;
#[cfg(feature = "CreateProtectedInstance")]
pub mod CreateProtectedInstance;
#[cfg(feature = "CreateProtectionGroup")]
pub mod CreateProtectionGroup;
#[cfg(feature = "CreateReplication")]
pub mod CreateReplication;
#[cfg(feature = "DeleteAllServerGroupFailureJobs")]
pub mod DeleteAllServerGroupFailureJobs;
#[cfg(feature = "DeleteDisasterRecoveryDrill")]
pub mod DeleteDisasterRecoveryDrill;
#[cfg(feature = "DeleteFailureJob")]
pub mod DeleteFailureJob;
#[cfg(feature = "DeleteProtectedInstance")]
pub mod DeleteProtectedInstance;
#[cfg(feature = "DeleteProtectedInstanceNic")]
pub mod DeleteProtectedInstanceNic;
#[cfg(feature = "DeleteProtectedInstanceTag")]
pub mod DeleteProtectedInstanceTag;
#[cfg(feature = "DeleteProtectionGroup")]
pub mod DeleteProtectionGroup;
#[cfg(feature = "DeleteReplication")]
pub mod DeleteReplication;
#[cfg(feature = "DeleteServerGroupFailureJobs")]
pub mod DeleteServerGroupFailureJobs;
#[cfg(feature = "DetachProtectedInstanceReplication")]
pub mod DetachProtectedInstanceReplication;
#[cfg(feature = "ExpandReplication")]
pub mod ExpandReplication;
#[cfg(feature = "ListActiveActiveDomains")]
pub mod ListActiveActiveDomains;
#[cfg(feature = "ListApiVersions")]
pub mod ListApiVersions;
#[cfg(feature = "ListDisasterRecoveryDrills")]
pub mod ListDisasterRecoveryDrills;
#[cfg(feature = "ListFailureJobs")]
pub mod ListFailureJobs;
#[cfg(feature = "ListProtectedInstances")]
pub mod ListProtectedInstances;
#[cfg(feature = "ListProtectedInstancesByTags")]
pub mod ListProtectedInstancesByTags;
#[cfg(feature = "ListProtectedInstancesProjectTags")]
pub mod ListProtectedInstancesProjectTags;
#[cfg(feature = "ListProtectedInstanceTags")]
pub mod ListProtectedInstanceTags;
#[cfg(feature = "ListProtectionGroups")]
pub mod ListProtectionGroups;
#[cfg(feature = "ListReplications")]
pub mod ListReplications;
#[cfg(feature = "ListRpoStatistics")]
pub mod ListRpoStatistics;
#[cfg(feature = "ResizeProtectedInstance")]
pub mod ResizeProtectedInstance;
#[cfg(feature = "ShowDisasterRecoveryDrill")]
pub mod ShowDisasterRecoveryDrill;
#[cfg(feature = "ShowJobStatus")]
pub mod ShowJobStatus;
#[cfg(feature = "ShowProtectedInstance")]
pub mod ShowProtectedInstance;
#[cfg(feature = "ShowProtectionGroup")]
pub mod ShowProtectionGroup;
#[cfg(feature = "ShowQuota")]
pub mod ShowQuota;
#[cfg(feature = "ShowReplication")]
pub mod ShowReplication;
#[cfg(feature = "ShowSpecifiedApiVersion")]
pub mod ShowSpecifiedApiVersion;
#[cfg(feature = "StartFailoverProtectionGroup")]
pub mod StartFailoverProtectionGroup;
#[cfg(feature = "StartProtectionGroup")]
pub mod StartProtectionGroup;
#[cfg(feature = "StartReverseProtectionGroup")]
pub mod StartReverseProtectionGroup;
#[cfg(feature = "StopProtectionGroup")]
pub mod StopProtectionGroup;
#[cfg(feature = "UpdateDisasterRecoveryDrillName")]
pub mod UpdateDisasterRecoveryDrillName;
#[cfg(feature = "UpdateProtectedInstanceName")]
pub mod UpdateProtectedInstanceName;
#[cfg(feature = "UpdateProtectionGroupName")]
pub mod UpdateProtectionGroupName;
#[cfg(feature = "UpdateReplicationName")]
pub mod UpdateReplicationName;
