#[cfg(feature = "BatchCreateFabricWorkspaceTags")]
pub mod BatchCreateFabricWorkspaceTags;
#[cfg(feature = "BatchDeleteFabricWorkspaceTags")]
pub mod BatchDeleteFabricWorkspaceTags;
#[cfg(feature = "CleanupModel")]
pub mod CleanupModel;
#[cfg(feature = "CountTagFabricWorkspaces")]
pub mod CountTagFabricWorkspaces;
#[cfg(feature = "CreateAgency")]
pub mod CreateAgency;
#[cfg(feature = "CreateAgreement")]
pub mod CreateAgreement;
#[cfg(feature = "CreateEndpoint")]
pub mod CreateEndpoint;
#[cfg(feature = "CreateMessageNotificationPolicy")]
pub mod CreateMessageNotificationPolicy;
#[cfg(feature = "CreateModelDefinition")]
pub mod CreateModelDefinition;
#[cfg(feature = "CreateWorkspace")]
pub mod CreateWorkspace;
#[cfg(feature = "DeleteAgency")]
pub mod DeleteAgency;
#[cfg(feature = "DeleteAgreement")]
pub mod DeleteAgreement;
#[cfg(feature = "DeleteEndpoint")]
pub mod DeleteEndpoint;
#[cfg(feature = "DeleteMessageNotificationPolicy")]
pub mod DeleteMessageNotificationPolicy;
#[cfg(feature = "DeleteModelVersion")]
pub mod DeleteModelVersion;
#[cfg(feature = "DeleteWorkspace")]
pub mod DeleteWorkspace;
#[cfg(feature = "ListAgency")]
pub mod ListAgency;
#[cfg(feature = "ListBaseModels")]
pub mod ListBaseModels;
#[cfg(feature = "ListEndpoints")]
pub mod ListEndpoints;
#[cfg(feature = "ListFabricProjectTags")]
pub mod ListFabricProjectTags;
#[cfg(feature = "ListFabricWorkspaceTags")]
pub mod ListFabricWorkspaceTags;
#[cfg(feature = "ListFeatures")]
pub mod ListFeatures;
#[cfg(feature = "ListFrameworks")]
pub mod ListFrameworks;
#[cfg(feature = "ListMessageNotificationPolicy")]
pub mod ListMessageNotificationPolicy;
#[cfg(feature = "ListModels")]
pub mod ListModels;
#[cfg(feature = "ListModelVersions")]
pub mod ListModelVersions;
#[cfg(feature = "ListSpecs")]
pub mod ListSpecs;
#[cfg(feature = "ListTagFabricWorkspaces")]
pub mod ListTagFabricWorkspaces;
#[cfg(feature = "ListWorkspaces")]
pub mod ListWorkspaces;
#[cfg(feature = "ShowAdminHealthCheck")]
pub mod ShowAdminHealthCheck;
#[cfg(feature = "ShowAgreement")]
pub mod ShowAgreement;
#[cfg(feature = "ShowEndpoint")]
pub mod ShowEndpoint;
#[cfg(feature = "SubscribeEndpoint")]
pub mod SubscribeEndpoint;
#[cfg(feature = "UpdateEndpoint")]
pub mod UpdateEndpoint;
#[cfg(feature = "UpdateMetricsConfig")]
pub mod UpdateMetricsConfig;
#[cfg(feature = "UpdateModelDefinition")]
pub mod UpdateModelDefinition;
#[cfg(feature = "UpdateWorkspace")]
pub mod UpdateWorkspace;
