#[cfg(feature = "CancelAssetTranscodeTask")]
pub mod CancelAssetTranscodeTask;
#[cfg(feature = "CancelExtractAudioTask")]
pub mod CancelExtractAudioTask;
#[cfg(feature = "CheckMd5Duplication")]
pub mod CheckMd5Duplication;
#[cfg(feature = "ConfirmAssetUpload")]
pub mod ConfirmAssetUpload;
#[cfg(feature = "ConfirmImageUpload")]
pub mod ConfirmImageUpload;
#[cfg(feature = "CreateAssetByFileUpload")]
pub mod CreateAssetByFileUpload;
#[cfg(feature = "CreateAssetCategory")]
pub mod CreateAssetCategory;
#[cfg(feature = "CreateAssetProcessTask")]
pub mod CreateAssetProcessTask;
#[cfg(feature = "CreateAssetReviewTask")]
pub mod CreateAssetReviewTask;
#[cfg(feature = "CreateExtractAudioTask")]
pub mod CreateExtractAudioTask;
#[cfg(feature = "CreatePreheatingAsset")]
pub mod CreatePreheatingAsset;
#[cfg(feature = "CreateTakeOverTask")]
pub mod CreateTakeOverTask;
#[cfg(feature = "CreateTemplateGroup")]
pub mod CreateTemplateGroup;
#[cfg(feature = "CreateTemplateGroupCollection")]
pub mod CreateTemplateGroupCollection;
#[cfg(feature = "CreateTranscodeTemplate")]
pub mod CreateTranscodeTemplate;
#[cfg(feature = "CreateWatermarkTemplate")]
pub mod CreateWatermarkTemplate;
#[cfg(feature = "DeleteAssetCategory")]
pub mod DeleteAssetCategory;
#[cfg(feature = "DeleteAssets")]
pub mod DeleteAssets;
#[cfg(feature = "DeleteTemplateGroup")]
pub mod DeleteTemplateGroup;
#[cfg(feature = "DeleteTemplateGroupCollection")]
pub mod DeleteTemplateGroupCollection;
#[cfg(feature = "DeleteTranscodeTemplate")]
pub mod DeleteTranscodeTemplate;
#[cfg(feature = "DeleteWatermarkTemplate")]
pub mod DeleteWatermarkTemplate;
#[cfg(feature = "ListAssetCategory")]
pub mod ListAssetCategory;
#[cfg(feature = "ListAssetDailySummaryLog")]
pub mod ListAssetDailySummaryLog;
#[cfg(feature = "ListAssetList")]
pub mod ListAssetList;
#[cfg(feature = "ListDomainLogs")]
pub mod ListDomainLogs;
#[cfg(feature = "ListTakeOverTask")]
pub mod ListTakeOverTask;
#[cfg(feature = "ListTemplateGroup")]
pub mod ListTemplateGroup;
#[cfg(feature = "ListTemplateGroupCollection")]
pub mod ListTemplateGroupCollection;
#[cfg(feature = "ListTopStatistics")]
pub mod ListTopStatistics;
#[cfg(feature = "ListTranscodeTemplate")]
pub mod ListTranscodeTemplate;
#[cfg(feature = "ListWatermarkTemplate")]
pub mod ListWatermarkTemplate;
#[cfg(feature = "PublishAssetFromObs")]
pub mod PublishAssetFromObs;
#[cfg(feature = "PublishAssets")]
pub mod PublishAssets;
#[cfg(feature = "ShowAssetCipher")]
pub mod ShowAssetCipher;
#[cfg(feature = "ShowAssetDetail")]
pub mod ShowAssetDetail;
#[cfg(feature = "ShowAssetMeta")]
pub mod ShowAssetMeta;
#[cfg(feature = "ShowAssetTempAuthority")]
pub mod ShowAssetTempAuthority;
#[cfg(feature = "ShowCdnStatistics")]
pub mod ShowCdnStatistics;
#[cfg(feature = "ShowPreheatingAsset")]
pub mod ShowPreheatingAsset;
#[cfg(feature = "ShowTakeOverAssetDetails")]
pub mod ShowTakeOverAssetDetails;
#[cfg(feature = "ShowTakeOverTaskDetails")]
pub mod ShowTakeOverTaskDetails;
#[cfg(feature = "ShowVodRetrieval")]
pub mod ShowVodRetrieval;
#[cfg(feature = "ShowVodStatistics")]
pub mod ShowVodStatistics;
#[cfg(feature = "UnpublishAssets")]
pub mod UnpublishAssets;
#[cfg(feature = "UpdateAsset")]
pub mod UpdateAsset;
#[cfg(feature = "UpdateAssetCategory")]
pub mod UpdateAssetCategory;
#[cfg(feature = "UpdateAssetMeta")]
pub mod UpdateAssetMeta;
#[cfg(feature = "UpdateBucketAuthorized")]
pub mod UpdateBucketAuthorized;
#[cfg(feature = "UpdateCoverByThumbnail")]
pub mod UpdateCoverByThumbnail;
#[cfg(feature = "UpdateStorageMode")]
pub mod UpdateStorageMode;
#[cfg(feature = "UpdateTemplateGroup")]
pub mod UpdateTemplateGroup;
#[cfg(feature = "UpdateTemplateGroupCollection")]
pub mod UpdateTemplateGroupCollection;
#[cfg(feature = "UpdateTranscodeTemplate")]
pub mod UpdateTranscodeTemplate;
#[cfg(feature = "UpdateWatermarkTemplate")]
pub mod UpdateWatermarkTemplate;
#[cfg(feature = "UploadMetaDataByUrl")]
pub mod UploadMetaDataByUrl;
