#[cfg(feature = "AddAgentPath")]
pub mod AddAgentPath;
#[cfg(feature = "AddMember")]
pub mod AddMember;
#[cfg(feature = "AddVaultResource")]
pub mod AddVaultResource;
#[cfg(feature = "AssociateVaultPolicy")]
pub mod AssociateVaultPolicy;
#[cfg(feature = "BatchCreateAndDeleteVaultTags")]
pub mod BatchCreateAndDeleteVaultTags;
#[cfg(feature = "BatchUpdateVault")]
pub mod BatchUpdateVault;
#[cfg(feature = "CheckAgent")]
pub mod CheckAgent;
#[cfg(feature = "CopyBackup")]
pub mod CopyBackup;
#[cfg(feature = "CopyCheckpoint")]
pub mod CopyCheckpoint;
#[cfg(feature = "CreateCheckpoint")]
pub mod CreateCheckpoint;
#[cfg(feature = "CreateOrganizationPolicy")]
pub mod CreateOrganizationPolicy;
#[cfg(feature = "CreatePolicy")]
pub mod CreatePolicy;
#[cfg(feature = "CreatePostPaidVault")]
pub mod CreatePostPaidVault;
#[cfg(feature = "CreateVault")]
pub mod CreateVault;
#[cfg(feature = "CreateVaultTags")]
pub mod CreateVaultTags;
#[cfg(feature = "DeleteBackup")]
pub mod DeleteBackup;
#[cfg(feature = "DeleteMember")]
pub mod DeleteMember;
#[cfg(feature = "DeleteOrganizationPolicy")]
pub mod DeleteOrganizationPolicy;
#[cfg(feature = "DeletePolicy")]
pub mod DeletePolicy;
#[cfg(feature = "DeleteVault")]
pub mod DeleteVault;
#[cfg(feature = "DeleteVaultTag")]
pub mod DeleteVaultTag;
#[cfg(feature = "DisassociateVaultPolicy")]
pub mod DisassociateVaultPolicy;
#[cfg(feature = "ImportBackup")]
pub mod ImportBackup;
#[cfg(feature = "ImportCheckpoint")]
pub mod ImportCheckpoint;
#[cfg(feature = "ListAgent")]
pub mod ListAgent;
#[cfg(feature = "ListBackups")]
pub mod ListBackups;
#[cfg(feature = "ListDomainProjects")]
pub mod ListDomainProjects;
#[cfg(feature = "ListExternalVault")]
pub mod ListExternalVault;
#[cfg(feature = "ListOpLogs")]
pub mod ListOpLogs;
#[cfg(feature = "ListOrganizationPolicies")]
pub mod ListOrganizationPolicies;
#[cfg(feature = "ListOrganizationPolicyDetail")]
pub mod ListOrganizationPolicyDetail;
#[cfg(feature = "ListPolicies")]
pub mod ListPolicies;
#[cfg(feature = "ListProjects")]
pub mod ListProjects;
#[cfg(feature = "ListProtectable")]
pub mod ListProtectable;
#[cfg(feature = "ListVault")]
pub mod ListVault;
#[cfg(feature = "MigrateDomain")]
pub mod MigrateDomain;
#[cfg(feature = "MigrateVaultResource")]
pub mod MigrateVaultResource;
#[cfg(feature = "RegisterAgent")]
pub mod RegisterAgent;
#[cfg(feature = "RemoveAgentPath")]
pub mod RemoveAgentPath;
#[cfg(feature = "RemoveVaultResource")]
pub mod RemoveVaultResource;
#[cfg(feature = "RestoreBackup")]
pub mod RestoreBackup;
#[cfg(feature = "SetVaultResource")]
pub mod SetVaultResource;
#[cfg(feature = "ShowAgent")]
pub mod ShowAgent;
#[cfg(feature = "ShowBackup")]
pub mod ShowBackup;
#[cfg(feature = "ShowCheckpoint")]
pub mod ShowCheckpoint;
#[cfg(feature = "ShowDomain")]
pub mod ShowDomain;
#[cfg(feature = "ShowMemberDetail")]
pub mod ShowMemberDetail;
#[cfg(feature = "ShowMembersDetail")]
pub mod ShowMembersDetail;
#[cfg(feature = "ShowMetadata")]
pub mod ShowMetadata;
#[cfg(feature = "ShowMigrateStatus")]
pub mod ShowMigrateStatus;
#[cfg(feature = "ShowOpLog")]
pub mod ShowOpLog;
#[cfg(feature = "ShowOrganizationPolicy")]
pub mod ShowOrganizationPolicy;
#[cfg(feature = "ShowPolicy")]
pub mod ShowPolicy;
#[cfg(feature = "ShowProtectable")]
pub mod ShowProtectable;
#[cfg(feature = "ShowReplicationCapabilities")]
pub mod ShowReplicationCapabilities;
#[cfg(feature = "ShowStorageUsage")]
pub mod ShowStorageUsage;
#[cfg(feature = "ShowSummary")]
pub mod ShowSummary;
#[cfg(feature = "ShowVault")]
pub mod ShowVault;
#[cfg(feature = "ShowVaultProjectTag")]
pub mod ShowVaultProjectTag;
#[cfg(feature = "ShowVaultResourceInstances")]
pub mod ShowVaultResourceInstances;
#[cfg(feature = "ShowVaultTag")]
pub mod ShowVaultTag;
#[cfg(feature = "UnregisterAgent")]
pub mod UnregisterAgent;
#[cfg(feature = "UpdateAgent")]
pub mod UpdateAgent;
#[cfg(feature = "UpdateBackup")]
pub mod UpdateBackup;
#[cfg(feature = "UpdateMemberStatus")]
pub mod UpdateMemberStatus;
#[cfg(feature = "UpdateOrder")]
pub mod UpdateOrder;
#[cfg(feature = "UpdateOrganizationPolicy")]
pub mod UpdateOrganizationPolicy;
#[cfg(feature = "UpdatePolicy")]
pub mod UpdatePolicy;
#[cfg(feature = "UpdateVault")]
pub mod UpdateVault;
