#[cfg(feature = "ApplyExecutionPlan")]
pub mod ApplyExecutionPlan;
#[cfg(feature = "ContinueDeployStack")]
pub mod ContinueDeployStack;
#[cfg(feature = "ContinueRollbackStack")]
pub mod ContinueRollbackStack;
#[cfg(feature = "CreateExecutionPlan")]
pub mod CreateExecutionPlan;
#[cfg(feature = "CreatePrivateProvider")]
pub mod CreatePrivateProvider;
#[cfg(feature = "CreatePrivateProviderVersion")]
pub mod CreatePrivateProviderVersion;
#[cfg(feature = "CreateStack")]
pub mod CreateStack;
#[cfg(feature = "CreateStackInstance")]
pub mod CreateStackInstance;
#[cfg(feature = "CreateStackSet")]
pub mod CreateStackSet;
#[cfg(feature = "CreateTemplate")]
pub mod CreateTemplate;
#[cfg(feature = "DeleteExecutionPlan")]
pub mod DeleteExecutionPlan;
#[cfg(feature = "DeleteStack")]
pub mod DeleteStack;
#[cfg(feature = "DeleteStackEnhanced")]
pub mod DeleteStackEnhanced;
#[cfg(feature = "DeleteStackInstance")]
pub mod DeleteStackInstance;
#[cfg(feature = "DeleteStackInstanceDeprecated")]
pub mod DeleteStackInstanceDeprecated;
#[cfg(feature = "DeleteStackSet")]
pub mod DeleteStackSet;
#[cfg(feature = "DeleteTemplate")]
pub mod DeleteTemplate;
#[cfg(feature = "DeleteTemplateVersion")]
pub mod DeleteTemplateVersion;
#[cfg(feature = "DeployStack")]
pub mod DeployStack;
#[cfg(feature = "DeployStackSet")]
pub mod DeployStackSet;
#[cfg(feature = "DownloadTemplate")]
pub mod DownloadTemplate;
#[cfg(feature = "EstimateExecutionPlanPrice")]
pub mod EstimateExecutionPlanPrice;
#[cfg(feature = "GetExecutionPlan")]
pub mod GetExecutionPlan;
#[cfg(feature = "GetExecutionPlanMetadata")]
pub mod GetExecutionPlanMetadata;
#[cfg(feature = "GetStackMetadata")]
pub mod GetStackMetadata;
#[cfg(feature = "GetStackTemplate")]
pub mod GetStackTemplate;
#[cfg(feature = "ListBriefStack")]
pub mod ListBriefStack;
#[cfg(feature = "ListBriefTemplates")]
pub mod ListBriefTemplates;
#[cfg(feature = "ListExecutionPlans")]
pub mod ListExecutionPlans;
#[cfg(feature = "ListStack")]
pub mod ListStack;
#[cfg(feature = "ListStackActions")]
pub mod ListStackActions;
#[cfg(feature = "ListStackElements")]
pub mod ListStackElements;
#[cfg(feature = "ListStackEvents")]
pub mod ListStackEvents;
#[cfg(feature = "ListStackInputs")]
pub mod ListStackInputs;
#[cfg(feature = "ListStackInstances")]
pub mod ListStackInstances;
#[cfg(feature = "ListStackOutputs")]
pub mod ListStackOutputs;
#[cfg(feature = "ListStackResources")]
pub mod ListStackResources;
#[cfg(feature = "ListStacks")]
pub mod ListStacks;
#[cfg(feature = "ListStackSetOperations")]
pub mod ListStackSetOperations;
#[cfg(feature = "ListStackSets")]
pub mod ListStackSets;
#[cfg(feature = "ListTemplateInputs")]
pub mod ListTemplateInputs;
#[cfg(feature = "ListTemplates")]
pub mod ListTemplates;
#[cfg(feature = "ListTemplateVersions")]
pub mod ListTemplateVersions;
#[cfg(feature = "ParseTemplateVariables")]
pub mod ParseTemplateVariables;
#[cfg(feature = "ShowStackAction")]
pub mod ShowStackAction;
#[cfg(feature = "ShowStackDetail")]
pub mod ShowStackDetail;
#[cfg(feature = "ShowStackElement")]
pub mod ShowStackElement;
#[cfg(feature = "ShowStackInstance")]
pub mod ShowStackInstance;
#[cfg(feature = "ShowStackSetMetadata")]
pub mod ShowStackSetMetadata;
#[cfg(feature = "ShowStackSetOperationMetadata")]
pub mod ShowStackSetOperationMetadata;
#[cfg(feature = "ShowStackSetTemplate")]
pub mod ShowStackSetTemplate;
#[cfg(feature = "ShowTemplateDetail")]
pub mod ShowTemplateDetail;
#[cfg(feature = "ShowTemplateMetadata")]
pub mod ShowTemplateMetadata;
#[cfg(feature = "ShowTemplateVersionContent")]
pub mod ShowTemplateVersionContent;
#[cfg(feature = "ShowTemplateVersionMetadata")]
pub mod ShowTemplateVersionMetadata;
#[cfg(feature = "UpdateStack")]
pub mod UpdateStack;
#[cfg(feature = "UpdateStackActions")]
pub mod UpdateStackActions;
#[cfg(feature = "UpdateStackInstances")]
pub mod UpdateStackInstances;
#[cfg(feature = "UpdateStackSet")]
pub mod UpdateStackSet;
#[cfg(feature = "UpdateTemplate")]
pub mod UpdateTemplate;
#[cfg(feature = "UpdateTemplateMetadata")]
pub mod UpdateTemplateMetadata;
