#[cfg(feature = "CreateScripts")]
pub mod CreateScripts;
#[cfg(feature = "DeleteScript")]
pub mod DeleteScript;
#[cfg(feature = "ExecuteScript")]
pub mod ExecuteScript;
#[cfg(feature = "ListInstanceCompliant")]
pub mod ListInstanceCompliant;
#[cfg(feature = "ListScript")]
pub mod ListScript;
#[cfg(feature = "ListScriptOrders")]
pub mod ListScriptOrders;
#[cfg(feature = "ListScriptOrdersBatches")]
pub mod ListScriptOrdersBatches;
#[cfg(feature = "ShowInstancePatchItems")]
pub mod ShowInstancePatchItems;
#[cfg(feature = "ShowScriptDetail")]
pub mod ShowScriptDetail;
#[cfg(feature = "ShowScriptOrderBasicInfo")]
pub mod ShowScriptOrderBasicInfo;
#[cfg(feature = "ShowScriptOrdersBatchDetail")]
pub mod ShowScriptOrdersBatchDetail;
#[cfg(feature = "ShowScriptOrderStatistics")]
pub mod ShowScriptOrderStatistics;
#[cfg(feature = "UpdateScript")]
pub mod UpdateScript;
#[cfg(feature = "UpdateScriptOrder")]
pub mod UpdateScriptOrder;
