#[cfg(feature = "CreateCocIncident")]
pub mod CreateCocIncident;
#[cfg(feature = "CreateCocIssues")]
pub mod CreateCocIssues;
#[cfg(feature = "CreateReportCustomEvent")]
pub mod CreateReportCustomEvent;
#[cfg(feature = "CreateReportPrometheusEvent")]
pub mod CreateReportPrometheusEvent;
#[cfg(feature = "CreateScript")]
pub mod CreateScript;
#[cfg(feature = "CreateWarRoom")]
pub mod CreateWarRoom;
#[cfg(feature = "DeleteScript")]
pub mod DeleteScript;
#[cfg(feature = "ExecutePublicScript")]
pub mod ExecutePublicScript;
#[cfg(feature = "ExecuteScript")]
pub mod ExecuteScript;
#[cfg(feature = "GetPublicScript")]
pub mod GetPublicScript;
#[cfg(feature = "GetScript")]
pub mod GetScript;
#[cfg(feature = "GetScriptJobBatch")]
pub mod GetScriptJobBatch;
#[cfg(feature = "GetScriptJobInfo")]
pub mod GetScriptJobInfo;
#[cfg(feature = "GetScriptJobStatistics")]
pub mod GetScriptJobStatistics;
#[cfg(feature = "HandleCocIncident")]
pub mod HandleCocIncident;
#[cfg(feature = "ListApplications")]
pub mod ListApplications;
#[cfg(feature = "ListAuthorizableTicketsExternal")]
pub mod ListAuthorizableTicketsExternal;
#[cfg(feature = "ListCocTicketOperationHistories")]
pub mod ListCocTicketOperationHistories;
#[cfg(feature = "ListInstanceCompliant")]
pub mod ListInstanceCompliant;
#[cfg(feature = "ListPublicScripts")]
pub mod ListPublicScripts;
#[cfg(feature = "ListResource")]
pub mod ListResource;
#[cfg(feature = "ListScriptJobBatches")]
pub mod ListScriptJobBatches;
#[cfg(feature = "ListScriptJobs")]
pub mod ListScriptJobs;
#[cfg(feature = "ListScripts")]
pub mod ListScripts;
#[cfg(feature = "ListWarRooms")]
pub mod ListWarRooms;
#[cfg(feature = "OperateScriptJob")]
pub mod OperateScriptJob;
#[cfg(feature = "ShowCocIncidentDetail")]
pub mod ShowCocIncidentDetail;
#[cfg(feature = "ShowCocIssuesDetail")]
pub mod ShowCocIssuesDetail;
#[cfg(feature = "ShowInstancePatchItems")]
pub mod ShowInstancePatchItems;
#[cfg(feature = "SyncResource")]
pub mod SyncResource;
#[cfg(feature = "UpdateScript")]
pub mod UpdateScript;
