#[cfg(feature = "CreateScript")]
pub mod CreateScript;
#[cfg(feature = "DeleteScript")]
pub mod DeleteScript;
#[cfg(feature = "ExecuteScript")]
pub mod ExecuteScript;
#[cfg(feature = "GetScript")]
pub mod GetScript;
#[cfg(feature = "GetScriptJobBatch")]
pub mod GetScriptJobBatch;
#[cfg(feature = "GetScriptJobInfo")]
pub mod GetScriptJobInfo;
#[cfg(feature = "GetScriptJobStatistics")]
pub mod GetScriptJobStatistics;
#[cfg(feature = "ListApplications")]
pub mod ListApplications;
#[cfg(feature = "ListInstanceCompliant")]
pub mod ListInstanceCompliant;
#[cfg(feature = "ListResources")]
pub mod ListResources;
#[cfg(feature = "ListScriptJobBatches")]
pub mod ListScriptJobBatches;
#[cfg(feature = "ListScriptJobs")]
pub mod ListScriptJobs;
#[cfg(feature = "ListScripts")]
pub mod ListScripts;
#[cfg(feature = "OperateScriptJob")]
pub mod OperateScriptJob;
#[cfg(feature = "ShowInstancePatchItems")]
pub mod ShowInstancePatchItems;
#[cfg(feature = "SyncResource")]
pub mod SyncResource;
#[cfg(feature = "UpdateScript")]
pub mod UpdateScript;
