#[cfg(feature = "AddServerGroupMember")]
pub mod AddServerGroupMember;
#[cfg(feature = "AssociateServerVirtualIp")]
pub mod AssociateServerVirtualIp;
#[cfg(feature = "AttachServerVolume")]
pub mod AttachServerVolume;
#[cfg(feature = "BatchAddServerNics")]
pub mod BatchAddServerNics;
#[cfg(feature = "BatchAttachSharableVolumes")]
pub mod BatchAttachSharableVolumes;
#[cfg(feature = "BatchCreateServerTags")]
pub mod BatchCreateServerTags;
#[cfg(feature = "BatchDeleteServerNics")]
pub mod BatchDeleteServerNics;
#[cfg(feature = "BatchDeleteServerTags")]
pub mod BatchDeleteServerTags;
#[cfg(feature = "BatchRebootServers")]
pub mod BatchRebootServers;
#[cfg(feature = "BatchResetServersPassword")]
pub mod BatchResetServersPassword;
#[cfg(feature = "BatchStartServers")]
pub mod BatchStartServers;
#[cfg(feature = "BatchStopServers")]
pub mod BatchStopServers;
#[cfg(feature = "BatchUpdateServersName")]
pub mod BatchUpdateServersName;
#[cfg(feature = "ChangeServerChargeMode")]
pub mod ChangeServerChargeMode;
#[cfg(feature = "ChangeServerNetworkInterface")]
pub mod ChangeServerNetworkInterface;
#[cfg(feature = "ChangeServerOsWithCloudInit")]
pub mod ChangeServerOsWithCloudInit;
#[cfg(feature = "ChangeServerOsWithoutCloudInit")]
pub mod ChangeServerOsWithoutCloudInit;
#[cfg(feature = "ChangeVpc")]
pub mod ChangeVpc;
#[cfg(feature = "CreatePostPaidServers")]
pub mod CreatePostPaidServers;
#[cfg(feature = "CreateServerGroup")]
pub mod CreateServerGroup;
#[cfg(feature = "CreateServers")]
pub mod CreateServers;
#[cfg(feature = "DeleteRecycleBinServer")]
pub mod DeleteRecycleBinServer;
#[cfg(feature = "DeleteServerGroup")]
pub mod DeleteServerGroup;
#[cfg(feature = "DeleteServerGroupMember")]
pub mod DeleteServerGroupMember;
#[cfg(feature = "DeleteServerMetadata")]
pub mod DeleteServerMetadata;
#[cfg(feature = "DeleteServerPassword")]
pub mod DeleteServerPassword;
#[cfg(feature = "DeleteServers")]
pub mod DeleteServers;
#[cfg(feature = "DetachServerVolume")]
pub mod DetachServerVolume;
#[cfg(feature = "DisassociateServerVirtualIp")]
pub mod DisassociateServerVirtualIp;
#[cfg(feature = "ListCloudServers")]
pub mod ListCloudServers;
#[cfg(feature = "ListFlavors")]
pub mod ListFlavors;
#[cfg(feature = "ListFlavorSellPolicies")]
pub mod ListFlavorSellPolicies;
#[cfg(feature = "ListRecycleBinServers")]
pub mod ListRecycleBinServers;
#[cfg(feature = "ListResizeFlavors")]
pub mod ListResizeFlavors;
#[cfg(feature = "ListScheduledEvents")]
pub mod ListScheduledEvents;
#[cfg(feature = "ListServerAzInfo")]
pub mod ListServerAzInfo;
#[cfg(feature = "ListServerBlockDevices")]
pub mod ListServerBlockDevices;
#[cfg(feature = "ListServerGroups")]
pub mod ListServerGroups;
#[cfg(feature = "ListServerInterfaces")]
pub mod ListServerInterfaces;
#[cfg(feature = "ListServersDetails")]
pub mod ListServersDetails;
#[cfg(feature = "ListServerTags")]
pub mod ListServerTags;
#[cfg(feature = "ListServerVolumeAttachments")]
pub mod ListServerVolumeAttachments;
#[cfg(feature = "MigrateServer")]
pub mod MigrateServer;
#[cfg(feature = "NovaAssociateSecurityGroup")]
pub mod NovaAssociateSecurityGroup;
#[cfg(feature = "NovaAttachInterface")]
pub mod NovaAttachInterface;
#[cfg(feature = "NovaAttachVolume")]
pub mod NovaAttachVolume;
#[cfg(feature = "NovaCreateKeypair")]
pub mod NovaCreateKeypair;
#[cfg(feature = "NovaCreateServerGroup")]
pub mod NovaCreateServerGroup;
#[cfg(feature = "NovaCreateServerMetadata")]
pub mod NovaCreateServerMetadata;
#[cfg(feature = "NovaCreateServers")]
pub mod NovaCreateServers;
#[cfg(feature = "NovaDeleteKeypair")]
pub mod NovaDeleteKeypair;
#[cfg(feature = "NovaDeleteServer")]
pub mod NovaDeleteServer;
#[cfg(feature = "NovaDeleteServerGroup")]
pub mod NovaDeleteServerGroup;
#[cfg(feature = "NovaDeleteServerMetadataItem")]
pub mod NovaDeleteServerMetadataItem;
#[cfg(feature = "NovaDetachInterface")]
pub mod NovaDetachInterface;
#[cfg(feature = "NovaDetachVolume")]
pub mod NovaDetachVolume;
#[cfg(feature = "NovaDisassociateSecurityGroup")]
pub mod NovaDisassociateSecurityGroup;
#[cfg(feature = "NovaListAvailabilityZones")]
pub mod NovaListAvailabilityZones;
#[cfg(feature = "NovaListFlavors")]
pub mod NovaListFlavors;
#[cfg(feature = "NovaListFlavorsDetails")]
pub mod NovaListFlavorsDetails;
#[cfg(feature = "NovaListKeypairs")]
pub mod NovaListKeypairs;
#[cfg(feature = "NovaListServerActions")]
pub mod NovaListServerActions;
#[cfg(feature = "NovaListServerGroups")]
pub mod NovaListServerGroups;
#[cfg(feature = "NovaListServerInterfaces")]
pub mod NovaListServerInterfaces;
#[cfg(feature = "NovaListServers")]
pub mod NovaListServers;
#[cfg(feature = "NovaListServersDetails")]
pub mod NovaListServersDetails;
#[cfg(feature = "NovaListServerSecurityGroups")]
pub mod NovaListServerSecurityGroups;
#[cfg(feature = "NovaListServerVolumes")]
pub mod NovaListServerVolumes;
#[cfg(feature = "NovaListVersions")]
pub mod NovaListVersions;
#[cfg(feature = "NovaLockServer")]
pub mod NovaLockServer;
#[cfg(feature = "NovaRebootServer")]
pub mod NovaRebootServer;
#[cfg(feature = "NovaShowFlavor")]
pub mod NovaShowFlavor;
#[cfg(feature = "NovaShowFlavorExtraSpecs")]
pub mod NovaShowFlavorExtraSpecs;
#[cfg(feature = "NovaShowKeypair")]
pub mod NovaShowKeypair;
#[cfg(feature = "NovaShowServer")]
pub mod NovaShowServer;
#[cfg(feature = "NovaShowServerAction")]
pub mod NovaShowServerAction;
#[cfg(feature = "NovaShowServerGroup")]
pub mod NovaShowServerGroup;
#[cfg(feature = "NovaShowServerInterface")]
pub mod NovaShowServerInterface;
#[cfg(feature = "NovaShowServerMetadata")]
pub mod NovaShowServerMetadata;
#[cfg(feature = "NovaShowServerMetadataItem")]
pub mod NovaShowServerMetadataItem;
#[cfg(feature = "NovaShowServerVolume")]
pub mod NovaShowServerVolume;
#[cfg(feature = "NovaShowVersion")]
pub mod NovaShowVersion;
#[cfg(feature = "NovaStartServer")]
pub mod NovaStartServer;
#[cfg(feature = "NovaStopServer")]
pub mod NovaStopServer;
#[cfg(feature = "NovaUnlockServer")]
pub mod NovaUnlockServer;
#[cfg(feature = "NovaUpdateServer")]
pub mod NovaUpdateServer;
#[cfg(feature = "NovaUpdateServerMetadata")]
pub mod NovaUpdateServerMetadata;
#[cfg(feature = "NovaUpdateServerMetadataItem")]
pub mod NovaUpdateServerMetadataItem;
#[cfg(feature = "RegisterServerMonitor")]
pub mod RegisterServerMonitor;
#[cfg(feature = "ReinstallServerWithCloudInit")]
pub mod ReinstallServerWithCloudInit;
#[cfg(feature = "ReinstallServerWithoutCloudInit")]
pub mod ReinstallServerWithoutCloudInit;
#[cfg(feature = "ResetServerPassword")]
pub mod ResetServerPassword;
#[cfg(feature = "ResizePostPaidServer")]
pub mod ResizePostPaidServer;
#[cfg(feature = "ResizeServer")]
pub mod ResizeServer;
#[cfg(feature = "RevertRecycleBinServer")]
pub mod RevertRecycleBinServer;
#[cfg(feature = "ShowJob")]
pub mod ShowJob;
#[cfg(feature = "ShowRecycleBin")]
pub mod ShowRecycleBin;
#[cfg(feature = "ShowRecycleBinServer")]
pub mod ShowRecycleBinServer;
#[cfg(feature = "ShowResetPasswordFlag")]
pub mod ShowResetPasswordFlag;
#[cfg(feature = "ShowServer")]
pub mod ShowServer;
