[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AcceptScheduledEvent = []
AddServerGroupMember = []
AssociateServerVirtualIp = []
AttachServerVolume = []
BatchAddServerNics = []
BatchAttachSharableVolumes = []
BatchCreateServerTags = []
BatchDeleteServerNics = []
BatchDeleteServerTags = []
BatchDetachVolumes = []
BatchRebootServers = []
BatchResetServersPassword = []
BatchResizeServers = []
BatchStartServers = []
BatchStopServers = []
BatchUpdateServersName = []
ChangeServerChargeMode = []
ChangeServerNetworkInterface = []
ChangeServerOsWithCloudInit = []
ChangeServerOsWithoutCloudInit = []
ChangeVpc = []
CreateLaunchTemplate = []
CreatePostPaidServers = []
CreateServerGroup = []
CreateServers = []
DeleteLaunchTemplates = []
DeleteRecycleBinServer = []
DeleteServerGroup = []
DeleteServerGroupMember = []
DeleteServerMetadata = []
DeleteServerPassword = []
DeleteServers = []
DetachServerVolume = []
DisassociateServerVirtualIp = []
ExecuteServerDump = []
ExecuteServerRedeploy = []
ListCloudServers = []
ListFlavorSellPolicies = []
ListFlavors = []
ListLaunchTemplateVersions = []
ListRecycleBinServers = []
ListResizeFlavors = []
ListScheduledEvents = []
ListServerAzInfo = []
ListServerBlockDevices = []
ListServerGroups = []
ListServerInterfaces = []
ListServerTags = []
ListServerVolumeAttachments = []
ListServersDetails = []
ListTemplates = []
MigrateServer = []
NovaAssociateSecurityGroup = []
NovaAttachInterface = []
NovaAttachVolume = []
NovaCreateKeypair = []
NovaCreateServerGroup = []
NovaCreateServerMetadata = []
NovaCreateServers = []
NovaDeleteKeypair = []
NovaDeleteServer = []
NovaDeleteServerGroup = []
NovaDeleteServerMetadataItem = []
NovaDetachInterface = []
NovaDetachVolume = []
NovaDisassociateSecurityGroup = []
NovaListAvailabilityZones = []
NovaListFlavors = []
NovaListFlavorsDetails = []
NovaListKeypairs = []
NovaListServerActions = []
NovaListServerGroups = []
NovaListServerInterfaces = []
NovaListServerSecurityGroups = []
NovaListServerVolumes = []
NovaListServers = []
NovaListServersDetails = []
NovaListVersions = []
NovaLockServer = []
NovaRebootServer = []
NovaShowFlavor = []
NovaShowFlavorExtraSpecs = []
NovaShowKeypair = []
NovaShowServer = []
NovaShowServerAction = []
NovaShowServerGroup = []
NovaShowServerInterface = []
NovaShowServerMetadata = []
NovaShowServerMetadataItem = []
NovaShowServerVolume = []
NovaShowVersion = []
NovaStartServer = []
NovaStopServer = []
NovaUnlockServer = []
NovaUpdateServer = []
NovaUpdateServerMetadata = []
NovaUpdateServerMetadataItem = []
RegisterServerMonitor = []
ReinstallServerWithCloudInit = []
ReinstallServerWithoutCloudInit = []
full = ["AcceptScheduledEvent", "AddServerGroupMember", "AssociateServerVirtualIp", "AttachServerVolume", "BatchAddServerNics", "BatchAttachSharableVolumes", "BatchCreateServerTags", "BatchDeleteServerNics", "BatchDeleteServerTags", "BatchDetachVolumes", "BatchRebootServers", "BatchResetServersPassword", "BatchResizeServers", "BatchStartServers", "BatchStopServers", "BatchUpdateServersName", "ChangeServerChargeMode", "ChangeServerNetworkInterface", "ChangeServerOsWithCloudInit", "ChangeServerOsWithoutCloudInit", "ChangeVpc", "CreateLaunchTemplate", "CreatePostPaidServers", "CreateServerGroup", "CreateServers", "DeleteLaunchTemplates", "DeleteRecycleBinServer", "DeleteServerGroup", "DeleteServerGroupMember", "DeleteServerMetadata", "DeleteServerPassword", "DeleteServers", "DetachServerVolume", "DisassociateServerVirtualIp", "ExecuteServerDump", "ExecuteServerRedeploy", "ListCloudServers", "ListFlavors", "ListFlavorSellPolicies", "ListLaunchTemplateVersions", "ListRecycleBinServers", "ListResizeFlavors", "ListScheduledEvents", "ListServerAzInfo", "ListServerBlockDevices", "ListServerGroups", "ListServerInterfaces", "ListServersDetails", "ListServerTags", "ListServerVolumeAttachments", "ListTemplates", "MigrateServer", "NovaAssociateSecurityGroup", "NovaAttachInterface", "NovaAttachVolume", "NovaCreateKeypair", "NovaCreateServerGroup", "NovaCreateServerMetadata", "NovaCreateServers", "NovaDeleteKeypair", "NovaDeleteServer", "NovaDeleteServerGroup", "NovaDeleteServerMetadataItem", "NovaDetachInterface", "NovaDetachVolume", "NovaDisassociateSecurityGroup", "NovaListAvailabilityZones", "NovaListFlavors", "NovaListFlavorsDetails", "NovaListKeypairs", "NovaListServerActions", "NovaListServerGroups", "NovaListServerInterfaces", "NovaListServers", "NovaListServersDetails", "NovaListServerSecurityGroups", "NovaListServerVolumes", "NovaListVersions", "NovaLockServer", "NovaRebootServer", "NovaShowFlavor", "NovaShowFlavorExtraSpecs", "NovaShowKeypair", "NovaShowServer", "NovaShowServerAction", "NovaShowServerGroup", "NovaShowServerInterface", "NovaShowServerMetadata", "NovaShowServerMetadataItem", "NovaShowServerVolume", "NovaShowVersion", "NovaStartServer", "NovaStopServer", "NovaUnlockServer", "NovaUpdateServer", "NovaUpdateServerMetadata", "NovaUpdateServerMetadataItem", "RegisterServerMonitor", "ReinstallServerWithCloudInit", "ReinstallServerWithoutCloudInit"]

[lib]
name = "huawei_cloud_api_definitions_ECS"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-ECS"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
