[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AttachEip = []
AttachEip2 = []
ClearGraph = []
ClearGraph2 = []
CreateBackup = []
CreateBackup2 = []
CreateGraph = []
CreateGraph2 = []
CreateMetadata = []
CreateMetadata2 = []
DeleteBackup = []
DeleteBackup2 = []
DeleteGraph = []
DeleteGraph2 = []
DeleteMetadata = []
DeleteMetadata2 = []
DeregisterScenes2 = []
DetachEip = []
DetachEip2 = []
ExpandGraph = []
ExpandGraph2 = []
ExportBackup2 = []
ExportGraph = []
ExportGraph2 = []
ImportBackup2 = []
ImportGraph = []
ImportGraph2 = []
ListBackups = []
ListBackups2 = []
ListGraphBackups = []
ListGraphBackups2 = []
ListGraphMetadatas = []
ListGraphs = []
ListGraphs2 = []
ListJobs = []
ListJobs2 = []
ListMetadatas = []
ListMetadatas2 = []
ListQuotas = []
ListQuotas2 = []
ListScenes2 = []
RegisterScenes2 = []
ResizeGraph = []
ResizeGraph2 = []
RestartGraph = []
RestartGraph2 = []
ShowGraph = []
ShowGraph2 = []
ShowJob = []
ShowJob2 = []
ShowMetadata2 = []
StartGraph = []
StartGraph2 = []
StopGraph = []
StopGraph2 = []
UpgradeGraph = []
UpgradeGraph2 = []
UploadFromObs = []
UploadFromObs2 = []
full = ["AttachEip", "AttachEip2", "ClearGraph", "ClearGraph2", "CreateBackup", "CreateBackup2", "CreateGraph", "CreateGraph2", "CreateMetadata", "CreateMetadata2", "DeleteBackup", "DeleteBackup2", "DeleteGraph", "DeleteGraph2", "DeleteMetadata", "DeleteMetadata2", "DeregisterScenes2", "DetachEip", "DetachEip2", "ExpandGraph", "ExpandGraph2", "ExportBackup2", "ExportGraph", "ExportGraph2", "ImportBackup2", "ImportGraph", "ImportGraph2", "ListBackups", "ListBackups2", "ListGraphBackups", "ListGraphBackups2", "ListGraphMetadatas", "ListGraphs", "ListGraphs2", "ListJobs", "ListJobs2", "ListMetadatas", "ListMetadatas2", "ListQuotas", "ListQuotas2", "ListScenes2", "RegisterScenes2", "ResizeGraph", "ResizeGraph2", "RestartGraph", "RestartGraph2", "ShowGraph", "ShowGraph2", "ShowJob", "ShowJob2", "ShowMetadata2", "StartGraph", "StartGraph2", "StopGraph", "StopGraph2", "UpgradeGraph", "UpgradeGraph2", "UploadFromObs", "UploadFromObs2"]

[lib]
name = "huawei_cloud_api_definitions_GES"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-GES"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
