#[cfg(feature = "AddApplyJoinProjectForAgc")]
pub mod AddApplyJoinProjectForAgc;
#[cfg(feature = "AddIssueWorkHours")]
pub mod AddIssueWorkHours;
#[cfg(feature = "AddMemberV4")]
pub mod AddMemberV4;
#[cfg(feature = "BatchAddMembersV4")]
pub mod BatchAddMembersV4;
#[cfg(feature = "BatchDeleteIssuesV4")]
pub mod BatchDeleteIssuesV4;
#[cfg(feature = "BatchDeleteIterationsV4")]
pub mod BatchDeleteIterationsV4;
#[cfg(feature = "BatchDeleteMembersV4")]
pub mod BatchDeleteMembersV4;
#[cfg(feature = "BatchUpdateChildNickNames")]
pub mod BatchUpdateChildNickNames;
#[cfg(feature = "CancelProjectDomain")]
pub mod CancelProjectDomain;
#[cfg(feature = "CheckProjectNameV4")]
pub mod CheckProjectNameV4;
#[cfg(feature = "CreateCustomfields")]
pub mod CreateCustomfields;
#[cfg(feature = "CreateIssueV4")]
pub mod CreateIssueV4;
#[cfg(feature = "CreateIterationV4")]
pub mod CreateIterationV4;
#[cfg(feature = "CreateProjectDomain")]
pub mod CreateProjectDomain;
#[cfg(feature = "CreateProjectModule")]
pub mod CreateProjectModule;
#[cfg(feature = "CreateProjectV4")]
pub mod CreateProjectV4;
#[cfg(feature = "CreateSystemIssueV4")]
pub mod CreateSystemIssueV4;
#[cfg(feature = "DeleteAttachment")]
pub mod DeleteAttachment;
#[cfg(feature = "DeleteIssueV4")]
pub mod DeleteIssueV4;
#[cfg(feature = "DeleteIterationV4")]
pub mod DeleteIterationV4;
#[cfg(feature = "DeleteProjectModule")]
pub mod DeleteProjectModule;
#[cfg(feature = "DeleteProjectV4")]
pub mod DeleteProjectV4;
#[cfg(feature = "DownloadAttachment")]
pub mod DownloadAttachment;
#[cfg(feature = "DownloadImageFile")]
pub mod DownloadImageFile;
#[cfg(feature = "ListAssociatedIssues")]
pub mod ListAssociatedIssues;
#[cfg(feature = "ListAssociatedTestCases")]
pub mod ListAssociatedTestCases;
#[cfg(feature = "ListAssociatedWikis")]
pub mod ListAssociatedWikis;
#[cfg(feature = "ListChildIssuesV4")]
pub mod ListChildIssuesV4;
#[cfg(feature = "ListDomainNotAddedProjectsV4")]
pub mod ListDomainNotAddedProjectsV4;
#[cfg(feature = "ListIssueAssociatedCommits")]
pub mod ListIssueAssociatedCommits;
#[cfg(feature = "ListIssueCommentsV4")]
pub mod ListIssueCommentsV4;
#[cfg(feature = "ListIssueCustomFields")]
pub mod ListIssueCustomFields;
#[cfg(feature = "ListIssueRecordsV4")]
pub mod ListIssueRecordsV4;
#[cfg(feature = "ListIssuesSfV4")]
pub mod ListIssuesSfV4;
#[cfg(feature = "ListIssuesV4")]
pub mod ListIssuesV4;
#[cfg(feature = "ListIterationHistories")]
pub mod ListIterationHistories;
#[cfg(feature = "ListProjectBugStaticsV4")]
pub mod ListProjectBugStaticsV4;
#[cfg(feature = "ListProjectDemandStaticV4")]
pub mod ListProjectDemandStaticV4;
#[cfg(feature = "ListProjectDomains")]
pub mod ListProjectDomains;
#[cfg(feature = "ListProjectIssuesRecordsV4")]
pub mod ListProjectIssuesRecordsV4;
#[cfg(feature = "ListProjectIterationsV4")]
pub mod ListProjectIterationsV4;
#[cfg(feature = "ListProjectMembersV4")]
pub mod ListProjectMembersV4;
#[cfg(feature = "ListProjectModules")]
pub mod ListProjectModules;
#[cfg(feature = "ListProjectsV4")]
pub mod ListProjectsV4;
#[cfg(feature = "ListProjectWorkHours")]
pub mod ListProjectWorkHours;
#[cfg(feature = "ListProjectWorkHoursType")]
pub mod ListProjectWorkHoursType;
#[cfg(feature = "ListScrumProjectStatuses")]
pub mod ListScrumProjectStatuses;
#[cfg(feature = "ListSpecIssueStayTimes")]
pub mod ListSpecIssueStayTimes;
#[cfg(feature = "ListStatusStatistic")]
pub mod ListStatusStatistic;
#[cfg(feature = "ListTemplates")]
pub mod ListTemplates;
#[cfg(feature = "ListWorkitems")]
pub mod ListWorkitems;
#[cfg(feature = "ListWorkitemStatusRecordsV4")]
pub mod ListWorkitemStatusRecordsV4;
#[cfg(feature = "RemoveProject")]
pub mod RemoveProject;
#[cfg(feature = "SearchIssues")]
pub mod SearchIssues;
#[cfg(feature = "ShowBugDensityV2")]
pub mod ShowBugDensityV2;
#[cfg(feature = "ShowBugsPerDeveloper")]
pub mod ShowBugsPerDeveloper;
#[cfg(feature = "ShowCompletionRate")]
pub mod ShowCompletionRate;
#[cfg(feature = "ShowCurUserInfo")]
pub mod ShowCurUserInfo;
#[cfg(feature = "ShowCurUserRole")]
pub mod ShowCurUserRole;
#[cfg(feature = "ShowIssueCompletionRate")]
pub mod ShowIssueCompletionRate;
#[cfg(feature = "ShowIssuesWrokFlowConfig")]
pub mod ShowIssuesWrokFlowConfig;
#[cfg(feature = "ShowIssueV4")]
pub mod ShowIssueV4;
#[cfg(feature = "ShowIterationV4")]
pub mod ShowIterationV4;
#[cfg(feature = "ShowProjectInfoV4")]
pub mod ShowProjectInfoV4;
#[cfg(feature = "ShowProjectSummaryV4")]
pub mod ShowProjectSummaryV4;
#[cfg(feature = "ShowProjectWorkHours")]
pub mod ShowProjectWorkHours;
#[cfg(feature = "ShowWorkItemWrokflowConfig")]
pub mod ShowWorkItemWrokflowConfig;
#[cfg(feature = "UpdateIssueV4")]
pub mod UpdateIssueV4;
#[cfg(feature = "UpdateIterationV4")]
pub mod UpdateIterationV4;
#[cfg(feature = "UpdateMembesRoleV4")]
pub mod UpdateMembesRoleV4;
#[cfg(feature = "UpdateNickNameV4")]
pub mod UpdateNickNameV4;
#[cfg(feature = "UpdateProjectDomain")]
pub mod UpdateProjectDomain;
#[cfg(feature = "UpdateProjectModule")]
pub mod UpdateProjectModule;
#[cfg(feature = "UpdateProjectV4")]
pub mod UpdateProjectV4;
#[cfg(feature = "UploadAttachments")]
pub mod UploadAttachments;
#[cfg(feature = "UploadIssueImg")]
pub mod UploadIssueImg;
