#[cfg(feature = "AddApplyJoinProjectForAgc")]
pub mod AddApplyJoinProjectForAgc;
#[cfg(feature = "AddIssueWorkHours")]
pub mod AddIssueWorkHours;
#[cfg(feature = "AddMemberV4")]
pub mod AddMemberV4;
#[cfg(feature = "AssociateIpdThirdParty")]
pub mod AssociateIpdThirdParty;
#[cfg(feature = "AssociateIssues")]
pub mod AssociateIssues;
#[cfg(feature = "AssociateScrumIssue")]
pub mod AssociateScrumIssue;
#[cfg(feature = "BatchAddMembersV4")]
pub mod BatchAddMembersV4;
#[cfg(feature = "BatchBaselineIpdIssues")]
pub mod BatchBaselineIpdIssues;
#[cfg(feature = "BatchCreateIpdIssues")]
pub mod BatchCreateIpdIssues;
#[cfg(feature = "BatchCreateIssueSnapitems")]
pub mod BatchCreateIssueSnapitems;
#[cfg(feature = "BatchCreateIssuesV2")]
pub mod BatchCreateIssuesV2;
#[cfg(feature = "BatchDeleteIpdIssue")]
pub mod BatchDeleteIpdIssue;
#[cfg(feature = "BatchDeleteIpdIssues")]
pub mod BatchDeleteIpdIssues;
#[cfg(feature = "BatchDeleteIssuesV4")]
pub mod BatchDeleteIssuesV4;
#[cfg(feature = "BatchDeleteIterationsV4")]
pub mod BatchDeleteIterationsV4;
#[cfg(feature = "BatchDeleteMembersV4")]
pub mod BatchDeleteMembersV4;
#[cfg(feature = "BatchDeletePlans")]
pub mod BatchDeletePlans;
#[cfg(feature = "BatchDeleteScrumWorkitem")]
pub mod BatchDeleteScrumWorkitem;
#[cfg(feature = "BatchDeleteSnapshots")]
pub mod BatchDeleteSnapshots;
#[cfg(feature = "BatchListAssociatedIssues")]
pub mod BatchListAssociatedIssues;
#[cfg(feature = "BatchTransferIpdWorkItemFlow")]
pub mod BatchTransferIpdWorkItemFlow;
#[cfg(feature = "BatchUpdateBaseline")]
pub mod BatchUpdateBaseline;
#[cfg(feature = "BatchUpdateChildNickNames")]
pub mod BatchUpdateChildNickNames;
#[cfg(feature = "BatchUpdateIpdIssues")]
pub mod BatchUpdateIpdIssues;
#[cfg(feature = "BatchUpdateScrumIssues")]
pub mod BatchUpdateScrumIssues;
#[cfg(feature = "BatchUpdateSnapshotDeletableFlag")]
pub mod BatchUpdateSnapshotDeletableFlag;
#[cfg(feature = "CancelProjectDomain")]
pub mod CancelProjectDomain;
#[cfg(feature = "CancelScrumAssociate")]
pub mod CancelScrumAssociate;
#[cfg(feature = "ChangePlanStatus")]
pub mod ChangePlanStatus;
#[cfg(feature = "CheckProjectNameV4")]
pub mod CheckProjectNameV4;
#[cfg(feature = "CreateCustomfields")]
pub mod CreateCustomfields;
#[cfg(feature = "CreateIpdIssueComments")]
pub mod CreateIpdIssueComments;
#[cfg(feature = "CreateIpdLabel")]
pub mod CreateIpdLabel;
#[cfg(feature = "CreateIpdProcessInstance")]
pub mod CreateIpdProcessInstance;
#[cfg(feature = "CreateIpdProjectIssue")]
pub mod CreateIpdProjectIssue;
#[cfg(feature = "CreateIpdProjectIssueAttachment")]
pub mod CreateIpdProjectIssueAttachment;
#[cfg(feature = "CreateIssueV4")]
pub mod CreateIssueV4;
#[cfg(feature = "CreateIterationV4")]
pub mod CreateIterationV4;
#[cfg(feature = "CreatePlans")]
pub mod CreatePlans;
#[cfg(feature = "CreateProjectDomain")]
pub mod CreateProjectDomain;
#[cfg(feature = "CreateProjectModule")]
pub mod CreateProjectModule;
#[cfg(feature = "CreateProjectV4")]
pub mod CreateProjectV4;
#[cfg(feature = "CreateScrumPlanToProject")]
pub mod CreateScrumPlanToProject;
#[cfg(feature = "CreateSprintSnapshots")]
pub mod CreateSprintSnapshots;
#[cfg(feature = "CreateSystemIssueV4")]
pub mod CreateSystemIssueV4;
#[cfg(feature = "DeleteAttachment")]
pub mod DeleteAttachment;
#[cfg(feature = "DeleteIpdIssueComment")]
pub mod DeleteIpdIssueComment;
#[cfg(feature = "DeleteIpdLabel")]
pub mod DeleteIpdLabel;
#[cfg(feature = "DeleteIpdThirdParty")]
pub mod DeleteIpdThirdParty;
#[cfg(feature = "DeleteIssueV4")]
pub mod DeleteIssueV4;
#[cfg(feature = "DeleteIterationV4")]
pub mod DeleteIterationV4;
#[cfg(feature = "DeleteProjectModule")]
pub mod DeleteProjectModule;
#[cfg(feature = "DeleteProjectV4")]
pub mod DeleteProjectV4;
#[cfg(feature = "DeleteScrumMyIssueNotes")]
pub mod DeleteScrumMyIssueNotes;
#[cfg(feature = "DeleteScrumPlanInProject")]
pub mod DeleteScrumPlanInProject;
#[cfg(feature = "DownloadAttachment")]
pub mod DownloadAttachment;
#[cfg(feature = "DownloadImageFile")]
pub mod DownloadImageFile;
#[cfg(feature = "DownloadIpdIssueAttachment")]
pub mod DownloadIpdIssueAttachment;
#[cfg(feature = "GetModelConfig")]
pub mod GetModelConfig;
#[cfg(feature = "ListAssociatedIssues")]
pub mod ListAssociatedIssues;
#[cfg(feature = "ListAssociatedTestCases")]
pub mod ListAssociatedTestCases;
#[cfg(feature = "ListAssociatedWikis")]
pub mod ListAssociatedWikis;
#[cfg(feature = "ListChildIssuesV4")]
pub mod ListChildIssuesV4;
#[cfg(feature = "ListDomainNotAddedProjectsV4")]
pub mod ListDomainNotAddedProjectsV4;
#[cfg(feature = "ListIpdIssueComments")]
pub mod ListIpdIssueComments;
#[cfg(feature = "ListIpdLabels")]
pub mod ListIpdLabels;
#[cfg(feature = "ListIpdProjectFields")]
pub mod ListIpdProjectFields;
#[cfg(feature = "ListIpdProjectIssues")]
pub mod ListIpdProjectIssues;
#[cfg(feature = "ListIpdReviewFormsByIssueId")]
pub mod ListIpdReviewFormsByIssueId;
#[cfg(feature = "ListIssueAssociatedCommits")]
pub mod ListIssueAssociatedCommits;
#[cfg(feature = "ListIssueBySnapIds")]
pub mod ListIssueBySnapIds;
#[cfg(feature = "ListIssueCommentsV4")]
pub mod ListIssueCommentsV4;
#[cfg(feature = "ListIssueCustomFields")]
pub mod ListIssueCustomFields;
#[cfg(feature = "ListIssueFields")]
pub mod ListIssueFields;
#[cfg(feature = "ListIssueRecordsV4")]
pub mod ListIssueRecordsV4;
#[cfg(feature = "ListIssueSprintSnapshots")]
pub mod ListIssueSprintSnapshots;
#[cfg(feature = "ListIssuesSfV4")]
pub mod ListIssuesSfV4;
#[cfg(feature = "ListIssueStatues")]
pub mod ListIssueStatues;
#[cfg(feature = "ListIssuesV4")]
pub mod ListIssuesV4;
#[cfg(feature = "ListIterationHistories")]
pub mod ListIterationHistories;
#[cfg(feature = "ListPlan")]
pub mod ListPlan;
#[cfg(feature = "ListPlanDetail")]
pub mod ListPlanDetail;
#[cfg(feature = "ListProjectBugStaticsV4")]
pub mod ListProjectBugStaticsV4;
#[cfg(feature = "ListProjectDemandStaticV4")]
pub mod ListProjectDemandStaticV4;
#[cfg(feature = "ListProjectDomains")]
pub mod ListProjectDomains;
#[cfg(feature = "ListProjectIssuesRecordsV4")]
pub mod ListProjectIssuesRecordsV4;
#[cfg(feature = "ListProjectIterationsV4")]
pub mod ListProjectIterationsV4;
#[cfg(feature = "ListProjectMembersV4")]
pub mod ListProjectMembersV4;
#[cfg(feature = "ListProjectModules")]
pub mod ListProjectModules;
#[cfg(feature = "ListProjectsV4")]
pub mod ListProjectsV4;
#[cfg(feature = "ListProjectUsers")]
pub mod ListProjectUsers;
#[cfg(feature = "ListProjectWorkHours")]
pub mod ListProjectWorkHours;
#[cfg(feature = "ListProjectWorkHoursType")]
pub mod ListProjectWorkHoursType;
#[cfg(feature = "ListScrumJobCache")]
pub mod ListScrumJobCache;
#[cfg(feature = "ListScrumProjectStatuses")]
pub mod ListScrumProjectStatuses;
#[cfg(feature = "ListSpecIssueStayTimes")]
pub mod ListSpecIssueStayTimes;
#[cfg(feature = "ListStatusStatistic")]
pub mod ListStatusStatistic;
#[cfg(feature = "ListTemplates")]
pub mod ListTemplates;
#[cfg(feature = "ListWorkitemConfigs")]
pub mod ListWorkitemConfigs;
#[cfg(feature = "ListWorkitems")]
pub mod ListWorkitems;
