#[cfg(feature = "BindInstanceTags")]
pub mod BindInstanceTags;
#[cfg(feature = "ChangeInstanceChargeMode")]
pub mod ChangeInstanceChargeMode;
#[cfg(feature = "CreateInstance")]
pub mod CreateInstance;
#[cfg(feature = "DeleteInstance")]
pub mod DeleteInstance;
#[cfg(feature = "ListInstanceFlavors")]
pub mod ListInstanceFlavors;
#[cfg(feature = "ListInstances")]
pub mod ListInstances;
#[cfg(feature = "ListInstanceTasks")]
pub mod ListInstanceTasks;
#[cfg(feature = "ResizeInstance")]
pub mod ResizeInstance;
#[cfg(feature = "RetryInstanceTask")]
pub mod RetryInstanceTask;
#[cfg(feature = "ShowInstance")]
pub mod ShowInstance;
#[cfg(feature = "ShowInstanceTask")]
pub mod ShowInstanceTask;
#[cfg(feature = "UnbindInstanceTags")]
pub mod UnbindInstanceTags;
#[cfg(feature = "UpdateInstance")]
pub mod UpdateInstance;
