#[cfg(feature = "BindInstanceTags")]
pub mod BindInstanceTags;
#[cfg(feature = "ChangeInstanceChargeMode")]
pub mod ChangeInstanceChargeMode;
#[cfg(feature = "CreateInstance")]
pub mod CreateInstance;
#[cfg(feature = "DeleteInstance")]
pub mod DeleteInstance;
#[cfg(feature = "ListInstances")]
pub mod ListInstances;
#[cfg(feature = "ResizeInstance")]
pub mod ResizeInstance;
#[cfg(feature = "ShowInstance")]
pub mod ShowInstance;
#[cfg(feature = "UnbindInstanceTags")]
pub mod UnbindInstanceTags;
#[cfg(feature = "UpdateInstance")]
pub mod UpdateInstance;
