#[cfg(feature = "ApplyCertificateToHost")]
pub mod ApplyCertificateToHost;
#[cfg(feature = "ChangePrepaidCloudWaf")]
pub mod ChangePrepaidCloudWaf;
#[cfg(feature = "CheckAgency")]
pub mod CheckAgency;
#[cfg(feature = "ConfirmIpReputationRule")]
pub mod ConfirmIpReputationRule;
#[cfg(feature = "ConfirmPolicyAntileakageMap")]
pub mod ConfirmPolicyAntileakageMap;
#[cfg(feature = "ConfirmPolicyIpReputationMap")]
pub mod ConfirmPolicyIpReputationMap;
#[cfg(feature = "ConfirmThreatMap")]
pub mod ConfirmThreatMap;
#[cfg(feature = "ConfirmUserBundle")]
pub mod ConfirmUserBundle;
#[cfg(feature = "CreateAnticrawlerRule")]
pub mod CreateAnticrawlerRule;
#[cfg(feature = "CreateAntileakageRule")]
pub mod CreateAntileakageRule;
#[cfg(feature = "CreateAntiTamperRule")]
pub mod CreateAntiTamperRule;
#[cfg(feature = "CreateCcRule")]
pub mod CreateCcRule;
#[cfg(feature = "CreateCertificate")]
pub mod CreateCertificate;
#[cfg(feature = "CreateCustomRule")]
pub mod CreateCustomRule;
#[cfg(feature = "CreateGeoipRule")]
pub mod CreateGeoipRule;
#[cfg(feature = "CreateHost")]
pub mod CreateHost;
#[cfg(feature = "CreateIgnoreRule")]
pub mod CreateIgnoreRule;
#[cfg(feature = "CreateInstance")]
pub mod CreateInstance;
#[cfg(feature = "CreateIpGroup")]
pub mod CreateIpGroup;
#[cfg(feature = "CreateIpReputationRule")]
pub mod CreateIpReputationRule;
#[cfg(feature = "CreatePolicy")]
pub mod CreatePolicy;
#[cfg(feature = "CreatePremiumHost")]
pub mod CreatePremiumHost;
#[cfg(feature = "CreatePrepaidCloudWaf")]
pub mod CreatePrepaidCloudWaf;
#[cfg(feature = "CreatePrivacyRule")]
pub mod CreatePrivacyRule;
#[cfg(feature = "CreatePunishmentRule")]
pub mod CreatePunishmentRule;
#[cfg(feature = "CreateValueList")]
pub mod CreateValueList;
#[cfg(feature = "CreateWhiteblackipRule")]
pub mod CreateWhiteblackipRule;
#[cfg(feature = "DeleteAnticrawlerRule")]
pub mod DeleteAnticrawlerRule;
#[cfg(feature = "DeleteAntileakageRule")]
pub mod DeleteAntileakageRule;
#[cfg(feature = "DeleteAntitamperRule")]
pub mod DeleteAntitamperRule;
#[cfg(feature = "DeleteCcRule")]
pub mod DeleteCcRule;
#[cfg(feature = "DeleteCertificate")]
pub mod DeleteCertificate;
#[cfg(feature = "DeleteCustomRule")]
pub mod DeleteCustomRule;
#[cfg(feature = "DeleteGeoipRule")]
pub mod DeleteGeoipRule;
#[cfg(feature = "DeleteHost")]
pub mod DeleteHost;
#[cfg(feature = "DeleteIgnoreRule")]
pub mod DeleteIgnoreRule;
#[cfg(feature = "DeleteInstance")]
pub mod DeleteInstance;
#[cfg(feature = "DeleteIpGroup")]
pub mod DeleteIpGroup;
#[cfg(feature = "DeleteIpReputationRule")]
pub mod DeleteIpReputationRule;
#[cfg(feature = "DeletePolicy")]
pub mod DeletePolicy;
#[cfg(feature = "DeletePremiumHost")]
pub mod DeletePremiumHost;
#[cfg(feature = "DeletePrivacyRule")]
pub mod DeletePrivacyRule;
#[cfg(feature = "DeletePunishmentRule")]
pub mod DeletePunishmentRule;
#[cfg(feature = "DeleteValueList")]
pub mod DeleteValueList;
#[cfg(feature = "DeleteWhiteBlackIpRule")]
pub mod DeleteWhiteBlackIpRule;
#[cfg(feature = "ListAnticrawlerRules")]
pub mod ListAnticrawlerRules;
#[cfg(feature = "ListAntileakageRules")]
pub mod ListAntileakageRules;
#[cfg(feature = "ListAntitamperRule")]
pub mod ListAntitamperRule;
#[cfg(feature = "ListAttackActionTypes")]
pub mod ListAttackActionTypes;
#[cfg(feature = "ListBandwidthTimeline")]
pub mod ListBandwidthTimeline;
#[cfg(feature = "ListBotMRequestDistribution")]
pub mod ListBotMRequestDistribution;
#[cfg(feature = "ListBotMScoreDistribution")]
pub mod ListBotMScoreDistribution;
#[cfg(feature = "ListBotMTimeline")]
pub mod ListBotMTimeline;
#[cfg(feature = "ListBotMTopnRequest")]
pub mod ListBotMTopnRequest;
#[cfg(feature = "ListCcRules")]
pub mod ListCcRules;
#[cfg(feature = "ListCertificates")]
pub mod ListCertificates;
#[cfg(feature = "ListCompositeHosts")]
pub mod ListCompositeHosts;
#[cfg(feature = "ListCustomRules")]
pub mod ListCustomRules;
#[cfg(feature = "ListEvent")]
pub mod ListEvent;
#[cfg(feature = "ListGeoipRule")]
pub mod ListGeoipRule;
#[cfg(feature = "ListHost")]
pub mod ListHost;
#[cfg(feature = "ListHostRoute")]
pub mod ListHostRoute;
#[cfg(feature = "ListIgnoreRule")]
pub mod ListIgnoreRule;
#[cfg(feature = "ListInstance")]
pub mod ListInstance;
#[cfg(feature = "ListInstanceTags")]
pub mod ListInstanceTags;
#[cfg(feature = "ListIpGroup")]
pub mod ListIpGroup;
#[cfg(feature = "ListIpReputationRules")]
pub mod ListIpReputationRules;
#[cfg(feature = "ListNoticeConfigs")]
pub mod ListNoticeConfigs;
#[cfg(feature = "ListOverviewsClassification")]
pub mod ListOverviewsClassification;
#[cfg(feature = "ListPolicy")]
pub mod ListPolicy;
#[cfg(feature = "ListPremiumHost")]
pub mod ListPremiumHost;
#[cfg(feature = "ListPrivacyRule")]
pub mod ListPrivacyRule;
#[cfg(feature = "ListProtectableResources")]
pub mod ListProtectableResources;
#[cfg(feature = "ListPunishmentRules")]
pub mod ListPunishmentRules;
#[cfg(feature = "ListQpsTimeline")]
pub mod ListQpsTimeline;
#[cfg(feature = "ListRequestTimeline")]
pub mod ListRequestTimeline;
#[cfg(feature = "ListResponseCodeTimeline")]
pub mod ListResponseCodeTimeline;
#[cfg(feature = "ListSecurityReportSubscriptions")]
pub mod ListSecurityReportSubscriptions;
#[cfg(feature = "ListStatistics")]
pub mod ListStatistics;
#[cfg(feature = "ListTopAbnormal")]
pub mod ListTopAbnormal;
#[cfg(feature = "ListTopDomains")]
pub mod ListTopDomains;
#[cfg(feature = "ListTopIp")]
pub mod ListTopIp;
#[cfg(feature = "ListTopUrl")]
pub mod ListTopUrl;
#[cfg(feature = "ListValueList")]
pub mod ListValueList;
#[cfg(feature = "ListWebBasicProtectionRules")]
pub mod ListWebBasicProtectionRules;
#[cfg(feature = "ListWhiteblackipRule")]
pub mod ListWhiteblackipRule;
#[cfg(feature = "MigrateCompositeHosts")]
pub mod MigrateCompositeHosts;
#[cfg(feature = "RenameInstance")]
pub mod RenameInstance;
#[cfg(feature = "ShowAnticrawlerRule")]
pub mod ShowAnticrawlerRule;
#[cfg(feature = "ShowAntileakageRule")]
pub mod ShowAntileakageRule;
#[cfg(feature = "ShowAntitamperRule")]
pub mod ShowAntitamperRule;
#[cfg(feature = "ShowCcRule")]
pub mod ShowCcRule;
#[cfg(feature = "ShowCertificate")]
pub mod ShowCertificate;
#[cfg(feature = "ShowCompositeHost")]
pub mod ShowCompositeHost;
#[cfg(feature = "ShowConsoleConfig")]
pub mod ShowConsoleConfig;
#[cfg(feature = "ShowCustomRule")]
pub mod ShowCustomRule;
#[cfg(feature = "ShowEvent")]
pub mod ShowEvent;
#[cfg(feature = "ShowGeoipRule")]
pub mod ShowGeoipRule;
#[cfg(feature = "ShowHost")]
pub mod ShowHost;
#[cfg(feature = "ShowHostStatus")]
pub mod ShowHostStatus;
