#[cfg(feature = "ApplyCertificateToHost")]
pub mod ApplyCertificateToHost;
#[cfg(feature = "BatchCreateAntileakageRule")]
pub mod BatchCreateAntileakageRule;
#[cfg(feature = "BatchCreateAntiTamperRule")]
pub mod BatchCreateAntiTamperRule;
#[cfg(feature = "BatchCreateCcRule")]
pub mod BatchCreateCcRule;
#[cfg(feature = "BatchCreateCustomRule")]
pub mod BatchCreateCustomRule;
#[cfg(feature = "BatchCreateGeoIpRule")]
pub mod BatchCreateGeoIpRule;
#[cfg(feature = "BatchCreateIgnoreRule")]
pub mod BatchCreateIgnoreRule;
#[cfg(feature = "BatchCreateIpReputationRule")]
pub mod BatchCreateIpReputationRule;
#[cfg(feature = "BatchCreatePrivacyRule")]
pub mod BatchCreatePrivacyRule;
#[cfg(feature = "BatchCreateWhiteblackipRule")]
pub mod BatchCreateWhiteblackipRule;
#[cfg(feature = "BatchDeleteAlertNoticeConfig")]
pub mod BatchDeleteAlertNoticeConfig;
#[cfg(feature = "BatchDeleteCompositeHosts")]
pub mod BatchDeleteCompositeHosts;
#[cfg(feature = "BatchDeletePolicies")]
pub mod BatchDeletePolicies;
#[cfg(feature = "BatchDeleteRules")]
pub mod BatchDeleteRules;
#[cfg(feature = "BatchUpdateAntileakageRules")]
pub mod BatchUpdateAntileakageRules;
#[cfg(feature = "BatchUpdateAntitamperRules")]
pub mod BatchUpdateAntitamperRules;
#[cfg(feature = "BatchUpdateCcRules")]
pub mod BatchUpdateCcRules;
#[cfg(feature = "BatchUpdateCustomRules")]
pub mod BatchUpdateCustomRules;
#[cfg(feature = "BatchUpdateGeoipRules")]
pub mod BatchUpdateGeoipRules;
#[cfg(feature = "BatchUpdateIgnoreRules")]
pub mod BatchUpdateIgnoreRules;
#[cfg(feature = "BatchUpdateIpReputationRules")]
pub mod BatchUpdateIpReputationRules;
#[cfg(feature = "BatchUpdatePrivacyRules")]
pub mod BatchUpdatePrivacyRules;
#[cfg(feature = "BatchUpdateWhiteblackipRules")]
pub mod BatchUpdateWhiteblackipRules;
#[cfg(feature = "ChangePrepaidCloudWaf")]
pub mod ChangePrepaidCloudWaf;
#[cfg(feature = "CheckAgency")]
pub mod CheckAgency;
#[cfg(feature = "ConfirmApplicationTypes")]
pub mod ConfirmApplicationTypes;
#[cfg(feature = "ConfirmAsyncJob")]
pub mod ConfirmAsyncJob;
#[cfg(feature = "ConfirmDnsDomain")]
pub mod ConfirmDnsDomain;
#[cfg(feature = "ConfirmIpReputationRule")]
pub mod ConfirmIpReputationRule;
#[cfg(feature = "ConfirmPolicyAntileakageMap")]
pub mod ConfirmPolicyAntileakageMap;
#[cfg(feature = "ConfirmPolicyIpReputationMap")]
pub mod ConfirmPolicyIpReputationMap;
#[cfg(feature = "ConfirmProtectionTypes")]
pub mod ConfirmProtectionTypes;
#[cfg(feature = "ConfirmThreatMap")]
pub mod ConfirmThreatMap;
#[cfg(feature = "ConfirmTmsResourceInstances")]
pub mod ConfirmTmsResourceInstances;
#[cfg(feature = "ConfirmUserBundle")]
pub mod ConfirmUserBundle;
#[cfg(feature = "CopyPolicyById")]
pub mod CopyPolicyById;
#[cfg(feature = "CreateAgency")]
pub mod CreateAgency;
#[cfg(feature = "CreateAlertNoticeConfig")]
pub mod CreateAlertNoticeConfig;
#[cfg(feature = "CreateAnticrawlerRule")]
pub mod CreateAnticrawlerRule;
#[cfg(feature = "CreateAntileakageRule")]
pub mod CreateAntileakageRule;
#[cfg(feature = "CreateAntiTamperRule")]
pub mod CreateAntiTamperRule;
#[cfg(feature = "CreateCcRule")]
pub mod CreateCcRule;
#[cfg(feature = "CreateCertificate")]
pub mod CreateCertificate;
#[cfg(feature = "CreateCustomRule")]
pub mod CreateCustomRule;
#[cfg(feature = "CreateEventExportJob")]
pub mod CreateEventExportJob;
#[cfg(feature = "CreateGeoipRule")]
pub mod CreateGeoipRule;
#[cfg(feature = "CreateHost")]
pub mod CreateHost;
#[cfg(feature = "CreateIgnoreRule")]
pub mod CreateIgnoreRule;
#[cfg(feature = "CreateInstance")]
pub mod CreateInstance;
#[cfg(feature = "CreateIpGroup")]
pub mod CreateIpGroup;
#[cfg(feature = "CreateIpReputationRule")]
pub mod CreateIpReputationRule;
#[cfg(feature = "CreatePolicy")]
pub mod CreatePolicy;
#[cfg(feature = "CreatePremiumHost")]
pub mod CreatePremiumHost;
#[cfg(feature = "CreatePrepaidCloudWaf")]
pub mod CreatePrepaidCloudWaf;
#[cfg(feature = "CreatePrivacyRule")]
pub mod CreatePrivacyRule;
#[cfg(feature = "CreatePunishmentRule")]
pub mod CreatePunishmentRule;
#[cfg(feature = "CreateQuickAccessDomain")]
pub mod CreateQuickAccessDomain;
#[cfg(feature = "CreateSecurityReportSubscription")]
pub mod CreateSecurityReportSubscription;
#[cfg(feature = "CreateValueList")]
pub mod CreateValueList;
#[cfg(feature = "CreateWhiteblackipRule")]
pub mod CreateWhiteblackipRule;
#[cfg(feature = "DeleteAgency")]
pub mod DeleteAgency;
#[cfg(feature = "DeleteAnticrawlerRule")]
pub mod DeleteAnticrawlerRule;
#[cfg(feature = "DeleteAntileakageRule")]
pub mod DeleteAntileakageRule;
#[cfg(feature = "DeleteAntitamperRule")]
pub mod DeleteAntitamperRule;
#[cfg(feature = "DeleteCcRule")]
pub mod DeleteCcRule;
#[cfg(feature = "DeleteCertificate")]
pub mod DeleteCertificate;
#[cfg(feature = "DeleteCustomRule")]
pub mod DeleteCustomRule;
#[cfg(feature = "DeleteGeoipRule")]
pub mod DeleteGeoipRule;
#[cfg(feature = "DeleteHost")]
pub mod DeleteHost;
#[cfg(feature = "DeleteIgnoreRule")]
pub mod DeleteIgnoreRule;
#[cfg(feature = "DeleteInstance")]
pub mod DeleteInstance;
#[cfg(feature = "DeleteIpGroup")]
pub mod DeleteIpGroup;
#[cfg(feature = "DeleteIpReputationRule")]
pub mod DeleteIpReputationRule;
#[cfg(feature = "DeletePolicy")]
pub mod DeletePolicy;
#[cfg(feature = "DeletePremiumHost")]
pub mod DeletePremiumHost;
#[cfg(feature = "DeletePrivacyRule")]
pub mod DeletePrivacyRule;
#[cfg(feature = "DeletePunishmentRule")]
pub mod DeletePunishmentRule;
#[cfg(feature = "DeleteSecurityReportSubscription")]
pub mod DeleteSecurityReportSubscription;
#[cfg(feature = "DeleteValueList")]
pub mod DeleteValueList;
#[cfg(feature = "DeleteWhiteBlackIpRule")]
pub mod DeleteWhiteBlackIpRule;
#[cfg(feature = "ListAnticrawlerRules")]
pub mod ListAnticrawlerRules;
#[cfg(feature = "ListAntileakagePolicyRules")]
pub mod ListAntileakagePolicyRules;
#[cfg(feature = "ListAntileakageRules")]
pub mod ListAntileakageRules;
#[cfg(feature = "ListAntiTamperPolicyRules")]
pub mod ListAntiTamperPolicyRules;
#[cfg(feature = "ListAntitamperRule")]
pub mod ListAntitamperRule;
#[cfg(feature = "ListAttackActionTypes")]
pub mod ListAttackActionTypes;
#[cfg(feature = "ListBandwidthTimeline")]
pub mod ListBandwidthTimeline;
#[cfg(feature = "ListCcPolicyRules")]
pub mod ListCcPolicyRules;
#[cfg(feature = "ListCcRules")]
pub mod ListCcRules;
#[cfg(feature = "ListCertificates")]
pub mod ListCertificates;
#[cfg(feature = "ListCompositeHosts")]
pub mod ListCompositeHosts;
#[cfg(feature = "ListCustomPolicyRules")]
pub mod ListCustomPolicyRules;
#[cfg(feature = "ListCustomRules")]
pub mod ListCustomRules;
#[cfg(feature = "ListEvent")]
pub mod ListEvent;
#[cfg(feature = "ListEventLog")]
pub mod ListEventLog;
#[cfg(feature = "ListGeoIpPolicyRules")]
pub mod ListGeoIpPolicyRules;
#[cfg(feature = "ListGeoipRule")]
pub mod ListGeoipRule;
#[cfg(feature = "ListHost")]
pub mod ListHost;
#[cfg(feature = "ListHostRoute")]
pub mod ListHostRoute;
#[cfg(feature = "ListIgnorePolicyRules")]
pub mod ListIgnorePolicyRules;
