[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
ShowBatchCheckinUsingPost = []
ShowBatchCheckoutAndUpdateUsingPost = []
ShowBatchCheckoutUsingPost = []
ShowBatchCreateUsingPost = []
ShowBatchDeleteBranchUsingPost = []
ShowBatchDeleteUsingPost = []
ShowBatchGetUsingPost = []
ShowBatchLogicalDeleteBranchUsingPost = []
ShowBatchLogicalDeleteUsingPost = []
ShowBatchReviseAndUpdateUsingPost = []
ShowBatchReviseUsingPost = []
ShowBatchUndoCheckoutByAdminUsingPost = []
ShowBatchUndoCheckoutUsingPost = []
ShowBatchUpdateAndCheckinUsingPost = []
ShowBatchUpdateByAdminUsingPost = []
ShowBatchUpdateUsingPost = []
ShowBatchUpdateVersionUsingPost = []
ShowCheckinUsingPost = []
ShowCheckoutAndUpdateUsingPost = []
ShowCheckoutUsingPost = []
ShowCompareBusinessVersionUsingPost = []
ShowCountUsingPost = []
ShowCreateUsingPost = []
ShowDeleteBranchUsingPost = []
ShowDeleteByConditionUsingPost = []
ShowDeleteLatestVersionUsingPost = []
ShowDeleteUsingPost = []
ShowFindUsingPost = []
ShowGetAllVersionsUsingPost = []
ShowGetByUniqueKeyUsingPost = []
ShowGetUsingPost = []
ShowGetVersionByMasterUsingPost = []
ShowListUsingPost = []
ShowLogicalDeleteBranchUsingPost = []
ShowLogicalDeleteByConditionUsingPost = []
ShowLogicalDeleteLatestVersionUsingPost = []
ShowLogicalDeleteUsingPost = []
ShowQueryUsingPost = []
ShowReviseAndUpdateUsingPost = []
ShowReviseUsingPost = []
ShowSaveAllUsingPost = []
ShowSaveAsUsingPost = []
ShowSaveUsingPost = []
ShowSelectUsingPost = []
ShowStaticsUsingPost = []
ShowUndoCheckoutByAdminUsingPost = []
ShowUndoCheckoutUsingPost = []
ShowUpdateAndCheckinUsingPost = []
ShowUpdateByAdminUsingPost = []
ShowUpdateByConditionUsingPost = []
ShowUpdateUsingPost = []
full = ["ShowBatchCheckinUsingPost", "ShowBatchCheckoutAndUpdateUsingPost", "ShowBatchCheckoutUsingPost", "ShowBatchCreateUsingPost", "ShowBatchDeleteBranchUsingPost", "ShowBatchDeleteUsingPost", "ShowBatchGetUsingPost", "ShowBatchLogicalDeleteBranchUsingPost", "ShowBatchLogicalDeleteUsingPost", "ShowBatchReviseAndUpdateUsingPost", "ShowBatchReviseUsingPost", "ShowBatchUndoCheckoutByAdminUsingPost", "ShowBatchUndoCheckoutUsingPost", "ShowBatchUpdateAndCheckinUsingPost", "ShowBatchUpdateByAdminUsingPost", "ShowBatchUpdateUsingPost", "ShowBatchUpdateVersionUsingPost", "ShowCheckinUsingPost", "ShowCheckoutAndUpdateUsingPost", "ShowCheckoutUsingPost", "ShowCompareBusinessVersionUsingPost", "ShowCountUsingPost", "ShowCreateUsingPost", "ShowDeleteBranchUsingPost", "ShowDeleteByConditionUsingPost", "ShowDeleteLatestVersionUsingPost", "ShowDeleteUsingPost", "ShowFindUsingPost", "ShowGetAllVersionsUsingPost", "ShowGetByUniqueKeyUsingPost", "ShowGetUsingPost", "ShowGetVersionByMasterUsingPost", "ShowListUsingPost", "ShowLogicalDeleteBranchUsingPost", "ShowLogicalDeleteByConditionUsingPost", "ShowLogicalDeleteLatestVersionUsingPost", "ShowLogicalDeleteUsingPost", "ShowQueryUsingPost", "ShowReviseAndUpdateUsingPost", "ShowReviseUsingPost", "ShowSaveAllUsingPost", "ShowSaveAsUsingPost", "ShowSaveUsingPost", "ShowSelectUsingPost", "ShowStaticsUsingPost", "ShowUndoCheckoutByAdminUsingPost", "ShowUndoCheckoutUsingPost", "ShowUpdateAndCheckinUsingPost", "ShowUpdateByAdminUsingPost", "ShowUpdateByConditionUsingPost", "ShowUpdateUsingPost"]

[lib]
name = "huawei_cloud_api_definitions_iDMEClassicAPI"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-iDMEClassicAPI"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
