[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
BatchCreateUsingPost = []
BatchDeleteLogicalUsingPost = []
BatchDeleteUsingPost = []
BatchShowGetUsingPost = []
BatchUpdateUsingPost = []
CountUsingPost = []
CreateUsingPost = []
DeleteByConditionUsingPost = []
DeleteUsingPost = []
ListQueryUsingPost = []
ListSelectUsingPost = []
ListUsingPost = []
SaveAllUsingPost = []
SaveAsUsingPost = []
SaveUsingPost = []
ShowFindUsingPost = []
ShowGetByUniqueKey = []
ShowGetUsingPost = []
ShowLogicalDeleteByConditionUsingPost = []
ShowLogicalDeleteUsingPost = []
ShowStaticsUsingPost = []
UpdateByConditionUsingPost = []
UpdateUsingPost = []
full = ["BatchCreateUsingPost", "BatchDeleteLogicalUsingPost", "BatchDeleteUsingPost", "BatchShowGetUsingPost", "BatchUpdateUsingPost", "CountUsingPost", "CreateUsingPost", "DeleteByConditionUsingPost", "DeleteUsingPost", "ListQueryUsingPost", "ListSelectUsingPost", "ListUsingPost", "SaveAllUsingPost", "SaveAsUsingPost", "SaveUsingPost", "ShowFindUsingPost", "ShowGetByUniqueKey", "ShowGetUsingPost", "ShowLogicalDeleteByConditionUsingPost", "ShowLogicalDeleteUsingPost", "ShowStaticsUsingPost", "UpdateByConditionUsingPost", "UpdateUsingPost"]

[lib]
name = "huawei_cloud_api_definitions_iDMEClassicAPI"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-iDMEClassicAPI"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
