[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddTag = []
AddToCategory = []
BatchAddChildNode = []
BatchCheckin = []
BatchCheckout = []
BatchCheckoutAndUpdate = []
BatchCheckoutUndo = []
BatchCheckoutUndoByAdmin = []
BatchCreateShareDocs = []
BatchCreateUsingPost = []
BatchCreateView = []
BatchDeleteBranch = []
BatchDeleteLatestVersion = []
BatchDeleteLogicalBranch = []
BatchDeleteLogicalLatestVersion = []
BatchDeleteLogicalUsingPost = []
BatchDeleteShareDocs = []
BatchDeleteStructuredDocument = []
BatchDeleteUsingPost = []
BatchExecuteRevise = []
BatchRemoveChildNode = []
BatchShowGetUsingPost = []
BatchUpdateAndCheckin = []
BatchUpdateAndRevise = []
BatchUpdateByAdmin = []
BatchUpdateDocument = []
BatchUpdateUsingPost = []
BatchUpdateVersion = []
Checkin = []
Checkout = []
CheckoutAndUpdate = []
CheckoutUndo = []
CheckoutUndoByAdmin = []
CollectHistoryData = []
CompareBusinessVersion = []
CompareVersion = []
CountUsingPost = []
CreateDocument = []
CreateUsingPost = []
CreateView = []
DeleteBranch = []
DeleteByConditionUsingPost = []
DeleteLatestVersion = []
DeleteLogicalBranch = []
DeleteLogicalLatestVersion = []
DeleteTarget = []
DeleteUsingPost = []
DisableDataInstance = []
EnableDataInstance = []
ExecuteRevise = []
GenerateBusinessCode = []
ListAllVersions = []
ListBatchQueryRelatedObjects = []
ListGetAllParentList = []
ListGetChildList = []
ListHistoryData = []
ListQueryDocuments = []
ListQueryRelatedObjects = []
ListQueryRelationship = []
ListQueryShareDocs = []
ListQueryTarget = []
ListQueryUsingPost = []
ListSelectUsingPost = []
ListUsingPost = []
Refresh = []
RemoveFromCategory = []
RemoveTag = []
SaveAllUsingPost = []
SaveAsUsingPost = []
SaveUsingPost = []
ShowFindUsingPost = []
ShowGetByUniqueKey = []
ShowGetParent = []
ShowGetRoot = []
ShowGetTokens = []
ShowGetUsingPost = []
ShowLogicalDeleteByConditionUsingPost = []
ShowLogicalDeleteUsingPost = []
ShowStaticsUsingPost = []
ShowTag = []
ShowVersionByMaster = []
SwitchLifecycleTemplate = []
UpdateAndCheckin = []
UpdateAndRevise = []
UpdateByAdmin = []
UpdateByConditionUsingPost = []
UpdateDocument = []
UpdateState = []
UpdateUsingPost = []
UpdateView = []
full = ["AddTag", "AddToCategory", "BatchAddChildNode", "BatchCheckin", "BatchCheckout", "BatchCheckoutAndUpdate", "BatchCheckoutUndo", "BatchCheckoutUndoByAdmin", "BatchCreateShareDocs", "BatchCreateUsingPost", "BatchCreateView", "BatchDeleteBranch", "BatchDeleteLatestVersion", "BatchDeleteLogicalBranch", "BatchDeleteLogicalLatestVersion", "BatchDeleteLogicalUsingPost", "BatchDeleteShareDocs", "BatchDeleteStructuredDocument", "BatchDeleteUsingPost", "BatchExecuteRevise", "BatchRemoveChildNode", "BatchShowGetUsingPost", "BatchUpdateAndCheckin", "BatchUpdateAndRevise", "BatchUpdateByAdmin", "BatchUpdateDocument", "BatchUpdateUsingPost", "BatchUpdateVersion", "Checkin", "Checkout", "CheckoutAndUpdate", "CheckoutUndo", "CheckoutUndoByAdmin", "CollectHistoryData", "CompareBusinessVersion", "CompareVersion", "CountUsingPost", "CreateDocument", "CreateUsingPost", "CreateView", "DeleteBranch", "DeleteByConditionUsingPost", "DeleteLatestVersion", "DeleteLogicalBranch", "DeleteLogicalLatestVersion", "DeleteTarget", "DeleteUsingPost", "DisableDataInstance", "EnableDataInstance", "ExecuteRevise", "GenerateBusinessCode", "ListAllVersions", "ListBatchQueryRelatedObjects", "ListGetAllParentList", "ListGetChildList", "ListHistoryData", "ListQueryDocuments", "ListQueryRelatedObjects", "ListQueryRelationship", "ListQueryShareDocs", "ListQueryTarget", "ListQueryUsingPost", "ListSelectUsingPost", "ListUsingPost", "Refresh", "RemoveFromCategory", "RemoveTag", "SaveAllUsingPost", "SaveAsUsingPost", "SaveUsingPost", "ShowFindUsingPost", "ShowGetByUniqueKey", "ShowGetParent", "ShowGetRoot", "ShowGetTokens", "ShowGetUsingPost", "ShowLogicalDeleteByConditionUsingPost", "ShowLogicalDeleteUsingPost", "ShowStaticsUsingPost", "ShowTag", "ShowVersionByMaster", "SwitchLifecycleTemplate", "UpdateAndCheckin", "UpdateAndRevise", "UpdateByAdmin", "UpdateByConditionUsingPost", "UpdateDocument", "UpdateState", "UpdateUsingPost", "UpdateView"]

[lib]
name = "huawei_cloud_api_definitions_iDMEClassicAPI"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-iDMEClassicAPI"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
