[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
CollectAllResourcesSummary = []
CollectConformancePackComplianceSummary = []
CollectTrackedResourcesSummary = []
CountAllResources = []
CountTrackedResources = []
CreateAggregationAuthorization = []
CreateConfigurationAggregator = []
CreateConformancePack = []
CreateOrganizationConformancePack = []
CreateOrganizationPolicyAssignment = []
CreatePolicyAssignments = []
CreateStoredQuery = []
CreateTrackerConfig = []
DeleteAggregationAuthorization = []
DeleteConfigurationAggregator = []
DeleteConformancePack = []
DeleteOrganizationConformancePack = []
DeleteOrganizationPolicyAssignment = []
DeletePendingAggregationRequest = []
DeletePolicyAssignment = []
DeleteStoredQuery = []
DeleteTrackerConfig = []
DisablePolicyAssignment = []
EnablePolicyAssignment = []
ListAggregateComplianceByPolicyAssignment = []
ListAggregateDiscoveredResources = []
ListAggregationAuthorizations = []
ListAllResources = []
ListAllTags = []
ListBuiltInConformancePackTemplates = []
ListBuiltInPolicyDefinitions = []
ListConfigurationAggregators = []
ListConformancePackComplianceByPackId = []
ListConformancePackComplianceDetailsByPackId = []
ListConformancePackComplianceScores = []
ListConformancePacks = []
ListOrganizationConformancePackStatuses = []
ListOrganizationConformancePacks = []
ListOrganizationPolicyAssignments = []
ListPendingAggregationRequests = []
ListPolicyAssignments = []
ListPolicyStatesByAssignmentId = []
ListPolicyStatesByDomainId = []
ListPolicyStatesByResourceId = []
ListProviders = []
ListRegions = []
ListResources = []
ListSchemas = []
ListStoredQueries = []
ListTrackedResourceTags = []
ListTrackedResources = []
RunAggregateResourceQuery = []
RunEvaluationByPolicyAssignmentId = []
RunQuery = []
ShowAggregateComplianceDetailsByPolicyAssignment = []
ShowAggregateDiscoveredResourceCounts = []
ShowAggregatePolicyAssignmentDetail = []
ShowAggregatePolicyStateComplianceSummary = []
ShowAggregateResourceConfig = []
ShowBuiltInConformancePackTemplate = []
ShowBuiltInPolicyDefinition = []
ShowConfigurationAggregator = []
ShowConfigurationAggregatorSourcesStatus = []
ShowConformancePack = []
ShowEvaluationStateByAssignmentId = []
ShowOrganizationConformancePack = []
ShowOrganizationConformancePackDetailedStatuses = []
ShowOrganizationPolicyAssignment = []
ShowOrganizationPolicyAssignmentDetailedStatus = []
ShowOrganizationPolicyAssignmentStatuses = []
ShowPolicyAssignment = []
ShowResourceById = []
ShowResourceDetail = []
ShowResourceHistory = []
ShowResourceRelations = []
ShowResourceRelationsDetail = []
ShowStoredQuery = []
ShowTrackedResourceDetail = []
ShowTrackerConfig = []
UpdateConfigurationAggregator = []
UpdatePolicyAssignment = []
UpdatePolicyState = []
UpdateStoredQuery = []
full = ["CollectAllResourcesSummary", "CollectConformancePackComplianceSummary", "CollectTrackedResourcesSummary", "CountAllResources", "CountTrackedResources", "CreateAggregationAuthorization", "CreateConfigurationAggregator", "CreateConformancePack", "CreateOrganizationConformancePack", "CreateOrganizationPolicyAssignment", "CreatePolicyAssignments", "CreateStoredQuery", "CreateTrackerConfig", "DeleteAggregationAuthorization", "DeleteConfigurationAggregator", "DeleteConformancePack", "DeleteOrganizationConformancePack", "DeleteOrganizationPolicyAssignment", "DeletePendingAggregationRequest", "DeletePolicyAssignment", "DeleteStoredQuery", "DeleteTrackerConfig", "DisablePolicyAssignment", "EnablePolicyAssignment", "ListAggregateComplianceByPolicyAssignment", "ListAggregateDiscoveredResources", "ListAggregationAuthorizations", "ListAllResources", "ListAllTags", "ListBuiltInConformancePackTemplates", "ListBuiltInPolicyDefinitions", "ListConfigurationAggregators", "ListConformancePackComplianceByPackId", "ListConformancePackComplianceDetailsByPackId", "ListConformancePackComplianceScores", "ListConformancePacks", "ListOrganizationConformancePacks", "ListOrganizationConformancePackStatuses", "ListOrganizationPolicyAssignments", "ListPendingAggregationRequests", "ListPolicyAssignments", "ListPolicyStatesByAssignmentId", "ListPolicyStatesByDomainId", "ListPolicyStatesByResourceId", "ListProviders", "ListRegions", "ListResources", "ListSchemas", "ListStoredQueries", "ListTrackedResources", "ListTrackedResourceTags", "RunAggregateResourceQuery", "RunEvaluationByPolicyAssignmentId", "RunQuery", "ShowAggregateComplianceDetailsByPolicyAssignment", "ShowAggregateDiscoveredResourceCounts", "ShowAggregatePolicyAssignmentDetail", "ShowAggregatePolicyStateComplianceSummary", "ShowAggregateResourceConfig", "ShowBuiltInConformancePackTemplate", "ShowBuiltInPolicyDefinition", "ShowConfigurationAggregator", "ShowConfigurationAggregatorSourcesStatus", "ShowConformancePack", "ShowEvaluationStateByAssignmentId", "ShowOrganizationConformancePack", "ShowOrganizationConformancePackDetailedStatuses", "ShowOrganizationPolicyAssignment", "ShowOrganizationPolicyAssignmentDetailedStatus", "ShowOrganizationPolicyAssignmentStatuses", "ShowPolicyAssignment", "ShowResourceById", "ShowResourceDetail", "ShowResourceHistory", "ShowResourceRelations", "ShowResourceRelationsDetail", "ShowStoredQuery", "ShowTrackedResourceDetail", "ShowTrackerConfig", "UpdateConfigurationAggregator", "UpdatePolicyAssignment", "UpdatePolicyState", "UpdateStoredQuery"]

[lib]
name = "huawei_cloud_api_definitions_Config"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-Config"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
