[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
BatchUpdateTasks = []
CheckPrefix = []
CreateSyncEvents = []
CreateSyncTask = []
CreateTask = []
CreateTaskGroup = []
DeleteSyncTask = []
DeleteTask = []
DeleteTaskGroup = []
ListApiVersions = []
ListSyncTaskStatistic = []
ListSyncTasks = []
ListTaskGroup = []
ListTasks = []
RetryTaskGroup = []
ShowApiInfo = []
ShowBucketList = []
ShowBucketObjects = []
ShowBucketRegion = []
ShowCdnInfo = []
ShowCloudType = []
ShowRegionInfo = []
ShowSyncTask = []
ShowTask = []
ShowTaskGroup = []
StartSyncTask = []
StartTask = []
StartTaskGroup = []
StopSyncTask = []
StopTask = []
StopTaskGroup = []
UpdateBandwidthPolicy = []
UpdateTaskGroup = []
full = ["BatchUpdateTasks", "CheckPrefix", "CreateSyncEvents", "CreateSyncTask", "CreateTask", "CreateTaskGroup", "DeleteSyncTask", "DeleteTask", "DeleteTaskGroup", "ListApiVersions", "ListSyncTasks", "ListSyncTaskStatistic", "ListTaskGroup", "ListTasks", "RetryTaskGroup", "ShowApiInfo", "ShowBucketList", "ShowBucketObjects", "ShowBucketRegion", "ShowCdnInfo", "ShowCloudType", "ShowRegionInfo", "ShowSyncTask", "ShowTask", "ShowTaskGroup", "StartSyncTask", "StartTask", "StartTaskGroup", "StopSyncTask", "StopTask", "StopTaskGroup", "UpdateBandwidthPolicy", "UpdateTaskGroup"]

[lib]
name = "huawei_cloud_api_definitions_OMS"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-OMS"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
