[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
CreateAgency = []
CreateApplication = []
CreateCertificate = []
CreateComponent = []
CreateComponentConfiguration = []
CreateComponentWithConfiguration = []
CreateDomain = []
CreateEnvironment = []
CreateMonitorSystem = []
CreateNoticeRule = []
CreateTimerRule = []
CreateVolume = []
CreateVpcEgress = []
DeleteApplication = []
DeleteCertificate = []
DeleteComponent = []
DeleteComponentConfiguration = []
DeleteDomain = []
DeleteEnvironment = []
DeleteNoticeRule = []
DeleteTimerRule = []
DeleteVolume = []
DeleteVpcEgress = []
ExecuteAction = []
ListAgencies = []
ListApplications = []
ListCertificates = []
ListComponentConfigurations = []
ListComponentInstances = []
ListComponentSnapshots = []
ListComponents = []
ListDomains = []
ListEips = []
ListEnvironments = []
ListNoticeRules = []
ListTimerRules = []
ListVolumes = []
ListVpcEgress = []
RetryJob = []
ShowApplication = []
ShowComponent = []
ShowExecutionResult = []
ShowJob = []
ShowMonitorSystem = []
ShowNoticeRule = []
UpdateCertificate = []
UpdateComponent = []
UpdateEip = []
UpdateMonitorSystem = []
UpdateNoticeRule = []
UpdateTimerRule = []
full = ["CreateAgency", "CreateApplication", "CreateCertificate", "CreateComponent", "CreateComponentConfiguration", "CreateComponentWithConfiguration", "CreateDomain", "CreateEnvironment", "CreateMonitorSystem", "CreateNoticeRule", "CreateTimerRule", "CreateVolume", "CreateVpcEgress", "DeleteApplication", "DeleteCertificate", "DeleteComponent", "DeleteComponentConfiguration", "DeleteDomain", "DeleteEnvironment", "DeleteNoticeRule", "DeleteTimerRule", "DeleteVolume", "DeleteVpcEgress", "ExecuteAction", "ListAgencies", "ListApplications", "ListCertificates", "ListComponentConfigurations", "ListComponentInstances", "ListComponents", "ListComponentSnapshots", "ListDomains", "ListEips", "ListEnvironments", "ListNoticeRules", "ListTimerRules", "ListVolumes", "ListVpcEgress", "RetryJob", "ShowApplication", "ShowComponent", "ShowExecutionResult", "ShowJob", "ShowMonitorSystem", "ShowNoticeRule", "UpdateCertificate", "UpdateComponent", "UpdateEip", "UpdateMonitorSystem", "UpdateNoticeRule", "UpdateTimerRule"]

[lib]
name = "huawei_cloud_api_definitions_CAE"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-CAE"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
