#[cfg(feature = "AddDesktopPoolVolumes")]
pub mod AddDesktopPoolVolumes;
#[cfg(feature = "AddDesktopSubResources")]
pub mod AddDesktopSubResources;
#[cfg(feature = "AddDesktopVolumes")]
pub mod AddDesktopVolumes;
#[cfg(feature = "AddMetricNotifyRule")]
pub mod AddMetricNotifyRule;
#[cfg(feature = "AddOu")]
pub mod AddOu;
#[cfg(feature = "AddRestrictedRule")]
pub mod AddRestrictedRule;
#[cfg(feature = "AddSite")]
pub mod AddSite;
#[cfg(feature = "AddVolumes")]
pub mod AddVolumes;
#[cfg(feature = "ApplyDesktopsInternet")]
pub mod ApplyDesktopsInternet;
#[cfg(feature = "ApplyInternet")]
pub mod ApplyInternet;
#[cfg(feature = "ApplyModelConfig")]
pub mod ApplyModelConfig;
#[cfg(feature = "ApplySubnetBandwidth")]
pub mod ApplySubnetBandwidth;
#[cfg(feature = "ApplyWorkspace")]
pub mod ApplyWorkspace;
#[cfg(feature = "AssociateDesktopsEip")]
pub mod AssociateDesktopsEip;
#[cfg(feature = "AttachInstances")]
pub mod AttachInstances;
#[cfg(feature = "BatchAddDesktopsTags")]
pub mod BatchAddDesktopsTags;
#[cfg(feature = "BatchAssociateInstances")]
pub mod BatchAssociateInstances;
#[cfg(feature = "BatchAttachInstances")]
pub mod BatchAttachInstances;
#[cfg(feature = "BatchBindProviders")]
pub mod BatchBindProviders;
#[cfg(feature = "BatchChangeDesktopNetwork")]
pub mod BatchChangeDesktopNetwork;
#[cfg(feature = "BatchChangeTags")]
pub mod BatchChangeTags;
#[cfg(feature = "BatchCheckDesktopRejoinDomain")]
pub mod BatchCheckDesktopRejoinDomain;
#[cfg(feature = "BatchCreateDesktopSnapshot")]
pub mod BatchCreateDesktopSnapshot;
#[cfg(feature = "BatchCreateModel")]
pub mod BatchCreateModel;
#[cfg(feature = "BatchCreateUsers")]
pub mod BatchCreateUsers;
#[cfg(feature = "BatchDeleteAccessPolicies")]
pub mod BatchDeleteAccessPolicies;
#[cfg(feature = "BatchDeleteAppRules")]
pub mod BatchDeleteAppRules;
#[cfg(feature = "BatchDeleteApps")]
pub mod BatchDeleteApps;
#[cfg(feature = "BatchDeleteDesktopNamePolicy")]
pub mod BatchDeleteDesktopNamePolicy;
#[cfg(feature = "BatchDeleteDesktops")]
pub mod BatchDeleteDesktops;
#[cfg(feature = "BatchDeleteDesktopSnapshot")]
pub mod BatchDeleteDesktopSnapshot;
#[cfg(feature = "BatchDeleteDesktopsTags")]
pub mod BatchDeleteDesktopsTags;
#[cfg(feature = "BatchDeleteJobs")]
pub mod BatchDeleteJobs;
#[cfg(feature = "BatchDeleteModel")]
pub mod BatchDeleteModel;
#[cfg(feature = "BatchDeleteOtpDevices")]
pub mod BatchDeleteOtpDevices;
#[cfg(feature = "BatchDeleteProviders")]
pub mod BatchDeleteProviders;
#[cfg(feature = "BatchDeleteScheduledTasks")]
pub mod BatchDeleteScheduledTasks;
#[cfg(feature = "BatchDeleteScreenRecords")]
pub mod BatchDeleteScreenRecords;
#[cfg(feature = "BatchDeleteSubJobs")]
pub mod BatchDeleteSubJobs;
#[cfg(feature = "BatchDeleteUser")]
pub mod BatchDeleteUser;
#[cfg(feature = "BatchDeleteUserGroups")]
pub mod BatchDeleteUserGroups;
#[cfg(feature = "BatchDetachInstances")]
pub mod BatchDetachInstances;
#[cfg(feature = "BatchDisableApps")]
pub mod BatchDisableApps;
#[cfg(feature = "BatchDisassociateDesktopsEip")]
pub mod BatchDisassociateDesktopsEip;
#[cfg(feature = "BatchEnableApps")]
pub mod BatchEnableApps;
#[cfg(feature = "BatchInstallAgent")]
pub mod BatchInstallAgent;
#[cfg(feature = "BatchInstallApps")]
pub mod BatchInstallApps;
#[cfg(feature = "BatchLogoffDesktops")]
pub mod BatchLogoffDesktops;
#[cfg(feature = "BatchModifyQosVolumes")]
pub mod BatchModifyQosVolumes;
#[cfg(feature = "BatchRebuildDesktopsSystemDisk")]
pub mod BatchRebuildDesktopsSystemDisk;
#[cfg(feature = "BatchRestoreDesktopSnapshot")]
pub mod BatchRestoreDesktopSnapshot;
#[cfg(feature = "BatchRunDesktops")]
pub mod BatchRunDesktops;
#[cfg(feature = "BatchUpdateAppAuthorizations")]
pub mod BatchUpdateAppAuthorizations;
#[cfg(feature = "BatchUpdateDesktopDomain")]
pub mod BatchUpdateDesktopDomain;
#[cfg(feature = "BatchUpdateTargetOfPolicyGroup")]
pub mod BatchUpdateTargetOfPolicyGroup;
#[cfg(feature = "CancelRemoteAssistance")]
pub mod CancelRemoteAssistance;
#[cfg(feature = "CancelWorkspace")]
pub mod CancelWorkspace;
#[cfg(feature = "ChangeDesktopNetwork")]
pub mod ChangeDesktopNetwork;
#[cfg(feature = "ChangeDesktopToImage")]
pub mod ChangeDesktopToImage;
#[cfg(feature = "ChangeUserPrivilegeGroup")]
pub mod ChangeUserPrivilegeGroup;
#[cfg(feature = "ChangeUserStatus")]
pub mod ChangeUserStatus;
#[cfg(feature = "CheckCidr")]
pub mod CheckCidr;
#[cfg(feature = "CheckDesktopImages")]
pub mod CheckDesktopImages;
#[cfg(feature = "CheckEdgeSiteResources")]
pub mod CheckEdgeSiteResources;
#[cfg(feature = "CheckEnterpriseId")]
pub mod CheckEnterpriseId;
#[cfg(feature = "CheckSysprepInfo")]
pub mod CheckSysprepInfo;
#[cfg(feature = "CloseDomainNew")]
pub mod CloseDomainNew;
#[cfg(feature = "CreateAccessPolicy")]
pub mod CreateAccessPolicy;
#[cfg(feature = "CreateAgencies")]
pub mod CreateAgencies;
#[cfg(feature = "CreateAndAuthorizeBucket")]
pub mod CreateAndAuthorizeBucket;
#[cfg(feature = "CreateAppRule")]
pub mod CreateAppRule;
#[cfg(feature = "CreateBucketCredential")]
pub mod CreateBucketCredential;
#[cfg(feature = "CreateCert")]
pub mod CreateCert;
#[cfg(feature = "CreateChangeOrder")]
pub mod CreateChangeOrder;
#[cfg(feature = "CreateDesktop")]
pub mod CreateDesktop;
#[cfg(feature = "CreateDesktopBatchOrder")]
pub mod CreateDesktopBatchOrder;
#[cfg(feature = "CreateDesktopNamePolicy")]
pub mod CreateDesktopNamePolicy;
#[cfg(feature = "CreateDesktopOrder")]
pub mod CreateDesktopOrder;
#[cfg(feature = "CreateDesktopPool")]
pub mod CreateDesktopPool;
#[cfg(feature = "CreateDesktopPoolAuthorizedObjects")]
pub mod CreateDesktopPoolAuthorizedObjects;
#[cfg(feature = "CreateDesktopPoolChangeOrder")]
pub mod CreateDesktopPoolChangeOrder;
#[cfg(feature = "CreateDesktopUser")]
pub mod CreateDesktopUser;
#[cfg(feature = "CreateDomainNew")]
pub mod CreateDomainNew;
#[cfg(feature = "CreateModelGroup")]
pub mod CreateModelGroup;
#[cfg(feature = "CreateOrder")]
pub mod CreateOrder;
#[cfg(feature = "CreatePolicyGroup")]
pub mod CreatePolicyGroup;
#[cfg(feature = "CreatePolicyTemplate")]
pub mod CreatePolicyTemplate;
#[cfg(feature = "CreateProvider")]
pub mod CreateProvider;
#[cfg(feature = "CreateRemoteAssistance")]
pub mod CreateRemoteAssistance;
#[cfg(feature = "CreateResourcePackagesOrder")]
pub mod CreateResourcePackagesOrder;
#[cfg(feature = "CreateScheduledTasks")]
pub mod CreateScheduledTasks;
#[cfg(feature = "CreateScript")]
pub mod CreateScript;
#[cfg(feature = "CreateSubnetBandwidthChangeOrder")]
pub mod CreateSubnetBandwidthChangeOrder;
#[cfg(feature = "CreateTag")]
pub mod CreateTag;
#[cfg(feature = "CreateTenantUpgradeStrategy")]
pub mod CreateTenantUpgradeStrategy;
#[cfg(feature = "CreateTerminalsBindingDesktops")]
pub mod CreateTerminalsBindingDesktops;
#[cfg(feature = "CreateUpgradeScheduleTask")]
pub mod CreateUpgradeScheduleTask;
#[cfg(feature = "CreateUserGroup")]
pub mod CreateUserGroup;
#[cfg(feature = "DeleteApp")]
pub mod DeleteApp;
#[cfg(feature = "DeleteAppRule")]
pub mod DeleteAppRule;
