#[cfg(feature = "AddAlarmRuleResources")]
pub mod AddAlarmRuleResources;
#[cfg(feature = "BatchCreateAgentInvocations")]
pub mod BatchCreateAgentInvocations;
#[cfg(feature = "BatchCreateResources")]
pub mod BatchCreateResources;
#[cfg(feature = "BatchDeleteAlarmRules")]
pub mod BatchDeleteAlarmRules;
#[cfg(feature = "BatchDeleteAlarmTemplates")]
pub mod BatchDeleteAlarmTemplates;
#[cfg(feature = "BatchDeleteNotificationMasks")]
pub mod BatchDeleteNotificationMasks;
#[cfg(feature = "BatchDeleteOneClickAlarms")]
pub mod BatchDeleteOneClickAlarms;
#[cfg(feature = "BatchDeleteResourceGroups")]
pub mod BatchDeleteResourceGroups;
#[cfg(feature = "BatchDeleteResources")]
pub mod BatchDeleteResources;
#[cfg(feature = "BatchEnableAlarmRules")]
pub mod BatchEnableAlarmRules;
#[cfg(feature = "BatchListMetricData")]
pub mod BatchListMetricData;
#[cfg(feature = "BatchUpdateNotificationMasks")]
pub mod BatchUpdateNotificationMasks;
#[cfg(feature = "BatchUpdateNotificationMaskTime")]
pub mod BatchUpdateNotificationMaskTime;
#[cfg(feature = "BatchUpdateOneClickAlarmPoliciesEnabledState")]
pub mod BatchUpdateOneClickAlarmPoliciesEnabledState;
#[cfg(feature = "BatchUpdateOneClickAlarmsEnabledState")]
pub mod BatchUpdateOneClickAlarmsEnabledState;
#[cfg(feature = "BatchUpdateWidgets")]
pub mod BatchUpdateWidgets;
#[cfg(feature = "CreateAlarm")]
pub mod CreateAlarm;
#[cfg(feature = "CreateAlarmRules")]
pub mod CreateAlarmRules;
#[cfg(feature = "CreateAlarmTemplate")]
pub mod CreateAlarmTemplate;
#[cfg(feature = "CreateDashboardWidgets")]
pub mod CreateDashboardWidgets;
#[cfg(feature = "CreateEvents")]
pub mod CreateEvents;
#[cfg(feature = "CreateMetricData")]
pub mod CreateMetricData;
#[cfg(feature = "CreateOneClickAlarm")]
pub mod CreateOneClickAlarm;
#[cfg(feature = "CreateOneDashboard")]
pub mod CreateOneDashboard;
#[cfg(feature = "CreateResourceGroup")]
pub mod CreateResourceGroup;
#[cfg(feature = "DeleteAlarm")]
pub mod DeleteAlarm;
#[cfg(feature = "DeleteAlarmRuleResources")]
pub mod DeleteAlarmRuleResources;
#[cfg(feature = "DeleteAlarmTemplate")]
pub mod DeleteAlarmTemplate;
#[cfg(feature = "DeleteDashboards")]
pub mod DeleteDashboards;
#[cfg(feature = "DeleteOneWidget")]
pub mod DeleteOneWidget;
#[cfg(feature = "DeleteResourceGroup")]
pub mod DeleteResourceGroup;
#[cfg(feature = "ListAgentDimensionInfo")]
pub mod ListAgentDimensionInfo;
#[cfg(feature = "ListAgentInvocations")]
pub mod ListAgentInvocations;
#[cfg(feature = "ListAgentStatus")]
pub mod ListAgentStatus;
#[cfg(feature = "ListAlarmHistories")]
pub mod ListAlarmHistories;
#[cfg(feature = "ListAlarmRulePolicies")]
pub mod ListAlarmRulePolicies;
#[cfg(feature = "ListAlarmRuleResources")]
pub mod ListAlarmRuleResources;
#[cfg(feature = "ListAlarmRules")]
pub mod ListAlarmRules;
#[cfg(feature = "ListAlarms")]
pub mod ListAlarms;
#[cfg(feature = "ListAlarmTemplateAssociationAlarms")]
pub mod ListAlarmTemplateAssociationAlarms;
#[cfg(feature = "ListAlarmTemplates")]
pub mod ListAlarmTemplates;
#[cfg(feature = "ListCesTargetProjectTags")]
pub mod ListCesTargetProjectTags;
#[cfg(feature = "ListDashboardInfos")]
pub mod ListDashboardInfos;
#[cfg(feature = "ListDashboardWidgets")]
pub mod ListDashboardWidgets;
#[cfg(feature = "ListEventDetail")]
pub mod ListEventDetail;
#[cfg(feature = "ListEvents")]
pub mod ListEvents;
#[cfg(feature = "ListMetrics")]
pub mod ListMetrics;
#[cfg(feature = "ListNotificationMaskResources")]
pub mod ListNotificationMaskResources;
#[cfg(feature = "ListNotificationMasks")]
pub mod ListNotificationMasks;
#[cfg(feature = "ListOneClickAlarmRules")]
pub mod ListOneClickAlarmRules;
#[cfg(feature = "ListOneClickAlarms")]
pub mod ListOneClickAlarms;
#[cfg(feature = "ListResourceGroup")]
pub mod ListResourceGroup;
#[cfg(feature = "ListResourceGroups")]
pub mod ListResourceGroups;
#[cfg(feature = "ListResourceGroupsServicesResources")]
pub mod ListResourceGroupsServicesResources;
#[cfg(feature = "ShowAlarm")]
pub mod ShowAlarm;
#[cfg(feature = "ShowAlarmTemplate")]
pub mod ShowAlarmTemplate;
#[cfg(feature = "ShowEventData")]
pub mod ShowEventData;
#[cfg(feature = "ShowMetricData")]
pub mod ShowMetricData;
#[cfg(feature = "ShowQuotas")]
pub mod ShowQuotas;
#[cfg(feature = "ShowResourceGroup")]
pub mod ShowResourceGroup;
#[cfg(feature = "ShowWidget")]
pub mod ShowWidget;
#[cfg(feature = "UpdateAlarm")]
pub mod UpdateAlarm;
#[cfg(feature = "UpdateAlarmAction")]
pub mod UpdateAlarmAction;
#[cfg(feature = "UpdateAlarmNotifications")]
pub mod UpdateAlarmNotifications;
#[cfg(feature = "UpdateAlarmRulePolicies")]
pub mod UpdateAlarmRulePolicies;
#[cfg(feature = "UpdateAlarmTemplate")]
pub mod UpdateAlarmTemplate;
#[cfg(feature = "UpdateDashboard")]
pub mod UpdateDashboard;
#[cfg(feature = "UpdateNotificationMask")]
pub mod UpdateNotificationMask;
#[cfg(feature = "UpdateOneClickAlarmNotifications")]
pub mod UpdateOneClickAlarmNotifications;
#[cfg(feature = "UpdateResourceGroup")]
pub mod UpdateResourceGroup;
