#[cfg(feature = "BatchDeleteTrashes")]
pub mod BatchDeleteTrashes;
#[cfg(feature = "BatchRestoreRepo")]
pub mod BatchRestoreRepo;
#[cfg(feature = "CreateArtifactory")]
pub mod CreateArtifactory;
#[cfg(feature = "CreateAttention")]
pub mod CreateAttention;
#[cfg(feature = "CreateDockerRepositories")]
pub mod CreateDockerRepositories;
#[cfg(feature = "CreateMavenRepo")]
pub mod CreateMavenRepo;
#[cfg(feature = "CreateProjectRelatedRepository")]
pub mod CreateProjectRelatedRepository;
#[cfg(feature = "DeleteArtifactFile")]
pub mod DeleteArtifactFile;
#[cfg(feature = "DeleteRepository")]
pub mod DeleteRepository;
#[cfg(feature = "ListAllRepositories")]
pub mod ListAllRepositories;
#[cfg(feature = "ListArtifactoryComponent")]
pub mod ListArtifactoryComponent;
#[cfg(feature = "ListArtifactoryStorageStatistic")]
pub mod ListArtifactoryStorageStatistic;
#[cfg(feature = "ListAttentions")]
pub mod ListAttentions;
#[cfg(feature = "ModifyRepository")]
pub mod ModifyRepository;
#[cfg(feature = "ResetUserPassword")]
pub mod ResetUserPassword;
#[cfg(feature = "SearchArtifacts")]
pub mod SearchArtifacts;
#[cfg(feature = "SearchByChecksum")]
pub mod SearchByChecksum;
#[cfg(feature = "ShowAudit")]
pub mod ShowAudit;
#[cfg(feature = "ShowFileTree")]
pub mod ShowFileTree;
#[cfg(feature = "ShowMavenInfo")]
pub mod ShowMavenInfo;
#[cfg(feature = "ShowProjectList")]
pub mod ShowProjectList;
#[cfg(feature = "ShowProjectReleaseFiles")]
pub mod ShowProjectReleaseFiles;
#[cfg(feature = "ShowReleaseProjectFiles")]
pub mod ShowReleaseProjectFiles;
#[cfg(feature = "ShowRepository")]
pub mod ShowRepository;
#[cfg(feature = "ShowRepositoryInfo")]
pub mod ShowRepositoryInfo;
#[cfg(feature = "ShowStorage")]
pub mod ShowStorage;
#[cfg(feature = "ShowUserPrivileges")]
pub mod ShowUserPrivileges;
#[cfg(feature = "UpdateArtifactory")]
pub mod UpdateArtifactory;
