#[cfg(feature = "BatchDeleteTrashes")]
pub mod BatchDeleteTrashes;
#[cfg(feature = "BatchRestoreRepo")]
pub mod BatchRestoreRepo;
#[cfg(feature = "CreateArtifactory")]
pub mod CreateArtifactory;
#[cfg(feature = "CreateAttention")]
pub mod CreateAttention;
#[cfg(feature = "CreateDockerRepositories")]
pub mod CreateDockerRepositories;
#[cfg(feature = "CreateMavenRepo")]
pub mod CreateMavenRepo;
#[cfg(feature = "CreateProjectRelatedRepository")]
pub mod CreateProjectRelatedRepository;
#[cfg(feature = "DeleteArtifactFile")]
pub mod DeleteArtifactFile;
#[cfg(feature = "DeleteCompletelyUpdateFileState")]
pub mod DeleteCompletelyUpdateFileState;
#[cfg(feature = "DeleteRepository")]
pub mod DeleteRepository;
#[cfg(feature = "ListAllRepositories")]
pub mod ListAllRepositories;
#[cfg(feature = "ListArtifactoryComponent")]
pub mod ListArtifactoryComponent;
#[cfg(feature = "ListArtifactoryStorageStatistic")]
pub mod ListArtifactoryStorageStatistic;
#[cfg(feature = "ListAttentions")]
pub mod ListAttentions;
#[cfg(feature = "ListCapacityMessageSetting")]
pub mod ListCapacityMessageSetting;
#[cfg(feature = "ListChildProxyRepositoriesList")]
pub mod ListChildProxyRepositoriesList;
#[cfg(feature = "ListDomainIpConfig")]
pub mod ListDomainIpConfig;
#[cfg(feature = "ListFileBuildArchives")]
pub mod ListFileBuildArchives;
#[cfg(feature = "ListFiles")]
pub mod ListFiles;
#[cfg(feature = "ListLatestVersionFiles")]
pub mod ListLatestVersionFiles;
#[cfg(feature = "ListMavenList")]
pub mod ListMavenList;
#[cfg(feature = "ListMavenUser")]
pub mod ListMavenUser;
#[cfg(feature = "ListNetProxy")]
pub mod ListNetProxy;
#[cfg(feature = "ListProjectRolePermissions")]
pub mod ListProjectRolePermissions;
#[cfg(feature = "ListProjectUsers")]
pub mod ListProjectUsers;
#[cfg(feature = "ListSecGuardList")]
pub mod ListSecGuardList;
#[cfg(feature = "ListUserPrivileges")]
pub mod ListUserPrivileges;
#[cfg(feature = "ModifyRepository")]
pub mod ModifyRepository;
#[cfg(feature = "ResetUserPassword")]
pub mod ResetUserPassword;
#[cfg(feature = "SearchArtifacts")]
pub mod SearchArtifacts;
#[cfg(feature = "SearchByChecksum")]
pub mod SearchByChecksum;
#[cfg(feature = "ShowAudit")]
pub mod ShowAudit;
#[cfg(feature = "ShowAutoDeleteJobSettings")]
pub mod ShowAutoDeleteJobSettings;
#[cfg(feature = "ShowDomainReleaseRepoStorage")]
pub mod ShowDomainReleaseRepoStorage;
#[cfg(feature = "ShowFileDetail")]
pub mod ShowFileDetail;
#[cfg(feature = "ShowFileDetailByFullName")]
pub mod ShowFileDetailByFullName;
#[cfg(feature = "ShowFileTree")]
pub mod ShowFileTree;
#[cfg(feature = "ShowLatestVersionFilesCount")]
pub mod ShowLatestVersionFilesCount;
#[cfg(feature = "ShowMavenInfo")]
pub mod ShowMavenInfo;
#[cfg(feature = "ShowMultiRolesUserPermissions")]
pub mod ShowMultiRolesUserPermissions;
#[cfg(feature = "ShowOpenSourceEnabled")]
pub mod ShowOpenSourceEnabled;
#[cfg(feature = "ShowPackageDataDetail")]
pub mod ShowPackageDataDetail;
#[cfg(feature = "ShowPackageInfo")]
pub mod ShowPackageInfo;
#[cfg(feature = "ShowProjectList")]
pub mod ShowProjectList;
#[cfg(feature = "ShowProjectRelatedRepository")]
pub mod ShowProjectRelatedRepository;
#[cfg(feature = "ShowProjectReleaseFiles")]
pub mod ShowProjectReleaseFiles;
#[cfg(feature = "ShowProjectStorageInfo")]
pub mod ShowProjectStorageInfo;
#[cfg(feature = "ShowProjectVersionsCount")]
pub mod ShowProjectVersionsCount;
#[cfg(feature = "ShowReleaseProjectFiles")]
pub mod ShowReleaseProjectFiles;
#[cfg(feature = "ShowRepository")]
pub mod ShowRepository;
#[cfg(feature = "ShowRepositoryInfo")]
pub mod ShowRepositoryInfo;
#[cfg(feature = "ShowRepositoryRolesPrivilege")]
pub mod ShowRepositoryRolesPrivilege;
#[cfg(feature = "ShowRepoUserInfo")]
pub mod ShowRepoUserInfo;
#[cfg(feature = "ShowStorage")]
pub mod ShowStorage;
#[cfg(feature = "ShowUserPrivileges")]
pub mod ShowUserPrivileges;
#[cfg(feature = "ShowUserTicket")]
pub mod ShowUserTicket;
#[cfg(feature = "ShowVersionList")]
pub mod ShowVersionList;
#[cfg(feature = "UpdateArtifactory")]
pub mod UpdateArtifactory;
#[cfg(feature = "UpdateRepoRolesPrivilege")]
pub mod UpdateRepoRolesPrivilege;
