[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
CreateReportExcel = []
CreateReportPdf = []
CreateTask = []
CreateTaskMultipartFile = []
DeleteTask = []
DownloadReportExcel = []
DownloadReportPdf = []
NotifyTaskMultipartFile = []
ShowInfoLeakSummary = []
ShowOpenSourceReport = []
ShowOpenSourceSummary = []
ShowReportExcelStatus = []
ShowReportPdfStatus = []
ShowSecCompileSummary = []
ShowSecConfigSummary = []
ShowTaskStatus = []
StopTask = []
UploadTaskMultipartFile = []
full = ["CreateReportExcel", "CreateReportPdf", "CreateTask", "CreateTaskMultipartFile", "DeleteTask", "DownloadReportExcel", "DownloadReportPdf", "NotifyTaskMultipartFile", "ShowInfoLeakSummary", "ShowOpenSourceReport", "ShowOpenSourceSummary", "ShowReportExcelStatus", "ShowReportPdfStatus", "ShowSecCompileSummary", "ShowSecConfigSummary", "ShowTaskStatus", "StopTask", "UploadTaskMultipartFile"]

[lib]
name = "huawei_cloud_api_definitions_DevSecurity"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-DevSecurity"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
