[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddAimMsgSignature = []
AddCallBack = []
AddVmsCallBack = []
CheckMobileCapability = []
CreateAimMsgTemplate = []
CreateAimPersonalTemplate = []
CreateAimSendTask = []
CreatePubInfo = []
CreateResolveTask = []
CreateSmsApp = []
CreateVmsSendTask = []
CreateVmsTemplate = []
DeleteAimMsgSignature = []
DeleteAimMsgTemplate = []
DeleteAimPersonalTemplate = []
DeletePortInfo = []
DeleteTemplateMaterial = []
FreezePub = []
ListAimCallbacks = []
ListAimMsgApp = []
ListAimMsgAppDetail = []
ListAimMsgSignature = []
ListAimMsgSignatureDetail = []
ListAimMsgTemplate = []
ListAimResolveDetails = []
ListAimSendDetails = []
ListAimSendReports = []
ListAimSendTasks = []
ListAimTemplateMaterials = []
ListAimTemplateReports = []
ListAimTemplates = []
ListMenus = []
ListPortInfos = []
ListPortalInfos = []
ListPubInfos = []
ListResolveTasks = []
ListVmsCallbacks = []
ListVmsSendTasks = []
ListVmsTemplateStatus = []
LockPort = []
PushMenuInfo = []
PushPortalInfo = []
RegisterPort = []
SendAimBatchDifferentMessages = []
SendAimBatchMessages = []
SetPrimaryVideoThumbnail = []
ShowAimMsgSignatureFileInfo = []
ShowAimMsgTemplateDetail = []
ShowAimMsgTemplateVariable = []
ShowTemplateVideoThumbnail = []
UnfreezePub = []
UnlockPort = []
UpdateAimMsgApp = []
UpdateAimMsgSignature = []
UpdateAimMsgTemplate = []
UpdateMenu = []
UpdatePersonalTemplateState = []
UpdatePortalInfo = []
UpdatePubInfo = []
UploadAimMsgSignatureFile = []
UploadAimTemplateMaterial = []
UploadMedia = []
full = ["AddAimMsgSignature", "AddCallBack", "AddVmsCallBack", "CheckMobileCapability", "CreateAimMsgTemplate", "CreateAimPersonalTemplate", "CreateAimSendTask", "CreatePubInfo", "CreateResolveTask", "CreateSmsApp", "CreateVmsSendTask", "CreateVmsTemplate", "DeleteAimMsgSignature", "DeleteAimMsgTemplate", "DeleteAimPersonalTemplate", "DeletePortInfo", "DeleteTemplateMaterial", "FreezePub", "ListAimCallbacks", "ListAimMsgApp", "ListAimMsgAppDetail", "ListAimMsgSignature", "ListAimMsgSignatureDetail", "ListAimMsgTemplate", "ListAimResolveDetails", "ListAimSendDetails", "ListAimSendReports", "ListAimSendTasks", "ListAimTemplateMaterials", "ListAimTemplateReports", "ListAimTemplates", "ListMenus", "ListPortalInfos", "ListPortInfos", "ListPubInfos", "ListResolveTasks", "ListVmsCallbacks", "ListVmsSendTasks", "ListVmsTemplateStatus", "LockPort", "PushMenuInfo", "PushPortalInfo", "RegisterPort", "SendAimBatchDifferentMessages", "SendAimBatchMessages", "SetPrimaryVideoThumbnail", "ShowAimMsgSignatureFileInfo", "ShowAimMsgTemplateDetail", "ShowAimMsgTemplateVariable", "ShowTemplateVideoThumbnail", "UnfreezePub", "UnlockPort", "UpdateAimMsgApp", "UpdateAimMsgSignature", "UpdateAimMsgTemplate", "UpdateMenu", "UpdatePersonalTemplateState", "UpdatePortalInfo", "UpdatePubInfo", "UploadAimMsgSignatureFile", "UploadAimTemplateMaterial", "UploadMedia"]

[lib]
name = "huawei_cloud_api_definitions_KooMessage"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-KooMessage"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
