#[cfg(feature = "AcceptHandshake")]
pub mod AcceptHandshake;
#[cfg(feature = "AttachDryRunPolicy")]
pub mod AttachDryRunPolicy;
#[cfg(feature = "AttachPolicy")]
pub mod AttachPolicy;
#[cfg(feature = "CancelHandshake")]
pub mod CancelHandshake;
#[cfg(feature = "CloseAccount")]
pub mod CloseAccount;
#[cfg(feature = "CreateAccount")]
pub mod CreateAccount;
#[cfg(feature = "CreateDryRunPolicy")]
pub mod CreateDryRunPolicy;
#[cfg(feature = "CreateOrganization")]
pub mod CreateOrganization;
#[cfg(feature = "CreateOrganizationalUnit")]
pub mod CreateOrganizationalUnit;
#[cfg(feature = "CreatePolicy")]
pub mod CreatePolicy;
#[cfg(feature = "CreateResourceAccount")]
pub mod CreateResourceAccount;
#[cfg(feature = "CreateTagResource")]
pub mod CreateTagResource;
#[cfg(feature = "DeclineHandshake")]
pub mod DeclineHandshake;
#[cfg(feature = "DeleteDryRunPolicy")]
pub mod DeleteDryRunPolicy;
#[cfg(feature = "DeleteOrganization")]
pub mod DeleteOrganization;
#[cfg(feature = "DeleteOrganizationalUnit")]
pub mod DeleteOrganizationalUnit;
#[cfg(feature = "DeletePolicy")]
pub mod DeletePolicy;
#[cfg(feature = "DeleteTagResource")]
pub mod DeleteTagResource;
#[cfg(feature = "DeregisterDelegatedAdministrator")]
pub mod DeregisterDelegatedAdministrator;
#[cfg(feature = "DetachDryRunPolicy")]
pub mod DetachDryRunPolicy;
#[cfg(feature = "DetachPolicy")]
pub mod DetachPolicy;
#[cfg(feature = "DisablePolicyType")]
pub mod DisablePolicyType;
#[cfg(feature = "DisableTrustedService")]
pub mod DisableTrustedService;
#[cfg(feature = "EnablePolicyType")]
pub mod EnablePolicyType;
#[cfg(feature = "EnableTrustedService")]
pub mod EnableTrustedService;
#[cfg(feature = "InviteAccount")]
pub mod InviteAccount;
#[cfg(feature = "LeaveOrganization")]
pub mod LeaveOrganization;
#[cfg(feature = "ListAccounts")]
pub mod ListAccounts;
#[cfg(feature = "ListCloseAccountStatuses")]
pub mod ListCloseAccountStatuses;
#[cfg(feature = "ListCreateAccountStatuses")]
pub mod ListCreateAccountStatuses;
#[cfg(feature = "ListDelegatedAdministrators")]
pub mod ListDelegatedAdministrators;
#[cfg(feature = "ListDelegatedServices")]
pub mod ListDelegatedServices;
#[cfg(feature = "ListDryRunPolicies")]
pub mod ListDryRunPolicies;
#[cfg(feature = "ListEntities")]
pub mod ListEntities;
#[cfg(feature = "ListEntitiesForDryRunPolicy")]
pub mod ListEntitiesForDryRunPolicy;
#[cfg(feature = "ListEntitiesForPolicy")]
pub mod ListEntitiesForPolicy;
#[cfg(feature = "ListHandshakes")]
pub mod ListHandshakes;
#[cfg(feature = "ListOrganizationalUnits")]
pub mod ListOrganizationalUnits;
#[cfg(feature = "ListPolicies")]
pub mod ListPolicies;
#[cfg(feature = "ListQuotas")]
pub mod ListQuotas;
#[cfg(feature = "ListReceivedHandshakes")]
pub mod ListReceivedHandshakes;
#[cfg(feature = "ListResourceInstances")]
pub mod ListResourceInstances;
#[cfg(feature = "ListResourceTags")]
pub mod ListResourceTags;
#[cfg(feature = "ListRoots")]
pub mod ListRoots;
#[cfg(feature = "ListServices")]
pub mod ListServices;
#[cfg(feature = "ListTagPolicyServices")]
pub mod ListTagPolicyServices;
#[cfg(feature = "ListTagResources")]
pub mod ListTagResources;
#[cfg(feature = "ListTagsForResource")]
pub mod ListTagsForResource;
#[cfg(feature = "ListTrustedServices")]
pub mod ListTrustedServices;
#[cfg(feature = "MoveAccount")]
pub mod MoveAccount;
#[cfg(feature = "RegisterDelegatedAdministrator")]
pub mod RegisterDelegatedAdministrator;
#[cfg(feature = "RemoveAccount")]
pub mod RemoveAccount;
#[cfg(feature = "ShowAccount")]
pub mod ShowAccount;
#[cfg(feature = "ShowCreateAccountStatus")]
pub mod ShowCreateAccountStatus;
#[cfg(feature = "ShowDryRunConfig")]
pub mod ShowDryRunConfig;
#[cfg(feature = "ShowDryRunPolicy")]
pub mod ShowDryRunPolicy;
#[cfg(feature = "ShowEffectivePolicies")]
pub mod ShowEffectivePolicies;
#[cfg(feature = "ShowHandshake")]
pub mod ShowHandshake;
#[cfg(feature = "ShowOrganization")]
pub mod ShowOrganization;
#[cfg(feature = "ShowOrganizationalUnit")]
pub mod ShowOrganizationalUnit;
#[cfg(feature = "ShowPolicy")]
pub mod ShowPolicy;
#[cfg(feature = "ShowResourceInstancesCount")]
pub mod ShowResourceInstancesCount;
#[cfg(feature = "TagResource")]
pub mod TagResource;
#[cfg(feature = "UntagResource")]
pub mod UntagResource;
#[cfg(feature = "UpdateAccount")]
pub mod UpdateAccount;
#[cfg(feature = "UpdateDryRunConfig")]
pub mod UpdateDryRunConfig;
#[cfg(feature = "UpdateDryRunPolicy")]
pub mod UpdateDryRunPolicy;
#[cfg(feature = "UpdateOrganizationalUnit")]
pub mod UpdateOrganizationalUnit;
#[cfg(feature = "UpdatePolicy")]
pub mod UpdatePolicy;
