#[cfg(feature = "AddBmsTag")]
pub mod AddBmsTag;
#[cfg(feature = "AddBmsTags")]
pub mod AddBmsTags;
#[cfg(feature = "AttachNicToBms")]
pub mod AttachNicToBms;
#[cfg(feature = "AttachVolumeToBms")]
pub mod AttachVolumeToBms;
#[cfg(feature = "BatchAttachSharedVolumeToBms")]
pub mod BatchAttachSharedVolumeToBms;
#[cfg(feature = "CreateBmsInstance")]
pub mod CreateBmsInstance;
#[cfg(feature = "CreateHighSpeedNetwork")]
pub mod CreateHighSpeedNetwork;
#[cfg(feature = "CreateIpv6Subnet")]
pub mod CreateIpv6Subnet;
#[cfg(feature = "DeleteBmsInstance")]
pub mod DeleteBmsInstance;
#[cfg(feature = "DeleteBmsTag")]
pub mod DeleteBmsTag;
#[cfg(feature = "DeleteBmsTags")]
pub mod DeleteBmsTags;
#[cfg(feature = "DeleteHighSpeedNetwork")]
pub mod DeleteHighSpeedNetwork;
#[cfg(feature = "DeleteIpv6Subnet")]
pub mod DeleteIpv6Subnet;
#[cfg(feature = "DeleteSshKey")]
pub mod DeleteSshKey;
#[cfg(feature = "DetachNicFromBms")]
pub mod DetachNicFromBms;
#[cfg(feature = "DetachVolumeFromBms")]
pub mod DetachVolumeFromBms;
#[cfg(feature = "ImportSshKey")]
pub mod ImportSshKey;
#[cfg(feature = "ListBmsInstance")]
pub mod ListBmsInstance;
#[cfg(feature = "ListBmsInterfaces")]
pub mod ListBmsInterfaces;
#[cfg(feature = "ListBmsVolume")]
pub mod ListBmsVolume;
#[cfg(feature = "ListFlavorsDetails")]
pub mod ListFlavorsDetails;
#[cfg(feature = "ListHighSpeedNetworks")]
pub mod ListHighSpeedNetworks;
#[cfg(feature = "ListInterfaces")]
pub mod ListInterfaces;
#[cfg(feature = "ListServersByBmsTags")]
pub mod ListServersByBmsTags;
#[cfg(feature = "ListSshKey")]
pub mod ListSshKey;
#[cfg(feature = "ModifyHighSpeedNetwork")]
pub mod ModifyHighSpeedNetwork;
#[cfg(feature = "ModifyHighSpeedNetworkEii")]
pub mod ModifyHighSpeedNetworkEii;
#[cfg(feature = "OperateBms")]
pub mod OperateBms;
#[cfg(feature = "ShowApicomJob")]
pub mod ShowApicomJob;
#[cfg(feature = "ShowBmsInstanceDetail")]
pub mod ShowBmsInstanceDetail;
#[cfg(feature = "ShowBmsInterface")]
pub mod ShowBmsInterface;
#[cfg(feature = "ShowBmsServerDetail")]
pub mod ShowBmsServerDetail;
#[cfg(feature = "ShowBmsTag")]
pub mod ShowBmsTag;
#[cfg(feature = "ShowSshKeyDetail")]
pub mod ShowSshKeyDetail;
#[cfg(feature = "ShowVolumeOfServer")]
pub mod ShowVolumeOfServer;
#[cfg(feature = "UpdateBmsMetadata")]
pub mod UpdateBmsMetadata;
