#[cfg(feature = "AddDeployKey")]
pub mod AddDeployKey;
#[cfg(feature = "AddDeployKeyV2")]
pub mod AddDeployKeyV2;
#[cfg(feature = "AddHooks")]
pub mod AddHooks;
#[cfg(feature = "AddProtectBranchV2")]
pub mod AddProtectBranchV2;
#[cfg(feature = "AddRepoMembers")]
pub mod AddRepoMembers;
#[cfg(feature = "AddSshKey")]
pub mod AddSshKey;
#[cfg(feature = "AddTagV2")]
pub mod AddTagV2;
#[cfg(feature = "AddTenantTrustedIpAddress")]
pub mod AddTenantTrustedIpAddress;
#[cfg(feature = "AddTrustedIpAddress")]
pub mod AddTrustedIpAddress;
#[cfg(feature = "AssociateGroupUserGroup")]
pub mod AssociateGroupUserGroup;
#[cfg(feature = "AssociateIssues")]
pub mod AssociateIssues;
#[cfg(feature = "AssociateRepositoryUserGroup")]
pub mod AssociateRepositoryUserGroup;
#[cfg(feature = "CreateCommit")]
pub mod CreateCommit;
#[cfg(feature = "CreateGroup")]
pub mod CreateGroup;
#[cfg(feature = "CreateMergeRequestDiscussion")]
pub mod CreateMergeRequestDiscussion;
#[cfg(feature = "CreateMergeRequestDiscussionNote")]
pub mod CreateMergeRequestDiscussionNote;
#[cfg(feature = "CreateNewBranch")]
pub mod CreateNewBranch;
#[cfg(feature = "CreateProjectAndforkRepositories")]
pub mod CreateProjectAndforkRepositories;
#[cfg(feature = "CreateProjectAndRepositories")]
pub mod CreateProjectAndRepositories;
#[cfg(feature = "CreateRepository")]
pub mod CreateRepository;
#[cfg(feature = "DeleteDeployKey")]
pub mod DeleteDeployKey;
#[cfg(feature = "DeleteDeployKeyV2")]
pub mod DeleteDeployKeyV2;
#[cfg(feature = "DeleteGroup")]
pub mod DeleteGroup;
#[cfg(feature = "DeleteHooks")]
pub mod DeleteHooks;
#[cfg(feature = "DeleteRepoMember")]
pub mod DeleteRepoMember;
#[cfg(feature = "DeleteRepository")]
pub mod DeleteRepository;
#[cfg(feature = "DeleteSShkey")]
pub mod DeleteSShkey;
#[cfg(feature = "DeleteTenantTrustedIpAddress")]
pub mod DeleteTenantTrustedIpAddress;
#[cfg(feature = "DeleteTrustedIpAddress")]
pub mod DeleteTrustedIpAddress;
#[cfg(feature = "GetAllRepositoryByProjectId")]
pub mod GetAllRepositoryByProjectId;
#[cfg(feature = "GetProductTemplates")]
pub mod GetProductTemplates;
#[cfg(feature = "GetRepositoryByProjectId")]
pub mod GetRepositoryByProjectId;
#[cfg(feature = "GetTemplates")]
pub mod GetTemplates;
#[cfg(feature = "ListBranchesByRepositoryId")]
pub mod ListBranchesByRepositoryId;
#[cfg(feature = "ListCommits")]
pub mod ListCommits;
#[cfg(feature = "ListCommitStatistics")]
pub mod ListCommitStatistics;
#[cfg(feature = "ListFiles")]
pub mod ListFiles;
#[cfg(feature = "ListFilesByQuery")]
pub mod ListFilesByQuery;
#[cfg(feature = "ListHooks")]
pub mod ListHooks;
#[cfg(feature = "ListManageableGroups")]
pub mod ListManageableGroups;
#[cfg(feature = "ListMergeChanges")]
pub mod ListMergeChanges;
#[cfg(feature = "ListMergeChangesTrees")]
pub mod ListMergeChangesTrees;
#[cfg(feature = "ListMergeRequest")]
pub mod ListMergeRequest;
#[cfg(feature = "ListMergeRequestReviewers")]
pub mod ListMergeRequestReviewers;
#[cfg(feature = "ListProductTwoTemplates")]
pub mod ListProductTwoTemplates;
#[cfg(feature = "ListRelatedCommits")]
pub mod ListRelatedCommits;
#[cfg(feature = "ListRepoMembers")]
pub mod ListRepoMembers;
#[cfg(feature = "ListRepositoryStatus")]
pub mod ListRepositoryStatus;
#[cfg(feature = "ListSshKeys")]
pub mod ListSshKeys;
#[cfg(feature = "ListSubfiles")]
pub mod ListSubfiles;
#[cfg(feature = "ListTemplatesTwo")]
pub mod ListTemplatesTwo;
#[cfg(feature = "ListTenantTrustedIpAddresses")]
pub mod ListTenantTrustedIpAddresses;
#[cfg(feature = "ListTrustedIpAddresses")]
pub mod ListTrustedIpAddresses;
#[cfg(feature = "ListTwoTemplates")]
pub mod ListTwoTemplates;
#[cfg(feature = "ListUserAllRepositories")]
pub mod ListUserAllRepositories;
#[cfg(feature = "LockRepository")]
pub mod LockRepository;
#[cfg(feature = "SetRepoRole")]
pub mod SetRepoRole;
#[cfg(feature = "ShareTemplates")]
pub mod ShareTemplates;
#[cfg(feature = "ShowAllRepositoryByTwoProjectId")]
pub mod ShowAllRepositoryByTwoProjectId;
#[cfg(feature = "ShowBranchesByRepositoryId")]
pub mod ShowBranchesByRepositoryId;
#[cfg(feature = "ShowBranchesByTwoRepositoryId")]
pub mod ShowBranchesByTwoRepositoryId;
#[cfg(feature = "ShowCommitsByBranch")]
pub mod ShowCommitsByBranch;
#[cfg(feature = "ShowCommitsByRepoId")]
pub mod ShowCommitsByRepoId;
#[cfg(feature = "ShowDiffCommit")]
pub mod ShowDiffCommit;
#[cfg(feature = "ShowFile")]
pub mod ShowFile;
#[cfg(feature = "ShowGroup")]
pub mod ShowGroup;
#[cfg(feature = "ShowHasPipeline")]
pub mod ShowHasPipeline;
#[cfg(feature = "ShowImageBlob")]
pub mod ShowImageBlob;
#[cfg(feature = "ShowMaster")]
pub mod ShowMaster;
#[cfg(feature = "ShowMergeRequest")]
pub mod ShowMergeRequest;
#[cfg(feature = "ShowPrivateKeyVerify")]
pub mod ShowPrivateKeyVerify;
#[cfg(feature = "ShowRepoId")]
pub mod ShowRepoId;
#[cfg(feature = "ShowRepositoryArchive")]
pub mod ShowRepositoryArchive;
#[cfg(feature = "ShowRepositoryByUuid")]
pub mod ShowRepositoryByUuid;
#[cfg(feature = "ShowRepositoryNameExist")]
pub mod ShowRepositoryNameExist;
#[cfg(feature = "ShowRepositoryStatistics")]
pub mod ShowRepositoryStatistics;
#[cfg(feature = "ShowReviewSetting")]
pub mod ShowReviewSetting;
#[cfg(feature = "ShowSingleCommit")]
pub mod ShowSingleCommit;
#[cfg(feature = "ShowStatisticalData")]
pub mod ShowStatisticalData;
#[cfg(feature = "ShowStatisticCommit")]
pub mod ShowStatisticCommit;
#[cfg(feature = "ShowStatisticCommitV3")]
pub mod ShowStatisticCommitV3;
#[cfg(feature = "UnlockRepository")]
pub mod UnlockRepository;
#[cfg(feature = "UpdateMergeRequestApprovalState")]
pub mod UpdateMergeRequestApprovalState;
#[cfg(feature = "UpdateTenantTrustedIpAddress")]
pub mod UpdateTenantTrustedIpAddress;
#[cfg(feature = "UpdateTrustedIpAddress")]
pub mod UpdateTrustedIpAddress;
#[cfg(feature = "ValidateHttpsInfo")]
pub mod ValidateHttpsInfo;
#[cfg(feature = "ValidateHttpsInfoV2")]
pub mod ValidateHttpsInfoV2;
