#[cfg(feature = "AddDeployKey")]
pub mod AddDeployKey;
#[cfg(feature = "AddDeployKeyV2")]
pub mod AddDeployKeyV2;
#[cfg(feature = "AddGroupWebhook")]
pub mod AddGroupWebhook;
#[cfg(feature = "AddHooks")]
pub mod AddHooks;
#[cfg(feature = "AddProjectWebhook")]
pub mod AddProjectWebhook;
#[cfg(feature = "AddProtectBranchV2")]
pub mod AddProtectBranchV2;
#[cfg(feature = "AddRepoMembers")]
pub mod AddRepoMembers;
#[cfg(feature = "AddRepositoryMembers")]
pub mod AddRepositoryMembers;
#[cfg(feature = "AddRepositoryWebhook")]
pub mod AddRepositoryWebhook;
#[cfg(feature = "AddSshKey")]
pub mod AddSshKey;
#[cfg(feature = "AddSubmodule")]
pub mod AddSubmodule;
#[cfg(feature = "AddTagV2")]
pub mod AddTagV2;
#[cfg(feature = "AddTenantTrustedIpAddress")]
pub mod AddTenantTrustedIpAddress;
#[cfg(feature = "AddTrustedIpAddress")]
pub mod AddTrustedIpAddress;
#[cfg(feature = "ApprovalMergeRequest")]
pub mod ApprovalMergeRequest;
#[cfg(feature = "AssociateGroupUserGroup")]
pub mod AssociateGroupUserGroup;
#[cfg(feature = "AssociateIssues")]
pub mod AssociateIssues;
#[cfg(feature = "AssociateRemoteMirror")]
pub mod AssociateRemoteMirror;
#[cfg(feature = "AssociateRepositoryUserGroup")]
pub mod AssociateRepositoryUserGroup;
#[cfg(feature = "BatchCreateProtectedBranch")]
pub mod BatchCreateProtectedBranch;
#[cfg(feature = "BatchCreateProtectedTags")]
pub mod BatchCreateProtectedTags;
#[cfg(feature = "BatchDeleteProtectedBranches")]
pub mod BatchDeleteProtectedBranches;
#[cfg(feature = "BatchDeleteProtectedTags")]
pub mod BatchDeleteProtectedTags;
#[cfg(feature = "BatchDeleteRepositoryFilePushPermissions")]
pub mod BatchDeleteRepositoryFilePushPermissions;
#[cfg(feature = "BatchUpdateProtectedBranches")]
pub mod BatchUpdateProtectedBranches;
#[cfg(feature = "BatchUpdateProtectedTags")]
pub mod BatchUpdateProtectedTags;
#[cfg(feature = "BatchUpdateRepositoryFilePushPermissions")]
pub mod BatchUpdateRepositoryFilePushPermissions;
#[cfg(feature = "CheckDeployKey")]
pub mod CheckDeployKey;
#[cfg(feature = "CheckGroupDeployKey")]
pub mod CheckGroupDeployKey;
#[cfg(feature = "CreateBranch")]
pub mod CreateBranch;
#[cfg(feature = "CreateCommit")]
pub mod CreateCommit;
#[cfg(feature = "CreateCommitRevert")]
pub mod CreateCommitRevert;
#[cfg(feature = "CreateDir")]
pub mod CreateDir;
#[cfg(feature = "CreateFile")]
pub mod CreateFile;
#[cfg(feature = "CreateFilePushPermission")]
pub mod CreateFilePushPermission;
#[cfg(feature = "CreateGroup")]
pub mod CreateGroup;
#[cfg(feature = "CreateGroupMergeRequestApproverSetting")]
pub mod CreateGroupMergeRequestApproverSetting;
#[cfg(feature = "CreateMergeRequest")]
pub mod CreateMergeRequest;
#[cfg(feature = "CreateMergeRequestApproverSetting")]
pub mod CreateMergeRequestApproverSetting;
#[cfg(feature = "CreateMergeRequestDiscussion")]
pub mod CreateMergeRequestDiscussion;
#[cfg(feature = "CreateMergeRequestDiscussionNote")]
pub mod CreateMergeRequestDiscussionNote;
#[cfg(feature = "CreateMergeRequestDiscussionResponse")]
pub mod CreateMergeRequestDiscussionResponse;
#[cfg(feature = "CreateMergeRequestTemplate")]
pub mod CreateMergeRequestTemplate;
#[cfg(feature = "CreateNewBranch")]
pub mod CreateNewBranch;
#[cfg(feature = "CreateProjectAndforkRepositories")]
pub mod CreateProjectAndforkRepositories;
#[cfg(feature = "CreateProjectAndRepositories")]
pub mod CreateProjectAndRepositories;
#[cfg(feature = "CreateProjectMergeRequestApproverSetting")]
pub mod CreateProjectMergeRequestApproverSetting;
#[cfg(feature = "CreateRepository")]
pub mod CreateRepository;
#[cfg(feature = "CreateRepositoryLabel")]
pub mod CreateRepositoryLabel;
#[cfg(feature = "CreateRepositorySystemLabels")]
pub mod CreateRepositorySystemLabels;
#[cfg(feature = "CreateReviewSetting")]
pub mod CreateReviewSetting;
#[cfg(feature = "CreateTag")]
pub mod CreateTag;
#[cfg(feature = "DeleteBranch")]
pub mod DeleteBranch;
#[cfg(feature = "DeleteDeployKey")]
pub mod DeleteDeployKey;
#[cfg(feature = "DeleteDeployKeyV2")]
pub mod DeleteDeployKeyV2;
#[cfg(feature = "DeleteFile")]
pub mod DeleteFile;
#[cfg(feature = "DeleteGroup")]
pub mod DeleteGroup;
#[cfg(feature = "DeleteGroupMergeRequestApproverSetting")]
pub mod DeleteGroupMergeRequestApproverSetting;
#[cfg(feature = "DeleteHooks")]
pub mod DeleteHooks;
#[cfg(feature = "DeleteMergeRequestApproverSetting")]
pub mod DeleteMergeRequestApproverSetting;
#[cfg(feature = "DeleteMergeRequestTemplate")]
pub mod DeleteMergeRequestTemplate;
#[cfg(feature = "DeleteMergeRequestVote")]
pub mod DeleteMergeRequestVote;
#[cfg(feature = "DeleteProjectMergeRequestApproverSetting")]
pub mod DeleteProjectMergeRequestApproverSetting;
#[cfg(feature = "DeleteProtectedBranch")]
pub mod DeleteProtectedBranch;
#[cfg(feature = "DeleteProtectedTag")]
pub mod DeleteProtectedTag;
#[cfg(feature = "DeleteRepoMember")]
pub mod DeleteRepoMember;
#[cfg(feature = "DeleteRepository")]
pub mod DeleteRepository;
#[cfg(feature = "DeleteRepositoryLabel")]
pub mod DeleteRepositoryLabel;
#[cfg(feature = "DeleteSshKey")]
pub mod DeleteSshKey;
#[cfg(feature = "DeleteTag")]
pub mod DeleteTag;
#[cfg(feature = "DeleteTenantTrustedIpAddress")]
pub mod DeleteTenantTrustedIpAddress;
#[cfg(feature = "DeleteTrustedIpAddress")]
pub mod DeleteTrustedIpAddress;
#[cfg(feature = "DownloadArchive")]
pub mod DownloadArchive;
#[cfg(feature = "DownloadBlobsRaw")]
pub mod DownloadBlobsRaw;
#[cfg(feature = "GetAllRepositoryByProjectId")]
pub mod GetAllRepositoryByProjectId;
#[cfg(feature = "GetProductTemplates")]
pub mod GetProductTemplates;
#[cfg(feature = "GetRepositoryByProjectId")]
pub mod GetRepositoryByProjectId;
#[cfg(feature = "GetTemplates")]
pub mod GetTemplates;
#[cfg(feature = "ImportMergeRequest")]
pub mod ImportMergeRequest;
#[cfg(feature = "ListBranches")]
pub mod ListBranches;
#[cfg(feature = "ListBranchesByRepositoryId")]
pub mod ListBranchesByRepositoryId;
#[cfg(feature = "ListBranchRelatedWorkItems")]
pub mod ListBranchRelatedWorkItems;
#[cfg(feature = "ListCommitAssociatedMergeRequests")]
pub mod ListCommitAssociatedMergeRequests;
#[cfg(feature = "ListCommitAssociatedRefs")]
pub mod ListCommitAssociatedRefs;
#[cfg(feature = "ListCommits")]
pub mod ListCommits;
#[cfg(feature = "ListCommitStatistics")]
pub mod ListCommitStatistics;
#[cfg(feature = "ListCurrentUserRepositories")]
pub mod ListCurrentUserRepositories;
#[cfg(feature = "ListDefaultReviewCategories")]
pub mod ListDefaultReviewCategories;
#[cfg(feature = "ListDiscussionTemplates")]
pub mod ListDiscussionTemplates;
#[cfg(feature = "ListFileBlameLines")]
pub mod ListFileBlameLines;
#[cfg(feature = "ListFiles")]
pub mod ListFiles;
#[cfg(feature = "ListFilesByQuery")]
pub mod ListFilesByQuery;
#[cfg(feature = "ListFileUpperTreeEntries")]
pub mod ListFileUpperTreeEntries;
#[cfg(feature = "ListGroupAddableMembers")]
pub mod ListGroupAddableMembers;
#[cfg(feature = "ListGroupAddableUserGroups")]
pub mod ListGroupAddableUserGroups;
#[cfg(feature = "ListGroupDeployKeys")]
pub mod ListGroupDeployKeys;
#[cfg(feature = "ListGroupMembers")]
pub mod ListGroupMembers;
#[cfg(feature = "ListGroupMergeRequestApproverSettings")]
pub mod ListGroupMergeRequestApproverSettings;
#[cfg(feature = "ListGroupMergeRequestCanBeAssignedReviewers")]
pub mod ListGroupMergeRequestCanBeAssignedReviewers;
#[cfg(feature = "ListGroupMergeRequestValidAssignedCandidates")]
pub mod ListGroupMergeRequestValidAssignedCandidates;
