[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddCceIntegrationProtection = []
AddHostsGroup = []
AddLoginWhiteList = []
AddProtectionPolicy = []
AddSystemUserWhiteList = []
AssociatePolicyGroup = []
BatchAddAccounts = []
BatchCreateTags = []
BatchScanSwrImage = []
ChangeAntivirusPolicy = []
ChangeBlockedIp = []
ChangeCheckRuleAction = []
ChangeEvent = []
ChangeHostsGroup = []
ChangeIsolatedFile = []
ChangeVulScanPolicy = []
ChangeVulStatus = []
CreateAntiVirusPolicy = []
CreateAntiVirusTask = []
CreateDecoyPortPolicy = []
CreateQuotasOrder = []
CreateVulnerabilityScanTask = []
DeleteAccount = []
DeleteAgentDaemonset = []
DeleteAntivirusPolicy = []
DeleteDecoyPortHostPolicy = []
DeleteDecoyPortPolicy = []
DeleteHostsGroup = []
DeleteIsolatedFile = []
DeleteProtectionPolicy = []
DeleteResourceInstanceTag = []
ExportAntiVirusResult = []
ExportVuls = []
HandleAntiVirusResult = []
ListAccounts = []
ListAgentInstallScript = []
ListAlarmWhiteList = []
ListAntiVirusHost = []
ListAntiVirusPolicy = []
ListAntiVirusResult = []
ListAntiVirusTask = []
ListAntivirusHandleHistory = []
ListAppChangeHistories = []
ListAppStatistics = []
ListApps = []
ListAutoLaunchChangeHistories = []
ListAutoLaunchStatistics = []
ListAutoLaunchs = []
ListBackupVaults = []
ListBlockedIp = []
ListCceClusterConfig = []
ListCheckFeatureRule = []
ListContainerNodes = []
ListContainers = []
ListDecoyPortPolicy = []
ListDownloadExportedFile = []
ListEventHandleHistory = []
ListHostGroups = []
ListHostProtectHistoryInfo = []
ListHostRaspProtectHistoryInfo = []
ListHostStatus = []
ListHostVuls = []
ListImageLocal = []
ListImageRiskConfigRules = []
ListImageRiskConfigs = []
ListImageVulnerabilities = []
ListIsolatedFile = []
ListJarPackageHostInfo = []
ListJarPackageStatistics = []
ListLoginCommonIp = []
ListLoginCommonLocation = []
ListLoginWhiteIp = []
ListLoginWhiteList = []
ListOperationLogsByVaultName = []
ListOrganizationTree = []
ListPasswordComplexity = []
ListPolicies = []
ListPolicyGroup = []
ListPortHost = []
ListPortStatistics = []
ListPorts = []
ListProcessStatistics = []
ListProcessesHost = []
ListProtectionPolicy = []
ListProtectionServer = []
ListProtectionServers = []
ListQueryExportTask = []
ListQuotasDetail = []
ListRansomwareProtectionNodes = []
ListRaspEvents = []
ListRaspPolicies = []
ListRiskConfigCheckRules = []
ListRiskConfigHosts = []
ListRiskConfigs = []
ListSecurityEvents = []
ListSwrImageRepository = []
ListSystemUserWhiteList = []
ListTwoFactorLoginHost = []
ListUserChangeHistories = []
ListUsers = []
full = ["AddCceIntegrationProtection", "AddHostsGroup", "AddLoginWhiteList", "AddProtectionPolicy", "AddSystemUserWhiteList", "AssociatePolicyGroup", "BatchAddAccounts", "BatchCreateTags", "BatchScanSwrImage", "ChangeAntivirusPolicy", "ChangeBlockedIp", "ChangeCheckRuleAction", "ChangeEvent", "ChangeHostsGroup", "ChangeIsolatedFile", "ChangeVulScanPolicy", "ChangeVulStatus", "CreateAntiVirusPolicy", "CreateAntiVirusTask", "CreateDecoyPortPolicy", "CreateQuotasOrder", "CreateVulnerabilityScanTask", "DeleteAccount", "DeleteAgentDaemonset", "DeleteAntivirusPolicy", "DeleteDecoyPortHostPolicy", "DeleteDecoyPortPolicy", "DeleteHostsGroup", "DeleteIsolatedFile", "DeleteProtectionPolicy", "DeleteResourceInstanceTag", "ExportAntiVirusResult", "ExportVuls", "HandleAntiVirusResult", "ListAccounts", "ListAgentInstallScript", "ListAlarmWhiteList", "ListAntivirusHandleHistory", "ListAntiVirusHost", "ListAntiVirusPolicy", "ListAntiVirusResult", "ListAntiVirusTask", "ListAppChangeHistories", "ListApps", "ListAppStatistics", "ListAutoLaunchChangeHistories", "ListAutoLaunchs", "ListAutoLaunchStatistics", "ListBackupVaults", "ListBlockedIp", "ListCceClusterConfig", "ListCheckFeatureRule", "ListContainerNodes", "ListContainers", "ListDecoyPortPolicy", "ListDownloadExportedFile", "ListEventHandleHistory", "ListHostGroups", "ListHostProtectHistoryInfo", "ListHostRaspProtectHistoryInfo", "ListHostStatus", "ListHostVuls", "ListImageLocal", "ListImageRiskConfigRules", "ListImageRiskConfigs", "ListImageVulnerabilities", "ListIsolatedFile", "ListJarPackageHostInfo", "ListJarPackageStatistics", "ListLoginCommonIp", "ListLoginCommonLocation", "ListLoginWhiteIp", "ListLoginWhiteList", "ListOperationLogsByVaultName", "ListOrganizationTree", "ListPasswordComplexity", "ListPolicies", "ListPolicyGroup", "ListPortHost", "ListPorts", "ListPortStatistics", "ListProcessesHost", "ListProcessStatistics", "ListProtectionPolicy", "ListProtectionServer", "ListProtectionServers", "ListQueryExportTask", "ListQuotasDetail", "ListRansomwareProtectionNodes", "ListRaspEvents", "ListRaspPolicies", "ListRiskConfigCheckRules", "ListRiskConfigHosts", "ListRiskConfigs", "ListSecurityEvents", "ListSwrImageRepository", "ListSystemUserWhiteList", "ListTwoFactorLoginHost", "ListUserChangeHistories", "ListUsers"]

[lib]
name = "huawei_cloud_api_definitions_HSS"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-HSS"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
