[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddAppWhitelistPolicyHost = []
AddAppWhitelistPolicyProcess = []
AddBaselineWhiteList = []
AddCceIntegrationProtection = []
AddCicdConfiguration = []
AddHostsGroup = []
AddImageWhiteLists = []
AddLoginWhiteList = []
AddPolicy = []
AddPolicyGroup = []
AddProtectionPolicy = []
AddRegistry = []
AddSystemUserWhiteList = []
AddVulWhiteList = []
AssociateHostAssetValue = []
AssociateHostsGroup = []
AssociatePolicyGroup = []
AssociateProtectionPolicy = []
BatchAddAccounts = []
BatchChangeEvent = []
BatchCreateTags = []
BatchDeleteAgentDaemonset = []
BatchDeleteRegistry = []
BatchDeleteTags = []
BatchExportBaselineTask = []
BatchExportLocalVulTask = []
BatchScanLocalImage = []
BatchScanSwrImage = []
BatchStartProtection = []
BatchStartWebTamperProtection = []
BatchUpgradeAgentDaemonset = []
CancelHostsQuota = []
ChangeAgentAutoUpgradeStatus = []
ChangeAntivirusPayPerScanStatus = []
ChangeAntivirusPolicy = []
ChangeAppWhitelistPolicy = []
ChangeAppWhitelistPolicyProcessStatus = []
ChangeAutoOpenQuotaStatus = []
ChangeBaselineWhiteList = []
ChangeBlockedIp = []
ChangeCheckRuleAction = []
ChangeClusterEvents = []
ChangeClusterProtectionPolicy = []
ChangeContainerStatus = []
ChangeEvent = []
ChangeExtendedWeakPassword = []
ChangeHostIgnoreStatus = []
ChangeHostsGroup = []
ChangeImageWhiteList = []
ChangeIsolatedFile = []
ChangeMalwareCollectStatus = []
ChangeMonthlyOperationReportTipStatus = []
ChangePasswordComplexityStatus = []
ChangePolicyGroup = []
ChangePolicySwitchStatus = []
ChangeSwitchesStatus = []
ChangeVulScanPolicy = []
ChangeVulStatus = []
ChangeVulWhiteList = []
CopyBaselinePolicyGroup = []
CreateAgentDaemonset = []
CreateAntiVirusPaidTask = []
CreateAntiVirusPolicy = []
CreateAntiVirusTask = []
CreateAppWhitelistPolicy = []
CreateCicdConfigurationCommand = []
CreateClusterProtectionPolicy = []
CreateClustersInfo = []
CreateContainerNetworkPolicy = []
CreateDecoyPortPolicy = []
CreateGlobalAssetScanTask = []
CreateImageSynchronizeTask = []
CreateManualImageScanTask = []
CreateMultiCloudClusters = []
CreateQuotasOrder = []
CreateSecurityGroupPolicy = []
CreateTask = []
CreateVpcEndpoint = []
CreateVulnerabilityScanTask = []
DeleteAccount = []
DeleteAgentDaemonset = []
DeleteAntivirusPolicy = []
DeleteAppWhitelistPolicy = []
DeleteAppWhitelistPolicyHost = []
DeleteBackupHostInfo = []
DeleteBaselineWhiteList = []
DeleteCicdConfigurations = []
DeleteClusterProtectionPolicy = []
DeleteContainerNetworkPolicy = []
DeleteDecoyPortHostPolicy = []
DeleteDecoyPortPolicy = []
DeleteDuplicationInfo = []
DeleteHostsGroup = []
DeleteImageWhiteLists = []
DeleteIsolatedFile = []
DeletePolicy = []
DeletePolicyGroup = []
DeleteProtectionPolicy = []
DeleteRegistry = []
DeleteResourceInstanceTag = []
full = ["AddAppWhitelistPolicyHost", "AddAppWhitelistPolicyProcess", "AddBaselineWhiteList", "AddCceIntegrationProtection", "AddCicdConfiguration", "AddHostsGroup", "AddImageWhiteLists", "AddLoginWhiteList", "AddPolicy", "AddPolicyGroup", "AddProtectionPolicy", "AddRegistry", "AddSystemUserWhiteList", "AddVulWhiteList", "AssociateHostAssetValue", "AssociateHostsGroup", "AssociatePolicyGroup", "AssociateProtectionPolicy", "BatchAddAccounts", "BatchChangeEvent", "BatchCreateTags", "BatchDeleteAgentDaemonset", "BatchDeleteRegistry", "BatchDeleteTags", "BatchExportBaselineTask", "BatchExportLocalVulTask", "BatchScanLocalImage", "BatchScanSwrImage", "BatchStartProtection", "BatchStartWebTamperProtection", "BatchUpgradeAgentDaemonset", "CancelHostsQuota", "ChangeAgentAutoUpgradeStatus", "ChangeAntivirusPayPerScanStatus", "ChangeAntivirusPolicy", "ChangeAppWhitelistPolicy", "ChangeAppWhitelistPolicyProcessStatus", "ChangeAutoOpenQuotaStatus", "ChangeBaselineWhiteList", "ChangeBlockedIp", "ChangeCheckRuleAction", "ChangeClusterEvents", "ChangeClusterProtectionPolicy", "ChangeContainerStatus", "ChangeEvent", "ChangeExtendedWeakPassword", "ChangeHostIgnoreStatus", "ChangeHostsGroup", "ChangeImageWhiteList", "ChangeIsolatedFile", "ChangeMalwareCollectStatus", "ChangeMonthlyOperationReportTipStatus", "ChangePasswordComplexityStatus", "ChangePolicyGroup", "ChangePolicySwitchStatus", "ChangeSwitchesStatus", "ChangeVulScanPolicy", "ChangeVulStatus", "ChangeVulWhiteList", "CopyBaselinePolicyGroup", "CreateAgentDaemonset", "CreateAntiVirusPaidTask", "CreateAntiVirusPolicy", "CreateAntiVirusTask", "CreateAppWhitelistPolicy", "CreateCicdConfigurationCommand", "CreateClusterProtectionPolicy", "CreateClustersInfo", "CreateContainerNetworkPolicy", "CreateDecoyPortPolicy", "CreateGlobalAssetScanTask", "CreateImageSynchronizeTask", "CreateManualImageScanTask", "CreateMultiCloudClusters", "CreateQuotasOrder", "CreateSecurityGroupPolicy", "CreateTask", "CreateVpcEndpoint", "CreateVulnerabilityScanTask", "DeleteAccount", "DeleteAgentDaemonset", "DeleteAntivirusPolicy", "DeleteAppWhitelistPolicy", "DeleteAppWhitelistPolicyHost", "DeleteBackupHostInfo", "DeleteBaselineWhiteList", "DeleteCicdConfigurations", "DeleteClusterProtectionPolicy", "DeleteContainerNetworkPolicy", "DeleteDecoyPortHostPolicy", "DeleteDecoyPortPolicy", "DeleteDuplicationInfo", "DeleteHostsGroup", "DeleteImageWhiteLists", "DeleteIsolatedFile", "DeletePolicy", "DeletePolicyGroup", "DeleteProtectionPolicy", "DeleteRegistry", "DeleteResourceInstanceTag"]

[lib]
name = "huawei_cloud_api_definitions_HSS"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-HSS"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
