[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddHostsGroup = []
AssociatePolicyGroup = []
BatchCreateTags = []
BatchScanSwrImage = []
ChangeBlockedIp = []
ChangeCheckRuleAction = []
ChangeEvent = []
ChangeHostsGroup = []
ChangeIsolatedFile = []
ChangeVulScanPolicy = []
ChangeVulStatus = []
CreateVulnerabilityScanTask = []
DeleteHostsGroup = []
DeleteResourceInstanceTag = []
ListAlarmWhiteList = []
ListAppChangeHistories = []
ListAppStatistics = []
ListApps = []
ListAutoLaunchChangeHistories = []
ListAutoLaunchStatistics = []
ListAutoLaunchs = []
ListBlockedIp = []
ListContainerNodes = []
ListEvents = []
ListHostGroups = []
ListHostProtectHistoryInfo = []
ListHostRaspProtectHistoryInfo = []
ListHostStatus = []
ListHostVuls = []
ListHosts = []
ListImageRiskConfigRules = []
ListImageRiskConfigs = []
ListImageVulnerabilities = []
ListIsolatedFile = []
ListJarPackageHostInfo = []
ListJarPackageStatistics = []
ListPasswordComplexity = []
ListPolicyGroup = []
ListPortHost = []
ListPortStatistics = []
ListPorts = []
ListProcessStatistics = []
ListProcessesHost = []
ListProtectionPolicy = []
ListProtectionServer = []
ListQuotasDetail = []
ListRiskConfigCheckRules = []
ListRiskConfigHosts = []
ListRiskConfigs = []
ListSecurityEvents = []
ListSwrImageRepository = []
ListUserChangeHistories = []
ListUserStatistics = []
ListUsers = []
ListVulHosts = []
ListVulScanTask = []
ListVulScanTaskHost = []
ListVulnerabilities = []
ListVulnerabilityCve = []
ListWeakPasswordUsers = []
ListWtpProtectHost = []
RunImageSynchronize = []
SetRaspSwitch = []
SetWtpProtectionStatusInfo = []
ShowAssetStatistic = []
ShowBackupPolicyInfo = []
ShowCheckRuleDetail = []
ShowImageCheckRuleDetail = []
ShowResourceQuotas = []
ShowRiskConfigDetail = []
ShowVulScanPolicy = []
ShowVulStatics = []
StartProtection = []
StopProtection = []
SwitchHostsProtectStatus = []
UpdateBackupPolicyInfo = []
UpdateProtectionPolicy = []
full = ["AddHostsGroup", "AssociatePolicyGroup", "BatchCreateTags", "BatchScanSwrImage", "ChangeBlockedIp", "ChangeCheckRuleAction", "ChangeEvent", "ChangeHostsGroup", "ChangeIsolatedFile", "ChangeVulScanPolicy", "ChangeVulStatus", "CreateVulnerabilityScanTask", "DeleteHostsGroup", "DeleteResourceInstanceTag", "ListAlarmWhiteList", "ListAppChangeHistories", "ListApps", "ListAppStatistics", "ListAutoLaunchChangeHistories", "ListAutoLaunchs", "ListAutoLaunchStatistics", "ListBlockedIp", "ListContainerNodes", "ListEvents", "ListHostGroups", "ListHostProtectHistoryInfo", "ListHostRaspProtectHistoryInfo", "ListHosts", "ListHostStatus", "ListHostVuls", "ListImageRiskConfigRules", "ListImageRiskConfigs", "ListImageVulnerabilities", "ListIsolatedFile", "ListJarPackageHostInfo", "ListJarPackageStatistics", "ListPasswordComplexity", "ListPolicyGroup", "ListPortHost", "ListPorts", "ListPortStatistics", "ListProcessesHost", "ListProcessStatistics", "ListProtectionPolicy", "ListProtectionServer", "ListQuotasDetail", "ListRiskConfigCheckRules", "ListRiskConfigHosts", "ListRiskConfigs", "ListSecurityEvents", "ListSwrImageRepository", "ListUserChangeHistories", "ListUsers", "ListUserStatistics", "ListVulHosts", "ListVulnerabilities", "ListVulnerabilityCve", "ListVulScanTask", "ListVulScanTaskHost", "ListWeakPasswordUsers", "ListWtpProtectHost", "RunImageSynchronize", "SetRaspSwitch", "SetWtpProtectionStatusInfo", "ShowAssetStatistic", "ShowBackupPolicyInfo", "ShowCheckRuleDetail", "ShowImageCheckRuleDetail", "ShowResourceQuotas", "ShowRiskConfigDetail", "ShowVulScanPolicy", "ShowVulStatics", "StartProtection", "StopProtection", "SwitchHostsProtectStatus", "UpdateBackupPolicyInfo", "UpdateProtectionPolicy"]

[lib]
name = "huawei_cloud_api_definitions_HSS"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-HSS"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
