[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddCceIntegrationProtection = []
AddHostsGroup = []
AddLoginWhiteList = []
AddPolicy = []
AddProtectionPolicy = []
AddSystemUserWhiteList = []
AssociatePolicyGroup = []
BatchAddAccounts = []
BatchCreateTags = []
BatchDeleteAgentDaemonset = []
BatchScanSwrImage = []
BatchStartProtection = []
BatchUpgradeAgentDaemonset = []
ChangeAntivirusPolicy = []
ChangeBlockedIp = []
ChangeCheckRuleAction = []
ChangeClusterEvents = []
ChangeClusterProtectionPolicy = []
ChangeEvent = []
ChangeHostsGroup = []
ChangeIsolatedFile = []
ChangePasswordComplexityStatus = []
ChangeVulScanPolicy = []
ChangeVulStatus = []
CreateAgentDaemonset = []
CreateAntiVirusPolicy = []
CreateAntiVirusTask = []
CreateClusterProtectionPolicy = []
CreateClustersInfo = []
CreateContainerNetworkPolicy = []
CreateDecoyPortPolicy = []
CreateGlobalAssetScanTask = []
CreateMultiCloudClusters = []
CreateQuotasOrder = []
CreateSecurityGroupPolicy = []
CreateVulnerabilityScanTask = []
DeleteAccount = []
DeleteAgentDaemonset = []
DeleteAntivirusPolicy = []
DeleteClusterProtectionPolicy = []
DeleteContainerNetworkPolicy = []
DeleteDecoyPortHostPolicy = []
DeleteDecoyPortPolicy = []
DeleteHostsGroup = []
DeleteIsolatedFile = []
DeletePolicy = []
DeleteProtectionPolicy = []
DeleteResourceInstanceTag = []
DeleteSecurityGroupPolicy = []
ExportAntiVirusResult = []
ExportContainerList = []
ExportVuls = []
HandleAntiVirusResult = []
ListAccounts = []
ListAgentInstallScript = []
ListAlarmWhiteList = []
ListAntiVirusHost = []
ListAntiVirusPolicy = []
ListAntiVirusResult = []
ListAntiVirusTask = []
ListAntivirusHandleHistory = []
ListAppChangeHistories = []
ListAppStatistics = []
ListApps = []
ListAutoLaunchChangeHistories = []
ListAutoLaunchStatistics = []
ListAutoLaunchs = []
ListBackupVaults = []
ListBlockedIp = []
ListCceClusterConfig = []
ListCceClusterDetectRisk = []
ListCheckFeatureRule = []
ListClusterAuditLogs = []
ListClusterEventLogs = []
ListClusterEvents = []
ListClusterProtectOverview = []
ListClusterProtectPolicyTemplates = []
ListClusterProtectionDefaultPolicy = []
ListClusterProtectionInfo = []
ListClusterProtectionItem = []
ListClusterProtectionPolicy = []
ListClusterProtectionPolicyDetail = []
ListCommonTips = []
ListContainerCmdLogs = []
ListContainerImageLogs = []
ListContainerImages = []
ListContainerLogs = []
ListContainerNetworkClusters = []
ListContainerNetworkNodeList = []
ListContainerNetworkPolicy = []
ListContainerNodes = []
ListContainers = []
ListDecoyPortPolicy = []
ListDownloadExportedFile = []
ListEventHandleHistory = []
ListGlobalAssetScanTask = []
ListHostGroups = []
ListHostProtectHistoryInfo = []
ListHostRaspProtectHistoryInfo = []
ListHostStatus = []
full = ["AddCceIntegrationProtection", "AddHostsGroup", "AddLoginWhiteList", "AddPolicy", "AddProtectionPolicy", "AddSystemUserWhiteList", "AssociatePolicyGroup", "BatchAddAccounts", "BatchCreateTags", "BatchDeleteAgentDaemonset", "BatchScanSwrImage", "BatchStartProtection", "BatchUpgradeAgentDaemonset", "ChangeAntivirusPolicy", "ChangeBlockedIp", "ChangeCheckRuleAction", "ChangeClusterEvents", "ChangeClusterProtectionPolicy", "ChangeEvent", "ChangeHostsGroup", "ChangeIsolatedFile", "ChangePasswordComplexityStatus", "ChangeVulScanPolicy", "ChangeVulStatus", "CreateAgentDaemonset", "CreateAntiVirusPolicy", "CreateAntiVirusTask", "CreateClusterProtectionPolicy", "CreateClustersInfo", "CreateContainerNetworkPolicy", "CreateDecoyPortPolicy", "CreateGlobalAssetScanTask", "CreateMultiCloudClusters", "CreateQuotasOrder", "CreateSecurityGroupPolicy", "CreateVulnerabilityScanTask", "DeleteAccount", "DeleteAgentDaemonset", "DeleteAntivirusPolicy", "DeleteClusterProtectionPolicy", "DeleteContainerNetworkPolicy", "DeleteDecoyPortHostPolicy", "DeleteDecoyPortPolicy", "DeleteHostsGroup", "DeleteIsolatedFile", "DeletePolicy", "DeleteProtectionPolicy", "DeleteResourceInstanceTag", "DeleteSecurityGroupPolicy", "ExportAntiVirusResult", "ExportContainerList", "ExportVuls", "HandleAntiVirusResult", "ListAccounts", "ListAgentInstallScript", "ListAlarmWhiteList", "ListAntivirusHandleHistory", "ListAntiVirusHost", "ListAntiVirusPolicy", "ListAntiVirusResult", "ListAntiVirusTask", "ListAppChangeHistories", "ListApps", "ListAppStatistics", "ListAutoLaunchChangeHistories", "ListAutoLaunchs", "ListAutoLaunchStatistics", "ListBackupVaults", "ListBlockedIp", "ListCceClusterConfig", "ListCceClusterDetectRisk", "ListCheckFeatureRule", "ListClusterAuditLogs", "ListClusterEventLogs", "ListClusterEvents", "ListClusterProtectionDefaultPolicy", "ListClusterProtectionInfo", "ListClusterProtectionItem", "ListClusterProtectionPolicy", "ListClusterProtectionPolicyDetail", "ListClusterProtectOverview", "ListClusterProtectPolicyTemplates", "ListCommonTips", "ListContainerCmdLogs", "ListContainerImageLogs", "ListContainerImages", "ListContainerLogs", "ListContainerNetworkClusters", "ListContainerNetworkNodeList", "ListContainerNetworkPolicy", "ListContainerNodes", "ListContainers", "ListDecoyPortPolicy", "ListDownloadExportedFile", "ListEventHandleHistory", "ListGlobalAssetScanTask", "ListHostGroups", "ListHostProtectHistoryInfo", "ListHostRaspProtectHistoryInfo", "ListHostStatus"]

[lib]
name = "huawei_cloud_api_definitions_HSS"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-HSS"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
