#[cfg(feature = "CancelSubscriptions")]
pub mod CancelSubscriptions;
#[cfg(feature = "CreateMessageTemplate")]
pub mod CreateMessageTemplate;
#[cfg(feature = "CreateTopic")]
pub mod CreateTopic;
#[cfg(feature = "DeleteMessageTemplate")]
pub mod DeleteMessageTemplate;
#[cfg(feature = "DeleteTopic")]
pub mod DeleteTopic;
#[cfg(feature = "DeleteTopicAttributeByName")]
pub mod DeleteTopicAttributeByName;
#[cfg(feature = "DeleteTopicAttributes")]
pub mod DeleteTopicAttributes;
#[cfg(feature = "ListMessageTemplates")]
pub mod ListMessageTemplates;
#[cfg(feature = "ListSubscriptions")]
pub mod ListSubscriptions;
#[cfg(feature = "ListSubscriptionsByTopic")]
pub mod ListSubscriptionsByTopic;
#[cfg(feature = "ListTopicAttributes")]
pub mod ListTopicAttributes;
#[cfg(feature = "ListTopics")]
pub mod ListTopics;
#[cfg(feature = "PublishMessage")]
pub mod PublishMessage;
#[cfg(feature = "PublishSms")]
pub mod PublishSms;
#[cfg(feature = "ShowCertification")]
pub mod ShowCertification;
#[cfg(feature = "ShowMessageTemplateDetail")]
pub mod ShowMessageTemplateDetail;
#[cfg(feature = "ShowTopicDetail")]
pub mod ShowTopicDetail;
#[cfg(feature = "SubscribeTopic")]
pub mod SubscribeTopic;
#[cfg(feature = "UpdateMessageTemplate")]
pub mod UpdateMessageTemplate;
#[cfg(feature = "UpdateTopic")]
pub mod UpdateTopic;
#[cfg(feature = "UpdateTopicAttribute")]
pub mod UpdateTopicAttribute;
