#[cfg(feature = "CreateImageSyncRepo")]
pub mod CreateImageSyncRepo;
#[cfg(feature = "CreateManualImageSyncRepo")]
pub mod CreateManualImageSyncRepo;
#[cfg(feature = "CreateNamespace")]
pub mod CreateNamespace;
#[cfg(feature = "CreateNamespaceAuth")]
pub mod CreateNamespaceAuth;
#[cfg(feature = "CreateRepo")]
pub mod CreateRepo;
#[cfg(feature = "CreateRepoDomains")]
pub mod CreateRepoDomains;
#[cfg(feature = "CreateRepoTag")]
pub mod CreateRepoTag;
#[cfg(feature = "CreateRetention")]
pub mod CreateRetention;
#[cfg(feature = "CreateSecret")]
pub mod CreateSecret;
#[cfg(feature = "CreateTrigger")]
pub mod CreateTrigger;
#[cfg(feature = "CreateUserRepositoryAuth")]
pub mod CreateUserRepositoryAuth;
#[cfg(feature = "DeleteImageSyncRepo")]
pub mod DeleteImageSyncRepo;
#[cfg(feature = "DeleteNamespaceAuth")]
pub mod DeleteNamespaceAuth;
#[cfg(feature = "DeleteNamespaces")]
pub mod DeleteNamespaces;
#[cfg(feature = "DeleteRepo")]
pub mod DeleteRepo;
#[cfg(feature = "DeleteRepoDomains")]
pub mod DeleteRepoDomains;
#[cfg(feature = "DeleteRepoTag")]
pub mod DeleteRepoTag;
#[cfg(feature = "DeleteRetention")]
pub mod DeleteRetention;
#[cfg(feature = "DeleteTrigger")]
pub mod DeleteTrigger;
#[cfg(feature = "DeleteUserRepositoryAuth")]
pub mod DeleteUserRepositoryAuth;
#[cfg(feature = "ListApiVersions")]
pub mod ListApiVersions;
#[cfg(feature = "ListImageAutoSyncReposDetails")]
pub mod ListImageAutoSyncReposDetails;
#[cfg(feature = "ListNamespaces")]
pub mod ListNamespaces;
#[cfg(feature = "ListQuotas")]
pub mod ListQuotas;
#[cfg(feature = "ListRepoDomains")]
pub mod ListRepoDomains;
#[cfg(feature = "ListReposDetails")]
pub mod ListReposDetails;
#[cfg(feature = "ListRepositoryTags")]
pub mod ListRepositoryTags;
#[cfg(feature = "ListRetentionHistories")]
pub mod ListRetentionHistories;
#[cfg(feature = "ListRetentions")]
pub mod ListRetentions;
#[cfg(feature = "ListSharedReposDetails")]
pub mod ListSharedReposDetails;
#[cfg(feature = "ListTriggersDetails")]
pub mod ListTriggersDetails;
#[cfg(feature = "ShowAccessDomain")]
pub mod ShowAccessDomain;
#[cfg(feature = "ShowApiVersion")]
pub mod ShowApiVersion;
#[cfg(feature = "ShowDomainOverview")]
pub mod ShowDomainOverview;
#[cfg(feature = "ShowDomainResourceReports")]
pub mod ShowDomainResourceReports;
#[cfg(feature = "ShowNamespace")]
pub mod ShowNamespace;
#[cfg(feature = "ShowNamespaceAuth")]
pub mod ShowNamespaceAuth;
#[cfg(feature = "ShowRepository")]
pub mod ShowRepository;
#[cfg(feature = "ShowRetention")]
pub mod ShowRetention;
#[cfg(feature = "ShowShareFeatureGates")]
pub mod ShowShareFeatureGates;
#[cfg(feature = "ShowSyncJob")]
pub mod ShowSyncJob;
#[cfg(feature = "ShowTrigger")]
pub mod ShowTrigger;
#[cfg(feature = "ShowUserRepositoryAuth")]
pub mod ShowUserRepositoryAuth;
#[cfg(feature = "UpdateNamespaceAuth")]
pub mod UpdateNamespaceAuth;
#[cfg(feature = "UpdateRepo")]
pub mod UpdateRepo;
#[cfg(feature = "UpdateRepoDomains")]
pub mod UpdateRepoDomains;
#[cfg(feature = "UpdateRetention")]
pub mod UpdateRetention;
#[cfg(feature = "UpdateTrigger")]
pub mod UpdateTrigger;
#[cfg(feature = "UpdateUserRepositoryAuth")]
pub mod UpdateUserRepositoryAuth;
