#[cfg(feature = "AddDomainName")]
pub mod AddDomainName;
#[cfg(feature = "CreateAuthorizationToken")]
pub mod CreateAuthorizationToken;
#[cfg(feature = "CreateImageSyncRepo")]
pub mod CreateImageSyncRepo;
#[cfg(feature = "CreateImmutableRule")]
pub mod CreateImmutableRule;
#[cfg(feature = "CreateInstance")]
pub mod CreateInstance;
#[cfg(feature = "CreateInstanceEndpointPolicy")]
pub mod CreateInstanceEndpointPolicy;
#[cfg(feature = "CreateInstanceInternalEndpoint")]
pub mod CreateInstanceInternalEndpoint;
#[cfg(feature = "CreateInstanceLtCredential")]
pub mod CreateInstanceLtCredential;
#[cfg(feature = "CreateInstanceNamespace")]
pub mod CreateInstanceNamespace;
#[cfg(feature = "CreateInstanceRegistry")]
pub mod CreateInstanceRegistry;
#[cfg(feature = "CreateInstanceReplicationPolicy")]
pub mod CreateInstanceReplicationPolicy;
#[cfg(feature = "CreateInstanceResourceTags")]
pub mod CreateInstanceResourceTags;
#[cfg(feature = "CreateInstanceRetentionPolicy")]
pub mod CreateInstanceRetentionPolicy;
#[cfg(feature = "CreateInstanceSignPolicy")]
pub mod CreateInstanceSignPolicy;
#[cfg(feature = "CreateInstanceTempCredential")]
pub mod CreateInstanceTempCredential;
#[cfg(feature = "CreateInstanceWebhook")]
pub mod CreateInstanceWebhook;
#[cfg(feature = "CreateManualImageSyncRepo")]
pub mod CreateManualImageSyncRepo;
#[cfg(feature = "CreateNamespace")]
pub mod CreateNamespace;
#[cfg(feature = "CreateNamespaceAuth")]
pub mod CreateNamespaceAuth;
#[cfg(feature = "CreateRepo")]
pub mod CreateRepo;
#[cfg(feature = "CreateRepoDomains")]
pub mod CreateRepoDomains;
#[cfg(feature = "CreateRepoTag")]
pub mod CreateRepoTag;
#[cfg(feature = "CreateRetention")]
pub mod CreateRetention;
#[cfg(feature = "CreateSecret")]
pub mod CreateSecret;
#[cfg(feature = "CreateSubResourceTags")]
pub mod CreateSubResourceTags;
#[cfg(feature = "CreateTrigger")]
pub mod CreateTrigger;
#[cfg(feature = "CreateUserRepositoryAuth")]
pub mod CreateUserRepositoryAuth;
#[cfg(feature = "DeleteDomainName")]
pub mod DeleteDomainName;
#[cfg(feature = "DeleteImageSyncRepo")]
pub mod DeleteImageSyncRepo;
#[cfg(feature = "DeleteImmutableRule")]
pub mod DeleteImmutableRule;
#[cfg(feature = "DeleteInstance")]
pub mod DeleteInstance;
#[cfg(feature = "DeleteInstanceArtifact")]
pub mod DeleteInstanceArtifact;
#[cfg(feature = "DeleteInstanceInternalEndpoint")]
pub mod DeleteInstanceInternalEndpoint;
#[cfg(feature = "DeleteInstanceJob")]
pub mod DeleteInstanceJob;
#[cfg(feature = "DeleteInstanceLtCredential")]
pub mod DeleteInstanceLtCredential;
#[cfg(feature = "DeleteInstanceNamespace")]
pub mod DeleteInstanceNamespace;
#[cfg(feature = "DeleteInstanceRegistry")]
pub mod DeleteInstanceRegistry;
#[cfg(feature = "DeleteInstanceReplicationPolicy")]
pub mod DeleteInstanceReplicationPolicy;
#[cfg(feature = "DeleteInstanceRepository")]
pub mod DeleteInstanceRepository;
#[cfg(feature = "DeleteInstanceResourceTags")]
pub mod DeleteInstanceResourceTags;
#[cfg(feature = "DeleteInstanceRetentionPolicy")]
pub mod DeleteInstanceRetentionPolicy;
#[cfg(feature = "DeleteInstanceSignPolicy")]
pub mod DeleteInstanceSignPolicy;
#[cfg(feature = "DeleteInstanceWebhook")]
pub mod DeleteInstanceWebhook;
#[cfg(feature = "DeleteNamespaceAuth")]
pub mod DeleteNamespaceAuth;
#[cfg(feature = "DeleteNamespaces")]
pub mod DeleteNamespaces;
#[cfg(feature = "DeleteRepo")]
pub mod DeleteRepo;
#[cfg(feature = "DeleteRepoDomains")]
pub mod DeleteRepoDomains;
#[cfg(feature = "DeleteRepoTag")]
pub mod DeleteRepoTag;
#[cfg(feature = "DeleteRetention")]
pub mod DeleteRetention;
#[cfg(feature = "DeleteSubResourceTags")]
pub mod DeleteSubResourceTags;
#[cfg(feature = "DeleteTrigger")]
pub mod DeleteTrigger;
#[cfg(feature = "DeleteUserRepositoryAuth")]
pub mod DeleteUserRepositoryAuth;
#[cfg(feature = "ExecuteInstanceReplicationPolicy")]
pub mod ExecuteInstanceReplicationPolicy;
#[cfg(feature = "ExecuteInstanceRetentionPolicy")]
pub mod ExecuteInstanceRetentionPolicy;
#[cfg(feature = "ExecuteInstanceSignPolicy")]
pub mod ExecuteInstanceSignPolicy;
#[cfg(feature = "ListApiVersions")]
pub mod ListApiVersions;
#[cfg(feature = "ListAuditLogs")]
pub mod ListAuditLogs;
#[cfg(feature = "ListDomainNames")]
pub mod ListDomainNames;
#[cfg(feature = "ListFeatureGates")]
pub mod ListFeatureGates;
#[cfg(feature = "ListGlobalFeatureGates")]
pub mod ListGlobalFeatureGates;
#[cfg(feature = "ListImageAutoSyncReposDetails")]
pub mod ListImageAutoSyncReposDetails;
#[cfg(feature = "ListImmutableRules")]
pub mod ListImmutableRules;
#[cfg(feature = "ListInstance")]
pub mod ListInstance;
#[cfg(feature = "ListInstanceAccessories")]
pub mod ListInstanceAccessories;
#[cfg(feature = "ListInstanceAllArtifacts")]
pub mod ListInstanceAllArtifacts;
#[cfg(feature = "ListInstanceArtifacts")]
pub mod ListInstanceArtifacts;
#[cfg(feature = "ListInstanceInternalEndpoints")]
pub mod ListInstanceInternalEndpoints;
#[cfg(feature = "ListInstanceJobs")]
pub mod ListInstanceJobs;
#[cfg(feature = "ListInstanceLtCredentials")]
pub mod ListInstanceLtCredentials;
#[cfg(feature = "ListInstanceNamespaces")]
pub mod ListInstanceNamespaces;
#[cfg(feature = "ListInstanceProjectTags")]
pub mod ListInstanceProjectTags;
#[cfg(feature = "ListInstanceRegistries")]
pub mod ListInstanceRegistries;
#[cfg(feature = "ListInstanceReplicationPolicies")]
pub mod ListInstanceReplicationPolicies;
#[cfg(feature = "ListInstanceReplicationPolicyExecSubTasks")]
pub mod ListInstanceReplicationPolicyExecSubTasks;
#[cfg(feature = "ListInstanceReplicationPolicyExecTasks")]
pub mod ListInstanceReplicationPolicyExecTasks;
#[cfg(feature = "ListInstanceReplicationPolicyExecutions")]
pub mod ListInstanceReplicationPolicyExecutions;
#[cfg(feature = "ListInstanceRepositories")]
pub mod ListInstanceRepositories;
#[cfg(feature = "ListInstanceResourceInstances")]
pub mod ListInstanceResourceInstances;
#[cfg(feature = "ListInstanceResourceTags")]
pub mod ListInstanceResourceTags;
#[cfg(feature = "ListInstanceRetentionPolicies")]
pub mod ListInstanceRetentionPolicies;
#[cfg(feature = "ListInstanceRetentionPolicyExecSubTasks")]
pub mod ListInstanceRetentionPolicyExecSubTasks;
#[cfg(feature = "ListInstanceRetentionPolicyExecTasks")]
pub mod ListInstanceRetentionPolicyExecTasks;
#[cfg(feature = "ListInstanceRetentionPolicyExecutions")]
pub mod ListInstanceRetentionPolicyExecutions;
#[cfg(feature = "ListInstanceSignatureExecutionSubtasks")]
pub mod ListInstanceSignatureExecutionSubtasks;
#[cfg(feature = "ListInstanceSignPolicies")]
pub mod ListInstanceSignPolicies;
#[cfg(feature = "ListInstanceSignPolicyExecTasks")]
pub mod ListInstanceSignPolicyExecTasks;
#[cfg(feature = "ListInstanceSignPolicyExecutions")]
pub mod ListInstanceSignPolicyExecutions;
#[cfg(feature = "ListInstanceStatistics")]
pub mod ListInstanceStatistics;
#[cfg(feature = "ListInstanceTags")]
pub mod ListInstanceTags;
#[cfg(feature = "ListInstanceWebhookJobs")]
pub mod ListInstanceWebhookJobs;
#[cfg(feature = "ListInstanceWebhooks")]
pub mod ListInstanceWebhooks;
#[cfg(feature = "ListNamespaceRepositories")]
pub mod ListNamespaceRepositories;
#[cfg(feature = "ListNamespaces")]
pub mod ListNamespaces;
#[cfg(feature = "ListNamespaceTags")]
pub mod ListNamespaceTags;
#[cfg(feature = "ListQuotas")]
pub mod ListQuotas;
#[cfg(feature = "ListRepoDomains")]
pub mod ListRepoDomains;
#[cfg(feature = "ListReposDetails")]
pub mod ListReposDetails;
#[cfg(feature = "ListRepositoryTags")]
pub mod ListRepositoryTags;
#[cfg(feature = "ListRetentionHistories")]
pub mod ListRetentionHistories;
#[cfg(feature = "ListRetentions")]
pub mod ListRetentions;
