[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
BatchSwitchMonitor = []
CreateApplication = []
CreateDataSource = []
CreateDataSyncTask = []
CreateDbConnectionPool = []
CreateInstance = []
CreateMonitor = []
CreateNamespace = []
DeleteAppSwitchJopNote = []
DeleteApplications = []
DeleteDataSource = []
DeleteDataSyncTask = []
DeleteGlobalConf = []
DeleteInstance = []
DeleteModule = []
DeleteSecret = []
DeployInstance = []
DownloadEtcdCert = []
EnableActivateModule = []
ListApplications = []
ListBatchSwitchDetail = []
ListInstances = []
ListMonitors = []
ListSwitchJobs = []
ResetDcMonitor = []
SetGlobalConf = []
SetMonitorGlobalConfig = []
SetSecret = []
ShowDataSource = []
ShowDataSources = []
ShowDataSyncTask = []
ShowDataSyncTasks = []
ShowDbConnectionPool = []
ShowDcMonitor = []
ShowGlobalConf = []
ShowInstance = []
ShowModule = []
ShowMonitor = []
ShowMonitorGlobalConfig = []
ShowNameSpaceList = []
ShowNamespacesById = []
ShowOverallMonitors = []
ShowSecret = []
ShowStatisticalData = []
SwitchMonitor = []
SwitchoverDataSyncTask = []
UpdateDataSource = []
UpdateDbConnectionPool = []
UpdateGlobalConf = []
UpdateInstance = []
UpdateModule = []
UpdateMonitor = []
UpdateNameSpace = []
full = ["BatchSwitchMonitor", "CreateApplication", "CreateDataSource", "CreateDataSyncTask", "CreateDbConnectionPool", "CreateInstance", "CreateMonitor", "CreateNamespace", "DeleteApplications", "DeleteAppSwitchJopNote", "DeleteDataSource", "DeleteDataSyncTask", "DeleteGlobalConf", "DeleteInstance", "DeleteModule", "DeleteSecret", "DeployInstance", "DownloadEtcdCert", "EnableActivateModule", "ListApplications", "ListBatchSwitchDetail", "ListInstances", "ListMonitors", "ListSwitchJobs", "ResetDcMonitor", "SetGlobalConf", "SetMonitorGlobalConfig", "SetSecret", "ShowDataSource", "ShowDataSources", "ShowDataSyncTask", "ShowDataSyncTasks", "ShowDbConnectionPool", "ShowDcMonitor", "ShowGlobalConf", "ShowInstance", "ShowModule", "ShowMonitor", "ShowMonitorGlobalConfig", "ShowNameSpaceList", "ShowNamespacesById", "ShowOverallMonitors", "ShowSecret", "ShowStatisticalData", "SwitchMonitor", "SwitchoverDataSyncTask", "UpdateDataSource", "UpdateDbConnectionPool", "UpdateGlobalConf", "UpdateInstance", "UpdateModule", "UpdateMonitor", "UpdateNameSpace"]

[lib]
name = "huawei_cloud_api_definitions_MAS"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-MAS"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "0.1.0"
