#[cfg(feature = "AddDeploymentNodes")]
pub mod AddDeploymentNodes;
#[cfg(feature = "BatchCreateNodeTags")]
pub mod BatchCreateNodeTags;
#[cfg(feature = "CreateConfigMap")]
pub mod CreateConfigMap;
#[cfg(feature = "CreateDeployment")]
pub mod CreateDeployment;
#[cfg(feature = "CreateNode")]
pub mod CreateNode;
#[cfg(feature = "CreateOrderForm")]
pub mod CreateOrderForm;
#[cfg(feature = "CreateResourceTags")]
pub mod CreateResourceTags;
#[cfg(feature = "CreateSecret")]
pub mod CreateSecret;
#[cfg(feature = "CreateTask")]
pub mod CreateTask;
#[cfg(feature = "CreateWorkSpace")]
pub mod CreateWorkSpace;
#[cfg(feature = "DeleteConfigMap")]
pub mod DeleteConfigMap;
#[cfg(feature = "DeleteDeployment")]
pub mod DeleteDeployment;
#[cfg(feature = "DeleteNode")]
pub mod DeleteNode;
#[cfg(feature = "DeletePod")]
pub mod DeletePod;
#[cfg(feature = "DeleteResourceTag")]
pub mod DeleteResourceTag;
#[cfg(feature = "DeleteSecret")]
pub mod DeleteSecret;
#[cfg(feature = "DeleteTask")]
pub mod DeleteTask;
#[cfg(feature = "DeleteWorkSpace")]
pub mod DeleteWorkSpace;
#[cfg(feature = "FreezeNode")]
pub mod FreezeNode;
#[cfg(feature = "ListConfigMaps")]
pub mod ListConfigMaps;
#[cfg(feature = "ListDeviceAlarms")]
pub mod ListDeviceAlarms;
#[cfg(feature = "ListDevices")]
pub mod ListDevices;
#[cfg(feature = "ListFirmwares")]
pub mod ListFirmwares;
#[cfg(feature = "ListPlatformManager")]
pub mod ListPlatformManager;
#[cfg(feature = "ListResourceTags")]
pub mod ListResourceTags;
#[cfg(feature = "ListSecrets")]
pub mod ListSecrets;
#[cfg(feature = "ListTasks")]
pub mod ListTasks;
#[cfg(feature = "ListWorkSpaces")]
pub mod ListWorkSpaces;
#[cfg(feature = "SetDefaultOrderForm")]
pub mod SetDefaultOrderForm;
#[cfg(feature = "ShowConfigMap")]
pub mod ShowConfigMap;
#[cfg(feature = "ShowDeployment")]
pub mod ShowDeployment;
#[cfg(feature = "ShowDeploymentPods")]
pub mod ShowDeploymentPods;
#[cfg(feature = "ShowDeployments")]
pub mod ShowDeployments;
#[cfg(feature = "ShowNode")]
pub mod ShowNode;
#[cfg(feature = "ShowNodeActivationRecords")]
pub mod ShowNodeActivationRecords;
#[cfg(feature = "ShowNodes")]
pub mod ShowNodes;
#[cfg(feature = "ShowResourceTags")]
pub mod ShowResourceTags;
#[cfg(feature = "ShowSecret")]
pub mod ShowSecret;
#[cfg(feature = "ShowSkillInfo")]
pub mod ShowSkillInfo;
#[cfg(feature = "ShowSkillList")]
pub mod ShowSkillList;
#[cfg(feature = "ShowSkillOrderInfo")]
pub mod ShowSkillOrderInfo;
#[cfg(feature = "ShowSkillOrderList")]
pub mod ShowSkillOrderList;
#[cfg(feature = "ShowTask")]
pub mod ShowTask;
#[cfg(feature = "ShowUpgradeProgress")]
pub mod ShowUpgradeProgress;
#[cfg(feature = "ShowWorkSpace")]
pub mod ShowWorkSpace;
#[cfg(feature = "StartAndStopDeployment")]
pub mod StartAndStopDeployment;
#[cfg(feature = "StartAndStopDeploymentPod")]
pub mod StartAndStopDeploymentPod;
#[cfg(feature = "SwitchNodeConnection")]
pub mod SwitchNodeConnection;
#[cfg(feature = "UnfreezeNode")]
pub mod UnfreezeNode;
#[cfg(feature = "UpdateConfigMap")]
pub mod UpdateConfigMap;
#[cfg(feature = "UpdateDeployment")]
pub mod UpdateDeployment;
#[cfg(feature = "UpdateDeploymentUsingPatch")]
pub mod UpdateDeploymentUsingPatch;
#[cfg(feature = "UpdateNode")]
pub mod UpdateNode;
#[cfg(feature = "UpdateNodeCert")]
pub mod UpdateNodeCert;
#[cfg(feature = "UpdateNodeFirmware")]
pub mod UpdateNodeFirmware;
#[cfg(feature = "UpdateSecret")]
pub mod UpdateSecret;
#[cfg(feature = "UpdateTask")]
pub mod UpdateTask;
#[cfg(feature = "UpdateWorkSpace")]
pub mod UpdateWorkSpace;
