#[cfg(feature = "AcceptResourceShareInvitation")]
pub mod AcceptResourceShareInvitation;
#[cfg(feature = "AssociateResourceShare")]
pub mod AssociateResourceShare;
#[cfg(feature = "AssociateResourceSharePermission")]
pub mod AssociateResourceSharePermission;
#[cfg(feature = "BatchCreateResourceShareTags")]
pub mod BatchCreateResourceShareTags;
#[cfg(feature = "BatchDeleteResourceShareTags")]
pub mod BatchDeleteResourceShareTags;
#[cfg(feature = "CreateResourceShare")]
pub mod CreateResourceShare;
#[cfg(feature = "DeleteResourceShare")]
pub mod DeleteResourceShare;
#[cfg(feature = "DisableOrganizationShare")]
pub mod DisableOrganizationShare;
#[cfg(feature = "DisassociateResourceShare")]
pub mod DisassociateResourceShare;
#[cfg(feature = "DisassociateResourceSharePermission")]
pub mod DisassociateResourceSharePermission;
#[cfg(feature = "EnableOrganizationShare")]
pub mod EnableOrganizationShare;
#[cfg(feature = "ListPermissions")]
pub mod ListPermissions;
#[cfg(feature = "ListPermissionVersions")]
pub mod ListPermissionVersions;
#[cfg(feature = "ListQuota")]
pub mod ListQuota;
#[cfg(feature = "ListResourceSharePermissions")]
pub mod ListResourceSharePermissions;
#[cfg(feature = "ListResourceSharesByTags")]
pub mod ListResourceSharesByTags;
#[cfg(feature = "ListResourceShareTags")]
pub mod ListResourceShareTags;
#[cfg(feature = "ListResourceTypes")]
pub mod ListResourceTypes;
#[cfg(feature = "RejectResourceShareInvitation")]
pub mod RejectResourceShareInvitation;
#[cfg(feature = "SearchDistinctPrincipals")]
pub mod SearchDistinctPrincipals;
#[cfg(feature = "SearchDistinctSharedResources")]
pub mod SearchDistinctSharedResources;
#[cfg(feature = "SearchResourceShareAssociations")]
pub mod SearchResourceShareAssociations;
#[cfg(feature = "SearchResourceShareCountByTags")]
pub mod SearchResourceShareCountByTags;
#[cfg(feature = "SearchResourceShareInvitation")]
pub mod SearchResourceShareInvitation;
#[cfg(feature = "SearchResourceShares")]
pub mod SearchResourceShares;
#[cfg(feature = "SearchSharedPrincipals")]
pub mod SearchSharedPrincipals;
#[cfg(feature = "SearchSharedResources")]
pub mod SearchSharedResources;
#[cfg(feature = "ShowOrganizationShare")]
pub mod ShowOrganizationShare;
#[cfg(feature = "ShowPermission")]
pub mod ShowPermission;
#[cfg(feature = "UpdateResourceShare")]
pub mod UpdateResourceShare;
