[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
CollectAllResourcesSummary = []
CountAllResources = []
CreateAggregationAuthorization = []
CreateConfigurationAggregator = []
CreateOrganizationPolicyAssignment = []
CreatePolicyAssignments = []
CreateStoredQuery = []
CreateTrackerConfig = []
DeleteAggregationAuthorization = []
DeleteConfigurationAggregator = []
DeleteOrganizationPolicyAssignment = []
DeletePendingAggregationRequest = []
DeletePolicyAssignment = []
DeleteStoredQuery = []
DeleteTrackerConfig = []
DisablePolicyAssignment = []
EnablePolicyAssignment = []
ListAggregateComplianceByPolicyAssignment = []
ListAggregateDiscoveredResources = []
ListAggregationAuthorizations = []
ListAllResources = []
ListAllTags = []
ListBuiltInPolicyDefinitions = []
ListConfigurationAggregators = []
ListOrganizationPolicyAssignments = []
ListPendingAggregationRequests = []
ListPolicyAssignments = []
ListPolicyStatesByAssignmentId = []
ListPolicyStatesByDomainId = []
ListPolicyStatesByResourceId = []
ListProviders = []
ListRegions = []
ListResources = []
ListSchemas = []
ListStoredQueries = []
RunAggregateResourceQuery = []
RunEvaluationByPolicyAssignmentId = []
RunQuery = []
ShowAggregateComplianceDetailsByPolicyAssignment = []
ShowAggregateDiscoveredResourceCounts = []
ShowAggregatePolicyAssignmentDetail = []
ShowAggregatePolicyStateComplianceSummary = []
ShowAggregateResourceConfig = []
ShowBuiltInPolicyDefinition = []
ShowConfigurationAggregator = []
ShowConfigurationAggregatorSourcesStatus = []
ShowEvaluationStateByAssignmentId = []
ShowOrganizationPolicyAssignment = []
ShowOrganizationPolicyAssignmentDetailedStatus = []
ShowOrganizationPolicyAssignmentStatuses = []
ShowPolicyAssignment = []
ShowResourceById = []
ShowResourceDetail = []
ShowResourceHistory = []
ShowResourceRelations = []
ShowResourceRelationsDetail = []
ShowStoredQuery = []
ShowTrackerConfig = []
UpdateConfigurationAggregator = []
UpdatePolicyAssignment = []
UpdatePolicyState = []
UpdateStoredQuery = []
full = ["CollectAllResourcesSummary", "CountAllResources", "CreateAggregationAuthorization", "CreateConfigurationAggregator", "CreateOrganizationPolicyAssignment", "CreatePolicyAssignments", "CreateStoredQuery", "CreateTrackerConfig", "DeleteAggregationAuthorization", "DeleteConfigurationAggregator", "DeleteOrganizationPolicyAssignment", "DeletePendingAggregationRequest", "DeletePolicyAssignment", "DeleteStoredQuery", "DeleteTrackerConfig", "DisablePolicyAssignment", "EnablePolicyAssignment", "ListAggregateComplianceByPolicyAssignment", "ListAggregateDiscoveredResources", "ListAggregationAuthorizations", "ListAllResources", "ListAllTags", "ListBuiltInPolicyDefinitions", "ListConfigurationAggregators", "ListOrganizationPolicyAssignments", "ListPendingAggregationRequests", "ListPolicyAssignments", "ListPolicyStatesByAssignmentId", "ListPolicyStatesByDomainId", "ListPolicyStatesByResourceId", "ListProviders", "ListRegions", "ListResources", "ListSchemas", "ListStoredQueries", "RunAggregateResourceQuery", "RunEvaluationByPolicyAssignmentId", "RunQuery", "ShowAggregateComplianceDetailsByPolicyAssignment", "ShowAggregateDiscoveredResourceCounts", "ShowAggregatePolicyAssignmentDetail", "ShowAggregatePolicyStateComplianceSummary", "ShowAggregateResourceConfig", "ShowBuiltInPolicyDefinition", "ShowConfigurationAggregator", "ShowConfigurationAggregatorSourcesStatus", "ShowEvaluationStateByAssignmentId", "ShowOrganizationPolicyAssignment", "ShowOrganizationPolicyAssignmentDetailedStatus", "ShowOrganizationPolicyAssignmentStatuses", "ShowPolicyAssignment", "ShowResourceById", "ShowResourceDetail", "ShowResourceHistory", "ShowResourceRelations", "ShowResourceRelationsDetail", "ShowStoredQuery", "ShowTrackerConfig", "UpdateConfigurationAggregator", "UpdatePolicyAssignment", "UpdatePolicyState", "UpdateStoredQuery"]

[lib]
name = "huawei_cloud_api_definitions_RMS"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-RMS"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
