[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddProtectedInstanceNic = []
AddProtectedInstanceTags = []
AttachProtectedInstanceReplication = []
BatchAddTags = []
BatchCreateProtectedInstances = []
BatchDeleteProtectedInstances = []
BatchDeleteTags = []
CreateDisasterRecoveryDrill = []
CreateProtectedInstance = []
CreateProtectionGroup = []
CreateReplication = []
DeleteAllServerGroupFailureJobs = []
DeleteDisasterRecoveryDrill = []
DeleteFailureJob = []
DeleteProtectedInstance = []
DeleteProtectedInstanceNic = []
DeleteProtectedInstanceTag = []
DeleteProtectionGroup = []
DeleteReplication = []
DeleteServerGroupFailureJobs = []
DetachProtectedInstanceReplication = []
ExpandReplication = []
ListActiveActiveDomains = []
ListApiVersions = []
ListDisasterRecoveryDrills = []
ListFailureJobs = []
ListProtectedInstanceTags = []
ListProtectedInstances = []
ListProtectedInstancesByTags = []
ListProtectedInstancesProjectTags = []
ListProtectionGroups = []
ListReplications = []
ListRpoStatistics = []
ResizeProtectedInstance = []
ShowDisasterRecoveryDrill = []
ShowJobStatus = []
ShowProtectedInstance = []
ShowProtectionGroup = []
ShowQuota = []
ShowReplication = []
ShowSpecifiedApiVersion = []
StartFailoverProtectionGroup = []
StartProtectionGroup = []
StartReverseProtectionGroup = []
StopProtectionGroup = []
UpdateDisasterRecoveryDrillName = []
UpdateProtectedInstanceName = []
UpdateProtectionGroupName = []
UpdateReplicationName = []
full = ["AddProtectedInstanceNic", "AddProtectedInstanceTags", "AttachProtectedInstanceReplication", "BatchAddTags", "BatchCreateProtectedInstances", "BatchDeleteProtectedInstances", "BatchDeleteTags", "CreateDisasterRecoveryDrill", "CreateProtectedInstance", "CreateProtectionGroup", "CreateReplication", "DeleteAllServerGroupFailureJobs", "DeleteDisasterRecoveryDrill", "DeleteFailureJob", "DeleteProtectedInstance", "DeleteProtectedInstanceNic", "DeleteProtectedInstanceTag", "DeleteProtectionGroup", "DeleteReplication", "DeleteServerGroupFailureJobs", "DetachProtectedInstanceReplication", "ExpandReplication", "ListActiveActiveDomains", "ListApiVersions", "ListDisasterRecoveryDrills", "ListFailureJobs", "ListProtectedInstances", "ListProtectedInstancesByTags", "ListProtectedInstancesProjectTags", "ListProtectedInstanceTags", "ListProtectionGroups", "ListReplications", "ListRpoStatistics", "ResizeProtectedInstance", "ShowDisasterRecoveryDrill", "ShowJobStatus", "ShowProtectedInstance", "ShowProtectionGroup", "ShowQuota", "ShowReplication", "ShowSpecifiedApiVersion", "StartFailoverProtectionGroup", "StartProtectionGroup", "StartReverseProtectionGroup", "StopProtectionGroup", "UpdateDisasterRecoveryDrillName", "UpdateProtectedInstanceName", "UpdateProtectionGroupName", "UpdateReplicationName"]

[lib]
name = "huawei_cloud_api_definitions_SDRS"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-SDRS"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "0.1.0"
