#[cfg(feature = "AddAppGroupAuthorization")]
pub mod AddAppGroupAuthorization;
#[cfg(feature = "AttachImageServerApp")]
pub mod AttachImageServerApp;
#[cfg(feature = "AuthorizeObs")]
pub mod AuthorizeObs;
#[cfg(feature = "BatchChangeServerImage")]
pub mod BatchChangeServerImage;
#[cfg(feature = "BatchChangeServerMaintainMode")]
pub mod BatchChangeServerMaintainMode;
#[cfg(feature = "BatchCreateServerGroupTags")]
pub mod BatchCreateServerGroupTags;
#[cfg(feature = "BatchDeleteAppGroup")]
pub mod BatchDeleteAppGroup;
#[cfg(feature = "BatchDeleteAppGroupAuthorization")]
pub mod BatchDeleteAppGroupAuthorization;
#[cfg(feature = "BatchDeleteAppSubJobs")]
pub mod BatchDeleteAppSubJobs;
#[cfg(feature = "BatchDeleteCloudStorage")]
pub mod BatchDeleteCloudStorage;
#[cfg(feature = "BatchDeleteImageServer")]
pub mod BatchDeleteImageServer;
#[cfg(feature = "BatchDeleteImageSubJobs")]
pub mod BatchDeleteImageSubJobs;
#[cfg(feature = "BatchDeletePersistentStorage")]
pub mod BatchDeletePersistentStorage;
#[cfg(feature = "BatchDeleteScheduleTask")]
pub mod BatchDeleteScheduleTask;
#[cfg(feature = "BatchDeleteServer")]
pub mod BatchDeleteServer;
#[cfg(feature = "BatchDeleteServerGroupTags")]
pub mod BatchDeleteServerGroupTags;
#[cfg(feature = "BatchDeleteWarehouseApp")]
pub mod BatchDeleteWarehouseApp;
#[cfg(feature = "BatchDisableApp")]
pub mod BatchDisableApp;
#[cfg(feature = "BatchEnableApp")]
pub mod BatchEnableApp;
#[cfg(feature = "BatchMigrateHostsServer")]
pub mod BatchMigrateHostsServer;
#[cfg(feature = "BatchRebootServer")]
pub mod BatchRebootServer;
#[cfg(feature = "BatchReinstallServer")]
pub mod BatchReinstallServer;
#[cfg(feature = "BatchRejoinDomain")]
pub mod BatchRejoinDomain;
#[cfg(feature = "BatchStartServer")]
pub mod BatchStartServer;
#[cfg(feature = "BatchStopServer")]
pub mod BatchStopServer;
#[cfg(feature = "BatchUpdateTsvi")]
pub mod BatchUpdateTsvi;
#[cfg(feature = "BatchUpgradeHdaVersion")]
pub mod BatchUpgradeHdaVersion;
#[cfg(feature = "BindAppWarehouseBucket")]
pub mod BindAppWarehouseBucket;
#[cfg(feature = "ChangeServerImage")]
pub mod ChangeServerImage;
#[cfg(feature = "CheckQuota")]
pub mod CheckQuota;
#[cfg(feature = "CountSubJobs")]
pub mod CountSubJobs;
#[cfg(feature = "CreateAppGroup")]
pub mod CreateAppGroup;
#[cfg(feature = "CreateAppServers")]
pub mod CreateAppServers;
#[cfg(feature = "CreateBucketOrAcl")]
pub mod CreateBucketOrAcl;
#[cfg(feature = "CreateCloudStorage")]
pub mod CreateCloudStorage;
#[cfg(feature = "CreateImageServer")]
pub mod CreateImageServer;
#[cfg(feature = "CreateOrder")]
pub mod CreateOrder;
#[cfg(feature = "CreateOrUpdateScalingPolicy")]
pub mod CreateOrUpdateScalingPolicy;
#[cfg(feature = "CreateOrUpdateStoragePolicyStatement")]
pub mod CreateOrUpdateStoragePolicyStatement;
#[cfg(feature = "CreatePersistentStorage")]
pub mod CreatePersistentStorage;
#[cfg(feature = "CreatePolicyGroup")]
pub mod CreatePolicyGroup;
#[cfg(feature = "CreatePolicyTemplate")]
pub mod CreatePolicyTemplate;
#[cfg(feature = "CreateScheduleTask")]
pub mod CreateScheduleTask;
#[cfg(feature = "CreateServerGroup")]
pub mod CreateServerGroup;
#[cfg(feature = "CreateServerGroupTags")]
pub mod CreateServerGroupTags;
#[cfg(feature = "CreateShareFolder")]
pub mod CreateShareFolder;
#[cfg(feature = "CreateUserFolderAssignment")]
pub mod CreateUserFolderAssignment;
#[cfg(feature = "CreateWarehouseApp")]
pub mod CreateWarehouseApp;
#[cfg(feature = "DeleteAppGroup")]
pub mod DeleteAppGroup;
#[cfg(feature = "DeleteAppIcon")]
pub mod DeleteAppIcon;
#[cfg(feature = "DeleteCloudStorage")]
pub mod DeleteCloudStorage;
#[cfg(feature = "DeleteCloudStorageAttachment")]
pub mod DeleteCloudStorageAttachment;
#[cfg(feature = "DeletePersistentStorage")]
pub mod DeletePersistentStorage;
#[cfg(feature = "DeletePolicyGroup")]
pub mod DeletePolicyGroup;
#[cfg(feature = "DeletePolicyTemplate")]
pub mod DeletePolicyTemplate;
#[cfg(feature = "DeleteScalingPolicy")]
pub mod DeleteScalingPolicy;
#[cfg(feature = "DeleteScheduleTask")]
pub mod DeleteScheduleTask;
#[cfg(feature = "DeleteServer")]
pub mod DeleteServer;
#[cfg(feature = "DeleteServerGroups")]
pub mod DeleteServerGroups;
#[cfg(feature = "DeleteServerGroupTags")]
pub mod DeleteServerGroupTags;
#[cfg(feature = "DeleteStorageClaim")]
pub mod DeleteStorageClaim;
#[cfg(feature = "DeleteUserStorageAttachment")]
pub mod DeleteUserStorageAttachment;
#[cfg(feature = "DeleteWarehouseApp")]
pub mod DeleteWarehouseApp;
#[cfg(feature = "DisassociateAppGroup")]
pub mod DisassociateAppGroup;
#[cfg(feature = "InitializeTenant")]
pub mod InitializeTenant;
#[cfg(feature = "ListAccessAgentLatestVersion")]
pub mod ListAccessAgentLatestVersion;
#[cfg(feature = "ListAppConnection")]
pub mod ListAppConnection;
#[cfg(feature = "ListAppGroup")]
pub mod ListAppGroup;
#[cfg(feature = "ListAppGroupAuthorization")]
pub mod ListAppGroupAuthorization;
#[cfg(feature = "ListAuthorizationMailRecord")]
pub mod ListAuthorizationMailRecord;
#[cfg(feature = "ListAvailabilityZone")]
pub mod ListAvailabilityZone;
#[cfg(feature = "ListAz")]
pub mod ListAz;
#[cfg(feature = "ListCloudStorage")]
pub mod ListCloudStorage;
#[cfg(feature = "ListCloudStorageAssignment")]
pub mod ListCloudStorageAssignment;
#[cfg(feature = "ListCorpConfigInfo")]
pub mod ListCorpConfigInfo;
#[cfg(feature = "ListFutureExecutions")]
pub mod ListFutureExecutions;
#[cfg(feature = "ListImageJobs")]
pub mod ListImageJobs;
#[cfg(feature = "ListImageServers")]
pub mod ListImageServers;
#[cfg(feature = "ListImageSubJobs")]
pub mod ListImageSubJobs;
#[cfg(feature = "ListLatestAttachedServerApp")]
pub mod ListLatestAttachedServerApp;
#[cfg(feature = "ListPersistentStorage")]
pub mod ListPersistentStorage;
#[cfg(feature = "ListPolicyGroup")]
pub mod ListPolicyGroup;
#[cfg(feature = "ListPolicyGroupDetailInfo")]
pub mod ListPolicyGroupDetailInfo;
#[cfg(feature = "ListPolicyOfPolicyGroup")]
pub mod ListPolicyOfPolicyGroup;
#[cfg(feature = "ListPolicyTemplate")]
pub mod ListPolicyTemplate;
#[cfg(feature = "ListProduct")]
pub mod ListProduct;
#[cfg(feature = "ListProjectConfigs")]
pub mod ListProjectConfigs;
#[cfg(feature = "ListPublishedApp")]
pub mod ListPublishedApp;
#[cfg(feature = "ListScheduleTasks")]
pub mod ListScheduleTasks;
#[cfg(feature = "ListServerGroups")]
pub mod ListServerGroups;
#[cfg(feature = "ListServerGroupTag")]
pub mod ListServerGroupTag;
#[cfg(feature = "ListServerHdaDetails")]
pub mod ListServerHdaDetails;
#[cfg(feature = "ListServerHdaUpgradeRecords")]
pub mod ListServerHdaUpgradeRecords;
#[cfg(feature = "ListServerMetricData")]
pub mod ListServerMetricData;
#[cfg(feature = "ListServers")]
pub mod ListServers;
#[cfg(feature = "ListSessionByUserName")]
pub mod ListSessionByUserName;
#[cfg(feature = "ListSessions")]
pub mod ListSessions;
#[cfg(feature = "ListSessionType")]
pub mod ListSessionType;
#[cfg(feature = "ListSfs3Storage")]
pub mod ListSfs3Storage;
#[cfg(feature = "ListShareFolder")]
pub mod ListShareFolder;
