#[cfg(feature = "AddAppGroupAuthorization")]
pub mod AddAppGroupAuthorization;
#[cfg(feature = "BatchDeleteAppGroup")]
pub mod BatchDeleteAppGroup;
#[cfg(feature = "BatchDeleteAppGroupAuthorization")]
pub mod BatchDeleteAppGroupAuthorization;
#[cfg(feature = "BatchDeleteServer")]
pub mod BatchDeleteServer;
#[cfg(feature = "BatchMigrateHostsServer")]
pub mod BatchMigrateHostsServer;
#[cfg(feature = "BatchRebootServer")]
pub mod BatchRebootServer;
#[cfg(feature = "BatchRejoinDomain")]
pub mod BatchRejoinDomain;
#[cfg(feature = "BatchStartServer")]
pub mod BatchStartServer;
#[cfg(feature = "BatchStopServer")]
pub mod BatchStopServer;
#[cfg(feature = "BatchUpdateTsvi")]
pub mod BatchUpdateTsvi;
#[cfg(feature = "ChangeServerImage")]
pub mod ChangeServerImage;
#[cfg(feature = "CheckQuota")]
pub mod CheckQuota;
#[cfg(feature = "CreateAppGroup")]
pub mod CreateAppGroup;
#[cfg(feature = "CreateAppServers")]
pub mod CreateAppServers;
#[cfg(feature = "CreateOrUpdateStoragePolicyStatement")]
pub mod CreateOrUpdateStoragePolicyStatement;
#[cfg(feature = "CreatePersistentStorage")]
pub mod CreatePersistentStorage;
#[cfg(feature = "CreatePolicyGroup")]
pub mod CreatePolicyGroup;
#[cfg(feature = "CreatePolicyTemplate")]
pub mod CreatePolicyTemplate;
#[cfg(feature = "CreateServerGroup")]
pub mod CreateServerGroup;
#[cfg(feature = "CreateShareFolder")]
pub mod CreateShareFolder;
#[cfg(feature = "DeletePersistentStorage")]
pub mod DeletePersistentStorage;
#[cfg(feature = "DeletePolicyGroup")]
pub mod DeletePolicyGroup;
#[cfg(feature = "DeletePolicyTemplate")]
pub mod DeletePolicyTemplate;
#[cfg(feature = "DeleteServerGroups")]
pub mod DeleteServerGroups;
#[cfg(feature = "DeleteStorageClaim")]
pub mod DeleteStorageClaim;
#[cfg(feature = "DeleteUserStorageAttachment")]
pub mod DeleteUserStorageAttachment;
#[cfg(feature = "ListAppConnection")]
pub mod ListAppConnection;
#[cfg(feature = "ListAppGroup")]
pub mod ListAppGroup;
#[cfg(feature = "ListAppGroupAuthorization")]
pub mod ListAppGroupAuthorization;
#[cfg(feature = "ListAvailabilityZone")]
pub mod ListAvailabilityZone;
#[cfg(feature = "ListPersistentStorage")]
pub mod ListPersistentStorage;
#[cfg(feature = "ListPolicyGroup")]
pub mod ListPolicyGroup;
#[cfg(feature = "ListPolicyTemplate")]
pub mod ListPolicyTemplate;
#[cfg(feature = "ListProduct")]
pub mod ListProduct;
#[cfg(feature = "ListPublishedApp")]
pub mod ListPublishedApp;
#[cfg(feature = "ListServerGroups")]
pub mod ListServerGroups;
#[cfg(feature = "ListServers")]
pub mod ListServers;
#[cfg(feature = "ListSessionByUserName")]
pub mod ListSessionByUserName;
#[cfg(feature = "ListSessionType")]
pub mod ListSessionType;
#[cfg(feature = "ListShareFolder")]
pub mod ListShareFolder;
#[cfg(feature = "ListStorageAssignment")]
pub mod ListStorageAssignment;
#[cfg(feature = "ListStoragePolicyStatement")]
pub mod ListStoragePolicyStatement;
#[cfg(feature = "ListTargetsOfPolicyGroup")]
pub mod ListTargetsOfPolicyGroup;
#[cfg(feature = "ListUserConnection")]
pub mod ListUserConnection;
#[cfg(feature = "ListVolumeType")]
pub mod ListVolumeType;
#[cfg(feature = "LogoffUserSession")]
pub mod LogoffUserSession;
#[cfg(feature = "PublishApp")]
pub mod PublishApp;
#[cfg(feature = "ReinstallServer")]
pub mod ReinstallServer;
#[cfg(feature = "ShowJob")]
pub mod ShowJob;
#[cfg(feature = "ShowJobDetail")]
pub mod ShowJobDetail;
#[cfg(feature = "ShowOriginalPolicyInfo")]
pub mod ShowOriginalPolicyInfo;
#[cfg(feature = "ShowPublishableApp")]
pub mod ShowPublishableApp;
#[cfg(feature = "UnpublishApp")]
pub mod UnpublishApp;
#[cfg(feature = "UpdateApp")]
pub mod UpdateApp;
#[cfg(feature = "UpdateAppGroup")]
pub mod UpdateAppGroup;
#[cfg(feature = "UpdatePolicyGroup")]
pub mod UpdatePolicyGroup;
#[cfg(feature = "UpdatePolicyTemplate")]
pub mod UpdatePolicyTemplate;
#[cfg(feature = "UpdateServer")]
pub mod UpdateServer;
#[cfg(feature = "UpdateServerGroup")]
pub mod UpdateServerGroup;
#[cfg(feature = "UpdateShareFolderAssignment")]
pub mod UpdateShareFolderAssignment;
#[cfg(feature = "UpdateUserFolderAssignment")]
pub mod UpdateUserFolderAssignment;
#[cfg(feature = "UploadAppIcon")]
pub mod UploadAppIcon;
