#[cfg(feature = "BatchCreateDataobjectRelations")]
pub mod BatchCreateDataobjectRelations;
#[cfg(feature = "BatchCreateDatapanelObjects")]
pub mod BatchCreateDatapanelObjects;
#[cfg(feature = "BatchSearchMetricHits")]
pub mod BatchSearchMetricHits;
#[cfg(feature = "BatchTagResources")]
pub mod BatchTagResources;
#[cfg(feature = "BatchUntagResources")]
pub mod BatchUntagResources;
#[cfg(feature = "BatchUpdateCatalogue")]
pub mod BatchUpdateCatalogue;
#[cfg(feature = "ChangeAlert")]
pub mod ChangeAlert;
#[cfg(feature = "ChangeAlerts")]
pub mod ChangeAlerts;
#[cfg(feature = "ChangeIncident")]
pub mod ChangeIncident;
#[cfg(feature = "ChangeIncidents")]
pub mod ChangeIncidents;
#[cfg(feature = "ChangePlaybookInstance")]
pub mod ChangePlaybookInstance;
#[cfg(feature = "ChangeResource")]
pub mod ChangeResource;
#[cfg(feature = "CopyMapping")]
pub mod CopyMapping;
#[cfg(feature = "CopyPlaybookVersion")]
pub mod CopyPlaybookVersion;
#[cfg(feature = "CountResourceInstance")]
pub mod CountResourceInstance;
#[cfg(feature = "CreateAdhocQuery")]
pub mod CreateAdhocQuery;
#[cfg(feature = "CreateAlert")]
pub mod CreateAlert;
#[cfg(feature = "CreateAlertRule")]
pub mod CreateAlertRule;
#[cfg(feature = "CreateAlertRuleSimulation")]
pub mod CreateAlertRuleSimulation;
#[cfg(feature = "CreateAnalysisScript")]
pub mod CreateAnalysisScript;
#[cfg(feature = "CreateAopWorkflow")]
pub mod CreateAopWorkflow;
#[cfg(feature = "CreateAopWorkflowVersion")]
pub mod CreateAopWorkflowVersion;
#[cfg(feature = "CreateAopWorkflowVersionApprovel")]
pub mod CreateAopWorkflowVersionApprovel;
#[cfg(feature = "CreateBatchOrderAlerts")]
pub mod CreateBatchOrderAlerts;
#[cfg(feature = "CreateCatalogue")]
pub mod CreateCatalogue;
#[cfg(feature = "CreateClassifier")]
pub mod CreateClassifier;
#[cfg(feature = "CreateCodeSegment")]
pub mod CreateCodeSegment;
#[cfg(feature = "CreateCollectConfig")]
pub mod CreateCollectConfig;
#[cfg(feature = "CreateCollectConfigV2")]
pub mod CreateCollectConfigV2;
#[cfg(feature = "CreateCollectorChannel")]
pub mod CreateCollectorChannel;
#[cfg(feature = "CreateCollectorChannelGroup")]
pub mod CreateCollectorChannelGroup;
#[cfg(feature = "CreateCollectorChannelOperation")]
pub mod CreateCollectorChannelOperation;
#[cfg(feature = "CreateCollectorConnection")]
pub mod CreateCollectorConnection;
#[cfg(feature = "CreateCollectorFiles")]
pub mod CreateCollectorFiles;
#[cfg(feature = "CreateCollectorParser")]
pub mod CreateCollectorParser;
#[cfg(feature = "CreateComponentTemplate")]
pub mod CreateComponentTemplate;
#[cfg(feature = "CreateConfigurationApplication")]
pub mod CreateConfigurationApplication;
#[cfg(feature = "CreateConfigurationDictionaries")]
pub mod CreateConfigurationDictionaries;
#[cfg(feature = "CreateConnection")]
pub mod CreateConnection;
#[cfg(feature = "CreateCustomizedCheckitem")]
pub mod CreateCustomizedCheckitem;
#[cfg(feature = "CreateCustomizedCompliancePackage")]
pub mod CreateCustomizedCompliancePackage;
#[cfg(feature = "CreateDataclassType")]
pub mod CreateDataclassType;
#[cfg(feature = "CreateDataobject")]
pub mod CreateDataobject;
#[cfg(feature = "CreateDataobjectRelation")]
pub mod CreateDataobjectRelation;
#[cfg(feature = "CreateDataspace")]
pub mod CreateDataspace;
#[cfg(feature = "CreateDataTransformation")]
pub mod CreateDataTransformation;
#[cfg(feature = "CreateGenericAction")]
pub mod CreateGenericAction;
#[cfg(feature = "CreateIncident")]
pub mod CreateIncident;
#[cfg(feature = "CreateIndicator")]
pub mod CreateIndicator;
#[cfg(feature = "CreateLayout")]
pub mod CreateLayout;
#[cfg(feature = "CreateLayoutField")]
pub mod CreateLayoutField;
#[cfg(feature = "CreateLayoutWizard")]
pub mod CreateLayoutWizard;
#[cfg(feature = "CreateMapper")]
pub mod CreateMapper;
#[cfg(feature = "CreateMetric")]
pub mod CreateMetric;
#[cfg(feature = "CreateModule")]
pub mod CreateModule;
#[cfg(feature = "CreateNote")]
pub mod CreateNote;
#[cfg(feature = "CreatePipe")]
pub mod CreatePipe;
#[cfg(feature = "CreatePipeConsumption")]
pub mod CreatePipeConsumption;
#[cfg(feature = "CreatePlaybook")]
pub mod CreatePlaybook;
#[cfg(feature = "CreatePlaybookAction")]
pub mod CreatePlaybookAction;
#[cfg(feature = "CreatePlaybookApprove")]
pub mod CreatePlaybookApprove;
#[cfg(feature = "CreatePlaybookRule")]
pub mod CreatePlaybookRule;
#[cfg(feature = "CreatePlaybookVersion")]
pub mod CreatePlaybookVersion;
#[cfg(feature = "CreatePreProcessRules")]
pub mod CreatePreProcessRules;
#[cfg(feature = "CreateReport")]
pub mod CreateReport;
#[cfg(feature = "CreateResourceConfig")]
pub mod CreateResourceConfig;
#[cfg(feature = "CreateRetrieveScript")]
pub mod CreateRetrieveScript;
#[cfg(feature = "CreateRetryPolicy")]
pub mod CreateRetryPolicy;
#[cfg(feature = "CreateSearchAnalysis")]
pub mod CreateSearchAnalysis;
#[cfg(feature = "CreateSearchCondition")]
pub mod CreateSearchCondition;
#[cfg(feature = "CreateServiceAgency")]
pub mod CreateServiceAgency;
#[cfg(feature = "CreateShipper")]
pub mod CreateShipper;
#[cfg(feature = "CreateShipperDelegateAuth")]
pub mod CreateShipperDelegateAuth;
#[cfg(feature = "CreateSqlRender")]
pub mod CreateSqlRender;
#[cfg(feature = "CreateSqlValidation")]
pub mod CreateSqlValidation;
#[cfg(feature = "CreateTable")]
pub mod CreateTable;
#[cfg(feature = "CreateTableAnalysis")]
pub mod CreateTableAnalysis;
#[cfg(feature = "CreateWorkflowInstance")]
pub mod CreateWorkflowInstance;
#[cfg(feature = "CreateWorkspace")]
pub mod CreateWorkspace;
#[cfg(feature = "DeleteAdhocQuery")]
pub mod DeleteAdhocQuery;
#[cfg(feature = "DeleteAlert")]
pub mod DeleteAlert;
#[cfg(feature = "DeleteAlertRule")]
pub mod DeleteAlertRule;
#[cfg(feature = "DeleteAlerts")]
pub mod DeleteAlerts;
#[cfg(feature = "DeleteAnalysisScript")]
pub mod DeleteAnalysisScript;
#[cfg(feature = "DeleteAopWorkflow")]
pub mod DeleteAopWorkflow;
#[cfg(feature = "DeleteAopWorkflowVersion")]
pub mod DeleteAopWorkflowVersion;
#[cfg(feature = "DeleteCatalogue")]
pub mod DeleteCatalogue;
#[cfg(feature = "DeleteCodeSegment")]
pub mod DeleteCodeSegment;
#[cfg(feature = "DeleteCollectorChannel")]
pub mod DeleteCollectorChannel;
#[cfg(feature = "DeleteCollectorChannelGroup")]
pub mod DeleteCollectorChannelGroup;
#[cfg(feature = "DeleteCollectorConnection")]
pub mod DeleteCollectorConnection;
#[cfg(feature = "DeleteCollectorParser")]
pub mod DeleteCollectorParser;
#[cfg(feature = "DeleteComponentTemplate")]
pub mod DeleteComponentTemplate;
#[cfg(feature = "DeleteConfigurationDictionaries")]
pub mod DeleteConfigurationDictionaries;
#[cfg(feature = "DeleteConnection")]
pub mod DeleteConnection;
#[cfg(feature = "DeleteCustomizedCheckitems")]
pub mod DeleteCustomizedCheckitems;
#[cfg(feature = "DeleteCustomizedCompliancePackages")]
pub mod DeleteCustomizedCompliancePackages;
#[cfg(feature = "DeleteDataclassType")]
pub mod DeleteDataclassType;
#[cfg(feature = "DeleteDataobjectRelation")]
pub mod DeleteDataobjectRelation;
#[cfg(feature = "DeleteDataobjects")]
pub mod DeleteDataobjects;
