[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddAgentPath = []
AddMember = []
AddVaultResource = []
AssociateVaultPolicy = []
BatchCreateAndDeleteVaultTags = []
BatchUpdateVault = []
CheckAgent = []
CopyBackup = []
CopyCheckpoint = []
CreateCheckpoint = []
CreatePolicy = []
CreatePostPaidVault = []
CreateVault = []
CreateVaultTags = []
DeleteBackup = []
DeleteMember = []
DeletePolicy = []
DeleteVault = []
DeleteVaultTag = []
DisassociateVaultPolicy = []
ImportBackup = []
ImportCheckpoint = []
ListAgent = []
ListBackups = []
ListDomainProjects = []
ListExternalVault = []
ListOpLogs = []
ListPolicies = []
ListProjects = []
ListProtectable = []
ListVault = []
MigrateDomain = []
MigrateVaultResource = []
RegisterAgent = []
RemoveAgentPath = []
RemoveVaultResource = []
RestoreBackup = []
SetVaultResource = []
ShowAgent = []
ShowBackup = []
ShowCheckpoint = []
ShowDomain = []
ShowMemberDetail = []
ShowMembersDetail = []
ShowMetadata = []
ShowMigrateStatus = []
ShowOpLog = []
ShowPolicy = []
ShowProtectable = []
ShowReplicationCapabilities = []
ShowStorageUsage = []
ShowSummary = []
ShowVault = []
ShowVaultProjectTag = []
ShowVaultResourceInstances = []
ShowVaultTag = []
UnregisterAgent = []
UpdateAgent = []
UpdateBackup = []
UpdateMemberStatus = []
UpdateOrder = []
UpdatePolicy = []
UpdateVault = []
full = ["AddAgentPath", "AddMember", "AddVaultResource", "AssociateVaultPolicy", "BatchCreateAndDeleteVaultTags", "BatchUpdateVault", "CheckAgent", "CopyBackup", "CopyCheckpoint", "CreateCheckpoint", "CreatePolicy", "CreatePostPaidVault", "CreateVault", "CreateVaultTags", "DeleteBackup", "DeleteMember", "DeletePolicy", "DeleteVault", "DeleteVaultTag", "DisassociateVaultPolicy", "ImportBackup", "ImportCheckpoint", "ListAgent", "ListBackups", "ListDomainProjects", "ListExternalVault", "ListOpLogs", "ListPolicies", "ListProjects", "ListProtectable", "ListVault", "MigrateDomain", "MigrateVaultResource", "RegisterAgent", "RemoveAgentPath", "RemoveVaultResource", "RestoreBackup", "SetVaultResource", "ShowAgent", "ShowBackup", "ShowCheckpoint", "ShowDomain", "ShowMemberDetail", "ShowMembersDetail", "ShowMetadata", "ShowMigrateStatus", "ShowOpLog", "ShowPolicy", "ShowProtectable", "ShowReplicationCapabilities", "ShowStorageUsage", "ShowSummary", "ShowVault", "ShowVaultProjectTag", "ShowVaultResourceInstances", "ShowVaultTag", "UnregisterAgent", "UpdateAgent", "UpdateBackup", "UpdateMemberStatus", "UpdateOrder", "UpdatePolicy", "UpdateVault"]

[lib]
name = "huawei_cloud_api_definitions_CBR"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-CBR"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "0.1.1"
