#[cfg(feature = "CreateAccessConfig")]
pub mod CreateAccessConfig;
#[cfg(feature = "CreateAgencyAccess")]
pub mod CreateAgencyAccess;
#[cfg(feature = "CreateAomMappingRules")]
pub mod CreateAomMappingRules;
#[cfg(feature = "CreateDashBoard")]
pub mod CreateDashBoard;
#[cfg(feature = "CreateDashboardGroup")]
pub mod CreateDashboardGroup;
#[cfg(feature = "Createfavorite")]
pub mod Createfavorite;
#[cfg(feature = "CreateHostGroup")]
pub mod CreateHostGroup;
#[cfg(feature = "CreateKeywordsAlarmRule")]
pub mod CreateKeywordsAlarmRule;
#[cfg(feature = "CreateLogGroup")]
pub mod CreateLogGroup;
#[cfg(feature = "CreateLogStream")]
pub mod CreateLogStream;
#[cfg(feature = "CreateLogStreamIndex")]
pub mod CreateLogStreamIndex;
#[cfg(feature = "CreateNotificationTemplate")]
pub mod CreateNotificationTemplate;
#[cfg(feature = "CreateSearchCriterias")]
pub mod CreateSearchCriterias;
#[cfg(feature = "CreateSqlAlarmRule")]
pub mod CreateSqlAlarmRule;
#[cfg(feature = "CreateStructConfig")]
pub mod CreateStructConfig;
#[cfg(feature = "CreateStructTemplate")]
pub mod CreateStructTemplate;
#[cfg(feature = "CreateTags")]
pub mod CreateTags;
#[cfg(feature = "CreateTransfer")]
pub mod CreateTransfer;
#[cfg(feature = "DeleteAccessConfig")]
pub mod DeleteAccessConfig;
#[cfg(feature = "DeleteActiveAlarms")]
pub mod DeleteActiveAlarms;
#[cfg(feature = "DeleteAomMappingRules")]
pub mod DeleteAomMappingRules;
#[cfg(feature = "Deletefavorite")]
pub mod Deletefavorite;
#[cfg(feature = "DeleteHostGroup")]
pub mod DeleteHostGroup;
#[cfg(feature = "DeleteKeywordsAlarmRule")]
pub mod DeleteKeywordsAlarmRule;
#[cfg(feature = "DeleteLogGroup")]
pub mod DeleteLogGroup;
#[cfg(feature = "DeleteLogStream")]
pub mod DeleteLogStream;
#[cfg(feature = "DeleteNotificationTemplate")]
pub mod DeleteNotificationTemplate;
#[cfg(feature = "DeleteSearchCriterias")]
pub mod DeleteSearchCriterias;
#[cfg(feature = "DeleteSqlAlarmRule")]
pub mod DeleteSqlAlarmRule;
#[cfg(feature = "DeleteStructTemplate")]
pub mod DeleteStructTemplate;
#[cfg(feature = "DeleteTransfer")]
pub mod DeleteTransfer;
#[cfg(feature = "DisableLogCollection")]
pub mod DisableLogCollection;
#[cfg(feature = "EnableLogCollection")]
pub mod EnableLogCollection;
#[cfg(feature = "ListAccessConfig")]
pub mod ListAccessConfig;
#[cfg(feature = "ListActiveOrHistoryAlarms")]
pub mod ListActiveOrHistoryAlarms;
#[cfg(feature = "ListBreifStructTemplate")]
pub mod ListBreifStructTemplate;
#[cfg(feature = "ListCharts")]
pub mod ListCharts;
#[cfg(feature = "ListCriterias")]
pub mod ListCriterias;
#[cfg(feature = "ListHistorySql")]
pub mod ListHistorySql;
#[cfg(feature = "ListHost")]
pub mod ListHost;
#[cfg(feature = "ListHostGroup")]
pub mod ListHostGroup;
#[cfg(feature = "ListKeywordsAlarmRules")]
pub mod ListKeywordsAlarmRules;
#[cfg(feature = "ListLogContext")]
pub mod ListLogContext;
#[cfg(feature = "ListLogGroups")]
pub mod ListLogGroups;
#[cfg(feature = "ListLogHistogram")]
pub mod ListLogHistogram;
#[cfg(feature = "ListLogs")]
pub mod ListLogs;
#[cfg(feature = "ListLogStream")]
pub mod ListLogStream;
#[cfg(feature = "ListLogStreamIndex")]
pub mod ListLogStreamIndex;
#[cfg(feature = "ListLogStreams")]
pub mod ListLogStreams;
#[cfg(feature = "ListNotificationTemplate")]
pub mod ListNotificationTemplate;
#[cfg(feature = "ListNotificationTemplates")]
pub mod ListNotificationTemplates;
#[cfg(feature = "ListNotificationTopics")]
pub mod ListNotificationTopics;
#[cfg(feature = "ListQueryAllSearchCriterias")]
pub mod ListQueryAllSearchCriterias;
#[cfg(feature = "ListQueryStructuredLogs")]
pub mod ListQueryStructuredLogs;
#[cfg(feature = "ListSqlAlarmRules")]
pub mod ListSqlAlarmRules;
#[cfg(feature = "ListStructTemplate")]
pub mod ListStructTemplate;
#[cfg(feature = "ListStructuredLogsWithTimeRange")]
pub mod ListStructuredLogsWithTimeRange;
#[cfg(feature = "ListTimeLineTrafficStatistics")]
pub mod ListTimeLineTrafficStatistics;
#[cfg(feature = "ListTopnTrafficStatistics")]
pub mod ListTopnTrafficStatistics;
#[cfg(feature = "ListTransfers")]
pub mod ListTransfers;
#[cfg(feature = "RegisterDmsKafkaInstance")]
pub mod RegisterDmsKafkaInstance;
#[cfg(feature = "ShowAdminConfig")]
pub mod ShowAdminConfig;
#[cfg(feature = "ShowAomMappingRule")]
pub mod ShowAomMappingRule;
#[cfg(feature = "ShowAomMappingRules")]
pub mod ShowAomMappingRules;
#[cfg(feature = "ShowLogConvergeConfig")]
pub mod ShowLogConvergeConfig;
#[cfg(feature = "ShowMemberGroupAndStream")]
pub mod ShowMemberGroupAndStream;
#[cfg(feature = "ShowNotificationTemplate")]
pub mod ShowNotificationTemplate;
#[cfg(feature = "ShowStructTemplate")]
pub mod ShowStructTemplate;
#[cfg(feature = "UpdateAccessConfig")]
pub mod UpdateAccessConfig;
#[cfg(feature = "UpdateAlarmRuleStatus")]
pub mod UpdateAlarmRuleStatus;
#[cfg(feature = "UpdateAomMappingRules")]
pub mod UpdateAomMappingRules;
#[cfg(feature = "UpdateHostGroup")]
pub mod UpdateHostGroup;
#[cfg(feature = "UpdateKeywordsAlarmRule")]
pub mod UpdateKeywordsAlarmRule;
#[cfg(feature = "UpdateLogConvergeConfig")]
pub mod UpdateLogConvergeConfig;
#[cfg(feature = "UpdateLogGroup")]
pub mod UpdateLogGroup;
#[cfg(feature = "UpdateLogStream")]
pub mod UpdateLogStream;
#[cfg(feature = "UpdateNotificationTemplate")]
pub mod UpdateNotificationTemplate;
#[cfg(feature = "UpdateSqlAlarmRule")]
pub mod UpdateSqlAlarmRule;
#[cfg(feature = "UpdateStructConfig")]
pub mod UpdateStructConfig;
#[cfg(feature = "UpdateStructTemplate")]
pub mod UpdateStructTemplate;
#[cfg(feature = "UpdateSwitch")]
pub mod UpdateSwitch;
#[cfg(feature = "UpdateTransfer")]
pub mod UpdateTransfer;
