#[cfg(feature = "AddAppWhitelistPolicyHost")]
pub mod AddAppWhitelistPolicyHost;
#[cfg(feature = "AddAppWhitelistPolicyProcess")]
pub mod AddAppWhitelistPolicyProcess;
#[cfg(feature = "AddBaselineWhiteList")]
pub mod AddBaselineWhiteList;
#[cfg(feature = "AddCceIntegrationProtection")]
pub mod AddCceIntegrationProtection;
#[cfg(feature = "AddCicdConfiguration")]
pub mod AddCicdConfiguration;
#[cfg(feature = "AddHostsGroup")]
pub mod AddHostsGroup;
#[cfg(feature = "AddImageWhiteLists")]
pub mod AddImageWhiteLists;
#[cfg(feature = "AddLoginWhiteList")]
pub mod AddLoginWhiteList;
#[cfg(feature = "AddPolicy")]
pub mod AddPolicy;
#[cfg(feature = "AddPolicyGroup")]
pub mod AddPolicyGroup;
#[cfg(feature = "AddProtectionPolicy")]
pub mod AddProtectionPolicy;
#[cfg(feature = "AddRegistry")]
pub mod AddRegistry;
#[cfg(feature = "AddSystemUserWhiteList")]
pub mod AddSystemUserWhiteList;
#[cfg(feature = "AddVulWhiteList")]
pub mod AddVulWhiteList;
#[cfg(feature = "AssociateHostAssetValue")]
pub mod AssociateHostAssetValue;
#[cfg(feature = "AssociateHostsGroup")]
pub mod AssociateHostsGroup;
#[cfg(feature = "AssociatePolicyGroup")]
pub mod AssociatePolicyGroup;
#[cfg(feature = "AssociateProtectionPolicy")]
pub mod AssociateProtectionPolicy;
#[cfg(feature = "BatchAddAccounts")]
pub mod BatchAddAccounts;
#[cfg(feature = "BatchChangeEvent")]
pub mod BatchChangeEvent;
#[cfg(feature = "BatchCreateTags")]
pub mod BatchCreateTags;
#[cfg(feature = "BatchDeleteAgentDaemonset")]
pub mod BatchDeleteAgentDaemonset;
#[cfg(feature = "BatchDeleteRegistry")]
pub mod BatchDeleteRegistry;
#[cfg(feature = "BatchDeleteTags")]
pub mod BatchDeleteTags;
#[cfg(feature = "BatchExportBaselineTask")]
pub mod BatchExportBaselineTask;
#[cfg(feature = "BatchExportLocalVulTask")]
pub mod BatchExportLocalVulTask;
#[cfg(feature = "BatchScanLocalImage")]
pub mod BatchScanLocalImage;
#[cfg(feature = "BatchScanSwrImage")]
pub mod BatchScanSwrImage;
#[cfg(feature = "BatchStartProtection")]
pub mod BatchStartProtection;
#[cfg(feature = "BatchStartWebTamperProtection")]
pub mod BatchStartWebTamperProtection;
#[cfg(feature = "BatchUpgradeAgentDaemonset")]
pub mod BatchUpgradeAgentDaemonset;
#[cfg(feature = "CancelHostsQuota")]
pub mod CancelHostsQuota;
#[cfg(feature = "ChangeAgentAutoUpgradeStatus")]
pub mod ChangeAgentAutoUpgradeStatus;
#[cfg(feature = "ChangeAntivirusPayPerScanStatus")]
pub mod ChangeAntivirusPayPerScanStatus;
#[cfg(feature = "ChangeAntivirusPolicy")]
pub mod ChangeAntivirusPolicy;
#[cfg(feature = "ChangeAppWhitelistPolicy")]
pub mod ChangeAppWhitelistPolicy;
#[cfg(feature = "ChangeAppWhitelistPolicyProcessStatus")]
pub mod ChangeAppWhitelistPolicyProcessStatus;
#[cfg(feature = "ChangeAutoOpenQuotaStatus")]
pub mod ChangeAutoOpenQuotaStatus;
#[cfg(feature = "ChangeBaselineWhiteList")]
pub mod ChangeBaselineWhiteList;
#[cfg(feature = "ChangeBlockedIp")]
pub mod ChangeBlockedIp;
#[cfg(feature = "ChangeCheckRuleAction")]
pub mod ChangeCheckRuleAction;
#[cfg(feature = "ChangeClusterEvents")]
pub mod ChangeClusterEvents;
#[cfg(feature = "ChangeClusterProtectionPolicy")]
pub mod ChangeClusterProtectionPolicy;
#[cfg(feature = "ChangeContainerStatus")]
pub mod ChangeContainerStatus;
#[cfg(feature = "ChangeEvent")]
pub mod ChangeEvent;
#[cfg(feature = "ChangeExtendedWeakPassword")]
pub mod ChangeExtendedWeakPassword;
#[cfg(feature = "ChangeHostIgnoreStatus")]
pub mod ChangeHostIgnoreStatus;
#[cfg(feature = "ChangeHostsGroup")]
pub mod ChangeHostsGroup;
#[cfg(feature = "ChangeImageWhiteList")]
pub mod ChangeImageWhiteList;
#[cfg(feature = "ChangeIsolatedFile")]
pub mod ChangeIsolatedFile;
#[cfg(feature = "ChangeMalwareCollectStatus")]
pub mod ChangeMalwareCollectStatus;
#[cfg(feature = "ChangeMonthlyOperationReportTipStatus")]
pub mod ChangeMonthlyOperationReportTipStatus;
#[cfg(feature = "ChangePasswordComplexityStatus")]
pub mod ChangePasswordComplexityStatus;
#[cfg(feature = "ChangePolicyGroup")]
pub mod ChangePolicyGroup;
#[cfg(feature = "ChangePolicySwitchStatus")]
pub mod ChangePolicySwitchStatus;
#[cfg(feature = "ChangeSwitchesStatus")]
pub mod ChangeSwitchesStatus;
#[cfg(feature = "ChangeVulScanPolicy")]
pub mod ChangeVulScanPolicy;
#[cfg(feature = "ChangeVulStatus")]
pub mod ChangeVulStatus;
#[cfg(feature = "ChangeVulWhiteList")]
pub mod ChangeVulWhiteList;
#[cfg(feature = "CopyBaselinePolicyGroup")]
pub mod CopyBaselinePolicyGroup;
#[cfg(feature = "CreateAgentDaemonset")]
pub mod CreateAgentDaemonset;
#[cfg(feature = "CreateAntiVirusPaidTask")]
pub mod CreateAntiVirusPaidTask;
#[cfg(feature = "CreateAntiVirusPolicy")]
pub mod CreateAntiVirusPolicy;
#[cfg(feature = "CreateAntiVirusTask")]
pub mod CreateAntiVirusTask;
#[cfg(feature = "CreateAppWhitelistPolicy")]
pub mod CreateAppWhitelistPolicy;
#[cfg(feature = "CreateCicdConfigurationCommand")]
pub mod CreateCicdConfigurationCommand;
#[cfg(feature = "CreateClusterProtectionPolicy")]
pub mod CreateClusterProtectionPolicy;
#[cfg(feature = "CreateClustersInfo")]
pub mod CreateClustersInfo;
#[cfg(feature = "CreateContainerNetworkPolicy")]
pub mod CreateContainerNetworkPolicy;
#[cfg(feature = "CreateDecoyPortPolicy")]
pub mod CreateDecoyPortPolicy;
#[cfg(feature = "CreateGlobalAssetScanTask")]
pub mod CreateGlobalAssetScanTask;
#[cfg(feature = "CreateImageSynchronizeTask")]
pub mod CreateImageSynchronizeTask;
#[cfg(feature = "CreateManualImageScanTask")]
pub mod CreateManualImageScanTask;
#[cfg(feature = "CreateMultiCloudClusters")]
pub mod CreateMultiCloudClusters;
#[cfg(feature = "CreateQuotasOrder")]
pub mod CreateQuotasOrder;
#[cfg(feature = "CreateSecurityGroupPolicy")]
pub mod CreateSecurityGroupPolicy;
#[cfg(feature = "CreateTask")]
pub mod CreateTask;
#[cfg(feature = "CreateVpcEndpoint")]
pub mod CreateVpcEndpoint;
#[cfg(feature = "CreateVulnerabilityScanTask")]
pub mod CreateVulnerabilityScanTask;
#[cfg(feature = "DeleteAccount")]
pub mod DeleteAccount;
#[cfg(feature = "DeleteAgentDaemonset")]
pub mod DeleteAgentDaemonset;
#[cfg(feature = "DeleteAntivirusPolicy")]
pub mod DeleteAntivirusPolicy;
#[cfg(feature = "DeleteAppWhitelistPolicy")]
pub mod DeleteAppWhitelistPolicy;
#[cfg(feature = "DeleteAppWhitelistPolicyHost")]
pub mod DeleteAppWhitelistPolicyHost;
#[cfg(feature = "DeleteBackupHostInfo")]
pub mod DeleteBackupHostInfo;
#[cfg(feature = "DeleteBaselineWhiteList")]
pub mod DeleteBaselineWhiteList;
#[cfg(feature = "DeleteCicdConfigurations")]
pub mod DeleteCicdConfigurations;
#[cfg(feature = "DeleteClusterProtectionPolicy")]
pub mod DeleteClusterProtectionPolicy;
#[cfg(feature = "DeleteContainerNetworkPolicy")]
pub mod DeleteContainerNetworkPolicy;
#[cfg(feature = "DeleteDecoyPortHostPolicy")]
pub mod DeleteDecoyPortHostPolicy;
#[cfg(feature = "DeleteDecoyPortPolicy")]
pub mod DeleteDecoyPortPolicy;
#[cfg(feature = "DeleteDuplicationInfo")]
pub mod DeleteDuplicationInfo;
#[cfg(feature = "DeleteHostsGroup")]
pub mod DeleteHostsGroup;
#[cfg(feature = "DeleteImageWhiteLists")]
pub mod DeleteImageWhiteLists;
#[cfg(feature = "DeleteIsolatedFile")]
pub mod DeleteIsolatedFile;
#[cfg(feature = "DeletePolicy")]
pub mod DeletePolicy;
#[cfg(feature = "DeletePolicyGroup")]
pub mod DeletePolicyGroup;
#[cfg(feature = "DeleteProtectionPolicy")]
pub mod DeleteProtectionPolicy;
#[cfg(feature = "DeleteRegistry")]
pub mod DeleteRegistry;
#[cfg(feature = "DeleteResourceInstanceTag")]
pub mod DeleteResourceInstanceTag;
