#[cfg(feature = "AuthorizePermission")]
pub mod AuthorizePermission;
#[cfg(feature = "BatchDeleteEvolveTask")]
pub mod BatchDeleteEvolveTask;
#[cfg(feature = "CreateAlgorithm")]
pub mod CreateAlgorithm;
#[cfg(feature = "CreateEvolveTask")]
pub mod CreateEvolveTask;
#[cfg(feature = "CreateTask")]
pub mod CreateTask;
#[cfg(feature = "DeleteAlgorithm")]
pub mod DeleteAlgorithm;
#[cfg(feature = "DeleteAlgorithmFile")]
pub mod DeleteAlgorithmFile;
#[cfg(feature = "DeleteEvolveTask")]
pub mod DeleteEvolveTask;
#[cfg(feature = "DeleteTask")]
pub mod DeleteTask;
#[cfg(feature = "ImportAlgorithmFile")]
pub mod ImportAlgorithmFile;
#[cfg(feature = "ListAlgorithms")]
pub mod ListAlgorithms;
#[cfg(feature = "ListBuckets")]
pub mod ListBuckets;
#[cfg(feature = "ListDirectoryByAlgorithmId")]
pub mod ListDirectoryByAlgorithmId;
#[cfg(feature = "ListDirectoryByResultCommitId")]
pub mod ListDirectoryByResultCommitId;
#[cfg(feature = "ListEvolveTaskMetas")]
pub mod ListEvolveTaskMetas;
#[cfg(feature = "ListEvolveTaskStats")]
pub mod ListEvolveTaskStats;
#[cfg(feature = "ListObject")]
pub mod ListObject;
#[cfg(feature = "ListPermission")]
pub mod ListPermission;
#[cfg(feature = "ListTask")]
pub mod ListTask;
#[cfg(feature = "RevokePermission")]
pub mod RevokePermission;
#[cfg(feature = "SaveAlgorithmFile")]
pub mod SaveAlgorithmFile;
#[cfg(feature = "ShowAlgorithm")]
pub mod ShowAlgorithm;
#[cfg(feature = "ShowAlgorithmFile")]
pub mod ShowAlgorithmFile;
#[cfg(feature = "ShowTask")]
pub mod ShowTask;
#[cfg(feature = "ShowTaskDetails")]
pub mod ShowTaskDetails;
#[cfg(feature = "ShowTaskResultCommit")]
pub mod ShowTaskResultCommit;
#[cfg(feature = "ShowTaskResultList")]
pub mod ShowTaskResultList;
#[cfg(feature = "ShowTaskRunningDetails")]
pub mod ShowTaskRunningDetails;
#[cfg(feature = "ShowTaskRunningLog")]
pub mod ShowTaskRunningLog;
#[cfg(feature = "StartEvolveTask")]
pub mod StartEvolveTask;
#[cfg(feature = "StopEvolveTask")]
pub mod StopEvolveTask;
#[cfg(feature = "UpdateAlgorithm")]
pub mod UpdateAlgorithm;
#[cfg(feature = "UpdateEvolveTask")]
pub mod UpdateEvolveTask;
