#[cfg(feature = "AuthorizePermission")]
pub mod AuthorizePermission;
#[cfg(feature = "BatchDeleteEvolveTask")]
pub mod BatchDeleteEvolveTask;
#[cfg(feature = "CancelChat")]
pub mod CancelChat;
#[cfg(feature = "CreateAlgorithm")]
pub mod CreateAlgorithm;
#[cfg(feature = "CreateArtifacts")]
pub mod CreateArtifacts;
#[cfg(feature = "CreateEvolveTask")]
pub mod CreateEvolveTask;
#[cfg(feature = "CreateModelService")]
pub mod CreateModelService;
#[cfg(feature = "CreateModelServiceTask")]
pub mod CreateModelServiceTask;
#[cfg(feature = "CreateTask")]
pub mod CreateTask;
#[cfg(feature = "DeleteAlgorithm")]
pub mod DeleteAlgorithm;
#[cfg(feature = "DeleteAlgorithmFile")]
pub mod DeleteAlgorithmFile;
#[cfg(feature = "DeleteChat")]
pub mod DeleteChat;
#[cfg(feature = "DeleteEvolveTask")]
pub mod DeleteEvolveTask;
#[cfg(feature = "DeleteModelAsset")]
pub mod DeleteModelAsset;
#[cfg(feature = "DeleteModelService")]
pub mod DeleteModelService;
#[cfg(feature = "DeleteTask")]
pub mod DeleteTask;
#[cfg(feature = "DownloadFile")]
pub mod DownloadFile;
#[cfg(feature = "ImportAlgorithmFile")]
pub mod ImportAlgorithmFile;
#[cfg(feature = "ListAlgorithms")]
pub mod ListAlgorithms;
#[cfg(feature = "ListArtifacts")]
pub mod ListArtifacts;
#[cfg(feature = "ListBuckets")]
pub mod ListBuckets;
#[cfg(feature = "ListChat")]
pub mod ListChat;
#[cfg(feature = "ListDirectoryByAlgorithmId")]
pub mod ListDirectoryByAlgorithmId;
#[cfg(feature = "ListDirectoryByResultCommitId")]
pub mod ListDirectoryByResultCommitId;
#[cfg(feature = "ListEvolveTaskMetas")]
pub mod ListEvolveTaskMetas;
#[cfg(feature = "ListEvolveTaskStats")]
pub mod ListEvolveTaskStats;
#[cfg(feature = "ListModelAssets")]
pub mod ListModelAssets;
#[cfg(feature = "ListModelServiceTasks")]
pub mod ListModelServiceTasks;
#[cfg(feature = "ListObject")]
pub mod ListObject;
#[cfg(feature = "ListPermission")]
pub mod ListPermission;
#[cfg(feature = "ListTask")]
pub mod ListTask;
#[cfg(feature = "PublishChat")]
pub mod PublishChat;
#[cfg(feature = "PublishModel")]
pub mod PublishModel;
#[cfg(feature = "RevokePermission")]
pub mod RevokePermission;
#[cfg(feature = "SaveAlgorithmFile")]
pub mod SaveAlgorithmFile;
#[cfg(feature = "ShowAlgorithm")]
pub mod ShowAlgorithm;
#[cfg(feature = "ShowAlgorithmFile")]
pub mod ShowAlgorithmFile;
#[cfg(feature = "ShowChat")]
pub mod ShowChat;
#[cfg(feature = "ShowModelAssetDetail")]
pub mod ShowModelAssetDetail;
#[cfg(feature = "ShowModelServiceDetail")]
pub mod ShowModelServiceDetail;
#[cfg(feature = "ShowModelServiceList")]
pub mod ShowModelServiceList;
#[cfg(feature = "ShowModelServiceTask")]
pub mod ShowModelServiceTask;
#[cfg(feature = "ShowTask")]
pub mod ShowTask;
#[cfg(feature = "ShowTaskDetails")]
pub mod ShowTaskDetails;
#[cfg(feature = "ShowTaskResultCommit")]
pub mod ShowTaskResultCommit;
#[cfg(feature = "ShowTaskResultList")]
pub mod ShowTaskResultList;
#[cfg(feature = "ShowTaskRunningDetails")]
pub mod ShowTaskRunningDetails;
#[cfg(feature = "ShowTaskRunningLog")]
pub mod ShowTaskRunningLog;
#[cfg(feature = "StartEvolveTask")]
pub mod StartEvolveTask;
#[cfg(feature = "StartModelService")]
pub mod StartModelService;
#[cfg(feature = "StopEvolveTask")]
pub mod StopEvolveTask;
#[cfg(feature = "StopModelService")]
pub mod StopModelService;
#[cfg(feature = "UpdateAlgorithm")]
pub mod UpdateAlgorithm;
#[cfg(feature = "UpdateChat")]
pub mod UpdateChat;
#[cfg(feature = "UpdateEvolveTask")]
pub mod UpdateEvolveTask;
#[cfg(feature = "UpdateModelAsset")]
pub mod UpdateModelAsset;
#[cfg(feature = "UpdateModelService")]
pub mod UpdateModelService;
#[cfg(feature = "UploadFile")]
pub mod UploadFile;
#[cfg(feature = "UploadModelServiceTaskFile")]
pub mod UploadModelServiceTaskFile;
