[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
CreateImageSyncRepo = []
CreateManualImageSyncRepo = []
CreateNamespace = []
CreateNamespaceAuth = []
CreateRepo = []
CreateRepoDomains = []
CreateRepoTag = []
CreateRetention = []
CreateSecret = []
CreateTrigger = []
CreateUserRepositoryAuth = []
DeleteImageSyncRepo = []
DeleteNamespaceAuth = []
DeleteNamespaces = []
DeleteRepo = []
DeleteRepoDomains = []
DeleteRepoTag = []
DeleteRetention = []
DeleteTrigger = []
DeleteUserRepositoryAuth = []
ListApiVersions = []
ListImageAutoSyncReposDetails = []
ListNamespaces = []
ListQuotas = []
ListRepoDomains = []
ListReposDetails = []
ListRepositoryTags = []
ListRetentionHistories = []
ListRetentions = []
ListSharedReposDetails = []
ListTriggersDetails = []
ShowAccessDomain = []
ShowApiVersion = []
ShowDomainOverview = []
ShowDomainResourceReports = []
ShowNamespace = []
ShowNamespaceAuth = []
ShowRepository = []
ShowRetention = []
ShowShareFeatureGates = []
ShowSyncJob = []
ShowTrigger = []
ShowUserRepositoryAuth = []
UpdateNamespaceAuth = []
UpdateRepo = []
UpdateRepoDomains = []
UpdateRetention = []
UpdateTrigger = []
UpdateUserRepositoryAuth = []
full = ["CreateImageSyncRepo", "CreateManualImageSyncRepo", "CreateNamespace", "CreateNamespaceAuth", "CreateRepo", "CreateRepoDomains", "CreateRepoTag", "CreateRetention", "CreateSecret", "CreateTrigger", "CreateUserRepositoryAuth", "DeleteImageSyncRepo", "DeleteNamespaceAuth", "DeleteNamespaces", "DeleteRepo", "DeleteRepoDomains", "DeleteRepoTag", "DeleteRetention", "DeleteTrigger", "DeleteUserRepositoryAuth", "ListApiVersions", "ListImageAutoSyncReposDetails", "ListNamespaces", "ListQuotas", "ListRepoDomains", "ListReposDetails", "ListRepositoryTags", "ListRetentionHistories", "ListRetentions", "ListSharedReposDetails", "ListTriggersDetails", "ShowAccessDomain", "ShowApiVersion", "ShowDomainOverview", "ShowDomainResourceReports", "ShowNamespace", "ShowNamespaceAuth", "ShowRepository", "ShowRetention", "ShowShareFeatureGates", "ShowSyncJob", "ShowTrigger", "ShowUserRepositoryAuth", "UpdateNamespaceAuth", "UpdateRepo", "UpdateRepoDomains", "UpdateRetention", "UpdateTrigger", "UpdateUserRepositoryAuth"]

[lib]
name = "huawei_cloud_api_definitions_SWR"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-SWR"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
