[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddDomainName = []
CreateAuthorizationToken = []
CreateImageSyncRepo = []
CreateImmutableRule = []
CreateInstance = []
CreateInstanceEndpointPolicy = []
CreateInstanceInternalEndpoint = []
CreateInstanceLtCredential = []
CreateInstanceNamespace = []
CreateInstanceRegistry = []
CreateInstanceReplicationPolicy = []
CreateInstanceResourceTags = []
CreateInstanceRetentionPolicy = []
CreateInstanceSignPolicy = []
CreateInstanceTempCredential = []
CreateInstanceWebhook = []
CreateManualImageSyncRepo = []
CreateNamespace = []
CreateNamespaceAuth = []
CreateRepo = []
CreateRepoDomains = []
CreateRepoTag = []
CreateRetention = []
CreateSecret = []
CreateSubResourceTags = []
CreateTrigger = []
CreateUserRepositoryAuth = []
DeleteDomainName = []
DeleteImageSyncRepo = []
DeleteImmutableRule = []
DeleteInstance = []
DeleteInstanceArtifact = []
DeleteInstanceInternalEndpoint = []
DeleteInstanceJob = []
DeleteInstanceLtCredential = []
DeleteInstanceNamespace = []
DeleteInstanceRegistry = []
DeleteInstanceReplicationPolicy = []
DeleteInstanceRepository = []
DeleteInstanceResourceTags = []
DeleteInstanceRetentionPolicy = []
DeleteInstanceSignPolicy = []
DeleteInstanceWebhook = []
DeleteNamespaceAuth = []
DeleteNamespaces = []
DeleteRepo = []
DeleteRepoDomains = []
DeleteRepoTag = []
DeleteRetention = []
DeleteSubResourceTags = []
DeleteTrigger = []
DeleteUserRepositoryAuth = []
ExecuteInstanceReplicationPolicy = []
ExecuteInstanceRetentionPolicy = []
ExecuteInstanceSignPolicy = []
ListApiVersions = []
ListAuditLogs = []
ListDomainNames = []
ListFeatureGates = []
ListGlobalFeatureGates = []
ListImageAutoSyncReposDetails = []
ListImmutableRules = []
ListInstance = []
ListInstanceAccessories = []
ListInstanceAllArtifacts = []
ListInstanceArtifacts = []
ListInstanceInternalEndpoints = []
ListInstanceJobs = []
ListInstanceLtCredentials = []
ListInstanceNamespaces = []
ListInstanceProjectTags = []
ListInstanceRegistries = []
ListInstanceReplicationPolicies = []
ListInstanceReplicationPolicyExecSubTasks = []
ListInstanceReplicationPolicyExecTasks = []
ListInstanceReplicationPolicyExecutions = []
ListInstanceRepositories = []
ListInstanceResourceInstances = []
ListInstanceResourceTags = []
ListInstanceRetentionPolicies = []
ListInstanceRetentionPolicyExecSubTasks = []
ListInstanceRetentionPolicyExecTasks = []
ListInstanceRetentionPolicyExecutions = []
ListInstanceSignPolicies = []
ListInstanceSignPolicyExecTasks = []
ListInstanceSignPolicyExecutions = []
ListInstanceSignatureExecutionSubtasks = []
ListInstanceStatistics = []
ListInstanceTags = []
ListInstanceWebhookJobs = []
ListInstanceWebhooks = []
ListNamespaceRepositories = []
ListNamespaceTags = []
ListNamespaces = []
ListQuotas = []
ListRepoDetails = []
ListRepoDomains = []
ListReposDetails = []
ListRepositoryTag = []
ListRepositoryTags = []
full = ["AddDomainName", "CreateAuthorizationToken", "CreateImageSyncRepo", "CreateImmutableRule", "CreateInstance", "CreateInstanceEndpointPolicy", "CreateInstanceInternalEndpoint", "CreateInstanceLtCredential", "CreateInstanceNamespace", "CreateInstanceRegistry", "CreateInstanceReplicationPolicy", "CreateInstanceResourceTags", "CreateInstanceRetentionPolicy", "CreateInstanceSignPolicy", "CreateInstanceTempCredential", "CreateInstanceWebhook", "CreateManualImageSyncRepo", "CreateNamespace", "CreateNamespaceAuth", "CreateRepo", "CreateRepoDomains", "CreateRepoTag", "CreateRetention", "CreateSecret", "CreateSubResourceTags", "CreateTrigger", "CreateUserRepositoryAuth", "DeleteDomainName", "DeleteImageSyncRepo", "DeleteImmutableRule", "DeleteInstance", "DeleteInstanceArtifact", "DeleteInstanceInternalEndpoint", "DeleteInstanceJob", "DeleteInstanceLtCredential", "DeleteInstanceNamespace", "DeleteInstanceRegistry", "DeleteInstanceReplicationPolicy", "DeleteInstanceRepository", "DeleteInstanceResourceTags", "DeleteInstanceRetentionPolicy", "DeleteInstanceSignPolicy", "DeleteInstanceWebhook", "DeleteNamespaceAuth", "DeleteNamespaces", "DeleteRepo", "DeleteRepoDomains", "DeleteRepoTag", "DeleteRetention", "DeleteSubResourceTags", "DeleteTrigger", "DeleteUserRepositoryAuth", "ExecuteInstanceReplicationPolicy", "ExecuteInstanceRetentionPolicy", "ExecuteInstanceSignPolicy", "ListApiVersions", "ListAuditLogs", "ListDomainNames", "ListFeatureGates", "ListGlobalFeatureGates", "ListImageAutoSyncReposDetails", "ListImmutableRules", "ListInstance", "ListInstanceAccessories", "ListInstanceAllArtifacts", "ListInstanceArtifacts", "ListInstanceInternalEndpoints", "ListInstanceJobs", "ListInstanceLtCredentials", "ListInstanceNamespaces", "ListInstanceProjectTags", "ListInstanceRegistries", "ListInstanceReplicationPolicies", "ListInstanceReplicationPolicyExecSubTasks", "ListInstanceReplicationPolicyExecTasks", "ListInstanceReplicationPolicyExecutions", "ListInstanceRepositories", "ListInstanceResourceInstances", "ListInstanceResourceTags", "ListInstanceRetentionPolicies", "ListInstanceRetentionPolicyExecSubTasks", "ListInstanceRetentionPolicyExecTasks", "ListInstanceRetentionPolicyExecutions", "ListInstanceSignatureExecutionSubtasks", "ListInstanceSignPolicies", "ListInstanceSignPolicyExecTasks", "ListInstanceSignPolicyExecutions", "ListInstanceStatistics", "ListInstanceTags", "ListInstanceWebhookJobs", "ListInstanceWebhooks", "ListNamespaceRepositories", "ListNamespaces", "ListNamespaceTags", "ListQuotas", "ListRepoDetails", "ListRepoDomains", "ListReposDetails", "ListRepositoryTag", "ListRepositoryTags"]

[lib]
name = "huawei_cloud_api_definitions_SWR"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-SWR"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
