[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddSubscription = []
AddSubscriptionFromSubscriptionUser = []
BatchCreateOrDeleteResourceTags = []
BatchCreateSubscriptionsFilterPolices = []
BatchDeleteSubscriptionsFilterPolices = []
BatchUpdateSubscriptionsFilterPolices = []
CancelSubscription = []
CreateApplication = []
CreateApplicationEndpoint = []
CreateLogtank = []
CreateMessageTemplate = []
CreateNotifyPolicy = []
CreateResourceTag = []
CreateTopic = []
DeleteApplication = []
DeleteApplicationEndpoint = []
DeleteLogtank = []
DeleteMessageTemplate = []
DeleteNotifyPolicy = []
DeleteResourceTag = []
DeleteTopic = []
DeleteTopicAttributeByName = []
DeleteTopicAttributes = []
ListApplicationAttributes = []
ListApplicationEndpointAttributes = []
ListApplicationEndpoints = []
ListApplications = []
ListLogtank = []
ListMessageTemplateDetails = []
ListMessageTemplates = []
ListProjectTags = []
ListResourceInstances = []
ListResourceTags = []
ListSubscriptions = []
ListSubscriptionsByTopic = []
ListTopicAttributes = []
ListTopicDetails = []
ListTopicMessageStatistics = []
ListTopics = []
ListVersion = []
ListVersions = []
PublishAppMessage = []
PublishHttpDetect = []
PublishMessage = []
ShowHttpDetectResult = []
ShowNotifyPolicy = []
UpdateApplication = []
UpdateApplicationEndpoint = []
UpdateLogtank = []
UpdateMessageTemplate = []
UpdateNotifyPolicy = []
UpdateSubscription = []
UpdateTopic = []
UpdateTopicAttribute = []
full = ["AddSubscription", "AddSubscriptionFromSubscriptionUser", "BatchCreateOrDeleteResourceTags", "BatchCreateSubscriptionsFilterPolices", "BatchDeleteSubscriptionsFilterPolices", "BatchUpdateSubscriptionsFilterPolices", "CancelSubscription", "CreateApplication", "CreateApplicationEndpoint", "CreateLogtank", "CreateMessageTemplate", "CreateNotifyPolicy", "CreateResourceTag", "CreateTopic", "DeleteApplication", "DeleteApplicationEndpoint", "DeleteLogtank", "DeleteMessageTemplate", "DeleteNotifyPolicy", "DeleteResourceTag", "DeleteTopic", "DeleteTopicAttributeByName", "DeleteTopicAttributes", "ListApplicationAttributes", "ListApplicationEndpointAttributes", "ListApplicationEndpoints", "ListApplications", "ListLogtank", "ListMessageTemplateDetails", "ListMessageTemplates", "ListProjectTags", "ListResourceInstances", "ListResourceTags", "ListSubscriptions", "ListSubscriptionsByTopic", "ListTopicAttributes", "ListTopicDetails", "ListTopicMessageStatistics", "ListTopics", "ListVersion", "ListVersions", "PublishAppMessage", "PublishHttpDetect", "PublishMessage", "ShowHttpDetectResult", "ShowNotifyPolicy", "UpdateApplication", "UpdateApplicationEndpoint", "UpdateLogtank", "UpdateMessageTemplate", "UpdateNotifyPolicy", "UpdateSubscription", "UpdateTopic", "UpdateTopicAttribute"]

[lib]
name = "huawei_cloud_api_definitions_SMN"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-SMN"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
