#[cfg(feature = "AddAimMsgSignature")]
pub mod AddAimMsgSignature;
#[cfg(feature = "AddCallBack")]
pub mod AddCallBack;
#[cfg(feature = "AddVmsCallBack")]
pub mod AddVmsCallBack;
#[cfg(feature = "CheckMobileCapability")]
pub mod CheckMobileCapability;
#[cfg(feature = "CreateAimMsgTemplate")]
pub mod CreateAimMsgTemplate;
#[cfg(feature = "CreateAimPersonalTemplate")]
pub mod CreateAimPersonalTemplate;
#[cfg(feature = "CreateAimSendTask")]
pub mod CreateAimSendTask;
#[cfg(feature = "CreatePubInfo")]
pub mod CreatePubInfo;
#[cfg(feature = "CreateResolveTask")]
pub mod CreateResolveTask;
#[cfg(feature = "CreateSmsApp")]
pub mod CreateSmsApp;
#[cfg(feature = "CreateVmsSendTask")]
pub mod CreateVmsSendTask;
#[cfg(feature = "CreateVmsTemplate")]
pub mod CreateVmsTemplate;
#[cfg(feature = "DeleteAimMsgSignature")]
pub mod DeleteAimMsgSignature;
#[cfg(feature = "DeleteAimMsgTemplate")]
pub mod DeleteAimMsgTemplate;
#[cfg(feature = "DeleteAimPersonalTemplate")]
pub mod DeleteAimPersonalTemplate;
#[cfg(feature = "DeletePortInfo")]
pub mod DeletePortInfo;
#[cfg(feature = "DeleteTemplateMaterial")]
pub mod DeleteTemplateMaterial;
#[cfg(feature = "FreezePub")]
pub mod FreezePub;
#[cfg(feature = "ListAimMsgApp")]
pub mod ListAimMsgApp;
#[cfg(feature = "ListAimMsgAppDetail")]
pub mod ListAimMsgAppDetail;
#[cfg(feature = "ListAimMsgSignature")]
pub mod ListAimMsgSignature;
#[cfg(feature = "ListAimMsgSignatureDetail")]
pub mod ListAimMsgSignatureDetail;
#[cfg(feature = "ListAimMsgTemplate")]
pub mod ListAimMsgTemplate;
#[cfg(feature = "ListAimResolveDetails")]
pub mod ListAimResolveDetails;
#[cfg(feature = "ListAimSendDetails")]
pub mod ListAimSendDetails;
#[cfg(feature = "ListAimSendReports")]
pub mod ListAimSendReports;
#[cfg(feature = "ListAimSendTasks")]
pub mod ListAimSendTasks;
#[cfg(feature = "ListAimTemplateMaterials")]
pub mod ListAimTemplateMaterials;
#[cfg(feature = "ListAimTemplateReports")]
pub mod ListAimTemplateReports;
#[cfg(feature = "ListAimTemplates")]
pub mod ListAimTemplates;
#[cfg(feature = "ListMenus")]
pub mod ListMenus;
#[cfg(feature = "ListPortalInfos")]
pub mod ListPortalInfos;
#[cfg(feature = "ListPortInfos")]
pub mod ListPortInfos;
#[cfg(feature = "ListPubInfos")]
pub mod ListPubInfos;
#[cfg(feature = "ListResolveTasks")]
pub mod ListResolveTasks;
#[cfg(feature = "ListVmsCallbacks")]
pub mod ListVmsCallbacks;
#[cfg(feature = "ListVmsSendTasks")]
pub mod ListVmsSendTasks;
#[cfg(feature = "ListVmsTemplateStatus")]
pub mod ListVmsTemplateStatus;
#[cfg(feature = "LockPort")]
pub mod LockPort;
#[cfg(feature = "PushMenuInfo")]
pub mod PushMenuInfo;
#[cfg(feature = "PushPortalInfo")]
pub mod PushPortalInfo;
#[cfg(feature = "RegisterPort")]
pub mod RegisterPort;
#[cfg(feature = "SendAimBatchDifferentMessages")]
pub mod SendAimBatchDifferentMessages;
#[cfg(feature = "SendAimBatchMessages")]
pub mod SendAimBatchMessages;
#[cfg(feature = "SetPrimaryVideoThumbnail")]
pub mod SetPrimaryVideoThumbnail;
#[cfg(feature = "ShowAimMsgSignatureFileInfo")]
pub mod ShowAimMsgSignatureFileInfo;
#[cfg(feature = "ShowAimMsgTemplateDetail")]
pub mod ShowAimMsgTemplateDetail;
#[cfg(feature = "ShowAimMsgTemplateVariable")]
pub mod ShowAimMsgTemplateVariable;
#[cfg(feature = "ShowTemplateVideoThumbnail")]
pub mod ShowTemplateVideoThumbnail;
#[cfg(feature = "UnfreezePub")]
pub mod UnfreezePub;
#[cfg(feature = "UnlockPort")]
pub mod UnlockPort;
#[cfg(feature = "UpdateAimMsgApp")]
pub mod UpdateAimMsgApp;
#[cfg(feature = "UpdateAimMsgSignature")]
pub mod UpdateAimMsgSignature;
#[cfg(feature = "UpdateAimMsgTemplate")]
pub mod UpdateAimMsgTemplate;
#[cfg(feature = "UpdateMenu")]
pub mod UpdateMenu;
#[cfg(feature = "UpdatePersonalTemplateState")]
pub mod UpdatePersonalTemplateState;
#[cfg(feature = "UpdatePortalInfo")]
pub mod UpdatePortalInfo;
#[cfg(feature = "UpdatePubInfo")]
pub mod UpdatePubInfo;
#[cfg(feature = "UploadAimMsgSignatureFile")]
pub mod UploadAimMsgSignatureFile;
#[cfg(feature = "UploadAimTemplateMaterial")]
pub mod UploadAimTemplateMaterial;
#[cfg(feature = "UploadMedia")]
pub mod UploadMedia;
