#[cfg(feature = "AddFacesByBase64")]
pub mod AddFacesByBase64;
#[cfg(feature = "AddFacesByFile")]
pub mod AddFacesByFile;
#[cfg(feature = "AddFacesByUrl")]
pub mod AddFacesByUrl;
#[cfg(feature = "BatchDeleteFaces")]
pub mod BatchDeleteFaces;
#[cfg(feature = "CompareFaceByBase64")]
pub mod CompareFaceByBase64;
#[cfg(feature = "CompareFaceByFile")]
pub mod CompareFaceByFile;
#[cfg(feature = "CompareFaceByUrl")]
pub mod CompareFaceByUrl;
#[cfg(feature = "CreateFaceSet")]
pub mod CreateFaceSet;
#[cfg(feature = "DeleteFaceByExternalImageId")]
pub mod DeleteFaceByExternalImageId;
#[cfg(feature = "DeleteFaceByFaceId")]
pub mod DeleteFaceByFaceId;
#[cfg(feature = "DeleteFaceSet")]
pub mod DeleteFaceSet;
#[cfg(feature = "DetectFaceByBase64")]
pub mod DetectFaceByBase64;
#[cfg(feature = "DetectFaceByFile")]
pub mod DetectFaceByFile;
#[cfg(feature = "DetectFaceByUrl")]
pub mod DetectFaceByUrl;
#[cfg(feature = "DetectLiveByBase64")]
pub mod DetectLiveByBase64;
#[cfg(feature = "DetectLiveByFile")]
pub mod DetectLiveByFile;
#[cfg(feature = "DetectLiveByUrl")]
pub mod DetectLiveByUrl;
#[cfg(feature = "DetectLiveFaceByBase64")]
pub mod DetectLiveFaceByBase64;
#[cfg(feature = "DetectLiveFaceByFile")]
pub mod DetectLiveFaceByFile;
#[cfg(feature = "DetectLiveFaceByUrl")]
pub mod DetectLiveFaceByUrl;
#[cfg(feature = "SearchFaceByBase64")]
pub mod SearchFaceByBase64;
#[cfg(feature = "SearchFaceByFaceId")]
pub mod SearchFaceByFaceId;
#[cfg(feature = "SearchFaceByFile")]
pub mod SearchFaceByFile;
#[cfg(feature = "SearchFaceByUrl")]
pub mod SearchFaceByUrl;
#[cfg(feature = "ShowAllFaceSets")]
pub mod ShowAllFaceSets;
#[cfg(feature = "ShowFacesByFaceId")]
pub mod ShowFacesByFaceId;
#[cfg(feature = "ShowFacesByLimit")]
pub mod ShowFacesByLimit;
#[cfg(feature = "ShowFaceSet")]
pub mod ShowFaceSet;
#[cfg(feature = "UpdateFace")]
pub mod UpdateFace;
