[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
ApplyCertificate = []
BatchPushCertificate = []
CancelCertificateRequest = []
CreateCsr = []
DeleteCertificate = []
DeleteCsr = []
DeployCertificate = []
ExportCertificate = []
ImportCertificate = []
ListCertificates = []
ListCsr = []
ListDeployedResources = []
PushCertificate = []
ShowCertificate = []
ShowCsr = []
ShowCsrPrivateKey = []
SubscribeCertificate = []
UnsubscribeCertificate = []
UpdateCsr = []
UploadCsr = []
full = ["ApplyCertificate", "BatchPushCertificate", "CancelCertificateRequest", "CreateCsr", "DeleteCertificate", "DeleteCsr", "DeployCertificate", "ExportCertificate", "ImportCertificate", "ListCertificates", "ListCsr", "ListDeployedResources", "PushCertificate", "ShowCertificate", "ShowCsr", "ShowCsrPrivateKey", "SubscribeCertificate", "UnsubscribeCertificate", "UpdateCsr", "UploadCsr"]

[lib]
name = "huawei_cloud_api_definitions_SCM"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-SCM"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
