#[cfg(feature = "ActionDeployment")]
pub mod ActionDeployment;
#[cfg(feature = "ActionExternalNetwork")]
pub mod ActionExternalNetwork;
#[cfg(feature = "AddClusterToAvailableZone")]
pub mod AddClusterToAvailableZone;
#[cfg(feature = "AddResource")]
pub mod AddResource;
#[cfg(feature = "AddResourceConfig")]
pub mod AddResourceConfig;
#[cfg(feature = "AddRolesInheritToProjects")]
pub mod AddRolesInheritToProjects;
#[cfg(feature = "AddRolesToDomain")]
pub mod AddRolesToDomain;
#[cfg(feature = "AddRolesToProjects")]
pub mod AddRolesToProjects;
#[cfg(feature = "AddUserToGroup")]
pub mod AddUserToGroup;
#[cfg(feature = "ApplyOpenapiStack")]
pub mod ApplyOpenapiStack;
#[cfg(feature = "BatchCreateTags")]
pub mod BatchCreateTags;
#[cfg(feature = "BatchDeleteApplicationDeployments")]
pub mod BatchDeleteApplicationDeployments;
#[cfg(feature = "BatchDeleteApplicationModules")]
pub mod BatchDeleteApplicationModules;
#[cfg(feature = "BatchDeleteSubscriptions")]
pub mod BatchDeleteSubscriptions;
#[cfg(feature = "BatchResourceEnterpriseActions")]
pub mod BatchResourceEnterpriseActions;
#[cfg(feature = "BindUserRole")]
pub mod BindUserRole;
#[cfg(feature = "ChangeApplicationStatus")]
pub mod ChangeApplicationStatus;
#[cfg(feature = "CheckDomainGroupRole")]
pub mod CheckDomainGroupRole;
#[cfg(feature = "CheckProjectGroupRole")]
pub mod CheckProjectGroupRole;
#[cfg(feature = "CheckUserInGroup")]
pub mod CheckUserInGroup;
#[cfg(feature = "CommitSubscriptions")]
pub mod CommitSubscriptions;
#[cfg(feature = "CopyApplicationDeployment")]
pub mod CopyApplicationDeployment;
#[cfg(feature = "CountTodoTasks")]
pub mod CountTodoTasks;
#[cfg(feature = "CountVDCResources")]
pub mod CountVDCResources;
#[cfg(feature = "CreateAKSK")]
pub mod CreateAKSK;
#[cfg(feature = "CreateApplication")]
pub mod CreateApplication;
#[cfg(feature = "CreateApplicationDeployment")]
pub mod CreateApplicationDeployment;
#[cfg(feature = "CreateApplicationModule")]
pub mod CreateApplicationModule;
#[cfg(feature = "CreateAvailableZones")]
pub mod CreateAvailableZones;
#[cfg(feature = "CreateCatalogs")]
pub mod CreateCatalogs;
#[cfg(feature = "CreateCategory")]
pub mod CreateCategory;
#[cfg(feature = "CreateDomain")]
pub mod CreateDomain;
#[cfg(feature = "CreateDomainOrVDC")]
pub mod CreateDomainOrVDC;
#[cfg(feature = "CreateEndpoint")]
pub mod CreateEndpoint;
#[cfg(feature = "CreateEndpointRegion")]
pub mod CreateEndpointRegion;
#[cfg(feature = "CreateEnterpriseProject")]
pub mod CreateEnterpriseProject;
#[cfg(feature = "CreateEp")]
pub mod CreateEp;
#[cfg(feature = "CreateExternalNetwork")]
pub mod CreateExternalNetwork;
#[cfg(feature = "CreateGroup")]
pub mod CreateGroup;
#[cfg(feature = "CreateIcon")]
pub mod CreateIcon;
#[cfg(feature = "CreateInstanceApplication")]
pub mod CreateInstanceApplication;
#[cfg(feature = "CreateLinks")]
pub mod CreateLinks;
#[cfg(feature = "CreateNetwork")]
pub mod CreateNetwork;
#[cfg(feature = "CreateProduct")]
pub mod CreateProduct;
#[cfg(feature = "CreateProject")]
pub mod CreateProject;
#[cfg(feature = "CreateQOSTemplate")]
pub mod CreateQOSTemplate;
#[cfg(feature = "CreateRegion")]
pub mod CreateRegion;
#[cfg(feature = "CreateResourceRecord")]
pub mod CreateResourceRecord;
#[cfg(feature = "CreateRolePolicy")]
pub mod CreateRolePolicy;
#[cfg(feature = "CreateRoute")]
pub mod CreateRoute;
#[cfg(feature = "CreateSecurityGroup")]
pub mod CreateSecurityGroup;
#[cfg(feature = "CreateSecurityGroupRule")]
pub mod CreateSecurityGroupRule;
#[cfg(feature = "CreateService")]
pub mod CreateService;
#[cfg(feature = "CreateServiceConfig")]
pub mod CreateServiceConfig;
#[cfg(feature = "CreateSubscriptions")]
pub mod CreateSubscriptions;
#[cfg(feature = "CreateSubscriptionsReq")]
pub mod CreateSubscriptionsReq;
#[cfg(feature = "CreateSystemPolicy")]
pub mod CreateSystemPolicy;
#[cfg(feature = "CreateTenantAgency")]
pub mod CreateTenantAgency;
#[cfg(feature = "CreateUriMapping")]
pub mod CreateUriMapping;
#[cfg(feature = "CreateUser")]
pub mod CreateUser;
#[cfg(feature = "CreateVDC")]
pub mod CreateVDC;
#[cfg(feature = "CreateVdcAgency")]
pub mod CreateVdcAgency;
#[cfg(feature = "CreateVdcUser")]
pub mod CreateVdcUser;
#[cfg(feature = "CreateWorkOrder")]
pub mod CreateWorkOrder;
#[cfg(feature = "CreatHtmlTemplate")]
pub mod CreatHtmlTemplate;
#[cfg(feature = "DeleteAgency")]
pub mod DeleteAgency;
#[cfg(feature = "DeleteAKSK")]
pub mod DeleteAKSK;
#[cfg(feature = "DeleteApplication")]
pub mod DeleteApplication;
#[cfg(feature = "DeleteApplicationDeployment")]
pub mod DeleteApplicationDeployment;
#[cfg(feature = "DeleteApplicationInstance")]
pub mod DeleteApplicationInstance;
#[cfg(feature = "DeleteApplicationModule")]
pub mod DeleteApplicationModule;
#[cfg(feature = "DeleteApprovalAttachment")]
pub mod DeleteApprovalAttachment;
#[cfg(feature = "DeleteAvailableZone")]
pub mod DeleteAvailableZone;
#[cfg(feature = "DeleteCatalogs")]
pub mod DeleteCatalogs;
#[cfg(feature = "DeleteCategory")]
pub mod DeleteCategory;
#[cfg(feature = "DeleteEndpoint")]
pub mod DeleteEndpoint;
#[cfg(feature = "DeleteEndpointRegion")]
pub mod DeleteEndpointRegion;
#[cfg(feature = "DeleteEnterpriseProject")]
pub mod DeleteEnterpriseProject;
#[cfg(feature = "DeleteEp")]
pub mod DeleteEp;
#[cfg(feature = "DeleteEpsResourceRules")]
pub mod DeleteEpsResourceRules;
#[cfg(feature = "DeleteExternalNetwork")]
pub mod DeleteExternalNetwork;
#[cfg(feature = "DeleteFCEcsTemplate")]
pub mod DeleteFCEcsTemplate;
#[cfg(feature = "DeleteGroup")]
pub mod DeleteGroup;
#[cfg(feature = "DeleteGroupEps")]
pub mod DeleteGroupEps;
#[cfg(feature = "DeleteHtmlTemplate")]
pub mod DeleteHtmlTemplate;
#[cfg(feature = "DeleteIcon")]
pub mod DeleteIcon;
#[cfg(feature = "DeleteLinks")]
pub mod DeleteLinks;
#[cfg(feature = "DeleteNetwork")]
pub mod DeleteNetwork;
#[cfg(feature = "DeleteOpenapiStack")]
pub mod DeleteOpenapiStack;
#[cfg(feature = "DeleteProduct")]
pub mod DeleteProduct;
#[cfg(feature = "DeleteProject")]
pub mod DeleteProject;
#[cfg(feature = "DeleteQOSTemplate")]
pub mod DeleteQOSTemplate;
#[cfg(feature = "DeleteRegion")]
pub mod DeleteRegion;
#[cfg(feature = "DeleteResourceConfig")]
pub mod DeleteResourceConfig;
#[cfg(feature = "DeleteResourceRecord")]
pub mod DeleteResourceRecord;
#[cfg(feature = "DeleteRolePolicy")]
pub mod DeleteRolePolicy;
#[cfg(feature = "DeleteRolesFromDomain")]
pub mod DeleteRolesFromDomain;
#[cfg(feature = "DeleteRolesFromProjects")]
pub mod DeleteRolesFromProjects;
#[cfg(feature = "DeleteRolesInheritToProjects")]
pub mod DeleteRolesInheritToProjects;
#[cfg(feature = "DeleteRoute")]
pub mod DeleteRoute;
