#[cfg(feature = "BatchDeleteNodes")]
pub mod BatchDeleteNodes;
#[cfg(feature = "BatchModifyReadWriteStrategy")]
pub mod BatchModifyReadWriteStrategy;
#[cfg(feature = "BindEip")]
pub mod BindEip;
#[cfg(feature = "CancelMigration")]
pub mod CancelMigration;
#[cfg(feature = "ChangeDatabaseVersion")]
pub mod ChangeDatabaseVersion;
#[cfg(feature = "ChangeStrategy")]
pub mod ChangeStrategy;
#[cfg(feature = "CheckDataNodeConnection")]
pub mod CheckDataNodeConnection;
#[cfg(feature = "CheckMigrateLogicDb")]
pub mod CheckMigrateLogicDb;
#[cfg(feature = "CheckPreliminaryResults")]
pub mod CheckPreliminaryResults;
#[cfg(feature = "CleanMigration")]
pub mod CleanMigration;
#[cfg(feature = "CompareParameterGroups")]
pub mod CompareParameterGroups;
#[cfg(feature = "CopyConfiguration")]
pub mod CopyConfiguration;
#[cfg(feature = "CreateDatabase")]
pub mod CreateDatabase;
#[cfg(feature = "CreateDdmConfigurations")]
pub mod CreateDdmConfigurations;
#[cfg(feature = "CreateDdmDatabase")]
pub mod CreateDdmDatabase;
#[cfg(feature = "CreateDdmInstance")]
pub mod CreateDdmInstance;
#[cfg(feature = "CreateGroup")]
pub mod CreateGroup;
#[cfg(feature = "CreateInstance")]
pub mod CreateInstance;
#[cfg(feature = "CreateUsers")]
pub mod CreateUsers;
#[cfg(feature = "DeleteBackup")]
pub mod DeleteBackup;
#[cfg(feature = "DeleteConfiguration")]
pub mod DeleteConfiguration;
#[cfg(feature = "DeleteDatabase")]
pub mod DeleteDatabase;
#[cfg(feature = "DeleteDdmDatabase")]
pub mod DeleteDdmDatabase;
#[cfg(feature = "DeleteDdmInstance")]
pub mod DeleteDdmInstance;
#[cfg(feature = "DeleteGroup")]
pub mod DeleteGroup;
#[cfg(feature = "DeleteInstance")]
pub mod DeleteInstance;
#[cfg(feature = "DeleteNodes")]
pub mod DeleteNodes;
#[cfg(feature = "DeleteUser")]
pub mod DeleteUser;
#[cfg(feature = "DownloadSchemaMetadata")]
pub mod DownloadSchemaMetadata;
#[cfg(feature = "ExecuteKillLogicalProcesses")]
pub mod ExecuteKillLogicalProcesses;
#[cfg(feature = "ExecuteKillPhysicalProcesses")]
pub mod ExecuteKillPhysicalProcesses;
#[cfg(feature = "ExpandDdmInstanceNodes")]
pub mod ExpandDdmInstanceNodes;
#[cfg(feature = "ExpandInstanceNodes")]
pub mod ExpandInstanceNodes;
#[cfg(feature = "ListApiVersion")]
pub mod ListApiVersion;
#[cfg(feature = "ListAvailableRds")]
pub mod ListAvailableRds;
#[cfg(feature = "ListAvailableRdsForMigrate")]
pub mod ListAvailableRdsForMigrate;
#[cfg(feature = "ListAvailableRdsList")]
pub mod ListAvailableRdsList;
#[cfg(feature = "ListBackups")]
pub mod ListBackups;
#[cfg(feature = "ListConfigurationApplyHistories")]
pub mod ListConfigurationApplyHistories;
#[cfg(feature = "ListDatabaseAvailableVersions")]
pub mod ListDatabaseAvailableVersions;
#[cfg(feature = "ListDatabases")]
pub mod ListDatabases;
#[cfg(feature = "ListDdmConfigurations")]
pub mod ListDdmConfigurations;
#[cfg(feature = "ListDdmEngines")]
pub mod ListDdmEngines;
#[cfg(feature = "ListDdmFlavors")]
pub mod ListDdmFlavors;
#[cfg(feature = "ListDdms")]
pub mod ListDdms;
#[cfg(feature = "ListEngines")]
pub mod ListEngines;
#[cfg(feature = "ListFlavors")]
pub mod ListFlavors;
#[cfg(feature = "ListGroup")]
pub mod ListGroup;
#[cfg(feature = "ListInstances")]
pub mod ListInstances;
#[cfg(feature = "ListInstancesConfigurations")]
pub mod ListInstancesConfigurations;
#[cfg(feature = "ListNodes")]
pub mod ListNodes;
#[cfg(feature = "ListReadWriteRatio")]
pub mod ListReadWriteRatio;
#[cfg(feature = "ListSlowLog")]
pub mod ListSlowLog;
#[cfg(feature = "ListSlowLogAnalysis")]
pub mod ListSlowLogAnalysis;
#[cfg(feature = "ListSlowLogs")]
pub mod ListSlowLogs;
#[cfg(feature = "ListSqlBlack")]
pub mod ListSqlBlack;
#[cfg(feature = "ListTasks")]
pub mod ListTasks;
#[cfg(feature = "ListUsers")]
pub mod ListUsers;
#[cfg(feature = "MigrateLogicDb")]
pub mod MigrateLogicDb;
#[cfg(feature = "MigrateResults")]
pub mod MigrateResults;
#[cfg(feature = "ModifyConfiguration")]
pub mod ModifyConfiguration;
#[cfg(feature = "ModifyEip")]
pub mod ModifyEip;
#[cfg(feature = "ModifySqlBlackList")]
pub mod ModifySqlBlackList;
#[cfg(feature = "RebuildConfig")]
pub mod RebuildConfig;
#[cfg(feature = "ResetAdministrator")]
pub mod ResetAdministrator;
#[cfg(feature = "ResetParameterGroup")]
pub mod ResetParameterGroup;
#[cfg(feature = "ResetUserPassword")]
pub mod ResetUserPassword;
#[cfg(feature = "ResizeFlavor")]
pub mod ResizeFlavor;
#[cfg(feature = "RestartDdmInstance")]
pub mod RestartDdmInstance;
#[cfg(feature = "RestartInstance")]
pub mod RestartInstance;
#[cfg(feature = "RestartNode")]
pub mod RestartNode;
#[cfg(feature = "Restore2Exist")]
pub mod Restore2Exist;
#[cfg(feature = "RestoreMetadata")]
pub mod RestoreMetadata;
#[cfg(feature = "RetryMigration")]
pub mod RetryMigration;
#[cfg(feature = "RollBackDatabaseVersion")]
pub mod RollBackDatabaseVersion;
#[cfg(feature = "RollbackMigration")]
pub mod RollbackMigration;
#[cfg(feature = "ShowAvalibleDdms")]
pub mod ShowAvalibleDdms;
#[cfg(feature = "ShowAvalibleRds")]
pub mod ShowAvalibleRds;
#[cfg(feature = "ShowAvalibleTime")]
pub mod ShowAvalibleTime;
#[cfg(feature = "ShowBackup")]
pub mod ShowBackup;
#[cfg(feature = "ShowConfiguration")]
pub mod ShowConfiguration;
#[cfg(feature = "ShowDatabase")]
pub mod ShowDatabase;
#[cfg(feature = "ShowDdmDetail")]
pub mod ShowDdmDetail;
#[cfg(feature = "ShowDdmJobResult")]
pub mod ShowDdmJobResult;
#[cfg(feature = "ShowDdmNodeDetail")]
pub mod ShowDdmNodeDetail;
#[cfg(feature = "ShowInstance")]
pub mod ShowInstance;
#[cfg(feature = "ShowInstanceDatabase")]
pub mod ShowInstanceDatabase;
#[cfg(feature = "ShowInstanceParam")]
pub mod ShowInstanceParam;
#[cfg(feature = "ShowIpGroup")]
pub mod ShowIpGroup;
#[cfg(feature = "ShowLogicalProcesses")]
pub mod ShowLogicalProcesses;
#[cfg(feature = "ShowMigrationLog")]
pub mod ShowMigrationLog;
#[cfg(feature = "ShowNode")]
pub mod ShowNode;
#[cfg(feature = "ShowPhysicalProcesses")]
pub mod ShowPhysicalProcesses;
#[cfg(feature = "ShowProcessesAuditLog")]
pub mod ShowProcessesAuditLog;
#[cfg(feature = "ShowPublicIp")]
pub mod ShowPublicIp;
#[cfg(feature = "ShowRelatedDns")]
pub mod ShowRelatedDns;
#[cfg(feature = "ShowRiskInfo")]
pub mod ShowRiskInfo;
#[cfg(feature = "ShrinkInstanceNodes")]
pub mod ShrinkInstanceNodes;
#[cfg(feature = "SwitchIpGroup")]
pub mod SwitchIpGroup;
#[cfg(feature = "SwitchRoute")]
pub mod SwitchRoute;
