#[cfg(feature = "BatchCreateInstanceTag")]
pub mod BatchCreateInstanceTag;
#[cfg(feature = "ChangeInstanceNetwork")]
pub mod ChangeInstanceNetwork;
#[cfg(feature = "ChangeInstanceOrder")]
pub mod ChangeInstanceOrder;
#[cfg(feature = "ChangeInstanceType")]
pub mod ChangeInstanceType;
#[cfg(feature = "CountInstancesByTag")]
pub mod CountInstancesByTag;
#[cfg(feature = "CreateCbh")]
pub mod CreateCbh;
#[cfg(feature = "CreateInstance")]
pub mod CreateInstance;
#[cfg(feature = "CreateInstanceOrder")]
pub mod CreateInstanceOrder;
#[cfg(feature = "DeleteInstance")]
pub mod DeleteInstance;
#[cfg(feature = "InstallCbhEip")]
pub mod InstallCbhEip;
#[cfg(feature = "InstallInstanceEip")]
pub mod InstallInstanceEip;
#[cfg(feature = "ListAvailableZones")]
pub mod ListAvailableZones;
#[cfg(feature = "ListCbhInstance")]
pub mod ListCbhInstance;
#[cfg(feature = "ListInstances")]
pub mod ListInstances;
#[cfg(feature = "ListInstancesByTag")]
pub mod ListInstancesByTag;
#[cfg(feature = "ListQuotaStatus")]
pub mod ListQuotaStatus;
#[cfg(feature = "ListSpecifications")]
pub mod ListSpecifications;
#[cfg(feature = "ListTags")]
pub mod ListTags;
#[cfg(feature = "LoginCbh")]
pub mod LoginCbh;
#[cfg(feature = "LoginInstance")]
pub mod LoginInstance;
#[cfg(feature = "LoginInstanceAdmin")]
pub mod LoginInstanceAdmin;
#[cfg(feature = "RebootInstance")]
pub mod RebootInstance;
#[cfg(feature = "RegisterAuthorization")]
pub mod RegisterAuthorization;
#[cfg(feature = "ResetInstanceLoginMethod")]
pub mod ResetInstanceLoginMethod;
#[cfg(feature = "ResetInstancePassword")]
pub mod ResetInstancePassword;
#[cfg(feature = "ResetLoginMethod")]
pub mod ResetLoginMethod;
#[cfg(feature = "ResetPassword")]
pub mod ResetPassword;
#[cfg(feature = "ResizeInstance")]
pub mod ResizeInstance;
#[cfg(feature = "RestartCbhInstance")]
pub mod RestartCbhInstance;
#[cfg(feature = "RollbackInstance")]
pub mod RollbackInstance;
#[cfg(feature = "SearchQuota")]
pub mod SearchQuota;
#[cfg(feature = "ShowAuthorization")]
pub mod ShowAuthorization;
#[cfg(feature = "ShowAvailableZoneInfo")]
pub mod ShowAvailableZoneInfo;
#[cfg(feature = "ShowEcsQuota")]
pub mod ShowEcsQuota;
#[cfg(feature = "ShowInstanceStatus")]
pub mod ShowInstanceStatus;
#[cfg(feature = "ShowInstanceTags")]
pub mod ShowInstanceTags;
#[cfg(feature = "ShowNetworkConfiguration")]
pub mod ShowNetworkConfiguration;
#[cfg(feature = "ShowOmUrl")]
pub mod ShowOmUrl;
#[cfg(feature = "ShowQuota")]
pub mod ShowQuota;
#[cfg(feature = "StartCbhInstance")]
pub mod StartCbhInstance;
#[cfg(feature = "StartInstance")]
pub mod StartInstance;
#[cfg(feature = "StopCbhInstance")]
pub mod StopCbhInstance;
#[cfg(feature = "StopInstance")]
pub mod StopInstance;
#[cfg(feature = "SwitchInstanceVpc")]
pub mod SwitchInstanceVpc;
#[cfg(feature = "UninstallCbhEip")]
pub mod UninstallCbhEip;
#[cfg(feature = "UninstallInstanceEip")]
pub mod UninstallInstanceEip;
#[cfg(feature = "UpdateInstanceSecurityGroup")]
pub mod UpdateInstanceSecurityGroup;
#[cfg(feature = "UpgradeCbhInstance")]
pub mod UpgradeCbhInstance;
#[cfg(feature = "UpgradeInstance")]
pub mod UpgradeInstance;
