#[cfg(feature = "AttachEip")]
pub mod AttachEip;
#[cfg(feature = "AttachEip2")]
pub mod AttachEip2;
#[cfg(feature = "ChangeSecurityGroup")]
pub mod ChangeSecurityGroup;
#[cfg(feature = "ClearGraph")]
pub mod ClearGraph;
#[cfg(feature = "ClearGraph2")]
pub mod ClearGraph2;
#[cfg(feature = "CreateBackup")]
pub mod CreateBackup;
#[cfg(feature = "CreateBackup2")]
pub mod CreateBackup2;
#[cfg(feature = "CreateGraph")]
pub mod CreateGraph;
#[cfg(feature = "CreateGraph2")]
pub mod CreateGraph2;
#[cfg(feature = "CreateMetadata")]
pub mod CreateMetadata;
#[cfg(feature = "CreateMetadata2")]
pub mod CreateMetadata2;
#[cfg(feature = "DeleteBackup")]
pub mod DeleteBackup;
#[cfg(feature = "DeleteBackup2")]
pub mod DeleteBackup2;
#[cfg(feature = "DeleteGraph")]
pub mod DeleteGraph;
#[cfg(feature = "DeleteGraph2")]
pub mod DeleteGraph2;
#[cfg(feature = "DeleteMetadata")]
pub mod DeleteMetadata;
#[cfg(feature = "DeleteMetadata2")]
pub mod DeleteMetadata2;
#[cfg(feature = "DeregisterScenes2")]
pub mod DeregisterScenes2;
#[cfg(feature = "DetachEip")]
pub mod DetachEip;
#[cfg(feature = "DetachEip2")]
pub mod DetachEip2;
#[cfg(feature = "ExpandGraph")]
pub mod ExpandGraph;
#[cfg(feature = "ExpandGraph2")]
pub mod ExpandGraph2;
#[cfg(feature = "ExportBackup2")]
pub mod ExportBackup2;
#[cfg(feature = "ExportGraph")]
pub mod ExportGraph;
#[cfg(feature = "ExportGraph2")]
pub mod ExportGraph2;
#[cfg(feature = "ImportBackup2")]
pub mod ImportBackup2;
#[cfg(feature = "ImportGraph")]
pub mod ImportGraph;
#[cfg(feature = "ImportGraph2")]
pub mod ImportGraph2;
#[cfg(feature = "ListBackups")]
pub mod ListBackups;
#[cfg(feature = "ListBackups2")]
pub mod ListBackups2;
#[cfg(feature = "ListGraphBackups")]
pub mod ListGraphBackups;
#[cfg(feature = "ListGraphBackups2")]
pub mod ListGraphBackups2;
#[cfg(feature = "ListGraphMetadatas")]
pub mod ListGraphMetadatas;
#[cfg(feature = "ListGraphs")]
pub mod ListGraphs;
#[cfg(feature = "ListGraphs2")]
pub mod ListGraphs2;
#[cfg(feature = "ListJobs")]
pub mod ListJobs;
#[cfg(feature = "ListJobs2")]
pub mod ListJobs2;
#[cfg(feature = "ListMetadatas")]
pub mod ListMetadatas;
#[cfg(feature = "ListMetadatas2")]
pub mod ListMetadatas2;
#[cfg(feature = "ListQuotas")]
pub mod ListQuotas;
#[cfg(feature = "ListQuotas2")]
pub mod ListQuotas2;
#[cfg(feature = "ListScenes2")]
pub mod ListScenes2;
#[cfg(feature = "RegisterScenes2")]
pub mod RegisterScenes2;
#[cfg(feature = "ResizeGraph")]
pub mod ResizeGraph;
#[cfg(feature = "ResizeGraph2")]
pub mod ResizeGraph2;
#[cfg(feature = "RestartGraph")]
pub mod RestartGraph;
#[cfg(feature = "RestartGraph2")]
pub mod RestartGraph2;
#[cfg(feature = "ShowBackupDownloadLink")]
pub mod ShowBackupDownloadLink;
#[cfg(feature = "ShowGraph")]
pub mod ShowGraph;
#[cfg(feature = "ShowGraph2")]
pub mod ShowGraph2;
#[cfg(feature = "ShowJob")]
pub mod ShowJob;
#[cfg(feature = "ShowJob2")]
pub mod ShowJob2;
#[cfg(feature = "ShowMetadata2")]
pub mod ShowMetadata2;
#[cfg(feature = "StartGraph")]
pub mod StartGraph;
#[cfg(feature = "StartGraph2")]
pub mod StartGraph2;
#[cfg(feature = "StopGraph")]
pub mod StopGraph;
#[cfg(feature = "StopGraph2")]
pub mod StopGraph2;
#[cfg(feature = "UpgradeGraph")]
pub mod UpgradeGraph;
#[cfg(feature = "UpgradeGraph2")]
pub mod UpgradeGraph2;
#[cfg(feature = "UploadFromObs")]
pub mod UploadFromObs;
#[cfg(feature = "UploadFromObs2")]
pub mod UploadFromObs2;
