#[cfg(feature = "AddQueueUserList")]
pub mod AddQueueUserList;
#[cfg(feature = "AddWorkloadPlanStage")]
pub mod AddWorkloadPlanStage;
#[cfg(feature = "AddWorkloadQueue")]
pub mod AddWorkloadQueue;
#[cfg(feature = "AddWorkloadRule")]
pub mod AddWorkloadRule;
#[cfg(feature = "AssociateEip")]
pub mod AssociateEip;
#[cfg(feature = "AssociateElb")]
pub mod AssociateElb;
#[cfg(feature = "BatchCreateClusterCn")]
pub mod BatchCreateClusterCn;
#[cfg(feature = "BatchCreateResourceTag")]
pub mod BatchCreateResourceTag;
#[cfg(feature = "BatchDeleteClusterCn")]
pub mod BatchDeleteClusterCn;
#[cfg(feature = "BatchDeleteResourceTag")]
pub mod BatchDeleteResourceTag;
#[cfg(feature = "CancelReadonlyCluster")]
pub mod CancelReadonlyCluster;
#[cfg(feature = "ChangeSecurityGroup")]
pub mod ChangeSecurityGroup;
#[cfg(feature = "CheckCluster")]
pub mod CheckCluster;
#[cfg(feature = "CheckClusterShrink")]
pub mod CheckClusterShrink;
#[cfg(feature = "CheckDisasterName")]
pub mod CheckDisasterName;
#[cfg(feature = "CheckGrowCluster")]
pub mod CheckGrowCluster;
#[cfg(feature = "CheckTableRestore")]
pub mod CheckTableRestore;
#[cfg(feature = "ConvertToLogicalCluster")]
pub mod ConvertToLogicalCluster;
#[cfg(feature = "CopySnapshot")]
pub mod CopySnapshot;
#[cfg(feature = "CreateAlarmSub")]
pub mod CreateAlarmSub;
#[cfg(feature = "CreateCluster")]
pub mod CreateCluster;
#[cfg(feature = "CreateClusterDns")]
pub mod CreateClusterDns;
#[cfg(feature = "CreateClusterV2")]
pub mod CreateClusterV2;
#[cfg(feature = "CreateClusterWorkload")]
pub mod CreateClusterWorkload;
#[cfg(feature = "CreateDatabaseUser")]
pub mod CreateDatabaseUser;
#[cfg(feature = "CreateDataSource")]
pub mod CreateDataSource;
#[cfg(feature = "CreateDisasterRecovery")]
pub mod CreateDisasterRecovery;
#[cfg(feature = "CreateEventSub")]
pub mod CreateEventSub;
#[cfg(feature = "CreateLogicalCluster")]
pub mod CreateLogicalCluster;
#[cfg(feature = "CreateLogicalClusterPlan")]
pub mod CreateLogicalClusterPlan;
#[cfg(feature = "CreateSnapshot")]
pub mod CreateSnapshot;
#[cfg(feature = "CreateSnapshotPolicy")]
pub mod CreateSnapshotPolicy;
#[cfg(feature = "CreateWorkloadPlan")]
pub mod CreateWorkloadPlan;
#[cfg(feature = "DeleteAlarmSub")]
pub mod DeleteAlarmSub;
#[cfg(feature = "DeleteCluster")]
pub mod DeleteCluster;
#[cfg(feature = "DeleteClusterDns")]
pub mod DeleteClusterDns;
#[cfg(feature = "DeleteClusterNodes")]
pub mod DeleteClusterNodes;
#[cfg(feature = "DeleteDatabaseUser")]
pub mod DeleteDatabaseUser;
#[cfg(feature = "DeleteDataSource")]
pub mod DeleteDataSource;
#[cfg(feature = "DeleteDisasterRecovery")]
pub mod DeleteDisasterRecovery;
#[cfg(feature = "DeleteDwsCluster")]
pub mod DeleteDwsCluster;
#[cfg(feature = "DeleteEventSub")]
pub mod DeleteEventSub;
#[cfg(feature = "DeleteLogicalCluster")]
pub mod DeleteLogicalCluster;
#[cfg(feature = "DeleteLogicalClusterPlan")]
pub mod DeleteLogicalClusterPlan;
#[cfg(feature = "DeleteQueueUserList")]
pub mod DeleteQueueUserList;
#[cfg(feature = "DeleteSnapshot")]
pub mod DeleteSnapshot;
#[cfg(feature = "DeleteSnapshotPolicy")]
pub mod DeleteSnapshotPolicy;
#[cfg(feature = "DeleteWorkloadPlan")]
pub mod DeleteWorkloadPlan;
#[cfg(feature = "DeleteWorkloadPlanStage")]
pub mod DeleteWorkloadPlanStage;
#[cfg(feature = "DeleteWorkloadQueue")]
pub mod DeleteWorkloadQueue;
#[cfg(feature = "DeleteWorkloadRule")]
pub mod DeleteWorkloadRule;
#[cfg(feature = "DisableLogicalClusterPlan")]
pub mod DisableLogicalClusterPlan;
#[cfg(feature = "DisableLtsLogs")]
pub mod DisableLtsLogs;
#[cfg(feature = "DisassociateEip")]
pub mod DisassociateEip;
#[cfg(feature = "DisassociateElb")]
pub mod DisassociateElb;
#[cfg(feature = "EnableLogicalCluster")]
pub mod EnableLogicalCluster;
#[cfg(feature = "EnableLogicalClusterPlan")]
pub mod EnableLogicalClusterPlan;
#[cfg(feature = "EnableLtsLogs")]
pub mod EnableLtsLogs;
#[cfg(feature = "EncryptCluster")]
pub mod EncryptCluster;
#[cfg(feature = "ExecuteClusterUpgradeAction")]
pub mod ExecuteClusterUpgradeAction;
#[cfg(feature = "ExecuteDatabaseOmUserAction")]
pub mod ExecuteDatabaseOmUserAction;
#[cfg(feature = "ExecuteFlavorChange")]
pub mod ExecuteFlavorChange;
#[cfg(feature = "ExecuteRedistributionCluster")]
pub mod ExecuteRedistributionCluster;
#[cfg(feature = "ExpandInstanceStorage")]
pub mod ExpandInstanceStorage;
#[cfg(feature = "ExportDatabaseUsers")]
pub mod ExportDatabaseUsers;
#[cfg(feature = "ExportUserAuthority")]
pub mod ExportUserAuthority;
#[cfg(feature = "ListAlarmConfigs")]
pub mod ListAlarmConfigs;
#[cfg(feature = "ListAlarmDetail")]
pub mod ListAlarmDetail;
#[cfg(feature = "ListAlarmStatistic")]
pub mod ListAlarmStatistic;
#[cfg(feature = "ListAlarmSubs")]
pub mod ListAlarmSubs;
#[cfg(feature = "ListAuditLog")]
pub mod ListAuditLog;
#[cfg(feature = "ListAvailabilityZones")]
pub mod ListAvailabilityZones;
#[cfg(feature = "ListAvailableDisasterClusters")]
pub mod ListAvailableDisasterClusters;
#[cfg(feature = "ListClusterActions")]
pub mod ListClusterActions;
#[cfg(feature = "ListClusterCn")]
pub mod ListClusterCn;
#[cfg(feature = "ListClusterConfigurations")]
pub mod ListClusterConfigurations;
#[cfg(feature = "ListClusterConfigurationsParameter")]
pub mod ListClusterConfigurationsParameter;
#[cfg(feature = "ListClusterDetails")]
pub mod ListClusterDetails;
#[cfg(feature = "ListClusterEndpoints")]
pub mod ListClusterEndpoints;
#[cfg(feature = "ListClusterNodes")]
pub mod ListClusterNodes;
#[cfg(feature = "ListClusters")]
pub mod ListClusters;
#[cfg(feature = "ListClusterScaleInNumbers")]
pub mod ListClusterScaleInNumbers;
#[cfg(feature = "ListClusterSnapshots")]
pub mod ListClusterSnapshots;
#[cfg(feature = "ListClusterTags")]
pub mod ListClusterTags;
#[cfg(feature = "ListClusterWorkload")]
pub mod ListClusterWorkload;
#[cfg(feature = "ListConfigurationsAuditRecords")]
pub mod ListConfigurationsAuditRecords;
#[cfg(feature = "ListDatabaseObjects")]
pub mod ListDatabaseObjects;
#[cfg(feature = "ListDatabaseUserAuthorities")]
pub mod ListDatabaseUserAuthorities;
#[cfg(feature = "ListDatabaseUsers")]
pub mod ListDatabaseUsers;
#[cfg(feature = "ListDataSource")]
pub mod ListDataSource;
#[cfg(feature = "ListDisasterRecover")]
pub mod ListDisasterRecover;
#[cfg(feature = "ListDssPools")]
pub mod ListDssPools;
#[cfg(feature = "ListElbs")]
pub mod ListElbs;
#[cfg(feature = "ListEvents")]
pub mod ListEvents;
#[cfg(feature = "ListEventSpecs")]
pub mod ListEventSpecs;
#[cfg(feature = "ListEventSubs")]
pub mod ListEventSubs;
#[cfg(feature = "ListHostDisk")]
pub mod ListHostDisk;
#[cfg(feature = "ListHostNet")]
pub mod ListHostNet;
#[cfg(feature = "ListHostOverview")]
pub mod ListHostOverview;
#[cfg(feature = "ListJobDetails")]
pub mod ListJobDetails;
