#[cfg(feature = "AddVpnUsersToGroup")]
pub mod AddVpnUsersToGroup;
#[cfg(feature = "BatchCreateResourceTags")]
pub mod BatchCreateResourceTags;
#[cfg(feature = "BatchCreateVpnUsers")]
pub mod BatchCreateVpnUsers;
#[cfg(feature = "BatchDeleteResourceTags")]
pub mod BatchDeleteResourceTags;
#[cfg(feature = "BatchDeleteVpnUsers")]
pub mod BatchDeleteVpnUsers;
#[cfg(feature = "CheckClientCaCertificate")]
pub mod CheckClientCaCertificate;
#[cfg(feature = "CountResourcesByTags")]
pub mod CountResourcesByTags;
#[cfg(feature = "CreateCgw")]
pub mod CreateCgw;
#[cfg(feature = "CreateConnectionMonitor")]
pub mod CreateConnectionMonitor;
#[cfg(feature = "CreateVgw")]
pub mod CreateVgw;
#[cfg(feature = "CreateVgwCertificate")]
pub mod CreateVgwCertificate;
#[cfg(feature = "CreateVpnAccessPolicy")]
pub mod CreateVpnAccessPolicy;
#[cfg(feature = "CreateVpnConnection")]
pub mod CreateVpnConnection;
#[cfg(feature = "CreateVpnServer")]
pub mod CreateVpnServer;
#[cfg(feature = "CreateVpnUser")]
pub mod CreateVpnUser;
#[cfg(feature = "CreateVpnUserGroup")]
pub mod CreateVpnUserGroup;
#[cfg(feature = "DeleteCgw")]
pub mod DeleteCgw;
#[cfg(feature = "DeleteClientCa")]
pub mod DeleteClientCa;
#[cfg(feature = "DeleteConnectionMonitor")]
pub mod DeleteConnectionMonitor;
#[cfg(feature = "DeleteP2cVgwConnection")]
pub mod DeleteP2cVgwConnection;
#[cfg(feature = "DeleteVgw")]
pub mod DeleteVgw;
#[cfg(feature = "DeleteVpnAccessPolicy")]
pub mod DeleteVpnAccessPolicy;
#[cfg(feature = "DeleteVpnConnection")]
pub mod DeleteVpnConnection;
#[cfg(feature = "DeleteVpnConnectionsLogConfig")]
pub mod DeleteVpnConnectionsLogConfig;
#[cfg(feature = "DeleteVpnUser")]
pub mod DeleteVpnUser;
#[cfg(feature = "DeleteVpnUserGroup")]
pub mod DeleteVpnUserGroup;
#[cfg(feature = "ExportClientConfig")]
pub mod ExportClientConfig;
#[cfg(feature = "ImportClientCa")]
pub mod ImportClientCa;
#[cfg(feature = "ListAvailabilityZones")]
pub mod ListAvailabilityZones;
#[cfg(feature = "ListCgws")]
pub mod ListCgws;
#[cfg(feature = "ListConnectionMonitors")]
pub mod ListConnectionMonitors;
#[cfg(feature = "ListExtendedAvailabilityZones")]
pub mod ListExtendedAvailabilityZones;
#[cfg(feature = "ListP2cVgwAvailabilityZones")]
pub mod ListP2cVgwAvailabilityZones;
#[cfg(feature = "ListP2cVgwConnections")]
pub mod ListP2cVgwConnections;
#[cfg(feature = "ListP2cVgws")]
pub mod ListP2cVgws;
#[cfg(feature = "ListProjectTags")]
pub mod ListProjectTags;
#[cfg(feature = "ListResourcesByTags")]
pub mod ListResourcesByTags;
#[cfg(feature = "ListVgws")]
pub mod ListVgws;
#[cfg(feature = "ListVpnAccessPolicies")]
pub mod ListVpnAccessPolicies;
#[cfg(feature = "ListVpnConnections")]
pub mod ListVpnConnections;
#[cfg(feature = "ListVpnServersByProject")]
pub mod ListVpnServersByProject;
#[cfg(feature = "ListVpnServersByVgw")]
pub mod ListVpnServersByVgw;
#[cfg(feature = "ListVpnUserGroups")]
pub mod ListVpnUserGroups;
#[cfg(feature = "ListVpnUsers")]
pub mod ListVpnUsers;
#[cfg(feature = "ListVpnUsersInGroup")]
pub mod ListVpnUsersInGroup;
#[cfg(feature = "RemoveVpnUsersFromGroup")]
pub mod RemoveVpnUsersFromGroup;
#[cfg(feature = "ResetVpnUserPassword")]
pub mod ResetVpnUserPassword;
#[cfg(feature = "ShowCgw")]
pub mod ShowCgw;
#[cfg(feature = "ShowClientCa")]
pub mod ShowClientCa;
#[cfg(feature = "ShowConnectionMonitor")]
pub mod ShowConnectionMonitor;
#[cfg(feature = "ShowP2cVgw")]
pub mod ShowP2cVgw;
#[cfg(feature = "ShowQuotasInfo")]
pub mod ShowQuotasInfo;
#[cfg(feature = "ShowResourceTags")]
pub mod ShowResourceTags;
#[cfg(feature = "ShowVgw")]
pub mod ShowVgw;
#[cfg(feature = "ShowVpnAccessPolicy")]
pub mod ShowVpnAccessPolicy;
#[cfg(feature = "ShowVpnConnection")]
pub mod ShowVpnConnection;
#[cfg(feature = "ShowVpnConnectionLog")]
pub mod ShowVpnConnectionLog;
#[cfg(feature = "ShowVpnConnectionsLogConfig")]
pub mod ShowVpnConnectionsLogConfig;
#[cfg(feature = "ShowVpnGatewayCertificate")]
pub mod ShowVpnGatewayCertificate;
#[cfg(feature = "ShowVpnGatewayRoutingTable")]
pub mod ShowVpnGatewayRoutingTable;
#[cfg(feature = "ShowVpnUser")]
pub mod ShowVpnUser;
#[cfg(feature = "ShowVpnUserGroup")]
pub mod ShowVpnUserGroup;
#[cfg(feature = "UpdateCgw")]
pub mod UpdateCgw;
#[cfg(feature = "UpdateClientCa")]
pub mod UpdateClientCa;
#[cfg(feature = "UpdateP2cVgw")]
pub mod UpdateP2cVgw;
#[cfg(feature = "UpdatePostpaidVgwSpecification")]
pub mod UpdatePostpaidVgwSpecification;
#[cfg(feature = "UpdateVgw")]
pub mod UpdateVgw;
#[cfg(feature = "UpdateVgwCertificate")]
pub mod UpdateVgwCertificate;
#[cfg(feature = "UpdateVpnAccessPolicy")]
pub mod UpdateVpnAccessPolicy;
#[cfg(feature = "UpdateVpnConnection")]
pub mod UpdateVpnConnection;
#[cfg(feature = "UpdateVpnConnectionsLogConfig")]
pub mod UpdateVpnConnectionsLogConfig;
#[cfg(feature = "UpdateVpnServer")]
pub mod UpdateVpnServer;
#[cfg(feature = "UpdateVpnUser")]
pub mod UpdateVpnUser;
#[cfg(feature = "UpdateVpnUserGroup")]
pub mod UpdateVpnUserGroup;
#[cfg(feature = "UpdateVpnUserPassword")]
pub mod UpdateVpnUserPassword;
