#[cfg(feature = "CreateCgw")]
pub mod CreateCgw;
#[cfg(feature = "CreateConnectionMonitor")]
pub mod CreateConnectionMonitor;
#[cfg(feature = "CreateVgw")]
pub mod CreateVgw;
#[cfg(feature = "CreateVgwCertificate")]
pub mod CreateVgwCertificate;
#[cfg(feature = "CreateVpnConnection")]
pub mod CreateVpnConnection;
#[cfg(feature = "DeleteCgw")]
pub mod DeleteCgw;
#[cfg(feature = "DeleteConnectionMonitor")]
pub mod DeleteConnectionMonitor;
#[cfg(feature = "DeleteVgw")]
pub mod DeleteVgw;
#[cfg(feature = "DeleteVpnConnection")]
pub mod DeleteVpnConnection;
#[cfg(feature = "ListAvailabilityZones")]
pub mod ListAvailabilityZones;
#[cfg(feature = "ListCgws")]
pub mod ListCgws;
#[cfg(feature = "ListConnectionMonitors")]
pub mod ListConnectionMonitors;
#[cfg(feature = "ListVgws")]
pub mod ListVgws;
#[cfg(feature = "ListVpnConnections")]
pub mod ListVpnConnections;
#[cfg(feature = "ShowCgw")]
pub mod ShowCgw;
#[cfg(feature = "ShowConnectionMonitor")]
pub mod ShowConnectionMonitor;
#[cfg(feature = "ShowQuotasInfo")]
pub mod ShowQuotasInfo;
#[cfg(feature = "ShowVgw")]
pub mod ShowVgw;
#[cfg(feature = "ShowVpnConnection")]
pub mod ShowVpnConnection;
#[cfg(feature = "ShowVpnGatewayCertificate")]
pub mod ShowVpnGatewayCertificate;
#[cfg(feature = "UpdateCgw")]
pub mod UpdateCgw;
#[cfg(feature = "UpdateVgw")]
pub mod UpdateVgw;
#[cfg(feature = "UpdateVgwCertificate")]
pub mod UpdateVgwCertificate;
#[cfg(feature = "UpdateVpnConnection")]
pub mod UpdateVpnConnection;
