#[cfg(feature = "AddGeipSegmentTags")]
pub mod AddGeipSegmentTags;
#[cfg(feature = "AddGlobalEipTags")]
pub mod AddGlobalEipTags;
#[cfg(feature = "AddInternetBandwidthTags")]
pub mod AddInternetBandwidthTags;
#[cfg(feature = "AssociateGeipSegmentInstance")]
pub mod AssociateGeipSegmentInstance;
#[cfg(feature = "AssociateInstance")]
pub mod AssociateInstance;
#[cfg(feature = "AttachInternetBandwidth")]
pub mod AttachInternetBandwidth;
#[cfg(feature = "BatchAttachGeipSegmentInternetBandwidth")]
pub mod BatchAttachGeipSegmentInternetBandwidth;
#[cfg(feature = "BatchAttachInternetBandwidth")]
pub mod BatchAttachInternetBandwidth;
#[cfg(feature = "BatchCreateGeipSegmentTags")]
pub mod BatchCreateGeipSegmentTags;
#[cfg(feature = "BatchCreateGlobalEip")]
pub mod BatchCreateGlobalEip;
#[cfg(feature = "BatchCreateGlobalEipTags")]
pub mod BatchCreateGlobalEipTags;
#[cfg(feature = "BatchCreateInternetBandwidth")]
pub mod BatchCreateInternetBandwidth;
#[cfg(feature = "BatchCreateInternetBandwidthTags")]
pub mod BatchCreateInternetBandwidthTags;
#[cfg(feature = "BatchDeleteGeipSegmentTags")]
pub mod BatchDeleteGeipSegmentTags;
#[cfg(feature = "BatchDeleteGlobalEipTags")]
pub mod BatchDeleteGlobalEipTags;
#[cfg(feature = "BatchDeleteInternetBandwidthTags")]
pub mod BatchDeleteInternetBandwidthTags;
#[cfg(feature = "BatchDetachGeipSegmentInternetBandwidth")]
pub mod BatchDetachGeipSegmentInternetBandwidth;
#[cfg(feature = "BatchDetachInternetBandwidth")]
pub mod BatchDetachInternetBandwidth;
#[cfg(feature = "CountGlobalEips")]
pub mod CountGlobalEips;
#[cfg(feature = "CountGlobalEipSegment")]
pub mod CountGlobalEipSegment;
#[cfg(feature = "CountInternetBandwidth")]
pub mod CountInternetBandwidth;
#[cfg(feature = "CreateGlobalEip")]
pub mod CreateGlobalEip;
#[cfg(feature = "CreateGlobalEipSegment")]
pub mod CreateGlobalEipSegment;
#[cfg(feature = "CreateInternetBandwidth")]
pub mod CreateInternetBandwidth;
#[cfg(feature = "CreateUserDisclaimer")]
pub mod CreateUserDisclaimer;
#[cfg(feature = "DeleteGeipSegmentTag")]
pub mod DeleteGeipSegmentTag;
#[cfg(feature = "DeleteGlobalEip")]
pub mod DeleteGlobalEip;
#[cfg(feature = "DeleteGlobalEipSegment")]
pub mod DeleteGlobalEipSegment;
#[cfg(feature = "DeleteGlobalEipTag")]
pub mod DeleteGlobalEipTag;
#[cfg(feature = "DeleteInternetBandwidth")]
pub mod DeleteInternetBandwidth;
#[cfg(feature = "DeleteInternetBandwidthTag")]
pub mod DeleteInternetBandwidthTag;
#[cfg(feature = "DeleteUserDisclaimer")]
pub mod DeleteUserDisclaimer;
#[cfg(feature = "DetachInternetBandwidth")]
pub mod DetachInternetBandwidth;
#[cfg(feature = "DisassociateGeipSegmentInstance")]
pub mod DisassociateGeipSegmentInstance;
#[cfg(feature = "DisassociateInstance")]
pub mod DisassociateInstance;
#[cfg(feature = "ListAccessSites")]
pub mod ListAccessSites;
#[cfg(feature = "ListGeipPools")]
pub mod ListGeipPools;
#[cfg(feature = "ListGeipResourceQuotas")]
pub mod ListGeipResourceQuotas;
#[cfg(feature = "ListGeipSegmentCountFilterTags")]
pub mod ListGeipSegmentCountFilterTags;
#[cfg(feature = "ListGeipSegmentDomainTags")]
pub mod ListGeipSegmentDomainTags;
#[cfg(feature = "ListGeipSegmentFilterTags")]
pub mod ListGeipSegmentFilterTags;
#[cfg(feature = "ListGlobalEipCountFilterTags")]
pub mod ListGlobalEipCountFilterTags;
#[cfg(feature = "ListGlobalEipDomainTags")]
pub mod ListGlobalEipDomainTags;
#[cfg(feature = "ListGlobalEipFilterTags")]
pub mod ListGlobalEipFilterTags;
#[cfg(feature = "ListGlobalEips")]
pub mod ListGlobalEips;
#[cfg(feature = "ListGlobalEipSegments")]
pub mod ListGlobalEipSegments;
#[cfg(feature = "ListInternetBandwidthCountFilterTags")]
pub mod ListInternetBandwidthCountFilterTags;
#[cfg(feature = "ListInternetBandwidthDomainTags")]
pub mod ListInternetBandwidthDomainTags;
#[cfg(feature = "ListInternetBandwidthFilterTags")]
pub mod ListInternetBandwidthFilterTags;
#[cfg(feature = "ListInternetBandwidthLimits")]
pub mod ListInternetBandwidthLimits;
#[cfg(feature = "ListInternetBandwidths")]
pub mod ListInternetBandwidths;
#[cfg(feature = "ListJobs")]
pub mod ListJobs;
#[cfg(feature = "ListSupportMasks")]
pub mod ListSupportMasks;
#[cfg(feature = "ListSupportRegions")]
pub mod ListSupportRegions;
#[cfg(feature = "ListTenantGeipSupportInstances")]
pub mod ListTenantGeipSupportInstances;
#[cfg(feature = "ShowGeipSegmentTags")]
pub mod ShowGeipSegmentTags;
#[cfg(feature = "ShowGlobalEip")]
pub mod ShowGlobalEip;
#[cfg(feature = "ShowGlobalEipSegment")]
pub mod ShowGlobalEipSegment;
#[cfg(feature = "ShowGlobalEipTags")]
pub mod ShowGlobalEipTags;
#[cfg(feature = "ShowInternetBandwidth")]
pub mod ShowInternetBandwidth;
#[cfg(feature = "ShowInternetBandwidthTags")]
pub mod ShowInternetBandwidthTags;
#[cfg(feature = "ShowJobs")]
pub mod ShowJobs;
#[cfg(feature = "ShowUserDisclaimer")]
pub mod ShowUserDisclaimer;
#[cfg(feature = "UpdateGlobalEip")]
pub mod UpdateGlobalEip;
#[cfg(feature = "UpdateGlobalEipSegment")]
pub mod UpdateGlobalEipSegment;
#[cfg(feature = "UpdateInternetBandwidth")]
pub mod UpdateInternetBandwidth;
