#[cfg(feature = "AssociateEndpointIpaddress")]
pub mod AssociateEndpointIpaddress;
#[cfg(feature = "AssociateResolverQueryLogConfig")]
pub mod AssociateResolverQueryLogConfig;
#[cfg(feature = "AssociateResolverRuleRouter")]
pub mod AssociateResolverRuleRouter;
#[cfg(feature = "AssociateRouter")]
pub mod AssociateRouter;
#[cfg(feature = "BatchCreateCombinedPublicRecordsetsTask")]
pub mod BatchCreateCombinedPublicRecordsetsTask;
#[cfg(feature = "BatchCreatePublicRecordsetsTask")]
pub mod BatchCreatePublicRecordsetsTask;
#[cfg(feature = "BatchCreatePublicZonesTask")]
pub mod BatchCreatePublicZonesTask;
#[cfg(feature = "BatchCreateRecordSetsTask")]
pub mod BatchCreateRecordSetsTask;
#[cfg(feature = "BatchCreateTag")]
pub mod BatchCreateTag;
#[cfg(feature = "BatchDeletePtrRecords")]
pub mod BatchDeletePtrRecords;
#[cfg(feature = "BatchDeletePublicRecordsetsTask")]
pub mod BatchDeletePublicRecordsetsTask;
#[cfg(feature = "BatchDeleteRecordSets")]
pub mod BatchDeleteRecordSets;
#[cfg(feature = "BatchDeleteRecordSetWithLine")]
pub mod BatchDeleteRecordSetWithLine;
#[cfg(feature = "BatchDeleteZones")]
pub mod BatchDeleteZones;
#[cfg(feature = "BatchSetRecordSetsStatus")]
pub mod BatchSetRecordSetsStatus;
#[cfg(feature = "BatchSetZonesStatus")]
pub mod BatchSetZonesStatus;
#[cfg(feature = "BatchTransferPublicZonesTask")]
pub mod BatchTransferPublicZonesTask;
#[cfg(feature = "BatchUpdatePublicRecordsetsTask")]
pub mod BatchUpdatePublicRecordsetsTask;
#[cfg(feature = "BatchUpdateRecordSetWithLine")]
pub mod BatchUpdateRecordSetWithLine;
#[cfg(feature = "CreateAuthorizeTxtRecord")]
pub mod CreateAuthorizeTxtRecord;
#[cfg(feature = "CreateAuthorizeTxtRecordVerification")]
pub mod CreateAuthorizeTxtRecordVerification;
#[cfg(feature = "CreateCustomLine")]
pub mod CreateCustomLine;
#[cfg(feature = "CreateEipRecordSet")]
pub mod CreateEipRecordSet;
#[cfg(feature = "CreateEndpoint")]
pub mod CreateEndpoint;
#[cfg(feature = "CreateLineGroup")]
pub mod CreateLineGroup;
#[cfg(feature = "CreatePrivateZone")]
pub mod CreatePrivateZone;
#[cfg(feature = "CreatePtr")]
pub mod CreatePtr;
#[cfg(feature = "CreatePublicZone")]
pub mod CreatePublicZone;
#[cfg(feature = "CreateRecordSet")]
pub mod CreateRecordSet;
#[cfg(feature = "CreateRecordSetWithBatchLines")]
pub mod CreateRecordSetWithBatchLines;
#[cfg(feature = "CreateRecordSetWithLine")]
pub mod CreateRecordSetWithLine;
#[cfg(feature = "CreateResolverQueryLogConfig")]
pub mod CreateResolverQueryLogConfig;
#[cfg(feature = "CreateResolverRule")]
pub mod CreateResolverRule;
#[cfg(feature = "CreateRetrieval")]
pub mod CreateRetrieval;
#[cfg(feature = "CreateRetrievalVerification")]
pub mod CreateRetrievalVerification;
#[cfg(feature = "CreateTag")]
pub mod CreateTag;
#[cfg(feature = "DeleteBatchCreateRecordSetsTask")]
pub mod DeleteBatchCreateRecordSetsTask;
#[cfg(feature = "DeleteCustomLine")]
pub mod DeleteCustomLine;
#[cfg(feature = "DeleteEndpoint")]
pub mod DeleteEndpoint;
#[cfg(feature = "DeleteLineGroup")]
pub mod DeleteLineGroup;
#[cfg(feature = "DeletePrivateZone")]
pub mod DeletePrivateZone;
#[cfg(feature = "DeletePtr")]
pub mod DeletePtr;
#[cfg(feature = "DeletePublicZone")]
pub mod DeletePublicZone;
#[cfg(feature = "DeleteRecordSet")]
pub mod DeleteRecordSet;
#[cfg(feature = "DeleteRecordSets")]
pub mod DeleteRecordSets;
#[cfg(feature = "DeleteResolverQueryLogConfig")]
pub mod DeleteResolverQueryLogConfig;
#[cfg(feature = "DeleteResolverRule")]
pub mod DeleteResolverRule;
#[cfg(feature = "DeleteTag")]
pub mod DeleteTag;
#[cfg(feature = "DisableDnssecConfig")]
pub mod DisableDnssecConfig;
#[cfg(feature = "DisassociateEndpointIpaddress")]
pub mod DisassociateEndpointIpaddress;
#[cfg(feature = "DisassociateResolverQueryLogConfig")]
pub mod DisassociateResolverQueryLogConfig;
#[cfg(feature = "DisassociateResolverRuleRouter")]
pub mod DisassociateResolverRuleRouter;
#[cfg(feature = "DisassociateRouter")]
pub mod DisassociateRouter;
#[cfg(feature = "EnableDnssecConfig")]
pub mod EnableDnssecConfig;
#[cfg(feature = "ListApiVersions")]
pub mod ListApiVersions;
#[cfg(feature = "ListBatchOperationTasks")]
pub mod ListBatchOperationTasks;
#[cfg(feature = "ListCustomLine")]
pub mod ListCustomLine;
#[cfg(feature = "ListEndpointIpaddresses")]
pub mod ListEndpointIpaddresses;
#[cfg(feature = "ListEndpoints")]
pub mod ListEndpoints;
#[cfg(feature = "ListEndpointVpcs")]
pub mod ListEndpointVpcs;
#[cfg(feature = "ListLineGroups")]
pub mod ListLineGroups;
#[cfg(feature = "ListNameServers")]
pub mod ListNameServers;
#[cfg(feature = "ListPrivateZones")]
pub mod ListPrivateZones;
#[cfg(feature = "ListPtrRecords")]
pub mod ListPtrRecords;
#[cfg(feature = "ListPtrs")]
pub mod ListPtrs;
#[cfg(feature = "ListPublicZoneLines")]
pub mod ListPublicZoneLines;
#[cfg(feature = "ListPublicZones")]
pub mod ListPublicZones;
#[cfg(feature = "ListRecordSets")]
pub mod ListRecordSets;
#[cfg(feature = "ListRecordSetsByZone")]
pub mod ListRecordSetsByZone;
#[cfg(feature = "ListRecordSetsWithLine")]
pub mod ListRecordSetsWithLine;
#[cfg(feature = "ListResolverQueryLogConfigs")]
pub mod ListResolverQueryLogConfigs;
#[cfg(feature = "ListResolverRules")]
pub mod ListResolverRules;
#[cfg(feature = "ListSystemLines")]
pub mod ListSystemLines;
#[cfg(feature = "ListTag")]
pub mod ListTag;
#[cfg(feature = "ListTags")]
pub mod ListTags;
#[cfg(feature = "RestorePtrRecord")]
pub mod RestorePtrRecord;
#[cfg(feature = "SetPrivateZoneProxyPattern")]
pub mod SetPrivateZoneProxyPattern;
#[cfg(feature = "SetRecordSetsStatus")]
pub mod SetRecordSetsStatus;
#[cfg(feature = "ShowApiInfo")]
pub mod ShowApiInfo;
#[cfg(feature = "ShowAuthorizeTxtRecord")]
pub mod ShowAuthorizeTxtRecord;
#[cfg(feature = "ShowBatchCreateRecordSetsTask")]
pub mod ShowBatchCreateRecordSetsTask;
#[cfg(feature = "ShowBatchOperationTask")]
pub mod ShowBatchOperationTask;
#[cfg(feature = "ShowDnssecConfig")]
pub mod ShowDnssecConfig;
#[cfg(feature = "ShowDomainDetection")]
pub mod ShowDomainDetection;
#[cfg(feature = "ShowDomainQuota")]
pub mod ShowDomainQuota;
#[cfg(feature = "ShowEmailRecordSet")]
pub mod ShowEmailRecordSet;
#[cfg(feature = "ShowEndpoint")]
pub mod ShowEndpoint;
#[cfg(feature = "ShowLineGroup")]
pub mod ShowLineGroup;
#[cfg(feature = "ShowPrivateZone")]
pub mod ShowPrivateZone;
#[cfg(feature = "ShowPrivateZoneNameServer")]
pub mod ShowPrivateZoneNameServer;
#[cfg(feature = "ShowPtr")]
pub mod ShowPtr;
#[cfg(feature = "ShowPtrRecordSet")]
pub mod ShowPtrRecordSet;
#[cfg(feature = "ShowPublicZone")]
pub mod ShowPublicZone;
#[cfg(feature = "ShowPublicZoneNameServer")]
pub mod ShowPublicZoneNameServer;
#[cfg(feature = "ShowRecordSet")]
pub mod ShowRecordSet;
#[cfg(feature = "ShowRecordSetByZone")]
pub mod ShowRecordSetByZone;
#[cfg(feature = "ShowRecordSetWithLine")]
pub mod ShowRecordSetWithLine;
#[cfg(feature = "ShowResolverQueryLogConfig")]
pub mod ShowResolverQueryLogConfig;
#[cfg(feature = "ShowResolverRule")]
pub mod ShowResolverRule;
#[cfg(feature = "ShowResourceTag")]
pub mod ShowResourceTag;
