#[cfg(feature = "AddFavouriteCustomTemplate")]
pub mod AddFavouriteCustomTemplate;
#[cfg(feature = "AddFavouriteOfficialTemplate")]
pub mod AddFavouriteOfficialTemplate;
#[cfg(feature = "AddFavouriteTask")]
pub mod AddFavouriteTask;
#[cfg(feature = "AddKeystorePermission")]
pub mod AddKeystorePermission;
#[cfg(feature = "ApplyProjectPermission")]
pub mod ApplyProjectPermission;
#[cfg(feature = "BatchDeleteBuildJobs")]
pub mod BatchDeleteBuildJobs;
#[cfg(feature = "BatchUpdateJobRolePermission")]
pub mod BatchUpdateJobRolePermission;
#[cfg(feature = "CheckJobCountIsTopLimit")]
pub mod CheckJobCountIsTopLimit;
#[cfg(feature = "CheckJobInternal")]
pub mod CheckJobInternal;
#[cfg(feature = "CheckJobNameIsExists")]
pub mod CheckJobNameIsExists;
#[cfg(feature = "CheckWebhookUrl")]
pub mod CheckWebhookUrl;
#[cfg(feature = "ClearRecyclingJobs")]
pub mod ClearRecyclingJobs;
#[cfg(feature = "CopyJob")]
pub mod CopyJob;
#[cfg(feature = "CreateBuildJob")]
pub mod CreateBuildJob;
#[cfg(feature = "CreateJobGroup")]
pub mod CreateJobGroup;
#[cfg(feature = "CreateNewJob")]
pub mod CreateNewJob;
#[cfg(feature = "CreateTemplate")]
pub mod CreateTemplate;
#[cfg(feature = "CreateTemplates")]
pub mod CreateTemplates;
#[cfg(feature = "DeleteBuildJob")]
pub mod DeleteBuildJob;
#[cfg(feature = "DeleteGroup")]
pub mod DeleteGroup;
#[cfg(feature = "DeleteKeystore")]
pub mod DeleteKeystore;
#[cfg(feature = "DeleteKeystorePermission")]
pub mod DeleteKeystorePermission;
#[cfg(feature = "DeleteRecyclingJobs")]
pub mod DeleteRecyclingJobs;
#[cfg(feature = "DeleteTemplate")]
pub mod DeleteTemplate;
#[cfg(feature = "DeleteTemplates")]
pub mod DeleteTemplates;
#[cfg(feature = "DeleteTheJob")]
pub mod DeleteTheJob;
#[cfg(feature = "DisableBuildJob")]
pub mod DisableBuildJob;
#[cfg(feature = "DisableNotice")]
pub mod DisableNotice;
#[cfg(feature = "DisableTheJob")]
pub mod DisableTheJob;
#[cfg(feature = "DownloadBuildFullLog")]
pub mod DownloadBuildFullLog;
#[cfg(feature = "DownloadBuildLog")]
pub mod DownloadBuildLog;
#[cfg(feature = "DownloadBuildRealTimeLog")]
pub mod DownloadBuildRealTimeLog;
#[cfg(feature = "DownloadJunitCoverageZip")]
pub mod DownloadJunitCoverageZip;
#[cfg(feature = "DownloadKeystore")]
pub mod DownloadKeystore;
#[cfg(feature = "DownloadKeystoreByName")]
pub mod DownloadKeystoreByName;
#[cfg(feature = "DownloadLogByRecordId")]
pub mod DownloadLogByRecordId;
#[cfg(feature = "DownloadRealTimeLog")]
pub mod DownloadRealTimeLog;
#[cfg(feature = "DownloadTaskLog")]
pub mod DownloadTaskLog;
#[cfg(feature = "EnableBuildJob")]
pub mod EnableBuildJob;
#[cfg(feature = "ExecuteJob")]
pub mod ExecuteJob;
#[cfg(feature = "ListBriefRecord")]
pub mod ListBriefRecord;
#[cfg(feature = "ListBuildInfoRecord")]
pub mod ListBuildInfoRecord;
#[cfg(feature = "ListBuildInfoRecordByJobId")]
pub mod ListBuildInfoRecordByJobId;
#[cfg(feature = "ListBuildParameter")]
pub mod ListBuildParameter;
#[cfg(feature = "ListCustomTemplate")]
pub mod ListCustomTemplate;
#[cfg(feature = "ListEndPoints")]
pub mod ListEndPoints;
#[cfg(feature = "ListGroupTree")]
pub mod ListGroupTree;
#[cfg(feature = "ListJob")]
pub mod ListJob;
#[cfg(feature = "ListJobConfig")]
pub mod ListJobConfig;
#[cfg(feature = "ListJunitCoverageSummary")]
pub mod ListJunitCoverageSummary;
#[cfg(feature = "ListKeystore")]
pub mod ListKeystore;
#[cfg(feature = "ListKeystoreSearch")]
pub mod ListKeystoreSearch;
#[cfg(feature = "ListNotice")]
pub mod ListNotice;
#[cfg(feature = "ListOfficialTemplate")]
pub mod ListOfficialTemplate;
#[cfg(feature = "ListProjectJobs")]
pub mod ListProjectJobs;
#[cfg(feature = "ListRecommendOfficialTemplate")]
pub mod ListRecommendOfficialTemplate;
#[cfg(feature = "ListRecords")]
pub mod ListRecords;
#[cfg(feature = "ListRecyclingJob")]
pub mod ListRecyclingJob;
#[cfg(feature = "ListRelatedProjectInfo")]
pub mod ListRelatedProjectInfo;
#[cfg(feature = "ListRepoBranch")]
pub mod ListRepoBranch;
#[cfg(feature = "ListRepository")]
pub mod ListRepository;
#[cfg(feature = "ListTemplates")]
pub mod ListTemplates;
#[cfg(feature = "ListUpdateJobHistory")]
pub mod ListUpdateJobHistory;
#[cfg(feature = "MoveGroup")]
pub mod MoveGroup;
#[cfg(feature = "RemoverFavouriteCustomTemplate")]
pub mod RemoverFavouriteCustomTemplate;
#[cfg(feature = "RemoverFavouriteOfficialTemplate")]
pub mod RemoverFavouriteOfficialTemplate;
#[cfg(feature = "RemoverFavouriteTask")]
pub mod RemoverFavouriteTask;
#[cfg(feature = "RestoreRecyclingJobs")]
pub mod RestoreRecyclingJobs;
#[cfg(feature = "RunJob")]
pub mod RunJob;
#[cfg(feature = "SaveTemplateUsedInfo")]
pub mod SaveTemplateUsedInfo;
#[cfg(feature = "SetKeepTime")]
pub mod SetKeepTime;
#[cfg(feature = "ShowActionIInfo")]
pub mod ShowActionIInfo;
#[cfg(feature = "ShowAvailableInnerSpec")]
pub mod ShowAvailableInnerSpec;
#[cfg(feature = "ShowBuildDetails")]
pub mod ShowBuildDetails;
#[cfg(feature = "ShowBuildInfoRecord")]
pub mod ShowBuildInfoRecord;
#[cfg(feature = "ShowBuildParamsList")]
pub mod ShowBuildParamsList;
#[cfg(feature = "ShowBuildRecord")]
pub mod ShowBuildRecord;
#[cfg(feature = "ShowBuildRecordBuildScript")]
pub mod ShowBuildRecordBuildScript;
#[cfg(feature = "ShowBuildRecordFlowGraph")]
pub mod ShowBuildRecordFlowGraph;
#[cfg(feature = "ShowBuildRecordFullStages")]
pub mod ShowBuildRecordFullStages;
#[cfg(feature = "ShowCopyName")]
pub mod ShowCopyName;
#[cfg(feature = "ShowDefaultBuildParameters")]
pub mod ShowDefaultBuildParameters;
#[cfg(feature = "ShowDefaultProjectPermission")]
pub mod ShowDefaultProjectPermission;
#[cfg(feature = "ShowDisable")]
pub mod ShowDisable;
#[cfg(feature = "ShowDockerfileTemplate")]
pub mod ShowDockerfileTemplate;
#[cfg(feature = "ShowDomainsStatuses")]
pub mod ShowDomainsStatuses;
#[cfg(feature = "ShowDomainStatus")]
pub mod ShowDomainStatus;
#[cfg(feature = "ShowFlowGraph")]
pub mod ShowFlowGraph;
#[cfg(feature = "ShowHistoryDetails")]
pub mod ShowHistoryDetails;
#[cfg(feature = "ShowImageTemplateList")]
pub mod ShowImageTemplateList;
#[cfg(feature = "ShowJobBuildRecordDetail")]
pub mod ShowJobBuildRecordDetail;
#[cfg(feature = "ShowJobBuildSuccessRatio")]
pub mod ShowJobBuildSuccessRatio;
#[cfg(feature = "ShowJobBuildTime")]
pub mod ShowJobBuildTime;
#[cfg(feature = "ShowJobConfig")]
pub mod ShowJobConfig;
#[cfg(feature = "ShowJobConfigDiff")]
pub mod ShowJobConfigDiff;
#[cfg(feature = "ShowJobInfo")]
pub mod ShowJobInfo;
#[cfg(feature = "ShowJobListByProjectId")]
pub mod ShowJobListByProjectId;
#[cfg(feature = "ShowJobNoticeConfigInfo")]
pub mod ShowJobNoticeConfigInfo;
#[cfg(feature = "ShowJobPipelineInfo")]
pub mod ShowJobPipelineInfo;
#[cfg(feature = "ShowJobRolePermission")]
pub mod ShowJobRolePermission;
