#[cfg(feature = "CheckJobNameIsExists")]
pub mod CheckJobNameIsExists;
#[cfg(feature = "CreateBuildJob")]
pub mod CreateBuildJob;
#[cfg(feature = "CreateTemplates")]
pub mod CreateTemplates;
#[cfg(feature = "DeleteBuildJob")]
pub mod DeleteBuildJob;
#[cfg(feature = "DeleteTemplates")]
pub mod DeleteTemplates;
#[cfg(feature = "DisableBuildJob")]
pub mod DisableBuildJob;
#[cfg(feature = "DisableNotice")]
pub mod DisableNotice;
#[cfg(feature = "DownloadBuildLog")]
pub mod DownloadBuildLog;
#[cfg(feature = "DownloadKeystore")]
pub mod DownloadKeystore;
#[cfg(feature = "DownloadKeystoreByName")]
pub mod DownloadKeystoreByName;
#[cfg(feature = "DownloadLogByRecordId")]
pub mod DownloadLogByRecordId;
#[cfg(feature = "DownloadRealTimeLog")]
pub mod DownloadRealTimeLog;
#[cfg(feature = "DownloadTaskLog")]
pub mod DownloadTaskLog;
#[cfg(feature = "EnableBuildJob")]
pub mod EnableBuildJob;
#[cfg(feature = "ListBuildInfoRecord")]
pub mod ListBuildInfoRecord;
#[cfg(feature = "ListBuildInfoRecordByJobId")]
pub mod ListBuildInfoRecordByJobId;
#[cfg(feature = "ListJobConfig")]
pub mod ListJobConfig;
#[cfg(feature = "ListKeystore")]
pub mod ListKeystore;
#[cfg(feature = "ListNotice")]
pub mod ListNotice;
#[cfg(feature = "ListOfficialTemplate")]
pub mod ListOfficialTemplate;
#[cfg(feature = "ListProjectJobs")]
pub mod ListProjectJobs;
#[cfg(feature = "ListRecords")]
pub mod ListRecords;
#[cfg(feature = "ListRecyclingJob")]
pub mod ListRecyclingJob;
#[cfg(feature = "ListRelatedProjectInfo")]
pub mod ListRelatedProjectInfo;
#[cfg(feature = "ListTemplates")]
pub mod ListTemplates;
#[cfg(feature = "RunJob")]
pub mod RunJob;
#[cfg(feature = "ShowBuildInfoRecord")]
pub mod ShowBuildInfoRecord;
#[cfg(feature = "ShowBuildParamsList")]
pub mod ShowBuildParamsList;
#[cfg(feature = "ShowBuildRecord")]
pub mod ShowBuildRecord;
#[cfg(feature = "ShowBuildRecordBuildScript")]
pub mod ShowBuildRecordBuildScript;
#[cfg(feature = "ShowBuildRecordFullStages")]
pub mod ShowBuildRecordFullStages;
#[cfg(feature = "ShowDefaultBuildParameters")]
pub mod ShowDefaultBuildParameters;
#[cfg(feature = "ShowDockerfileTemplate")]
pub mod ShowDockerfileTemplate;
#[cfg(feature = "ShowFlowGraph")]
pub mod ShowFlowGraph;
#[cfg(feature = "ShowHistoryDetails")]
pub mod ShowHistoryDetails;
#[cfg(feature = "ShowImageTemplateList")]
pub mod ShowImageTemplateList;
#[cfg(feature = "ShowJobBuildSuccessRatio")]
pub mod ShowJobBuildSuccessRatio;
#[cfg(feature = "ShowJobBuildTime")]
pub mod ShowJobBuildTime;
#[cfg(feature = "ShowJobConfig")]
pub mod ShowJobConfig;
#[cfg(feature = "ShowJobConfigDiff")]
pub mod ShowJobConfigDiff;
#[cfg(feature = "ShowJobInfo")]
pub mod ShowJobInfo;
#[cfg(feature = "ShowJobListByProjectId")]
pub mod ShowJobListByProjectId;
#[cfg(feature = "ShowJobNoticeConfigInfo")]
pub mod ShowJobNoticeConfigInfo;
#[cfg(feature = "ShowJobRolePermission")]
pub mod ShowJobRolePermission;
#[cfg(feature = "ShowJobStatus")]
pub mod ShowJobStatus;
#[cfg(feature = "ShowJobSuccessRatio")]
pub mod ShowJobSuccessRatio;
#[cfg(feature = "ShowJobSystemParameters")]
pub mod ShowJobSystemParameters;
#[cfg(feature = "ShowKeystorePermission")]
pub mod ShowKeystorePermission;
#[cfg(feature = "ShowLastHistory")]
pub mod ShowLastHistory;
#[cfg(feature = "ShowListHistory")]
pub mod ShowListHistory;
#[cfg(feature = "ShowListPeriodHistory")]
pub mod ShowListPeriodHistory;
#[cfg(feature = "ShowOutputInfo")]
pub mod ShowOutputInfo;
#[cfg(feature = "ShowProjectPermission")]
pub mod ShowProjectPermission;
#[cfg(feature = "ShowRecordDetail")]
pub mod ShowRecordDetail;
#[cfg(feature = "ShowRecordInfo")]
pub mod ShowRecordInfo;
#[cfg(feature = "ShowRelatedProject")]
pub mod ShowRelatedProject;
#[cfg(feature = "ShowReportSummary")]
pub mod ShowReportSummary;
#[cfg(feature = "ShowRunningStatus")]
pub mod ShowRunningStatus;
#[cfg(feature = "ShowYamlTemplate")]
pub mod ShowYamlTemplate;
#[cfg(feature = "StopBuildJob")]
pub mod StopBuildJob;
#[cfg(feature = "StopJob")]
pub mod StopJob;
#[cfg(feature = "UpdateBuildJob")]
pub mod UpdateBuildJob;
#[cfg(feature = "UpdateNotice")]
pub mod UpdateNotice;
