[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddSpurPoint = []
CreateCommonWorkspace = []
CreateMarkerInfo = []
CreateReal3DTask = []
CreateTask = []
DeleteCommonWorkspace = []
DeleteReal3DProduct = []
DeleteReal3DTask = []
DeleteSpurPoint = []
DeleteTask = []
ListCommonWorkspace = []
ListFolder = []
ListImageBaseInfo = []
ListReal3DProducts = []
ListSpurPoints = []
ListTaskInfo = []
ListTasksInWorkspace = []
ListUsageInfo = []
ShowReal3DUsage = []
ShowSpurCount = []
ShowTaskOverview = []
ShowTaskOverviewInWorkspace = []
StartNavi = []
StartReal3DTask = []
StartTask = []
StartVps = []
StopReal3DTask = []
StopTask = []
UpdateCommonWorkspace = []
UpdateReal3DTask = []
UpdateReal3DTaskArchivedStatus = []
UpdateTaskArchivedStatus = []
ValidateImage = []
full = ["AddSpurPoint", "CreateCommonWorkspace", "CreateMarkerInfo", "CreateReal3DTask", "CreateTask", "DeleteCommonWorkspace", "DeleteReal3DProduct", "DeleteReal3DTask", "DeleteSpurPoint", "DeleteTask", "ListCommonWorkspace", "ListFolder", "ListImageBaseInfo", "ListReal3DProducts", "ListSpurPoints", "ListTaskInfo", "ListTasksInWorkspace", "ListUsageInfo", "ShowReal3DUsage", "ShowSpurCount", "ShowTaskOverview", "ShowTaskOverviewInWorkspace", "StartNavi", "StartReal3DTask", "StartTask", "StartVps", "StopReal3DTask", "StopTask", "UpdateCommonWorkspace", "UpdateReal3DTask", "UpdateReal3DTaskArchivedStatus", "UpdateTaskArchivedStatus", "ValidateImage"]

[lib]
name = "huawei_cloud_api_definitions_KooMap"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-KooMap"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "0.1.0"
