#[cfg(feature = "BatchShowPipelinesLatestStatus")]
pub mod BatchShowPipelinesLatestStatus;
#[cfg(feature = "BatchShowPipelinesStatus")]
pub mod BatchShowPipelinesStatus;
#[cfg(feature = "CreatePipelineByTemplate")]
pub mod CreatePipelineByTemplate;
#[cfg(feature = "CreatePipelineByTemplateId")]
pub mod CreatePipelineByTemplateId;
#[cfg(feature = "DeletePipeline")]
pub mod DeletePipeline;
#[cfg(feature = "ListPipelineRuns")]
pub mod ListPipelineRuns;
#[cfg(feature = "ListPipelines")]
pub mod ListPipelines;
#[cfg(feature = "ListPipelineSimpleInfo")]
pub mod ListPipelineSimpleInfo;
#[cfg(feature = "ListPipelineTemplates")]
pub mod ListPipelineTemplates;
#[cfg(feature = "ListPipleineBuildResult")]
pub mod ListPipleineBuildResult;
#[cfg(feature = "ListTemplates")]
pub mod ListTemplates;
#[cfg(feature = "RemovePipeline")]
pub mod RemovePipeline;
#[cfg(feature = "RunPipeline")]
pub mod RunPipeline;
#[cfg(feature = "ShowInstanceStatus")]
pub mod ShowInstanceStatus;
#[cfg(feature = "ShowPipelineRunDetail")]
pub mod ShowPipelineRunDetail;
#[cfg(feature = "ShowPipelineTemplateDetail")]
pub mod ShowPipelineTemplateDetail;
#[cfg(feature = "ShowPipleineStatus")]
pub mod ShowPipleineStatus;
#[cfg(feature = "ShowTemplateDetail")]
pub mod ShowTemplateDetail;
#[cfg(feature = "StartNewPipeline")]
pub mod StartNewPipeline;
#[cfg(feature = "StopPipelineNew")]
pub mod StopPipelineNew;
#[cfg(feature = "StopPipelineRun")]
pub mod StopPipelineRun;
