#[cfg(feature = "connectCoreV1GetNamespacedPodExec")]
pub mod connectCoreV1GetNamespacedPodExec;
#[cfg(feature = "connectCoreV1PostNamespacedPodExec")]
pub mod connectCoreV1PostNamespacedPodExec;
#[cfg(feature = "createAppsV1NamespacedDeployment")]
pub mod createAppsV1NamespacedDeployment;
#[cfg(feature = "createAppsV1NamespacedStatefulSet")]
pub mod createAppsV1NamespacedStatefulSet;
#[cfg(feature = "createBatchV1NamespacedJob")]
pub mod createBatchV1NamespacedJob;
#[cfg(feature = "createBatchVolcanoShV1alpha1NamespacedJob")]
pub mod createBatchVolcanoShV1alpha1NamespacedJob;
#[cfg(feature = "createCoreV1Namespace")]
pub mod createCoreV1Namespace;
#[cfg(feature = "createCoreV1NamespacedConfigMap")]
pub mod createCoreV1NamespacedConfigMap;
#[cfg(feature = "createCoreV1NamespacedEndpoints")]
pub mod createCoreV1NamespacedEndpoints;
#[cfg(feature = "createCoreV1NamespacedPersistentVolumeClaim")]
pub mod createCoreV1NamespacedPersistentVolumeClaim;
#[cfg(feature = "createCoreV1NamespacedPod")]
pub mod createCoreV1NamespacedPod;
#[cfg(feature = "createCoreV1NamespacedSecret")]
pub mod createCoreV1NamespacedSecret;
#[cfg(feature = "createCoreV1NamespacedService")]
pub mod createCoreV1NamespacedService;
#[cfg(feature = "createCrdYangtseCniV1NamespacedEIPPool")]
pub mod createCrdYangtseCniV1NamespacedEIPPool;
#[cfg(feature = "createExtensionsV1beta1NamespacedIngress")]
pub mod createExtensionsV1beta1NamespacedIngress;
#[cfg(feature = "createNetworkingCciIoV1beta1NamespacedNetwork")]
pub mod createNetworkingCciIoV1beta1NamespacedNetwork;
#[cfg(feature = "createRbacAuthorizationV1NamespacedRoleBinding")]
pub mod createRbacAuthorizationV1NamespacedRoleBinding;
#[cfg(feature = "deleteAppsV1CollectionNamespacedDeployment")]
pub mod deleteAppsV1CollectionNamespacedDeployment;
#[cfg(feature = "deleteAppsV1CollectionNamespacedStatefulSet")]
pub mod deleteAppsV1CollectionNamespacedStatefulSet;
#[cfg(feature = "deleteAppsV1NamespacedDeployment")]
pub mod deleteAppsV1NamespacedDeployment;
#[cfg(feature = "deleteAppsV1NamespacedStatefulSet")]
pub mod deleteAppsV1NamespacedStatefulSet;
#[cfg(feature = "deleteBatchV1CollectionNamespacedJob")]
pub mod deleteBatchV1CollectionNamespacedJob;
#[cfg(feature = "deleteBatchV1NamespacedJob")]
pub mod deleteBatchV1NamespacedJob;
#[cfg(feature = "deleteBatchVolcanoShV1alpha1CollectionNamespacedJob")]
pub mod deleteBatchVolcanoShV1alpha1CollectionNamespacedJob;
#[cfg(feature = "deleteBatchVolcanoShV1alpha1NamespacedJob")]
pub mod deleteBatchVolcanoShV1alpha1NamespacedJob;
#[cfg(feature = "deleteCoreV1CollectionNamespacedConfigMap")]
pub mod deleteCoreV1CollectionNamespacedConfigMap;
#[cfg(feature = "deleteCoreV1CollectionNamespacedPod")]
pub mod deleteCoreV1CollectionNamespacedPod;
#[cfg(feature = "deleteCoreV1CollectionNamespacedSecret")]
pub mod deleteCoreV1CollectionNamespacedSecret;
#[cfg(feature = "deleteCoreV1Namespace")]
pub mod deleteCoreV1Namespace;
#[cfg(feature = "deleteCoreV1NamespacedConfigMap")]
pub mod deleteCoreV1NamespacedConfigMap;
#[cfg(feature = "deleteCoreV1NamespacedEndpoints")]
pub mod deleteCoreV1NamespacedEndpoints;
#[cfg(feature = "deleteCoreV1NamespacedEvent")]
pub mod deleteCoreV1NamespacedEvent;
#[cfg(feature = "deleteCoreV1NamespacedPersistentVolumeClaim")]
pub mod deleteCoreV1NamespacedPersistentVolumeClaim;
#[cfg(feature = "deleteCoreV1NamespacedPod")]
pub mod deleteCoreV1NamespacedPod;
#[cfg(feature = "deleteCoreV1NamespacedSecret")]
pub mod deleteCoreV1NamespacedSecret;
#[cfg(feature = "deleteCoreV1NamespacedService")]
pub mod deleteCoreV1NamespacedService;
#[cfg(feature = "deleteCrdYangtseCniV1NamespacedEIPPool")]
pub mod deleteCrdYangtseCniV1NamespacedEIPPool;
#[cfg(feature = "deleteExtensionsV1beta1CollectionNamespacedIngress")]
pub mod deleteExtensionsV1beta1CollectionNamespacedIngress;
#[cfg(feature = "deleteExtensionsV1beta1NamespacedIngress")]
pub mod deleteExtensionsV1beta1NamespacedIngress;
#[cfg(feature = "deleteNetworkingCciIoV1beta1CollectionNamespacedNetwork")]
pub mod deleteNetworkingCciIoV1beta1CollectionNamespacedNetwork;
#[cfg(feature = "deleteNetworkingCciIoV1beta1NamespacedNetwork")]
pub mod deleteNetworkingCciIoV1beta1NamespacedNetwork;
#[cfg(feature = "deleteRbacAuthorizationV1NamespacedRoleBinding")]
pub mod deleteRbacAuthorizationV1NamespacedRoleBinding;
#[cfg(feature = "getAPIVersions")]
pub mod getAPIVersions;
#[cfg(feature = "getAppsAPIGroup")]
pub mod getAppsAPIGroup;
#[cfg(feature = "getAppsV1APIResources")]
pub mod getAppsV1APIResources;
#[cfg(feature = "getBatchAPIGroup")]
pub mod getBatchAPIGroup;
#[cfg(feature = "getBatchV1APIResources")]
pub mod getBatchV1APIResources;
#[cfg(feature = "getBatchV1beta1APIResources")]
pub mod getBatchV1beta1APIResources;
#[cfg(feature = "getBatchVolcanoShAPIGroup")]
pub mod getBatchVolcanoShAPIGroup;
#[cfg(feature = "getBatchVolcanoShV1alpha1APIResources")]
pub mod getBatchVolcanoShV1alpha1APIResources;
#[cfg(feature = "getCoreAPIVersions")]
pub mod getCoreAPIVersions;
#[cfg(feature = "getCoreV1APIResources")]
pub mod getCoreV1APIResources;
#[cfg(feature = "getCrdYangtseCniAPIGroup")]
pub mod getCrdYangtseCniAPIGroup;
#[cfg(feature = "getCrdYangtseCniV1APIResources")]
pub mod getCrdYangtseCniV1APIResources;
#[cfg(feature = "getExtensionsAPIGroup")]
pub mod getExtensionsAPIGroup;
#[cfg(feature = "getExtensionsV1beta1APIResources")]
pub mod getExtensionsV1beta1APIResources;
#[cfg(feature = "getMetricsAPIGroup")]
pub mod getMetricsAPIGroup;
#[cfg(feature = "getMetricsV1beta1APIResources")]
pub mod getMetricsV1beta1APIResources;
#[cfg(feature = "getNetworkingCciIoAPIGroup")]
pub mod getNetworkingCciIoAPIGroup;
#[cfg(feature = "getNetworkingCciIoV1beta1APIResources")]
pub mod getNetworkingCciIoV1beta1APIResources;
#[cfg(feature = "GetOpenAPIv2")]
pub mod GetOpenAPIv2;
#[cfg(feature = "getRbacAuthorizationAPIGroup")]
pub mod getRbacAuthorizationAPIGroup;
#[cfg(feature = "getRbacAuthorizationV1APIResources")]
pub mod getRbacAuthorizationV1APIResources;
#[cfg(feature = "listAppsV1DeploymentForAllNamespaces")]
pub mod listAppsV1DeploymentForAllNamespaces;
#[cfg(feature = "listAppsV1NamespacedDeployment")]
pub mod listAppsV1NamespacedDeployment;
#[cfg(feature = "listAppsV1NamespacedReplicaSet")]
pub mod listAppsV1NamespacedReplicaSet;
#[cfg(feature = "listAppsV1NamespacedStatefulSet")]
pub mod listAppsV1NamespacedStatefulSet;
#[cfg(feature = "listAppsV1StatefulSetForAllNamespaces")]
pub mod listAppsV1StatefulSetForAllNamespaces;
#[cfg(feature = "listBatchV1beta1CronJobForAllNamespaces")]
pub mod listBatchV1beta1CronJobForAllNamespaces;
#[cfg(feature = "listBatchV1JobForAllNamespaces")]
pub mod listBatchV1JobForAllNamespaces;
#[cfg(feature = "listBatchV1NamespacedJob")]
pub mod listBatchV1NamespacedJob;
#[cfg(feature = "listBatchVolcanoShV1alpha1NamespacedJob")]
pub mod listBatchVolcanoShV1alpha1NamespacedJob;
#[cfg(feature = "listCoreV1Namespace")]
pub mod listCoreV1Namespace;
#[cfg(feature = "listCoreV1NamespacedConfigMap")]
pub mod listCoreV1NamespacedConfigMap;
#[cfg(feature = "listCoreV1NamespacedEndpoints")]
pub mod listCoreV1NamespacedEndpoints;
#[cfg(feature = "listCoreV1NamespacedEvent")]
pub mod listCoreV1NamespacedEvent;
#[cfg(feature = "listCoreV1NamespacedPersistentVolumeClaim")]
pub mod listCoreV1NamespacedPersistentVolumeClaim;
#[cfg(feature = "listCoreV1NamespacedPod")]
pub mod listCoreV1NamespacedPod;
#[cfg(feature = "listCoreV1NamespacedResourceQuota")]
pub mod listCoreV1NamespacedResourceQuota;
#[cfg(feature = "listCoreV1NamespacedSecret")]
pub mod listCoreV1NamespacedSecret;
#[cfg(feature = "listCoreV1NamespacedService")]
pub mod listCoreV1NamespacedService;
#[cfg(feature = "listCoreV1PodForAllNamespaces")]
pub mod listCoreV1PodForAllNamespaces;
#[cfg(feature = "listCrdYangtseCniV1NamespacedEIPPool")]
pub mod listCrdYangtseCniV1NamespacedEIPPool;
#[cfg(feature = "listExtensionsV1beta1NamespacedIngress")]
pub mod listExtensionsV1beta1NamespacedIngress;
#[cfg(feature = "listMetricsV1beta1NamespacedPodMetrics")]
pub mod listMetricsV1beta1NamespacedPodMetrics;
#[cfg(feature = "listNetworkingCciIoV1beta1NamespacedNetwork")]
pub mod listNetworkingCciIoV1beta1NamespacedNetwork;
#[cfg(feature = "listRbacAuthorizationV1ClusterRole")]
pub mod listRbacAuthorizationV1ClusterRole;
#[cfg(feature = "listRbacAuthorizationV1NamespacedRoleBinding")]
pub mod listRbacAuthorizationV1NamespacedRoleBinding;
#[cfg(feature = "listRbacAuthorizationV1RoleBindingForAllNamespaces")]
pub mod listRbacAuthorizationV1RoleBindingForAllNamespaces;
#[cfg(feature = "listStorageV1StorageClass")]
pub mod listStorageV1StorageClass;
#[cfg(feature = "patchAppsV1NamespacedDeployment")]
pub mod patchAppsV1NamespacedDeployment;
#[cfg(feature = "patchAppsV1NamespacedDeploymentScale")]
pub mod patchAppsV1NamespacedDeploymentScale;
#[cfg(feature = "patchAppsV1NamespacedStatefulSet")]
pub mod patchAppsV1NamespacedStatefulSet;
#[cfg(feature = "patchBatchV1NamespacedJob")]
pub mod patchBatchV1NamespacedJob;
#[cfg(feature = "patchBatchVolcanoShV1alpha1NamespacedJob")]
pub mod patchBatchVolcanoShV1alpha1NamespacedJob;
#[cfg(feature = "patchCoreV1NamespacedConfigMap")]
pub mod patchCoreV1NamespacedConfigMap;
#[cfg(feature = "patchCoreV1NamespacedEndpoints")]
pub mod patchCoreV1NamespacedEndpoints;
#[cfg(feature = "patchCoreV1NamespacedPod")]
pub mod patchCoreV1NamespacedPod;
#[cfg(feature = "patchCoreV1NamespacedSecret")]
pub mod patchCoreV1NamespacedSecret;
#[cfg(feature = "patchCoreV1NamespacedService")]
pub mod patchCoreV1NamespacedService;
