[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
ListAgents = []
ListAuditInfo = []
ListFlJob = []
ListInstanceHistory = []
ListLeagueDatasets = []
ListLeagues = []
ListNodes = []
ListNotices = []
ListPartners = []
ListSqlJob = []
ShowAgentDetail = []
ShowDatasetStatistics = []
ShowInstanceReport = []
ShowJobInstanceDag = []
ShowJobStatistics = []
ShowLeague = []
ShowOverview = []
ShowPartnerStatistics = []
UpdateLeague = []
full = ["ListAgents", "ListAuditInfo", "ListFlJob", "ListInstanceHistory", "ListLeagueDatasets", "ListLeagues", "ListNodes", "ListNotices", "ListPartners", "ListSqlJob", "ShowAgentDetail", "ShowDatasetStatistics", "ShowInstanceReport", "ShowJobInstanceDag", "ShowJobStatistics", "ShowLeague", "ShowOverview", "ShowPartnerStatistics", "UpdateLeague"]

[lib]
name = "huawei_cloud_api_definitions_TICS"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-TICS"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "0.1.0"
