[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddAttributeattribute = []
AddTagExaDefinition = []
AddTagXdmSearchServDefineMaster = []
AttachTagToExaAttrtag = []
CheckHasAccessAccessService = []
CheckUniqueExaDefinition = []
CheckUniqueFolder = []
CheckUniqueLifecycleTemplate = []
CheckUniquetag = []
CheckUniquetaggroup = []
CheckUniqueunique = []
CheckinXdmSearchServDefine = []
CheckoutAndUpdateXdmSearchServDefine = []
CheckoutLifecycleTemplate = []
CheckoutXdmSearchServDefine = []
CompareBusinessVersionLifecycleTemplate = []
CompareBusinessVersionXdmSearchServDefine = []
CompareVersionBaseLine = []
CompareVersionBaseLineLink = []
CompareVersionClassificationNode = []
CompareVersionClassificationNodeGroup = []
CompareVersionExaDefinition = []
CompareVersionExaDefinitionLink = []
CompareVersionFolder = []
CompareVersionLifecycleBusinessOperation = []
CompareVersionLifecycleOperation = []
CompareVersionLifecyclePhase = []
CompareVersionLifecycleState = []
CompareVersionLifecycleTemplate = []
CompareVersionLinkxSyncTask = []
CompareVersionMeasuringUnit = []
CompareVersionTag = []
CompareVersionTagGroup = []
CompareVersionTagLink = []
CompareVersionTenant = []
CompareVersionTypeDefinition = []
CompareVersionTypeDefinitionInheritLink = []
CompareVersionUnitType = []
CompareVersionXDmPermissionAssignmentXdmPermissionAssignment = []
CompareVersionXDmPermissionXdmPermission = []
CompareVersionXDmPolicyRuleXdmPolicyRule = []
CompareVersionXDmPrincipalRelationOperationHistory = []
CompareVersionXDmRoleXdmRole = []
CompareVersionXDmSearchColumnEntityXdmSearchColumnEntity = []
CompareVersionXDmUserGroupXdmUserGroup = []
CompareVersionXDmUserXdmUser = []
CountBaseLine = []
CountClassificationNode = []
CountClassificationNodeGroup = []
CountDimensionBaseAttr = []
CountExaDefinition = []
CountExaDefinitionLink = []
CountFolder = []
CountFolderedLink = []
CountLegalValue = []
CountLegalValueType = []
CountLifecycleBusinessOperation = []
CountLifecycleOperation = []
CountLifecycleTemplate = []
CountLinkxSyncTask = []
CountTagGroup = []
CountTagLink = []
CountTypeDefinition = []
CountTypeDefinitionInheritLink = []
CountUnitType = []
CountXDmAspectXdmAspect = []
CountXDmFolderAndPolicySetRelationXdmFolderAndPolicySetRelation = []
CountXDmOperationRelationXdmOperationRelation = []
CountXDmPermissionAssignmentXdmPermissionAssignment = []
CountXDmPermissionOperationXdmPermissionOperation = []
CountXDmPermissionXdmPermission = []
CountXDmPolicySetXdmPolicySet = []
CountXDmSearchServDefineApiXdmSearchServDefineApi = []
CountXDmSearchServDefineXdmSearchServDefine = []
CountXDmSearchServRelationLogXdmSearchServRelationLog = []
CountXDmTeamAndFolderRelationXdmTeamAndFolderRelation = []
CountXDmTeamRoleXdmTeamRole = []
CountXDmTeamXdmTeam = []
CreateClassificationNode = []
CreateExaDefinition = []
CreateExaDefinitionLink = []
CreateFolderedLink = []
CreateLegalValueType = []
CreateLifecycleBusinessOperation = []
CreateLifecycleOperation = []
CreateLifecycleState = []
CreateLifecycleTemplateLink = []
CreateTenant = []
CreateUnitType = []
CreateXDmOperationRelationXdmOperationRelation = []
CreateXDmPermissionAssignmentXdmPermissionAssignment = []
CreateXDmPermissionOperationXdmPermissionOperation = []
CreateXDmPermissionXdmPermission = []
CreateXDmPolicyRuleXdmPolicyRule = []
CreateXDmPolicyXdmPolicy = []
CreateXDmRoleMemberXdmRoleMember = []
Createauthorization = []
Createcustomservice = []
Createtag = []
Createtaggroup = []
full = ["AddAttributeattribute", "AddTagExaDefinition", "AddTagXdmSearchServDefineMaster", "AttachTagToExaAttrtag", "CheckHasAccessAccessService", "CheckinXdmSearchServDefine", "CheckoutAndUpdateXdmSearchServDefine", "CheckoutLifecycleTemplate", "CheckoutXdmSearchServDefine", "CheckUniqueExaDefinition", "CheckUniqueFolder", "CheckUniqueLifecycleTemplate", "CheckUniquetag", "CheckUniquetaggroup", "CheckUniqueunique", "CompareBusinessVersionLifecycleTemplate", "CompareBusinessVersionXdmSearchServDefine", "CompareVersionBaseLine", "CompareVersionBaseLineLink", "CompareVersionClassificationNode", "CompareVersionClassificationNodeGroup", "CompareVersionExaDefinition", "CompareVersionExaDefinitionLink", "CompareVersionFolder", "CompareVersionLifecycleBusinessOperation", "CompareVersionLifecycleOperation", "CompareVersionLifecyclePhase", "CompareVersionLifecycleState", "CompareVersionLifecycleTemplate", "CompareVersionLinkxSyncTask", "CompareVersionMeasuringUnit", "CompareVersionTag", "CompareVersionTagGroup", "CompareVersionTagLink", "CompareVersionTenant", "CompareVersionTypeDefinition", "CompareVersionTypeDefinitionInheritLink", "CompareVersionUnitType", "CompareVersionXDmPermissionAssignmentXdmPermissionAssignment", "CompareVersionXDmPermissionXdmPermission", "CompareVersionXDmPolicyRuleXdmPolicyRule", "CompareVersionXDmPrincipalRelationOperationHistory", "CompareVersionXDmRoleXdmRole", "CompareVersionXDmSearchColumnEntityXdmSearchColumnEntity", "CompareVersionXDmUserGroupXdmUserGroup", "CompareVersionXDmUserXdmUser", "CountBaseLine", "CountClassificationNode", "CountClassificationNodeGroup", "CountDimensionBaseAttr", "CountExaDefinition", "CountExaDefinitionLink", "CountFolder", "CountFolderedLink", "CountLegalValue", "CountLegalValueType", "CountLifecycleBusinessOperation", "CountLifecycleOperation", "CountLifecycleTemplate", "CountLinkxSyncTask", "CountTagGroup", "CountTagLink", "CountTypeDefinition", "CountTypeDefinitionInheritLink", "CountUnitType", "CountXDmAspectXdmAspect", "CountXDmFolderAndPolicySetRelationXdmFolderAndPolicySetRelation", "CountXDmOperationRelationXdmOperationRelation", "CountXDmPermissionAssignmentXdmPermissionAssignment", "CountXDmPermissionOperationXdmPermissionOperation", "CountXDmPermissionXdmPermission", "CountXDmPolicySetXdmPolicySet", "CountXDmSearchServDefineApiXdmSearchServDefineApi", "CountXDmSearchServDefineXdmSearchServDefine", "CountXDmSearchServRelationLogXdmSearchServRelationLog", "CountXDmTeamAndFolderRelationXdmTeamAndFolderRelation", "CountXDmTeamRoleXdmTeamRole", "CountXDmTeamXdmTeam", "Createauthorization", "CreateClassificationNode", "Createcustomservice", "CreateExaDefinition", "CreateExaDefinitionLink", "CreateFolderedLink", "CreateLegalValueType", "CreateLifecycleBusinessOperation", "CreateLifecycleOperation", "CreateLifecycleState", "CreateLifecycleTemplateLink", "Createtag", "Createtaggroup", "CreateTenant", "CreateUnitType", "CreateXDmOperationRelationXdmOperationRelation", "CreateXDmPermissionAssignmentXdmPermissionAssignment", "CreateXDmPermissionOperationXdmPermissionOperation", "CreateXDmPermissionXdmPermission", "CreateXDmPolicyRuleXdmPolicyRule", "CreateXDmPolicyXdmPolicy", "CreateXDmRoleMemberXdmRoleMember"]

[lib]
name = "huawei_cloud_api_definitions_IDT"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-IDT"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "0.1.0"
