[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
BatchAddRelationsByOneCase = []
BatchDeleteTestCase = []
BatchDeleteTestReport = []
CheckPermission = []
CreateApiTestSuiteByRepoFile = []
CreatePlan = []
CreateRelationsByOneCase = []
CreateResourceUri = []
CreateService = []
CreateTestCase = []
CreateTestCaseInPlan = []
DeleteRelationsByOneCase = []
DeleteService = []
ListAlertGroupsByCondition = []
ListAlertTemplates = []
ListAllBranches = []
ListAllConfigItemByType = []
ListAllIterators = []
ListAttachments = []
ListBasicAw = []
ListBranches = []
ListEnvironments = []
ListIssueTree = []
ListProjectFieldConfigs = []
ListProjectTestCaseFields = []
ListPublicLibAndAws = []
ListReports = []
ListResourcePools = []
ListTaskTestCases = []
ListTestCaseHistories = []
ListTestCases = []
ListTestReportsByCondition = []
ListTestTypes = []
ListTestcasesByProjectIssuesRelation = []
ListUsageInfos = []
ListUserDnsMapping = []
ListUserPackageUsage = []
ListUserPopupInfo = []
ListVariables = []
RunTestCase = []
SaveTaskSetting = []
ShowAllConfigValueByTypeAndKey = []
ShowAllFeatureChildren = []
ShowApiTestcaseHistories = []
ShowBackgroundInfo = []
ShowDisclaimerRecord = []
ShowDomainInfo = []
ShowFeatureChildren = []
ShowFreeDeclaration = []
ShowIfTaskNameRepeat = []
ShowIfUserNameRepeat = []
ShowIssuesByPlanId = []
ShowIteratorByDefect = []
ShowMindmapByPage = []
ShowMindmapCreatorName = []
ShowPlanJournals = []
ShowPlanList = []
ShowPlans = []
ShowProgress = []
ShowProjectDataDashboard = []
ShowRegisterService = []
ShowReport = []
ShowRequirementsOverview = []
ShowSystemConfigs = []
ShowTestCase = []
ShowTestCaseAndDefectInfo = []
ShowTestCaseDetail = []
ShowTestCaseDetailV2 = []
ShowUserAccessInfo = []
ShowUserExecuteTestCaseInfo = []
UpdateService = []
UpdateTestCase = []
UpdateTestCaseResult = []
full = ["BatchAddRelationsByOneCase", "BatchDeleteTestCase", "BatchDeleteTestReport", "CheckPermission", "CreateApiTestSuiteByRepoFile", "CreatePlan", "CreateRelationsByOneCase", "CreateResourceUri", "CreateService", "CreateTestCase", "CreateTestCaseInPlan", "DeleteRelationsByOneCase", "DeleteService", "ListAlertGroupsByCondition", "ListAlertTemplates", "ListAllBranches", "ListAllConfigItemByType", "ListAllIterators", "ListAttachments", "ListBasicAw", "ListBranches", "ListEnvironments", "ListIssueTree", "ListProjectFieldConfigs", "ListProjectTestCaseFields", "ListPublicLibAndAws", "ListReports", "ListResourcePools", "ListTaskTestCases", "ListTestCaseHistories", "ListTestCases", "ListTestcasesByProjectIssuesRelation", "ListTestReportsByCondition", "ListTestTypes", "ListUsageInfos", "ListUserDnsMapping", "ListUserPackageUsage", "ListUserPopupInfo", "ListVariables", "RunTestCase", "SaveTaskSetting", "ShowAllConfigValueByTypeAndKey", "ShowAllFeatureChildren", "ShowApiTestcaseHistories", "ShowBackgroundInfo", "ShowDisclaimerRecord", "ShowDomainInfo", "ShowFeatureChildren", "ShowFreeDeclaration", "ShowIfTaskNameRepeat", "ShowIfUserNameRepeat", "ShowIssuesByPlanId", "ShowIteratorByDefect", "ShowMindmapByPage", "ShowMindmapCreatorName", "ShowPlanJournals", "ShowPlanList", "ShowPlans", "ShowProgress", "ShowProjectDataDashboard", "ShowRegisterService", "ShowReport", "ShowRequirementsOverview", "ShowSystemConfigs", "ShowTestCase", "ShowTestCaseAndDefectInfo", "ShowTestCaseDetail", "ShowTestCaseDetailV2", "ShowUserAccessInfo", "ShowUserExecuteTestCaseInfo", "UpdateService", "UpdateTestCase", "UpdateTestCaseResult"]

[lib]
name = "huawei_cloud_api_definitions_CloudTest"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-CloudTest"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
