[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddCaseResultFour = []
AddFeature = []
AddTestCaseComment = []
AddTestCaseResultLog = []
BatchAddRelationsByOneCase = []
BatchAddResourcesForIterator = []
BatchDeleteFacotrByIds = []
BatchDeleteTestCase = []
BatchDeleteTestCases = []
BatchDeleteTestReport = []
BatchRemoveTestCasesFromIterator = []
BatchShowTestCase = []
BatchUpdateVersionTestCases = []
CheckPermission = []
CreateApiTestSuiteByRepoFile = []
CreateAssetTree = []
CreateBackupMindmap = []
CreateIterator = []
CreatePlan = []
CreateProjectBranch = []
CreateRelationsByOneCase = []
CreateReport = []
CreateResourceUri = []
CreateService = []
CreateTaskDefaultResult = []
CreateTemplate = []
CreateTestCase = []
CreateTestCaseInPlan = []
CreateUserDefinedUrlKeyWord = []
CreateVersionTestCase = []
DeleteAsset = []
DeleteAssetTree = []
DeleteBasicAwById = []
DeleteFacotrById = []
DeleteMindmapBackupById = []
DeleteMindmapRecycleById = []
DeleteRelationsByOneCase = []
DeleteService = []
DeleteTemplateById = []
DeleteTestCaseComment = []
DownloadAssetTemplate = []
ExportFactor = []
ImportAsset = []
ImportFactor = []
ListAlarmStatisticsUsing = []
ListAlertGroupsByCondition = []
ListAlertTemplates = []
ListAllBranches = []
ListAllConfigItemByType = []
ListAllIterators = []
ListAllTestCases = []
ListAttachments = []
ListAvailableConfig = []
ListBasicAw = []
ListBasicAwInfoListSupportsSearch = []
ListBranches = []
ListCasesStatus = []
ListDomainVisibleServices = []
ListEnvironments = []
ListIssueTree = []
ListIteratorIssueTree = []
ListIterators = []
ListLinesUsing = []
ListMsgInfosUsing = []
ListOwnTestCases = []
ListProjectFieldConfigs = []
ListProjectTestCaseFields = []
ListPublicLibAndAws = []
ListReports = []
ListResourcePools = []
ListScattersUsing = []
ListSubTaskCaseOverstockUsing = []
ListTaskAssignCases = []
ListTaskResults = []
ListTaskResultsDetail = []
ListTaskTestCases = []
ListTasks = []
ListTestCaseComments = []
ListTestCaseHistories = []
ListTestCaseScriptDetail = []
ListTestCases = []
ListTestCasesByIssue = []
ListTestReportsByCondition = []
ListTestTypes = []
ListTestcasePlans = []
ListTestcasesByProjectIssuesRelation = []
ListUsageInfos = []
ListUserDnsMapping = []
ListUserPackageUsage = []
ListUserPopupInfo = []
ListUsingGet = []
ListVariables = []
RemoveIssuesFromIterator = []
RunTestCase = []
SaveTaskSetting = []
ShowAllConfigValueByTypeAndKey = []
ShowAllFeatureChildren = []
ShowApiTestcaseHistories = []
ShowAsset = []
ShowAssetTree = []
full = ["AddCaseResultFour", "AddFeature", "AddTestCaseComment", "AddTestCaseResultLog", "BatchAddRelationsByOneCase", "BatchAddResourcesForIterator", "BatchDeleteFacotrByIds", "BatchDeleteTestCase", "BatchDeleteTestCases", "BatchDeleteTestReport", "BatchRemoveTestCasesFromIterator", "BatchShowTestCase", "BatchUpdateVersionTestCases", "CheckPermission", "CreateApiTestSuiteByRepoFile", "CreateAssetTree", "CreateBackupMindmap", "CreateIterator", "CreatePlan", "CreateProjectBranch", "CreateRelationsByOneCase", "CreateReport", "CreateResourceUri", "CreateService", "CreateTaskDefaultResult", "CreateTemplate", "CreateTestCase", "CreateTestCaseInPlan", "CreateUserDefinedUrlKeyWord", "CreateVersionTestCase", "DeleteAsset", "DeleteAssetTree", "DeleteBasicAwById", "DeleteFacotrById", "DeleteMindmapBackupById", "DeleteMindmapRecycleById", "DeleteRelationsByOneCase", "DeleteService", "DeleteTemplateById", "DeleteTestCaseComment", "DownloadAssetTemplate", "ExportFactor", "ImportAsset", "ImportFactor", "ListAlarmStatisticsUsing", "ListAlertGroupsByCondition", "ListAlertTemplates", "ListAllBranches", "ListAllConfigItemByType", "ListAllIterators", "ListAllTestCases", "ListAttachments", "ListAvailableConfig", "ListBasicAw", "ListBasicAwInfoListSupportsSearch", "ListBranches", "ListCasesStatus", "ListDomainVisibleServices", "ListEnvironments", "ListIssueTree", "ListIteratorIssueTree", "ListIterators", "ListLinesUsing", "ListMsgInfosUsing", "ListOwnTestCases", "ListProjectFieldConfigs", "ListProjectTestCaseFields", "ListPublicLibAndAws", "ListReports", "ListResourcePools", "ListScattersUsing", "ListSubTaskCaseOverstockUsing", "ListTaskAssignCases", "ListTaskResults", "ListTaskResultsDetail", "ListTasks", "ListTaskTestCases", "ListTestCaseComments", "ListTestCaseHistories", "ListTestcasePlans", "ListTestCases", "ListTestCasesByIssue", "ListTestcasesByProjectIssuesRelation", "ListTestCaseScriptDetail", "ListTestReportsByCondition", "ListTestTypes", "ListUsageInfos", "ListUserDnsMapping", "ListUserPackageUsage", "ListUserPopupInfo", "ListUsingGet", "ListVariables", "RemoveIssuesFromIterator", "RunTestCase", "SaveTaskSetting", "ShowAllConfigValueByTypeAndKey", "ShowAllFeatureChildren", "ShowApiTestcaseHistories", "ShowAsset", "ShowAssetTree"]

[lib]
name = "huawei_cloud_api_definitions_CloudTest"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-CloudTest"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
