[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddTestCaseComment = []
BatchAddRelationsByOneCase = []
BatchAddResourcesForIterator = []
BatchDeleteTestCase = []
BatchDeleteTestCases = []
BatchDeleteTestReport = []
BatchRemoveTestCasesFromIterator = []
BatchUpdateVersionTestCases = []
CheckPermission = []
CreateApiTestSuiteByRepoFile = []
CreateIterator = []
CreatePlan = []
CreateProjectBranch = []
CreateRelationsByOneCase = []
CreateReport = []
CreateResourceUri = []
CreateService = []
CreateTestCase = []
CreateTestCaseInPlan = []
CreateUserDefinedUrlKeyWord = []
CreateVersionTestCase = []
DeleteBasicAwById = []
DeleteRelationsByOneCase = []
DeleteService = []
DeleteTestCaseComment = []
ListAlarmStatisticsUsing = []
ListAlertGroupsByCondition = []
ListAlertTemplates = []
ListAllBranches = []
ListAllConfigItemByType = []
ListAllIterators = []
ListAllTestCases = []
ListAttachments = []
ListAvailableConfig = []
ListBasicAw = []
ListBasicAwInfoListSupportsSearch = []
ListBranches = []
ListCasesStatus = []
ListDomainVisibleServices = []
ListEnvironments = []
ListIssueTree = []
ListIteratorIssueTree = []
ListIterators = []
ListLinesUsing = []
ListMsgInfosUsing = []
ListOwnTestCases = []
ListProjectFieldConfigs = []
ListProjectTestCaseFields = []
ListPublicLibAndAws = []
ListReports = []
ListResourcePools = []
ListScattersUsing = []
ListSubTaskCaseOverstockUsing = []
ListTaskAssignCases = []
ListTaskTestCases = []
ListTasks = []
ListTestCaseComments = []
ListTestCaseHistories = []
ListTestCaseScriptDetail = []
ListTestCases = []
ListTestCasesByIssue = []
ListTestReportsByCondition = []
ListTestTypes = []
ListTestcasesByProjectIssuesRelation = []
ListUsageInfos = []
ListUserDnsMapping = []
ListUserPackageUsage = []
ListUserPopupInfo = []
ListUsingGet = []
ListVariables = []
RemoveIssuesFromIterator = []
RunTestCase = []
SaveTaskSetting = []
ShowAllConfigValueByTypeAndKey = []
ShowAllFeatureChildren = []
ShowApiTestcaseHistories = []
ShowAsset = []
ShowAssetTree = []
ShowBackgroundInfo = []
ShowBranch = []
ShowConcurrencyPackageUsing = []
ShowDisclaimerRecord = []
ShowDomainInfo = []
ShowEchoTestPackageUsing = []
ShowFactorByAssetId = []
ShowFactorById = []
ShowFeatureChildren = []
ShowFreeDeclaration = []
ShowIfTaskNameRepeat = []
ShowIfUserNameRepeat = []
ShowIssuesByPlanId = []
ShowIteratorByDefect = []
ShowIteratorDetail = []
ShowMindMapById = []
ShowMindmapByPage = []
ShowMindmapCreatorName = []
ShowOperationalDataCurrentMonthUsing = []
ShowPlanJournals = []
ShowPlanList = []
ShowPlans = []
full = ["AddTestCaseComment", "BatchAddRelationsByOneCase", "BatchAddResourcesForIterator", "BatchDeleteTestCase", "BatchDeleteTestCases", "BatchDeleteTestReport", "BatchRemoveTestCasesFromIterator", "BatchUpdateVersionTestCases", "CheckPermission", "CreateApiTestSuiteByRepoFile", "CreateIterator", "CreatePlan", "CreateProjectBranch", "CreateRelationsByOneCase", "CreateReport", "CreateResourceUri", "CreateService", "CreateTestCase", "CreateTestCaseInPlan", "CreateUserDefinedUrlKeyWord", "CreateVersionTestCase", "DeleteBasicAwById", "DeleteRelationsByOneCase", "DeleteService", "DeleteTestCaseComment", "ListAlarmStatisticsUsing", "ListAlertGroupsByCondition", "ListAlertTemplates", "ListAllBranches", "ListAllConfigItemByType", "ListAllIterators", "ListAllTestCases", "ListAttachments", "ListAvailableConfig", "ListBasicAw", "ListBasicAwInfoListSupportsSearch", "ListBranches", "ListCasesStatus", "ListDomainVisibleServices", "ListEnvironments", "ListIssueTree", "ListIteratorIssueTree", "ListIterators", "ListLinesUsing", "ListMsgInfosUsing", "ListOwnTestCases", "ListProjectFieldConfigs", "ListProjectTestCaseFields", "ListPublicLibAndAws", "ListReports", "ListResourcePools", "ListScattersUsing", "ListSubTaskCaseOverstockUsing", "ListTaskAssignCases", "ListTasks", "ListTaskTestCases", "ListTestCaseComments", "ListTestCaseHistories", "ListTestCases", "ListTestCasesByIssue", "ListTestcasesByProjectIssuesRelation", "ListTestCaseScriptDetail", "ListTestReportsByCondition", "ListTestTypes", "ListUsageInfos", "ListUserDnsMapping", "ListUserPackageUsage", "ListUserPopupInfo", "ListUsingGet", "ListVariables", "RemoveIssuesFromIterator", "RunTestCase", "SaveTaskSetting", "ShowAllConfigValueByTypeAndKey", "ShowAllFeatureChildren", "ShowApiTestcaseHistories", "ShowAsset", "ShowAssetTree", "ShowBackgroundInfo", "ShowBranch", "ShowConcurrencyPackageUsing", "ShowDisclaimerRecord", "ShowDomainInfo", "ShowEchoTestPackageUsing", "ShowFactorByAssetId", "ShowFactorById", "ShowFeatureChildren", "ShowFreeDeclaration", "ShowIfTaskNameRepeat", "ShowIfUserNameRepeat", "ShowIssuesByPlanId", "ShowIteratorByDefect", "ShowIteratorDetail", "ShowMindMapById", "ShowMindmapByPage", "ShowMindmapCreatorName", "ShowOperationalDataCurrentMonthUsing", "ShowPlanJournals", "ShowPlanList", "ShowPlans"]

[lib]
name = "huawei_cloud_api_definitions_CloudTest"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-CloudTest"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
