[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
RecognizeAcceptanceBill = []
RecognizeAutoClassification = []
RecognizeBankReceipt = []
RecognizeBankcard = []
RecognizeBusinessCard = []
RecognizeBusinessLicense = []
RecognizeColombiaIdCard = []
RecognizeCustomTemplate = []
RecognizeDriverLicense = []
RecognizeFinancialStatement = []
RecognizeFlightItinerary = []
RecognizeGeneralTable = []
RecognizeGeneralText = []
RecognizeHandwriting = []
RecognizeHouseholdRegister = []
RecognizeIdCard = []
RecognizeInsurancePolicy = []
RecognizeInvoiceVerification = []
RecognizeLicensePlate = []
RecognizeMvsInvoice = []
RecognizePassport = []
RecognizeQualificationCertificate = []
RecognizeQuotaInvoice = []
RecognizeRealEstateCertificate = []
RecognizeSeal = []
RecognizeSmartDocumentRecognizer = []
RecognizeTaxiInvoice = []
RecognizeThailandIdcard = []
RecognizeThailandLicensePlate = []
RecognizeTollInvoice = []
RecognizeTrainTicket = []
RecognizeTransportationLicense = []
RecognizeVatInvoice = []
RecognizeVehicleCertificate = []
RecognizeVehicleLicense = []
RecognizeVin = []
RecognizeWaybillElectronic = []
RecognizeWebImage = []
full = ["RecognizeAcceptanceBill", "RecognizeAutoClassification", "RecognizeBankcard", "RecognizeBankReceipt", "RecognizeBusinessCard", "RecognizeBusinessLicense", "RecognizeColombiaIdCard", "RecognizeCustomTemplate", "RecognizeDriverLicense", "RecognizeFinancialStatement", "RecognizeFlightItinerary", "RecognizeGeneralTable", "RecognizeGeneralText", "RecognizeHandwriting", "RecognizeHouseholdRegister", "RecognizeIdCard", "RecognizeInsurancePolicy", "RecognizeInvoiceVerification", "RecognizeLicensePlate", "RecognizeMvsInvoice", "RecognizePassport", "RecognizeQualificationCertificate", "RecognizeQuotaInvoice", "RecognizeRealEstateCertificate", "RecognizeSeal", "RecognizeSmartDocumentRecognizer", "RecognizeTaxiInvoice", "RecognizeThailandIdcard", "RecognizeThailandLicensePlate", "RecognizeTollInvoice", "RecognizeTrainTicket", "RecognizeTransportationLicense", "RecognizeVatInvoice", "RecognizeVehicleCertificate", "RecognizeVehicleLicense", "RecognizeVin", "RecognizeWaybillElectronic", "RecognizeWebImage"]

[lib]
name = "huawei_cloud_api_definitions_OCR"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-OCR"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
