#[cfg(feature = "BindPrivateZoneVpc")]
pub mod BindPrivateZoneVpc;
#[cfg(feature = "CreatePrivateZone")]
pub mod CreatePrivateZone;
#[cfg(feature = "CreateRecordset")]
pub mod CreateRecordset;
#[cfg(feature = "DeletePrivateZone")]
pub mod DeletePrivateZone;
#[cfg(feature = "DeleteRecordSet")]
pub mod DeleteRecordSet;
#[cfg(feature = "ListNameServers")]
pub mod ListNameServers;
#[cfg(feature = "ListPrivateZoneNameServers")]
pub mod ListPrivateZoneNameServers;
#[cfg(feature = "ListPrivateZones")]
pub mod ListPrivateZones;
#[cfg(feature = "ListRecordSets")]
pub mod ListRecordSets;
#[cfg(feature = "ListVersions")]
pub mod ListVersions;
#[cfg(feature = "ListZoneRecordSets")]
pub mod ListZoneRecordSets;
#[cfg(feature = "ShowPrivateZone")]
pub mod ShowPrivateZone;
#[cfg(feature = "ShowRecordSet")]
pub mod ShowRecordSet;
#[cfg(feature = "ShowVersion")]
pub mod ShowVersion;
#[cfg(feature = "UnbindPrivateZoneVpc")]
pub mod UnbindPrivateZoneVpc;
#[cfg(feature = "UpdatePrivateZone")]
pub mod UpdatePrivateZone;
#[cfg(feature = "UpdateRecordSet")]
pub mod UpdateRecordSet;
