#[cfg(feature = "AddExtensionEvaluation")]
pub mod AddExtensionEvaluation;
#[cfg(feature = "AddExtensionEvaluationReply")]
pub mod AddExtensionEvaluationReply;
#[cfg(feature = "AddExtensionStar")]
pub mod AddExtensionStar;
#[cfg(feature = "CheckInstanceAccess")]
pub mod CheckInstanceAccess;
#[cfg(feature = "CheckMaliciousExtensionEvaluation")]
pub mod CheckMaliciousExtensionEvaluation;
#[cfg(feature = "CheckName")]
pub mod CheckName;
#[cfg(feature = "CreateAcceptance")]
pub mod CreateAcceptance;
#[cfg(feature = "CreateApply")]
pub mod CreateApply;
#[cfg(feature = "CreateEvent")]
pub mod CreateEvent;
#[cfg(feature = "CreateExtensionAuthorization")]
pub mod CreateExtensionAuthorization;
#[cfg(feature = "CreateInstance")]
pub mod CreateInstance;
#[cfg(feature = "CreateInstanceBy3rd")]
pub mod CreateInstanceBy3rd;
#[cfg(feature = "CreateLogin")]
pub mod CreateLogin;
#[cfg(feature = "CreateRequest")]
pub mod CreateRequest;
#[cfg(feature = "DeleteEvaluation")]
pub mod DeleteEvaluation;
#[cfg(feature = "DeleteEvaluationReply")]
pub mod DeleteEvaluationReply;
#[cfg(feature = "DeleteInstance")]
pub mod DeleteInstance;
#[cfg(feature = "ListExtensions")]
pub mod ListExtensions;
#[cfg(feature = "ListInstances")]
pub mod ListInstances;
#[cfg(feature = "ListOrgInstances")]
pub mod ListOrgInstances;
#[cfg(feature = "ListProjectTemplates")]
pub mod ListProjectTemplates;
#[cfg(feature = "ListPublisher")]
pub mod ListPublisher;
#[cfg(feature = "ListStacks")]
pub mod ListStacks;
#[cfg(feature = "PublishExtension")]
pub mod PublishExtension;
#[cfg(feature = "ShowAccountStatus")]
pub mod ShowAccountStatus;
#[cfg(feature = "ShowCategoryList")]
pub mod ShowCategoryList;
#[cfg(feature = "ShowExtensionAuthorization")]
pub mod ShowExtensionAuthorization;
#[cfg(feature = "ShowExtensionDetail")]
pub mod ShowExtensionDetail;
#[cfg(feature = "ShowExtensionEvaluation")]
pub mod ShowExtensionEvaluation;
#[cfg(feature = "ShowExtensionEvaluationStar")]
pub mod ShowExtensionEvaluationStar;
#[cfg(feature = "ShowExtensionTestingResult")]
pub mod ShowExtensionTestingResult;
#[cfg(feature = "ShowInstance")]
pub mod ShowInstance;
#[cfg(feature = "ShowInstanceStatusInfo")]
pub mod ShowInstanceStatusInfo;
#[cfg(feature = "ShowPrice")]
pub mod ShowPrice;
#[cfg(feature = "ShowResult")]
pub mod ShowResult;
#[cfg(feature = "StartChat")]
pub mod StartChat;
#[cfg(feature = "StartInstance")]
pub mod StartInstance;
#[cfg(feature = "StopInstance")]
pub mod StopInstance;
#[cfg(feature = "SyncChat")]
pub mod SyncChat;
#[cfg(feature = "SyncGetChatResult")]
pub mod SyncGetChatResult;
#[cfg(feature = "UpdateInstance")]
pub mod UpdateInstance;
#[cfg(feature = "UpdateInstanceActivity")]
pub mod UpdateInstanceActivity;
#[cfg(feature = "UploadExtensionFile")]
pub mod UploadExtensionFile;
#[cfg(feature = "UploadFilePublisher")]
pub mod UploadFilePublisher;
