#[cfg(feature = "CreateIkePolicy")]
pub mod CreateIkePolicy;
#[cfg(feature = "CreateIpsecConnection")]
pub mod CreateIpsecConnection;
#[cfg(feature = "CreateIpsecPolicy")]
pub mod CreateIpsecPolicy;
#[cfg(feature = "CreateVpnEndpointGroup")]
pub mod CreateVpnEndpointGroup;
#[cfg(feature = "CreateVpnService")]
pub mod CreateVpnService;
#[cfg(feature = "ListIkePolicies")]
pub mod ListIkePolicies;
#[cfg(feature = "ListIpsecConnections")]
pub mod ListIpsecConnections;
#[cfg(feature = "ListIpsecPolicies")]
pub mod ListIpsecPolicies;
#[cfg(feature = "ListVpnEndpointGroups")]
pub mod ListVpnEndpointGroups;
#[cfg(feature = "ListVpnServices")]
pub mod ListVpnServices;
#[cfg(feature = "RemoveIkePolicy")]
pub mod RemoveIkePolicy;
#[cfg(feature = "RemoveIpsecConnection")]
pub mod RemoveIpsecConnection;
#[cfg(feature = "RemoveIpsecPolicy")]
pub mod RemoveIpsecPolicy;
#[cfg(feature = "RemoveVpnEndpointGroup")]
pub mod RemoveVpnEndpointGroup;
#[cfg(feature = "RemoveVpnService")]
pub mod RemoveVpnService;
#[cfg(feature = "ShowIkePolicy")]
pub mod ShowIkePolicy;
#[cfg(feature = "ShowIpsecConnection")]
pub mod ShowIpsecConnection;
#[cfg(feature = "ShowIpsecPolicy")]
pub mod ShowIpsecPolicy;
#[cfg(feature = "ShowVpnEndpointGroup")]
pub mod ShowVpnEndpointGroup;
#[cfg(feature = "ShowVpnService")]
pub mod ShowVpnService;
#[cfg(feature = "UpdateIkePolicy")]
pub mod UpdateIkePolicy;
#[cfg(feature = "UpdateIpsecPolicy")]
pub mod UpdateIpsecPolicy;
#[cfg(feature = "UpdatesIpsecConnection")]
pub mod UpdatesIpsecConnection;
#[cfg(feature = "UpdateVpnEndpointGroup")]
pub mod UpdateVpnEndpointGroup;
#[cfg(feature = "UpdateVpnService")]
pub mod UpdateVpnService;
