#[cfg(feature = "ApplyArchiveRule")]
pub mod ApplyArchiveRule;
#[cfg(feature = "CheckNoNewAccess")]
pub mod CheckNoNewAccess;
#[cfg(feature = "CreateAccessPreview")]
pub mod CreateAccessPreview;
#[cfg(feature = "CreateAnalyzer")]
pub mod CreateAnalyzer;
#[cfg(feature = "CreateArchiveRule")]
pub mod CreateArchiveRule;
#[cfg(feature = "CreateNotificationSetting")]
pub mod CreateNotificationSetting;
#[cfg(feature = "CreateResourceConfigurations")]
pub mod CreateResourceConfigurations;
#[cfg(feature = "DeleteAnalyzer")]
pub mod DeleteAnalyzer;
#[cfg(feature = "DeleteArchiveRule")]
pub mod DeleteArchiveRule;
#[cfg(feature = "DeleteNotificationSetting")]
pub mod DeleteNotificationSetting;
#[cfg(feature = "DeleteResourceConfigurations")]
pub mod DeleteResourceConfigurations;
#[cfg(feature = "ListAccessPreviewFindings")]
pub mod ListAccessPreviewFindings;
#[cfg(feature = "ListAccessPreviews")]
pub mod ListAccessPreviews;
#[cfg(feature = "ListAnalyzers")]
pub mod ListAnalyzers;
#[cfg(feature = "ListArchiveRules")]
pub mod ListArchiveRules;
#[cfg(feature = "ListFindings")]
pub mod ListFindings;
#[cfg(feature = "ListNotificationSettings")]
pub mod ListNotificationSettings;
#[cfg(feature = "ListResourceConfigurations")]
pub mod ListResourceConfigurations;
#[cfg(feature = "ShowAccessPreview")]
pub mod ShowAccessPreview;
#[cfg(feature = "ShowAnalyzer")]
pub mod ShowAnalyzer;
#[cfg(feature = "ShowArchiveRule")]
pub mod ShowArchiveRule;
#[cfg(feature = "ShowFinding")]
pub mod ShowFinding;
#[cfg(feature = "ShowNotificationSetting")]
pub mod ShowNotificationSetting;
#[cfg(feature = "StartResourceScan")]
pub mod StartResourceScan;
#[cfg(feature = "TagResource")]
pub mod TagResource;
#[cfg(feature = "UntagResource")]
pub mod UntagResource;
#[cfg(feature = "UpdateAnalyzer")]
pub mod UpdateAnalyzer;
#[cfg(feature = "UpdateArchiveRule")]
pub mod UpdateArchiveRule;
#[cfg(feature = "UpdateFindings")]
pub mod UpdateFindings;
#[cfg(feature = "UpdateNotificationSetting")]
pub mod UpdateNotificationSetting;
#[cfg(feature = "ValidatePolicy")]
pub mod ValidatePolicy;
