#[cfg(feature = "CreateDnatRuleEii")]
pub mod CreateDnatRuleEii;
#[cfg(feature = "CreateFlowLog")]
pub mod CreateFlowLog;
#[cfg(feature = "CreateNatGatewayCom")]
pub mod CreateNatGatewayCom;
#[cfg(feature = "CreateNatGatewayEii")]
pub mod CreateNatGatewayEii;
#[cfg(feature = "CreateSnatRuleCom")]
pub mod CreateSnatRuleCom;
#[cfg(feature = "CreateSnatRuleEii")]
pub mod CreateSnatRuleEii;
#[cfg(feature = "DeleteDnatRuleEii")]
pub mod DeleteDnatRuleEii;
#[cfg(feature = "DeleteFlowLog")]
pub mod DeleteFlowLog;
#[cfg(feature = "DeleteNatGatewayEii")]
pub mod DeleteNatGatewayEii;
#[cfg(feature = "DeleteSnatRuleEii")]
pub mod DeleteSnatRuleEii;
#[cfg(feature = "ListDnatRulesEii")]
pub mod ListDnatRulesEii;
#[cfg(feature = "ListFlowlog")]
pub mod ListFlowlog;
#[cfg(feature = "ListNatGatewaysEii")]
pub mod ListNatGatewaysEii;
#[cfg(feature = "ListSnatRulesEii")]
pub mod ListSnatRulesEii;
#[cfg(feature = "ShowDnatRuleEii")]
pub mod ShowDnatRuleEii;
#[cfg(feature = "ShowFlowlog")]
pub mod ShowFlowlog;
#[cfg(feature = "ShowNatGatewayCom")]
pub mod ShowNatGatewayCom;
#[cfg(feature = "ShowNatGatewayEii")]
pub mod ShowNatGatewayEii;
#[cfg(feature = "ShowSnatRuleCom")]
pub mod ShowSnatRuleCom;
#[cfg(feature = "ShowSnatRuleEii")]
pub mod ShowSnatRuleEii;
#[cfg(feature = "UpdateDnatRuleEii")]
pub mod UpdateDnatRuleEii;
#[cfg(feature = "UpdateFlowLog")]
pub mod UpdateFlowLog;
#[cfg(feature = "UpdateNatGatewayEii")]
pub mod UpdateNatGatewayEii;
#[cfg(feature = "UpdateSnatRulesCom")]
pub mod UpdateSnatRulesCom;
