#[cfg(feature = "CreateGroup")]
pub mod CreateGroup;
#[cfg(feature = "CreateUser")]
pub mod CreateUser;
#[cfg(feature = "DeleteGroup")]
pub mod DeleteGroup;
#[cfg(feature = "DeleteUser")]
pub mod DeleteUser;
#[cfg(feature = "GetGroup")]
pub mod GetGroup;
#[cfg(feature = "GetUser")]
pub mod GetUser;
#[cfg(feature = "ListGroups")]
pub mod ListGroups;
#[cfg(feature = "ListUsers")]
pub mod ListUsers;
#[cfg(feature = "PatchGroup")]
pub mod PatchGroup;
#[cfg(feature = "PatchUser")]
pub mod PatchUser;
#[cfg(feature = "PutUser")]
pub mod PutUser;
#[cfg(feature = "ServiceProviderConfig")]
pub mod ServiceProviderConfig;
