#[cfg(feature = "BatchAddSharedTags")]
pub mod BatchAddSharedTags;
#[cfg(feature = "ChangeSecurityGroup")]
pub mod ChangeSecurityGroup;
#[cfg(feature = "ChangeShareName")]
pub mod ChangeShareName;
#[cfg(feature = "CreateBackendTarget")]
pub mod CreateBackendTarget;
#[cfg(feature = "CreateFsDir")]
pub mod CreateFsDir;
#[cfg(feature = "CreateFsDirQuota")]
pub mod CreateFsDirQuota;
#[cfg(feature = "CreateFsTask")]
pub mod CreateFsTask;
#[cfg(feature = "CreateHpcCacheTask")]
pub mod CreateHpcCacheTask;
#[cfg(feature = "CreateLdapConfig")]
pub mod CreateLdapConfig;
#[cfg(feature = "CreatePermRule")]
pub mod CreatePermRule;
#[cfg(feature = "CreateShare")]
pub mod CreateShare;
#[cfg(feature = "CreateSharedTag")]
pub mod CreateSharedTag;
#[cfg(feature = "DeleteBackendTarget")]
pub mod DeleteBackendTarget;
#[cfg(feature = "DeleteFsDir")]
pub mod DeleteFsDir;
#[cfg(feature = "DeleteFsDirQuota")]
pub mod DeleteFsDirQuota;
#[cfg(feature = "DeleteFsTask")]
pub mod DeleteFsTask;
#[cfg(feature = "DeleteHpcCacheTask")]
pub mod DeleteHpcCacheTask;
#[cfg(feature = "DeleteLdapConfig")]
pub mod DeleteLdapConfig;
#[cfg(feature = "DeletePermRule")]
pub mod DeletePermRule;
#[cfg(feature = "DeleteShare")]
pub mod DeleteShare;
#[cfg(feature = "DeleteSharedTag")]
pub mod DeleteSharedTag;
#[cfg(feature = "ExpandShare")]
pub mod ExpandShare;
#[cfg(feature = "ListBackendTargets")]
pub mod ListBackendTargets;
#[cfg(feature = "ListFsTasks")]
pub mod ListFsTasks;
#[cfg(feature = "ListHpcCacheTasks")]
pub mod ListHpcCacheTasks;
#[cfg(feature = "ListPermRules")]
pub mod ListPermRules;
#[cfg(feature = "ListSharedTags")]
pub mod ListSharedTags;
#[cfg(feature = "ListShares")]
pub mod ListShares;
#[cfg(feature = "ListSharesByTag")]
pub mod ListSharesByTag;
#[cfg(feature = "SetHpcCacheBackend")]
pub mod SetHpcCacheBackend;
#[cfg(feature = "ShowBackendTargetInfo")]
pub mod ShowBackendTargetInfo;
#[cfg(feature = "ShowFsDir")]
pub mod ShowFsDir;
#[cfg(feature = "ShowFsDirQuota")]
pub mod ShowFsDirQuota;
#[cfg(feature = "ShowFsDirUsage")]
pub mod ShowFsDirUsage;
#[cfg(feature = "ShowFsTask")]
pub mod ShowFsTask;
#[cfg(feature = "ShowHpcCacheTask")]
pub mod ShowHpcCacheTask;
#[cfg(feature = "ShowJobDetail")]
pub mod ShowJobDetail;
#[cfg(feature = "ShowLdapConfig")]
pub mod ShowLdapConfig;
#[cfg(feature = "ShowPermRule")]
pub mod ShowPermRule;
#[cfg(feature = "ShowShare")]
pub mod ShowShare;
#[cfg(feature = "ShowSharedTags")]
pub mod ShowSharedTags;
#[cfg(feature = "UpdateFsDirQuota")]
pub mod UpdateFsDirQuota;
#[cfg(feature = "UpdateHpcShare")]
pub mod UpdateHpcShare;
#[cfg(feature = "UpdateLdapConfig")]
pub mod UpdateLdapConfig;
#[cfg(feature = "UpdateObsTargetAttributes")]
pub mod UpdateObsTargetAttributes;
#[cfg(feature = "UpdateObsTargetPolicy")]
pub mod UpdateObsTargetPolicy;
#[cfg(feature = "UpdatePermRule")]
pub mod UpdatePermRule;
