[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AttachCallbackInstanceLifeCycleHook = []
BatchAddScalingInstances = []
BatchDeleteScalingConfigs = []
BatchDeleteScalingPolicies = []
BatchPauseScalingPolicies = []
BatchProtectScalingInstances = []
BatchRemoveScalingInstances = []
BatchResumeScalingPolicies = []
BatchSetScalingInstancesStandby = []
BatchUnprotectScalingInstances = []
BatchUnsetScalingInstancesStantby = []
CloseWarmPool = []
CreateGroupScheduledTask = []
CreateLifyCycleHook = []
CreateScalingConfig = []
CreateScalingGroup = []
CreateScalingNotification = []
CreateScalingPolicy = []
CreateScalingTagInfo = []
CreateScalingV2Policy = []
DeleteGroupScheduledTask = []
DeleteLifecycleHook = []
DeleteScalingConfig = []
DeleteScalingGroup = []
DeleteScalingInstance = []
DeleteScalingNotification = []
DeleteScalingPolicy = []
DeleteScalingTagInfo = []
ExecuteScalingPolicy = []
ListAllScalingV2Policies = []
ListApiVersions = []
ListGroupScheduledTasks = []
ListHookInstances = []
ListLifeCycleHooks = []
ListResourceInstances = []
ListScalingActivityLogs = []
ListScalingActivityV2Logs = []
ListScalingConfigs = []
ListScalingGroups = []
ListScalingInstances = []
ListScalingNotifications = []
ListScalingPolicies = []
ListScalingPolicyExecuteLogs = []
ListScalingTagInfosByResourceId = []
ListScalingTagInfosByTenantId = []
ListScalingV2Policies = []
ListWarmPoolInstances = []
PauseScalingGroup = []
PauseScalingPolicy = []
PutWarmPool = []
QueryWarmPool = []
ResumeScalingGroup = []
ResumeScalingPolicy = []
ShowApiVersion = []
ShowLifeCycleHook = []
ShowPolicyAndInstanceQuota = []
ShowResourceQuota = []
ShowScalingConfig = []
ShowScalingGroup = []
ShowScalingPolicy = []
ShowScalingV2Policy = []
UpdateGroupScheduledTask = []
UpdateLifeCycleHook = []
UpdateScalingGroup = []
UpdateScalingPolicy = []
UpdateScalingV2Policy = []
full = ["AttachCallbackInstanceLifeCycleHook", "BatchAddScalingInstances", "BatchDeleteScalingConfigs", "BatchDeleteScalingPolicies", "BatchPauseScalingPolicies", "BatchProtectScalingInstances", "BatchRemoveScalingInstances", "BatchResumeScalingPolicies", "BatchSetScalingInstancesStandby", "BatchUnprotectScalingInstances", "BatchUnsetScalingInstancesStantby", "CloseWarmPool", "CreateGroupScheduledTask", "CreateLifyCycleHook", "CreateScalingConfig", "CreateScalingGroup", "CreateScalingNotification", "CreateScalingPolicy", "CreateScalingTagInfo", "CreateScalingV2Policy", "DeleteGroupScheduledTask", "DeleteLifecycleHook", "DeleteScalingConfig", "DeleteScalingGroup", "DeleteScalingInstance", "DeleteScalingNotification", "DeleteScalingPolicy", "DeleteScalingTagInfo", "ExecuteScalingPolicy", "ListAllScalingV2Policies", "ListApiVersions", "ListGroupScheduledTasks", "ListHookInstances", "ListLifeCycleHooks", "ListResourceInstances", "ListScalingActivityLogs", "ListScalingActivityV2Logs", "ListScalingConfigs", "ListScalingGroups", "ListScalingInstances", "ListScalingNotifications", "ListScalingPolicies", "ListScalingPolicyExecuteLogs", "ListScalingTagInfosByResourceId", "ListScalingTagInfosByTenantId", "ListScalingV2Policies", "ListWarmPoolInstances", "PauseScalingGroup", "PauseScalingPolicy", "PutWarmPool", "QueryWarmPool", "ResumeScalingGroup", "ResumeScalingPolicy", "ShowApiVersion", "ShowLifeCycleHook", "ShowPolicyAndInstanceQuota", "ShowResourceQuota", "ShowScalingConfig", "ShowScalingGroup", "ShowScalingPolicy", "ShowScalingV2Policy", "UpdateGroupScheduledTask", "UpdateLifeCycleHook", "UpdateScalingGroup", "UpdateScalingPolicy", "UpdateScalingV2Policy"]

[lib]
name = "huawei_cloud_api_definitions_AS"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-AS"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
