[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddPartitions = []
ApplyForAccess = []
AssociatePrincipals = []
AssociateRoles = []
AuthorizeAccessService = []
BatchAuthorizeInterface = []
BatchCancelAuthorizationInterface = []
BatchCheckPermission = []
BatchDeletePartition = []
BatchListPartitionByValues = []
BatchShowPartitionColumnStatistics = []
BatchUpdateLakeFormationInstanceTags = []
BatchUpdatePartition = []
CountMetaObj = []
CreateAccessClient = []
CreateAgency = []
CreateAgreement = []
CreateCatalog = []
CreateDatabase = []
CreateFunction = []
CreateLakeFormationInstance = []
CreateRole = []
CreateTable = []
DeleteAccessClient = []
DeleteAgency = []
DeleteAgreement = []
DeleteCatalog = []
DeleteDatabase = []
DeleteFunction = []
DeleteLakeFormationInstance = []
DeletePartitionColumnStatistics = []
DeleteRole = []
DeleteTable = []
DeleteTableColumnStatistics = []
ListAccessClientInfos = []
ListAccessInfos = []
ListAllFunctions = []
ListCatalogs = []
ListConfigs = []
ListDatabaseNames = []
ListDatabases = []
ListFunctionNames = []
ListFunctions = []
ListGroupsForDomain = []
ListInterfaces = []
ListLakeFormationInstanceTags = []
ListLakeFormationInstances = []
ListObsBuckets = []
ListObsObject = []
ListPartitionNames = []
ListPartitionNamesWithoutLimit = []
ListPartitions = []
ListPolicy = []
ListPrincipals = []
ListQuotas = []
ListRoleNames = []
ListRoles = []
ListSpecs = []
ListTableColumnStatistics = []
ListTableMeta = []
ListTableNames = []
ListTables = []
ListTablesByName = []
ListUserRoles = []
ListUsers = []
MoveLakeFormationInstanceOutRecycleBin = []
RevokePrincipals = []
RevokeRoles = []
SetPartitionColumnStatistics = []
SetTableColumnStatistics = []
ShowAccessClient = []
ShowAccessService = []
ShowAgency = []
ShowAgreement = []
ShowAgreementRule = []
ShowCatalog = []
ShowCredential = []
ShowDatabase = []
ShowFunction = []
ShowLakeFormationInstance = []
ShowRole = []
ShowSyncPolicy = []
ShowTable = []
UpdateAccessClient = []
UpdateCatalog = []
UpdateDatabase = []
UpdateFunction = []
UpdateLakeFormationInstance = []
UpdateLakeFormationInstanceDefault = []
UpdateLakeFormationInstanceScale = []
UpdatePrincipals = []
UpdateRole = []
UpdateRoles = []
UpdateTable = []
full = ["AddPartitions", "ApplyForAccess", "AssociatePrincipals", "AssociateRoles", "AuthorizeAccessService", "BatchAuthorizeInterface", "BatchCancelAuthorizationInterface", "BatchCheckPermission", "BatchDeletePartition", "BatchListPartitionByValues", "BatchShowPartitionColumnStatistics", "BatchUpdateLakeFormationInstanceTags", "BatchUpdatePartition", "CountMetaObj", "CreateAccessClient", "CreateAgency", "CreateAgreement", "CreateCatalog", "CreateDatabase", "CreateFunction", "CreateLakeFormationInstance", "CreateRole", "CreateTable", "DeleteAccessClient", "DeleteAgency", "DeleteAgreement", "DeleteCatalog", "DeleteDatabase", "DeleteFunction", "DeleteLakeFormationInstance", "DeletePartitionColumnStatistics", "DeleteRole", "DeleteTable", "DeleteTableColumnStatistics", "ListAccessClientInfos", "ListAccessInfos", "ListAllFunctions", "ListCatalogs", "ListConfigs", "ListDatabaseNames", "ListDatabases", "ListFunctionNames", "ListFunctions", "ListGroupsForDomain", "ListInterfaces", "ListLakeFormationInstances", "ListLakeFormationInstanceTags", "ListObsBuckets", "ListObsObject", "ListPartitionNames", "ListPartitionNamesWithoutLimit", "ListPartitions", "ListPolicy", "ListPrincipals", "ListQuotas", "ListRoleNames", "ListRoles", "ListSpecs", "ListTableColumnStatistics", "ListTableMeta", "ListTableNames", "ListTables", "ListTablesByName", "ListUserRoles", "ListUsers", "MoveLakeFormationInstanceOutRecycleBin", "RevokePrincipals", "RevokeRoles", "SetPartitionColumnStatistics", "SetTableColumnStatistics", "ShowAccessClient", "ShowAccessService", "ShowAgency", "ShowAgreement", "ShowAgreementRule", "ShowCatalog", "ShowCredential", "ShowDatabase", "ShowFunction", "ShowLakeFormationInstance", "ShowRole", "ShowSyncPolicy", "ShowTable", "UpdateAccessClient", "UpdateCatalog", "UpdateDatabase", "UpdateFunction", "UpdateLakeFormationInstance", "UpdateLakeFormationInstanceDefault", "UpdateLakeFormationInstanceScale", "UpdatePrincipals", "UpdateRole", "UpdateRoles", "UpdateTable"]

[lib]
name = "huawei_cloud_api_definitions_LakeFormation"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-LakeFormation"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "0.1.0"
