[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddUserToGroupV5 = []
AssociateAgencyWithAllProjectsPermission = []
AssociateAgencyWithDomainPermission = []
AssociateAgencyWithProjectPermission = []
AssociateRoleToAgencyOnEnterpriseProject = []
AssociateRoleToGroupOnEnterpriseProject = []
AssociateRoleToUserOnEnterpriseProject = []
AttachAgencyPolicyV5 = []
AttachGroupPolicyV5 = []
AttachUserPolicyV5 = []
ChangePasswordV5 = []
CheckAllProjectsPermissionForAgency = []
CheckDomainPermissionForAgency = []
CheckProjectPermissionForAgency = []
CreateAccessKeyV5 = []
CreateAgency = []
CreateAgencyCustomPolicy = []
CreateAgencyV5 = []
CreateBindingDevice = []
CreateCloudServiceCustomPolicy = []
CreateGroupV5 = []
CreateLoginProfileV5 = []
CreateLoginToken = []
CreateMetadata = []
CreateMfaDevice = []
CreateOpenIdConnectConfig = []
CreatePermanentAccessKey = []
CreatePolicyV5 = []
CreatePolicyVersionV5 = []
CreateServiceLinkedAgencyV5 = []
CreateTemporaryAccessKeyByAgency = []
CreateTemporaryAccessKeyByToken = []
CreateTokenWithIdToken = []
CreateUnscopeTokenByIdpInitiated = []
CreateUnscopedTokenWithIdToken = []
CreateUser = []
CreateUserV5 = []
CreateVirtualMfaDeviceV5 = []
DeleteAccessKeyV5 = []
DeleteAgency = []
DeleteAgencyV5 = []
DeleteBindingDevice = []
DeleteCustomPolicy = []
DeleteDomainGroupInheritedRole = []
DeleteGroupV5 = []
DeleteLoginProfileV5 = []
DeleteMfaDevice = []
DeletePermanentAccessKey = []
DeletePolicyV5 = []
DeletePolicyVersionV5 = []
DeleteResourceTagsV5 = []
DeleteServiceLinkedAgencyV5 = []
DeleteUserV5 = []
DeleteVirtualMfaDeviceV5 = []
DetachAgencyPolicyV5 = []
DetachGroupPolicyV5 = []
DetachUserPolicyV5 = []
DisableMfaDeviceV5 = []
EnableMfaDeviceV5 = []
GetAccountSummaryV5 = []
GetAgencyV5 = []
GetAsymmetricSignatureSwitchV5 = []
GetAuthorizationSchemaV5 = []
GetFeatureStatusV5 = []
GetPolicyV5 = []
GetPolicyVersionV5 = []
GetServiceLinkedAgencyDeletionStatusV5 = []
KeystoneAddUserToGroup = []
KeystoneAssociateGroupWithDomainPermission = []
KeystoneAssociateGroupWithProjectPermission = []
KeystoneCheckDomainPermissionForGroup = []
KeystoneCheckProjectPermissionForGroup = []
KeystoneCheckUserInGroup = []
KeystoneCheckroleForGroup = []
KeystoneCreateAgencyToken = []
KeystoneCreateGroup = []
KeystoneCreateIdentityProvider = []
KeystoneCreateMapping = []
KeystoneCreateProject = []
KeystoneCreateProtocol = []
KeystoneCreateScopedToken = []
KeystoneCreateUser = []
KeystoneCreateUserTokenByPassword = []
KeystoneCreateUserTokenByPasswordAndMfa = []
KeystoneDeleteGroup = []
KeystoneDeleteIdentityProvider = []
KeystoneDeleteMapping = []
KeystoneDeleteProtocol = []
KeystoneDeleteUser = []
KeystoneListAllProjectPermissionsForGroup = []
KeystoneListAuthDomains = []
KeystoneListAuthProjects = []
KeystoneListDomainPermissionsForGroup = []
KeystoneListEndpoints = []
KeystoneListFederationDomains = []
KeystoneListFederationProjects = []
KeystoneListGroups = []
KeystoneListGroupsForUser = []
KeystoneListIdentityProviders = []
KeystoneListMappings = []
full = ["AddUserToGroupV5", "AssociateAgencyWithAllProjectsPermission", "AssociateAgencyWithDomainPermission", "AssociateAgencyWithProjectPermission", "AssociateRoleToAgencyOnEnterpriseProject", "AssociateRoleToGroupOnEnterpriseProject", "AssociateRoleToUserOnEnterpriseProject", "AttachAgencyPolicyV5", "AttachGroupPolicyV5", "AttachUserPolicyV5", "ChangePasswordV5", "CheckAllProjectsPermissionForAgency", "CheckDomainPermissionForAgency", "CheckProjectPermissionForAgency", "CreateAccessKeyV5", "CreateAgency", "CreateAgencyCustomPolicy", "CreateAgencyV5", "CreateBindingDevice", "CreateCloudServiceCustomPolicy", "CreateGroupV5", "CreateLoginProfileV5", "CreateLoginToken", "CreateMetadata", "CreateMfaDevice", "CreateOpenIdConnectConfig", "CreatePermanentAccessKey", "CreatePolicyV5", "CreatePolicyVersionV5", "CreateServiceLinkedAgencyV5", "CreateTemporaryAccessKeyByAgency", "CreateTemporaryAccessKeyByToken", "CreateTokenWithIdToken", "CreateUnscopedTokenWithIdToken", "CreateUnscopeTokenByIdpInitiated", "CreateUser", "CreateUserV5", "CreateVirtualMfaDeviceV5", "DeleteAccessKeyV5", "DeleteAgency", "DeleteAgencyV5", "DeleteBindingDevice", "DeleteCustomPolicy", "DeleteDomainGroupInheritedRole", "DeleteGroupV5", "DeleteLoginProfileV5", "DeleteMfaDevice", "DeletePermanentAccessKey", "DeletePolicyV5", "DeletePolicyVersionV5", "DeleteResourceTagsV5", "DeleteServiceLinkedAgencyV5", "DeleteUserV5", "DeleteVirtualMfaDeviceV5", "DetachAgencyPolicyV5", "DetachGroupPolicyV5", "DetachUserPolicyV5", "DisableMfaDeviceV5", "EnableMfaDeviceV5", "GetAccountSummaryV5", "GetAgencyV5", "GetAsymmetricSignatureSwitchV5", "GetAuthorizationSchemaV5", "GetFeatureStatusV5", "GetPolicyV5", "GetPolicyVersionV5", "GetServiceLinkedAgencyDeletionStatusV5", "KeystoneAddUserToGroup", "KeystoneAssociateGroupWithDomainPermission", "KeystoneAssociateGroupWithProjectPermission", "KeystoneCheckDomainPermissionForGroup", "KeystoneCheckProjectPermissionForGroup", "KeystoneCheckroleForGroup", "KeystoneCheckUserInGroup", "KeystoneCreateAgencyToken", "KeystoneCreateGroup", "KeystoneCreateIdentityProvider", "KeystoneCreateMapping", "KeystoneCreateProject", "KeystoneCreateProtocol", "KeystoneCreateScopedToken", "KeystoneCreateUser", "KeystoneCreateUserTokenByPassword", "KeystoneCreateUserTokenByPasswordAndMfa", "KeystoneDeleteGroup", "KeystoneDeleteIdentityProvider", "KeystoneDeleteMapping", "KeystoneDeleteProtocol", "KeystoneDeleteUser", "KeystoneListAllProjectPermissionsForGroup", "KeystoneListAuthDomains", "KeystoneListAuthProjects", "KeystoneListDomainPermissionsForGroup", "KeystoneListEndpoints", "KeystoneListFederationDomains", "KeystoneListFederationProjects", "KeystoneListGroups", "KeystoneListGroupsForUser", "KeystoneListIdentityProviders", "KeystoneListMappings"]

[lib]
name = "huawei_cloud_api_definitions_IAM"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-IAM"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
