[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AssociateAgencyWithAllProjectsPermission = []
AssociateAgencyWithDomainPermission = []
AssociateAgencyWithProjectPermission = []
AssociateRoleToAgencyOnEnterpriseProject = []
AssociateRoleToGroupOnEnterpriseProject = []
AssociateRoleToUserOnEnterpriseProject = []
CheckAllProjectsPermissionForAgency = []
CheckDomainPermissionForAgency = []
CheckProjectPermissionForAgency = []
CreateAgency = []
CreateAgencyCustomPolicy = []
CreateBindingDevice = []
CreateCloudServiceCustomPolicy = []
CreateLoginToken = []
CreateMetadata = []
CreateMfaDevice = []
CreateOpenIdConnectConfig = []
CreatePermanentAccessKey = []
CreateTemporaryAccessKeyByAgency = []
CreateTemporaryAccessKeyByToken = []
CreateTokenWithIdToken = []
CreateUnscopeTokenByIdpInitiated = []
CreateUnscopedTokenWithIdToken = []
CreateUser = []
DeleteAgency = []
DeleteBindingDevice = []
DeleteCustomPolicy = []
DeleteDomainGroupInheritedRole = []
DeleteMfaDevice = []
DeletePermanentAccessKey = []
KeystoneAddUserToGroup = []
KeystoneAssociateGroupWithDomainPermission = []
KeystoneAssociateGroupWithProjectPermission = []
KeystoneCheckDomainPermissionForGroup = []
KeystoneCheckProjectPermissionForGroup = []
KeystoneCheckUserInGroup = []
KeystoneCheckroleForGroup = []
KeystoneCreateAgencyToken = []
KeystoneCreateGroup = []
KeystoneCreateIdentityProvider = []
KeystoneCreateMapping = []
KeystoneCreateProject = []
KeystoneCreateProtocol = []
KeystoneCreateScopedToken = []
KeystoneCreateUser = []
KeystoneCreateUserTokenByPassword = []
KeystoneCreateUserTokenByPasswordAndMfa = []
KeystoneDeleteGroup = []
KeystoneDeleteIdentityProvider = []
KeystoneDeleteMapping = []
KeystoneDeleteProtocol = []
KeystoneDeleteUser = []
KeystoneListAllProjectPermissionsForGroup = []
KeystoneListAuthDomains = []
KeystoneListAuthProjects = []
KeystoneListDomainPermissionsForGroup = []
KeystoneListEndpoints = []
KeystoneListFederationDomains = []
KeystoneListGroups = []
KeystoneListGroupsForUser = []
KeystoneListIdentityProviders = []
KeystoneListMappings = []
KeystoneListPermissions = []
KeystoneListProjectPermissionsForGroup = []
KeystoneListProjects = []
KeystoneListProjectsForUser = []
KeystoneListProtocols = []
KeystoneListRegions = []
KeystoneListServices = []
KeystoneListUsers = []
KeystoneListUsersForGroupByAdmin = []
KeystoneListVersions = []
KeystoneRemoveDomainPermissionFromGroup = []
KeystoneRemoveProjectPermissionFromGroup = []
KeystoneRemoveUserFromGroup = []
KeystoneShowCatalog = []
KeystoneShowEndpoint = []
KeystoneShowGroup = []
KeystoneShowIdentityProvider = []
KeystoneShowMapping = []
KeystoneShowPermission = []
KeystoneShowProject = []
KeystoneShowProtocol = []
KeystoneShowRegion = []
KeystoneShowSecurityCompliance = []
KeystoneShowSecurityComplianceByOption = []
KeystoneShowService = []
KeystoneShowUser = []
KeystoneShowVersion = []
KeystoneUpdateGroup = []
KeystoneUpdateIdentityProvider = []
KeystoneUpdateMapping = []
KeystoneUpdateProject = []
KeystoneUpdateProtocol = []
KeystoneUpdateUserByAdmin = []
KeystoneUpdateUserPassword = []
KeystoneValidateToken = []
ListAgencies = []
ListAllProjectsPermissionsForAgency = []
ListCustomPolicies = []
full = ["AssociateAgencyWithAllProjectsPermission", "AssociateAgencyWithDomainPermission", "AssociateAgencyWithProjectPermission", "AssociateRoleToAgencyOnEnterpriseProject", "AssociateRoleToGroupOnEnterpriseProject", "AssociateRoleToUserOnEnterpriseProject", "CheckAllProjectsPermissionForAgency", "CheckDomainPermissionForAgency", "CheckProjectPermissionForAgency", "CreateAgency", "CreateAgencyCustomPolicy", "CreateBindingDevice", "CreateCloudServiceCustomPolicy", "CreateLoginToken", "CreateMetadata", "CreateMfaDevice", "CreateOpenIdConnectConfig", "CreatePermanentAccessKey", "CreateTemporaryAccessKeyByAgency", "CreateTemporaryAccessKeyByToken", "CreateTokenWithIdToken", "CreateUnscopedTokenWithIdToken", "CreateUnscopeTokenByIdpInitiated", "CreateUser", "DeleteAgency", "DeleteBindingDevice", "DeleteCustomPolicy", "DeleteDomainGroupInheritedRole", "DeleteMfaDevice", "DeletePermanentAccessKey", "KeystoneAddUserToGroup", "KeystoneAssociateGroupWithDomainPermission", "KeystoneAssociateGroupWithProjectPermission", "KeystoneCheckDomainPermissionForGroup", "KeystoneCheckProjectPermissionForGroup", "KeystoneCheckroleForGroup", "KeystoneCheckUserInGroup", "KeystoneCreateAgencyToken", "KeystoneCreateGroup", "KeystoneCreateIdentityProvider", "KeystoneCreateMapping", "KeystoneCreateProject", "KeystoneCreateProtocol", "KeystoneCreateScopedToken", "KeystoneCreateUser", "KeystoneCreateUserTokenByPassword", "KeystoneCreateUserTokenByPasswordAndMfa", "KeystoneDeleteGroup", "KeystoneDeleteIdentityProvider", "KeystoneDeleteMapping", "KeystoneDeleteProtocol", "KeystoneDeleteUser", "KeystoneListAllProjectPermissionsForGroup", "KeystoneListAuthDomains", "KeystoneListAuthProjects", "KeystoneListDomainPermissionsForGroup", "KeystoneListEndpoints", "KeystoneListFederationDomains", "KeystoneListGroups", "KeystoneListGroupsForUser", "KeystoneListIdentityProviders", "KeystoneListMappings", "KeystoneListPermissions", "KeystoneListProjectPermissionsForGroup", "KeystoneListProjects", "KeystoneListProjectsForUser", "KeystoneListProtocols", "KeystoneListRegions", "KeystoneListServices", "KeystoneListUsers", "KeystoneListUsersForGroupByAdmin", "KeystoneListVersions", "KeystoneRemoveDomainPermissionFromGroup", "KeystoneRemoveProjectPermissionFromGroup", "KeystoneRemoveUserFromGroup", "KeystoneShowCatalog", "KeystoneShowEndpoint", "KeystoneShowGroup", "KeystoneShowIdentityProvider", "KeystoneShowMapping", "KeystoneShowPermission", "KeystoneShowProject", "KeystoneShowProtocol", "KeystoneShowRegion", "KeystoneShowSecurityCompliance", "KeystoneShowSecurityComplianceByOption", "KeystoneShowService", "KeystoneShowUser", "KeystoneShowVersion", "KeystoneUpdateGroup", "KeystoneUpdateIdentityProvider", "KeystoneUpdateMapping", "KeystoneUpdateProject", "KeystoneUpdateProtocol", "KeystoneUpdateUserByAdmin", "KeystoneUpdateUserPassword", "KeystoneValidateToken", "ListAgencies", "ListAllProjectsPermissionsForAgency", "ListCustomPolicies"]

[lib]
name = "huawei_cloud_api_definitions_IAM"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-IAM"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "0.1.0"
