#[cfg(feature = "CreateResDatasource")]
pub mod CreateResDatasource;
#[cfg(feature = "CreateResIntelligentScene")]
pub mod CreateResIntelligentScene;
#[cfg(feature = "CreateResJob")]
pub mod CreateResJob;
#[cfg(feature = "CreateResJobs")]
pub mod CreateResJobs;
#[cfg(feature = "CreateResOnlineInstance")]
pub mod CreateResOnlineInstance;
#[cfg(feature = "CreateResScene")]
pub mod CreateResScene;
#[cfg(feature = "CreateResWorkspace")]
pub mod CreateResWorkspace;
#[cfg(feature = "DeleteResDatasource")]
pub mod DeleteResDatasource;
#[cfg(feature = "DeleteResJob")]
pub mod DeleteResJob;
#[cfg(feature = "DeleteResOnlineInstance")]
pub mod DeleteResOnlineInstance;
#[cfg(feature = "DeleteResScene")]
pub mod DeleteResScene;
#[cfg(feature = "DeleteResWorkspace")]
pub mod DeleteResWorkspace;
#[cfg(feature = "ListResDatasources")]
pub mod ListResDatasources;
#[cfg(feature = "ListResEnterprises")]
pub mod ListResEnterprises;
#[cfg(feature = "ListResOnlineServiceDetails")]
pub mod ListResOnlineServiceDetails;
#[cfg(feature = "ListResResourceSpec")]
pub mod ListResResourceSpec;
#[cfg(feature = "ListResScenes")]
pub mod ListResScenes;
#[cfg(feature = "ListResWorkspaces")]
pub mod ListResWorkspaces;
#[cfg(feature = "ShowResDatasource")]
pub mod ShowResDatasource;
#[cfg(feature = "ShowResDatasourceWorkDetail")]
pub mod ShowResDatasourceWorkDetail;
#[cfg(feature = "ShowResJob")]
pub mod ShowResJob;
#[cfg(feature = "ShowResRecallSet")]
pub mod ShowResRecallSet;
#[cfg(feature = "ShowResScene")]
pub mod ShowResScene;
#[cfg(feature = "ShowResWrokspace")]
pub mod ShowResWrokspace;
#[cfg(feature = "StartResJob")]
pub mod StartResJob;
#[cfg(feature = "StartResSceneJobs")]
pub mod StartResSceneJobs;
#[cfg(feature = "UpdateResDatasource")]
pub mod UpdateResDatasource;
#[cfg(feature = "UpdateResDatastruct")]
pub mod UpdateResDatastruct;
#[cfg(feature = "UpdateResIntelligentScene")]
pub mod UpdateResIntelligentScene;
#[cfg(feature = "UpdateResJob")]
pub mod UpdateResJob;
#[cfg(feature = "UpdateResOnlineInstance")]
pub mod UpdateResOnlineInstance;
#[cfg(feature = "UpdateResScene")]
pub mod UpdateResScene;
#[cfg(feature = "UpdateResWorkspace")]
pub mod UpdateResWorkspace;
