#[cfg(feature = "AddBandwith")]
pub mod AddBandwith;
#[cfg(feature = "BatchCreateBandwiths")]
pub mod BatchCreateBandwiths;
#[cfg(feature = "CreateBandwiths")]
pub mod CreateBandwiths;
#[cfg(feature = "CreateEip")]
pub mod CreateEip;
#[cfg(feature = "CreateEipEiii")]
pub mod CreateEipEiii;
#[cfg(feature = "CreateFloatingips")]
pub mod CreateFloatingips;
#[cfg(feature = "CreateFloatingipsEii")]
pub mod CreateFloatingipsEii;
#[cfg(feature = "DeleteBandwith")]
pub mod DeleteBandwith;
#[cfg(feature = "DeleteEip")]
pub mod DeleteEip;
#[cfg(feature = "DeleteFloatingip")]
pub mod DeleteFloatingip;
#[cfg(feature = "DeleteFloatingipsEiiById")]
pub mod DeleteFloatingipsEiiById;
#[cfg(feature = "ListBandwidthInternal")]
pub mod ListBandwidthInternal;
#[cfg(feature = "ListBandwiths")]
pub mod ListBandwiths;
#[cfg(feature = "ListEip")]
pub mod ListEip;
#[cfg(feature = "ListFloatingip")]
pub mod ListFloatingip;
#[cfg(feature = "ListPublicIp")]
pub mod ListPublicIp;
#[cfg(feature = "RemoveBandwith")]
pub mod RemoveBandwith;
#[cfg(feature = "ShowBandwidthDetailInternal")]
pub mod ShowBandwidthDetailInternal;
#[cfg(feature = "ShowBandwith")]
pub mod ShowBandwith;
#[cfg(feature = "ShowEipByTypes")]
pub mod ShowEipByTypes;
#[cfg(feature = "ShowEipExt")]
pub mod ShowEipExt;
#[cfg(feature = "ShowEipListEiii")]
pub mod ShowEipListEiii;
#[cfg(feature = "ShowFloatingipDetails")]
pub mod ShowFloatingipDetails;
#[cfg(feature = "ShowFloatingipEiiById")]
pub mod ShowFloatingipEiiById;
#[cfg(feature = "ShowFloatingipsEii")]
pub mod ShowFloatingipsEii;
#[cfg(feature = "ShowFloatingipsListEii")]
pub mod ShowFloatingipsListEii;
#[cfg(feature = "ShowPublicIp")]
pub mod ShowPublicIp;
#[cfg(feature = "UpdateBandwidthInternal")]
pub mod UpdateBandwidthInternal;
#[cfg(feature = "UpdateEip")]
pub mod UpdateEip;
#[cfg(feature = "UpdateFloatingip")]
pub mod UpdateFloatingip;
#[cfg(feature = "UpdateVpcBandwith")]
pub mod UpdateVpcBandwith;
