#[cfg(feature = "BatchSaveAuth")]
pub mod BatchSaveAuth;
#[cfg(feature = "CreateAndUpdateExportConfig")]
pub mod CreateAndUpdateExportConfig;
#[cfg(feature = "CreateAndUpdatePermission")]
pub mod CreateAndUpdatePermission;
#[cfg(feature = "CreateDataConnection")]
pub mod CreateDataConnection;
#[cfg(feature = "CreateUserTag")]
pub mod CreateUserTag;
#[cfg(feature = "CreateWorkspace")]
pub mod CreateWorkspace;
#[cfg(feature = "DeleteDataConnectionByConnectionId")]
pub mod DeleteDataConnectionByConnectionId;
#[cfg(feature = "DeleteRule")]
pub mod DeleteRule;
#[cfg(feature = "DeleteUserTag")]
pub mod DeleteUserTag;
#[cfg(feature = "DeleteWorkspace")]
pub mod DeleteWorkspace;
#[cfg(feature = "ExportResourcePackage")]
pub mod ExportResourcePackage;
#[cfg(feature = "ImportResourcePackage")]
pub mod ImportResourcePackage;
#[cfg(feature = "ListAuthed")]
pub mod ListAuthed;
#[cfg(feature = "ListAuthProperties")]
pub mod ListAuthProperties;
#[cfg(feature = "ListCubeAndCatalogList")]
pub mod ListCubeAndCatalogList;
#[cfg(feature = "ListDataConnection")]
pub mod ListDataConnection;
#[cfg(feature = "ListInstances")]
pub mod ListInstances;
#[cfg(feature = "ListPermission")]
pub mod ListPermission;
#[cfg(feature = "ListPermissionConfig")]
pub mod ListPermissionConfig;
#[cfg(feature = "ListResources")]
pub mod ListResources;
#[cfg(feature = "ListUserTagHead")]
pub mod ListUserTagHead;
#[cfg(feature = "ListUserTagValue")]
pub mod ListUserTagValue;
#[cfg(feature = "ListWorkspaces")]
pub mod ListWorkspaces;
#[cfg(feature = "SaveDatasetForOpenApi")]
pub mod SaveDatasetForOpenApi;
#[cfg(feature = "SaveOrUpdateAuthProperties")]
pub mod SaveOrUpdateAuthProperties;
#[cfg(feature = "SaveUserTagValue")]
pub mod SaveUserTagValue;
#[cfg(feature = "ShowDataConnectionByConnectionId")]
pub mod ShowDataConnectionByConnectionId;
#[cfg(feature = "ShowDatasetDetail")]
pub mod ShowDatasetDetail;
#[cfg(feature = "ShowImportResourceTaskDetail")]
pub mod ShowImportResourceTaskDetail;
#[cfg(feature = "UpdateDataConnection")]
pub mod UpdateDataConnection;
#[cfg(feature = "UpdatePermissionConfig")]
pub mod UpdatePermissionConfig;
#[cfg(feature = "UpdateUserTag")]
pub mod UpdateUserTag;
#[cfg(feature = "UpdateWorkspace")]
pub mod UpdateWorkspace;
