#[cfg(feature = "AsyncInvokeInstance")]
pub mod AsyncInvokeInstance;
#[cfg(feature = "BatchResetInstance")]
pub mod BatchResetInstance;
#[cfg(feature = "BatchShowInstance")]
pub mod BatchShowInstance;
#[cfg(feature = "BatchShowSku")]
pub mod BatchShowSku;
#[cfg(feature = "CancelInstance")]
pub mod CancelInstance;
#[cfg(feature = "CreateInstance")]
pub mod CreateInstance;
#[cfg(feature = "DeleteInstance")]
pub mod DeleteInstance;
#[cfg(feature = "ExecuteInstanceAuthToken")]
pub mod ExecuteInstanceAuthToken;
#[cfg(feature = "ExecuteJob")]
pub mod ExecuteJob;
#[cfg(feature = "ProvisionInstance")]
pub mod ProvisionInstance;
#[cfg(feature = "SetVideo")]
pub mod SetVideo;
#[cfg(feature = "SyncInvokeInstance")]
pub mod SyncInvokeInstance;
