#[cfg(feature = "AsyncInvokeInstance")]
pub mod AsyncInvokeInstance;
#[cfg(feature = "BatchResetInstance")]
pub mod BatchResetInstance;
#[cfg(feature = "BatchShowInstance")]
pub mod BatchShowInstance;
#[cfg(feature = "ExecuteInstanceAuthToken")]
pub mod ExecuteInstanceAuthToken;
#[cfg(feature = "ExecuteJob")]
pub mod ExecuteJob;
#[cfg(feature = "SetVideo")]
pub mod SetVideo;
#[cfg(feature = "SyncInvokeInstance")]
pub mod SyncInvokeInstance;
