#[cfg(feature = "AsyncInvokeInstance")]
pub mod AsyncInvokeInstance;
#[cfg(feature = "BatchBackupInstances")]
pub mod BatchBackupInstances;
#[cfg(feature = "BatchPrepareInstances")]
pub mod BatchPrepareInstances;
#[cfg(feature = "BatchRebootInstance")]
pub mod BatchRebootInstance;
#[cfg(feature = "BatchResetInstance")]
pub mod BatchResetInstance;
#[cfg(feature = "BatchShowInstance")]
pub mod BatchShowInstance;
#[cfg(feature = "BatchShowSku")]
pub mod BatchShowSku;
#[cfg(feature = "CancelInstance")]
pub mod CancelInstance;
#[cfg(feature = "CreateInstance")]
pub mod CreateInstance;
#[cfg(feature = "DeleteInstance")]
pub mod DeleteInstance;
#[cfg(feature = "ExecuteInstanceAuthToken")]
pub mod ExecuteInstanceAuthToken;
#[cfg(feature = "ExecuteJob")]
pub mod ExecuteJob;
#[cfg(feature = "InstallApp")]
pub mod InstallApp;
#[cfg(feature = "ListInstances")]
pub mod ListInstances;
#[cfg(feature = "ProvisionInstance")]
pub mod ProvisionInstance;
#[cfg(feature = "SetVideo")]
pub mod SetVideo;
#[cfg(feature = "ShowProgress")]
pub mod ShowProgress;
#[cfg(feature = "StopInstancesSession")]
pub mod StopInstancesSession;
#[cfg(feature = "StopInstancesStreaming")]
pub mod StopInstancesStreaming;
#[cfg(feature = "SyncInvokeInstance")]
pub mod SyncInvokeInstance;
