[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
CreateCgw = []
CreateConnectionMonitor = []
CreateVgw = []
CreateVgwCertificate = []
CreateVpnConnection = []
DeleteCgw = []
DeleteConnectionMonitor = []
DeleteVgw = []
DeleteVpnConnection = []
ListAvailabilityZones = []
ListCgws = []
ListConnectionMonitors = []
ListVgws = []
ListVpnConnections = []
ShowCgw = []
ShowConnectionMonitor = []
ShowQuotasInfo = []
ShowVgw = []
ShowVpnConnection = []
ShowVpnGatewayCertificate = []
UpdateCgw = []
UpdateVgw = []
UpdateVgwCertificate = []
UpdateVpnConnection = []
full = ["CreateCgw", "CreateConnectionMonitor", "CreateVgw", "CreateVgwCertificate", "CreateVpnConnection", "DeleteCgw", "DeleteConnectionMonitor", "DeleteVgw", "DeleteVpnConnection", "ListAvailabilityZones", "ListCgws", "ListConnectionMonitors", "ListVgws", "ListVpnConnections", "ShowCgw", "ShowConnectionMonitor", "ShowQuotasInfo", "ShowVgw", "ShowVpnConnection", "ShowVpnGatewayCertificate", "UpdateCgw", "UpdateVgw", "UpdateVgwCertificate", "UpdateVpnConnection"]

[lib]
name = "huawei_cloud_api_definitions_VPN"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-VPN"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "0.1.1"
