[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddVpnUsersToGroup = []
BatchCreateResourceTags = []
BatchCreateVpnUsers = []
BatchDeleteResourceTags = []
BatchDeleteVpnUsers = []
CheckClientCaCertificate = []
CountResourcesByTags = []
CreateCgw = []
CreateConnectionMonitor = []
CreateVgw = []
CreateVgwCertificate = []
CreateVpnAccessPolicy = []
CreateVpnConnection = []
CreateVpnServer = []
CreateVpnUser = []
CreateVpnUserGroup = []
DeleteCgw = []
DeleteClientCa = []
DeleteConnectionMonitor = []
DeleteP2cVgwConnection = []
DeleteVgw = []
DeleteVpnAccessPolicy = []
DeleteVpnConnection = []
DeleteVpnConnectionsLogConfig = []
DeleteVpnUser = []
DeleteVpnUserGroup = []
ExportClientConfig = []
ImportClientCa = []
ListAvailabilityZones = []
ListCgws = []
ListConnectionMonitors = []
ListExtendedAvailabilityZones = []
ListP2cVgwAvailabilityZones = []
ListP2cVgwConnections = []
ListP2cVgws = []
ListProjectTags = []
ListResourcesByTags = []
ListVgws = []
ListVpnAccessPolicies = []
ListVpnConnections = []
ListVpnServersByProject = []
ListVpnServersByVgw = []
ListVpnUserGroups = []
ListVpnUsers = []
ListVpnUsersInGroup = []
RemoveVpnUsersFromGroup = []
ResetVpnUserPassword = []
ShowCgw = []
ShowClientCa = []
ShowConnectionMonitor = []
ShowP2cVgw = []
ShowQuotasInfo = []
ShowResourceTags = []
ShowVgw = []
ShowVpnAccessPolicy = []
ShowVpnConnection = []
ShowVpnConnectionLog = []
ShowVpnConnectionsLogConfig = []
ShowVpnGatewayCertificate = []
ShowVpnGatewayRoutingTable = []
ShowVpnUser = []
ShowVpnUserGroup = []
UpdateCgw = []
UpdateClientCa = []
UpdateP2cVgw = []
UpdatePostpaidVgwSpecification = []
UpdateVgw = []
UpdateVgwCertificate = []
UpdateVpnAccessPolicy = []
UpdateVpnConnection = []
UpdateVpnConnectionsLogConfig = []
UpdateVpnServer = []
UpdateVpnUser = []
UpdateVpnUserGroup = []
UpdateVpnUserPassword = []
full = ["AddVpnUsersToGroup", "BatchCreateResourceTags", "BatchCreateVpnUsers", "BatchDeleteResourceTags", "BatchDeleteVpnUsers", "CheckClientCaCertificate", "CountResourcesByTags", "CreateCgw", "CreateConnectionMonitor", "CreateVgw", "CreateVgwCertificate", "CreateVpnAccessPolicy", "CreateVpnConnection", "CreateVpnServer", "CreateVpnUser", "CreateVpnUserGroup", "DeleteCgw", "DeleteClientCa", "DeleteConnectionMonitor", "DeleteP2cVgwConnection", "DeleteVgw", "DeleteVpnAccessPolicy", "DeleteVpnConnection", "DeleteVpnConnectionsLogConfig", "DeleteVpnUser", "DeleteVpnUserGroup", "ExportClientConfig", "ImportClientCa", "ListAvailabilityZones", "ListCgws", "ListConnectionMonitors", "ListExtendedAvailabilityZones", "ListP2cVgwAvailabilityZones", "ListP2cVgwConnections", "ListP2cVgws", "ListProjectTags", "ListResourcesByTags", "ListVgws", "ListVpnAccessPolicies", "ListVpnConnections", "ListVpnServersByProject", "ListVpnServersByVgw", "ListVpnUserGroups", "ListVpnUsers", "ListVpnUsersInGroup", "RemoveVpnUsersFromGroup", "ResetVpnUserPassword", "ShowCgw", "ShowClientCa", "ShowConnectionMonitor", "ShowP2cVgw", "ShowQuotasInfo", "ShowResourceTags", "ShowVgw", "ShowVpnAccessPolicy", "ShowVpnConnection", "ShowVpnConnectionLog", "ShowVpnConnectionsLogConfig", "ShowVpnGatewayCertificate", "ShowVpnGatewayRoutingTable", "ShowVpnUser", "ShowVpnUserGroup", "UpdateCgw", "UpdateClientCa", "UpdateP2cVgw", "UpdatePostpaidVgwSpecification", "UpdateVgw", "UpdateVgwCertificate", "UpdateVpnAccessPolicy", "UpdateVpnConnection", "UpdateVpnConnectionsLogConfig", "UpdateVpnServer", "UpdateVpnUser", "UpdateVpnUserGroup", "UpdateVpnUserPassword"]

[lib]
name = "huawei_cloud_api_definitions_VPN"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-VPN"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
