[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
BatchCreateOrDeleteTags = []
BatchDeleteInstances = []
BatchShowNodesInformation = []
BatchStopMigrationTasks = []
ChangeMasterStandby = []
CopyInstance = []
CreateAclAccount = []
CreateAutoExpireScanTask = []
CreateBigkeyScanTask = []
CreateCustomTemplate = []
CreateDiagnosisTask = []
CreateHotkeyScanTask = []
CreateInstance = []
CreateMigrationTask = []
CreateOnlineMigrationTask = []
CreateRedislog = []
CreateRedislogDownloadLink = []
CreateResizeOrder = []
DeleteAclAccount = []
DeleteBackgroundTask = []
DeleteBackupFile = []
DeleteBigkeyScanTask = []
DeleteCenterTask = []
DeleteConfigTemplate = []
DeleteDiagnosisTask = []
DeleteHotkeyScanTask = []
DeleteIpFromDomainName = []
DeleteMigrationTask = []
DeleteSingleInstance = []
DownloadSslCert = []
ExchangeInstanceIp = []
ExecuteClusterSwitchover = []
ExecuteCommandMobilization = []
ExportExcelJob = []
ExportInstancesTask = []
ListAclAccounts = []
ListAvailableZones = []
ListBackgroundTask = []
ListBackupFileLinks = []
ListBackupRecords = []
ListBigkeyScanTasks = []
ListCenterTask = []
ListConfigHistories = []
ListConfigTemplates = []
ListConfigurations = []
ListDiagnosisTasks = []
ListFlavors = []
ListGroupReplicationInfo = []
ListHotKeyScanTasks = []
ListInstanceOperations = []
ListInstances = []
ListMaintenanceWindows = []
ListMigrationTask = []
ListMigrationTaskLogs = []
ListMonitoredObjects = []
ListMonitoredObjectsOfInstance = []
ListNumberOfInstancesInDifferentStatus = []
ListRedislog = []
ListRestoreRecords = []
ListSlowlog = []
ListStatisticsOfRunningInstances = []
ListTagsOfTenant = []
LoginWebCli = []
LogoffWebCli = []
ResetAclAccountPassWord = []
ResetPassword = []
ResizeInstance = []
RestartOrFlushInstances = []
RestoreInstance = []
ScanExpireKey = []
SetOnlineMigrationTask = []
ShowBackgroundTaskProgress = []
ShowBigkeyAutoscanConfig = []
ShowBigkeyScanTaskDetails = []
ShowConfigHistoryDetail = []
ShowConfigTemplate = []
ShowDiagnosisTaskDetails = []
ShowExpireAutoScanConfig = []
ShowExpireKeyScanInfo = []
ShowHotkeyAutoscanConfig = []
ShowHotkeyTaskDetails = []
ShowInstance = []
ShowInstanceSslDetail = []
ShowIpWhitelist = []
ShowJobInfo = []
ShowMigrationTask = []
ShowMigrationTaskStats = []
ShowNodesInformation = []
ShowQuotaOfTenant = []
ShowReplicationStates = []
ShowTags = []
StartInstanceResizeCheckJob = []
StopMigrationTask = []
StopMigrationTaskSync = []
UpdateAclAccount = []
UpdateAclAccountPassWord = []
UpdateAclAccountRemark = []
UpdateBigkeyAutoscanConfig = []
UpdateClientIpTransparentTransmission = []
UpdateConfigTemplate = []
full = ["BatchCreateOrDeleteTags", "BatchDeleteInstances", "BatchShowNodesInformation", "BatchStopMigrationTasks", "ChangeMasterStandby", "CopyInstance", "CreateAclAccount", "CreateAutoExpireScanTask", "CreateBigkeyScanTask", "CreateCustomTemplate", "CreateDiagnosisTask", "CreateHotkeyScanTask", "CreateInstance", "CreateMigrationTask", "CreateOnlineMigrationTask", "CreateRedislog", "CreateRedislogDownloadLink", "CreateResizeOrder", "DeleteAclAccount", "DeleteBackgroundTask", "DeleteBackupFile", "DeleteBigkeyScanTask", "DeleteCenterTask", "DeleteConfigTemplate", "DeleteDiagnosisTask", "DeleteHotkeyScanTask", "DeleteIpFromDomainName", "DeleteMigrationTask", "DeleteSingleInstance", "DownloadSslCert", "ExchangeInstanceIp", "ExecuteClusterSwitchover", "ExecuteCommandMobilization", "ExportExcelJob", "ExportInstancesTask", "ListAclAccounts", "ListAvailableZones", "ListBackgroundTask", "ListBackupFileLinks", "ListBackupRecords", "ListBigkeyScanTasks", "ListCenterTask", "ListConfigHistories", "ListConfigTemplates", "ListConfigurations", "ListDiagnosisTasks", "ListFlavors", "ListGroupReplicationInfo", "ListHotKeyScanTasks", "ListInstanceOperations", "ListInstances", "ListMaintenanceWindows", "ListMigrationTask", "ListMigrationTaskLogs", "ListMonitoredObjects", "ListMonitoredObjectsOfInstance", "ListNumberOfInstancesInDifferentStatus", "ListRedislog", "ListRestoreRecords", "ListSlowlog", "ListStatisticsOfRunningInstances", "ListTagsOfTenant", "LoginWebCli", "LogoffWebCli", "ResetAclAccountPassWord", "ResetPassword", "ResizeInstance", "RestartOrFlushInstances", "RestoreInstance", "ScanExpireKey", "SetOnlineMigrationTask", "ShowBackgroundTaskProgress", "ShowBigkeyAutoscanConfig", "ShowBigkeyScanTaskDetails", "ShowConfigHistoryDetail", "ShowConfigTemplate", "ShowDiagnosisTaskDetails", "ShowExpireAutoScanConfig", "ShowExpireKeyScanInfo", "ShowHotkeyAutoscanConfig", "ShowHotkeyTaskDetails", "ShowInstance", "ShowInstanceSslDetail", "ShowIpWhitelist", "ShowJobInfo", "ShowMigrationTask", "ShowMigrationTaskStats", "ShowNodesInformation", "ShowQuotaOfTenant", "ShowReplicationStates", "ShowTags", "StartInstanceResizeCheckJob", "StopMigrationTask", "StopMigrationTaskSync", "UpdateAclAccount", "UpdateAclAccountPassWord", "UpdateAclAccountRemark", "UpdateBigkeyAutoscanConfig", "UpdateClientIpTransparentTransmission", "UpdateConfigTemplate"]

[lib]
name = "huawei_cloud_api_definitions_DCS"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-DCS"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
