[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AutoRenewalResources = []
CancelAutoRenewalResources = []
CancelCustomerOrder = []
CancelResourcesSubscription = []
ChangeEnterpriseRealnameAuthentication = []
CheckUserIdentity = []
ClaimEnterpriseMultiAccountCoupon = []
CreateEnterpriseProjectAuth = []
CreateEnterpriseRealnameAuthentication = []
CreatePartnerCoupons = []
CreatePersonalRealnameAuth = []
CreateSubCustomer = []
CreateSubEnterpriseAccount = []
ListCities = []
ListConsumeSubCustomers = []
ListConversions = []
ListCosts = []
ListCounties = []
ListCouponQuotasRecords = []
ListCustomerAccountChangeRecords = []
ListCustomerBillsFeeRecords = []
ListCustomerBillsMonthlyBreakDown = []
ListCustomerOnDemandResources = []
ListCustomerOrders = []
ListCustomersBalancesDetail = []
ListCustomerselfResourceRecordDetails = []
ListCustomerselfResourceRecords = []
ListEnterpriseMultiAccount = []
ListEnterpriseOrganizations = []
ListEnterpriseSubCustomers = []
ListFreeResourceInfos = []
ListFreeResourceUsages = []
ListFreeResourcesUsageRecords = []
ListIncentiveDiscountPolicies = []
ListIndirectPartners = []
ListIssuedCouponQuotas = []
ListIssuedPartnerCoupons = []
ListMeasureUnits = []
ListMultiAccountRetrieveCoupons = []
ListMultiAccountTransferCoupons = []
ListOnDemandResourceRatings = []
ListOrderCouponsByOrderId = []
ListOrderDiscounts = []
ListPartnerAccountChangeRecords = []
ListPartnerAdjustRecords = []
ListPartnerBalances = []
ListPartnerCouponsRecord = []
ListPayPerUseCustomerResources = []
ListProvinces = []
ListQuotaCoupons = []
ListRateOnPeriodDetail = []
ListRenewRateOnPeriod = []
ListResourceTypes = []
ListResourceUsage = []
ListResourceUsageSummary = []
ListServiceResources = []
ListServiceTypes = []
ListStoredValueCards = []
ListSubCustomerBillDetail = []
ListSubCustomerCoupons = []
ListSubCustomerNewTag = []
ListSubCustomers = []
ListSubcustomerMonthlyBills = []
ListUsageTypes = []
PayOrders = []
ReclaimCouponQuotas = []
ReclaimEnterpriseMultiAccountCoupon = []
ReclaimIndirectPartnerAccount = []
ReclaimPartnerCoupons = []
ReclaimSubEnterpriseAmount = []
ReclaimToPartnerAccount = []
RenewalResources = []
SendSmsVerificationCode = []
SendVerificationMessageCode = []
SetResourcesRenewConfig = []
ShowCustomerAccountBalances = []
ShowCustomerMonthlySum = []
ShowCustomerOrderDetails = []
ShowMultiAccountTransferAmount = []
ShowRealnameAuthenticationReviewResult = []
ShowRefundOrderDetails = []
UpdateCouponQuotas = []
UpdateCustomerAccountAmount = []
UpdateIndirectPartnerAccount = []
UpdatePeriodToOnDemand = []
UpdateSubEnterpriseAmount = []
full = ["AutoRenewalResources", "CancelAutoRenewalResources", "CancelCustomerOrder", "CancelResourcesSubscription", "ChangeEnterpriseRealnameAuthentication", "CheckUserIdentity", "ClaimEnterpriseMultiAccountCoupon", "CreateEnterpriseProjectAuth", "CreateEnterpriseRealnameAuthentication", "CreatePartnerCoupons", "CreatePersonalRealnameAuth", "CreateSubCustomer", "CreateSubEnterpriseAccount", "ListCities", "ListConsumeSubCustomers", "ListConversions", "ListCosts", "ListCounties", "ListCouponQuotasRecords", "ListCustomerAccountChangeRecords", "ListCustomerBillsFeeRecords", "ListCustomerBillsMonthlyBreakDown", "ListCustomerOnDemandResources", "ListCustomerOrders", "ListCustomersBalancesDetail", "ListCustomerselfResourceRecordDetails", "ListCustomerselfResourceRecords", "ListEnterpriseMultiAccount", "ListEnterpriseOrganizations", "ListEnterpriseSubCustomers", "ListFreeResourceInfos", "ListFreeResourcesUsageRecords", "ListFreeResourceUsages", "ListIncentiveDiscountPolicies", "ListIndirectPartners", "ListIssuedCouponQuotas", "ListIssuedPartnerCoupons", "ListMeasureUnits", "ListMultiAccountRetrieveCoupons", "ListMultiAccountTransferCoupons", "ListOnDemandResourceRatings", "ListOrderCouponsByOrderId", "ListOrderDiscounts", "ListPartnerAccountChangeRecords", "ListPartnerAdjustRecords", "ListPartnerBalances", "ListPartnerCouponsRecord", "ListPayPerUseCustomerResources", "ListProvinces", "ListQuotaCoupons", "ListRateOnPeriodDetail", "ListRenewRateOnPeriod", "ListResourceTypes", "ListResourceUsage", "ListResourceUsageSummary", "ListServiceResources", "ListServiceTypes", "ListStoredValueCards", "ListSubCustomerBillDetail", "ListSubCustomerCoupons", "ListSubcustomerMonthlyBills", "ListSubCustomerNewTag", "ListSubCustomers", "ListUsageTypes", "PayOrders", "ReclaimCouponQuotas", "ReclaimEnterpriseMultiAccountCoupon", "ReclaimIndirectPartnerAccount", "ReclaimPartnerCoupons", "ReclaimSubEnterpriseAmount", "ReclaimToPartnerAccount", "RenewalResources", "SendSmsVerificationCode", "SendVerificationMessageCode", "SetResourcesRenewConfig", "ShowCustomerAccountBalances", "ShowCustomerMonthlySum", "ShowCustomerOrderDetails", "ShowMultiAccountTransferAmount", "ShowRealnameAuthenticationReviewResult", "ShowRefundOrderDetails", "UpdateCouponQuotas", "UpdateCustomerAccountAmount", "UpdateIndirectPartnerAccount", "UpdatePeriodToOnDemand", "UpdateSubEnterpriseAmount"]

[lib]
name = "huawei_cloud_api_definitions_BSS"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-BSS"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
