#[cfg(feature = "AssociateAlias")]
pub mod AssociateAlias;
#[cfg(feature = "BatchCreateKmsTags")]
pub mod BatchCreateKmsTags;
#[cfg(feature = "CancelGrant")]
pub mod CancelGrant;
#[cfg(feature = "CancelKeyDeletion")]
pub mod CancelKeyDeletion;
#[cfg(feature = "CancelSelfGrant")]
pub mod CancelSelfGrant;
#[cfg(feature = "CreateAlias")]
pub mod CreateAlias;
#[cfg(feature = "CreateDatakey")]
pub mod CreateDatakey;
#[cfg(feature = "CreateDatakeyWithoutPlaintext")]
pub mod CreateDatakeyWithoutPlaintext;
#[cfg(feature = "CreateEcDatakeyPair")]
pub mod CreateEcDatakeyPair;
#[cfg(feature = "CreateGrant")]
pub mod CreateGrant;
#[cfg(feature = "CreateKey")]
pub mod CreateKey;
#[cfg(feature = "CreateKeyStore")]
pub mod CreateKeyStore;
#[cfg(feature = "CreateKmsTag")]
pub mod CreateKmsTag;
#[cfg(feature = "CreateParametersForImport")]
pub mod CreateParametersForImport;
#[cfg(feature = "CreatePin")]
pub mod CreatePin;
#[cfg(feature = "CreateRandom")]
pub mod CreateRandom;
#[cfg(feature = "CreateRsaDatakeyPair")]
pub mod CreateRsaDatakeyPair;
#[cfg(feature = "DecryptData")]
pub mod DecryptData;
#[cfg(feature = "DecryptDatakey")]
pub mod DecryptDatakey;
#[cfg(feature = "DeleteAlias")]
pub mod DeleteAlias;
#[cfg(feature = "DeleteImportedKeyMaterial")]
pub mod DeleteImportedKeyMaterial;
#[cfg(feature = "DeleteKey")]
pub mod DeleteKey;
#[cfg(feature = "DeleteKeyStore")]
pub mod DeleteKeyStore;
#[cfg(feature = "DeleteTag")]
pub mod DeleteTag;
#[cfg(feature = "DisableKey")]
pub mod DisableKey;
#[cfg(feature = "DisableKeyRotation")]
pub mod DisableKeyRotation;
#[cfg(feature = "DisableKeyStore")]
pub mod DisableKeyStore;
#[cfg(feature = "EnableKey")]
pub mod EnableKey;
#[cfg(feature = "EnableKeyRotation")]
pub mod EnableKeyRotation;
#[cfg(feature = "EnableKeyStore")]
pub mod EnableKeyStore;
#[cfg(feature = "EncryptData")]
pub mod EncryptData;
#[cfg(feature = "EncryptDatakey")]
pub mod EncryptDatakey;
#[cfg(feature = "GenerateMac")]
pub mod GenerateMac;
#[cfg(feature = "ImportKeyMaterial")]
pub mod ImportKeyMaterial;
#[cfg(feature = "ListAliases")]
pub mod ListAliases;
#[cfg(feature = "ListGrants")]
pub mod ListGrants;
#[cfg(feature = "ListKeyDetail")]
pub mod ListKeyDetail;
#[cfg(feature = "ListKeys")]
pub mod ListKeys;
#[cfg(feature = "ListKeyStores")]
pub mod ListKeyStores;
#[cfg(feature = "ListKmsByTags")]
pub mod ListKmsByTags;
#[cfg(feature = "ListKmsTags")]
pub mod ListKmsTags;
#[cfg(feature = "ListRetirableGrants")]
pub mod ListRetirableGrants;
#[cfg(feature = "ListSupportRegions")]
pub mod ListSupportRegions;
#[cfg(feature = "ReplicateKey")]
pub mod ReplicateKey;
#[cfg(feature = "ShowKeyRotationStatus")]
pub mod ShowKeyRotationStatus;
#[cfg(feature = "ShowKeyStore")]
pub mod ShowKeyStore;
#[cfg(feature = "ShowKmsTags")]
pub mod ShowKmsTags;
#[cfg(feature = "ShowPublicKey")]
pub mod ShowPublicKey;
#[cfg(feature = "ShowUserInstances")]
pub mod ShowUserInstances;
#[cfg(feature = "ShowUserQuotas")]
pub mod ShowUserQuotas;
#[cfg(feature = "ShowVersion")]
pub mod ShowVersion;
#[cfg(feature = "ShowVersions")]
pub mod ShowVersions;
#[cfg(feature = "Sign")]
pub mod Sign;
#[cfg(feature = "UpdateKeyAlias")]
pub mod UpdateKeyAlias;
#[cfg(feature = "UpdateKeyDescription")]
pub mod UpdateKeyDescription;
#[cfg(feature = "UpdateKeyRotationInterval")]
pub mod UpdateKeyRotationInterval;
#[cfg(feature = "UpdatePrimaryRegion")]
pub mod UpdatePrimaryRegion;
#[cfg(feature = "ValidateSignature")]
pub mod ValidateSignature;
#[cfg(feature = "VerifyMac")]
pub mod VerifyMac;
