[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
ApplyCentralNetworkPolicy = []
AssociateBandwidthPackage = []
BatchCreateDeleteTags = []
CreateAuthorisation = []
CreateBandwidthPackage = []
CreateCentralNetwork = []
CreateCentralNetworkGdgwAttachment = []
CreateCentralNetworkPolicy = []
CreateCloudConnection = []
CreateInterRegionBandwidth = []
CreateNetworkInstance = []
CreateTag = []
DeleteAuthorisation = []
DeleteBandwidthPackage = []
DeleteCentralNetwork = []
DeleteCentralNetworkAttachment = []
DeleteCentralNetworkPolicy = []
DeleteCloudConnection = []
DeleteInterRegionBandwidth = []
DeleteNetworkInstance = []
DeleteTag = []
DisassociateBandwidthPackage = []
ListAuthorisations = []
ListBandwidthPackageTags = []
ListBandwidthPackages = []
ListBandwidthPackagesByTags = []
ListCentralNetworkAttachments = []
ListCentralNetworkCapabilities = []
ListCentralNetworkConnections = []
ListCentralNetworkGdgwAttachments = []
ListCentralNetworkPolicies = []
ListCentralNetworkPolicyChangeSet = []
ListCentralNetworkQuotas = []
ListCentralNetworkTags = []
ListCentralNetworks = []
ListCloudConnectionQuotas = []
ListCloudConnectionRoutes = []
ListCloudConnectionTags = []
ListCloudConnections = []
ListCloudConnectionsByTags = []
ListDomainTags = []
ListInterRegionBandwidths = []
ListNetworkInstances = []
ListPermissions = []
ListResourceByFilterTag = []
ListTags = []
ShowBandwidthPackage = []
ShowCentralNetwork = []
ShowCentralNetworkGdgwAttachment = []
ShowCloudConnection = []
ShowCloudConnectionRoutes = []
ShowInterRegionBandwidth = []
ShowNetworkInstance = []
TagBandwidthPackage = []
TagCentralNetwork = []
TagCloudConnection = []
UntagBandwidthPackage = []
UntagCentralNetwork = []
UntagCloudConnection = []
UpdateAuthorisation = []
UpdateBandwidthPackage = []
UpdateCentralNetwork = []
UpdateCentralNetworkConnection = []
UpdateCentralNetworkGdgwAttachment = []
UpdateCloudConnection = []
UpdateInterRegionBandwidth = []
UpdateNetworkInstance = []
full = ["ApplyCentralNetworkPolicy", "AssociateBandwidthPackage", "BatchCreateDeleteTags", "CreateAuthorisation", "CreateBandwidthPackage", "CreateCentralNetwork", "CreateCentralNetworkGdgwAttachment", "CreateCentralNetworkPolicy", "CreateCloudConnection", "CreateInterRegionBandwidth", "CreateNetworkInstance", "CreateTag", "DeleteAuthorisation", "DeleteBandwidthPackage", "DeleteCentralNetwork", "DeleteCentralNetworkAttachment", "DeleteCentralNetworkPolicy", "DeleteCloudConnection", "DeleteInterRegionBandwidth", "DeleteNetworkInstance", "DeleteTag", "DisassociateBandwidthPackage", "ListAuthorisations", "ListBandwidthPackages", "ListBandwidthPackagesByTags", "ListBandwidthPackageTags", "ListCentralNetworkAttachments", "ListCentralNetworkCapabilities", "ListCentralNetworkConnections", "ListCentralNetworkGdgwAttachments", "ListCentralNetworkPolicies", "ListCentralNetworkPolicyChangeSet", "ListCentralNetworkQuotas", "ListCentralNetworks", "ListCentralNetworkTags", "ListCloudConnectionQuotas", "ListCloudConnectionRoutes", "ListCloudConnections", "ListCloudConnectionsByTags", "ListCloudConnectionTags", "ListDomainTags", "ListInterRegionBandwidths", "ListNetworkInstances", "ListPermissions", "ListResourceByFilterTag", "ListTags", "ShowBandwidthPackage", "ShowCentralNetwork", "ShowCentralNetworkGdgwAttachment", "ShowCloudConnection", "ShowCloudConnectionRoutes", "ShowInterRegionBandwidth", "ShowNetworkInstance", "TagBandwidthPackage", "TagCentralNetwork", "TagCloudConnection", "UntagBandwidthPackage", "UntagCentralNetwork", "UntagCloudConnection", "UpdateAuthorisation", "UpdateBandwidthPackage", "UpdateCentralNetwork", "UpdateCentralNetworkConnection", "UpdateCentralNetworkGdgwAttachment", "UpdateCloudConnection", "UpdateInterRegionBandwidth", "UpdateNetworkInstance"]

[lib]
name = "huawei_cloud_api_definitions_CC"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-CC"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "0.1.0"
