#[cfg(feature = "AddPublicipsIntoSharedBandwidth")]
pub mod AddPublicipsIntoSharedBandwidth;
#[cfg(feature = "AssociatePublicips")]
pub mod AssociatePublicips;
#[cfg(feature = "AttachBatchPublicIp")]
pub mod AttachBatchPublicIp;
#[cfg(feature = "AttachShareBandwidth")]
pub mod AttachShareBandwidth;
#[cfg(feature = "BatchCreatePublicips")]
pub mod BatchCreatePublicips;
#[cfg(feature = "BatchCreatePublicipTags")]
pub mod BatchCreatePublicipTags;
#[cfg(feature = "BatchCreateSharedBandwidths")]
pub mod BatchCreateSharedBandwidths;
#[cfg(feature = "BatchDeletePublicIp")]
pub mod BatchDeletePublicIp;
#[cfg(feature = "BatchDeletePublicipTags")]
pub mod BatchDeletePublicipTags;
#[cfg(feature = "BatchDisassociatePublicips")]
pub mod BatchDisassociatePublicips;
#[cfg(feature = "BatchModifyBandwidth")]
pub mod BatchModifyBandwidth;
#[cfg(feature = "ChangeBandwidthToPeriod")]
pub mod ChangeBandwidthToPeriod;
#[cfg(feature = "ChangePublicipToPeriod")]
pub mod ChangePublicipToPeriod;
#[cfg(feature = "CountEipAvailableResources")]
pub mod CountEipAvailableResources;
#[cfg(feature = "CountPublicIp")]
pub mod CountPublicIp;
#[cfg(feature = "CountPublicIpInstance")]
pub mod CountPublicIpInstance;
#[cfg(feature = "CreatePrePaidPublicip")]
pub mod CreatePrePaidPublicip;
#[cfg(feature = "CreatePublicip")]
pub mod CreatePublicip;
#[cfg(feature = "CreatePublicipTag")]
pub mod CreatePublicipTag;
#[cfg(feature = "CreateSharedBandwidth")]
pub mod CreateSharedBandwidth;
#[cfg(feature = "DeletePublicip")]
pub mod DeletePublicip;
#[cfg(feature = "DeletePublicipTag")]
pub mod DeletePublicipTag;
#[cfg(feature = "DeleteSharedBandwidth")]
pub mod DeleteSharedBandwidth;
#[cfg(feature = "DetachBatchPublicIp")]
pub mod DetachBatchPublicIp;
#[cfg(feature = "DetachShareBandwidth")]
pub mod DetachShareBandwidth;
#[cfg(feature = "DisableNat64")]
pub mod DisableNat64;
#[cfg(feature = "DisassociatePublicips")]
pub mod DisassociatePublicips;
#[cfg(feature = "EnableNat64")]
pub mod EnableNat64;
#[cfg(feature = "ListBandwidth")]
pub mod ListBandwidth;
#[cfg(feature = "ListBandwidthPkg")]
pub mod ListBandwidthPkg;
#[cfg(feature = "ListBandwidths")]
pub mod ListBandwidths;
#[cfg(feature = "ListBandwidthsLimit")]
pub mod ListBandwidthsLimit;
#[cfg(feature = "ListCommonPools")]
pub mod ListCommonPools;
#[cfg(feature = "ListEipBandwidths")]
pub mod ListEipBandwidths;
#[cfg(feature = "ListPublicipPool")]
pub mod ListPublicipPool;
#[cfg(feature = "ListPublicips")]
pub mod ListPublicips;
#[cfg(feature = "ListPublicipsByTags")]
pub mod ListPublicipsByTags;
#[cfg(feature = "ListPublicipTags")]
pub mod ListPublicipTags;
#[cfg(feature = "ListQuotas")]
pub mod ListQuotas;
#[cfg(feature = "ListShareBandwidthTypes")]
pub mod ListShareBandwidthTypes;
#[cfg(feature = "NeutronCreateFloatingIp")]
pub mod NeutronCreateFloatingIp;
#[cfg(feature = "NeutronDeleteFloatingIp")]
pub mod NeutronDeleteFloatingIp;
#[cfg(feature = "NeutronListFloatingIps")]
pub mod NeutronListFloatingIps;
#[cfg(feature = "NeutronShowFloatingIp")]
pub mod NeutronShowFloatingIp;
#[cfg(feature = "NeutronUpdateFloatingIp")]
pub mod NeutronUpdateFloatingIp;
#[cfg(feature = "RemovePublicipsFromSharedBandwidth")]
pub mod RemovePublicipsFromSharedBandwidth;
#[cfg(feature = "ShowBandwidth")]
pub mod ShowBandwidth;
#[cfg(feature = "ShowPublicip")]
pub mod ShowPublicip;
#[cfg(feature = "ShowPublicipPool")]
pub mod ShowPublicipPool;
#[cfg(feature = "ShowPublicipTags")]
pub mod ShowPublicipTags;
#[cfg(feature = "ShowPublicIpType")]
pub mod ShowPublicIpType;
#[cfg(feature = "ShowResourcesJobDetail")]
pub mod ShowResourcesJobDetail;
#[cfg(feature = "UpdateBandwidth")]
pub mod UpdateBandwidth;
#[cfg(feature = "UpdatePrePaidBandwidth")]
pub mod UpdatePrePaidBandwidth;
#[cfg(feature = "UpdatePublicip")]
pub mod UpdatePublicip;
