[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
BatchCreateOrDeleteRabbitMqTag = []
BatchRestartOrDeleteInstances = []
CreatePostPaidInstanceByEngine = []
DeleteBackgroundTask = []
DeleteInstance = []
ListAvailableZones = []
ListBackgroundTasks = []
ListEngineProducts = []
ListInstancesDetails = []
ListPlugins = []
ResetPassword = []
ResizeEngineInstance = []
ShowBackgroundTask = []
ShowCesHierarchy = []
ShowEngineInstanceExtendProductInfo = []
ShowInstance = []
ShowMaintainWindows = []
ShowRabbitMqProjectTags = []
ShowRabbitMqTags = []
UpdateInstance = []
UpdatePlugins = []
full = ["BatchCreateOrDeleteRabbitMqTag", "BatchRestartOrDeleteInstances", "CreatePostPaidInstanceByEngine", "DeleteBackgroundTask", "DeleteInstance", "ListAvailableZones", "ListBackgroundTasks", "ListEngineProducts", "ListInstancesDetails", "ListPlugins", "ResetPassword", "ResizeEngineInstance", "ShowBackgroundTask", "ShowCesHierarchy", "ShowEngineInstanceExtendProductInfo", "ShowInstance", "ShowMaintainWindows", "ShowRabbitMqProjectTags", "ShowRabbitMqTags", "UpdateInstance", "UpdatePlugins"]

[lib]
name = "huawei_cloud_api_definitions_RabbitMQ"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-RabbitMQ"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "0.1.1"
