[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
BatchCreateOrDeleteRabbitMqTag = []
BatchDeleteExchanges = []
BatchDeleteQueues = []
BatchDeleteVhosts = []
BatchRestartOrDeleteInstances = []
CreateBinding = []
CreateExchange = []
CreatePostPaidInstanceByEngine = []
CreateQueue = []
CreateUser = []
CreateVhost = []
DeleteBackgroundTask = []
DeleteBinding = []
DeleteInstance = []
DeleteQueueInfo = []
DeleteUser = []
ListAvailableZones = []
ListBackgroundTasks = []
ListBindings = []
ListEngineProducts = []
ListExchanges = []
ListInstancesDetails = []
ListPlugins = []
ListQueues = []
ListUser = []
ListVhosts = []
ResetPassword = []
ResizeEngineInstance = []
ShowBackgroundTask = []
ShowCesHierarchy = []
ShowEngineInstanceExtendProductInfo = []
ShowInstance = []
ShowMaintainWindows = []
ShowQueueDetails = []
ShowRabbitMqProjectTags = []
ShowRabbitMqTags = []
UpdateInstance = []
UpdatePlugins = []
UpdateUser = []
full = ["BatchCreateOrDeleteRabbitMqTag", "BatchDeleteExchanges", "BatchDeleteQueues", "BatchDeleteVhosts", "BatchRestartOrDeleteInstances", "CreateBinding", "CreateExchange", "CreatePostPaidInstanceByEngine", "CreateQueue", "CreateUser", "CreateVhost", "DeleteBackgroundTask", "DeleteBinding", "DeleteInstance", "DeleteQueueInfo", "DeleteUser", "ListAvailableZones", "ListBackgroundTasks", "ListBindings", "ListEngineProducts", "ListExchanges", "ListInstancesDetails", "ListPlugins", "ListQueues", "ListUser", "ListVhosts", "ResetPassword", "ResizeEngineInstance", "ShowBackgroundTask", "ShowCesHierarchy", "ShowEngineInstanceExtendProductInfo", "ShowInstance", "ShowMaintainWindows", "ShowQueueDetails", "ShowRabbitMqProjectTags", "ShowRabbitMqTags", "UpdateInstance", "UpdatePlugins", "UpdateUser"]

[lib]
name = "huawei_cloud_api_definitions_RabbitMQ"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-RabbitMQ"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
