#[cfg(feature = "AddNetworkSwitchPolicy")]
pub mod AddNetworkSwitchPolicy;
#[cfg(feature = "BatchSetAttributes")]
pub mod BatchSetAttributes;
#[cfg(feature = "BatchSetTags")]
pub mod BatchSetTags;
#[cfg(feature = "CreateAttribute")]
pub mod CreateAttribute;
#[cfg(feature = "CreateTag")]
pub mod CreateTag;
#[cfg(feature = "DeleteRealName")]
pub mod DeleteRealName;
#[cfg(feature = "DeleteTag")]
pub mod DeleteTag;
#[cfg(feature = "DisableAttribute")]
pub mod DisableAttribute;
#[cfg(feature = "EnableAttribute")]
pub mod EnableAttribute;
#[cfg(feature = "EnableSimCard")]
pub mod EnableSimCard;
#[cfg(feature = "ListAttributes")]
pub mod ListAttributes;
#[cfg(feature = "ListBackPoolMembers")]
pub mod ListBackPoolMembers;
#[cfg(feature = "ListBackPools")]
pub mod ListBackPools;
#[cfg(feature = "ListFlowBySimCards")]
pub mod ListFlowBySimCards;
#[cfg(feature = "ListNetworkSwitchPolicies")]
pub mod ListNetworkSwitchPolicies;
#[cfg(feature = "ListProPricePlans")]
pub mod ListProPricePlans;
#[cfg(feature = "ListSimCards")]
pub mod ListSimCards;
#[cfg(feature = "ListSimDeviceMultiply")]
pub mod ListSimDeviceMultiply;
#[cfg(feature = "ListSimPoolMembers")]
pub mod ListSimPoolMembers;
#[cfg(feature = "ListSimPools")]
pub mod ListSimPools;
#[cfg(feature = "ListSimPricePlans")]
pub mod ListSimPricePlans;
#[cfg(feature = "ListSmsDetails")]
pub mod ListSmsDetails;
#[cfg(feature = "ListTags")]
pub mod ListTags;
#[cfg(feature = "ListWorkOrderDetails")]
pub mod ListWorkOrderDetails;
#[cfg(feature = "ListWorkOrders")]
pub mod ListWorkOrders;
#[cfg(feature = "RegisterImei")]
pub mod RegisterImei;
#[cfg(feature = "ResetSimCard")]
pub mod ResetSimCard;
#[cfg(feature = "SendSms")]
pub mod SendSms;
#[cfg(feature = "SetExceedCutNet")]
pub mod SetExceedCutNet;
#[cfg(feature = "SetNetworkSwitchPolicy")]
pub mod SetNetworkSwitchPolicy;
#[cfg(feature = "SetSpeedValue")]
pub mod SetSpeedValue;
#[cfg(feature = "ShowMonthUsages")]
pub mod ShowMonthUsages;
#[cfg(feature = "ShowRealNamed")]
pub mod ShowRealNamed;
#[cfg(feature = "ShowSimCard")]
pub mod ShowSimCard;
#[cfg(feature = "StartStopNet")]
pub mod StartStopNet;
#[cfg(feature = "StopSimCard")]
pub mod StopSimCard;
#[cfg(feature = "SwitchNetwork")]
pub mod SwitchNetwork;
#[cfg(feature = "UpdateAttribute")]
pub mod UpdateAttribute;
