[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
GetOpenAPIv2 = []
connectCoreV1GetNamespacedPodExec = []
connectCoreV1PostNamespacedPodExec = []
createAppsV1NamespacedDeployment = []
createBatchV1NamespacedJob = []
createBatchVolcanoShV1alpha1NamespacedJob = []
createCoreV1Namespace = []
createCoreV1NamespacedConfigMap = []
createCoreV1NamespacedEndpoints = []
createCoreV1NamespacedPersistentVolumeClaim = []
createCoreV1NamespacedPod = []
createCoreV1NamespacedSecret = []
createCoreV1NamespacedService = []
createCrdYangtseCniV1NamespacedEIPPool = []
createExtensionsV1beta1NamespacedIngress = []
createNetworkingCciIoV1beta1NamespacedNetwork = []
createRbacAuthorizationV1NamespacedRoleBinding = []
deleteAppsV1CollectionNamespacedDeployment = []
deleteAppsV1CollectionNamespacedStatefulSet = []
deleteAppsV1NamespacedDeployment = []
deleteAppsV1NamespacedStatefulSet = []
deleteBatchV1CollectionNamespacedJob = []
deleteBatchV1NamespacedJob = []
deleteBatchVolcanoShV1alpha1CollectionNamespacedJob = []
deleteBatchVolcanoShV1alpha1NamespacedJob = []
deleteCoreV1CollectionNamespacedConfigMap = []
deleteCoreV1CollectionNamespacedPod = []
deleteCoreV1CollectionNamespacedSecret = []
deleteCoreV1Namespace = []
deleteCoreV1NamespacedConfigMap = []
deleteCoreV1NamespacedEndpoints = []
deleteCoreV1NamespacedEvent = []
deleteCoreV1NamespacedPersistentVolumeClaim = []
deleteCoreV1NamespacedPod = []
deleteCoreV1NamespacedSecret = []
deleteCoreV1NamespacedService = []
deleteCrdYangtseCniV1NamespacedEIPPool = []
deleteExtensionsV1beta1CollectionNamespacedIngress = []
deleteExtensionsV1beta1NamespacedIngress = []
deleteNetworkingCciIoV1beta1CollectionNamespacedNetwork = []
deleteNetworkingCciIoV1beta1NamespacedNetwork = []
deleteRbacAuthorizationV1NamespacedRoleBinding = []
full = ["connectCoreV1GetNamespacedPodExec", "connectCoreV1PostNamespacedPodExec", "createAppsV1NamespacedDeployment", "createBatchV1NamespacedJob", "createBatchVolcanoShV1alpha1NamespacedJob", "createCoreV1Namespace", "createCoreV1NamespacedConfigMap", "createCoreV1NamespacedEndpoints", "createCoreV1NamespacedPersistentVolumeClaim", "createCoreV1NamespacedPod", "createCoreV1NamespacedSecret", "createCoreV1NamespacedService", "createCrdYangtseCniV1NamespacedEIPPool", "createExtensionsV1beta1NamespacedIngress", "createNetworkingCciIoV1beta1NamespacedNetwork", "createRbacAuthorizationV1NamespacedRoleBinding", "deleteAppsV1CollectionNamespacedDeployment", "deleteAppsV1CollectionNamespacedStatefulSet", "deleteAppsV1NamespacedDeployment", "deleteAppsV1NamespacedStatefulSet", "deleteBatchV1CollectionNamespacedJob", "deleteBatchV1NamespacedJob", "deleteBatchVolcanoShV1alpha1CollectionNamespacedJob", "deleteBatchVolcanoShV1alpha1NamespacedJob", "deleteCoreV1CollectionNamespacedConfigMap", "deleteCoreV1CollectionNamespacedPod", "deleteCoreV1CollectionNamespacedSecret", "deleteCoreV1Namespace", "deleteCoreV1NamespacedConfigMap", "deleteCoreV1NamespacedEndpoints", "deleteCoreV1NamespacedEvent", "deleteCoreV1NamespacedPersistentVolumeClaim", "deleteCoreV1NamespacedPod", "deleteCoreV1NamespacedSecret", "deleteCoreV1NamespacedService", "deleteCrdYangtseCniV1NamespacedEIPPool", "deleteExtensionsV1beta1CollectionNamespacedIngress", "deleteExtensionsV1beta1NamespacedIngress", "deleteNetworkingCciIoV1beta1CollectionNamespacedNetwork", "deleteNetworkingCciIoV1beta1NamespacedNetwork", "deleteRbacAuthorizationV1NamespacedRoleBinding", "getAPIVersions", "getAppsAPIGroup", "getAppsV1APIResources", "getBatchAPIGroup", "getBatchV1APIResources", "getBatchV1beta1APIResources", "getBatchVolcanoShAPIGroup", "getBatchVolcanoShV1alpha1APIResources", "getCoreAPIVersions", "getCoreV1APIResources", "getCrdYangtseCniAPIGroup", "getCrdYangtseCniV1APIResources", "getExtensionsAPIGroup", "getExtensionsV1beta1APIResources", "getMetricsAPIGroup", "getMetricsV1beta1APIResources", "getNetworkingCciIoAPIGroup", "getNetworkingCciIoV1beta1APIResources", "GetOpenAPIv2", "getRbacAuthorizationAPIGroup", "getRbacAuthorizationV1APIResources", "listAppsV1DeploymentForAllNamespaces", "listAppsV1NamespacedDeployment", "listAppsV1NamespacedReplicaSet", "listAppsV1NamespacedStatefulSet", "listAppsV1StatefulSetForAllNamespaces", "listBatchV1beta1CronJobForAllNamespaces", "listBatchV1JobForAllNamespaces", "listBatchV1NamespacedJob", "listBatchVolcanoShV1alpha1NamespacedJob", "listCoreV1Namespace", "listCoreV1NamespacedConfigMap", "listCoreV1NamespacedEndpoints", "listCoreV1NamespacedEvent", "listCoreV1NamespacedPersistentVolumeClaim", "listCoreV1NamespacedPod", "listCoreV1NamespacedResourceQuota", "listCoreV1NamespacedSecret", "listCoreV1NamespacedService", "listCoreV1PodForAllNamespaces", "listCrdYangtseCniV1NamespacedEIPPool", "listExtensionsV1beta1NamespacedIngress", "listMetricsV1beta1NamespacedPodMetrics", "listNetworkingCciIoV1beta1NamespacedNetwork", "listRbacAuthorizationV1ClusterRole", "listRbacAuthorizationV1NamespacedRoleBinding", "listRbacAuthorizationV1RoleBindingForAllNamespaces", "listStorageV1StorageClass", "patchAppsV1NamespacedDeployment", "patchAppsV1NamespacedDeploymentScale", "patchAppsV1NamespacedStatefulSet", "patchBatchV1NamespacedJob", "patchBatchVolcanoShV1alpha1NamespacedJob", "patchCoreV1NamespacedConfigMap", "patchCoreV1NamespacedEndpoints", "patchCoreV1NamespacedPod", "patchCoreV1NamespacedSecret", "patchCoreV1NamespacedService"]
getAPIVersions = []
getAppsAPIGroup = []
getAppsV1APIResources = []
getBatchAPIGroup = []
getBatchV1APIResources = []
getBatchV1beta1APIResources = []
getBatchVolcanoShAPIGroup = []
getBatchVolcanoShV1alpha1APIResources = []
getCoreAPIVersions = []
getCoreV1APIResources = []
getCrdYangtseCniAPIGroup = []
getCrdYangtseCniV1APIResources = []
getExtensionsAPIGroup = []
getExtensionsV1beta1APIResources = []
getMetricsAPIGroup = []
getMetricsV1beta1APIResources = []
getNetworkingCciIoAPIGroup = []
getNetworkingCciIoV1beta1APIResources = []
getRbacAuthorizationAPIGroup = []
getRbacAuthorizationV1APIResources = []
listAppsV1DeploymentForAllNamespaces = []
listAppsV1NamespacedDeployment = []
listAppsV1NamespacedReplicaSet = []
listAppsV1NamespacedStatefulSet = []
listAppsV1StatefulSetForAllNamespaces = []
listBatchV1JobForAllNamespaces = []
listBatchV1NamespacedJob = []
listBatchV1beta1CronJobForAllNamespaces = []
listBatchVolcanoShV1alpha1NamespacedJob = []
listCoreV1Namespace = []
listCoreV1NamespacedConfigMap = []
listCoreV1NamespacedEndpoints = []
listCoreV1NamespacedEvent = []
listCoreV1NamespacedPersistentVolumeClaim = []
listCoreV1NamespacedPod = []
listCoreV1NamespacedResourceQuota = []
listCoreV1NamespacedSecret = []
listCoreV1NamespacedService = []
listCoreV1PodForAllNamespaces = []
listCrdYangtseCniV1NamespacedEIPPool = []
listExtensionsV1beta1NamespacedIngress = []
listMetricsV1beta1NamespacedPodMetrics = []
listNetworkingCciIoV1beta1NamespacedNetwork = []
listRbacAuthorizationV1ClusterRole = []
listRbacAuthorizationV1NamespacedRoleBinding = []
listRbacAuthorizationV1RoleBindingForAllNamespaces = []
listStorageV1StorageClass = []
patchAppsV1NamespacedDeployment = []
patchAppsV1NamespacedDeploymentScale = []
patchAppsV1NamespacedStatefulSet = []
patchBatchV1NamespacedJob = []
patchBatchVolcanoShV1alpha1NamespacedJob = []
patchCoreV1NamespacedConfigMap = []
patchCoreV1NamespacedEndpoints = []
patchCoreV1NamespacedPod = []
patchCoreV1NamespacedSecret = []
patchCoreV1NamespacedService = []

[lib]
name = "huawei_cloud_api_definitions_CCI"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-CCI"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
