#[cfg(feature = "CreateWebHook")]
pub mod CreateWebHook;
#[cfg(feature = "DeleteWebHook")]
pub mod DeleteWebHook;
#[cfg(feature = "ListProjectDetail")]
pub mod ListProjectDetail;
#[cfg(feature = "ListProjects")]
pub mod ListProjects;
#[cfg(feature = "ListRepositoryBranches")]
pub mod ListRepositoryBranches;
#[cfg(feature = "ListRepositoryCommits")]
pub mod ListRepositoryCommits;
#[cfg(feature = "ListRepositoryTags")]
pub mod ListRepositoryTags;
#[cfg(feature = "ListWebHookDetail")]
pub mod ListWebHookDetail;
#[cfg(feature = "UpdateWebHook")]
pub mod UpdateWebHook;
