[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AcceptHandshake = []
AttachPolicy = []
CancelHandshake = []
CloseAccount = []
CreateAccount = []
CreateOrganization = []
CreateOrganizationalUnit = []
CreatePolicy = []
CreateTagResource = []
DeclineHandshake = []
DeleteOrganization = []
DeleteOrganizationalUnit = []
DeletePolicy = []
DeleteTagResource = []
DeregisterDelegatedAdministrator = []
DetachPolicy = []
DisablePolicyType = []
DisableTrustedService = []
EnablePolicyType = []
EnableTrustedService = []
InviteAccount = []
LeaveOrganization = []
ListAccounts = []
ListCloseAccountStatuses = []
ListCreateAccountStatuses = []
ListDelegatedAdministrators = []
ListDelegatedServices = []
ListEntities = []
ListEntitiesForPolicy = []
ListHandshakes = []
ListOrganizationalUnits = []
ListPolicies = []
ListQuotas = []
ListReceivedHandshakes = []
ListResourceInstances = []
ListResourceTags = []
ListRoots = []
ListServices = []
ListTagPolicyServices = []
ListTagResources = []
ListTagsForResource = []
ListTrustedServices = []
MoveAccount = []
RegisterDelegatedAdministrator = []
RemoveAccount = []
ShowAccount = []
ShowCreateAccountStatus = []
ShowEffectivePolicies = []
ShowHandshake = []
ShowOrganization = []
ShowOrganizationalUnit = []
ShowPolicy = []
ShowResourceInstancesCount = []
TagResource = []
UntagResource = []
UpdateOrganizationalUnit = []
UpdatePolicy = []
full = ["AcceptHandshake", "AttachPolicy", "CancelHandshake", "CloseAccount", "CreateAccount", "CreateOrganization", "CreateOrganizationalUnit", "CreatePolicy", "CreateTagResource", "DeclineHandshake", "DeleteOrganization", "DeleteOrganizationalUnit", "DeletePolicy", "DeleteTagResource", "DeregisterDelegatedAdministrator", "DetachPolicy", "DisablePolicyType", "DisableTrustedService", "EnablePolicyType", "EnableTrustedService", "InviteAccount", "LeaveOrganization", "ListAccounts", "ListCloseAccountStatuses", "ListCreateAccountStatuses", "ListDelegatedAdministrators", "ListDelegatedServices", "ListEntities", "ListEntitiesForPolicy", "ListHandshakes", "ListOrganizationalUnits", "ListPolicies", "ListQuotas", "ListReceivedHandshakes", "ListResourceInstances", "ListResourceTags", "ListRoots", "ListServices", "ListTagPolicyServices", "ListTagResources", "ListTagsForResource", "ListTrustedServices", "MoveAccount", "RegisterDelegatedAdministrator", "RemoveAccount", "ShowAccount", "ShowCreateAccountStatus", "ShowEffectivePolicies", "ShowHandshake", "ShowOrganization", "ShowOrganizationalUnit", "ShowPolicy", "ShowResourceInstancesCount", "TagResource", "UntagResource", "UpdateOrganizationalUnit", "UpdatePolicy"]

[lib]
name = "huawei_cloud_api_definitions_Organizations"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-Organizations"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
