#[cfg(feature = "CancelScript")]
pub mod CancelScript;
#[cfg(feature = "CreateJob")]
pub mod CreateJob;
#[cfg(feature = "CreateResource")]
pub mod CreateResource;
#[cfg(feature = "CreateScript")]
pub mod CreateScript;
#[cfg(feature = "DeleteJob")]
pub mod DeleteJob;
#[cfg(feature = "DeleteResource")]
pub mod DeleteResource;
#[cfg(feature = "DeleteScript")]
pub mod DeleteScript;
#[cfg(feature = "ExecuteScript")]
pub mod ExecuteScript;
#[cfg(feature = "ExportJob")]
pub mod ExportJob;
#[cfg(feature = "ExportJobList")]
pub mod ExportJobList;
#[cfg(feature = "ImportJob")]
pub mod ImportJob;
#[cfg(feature = "ListJobInstances")]
pub mod ListJobInstances;
#[cfg(feature = "ListJobs")]
pub mod ListJobs;
#[cfg(feature = "ListResources")]
pub mod ListResources;
#[cfg(feature = "ListScriptResults")]
pub mod ListScriptResults;
#[cfg(feature = "ListScripts")]
pub mod ListScripts;
#[cfg(feature = "ListSystemTasks")]
pub mod ListSystemTasks;
#[cfg(feature = "RestoreJobInstance")]
pub mod RestoreJobInstance;
#[cfg(feature = "RunOnce")]
pub mod RunOnce;
#[cfg(feature = "ShowFileInfo")]
pub mod ShowFileInfo;
#[cfg(feature = "ShowJob")]
pub mod ShowJob;
#[cfg(feature = "ShowJobInstance")]
pub mod ShowJobInstance;
#[cfg(feature = "ShowJobStatus")]
pub mod ShowJobStatus;
#[cfg(feature = "ShowResource")]
pub mod ShowResource;
#[cfg(feature = "ShowScript")]
pub mod ShowScript;
#[cfg(feature = "StartJob")]
pub mod StartJob;
#[cfg(feature = "StopJob")]
pub mod StopJob;
#[cfg(feature = "StopJobInstance")]
pub mod StopJobInstance;
#[cfg(feature = "UpdateJob")]
pub mod UpdateJob;
#[cfg(feature = "UpdateResource")]
pub mod UpdateResource;
#[cfg(feature = "UpdateScript")]
pub mod UpdateScript;
