#[cfg(feature = "AcceptServiceContract")]
pub mod AcceptServiceContract;
#[cfg(feature = "AsyncInvokeApiStartWorkflow")]
pub mod AsyncInvokeApiStartWorkflow;
#[cfg(feature = "CheckWorkflowAuthentication")]
pub mod CheckWorkflowAuthentication;
#[cfg(feature = "CreateMyActionTemplate")]
pub mod CreateMyActionTemplate;
#[cfg(feature = "CreateWorkflow")]
pub mod CreateWorkflow;
#[cfg(feature = "CreateWorkflowAuthentication")]
pub mod CreateWorkflowAuthentication;
#[cfg(feature = "DeleteMyActionTemplate")]
pub mod DeleteMyActionTemplate;
#[cfg(feature = "DeleteWorkflow")]
pub mod DeleteWorkflow;
#[cfg(feature = "ListMyActionTemplate")]
pub mod ListMyActionTemplate;
#[cfg(feature = "ListSystemTemplates")]
pub mod ListSystemTemplates;
#[cfg(feature = "ListWorkflowInstance")]
pub mod ListWorkflowInstance;
#[cfg(feature = "ListWorkflows")]
pub mod ListWorkflows;
#[cfg(feature = "RestoreWorkflowExecution")]
pub mod RestoreWorkflowExecution;
#[cfg(feature = "ShowPublicActionList")]
pub mod ShowPublicActionList;
#[cfg(feature = "ShowPublicTemplateInfo")]
pub mod ShowPublicTemplateInfo;
#[cfg(feature = "ShowServiceContract")]
pub mod ShowServiceContract;
#[cfg(feature = "ShowSystemTemplateDetail")]
pub mod ShowSystemTemplateDetail;
#[cfg(feature = "ShowThirdTemplateInfo")]
pub mod ShowThirdTemplateInfo;
#[cfg(feature = "ShowWorkflowInfo")]
pub mod ShowWorkflowInfo;
#[cfg(feature = "ShowWorkflowInstance")]
pub mod ShowWorkflowInstance;
#[cfg(feature = "UpdateMyActionTemplate")]
pub mod UpdateMyActionTemplate;
#[cfg(feature = "UpdateMyActionTemplateToDeprecated")]
pub mod UpdateMyActionTemplateToDeprecated;
#[cfg(feature = "UpdateWorkflow")]
pub mod UpdateWorkflow;
