[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
BatchCreateKmsTags = []
CancelGrant = []
CancelKeyDeletion = []
CancelSelfGrant = []
CreateDatakey = []
CreateDatakeyWithoutPlaintext = []
CreateGrant = []
CreateKey = []
CreateKeyStore = []
CreateKmsTag = []
CreateParametersForImport = []
CreateRandom = []
DecryptData = []
DecryptDatakey = []
DeleteImportedKeyMaterial = []
DeleteKey = []
DeleteKeyStore = []
DeleteTag = []
DisableKey = []
DisableKeyRotation = []
DisableKeyStore = []
EnableKey = []
EnableKeyRotation = []
EnableKeyStore = []
EncryptData = []
EncryptDatakey = []
ImportKeyMaterial = []
ListGrants = []
ListKeyDetail = []
ListKeyStores = []
ListKeys = []
ListKmsByTags = []
ListKmsTags = []
ListRetirableGrants = []
ShowKeyRotationStatus = []
ShowKeyStore = []
ShowKmsTags = []
ShowPublicKey = []
ShowUserInstances = []
ShowUserQuotas = []
ShowVersion = []
ShowVersions = []
Sign = []
UpdateKeyAlias = []
UpdateKeyDescription = []
UpdateKeyRotationInterval = []
ValidateSignature = []
full = ["BatchCreateKmsTags", "CancelGrant", "CancelKeyDeletion", "CancelSelfGrant", "CreateDatakey", "CreateDatakeyWithoutPlaintext", "CreateGrant", "CreateKey", "CreateKeyStore", "CreateKmsTag", "CreateParametersForImport", "CreateRandom", "DecryptData", "DecryptDatakey", "DeleteImportedKeyMaterial", "DeleteKey", "DeleteKeyStore", "DeleteTag", "DisableKey", "DisableKeyRotation", "DisableKeyStore", "EnableKey", "EnableKeyRotation", "EnableKeyStore", "EncryptData", "EncryptDatakey", "ImportKeyMaterial", "ListGrants", "ListKeyDetail", "ListKeys", "ListKeyStores", "ListKmsByTags", "ListKmsTags", "ListRetirableGrants", "ShowKeyRotationStatus", "ShowKeyStore", "ShowKmsTags", "ShowPublicKey", "ShowUserInstances", "ShowUserQuotas", "ShowVersion", "ShowVersions", "Sign", "UpdateKeyAlias", "UpdateKeyDescription", "UpdateKeyRotationInterval", "ValidateSignature"]

[lib]
name = "huawei_cloud_api_definitions_KMS"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-KMS"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
