[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AssociateAlias = []
BatchCreateKmsTags = []
CancelGrant = []
CancelKeyDeletion = []
CancelSelfGrant = []
CreateAlias = []
CreateDatakey = []
CreateDatakeyWithoutPlaintext = []
CreateEcDatakeyPair = []
CreateGrant = []
CreateKey = []
CreateKeyStore = []
CreateKmsTag = []
CreateParametersForImport = []
CreateRandom = []
CreateRsaDatakeyPair = []
DecryptData = []
DecryptDatakey = []
DeleteAlias = []
DeleteImportedKeyMaterial = []
DeleteKey = []
DeleteKeyStore = []
DeleteTag = []
DisableKey = []
DisableKeyRotation = []
DisableKeyStore = []
EnableKey = []
EnableKeyRotation = []
EnableKeyStore = []
EncryptData = []
EncryptDatakey = []
GenerateMac = []
ImportKeyMaterial = []
ListAliases = []
ListGrants = []
ListKeyDetail = []
ListKeyStores = []
ListKeys = []
ListKmsByTags = []
ListKmsTags = []
ListRetirableGrants = []
ListSupportRegions = []
ReplicateKey = []
ShowKeyRotationStatus = []
ShowKeyStore = []
ShowKmsTags = []
ShowPublicKey = []
ShowUserInstances = []
ShowUserQuotas = []
ShowVersion = []
ShowVersions = []
Sign = []
UpdateKeyAlias = []
UpdateKeyDescription = []
UpdateKeyRotationInterval = []
UpdatePrimaryRegion = []
ValidateSignature = []
VerifyMac = []
full = ["AssociateAlias", "BatchCreateKmsTags", "CancelGrant", "CancelKeyDeletion", "CancelSelfGrant", "CreateAlias", "CreateDatakey", "CreateDatakeyWithoutPlaintext", "CreateEcDatakeyPair", "CreateGrant", "CreateKey", "CreateKeyStore", "CreateKmsTag", "CreateParametersForImport", "CreateRandom", "CreateRsaDatakeyPair", "DecryptData", "DecryptDatakey", "DeleteAlias", "DeleteImportedKeyMaterial", "DeleteKey", "DeleteKeyStore", "DeleteTag", "DisableKey", "DisableKeyRotation", "DisableKeyStore", "EnableKey", "EnableKeyRotation", "EnableKeyStore", "EncryptData", "EncryptDatakey", "GenerateMac", "ImportKeyMaterial", "ListAliases", "ListGrants", "ListKeyDetail", "ListKeys", "ListKeyStores", "ListKmsByTags", "ListKmsTags", "ListRetirableGrants", "ListSupportRegions", "ReplicateKey", "ShowKeyRotationStatus", "ShowKeyStore", "ShowKmsTags", "ShowPublicKey", "ShowUserInstances", "ShowUserQuotas", "ShowVersion", "ShowVersions", "Sign", "UpdateKeyAlias", "UpdateKeyDescription", "UpdateKeyRotationInterval", "UpdatePrimaryRegion", "ValidateSignature", "VerifyMac"]

[lib]
name = "huawei_cloud_api_definitions_KMS"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-KMS"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
