[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
CheckPutEvents = []
CreateAgencies = []
CreateChannel = []
CreateConnection = []
CreateEndpoint = []
CreateEventSchema = []
CreateEventSchemaVersion = []
CreateEventSource = []
CreateEventStreaming = []
CreateSubscription = []
CreateSubscriptionTarget = []
DeleteChannel = []
DeleteConnection = []
DeleteEndpoint = []
DeleteEventSchema = []
DeleteEventSchemaVersion = []
DeleteEventSource = []
DeleteEventStreaming = []
DeleteSubscription = []
DeleteSubscriptionTarget = []
DiscoverEventSchemaFromData = []
ExecuteSubscriptionOperation = []
ListAgencies = []
ListApiVersions = []
ListChannels = []
ListConnections = []
ListEndpoints = []
ListEventSchema = []
ListEventSchemaVersions = []
ListEventSources = []
ListEventStreaming = []
ListEventTarget = []
ListObsBuckets = []
ListPubMetrics = []
ListQuotas = []
ListSubMetrics = []
ListSubscriptions = []
ListTracedEvents = []
ListTriggers = []
ListWorkflowTriggers = []
PutEvents = []
PutOfficialEvents = []
QuerySupportFeature = []
Refurbishobs = []
ResumeEventStreaming = []
ShowDetailOfChannel = []
ShowDetailOfConnection = []
ShowDetailOfEvent = []
ShowDetailOfEventSchema = []
ShowDetailOfEventSchemaVersion = []
ShowDetailOfEventSource = []
ShowDetailOfEventTrace = []
ShowDetailOfSubscription = []
ShowDetailOfSubscriptionTarget = []
ShowEventStreaming = []
ShowListOfEventSample = []
UpdateChannel = []
UpdateConnection = []
UpdateEndpoint = []
UpdateEventSchema = []
UpdateEventSource = []
UpdateEventStreaming = []
UpdateSubscription = []
UpdateSubscriptionSource = []
UpdateSubscriptionTarget = []
full = ["CheckPutEvents", "CreateAgencies", "CreateChannel", "CreateConnection", "CreateEndpoint", "CreateEventSchema", "CreateEventSchemaVersion", "CreateEventSource", "CreateEventStreaming", "CreateSubscription", "CreateSubscriptionTarget", "DeleteChannel", "DeleteConnection", "DeleteEndpoint", "DeleteEventSchema", "DeleteEventSchemaVersion", "DeleteEventSource", "DeleteEventStreaming", "DeleteSubscription", "DeleteSubscriptionTarget", "DiscoverEventSchemaFromData", "ExecuteSubscriptionOperation", "ListAgencies", "ListApiVersions", "ListChannels", "ListConnections", "ListEndpoints", "ListEventSchema", "ListEventSchemaVersions", "ListEventSources", "ListEventStreaming", "ListEventTarget", "ListObsBuckets", "ListPubMetrics", "ListQuotas", "ListSubMetrics", "ListSubscriptions", "ListTracedEvents", "ListTriggers", "ListWorkflowTriggers", "PutEvents", "PutOfficialEvents", "QuerySupportFeature", "Refurbishobs", "ResumeEventStreaming", "ShowDetailOfChannel", "ShowDetailOfConnection", "ShowDetailOfEvent", "ShowDetailOfEventSchema", "ShowDetailOfEventSchemaVersion", "ShowDetailOfEventSource", "ShowDetailOfEventTrace", "ShowDetailOfSubscription", "ShowDetailOfSubscriptionTarget", "ShowEventStreaming", "ShowListOfEventSample", "UpdateChannel", "UpdateConnection", "UpdateEndpoint", "UpdateEventSchema", "UpdateEventSource", "UpdateEventStreaming", "UpdateSubscription", "UpdateSubscriptionSource", "UpdateSubscriptionTarget"]

[lib]
name = "huawei_cloud_api_definitions_EG"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-EG"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
