[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
BatchShowPipelinesLatestStatus = []
BatchShowPipelinesStatus = []
CreatePipelineByTemplate = []
CreatePipelineByTemplateId = []
DeletePipeline = []
ListPipelineRuns = []
ListPipelineSimpleInfo = []
ListPipelineTemplates = []
ListPipelines = []
ListPipleineBuildResult = []
ListTemplates = []
RemovePipeline = []
RunPipeline = []
ShowInstanceStatus = []
ShowPipelineRunDetail = []
ShowPipelineTemplateDetail = []
ShowPipleineStatus = []
ShowTemplateDetail = []
StartNewPipeline = []
StopPipelineNew = []
StopPipelineRun = []
full = ["BatchShowPipelinesLatestStatus", "BatchShowPipelinesStatus", "CreatePipelineByTemplate", "CreatePipelineByTemplateId", "DeletePipeline", "ListPipelineRuns", "ListPipelines", "ListPipelineSimpleInfo", "ListPipelineTemplates", "ListPipleineBuildResult", "ListTemplates", "RemovePipeline", "RunPipeline", "ShowInstanceStatus", "ShowPipelineRunDetail", "ShowPipelineTemplateDetail", "ShowPipleineStatus", "ShowTemplateDetail", "StartNewPipeline", "StopPipelineNew", "StopPipelineRun"]

[lib]
name = "huawei_cloud_api_definitions_CloudPipeline"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-CloudPipeline"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "0.1.1"
