#[cfg(feature = "AddPostgresqlHbaConf")]
pub mod AddPostgresqlHbaConf;
#[cfg(feature = "AllowDbPrivilege")]
pub mod AllowDbPrivilege;
#[cfg(feature = "AllowDbUserPrivilege")]
pub mod AllowDbUserPrivilege;
#[cfg(feature = "AllowSqlserverDbUserPrivilege")]
pub mod AllowSqlserverDbUserPrivilege;
#[cfg(feature = "ApplyConfigurationAsync")]
pub mod ApplyConfigurationAsync;
#[cfg(feature = "AttachEip")]
pub mod AttachEip;
#[cfg(feature = "BatchAddMsdtcs")]
pub mod BatchAddMsdtcs;
#[cfg(feature = "BatchDeleteInstance")]
pub mod BatchDeleteInstance;
#[cfg(feature = "BatchDeleteManualBackup")]
pub mod BatchDeleteManualBackup;
#[cfg(feature = "BatchExecuteEvents")]
pub mod BatchExecuteEvents;
#[cfg(feature = "BatchModifyPublication")]
pub mod BatchModifyPublication;
#[cfg(feature = "BatchModifySubscription")]
pub mod BatchModifySubscription;
#[cfg(feature = "BatchRestoreDatabase")]
pub mod BatchRestoreDatabase;
#[cfg(feature = "BatchRestorePostgreSqlTables")]
pub mod BatchRestorePostgreSqlTables;
#[cfg(feature = "BatchStopInstance")]
pub mod BatchStopInstance;
#[cfg(feature = "BatchTagAddAction")]
pub mod BatchTagAddAction;
#[cfg(feature = "BatchTagDelAction")]
pub mod BatchTagDelAction;
#[cfg(feature = "ChangeFailoverMode")]
pub mod ChangeFailoverMode;
#[cfg(feature = "ChangeFailoverStrategy")]
pub mod ChangeFailoverStrategy;
#[cfg(feature = "ChangeOpsWindow")]
pub mod ChangeOpsWindow;
#[cfg(feature = "ChangeProxyScale")]
pub mod ChangeProxyScale;
#[cfg(feature = "ChangeTheDelayThreshold")]
pub mod ChangeTheDelayThreshold;
#[cfg(feature = "CheckInstanceForUpgrade")]
pub mod CheckInstanceForUpgrade;
#[cfg(feature = "CheckWeakpwd")]
pub mod CheckWeakpwd;
#[cfg(feature = "CollectPublicationMonitor")]
pub mod CollectPublicationMonitor;
#[cfg(feature = "CollectSubscriptionMonitor")]
pub mod CollectSubscriptionMonitor;
#[cfg(feature = "CompareConfiguration")]
pub mod CompareConfiguration;
#[cfg(feature = "CopyConfiguration")]
pub mod CopyConfiguration;
#[cfg(feature = "CopyDatabase")]
pub mod CopyDatabase;
#[cfg(feature = "CreateConfiguration")]
pub mod CreateConfiguration;
#[cfg(feature = "CreateDatabase")]
pub mod CreateDatabase;
#[cfg(feature = "CreateDbUser")]
pub mod CreateDbUser;
#[cfg(feature = "CreateDistribution")]
pub mod CreateDistribution;
#[cfg(feature = "CreateDnsName")]
pub mod CreateDnsName;
#[cfg(feature = "CreateInstance")]
pub mod CreateInstance;
#[cfg(feature = "CreateInstanceIam5")]
pub mod CreateInstanceIam5;
#[cfg(feature = "CreateIntelligentKillSession")]
pub mod CreateIntelligentKillSession;
#[cfg(feature = "CreateManualBackup")]
pub mod CreateManualBackup;
#[cfg(feature = "CreatePostgresqlDatabase")]
pub mod CreatePostgresqlDatabase;
#[cfg(feature = "CreatePostgresqlDatabaseSchema")]
pub mod CreatePostgresqlDatabaseSchema;
#[cfg(feature = "CreatePostgresqlDbUser")]
pub mod CreatePostgresqlDbUser;
#[cfg(feature = "CreatePostgresqlExtension")]
pub mod CreatePostgresqlExtension;
#[cfg(feature = "CreatePublication")]
pub mod CreatePublication;
#[cfg(feature = "CreateRdSforMySqlProxy")]
pub mod CreateRdSforMySqlProxy;
#[cfg(feature = "CreateRebuildSlave")]
pub mod CreateRebuildSlave;
#[cfg(feature = "CreateRestoreInstance")]
pub mod CreateRestoreInstance;
#[cfg(feature = "CreateSqlLimit")]
pub mod CreateSqlLimit;
#[cfg(feature = "CreateSqlserverDatabase")]
pub mod CreateSqlserverDatabase;
#[cfg(feature = "CreateSqlserverDbUser")]
pub mod CreateSqlserverDbUser;
#[cfg(feature = "CreateSubscription")]
pub mod CreateSubscription;
#[cfg(feature = "CreateXelLogDownload")]
pub mod CreateXelLogDownload;
#[cfg(feature = "DeleteConfiguration")]
pub mod DeleteConfiguration;
#[cfg(feature = "DeleteDatabase")]
pub mod DeleteDatabase;
#[cfg(feature = "DeleteDbUser")]
pub mod DeleteDbUser;
#[cfg(feature = "DeleteDisasterRecovery")]
pub mod DeleteDisasterRecovery;
#[cfg(feature = "DeleteDistribution")]
pub mod DeleteDistribution;
#[cfg(feature = "DeleteInstance")]
pub mod DeleteInstance;
#[cfg(feature = "DeleteJob")]
pub mod DeleteJob;
#[cfg(feature = "DeleteLogLtsConfigs")]
pub mod DeleteLogLtsConfigs;
#[cfg(feature = "DeleteManualBackup")]
pub mod DeleteManualBackup;
#[cfg(feature = "DeleteMsdtcLocalHost")]
pub mod DeleteMsdtcLocalHost;
#[cfg(feature = "DeletePostgresqlDatabase")]
pub mod DeletePostgresqlDatabase;
#[cfg(feature = "DeletePostgresqlDbUser")]
pub mod DeletePostgresqlDbUser;
#[cfg(feature = "DeletePostgresqlExtension")]
pub mod DeletePostgresqlExtension;
#[cfg(feature = "DeletePostgresqlHbaConf")]
pub mod DeletePostgresqlHbaConf;
#[cfg(feature = "DeletePublication")]
pub mod DeletePublication;
#[cfg(feature = "DeleteRdSforMySqlProxy")]
pub mod DeleteRdSforMySqlProxy;
#[cfg(feature = "DeleteSqlLimit")]
pub mod DeleteSqlLimit;
#[cfg(feature = "DeleteSqlserverDatabase")]
pub mod DeleteSqlserverDatabase;
#[cfg(feature = "DeleteSqlserverDatabaseEx")]
pub mod DeleteSqlserverDatabaseEx;
#[cfg(feature = "DeleteSqlserverDbUser")]
pub mod DeleteSqlserverDbUser;
#[cfg(feature = "DeleteSubscription")]
pub mod DeleteSubscription;
#[cfg(feature = "DownloadErrorlog")]
pub mod DownloadErrorlog;
#[cfg(feature = "DownloadSlowlog")]
pub mod DownloadSlowlog;
#[cfg(feature = "EnableConfiguration")]
pub mod EnableConfiguration;
#[cfg(feature = "ExecutePrivilegeDatabaseUserRole")]
pub mod ExecutePrivilegeDatabaseUserRole;
#[cfg(feature = "ExecuteRevokeDatabaseUserRole")]
pub mod ExecuteRevokeDatabaseUserRole;
#[cfg(feature = "GetInstancesNoIndexTables")]
pub mod GetInstancesNoIndexTables;
#[cfg(feature = "ListApiVersion")]
pub mod ListApiVersion;
#[cfg(feature = "ListApiVersionNew")]
pub mod ListApiVersionNew;
#[cfg(feature = "ListAuditlogs")]
pub mod ListAuditlogs;
#[cfg(feature = "ListAuthorizedDatabases")]
pub mod ListAuthorizedDatabases;
#[cfg(feature = "ListAuthorizedDbUsers")]
pub mod ListAuthorizedDbUsers;
#[cfg(feature = "ListAuthorizedSqlserverDbUsers")]
pub mod ListAuthorizedSqlserverDbUsers;
#[cfg(feature = "ListAutoScalingPolicy")]
pub mod ListAutoScalingPolicy;
#[cfg(feature = "ListBackups")]
pub mod ListBackups;
#[cfg(feature = "ListBackupTransfers")]
pub mod ListBackupTransfers;
#[cfg(feature = "ListBusinessPartners")]
pub mod ListBusinessPartners;
#[cfg(feature = "ListCollations")]
pub mod ListCollations;
#[cfg(feature = "ListConfigurationApplyHistories")]
pub mod ListConfigurationApplyHistories;
#[cfg(feature = "ListConfigurations")]
pub mod ListConfigurations;
#[cfg(feature = "ListDatabases")]
pub mod ListDatabases;
#[cfg(feature = "ListDatabaseUserRole")]
pub mod ListDatabaseUserRole;
#[cfg(feature = "ListDatastores")]
pub mod ListDatastores;
#[cfg(feature = "ListDbAgentJobHistorys")]
pub mod ListDbAgentJobHistorys;
#[cfg(feature = "ListDbAgentJobHistorySteps")]
pub mod ListDbAgentJobHistorySteps;
#[cfg(feature = "ListDbAgentJobs")]
pub mod ListDbAgentJobs;
#[cfg(feature = "ListDbUsers")]
pub mod ListDbUsers;
#[cfg(feature = "ListDistribution")]
pub mod ListDistribution;
#[cfg(feature = "ListDistributorInstances")]
pub mod ListDistributorInstances;
