#[cfg(feature = "AddPostgresqlHbaConf")]
pub mod AddPostgresqlHbaConf;
#[cfg(feature = "AllowDbPrivilege")]
pub mod AllowDbPrivilege;
#[cfg(feature = "AllowDbUserPrivilege")]
pub mod AllowDbUserPrivilege;
#[cfg(feature = "AllowSqlserverDbUserPrivilege")]
pub mod AllowSqlserverDbUserPrivilege;
#[cfg(feature = "ApplyConfigurationAsync")]
pub mod ApplyConfigurationAsync;
#[cfg(feature = "AttachEip")]
pub mod AttachEip;
#[cfg(feature = "BatchAddMsdtcs")]
pub mod BatchAddMsdtcs;
#[cfg(feature = "BatchDeleteManualBackup")]
pub mod BatchDeleteManualBackup;
#[cfg(feature = "BatchRestoreDatabase")]
pub mod BatchRestoreDatabase;
#[cfg(feature = "BatchRestorePostgreSqlTables")]
pub mod BatchRestorePostgreSqlTables;
#[cfg(feature = "BatchTagAddAction")]
pub mod BatchTagAddAction;
#[cfg(feature = "BatchTagDelAction")]
pub mod BatchTagDelAction;
#[cfg(feature = "ChangeFailoverMode")]
pub mod ChangeFailoverMode;
#[cfg(feature = "ChangeFailoverStrategy")]
pub mod ChangeFailoverStrategy;
#[cfg(feature = "ChangeOpsWindow")]
pub mod ChangeOpsWindow;
#[cfg(feature = "ChangeProxyScale")]
pub mod ChangeProxyScale;
#[cfg(feature = "ChangeTheDelayThreshold")]
pub mod ChangeTheDelayThreshold;
#[cfg(feature = "CopyConfiguration")]
pub mod CopyConfiguration;
#[cfg(feature = "CreateConfiguration")]
pub mod CreateConfiguration;
#[cfg(feature = "CreateDatabase")]
pub mod CreateDatabase;
#[cfg(feature = "CreateDbUser")]
pub mod CreateDbUser;
#[cfg(feature = "CreateDnsName")]
pub mod CreateDnsName;
#[cfg(feature = "CreateInstance")]
pub mod CreateInstance;
#[cfg(feature = "CreateManualBackup")]
pub mod CreateManualBackup;
#[cfg(feature = "CreatePostgresqlDatabase")]
pub mod CreatePostgresqlDatabase;
#[cfg(feature = "CreatePostgresqlDatabaseSchema")]
pub mod CreatePostgresqlDatabaseSchema;
#[cfg(feature = "CreatePostgresqlDbUser")]
pub mod CreatePostgresqlDbUser;
#[cfg(feature = "CreatePostgresqlExtension")]
pub mod CreatePostgresqlExtension;
#[cfg(feature = "CreateRdSforMySqlProxy")]
pub mod CreateRdSforMySqlProxy;
#[cfg(feature = "CreateRestoreInstance")]
pub mod CreateRestoreInstance;
#[cfg(feature = "CreateSqlserverDatabase")]
pub mod CreateSqlserverDatabase;
#[cfg(feature = "CreateSqlserverDbUser")]
pub mod CreateSqlserverDbUser;
#[cfg(feature = "CreateXelLogDownload")]
pub mod CreateXelLogDownload;
#[cfg(feature = "DeleteConfiguration")]
pub mod DeleteConfiguration;
#[cfg(feature = "DeleteDatabase")]
pub mod DeleteDatabase;
#[cfg(feature = "DeleteDbUser")]
pub mod DeleteDbUser;
#[cfg(feature = "DeleteInstance")]
pub mod DeleteInstance;
#[cfg(feature = "DeleteJob")]
pub mod DeleteJob;
#[cfg(feature = "DeleteLogLtsConfigs")]
pub mod DeleteLogLtsConfigs;
#[cfg(feature = "DeleteManualBackup")]
pub mod DeleteManualBackup;
#[cfg(feature = "DeletePostgresqlDatabase")]
pub mod DeletePostgresqlDatabase;
#[cfg(feature = "DeletePostgresqlDbUser")]
pub mod DeletePostgresqlDbUser;
#[cfg(feature = "DeletePostgresqlExtension")]
pub mod DeletePostgresqlExtension;
#[cfg(feature = "DeletePostgresqlHbaConf")]
pub mod DeletePostgresqlHbaConf;
#[cfg(feature = "DeleteRdSforMySqlProxy")]
pub mod DeleteRdSforMySqlProxy;
#[cfg(feature = "DeleteSqlserverDatabase")]
pub mod DeleteSqlserverDatabase;
#[cfg(feature = "DeleteSqlserverDatabaseEx")]
pub mod DeleteSqlserverDatabaseEx;
#[cfg(feature = "DeleteSqlserverDbUser")]
pub mod DeleteSqlserverDbUser;
#[cfg(feature = "DownloadSlowlog")]
pub mod DownloadSlowlog;
#[cfg(feature = "EnableConfiguration")]
pub mod EnableConfiguration;
#[cfg(feature = "ExecutePrivilegeDatabaseUserRole")]
pub mod ExecutePrivilegeDatabaseUserRole;
#[cfg(feature = "ExecuteRevokeDatabaseUserRole")]
pub mod ExecuteRevokeDatabaseUserRole;
#[cfg(feature = "ListApiVersion")]
pub mod ListApiVersion;
#[cfg(feature = "ListApiVersionNew")]
pub mod ListApiVersionNew;
#[cfg(feature = "ListAuditlogs")]
pub mod ListAuditlogs;
#[cfg(feature = "ListAuthorizedDatabases")]
pub mod ListAuthorizedDatabases;
#[cfg(feature = "ListAuthorizedDbUsers")]
pub mod ListAuthorizedDbUsers;
#[cfg(feature = "ListAuthorizedSqlserverDbUsers")]
pub mod ListAuthorizedSqlserverDbUsers;
#[cfg(feature = "ListBackups")]
pub mod ListBackups;
#[cfg(feature = "ListCollations")]
pub mod ListCollations;
#[cfg(feature = "ListConfigurations")]
pub mod ListConfigurations;
#[cfg(feature = "ListDatabases")]
pub mod ListDatabases;
#[cfg(feature = "ListDatabaseUserRole")]
pub mod ListDatabaseUserRole;
#[cfg(feature = "ListDatastores")]
pub mod ListDatastores;
#[cfg(feature = "ListDbUsers")]
pub mod ListDbUsers;
#[cfg(feature = "ListDrRelations")]
pub mod ListDrRelations;
#[cfg(feature = "ListEngineFlavors")]
pub mod ListEngineFlavors;
#[cfg(feature = "ListErrorlogForLts")]
pub mod ListErrorlogForLts;
#[cfg(feature = "ListErrorLogs")]
pub mod ListErrorLogs;
#[cfg(feature = "ListErrorLogsNew")]
pub mod ListErrorLogsNew;
#[cfg(feature = "ListFlavors")]
pub mod ListFlavors;
#[cfg(feature = "ListHistoryDatabase")]
pub mod ListHistoryDatabase;
#[cfg(feature = "ListInspectionHistories")]
pub mod ListInspectionHistories;
#[cfg(feature = "ListInstanceDiagnosis")]
pub mod ListInstanceDiagnosis;
#[cfg(feature = "ListInstanceParamHistories")]
pub mod ListInstanceParamHistories;
#[cfg(feature = "ListInstances")]
pub mod ListInstances;
#[cfg(feature = "ListInstancesInfoDiagnosis")]
pub mod ListInstancesInfoDiagnosis;
#[cfg(feature = "ListInstancesSupportFastRestore")]
pub mod ListInstancesSupportFastRestore;
#[cfg(feature = "ListInstanceTags")]
pub mod ListInstanceTags;
#[cfg(feature = "ListJobInfo")]
pub mod ListJobInfo;
#[cfg(feature = "ListJobInfoDetail")]
pub mod ListJobInfoDetail;
#[cfg(feature = "ListLogLtsConfigs")]
pub mod ListLogLtsConfigs;
#[cfg(feature = "ListMsdtcHosts")]
pub mod ListMsdtcHosts;
#[cfg(feature = "ListOffSiteBackups")]
pub mod ListOffSiteBackups;
#[cfg(feature = "ListOffSiteInstances")]
pub mod ListOffSiteInstances;
#[cfg(feature = "ListOffSiteRestoreTimes")]
pub mod ListOffSiteRestoreTimes;
#[cfg(feature = "ListPostgresqlDatabases")]
pub mod ListPostgresqlDatabases;
#[cfg(feature = "ListPostgresqlDatabaseSchemas")]
pub mod ListPostgresqlDatabaseSchemas;
#[cfg(feature = "ListPostgresqlDbUserPaginated")]
pub mod ListPostgresqlDbUserPaginated;
#[cfg(feature = "ListPostgresqlExtension")]
pub mod ListPostgresqlExtension;
#[cfg(feature = "ListPostgresqlHbaInfo")]
pub mod ListPostgresqlHbaInfo;
#[cfg(feature = "ListPostgresqlHbaInfoHistory")]
pub mod ListPostgresqlHbaInfoHistory;
#[cfg(feature = "ListPostgresqlListHistoryTables")]
pub mod ListPostgresqlListHistoryTables;
#[cfg(feature = "ListPredefinedTag")]
pub mod ListPredefinedTag;
#[cfg(feature = "ListProjectTags")]
pub mod ListProjectTags;
#[cfg(feature = "ListRdSforMySqlProxy")]
pub mod ListRdSforMySqlProxy;
#[cfg(feature = "ListRdSforMysqlProxyFlavors")]
pub mod ListRdSforMysqlProxyFlavors;
#[cfg(feature = "ListRecycleInstances")]
pub mod ListRecycleInstances;
#[cfg(feature = "ListSimplifiedInstances")]
pub mod ListSimplifiedInstances;
