[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddImageTag = []
BatchAddMembers = []
BatchAddOrDeleteTags = []
BatchDeleteMembers = []
BatchUpdateMembers = []
CopyImageCrossRegion = []
CopyImageInRegion = []
CreateDataImage = []
CreateImage = []
CreateOrUpdateTags = []
CreateWholeImage = []
DeleteImageTag = []
ExportImage = []
GlanceAddImageMember = []
GlanceCreateImageMetadata = []
GlanceCreateTag = []
GlanceDeleteImage = []
GlanceDeleteImageMember = []
GlanceDeleteTag = []
GlanceListImageMemberSchemas = []
GlanceListImageMembers = []
GlanceListImageSchemas = []
GlanceListImages = []
GlanceShowImage = []
GlanceShowImageMember = []
GlanceShowImageMemberSchemas = []
GlanceShowImageSchemas = []
GlanceUpdateImage = []
GlanceUpdateImageMember = []
ImportImageQuick = []
ListImageByTags = []
ListImageTags = []
ListImages = []
ListImagesTags = []
ListOsVersions = []
ListTags = []
ListVersions = []
RegisterImage = []
ShowImageQuota = []
ShowJob = []
ShowJobProgress = []
ShowVersion = []
UpdateImage = []
full = ["AddImageTag", "BatchAddMembers", "BatchAddOrDeleteTags", "BatchDeleteMembers", "BatchUpdateMembers", "CopyImageCrossRegion", "CopyImageInRegion", "CreateDataImage", "CreateImage", "CreateOrUpdateTags", "CreateWholeImage", "DeleteImageTag", "ExportImage", "GlanceAddImageMember", "GlanceCreateImageMetadata", "GlanceCreateTag", "GlanceDeleteImage", "GlanceDeleteImageMember", "GlanceDeleteTag", "GlanceListImageMembers", "GlanceListImageMemberSchemas", "GlanceListImages", "GlanceListImageSchemas", "GlanceShowImage", "GlanceShowImageMember", "GlanceShowImageMemberSchemas", "GlanceShowImageSchemas", "GlanceUpdateImage", "GlanceUpdateImageMember", "ImportImageQuick", "ListImageByTags", "ListImages", "ListImagesTags", "ListImageTags", "ListOsVersions", "ListTags", "ListVersions", "RegisterImage", "ShowImageQuota", "ShowJob", "ShowJobProgress", "ShowVersion", "UpdateImage"]

[lib]
name = "huawei_cloud_api_definitions_IMS"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-IMS"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "0.1.0"
