#[cfg(feature = "CreateGroup")]
pub mod CreateGroup;
#[cfg(feature = "CreateGroupMembership")]
pub mod CreateGroupMembership;
#[cfg(feature = "CreateUser")]
pub mod CreateUser;
#[cfg(feature = "DeleteGroup")]
pub mod DeleteGroup;
#[cfg(feature = "DeleteGroupMembership")]
pub mod DeleteGroupMembership;
#[cfg(feature = "DeleteUser")]
pub mod DeleteUser;
#[cfg(feature = "DescribeGroup")]
pub mod DescribeGroup;
#[cfg(feature = "DescribeGroupMembership")]
pub mod DescribeGroupMembership;
#[cfg(feature = "DescribeUser")]
pub mod DescribeUser;
#[cfg(feature = "GetGroupId")]
pub mod GetGroupId;
#[cfg(feature = "GetGroupMembershipId")]
pub mod GetGroupMembershipId;
#[cfg(feature = "GetUserId")]
pub mod GetUserId;
#[cfg(feature = "IsMemberInGroups")]
pub mod IsMemberInGroups;
#[cfg(feature = "ListGroupMemberships")]
pub mod ListGroupMemberships;
#[cfg(feature = "ListGroupMembershipsForMember")]
pub mod ListGroupMembershipsForMember;
#[cfg(feature = "ListGroups")]
pub mod ListGroups;
#[cfg(feature = "ListUsers")]
pub mod ListUsers;
#[cfg(feature = "UpdateGroup")]
pub mod UpdateGroup;
#[cfg(feature = "UpdateUser")]
pub mod UpdateUser;
