#[cfg(feature = "BatchDeleteSessions")]
pub mod BatchDeleteSessions;
#[cfg(feature = "BatchListMfaDevicesForUser")]
pub mod BatchListMfaDevicesForUser;
#[cfg(feature = "CreateBearerToken")]
pub mod CreateBearerToken;
#[cfg(feature = "CreateExternalIdPConfigurationForDirectory")]
pub mod CreateExternalIdPConfigurationForDirectory;
#[cfg(feature = "CreateGroup")]
pub mod CreateGroup;
#[cfg(feature = "CreateGroupMembership")]
pub mod CreateGroupMembership;
#[cfg(feature = "CreateProvisioningTenant")]
pub mod CreateProvisioningTenant;
#[cfg(feature = "CreateSpCertificate")]
pub mod CreateSpCertificate;
#[cfg(feature = "CreateUser")]
pub mod CreateUser;
#[cfg(feature = "DeleteBearerToken")]
pub mod DeleteBearerToken;
#[cfg(feature = "DeleteExternalIdPCertificate")]
pub mod DeleteExternalIdPCertificate;
#[cfg(feature = "DeleteExternalIdPConfigurationForDirectory")]
pub mod DeleteExternalIdPConfigurationForDirectory;
#[cfg(feature = "DeleteGroup")]
pub mod DeleteGroup;
#[cfg(feature = "DeleteGroupMembership")]
pub mod DeleteGroupMembership;
#[cfg(feature = "DeleteMfaDeviceForUser")]
pub mod DeleteMfaDeviceForUser;
#[cfg(feature = "DeleteProvisioningTenant")]
pub mod DeleteProvisioningTenant;
#[cfg(feature = "DeleteSpCertificate")]
pub mod DeleteSpCertificate;
#[cfg(feature = "DeleteUser")]
pub mod DeleteUser;
#[cfg(feature = "DescribeGroup")]
pub mod DescribeGroup;
#[cfg(feature = "DescribeGroupMembership")]
pub mod DescribeGroupMembership;
#[cfg(feature = "DescribeGroups")]
pub mod DescribeGroups;
#[cfg(feature = "DescribePasswordPolicy")]
pub mod DescribePasswordPolicy;
#[cfg(feature = "DescribeUser")]
pub mod DescribeUser;
#[cfg(feature = "DescribeUsers")]
pub mod DescribeUsers;
#[cfg(feature = "DisableExternalIdPConfigurationForDirectory")]
pub mod DisableExternalIdPConfigurationForDirectory;
#[cfg(feature = "DisableUser")]
pub mod DisableUser;
#[cfg(feature = "EnableExternalIdPConfigurationForDirectory")]
pub mod EnableExternalIdPConfigurationForDirectory;
#[cfg(feature = "EnableUser")]
pub mod EnableUser;
#[cfg(feature = "GetGroupId")]
pub mod GetGroupId;
#[cfg(feature = "GetGroupMembershipId")]
pub mod GetGroupMembershipId;
#[cfg(feature = "GetIdentityStoreSummary")]
pub mod GetIdentityStoreSummary;
#[cfg(feature = "GetSpConfigurationForDirectory")]
pub mod GetSpConfigurationForDirectory;
#[cfg(feature = "GetUserId")]
pub mod GetUserId;
#[cfg(feature = "ImportExternalIdPCertificate")]
pub mod ImportExternalIdPCertificate;
#[cfg(feature = "IsMemberInGroups")]
pub mod IsMemberInGroups;
#[cfg(feature = "ListBearerTokens")]
pub mod ListBearerTokens;
#[cfg(feature = "ListExternalIdPCertificates")]
pub mod ListExternalIdPCertificates;
#[cfg(feature = "ListExternalIdPConfigurationsForDirectory")]
pub mod ListExternalIdPConfigurationsForDirectory;
#[cfg(feature = "ListGroupMemberships")]
pub mod ListGroupMemberships;
#[cfg(feature = "ListGroupMembershipsForMember")]
pub mod ListGroupMembershipsForMember;
#[cfg(feature = "ListGroups")]
pub mod ListGroups;
#[cfg(feature = "ListProvisioningTenants")]
pub mod ListProvisioningTenants;
#[cfg(feature = "ListSessions")]
pub mod ListSessions;
#[cfg(feature = "ListSpCertificates")]
pub mod ListSpCertificates;
#[cfg(feature = "ListUsers")]
pub mod ListUsers;
#[cfg(feature = "RegisterMfaDeviceForUser")]
pub mod RegisterMfaDeviceForUser;
#[cfg(feature = "ResetPwdMode")]
pub mod ResetPwdMode;
#[cfg(feature = "UpdateExternalIdPConfigurationForDirectory")]
pub mod UpdateExternalIdPConfigurationForDirectory;
#[cfg(feature = "UpdateGroup")]
pub mod UpdateGroup;
#[cfg(feature = "UpdateMfaDeviceForUser")]
pub mod UpdateMfaDeviceForUser;
#[cfg(feature = "UpdatePasswordPolicy")]
pub mod UpdatePasswordPolicy;
#[cfg(feature = "UpdateSpActiveCertificate")]
pub mod UpdateSpActiveCertificate;
#[cfg(feature = "UpdateUser")]
pub mod UpdateUser;
#[cfg(feature = "VerifyEmail")]
pub mod VerifyEmail;
