#[cfg(feature = "CreateCollectionRecord")]
pub mod CreateCollectionRecord;
#[cfg(feature = "CreateJob")]
pub mod CreateJob;
#[cfg(feature = "CreateSimSmMaps")]
pub mod CreateSimSmMaps;
#[cfg(feature = "CreateSimSmScenarios")]
pub mod CreateSimSmScenarios;
#[cfg(feature = "CreateSimSmScenariosFiles")]
pub mod CreateSimSmScenariosFiles;
#[cfg(feature = "DeleteCollectionById")]
pub mod DeleteCollectionById;
#[cfg(feature = "DeleteJob")]
pub mod DeleteJob;
#[cfg(feature = "DeletePackageById")]
pub mod DeletePackageById;
#[cfg(feature = "ListCollectionRecords")]
pub mod ListCollectionRecords;
#[cfg(feature = "ListJobs")]
pub mod ListJobs;
#[cfg(feature = "ListPackages")]
pub mod ListPackages;
#[cfg(feature = "ListSimSmScenarios")]
pub mod ListSimSmScenarios;
#[cfg(feature = "UpdateJob")]
pub mod UpdateJob;
#[cfg(feature = "UpdatePackageById")]
pub mod UpdatePackageById;
#[cfg(feature = "UpdateSimSmMapsFiles")]
pub mod UpdateSimSmMapsFiles;
#[cfg(feature = "UpdateSimSmScenariosFiles")]
pub mod UpdateSimSmScenariosFiles;
