#[cfg(feature = "AddResourcesToGroup")]
pub mod AddResourcesToGroup;
#[cfg(feature = "CollectAllResourcesSummary")]
pub mod CollectAllResourcesSummary;
#[cfg(feature = "CountAllResources")]
pub mod CountAllResources;
#[cfg(feature = "CreateResourceGroup")]
pub mod CreateResourceGroup;
#[cfg(feature = "DeleteResourceGroup")]
pub mod DeleteResourceGroup;
#[cfg(feature = "ListAllProviders")]
pub mod ListAllProviders;
#[cfg(feature = "ListAllResources")]
pub mod ListAllResources;
#[cfg(feature = "ListAllTags")]
pub mod ListAllTags;
#[cfg(feature = "ListResourceGroups")]
pub mod ListResourceGroups;
#[cfg(feature = "ListResources")]
pub mod ListResources;
#[cfg(feature = "RemoveResourceFromGroup")]
pub mod RemoveResourceFromGroup;
#[cfg(feature = "ShowResourceById")]
pub mod ShowResourceById;
#[cfg(feature = "ShowResourceDetail")]
pub mod ShowResourceDetail;
#[cfg(feature = "ShowResourceGroup")]
pub mod ShowResourceGroup;
#[cfg(feature = "ShowResourceRelations")]
pub mod ShowResourceRelations;
#[cfg(feature = "UpdateResourceGroup")]
pub mod UpdateResourceGroup;
