#[cfg(feature = "BatchCreateTags")]
pub mod BatchCreateTags;
#[cfg(feature = "BatchDeleteTags")]
pub mod BatchDeleteTags;
#[cfg(feature = "BatchExportCloudPhoneData")]
pub mod BatchExportCloudPhoneData;
#[cfg(feature = "BatchImportCloudPhoneData")]
pub mod BatchImportCloudPhoneData;
#[cfg(feature = "ChangeCloudPhoneServer")]
pub mod ChangeCloudPhoneServer;
#[cfg(feature = "ChangeCloudPhoneServerModel")]
pub mod ChangeCloudPhoneServerModel;
#[cfg(feature = "CreateNet2CloudPhoneServer")]
pub mod CreateNet2CloudPhoneServer;
#[cfg(feature = "DeleteShareApps")]
pub mod DeleteShareApps;
#[cfg(feature = "DeleteShareFiles")]
pub mod DeleteShareFiles;
#[cfg(feature = "ImportTraffic")]
pub mod ImportTraffic;
#[cfg(feature = "InstallApk")]
pub mod InstallApk;
#[cfg(feature = "ListCloudPhoneImages")]
pub mod ListCloudPhoneImages;
#[cfg(feature = "ListCloudPhoneModels")]
pub mod ListCloudPhoneModels;
#[cfg(feature = "ListCloudPhones")]
pub mod ListCloudPhones;
#[cfg(feature = "ListCloudPhoneServerModels")]
pub mod ListCloudPhoneServerModels;
#[cfg(feature = "ListCloudPhoneServers")]
pub mod ListCloudPhoneServers;
#[cfg(feature = "ListEncodeServers")]
pub mod ListEncodeServers;
#[cfg(feature = "ListJobs")]
pub mod ListJobs;
#[cfg(feature = "ListProjectTags")]
pub mod ListProjectTags;
#[cfg(feature = "ListResourceInstances")]
pub mod ListResourceInstances;
#[cfg(feature = "ListResourceTags")]
pub mod ListResourceTags;
#[cfg(feature = "ListShareFiles")]
pub mod ListShareFiles;
#[cfg(feature = "PushFile")]
pub mod PushFile;
#[cfg(feature = "PushShareApps")]
pub mod PushShareApps;
#[cfg(feature = "PushShareFiles")]
pub mod PushShareFiles;
#[cfg(feature = "ResetCloudPhone")]
pub mod ResetCloudPhone;
#[cfg(feature = "RestartCloudPhone")]
pub mod RestartCloudPhone;
#[cfg(feature = "RestartCloudPhoneServer")]
pub mod RestartCloudPhoneServer;
#[cfg(feature = "RestartEncodeServer")]
pub mod RestartEncodeServer;
#[cfg(feature = "RunShellCommand")]
pub mod RunShellCommand;
#[cfg(feature = "RunSyncCommand")]
pub mod RunSyncCommand;
#[cfg(feature = "ShowBandwidthDetail")]
pub mod ShowBandwidthDetail;
#[cfg(feature = "ShowCloudPhoneDetail")]
pub mod ShowCloudPhoneDetail;
#[cfg(feature = "ShowCloudPhoneServerDetail")]
pub mod ShowCloudPhoneServerDetail;
#[cfg(feature = "ShowJob")]
pub mod ShowJob;
#[cfg(feature = "StopCloudPhone")]
pub mod StopCloudPhone;
#[cfg(feature = "UninstallApk")]
pub mod UninstallApk;
#[cfg(feature = "UpdateBandwidth")]
pub mod UpdateBandwidth;
#[cfg(feature = "UpdateCloudPhoneProperty")]
pub mod UpdateCloudPhoneProperty;
#[cfg(feature = "UpdateKeypair")]
pub mod UpdateKeypair;
#[cfg(feature = "UpdatePhoneName")]
pub mod UpdatePhoneName;
#[cfg(feature = "UpdateServerName")]
pub mod UpdateServerName;
