#[cfg(feature = "CancelRemuxTask")]
pub mod CancelRemuxTask;
#[cfg(feature = "CreateAgenciesTask")]
pub mod CreateAgenciesTask;
#[cfg(feature = "CreateAnimatedGraphicsTask")]
pub mod CreateAnimatedGraphicsTask;
#[cfg(feature = "CreateEditingJob")]
pub mod CreateEditingJob;
#[cfg(feature = "CreateEncryptTask")]
pub mod CreateEncryptTask;
#[cfg(feature = "CreateExtractTask")]
pub mod CreateExtractTask;
#[cfg(feature = "CreateRemuxTask")]
pub mod CreateRemuxTask;
#[cfg(feature = "CreateRetryRemuxTask")]
pub mod CreateRetryRemuxTask;
#[cfg(feature = "CreateTemplateGroup")]
pub mod CreateTemplateGroup;
#[cfg(feature = "CreateThumbnailsTask")]
pub mod CreateThumbnailsTask;
#[cfg(feature = "CreateTranscodingTask")]
pub mod CreateTranscodingTask;
#[cfg(feature = "CreateTransTemplate")]
pub mod CreateTransTemplate;
#[cfg(feature = "CreateWatermarkTemplate")]
pub mod CreateWatermarkTemplate;
#[cfg(feature = "DeleteAnimatedGraphicsTask")]
pub mod DeleteAnimatedGraphicsTask;
#[cfg(feature = "DeleteEditingJob")]
pub mod DeleteEditingJob;
#[cfg(feature = "DeleteEncryptTask")]
pub mod DeleteEncryptTask;
#[cfg(feature = "DeleteExtractTask")]
pub mod DeleteExtractTask;
#[cfg(feature = "DeleteRemuxTask")]
pub mod DeleteRemuxTask;
#[cfg(feature = "DeleteTemplate")]
pub mod DeleteTemplate;
#[cfg(feature = "DeleteTemplateGroup")]
pub mod DeleteTemplateGroup;
#[cfg(feature = "DeleteThumbnailsTask")]
pub mod DeleteThumbnailsTask;
#[cfg(feature = "DeleteTranscodingTask")]
pub mod DeleteTranscodingTask;
#[cfg(feature = "DeleteTranscodingTaskByConsole")]
pub mod DeleteTranscodingTaskByConsole;
#[cfg(feature = "DeleteWatermarkTemplate")]
pub mod DeleteWatermarkTemplate;
#[cfg(feature = "ListAllBuckets")]
pub mod ListAllBuckets;
#[cfg(feature = "ListAllObsObjList")]
pub mod ListAllObsObjList;
#[cfg(feature = "ListAnimatedGraphicsTask")]
pub mod ListAnimatedGraphicsTask;
#[cfg(feature = "ListEditingJob")]
pub mod ListEditingJob;
#[cfg(feature = "ListEncryptTask")]
pub mod ListEncryptTask;
#[cfg(feature = "ListExtractTask")]
pub mod ListExtractTask;
#[cfg(feature = "ListNotifyEvent")]
pub mod ListNotifyEvent;
#[cfg(feature = "ListNotifySmnTopicConfig")]
pub mod ListNotifySmnTopicConfig;
#[cfg(feature = "ListRemuxTask")]
pub mod ListRemuxTask;
#[cfg(feature = "ListStatSummary")]
pub mod ListStatSummary;
#[cfg(feature = "ListTemplate")]
pub mod ListTemplate;
#[cfg(feature = "ListTemplateGroup")]
pub mod ListTemplateGroup;
#[cfg(feature = "ListThumbnailsTask")]
pub mod ListThumbnailsTask;
#[cfg(feature = "ListTranscodingTask")]
pub mod ListTranscodingTask;
#[cfg(feature = "ListWatermarkTemplate")]
pub mod ListWatermarkTemplate;
#[cfg(feature = "NotifySmnTopicConfig")]
pub mod NotifySmnTopicConfig;
#[cfg(feature = "ShowAgenciesTask")]
pub mod ShowAgenciesTask;
#[cfg(feature = "ShowTenantAccessInfo")]
pub mod ShowTenantAccessInfo;
#[cfg(feature = "UpdateBucketAuthorized")]
pub mod UpdateBucketAuthorized;
#[cfg(feature = "UpdateTemplateGroup")]
pub mod UpdateTemplateGroup;
#[cfg(feature = "UpdateTenantAccessInfo")]
pub mod UpdateTenantAccessInfo;
#[cfg(feature = "UpdateTransTemplate")]
pub mod UpdateTransTemplate;
#[cfg(feature = "UpdateWatermarkTemplate")]
pub mod UpdateWatermarkTemplate;
