[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
ApplyConfiguration = []
ApplyConfigurationToInstances = []
BatchDeleteManualBackup = []
BatchTagAction = []
BatchUpgradeDatabaseVersion = []
CancelInstanceScheduleWindow = []
CheckDisasterRecoveryOperation = []
CheckWeekPassword = []
ClearInstanceSessions = []
CompareConfiguration = []
CopyConfiguration = []
CreateBack = []
CreateColdVolume = []
CreateConfiguration = []
CreateDbCacheMapping = []
CreateDbCacheRule = []
CreateDbUser = []
CreateDisasterRecovery = []
CreateGeminiDbDualActive = []
CreateInstance = []
DeleteBackup = []
DeleteConfiguration = []
DeleteDbCacheMapping = []
DeleteDbCacheRule = []
DeleteDbUser = []
DeleteDisasterRecovery = []
DeleteEnlargeFailNode = []
DeleteGeminiDbDualActive = []
DeleteInstance = []
DeleteInstancesSession = []
DeleteLtsConfigs = []
DeleteRedisDisabledCommands = []
ExpandInstanceNode = []
ListApiVersion = []
ListAvailableFlavorInfos = []
ListBackups = []
ListCassandraSlowLogs = []
ListConfigurationDatastores = []
ListConfigurationTemplates = []
ListConfigurations = []
ListDatastores = []
ListDbCacheMappings = []
ListDbCacheRules = []
ListDbUsers = []
ListDedicatedResources = []
ListEpsQuotas = []
ListFlavorInfos = []
ListFlavors = []
ListInfluxdbSlowLogs = []
ListInstanceDatabases = []
ListInstanceMaintenanceWindow = []
ListInstanceSessions = []
ListInstanceTags = []
ListInstances = []
ListInstancesByResourceTags = []
ListInstancesByTags = []
ListInstancesSession = []
ListInstancesSessionStatistics = []
ListJobs = []
ListLtsConfigs = []
ListMongodbErrorLogs = []
ListMongodbSlowLogs = []
ListNosqlTaskList = []
ListProjectTags = []
ListRecycleInstances = []
ListRedisPitrRestoreTime = []
ListRedisSlowLogs = []
ListRestoreDatabases = []
ListRestoreTables = []
ListRestoreTime = []
ListSlowLogs = []
ModifyAutoNodeExpansionPolicy = []
ModifyDbUserPrivilege = []
ModifyEpsQuotas = []
ModifyInstanceMaintenanceWindow = []
ModifyPort = []
ModifyPublicIp = []
ModifyVolume = []
OfflineNodes = []
PauseResumeDataSynchronization = []
ResetDbUserPassword = []
ResetParamGroupTemplate = []
ResetPassword = []
ResizeColdVolume = []
ResizeInstance = []
ResizeInstanceVolume = []
RestartInstance = []
RestoreExistingInstance = []
RestoreRedisData = []
RestoreRedisPitr = []
SaveLtsConfigs = []
SaveRedisDisabledCommands = []
SetAutoEnlargePolicy = []
SetBackupPolicy = []
SetDisasterRecoverySettings = []
SetInstanceDataDump = []
SetRecyclePolicy = []
SetRedisPitrPolicy = []
ShowAllInstancesBackups = []
ShowAllInstancesBackupsNew = []
full = ["ApplyConfiguration", "ApplyConfigurationToInstances", "BatchDeleteManualBackup", "BatchTagAction", "BatchUpgradeDatabaseVersion", "CancelInstanceScheduleWindow", "CheckDisasterRecoveryOperation", "CheckWeekPassword", "ClearInstanceSessions", "CompareConfiguration", "CopyConfiguration", "CreateBack", "CreateColdVolume", "CreateConfiguration", "CreateDbCacheMapping", "CreateDbCacheRule", "CreateDbUser", "CreateDisasterRecovery", "CreateGeminiDbDualActive", "CreateInstance", "DeleteBackup", "DeleteConfiguration", "DeleteDbCacheMapping", "DeleteDbCacheRule", "DeleteDbUser", "DeleteDisasterRecovery", "DeleteEnlargeFailNode", "DeleteGeminiDbDualActive", "DeleteInstance", "DeleteInstancesSession", "DeleteLtsConfigs", "DeleteRedisDisabledCommands", "ExpandInstanceNode", "ListApiVersion", "ListAvailableFlavorInfos", "ListBackups", "ListCassandraSlowLogs", "ListConfigurationDatastores", "ListConfigurations", "ListConfigurationTemplates", "ListDatastores", "ListDbCacheMappings", "ListDbCacheRules", "ListDbUsers", "ListDedicatedResources", "ListEpsQuotas", "ListFlavorInfos", "ListFlavors", "ListInfluxdbSlowLogs", "ListInstanceDatabases", "ListInstanceMaintenanceWindow", "ListInstances", "ListInstancesByResourceTags", "ListInstancesByTags", "ListInstanceSessions", "ListInstancesSession", "ListInstancesSessionStatistics", "ListInstanceTags", "ListJobs", "ListLtsConfigs", "ListMongodbErrorLogs", "ListMongodbSlowLogs", "ListNosqlTaskList", "ListProjectTags", "ListRecycleInstances", "ListRedisPitrRestoreTime", "ListRedisSlowLogs", "ListRestoreDatabases", "ListRestoreTables", "ListRestoreTime", "ListSlowLogs", "ModifyAutoNodeExpansionPolicy", "ModifyDbUserPrivilege", "ModifyEpsQuotas", "ModifyInstanceMaintenanceWindow", "ModifyPort", "ModifyPublicIp", "ModifyVolume", "OfflineNodes", "PauseResumeDataSynchronization", "ResetDbUserPassword", "ResetParamGroupTemplate", "ResetPassword", "ResizeColdVolume", "ResizeInstance", "ResizeInstanceVolume", "RestartInstance", "RestoreExistingInstance", "RestoreRedisData", "RestoreRedisPitr", "SaveLtsConfigs", "SaveRedisDisabledCommands", "SetAutoEnlargePolicy", "SetBackupPolicy", "SetDisasterRecoverySettings", "SetInstanceDataDump", "SetRecyclePolicy", "SetRedisPitrPolicy", "ShowAllInstancesBackups", "ShowAllInstancesBackupsNew"]

[lib]
name = "huawei_cloud_api_definitions_GaussDBforNoSQL"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-GaussDBforNoSQL"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
