[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
ApplyConfiguration = []
ApplyConfigurationToInstances = []
BatchTagAction = []
BatchUpgradeDatabaseVersion = []
CancelInstanceScheduleWindow = []
CheckDisasterRecoveryOperation = []
CheckWeekPassword = []
CompareConfiguration = []
CopyConfiguration = []
CreateBack = []
CreateColdVolume = []
CreateConfiguration = []
CreateDbCacheMapping = []
CreateDbCacheRule = []
CreateDbUser = []
CreateDisasterRecovery = []
CreateInstance = []
DeleteBackup = []
DeleteConfiguration = []
DeleteDbCacheMapping = []
DeleteDbCacheRule = []
DeleteDbUser = []
DeleteDisasterRecovery = []
DeleteEnlargeFailNode = []
DeleteInstance = []
DeleteInstancesSession = []
DeleteLtsConfigs = []
ExpandInstanceNode = []
ListApiVersion = []
ListAvailableFlavorInfos = []
ListCassandraSlowLogs = []
ListConfigurationDatastores = []
ListConfigurationTemplates = []
ListConfigurations = []
ListDatastores = []
ListDbCacheMappings = []
ListDbCacheRules = []
ListDbUsers = []
ListDedicatedResources = []
ListEpsQuotas = []
ListFlavorInfos = []
ListFlavors = []
ListInfluxdbSlowLogs = []
ListInstanceDatabases = []
ListInstanceMaintenanceWindow = []
ListInstanceTags = []
ListInstances = []
ListInstancesByResourceTags = []
ListInstancesByTags = []
ListInstancesSession = []
ListInstancesSessionStatistics = []
ListJobs = []
ListLtsConfigs = []
ListMongodbErrorLogs = []
ListMongodbSlowLogs = []
ListNosqlTaskList = []
ListProjectTags = []
ListRecycleInstances = []
ListRedisSlowLogs = []
ListRestoreDatabases = []
ListRestoreTables = []
ListRestoreTime = []
ListSlowLogs = []
ModifyDbUserPrivilege = []
ModifyEpsQuotas = []
ModifyInstanceMaintenanceWindow = []
ModifyPort = []
ModifyPublicIp = []
ModifyVolume = []
OfflineNodes = []
PauseResumeDataSynchronization = []
ResetDbUserPassword = []
ResetParamGroupTemplate = []
ResetPassword = []
ResizeColdVolume = []
ResizeInstance = []
ResizeInstanceVolume = []
RestartInstance = []
RestoreExistingInstance = []
SaveLtsConfigs = []
SetAutoEnlargePolicy = []
SetBackupPolicy = []
SetInstanceDataDump = []
SetRecyclePolicy = []
ShowAllInstancesBackups = []
ShowAllInstancesBackupsNew = []
ShowApiVersion = []
ShowApplicableInstances = []
ShowApplyHistory = []
ShowAutoEnlargePolicy = []
ShowBackupPolicies = []
ShowBackupPolicy = []
ShowConfigurationDetail = []
ShowElbIpGroup = []
ShowErrorLog = []
ShowHighRiskCommands = []
ShowInstanceBiactiveRegions = []
ShowInstanceConfiguration = []
ShowInstanceRole = []
ShowIpNumRequirement = []
full = ["ApplyConfiguration", "ApplyConfigurationToInstances", "BatchTagAction", "BatchUpgradeDatabaseVersion", "CancelInstanceScheduleWindow", "CheckDisasterRecoveryOperation", "CheckWeekPassword", "CompareConfiguration", "CopyConfiguration", "CreateBack", "CreateColdVolume", "CreateConfiguration", "CreateDbCacheMapping", "CreateDbCacheRule", "CreateDbUser", "CreateDisasterRecovery", "CreateInstance", "DeleteBackup", "DeleteConfiguration", "DeleteDbCacheMapping", "DeleteDbCacheRule", "DeleteDbUser", "DeleteDisasterRecovery", "DeleteEnlargeFailNode", "DeleteInstance", "DeleteInstancesSession", "DeleteLtsConfigs", "ExpandInstanceNode", "ListApiVersion", "ListAvailableFlavorInfos", "ListCassandraSlowLogs", "ListConfigurationDatastores", "ListConfigurations", "ListConfigurationTemplates", "ListDatastores", "ListDbCacheMappings", "ListDbCacheRules", "ListDbUsers", "ListDedicatedResources", "ListEpsQuotas", "ListFlavorInfos", "ListFlavors", "ListInfluxdbSlowLogs", "ListInstanceDatabases", "ListInstanceMaintenanceWindow", "ListInstances", "ListInstancesByResourceTags", "ListInstancesByTags", "ListInstancesSession", "ListInstancesSessionStatistics", "ListInstanceTags", "ListJobs", "ListLtsConfigs", "ListMongodbErrorLogs", "ListMongodbSlowLogs", "ListNosqlTaskList", "ListProjectTags", "ListRecycleInstances", "ListRedisSlowLogs", "ListRestoreDatabases", "ListRestoreTables", "ListRestoreTime", "ListSlowLogs", "ModifyDbUserPrivilege", "ModifyEpsQuotas", "ModifyInstanceMaintenanceWindow", "ModifyPort", "ModifyPublicIp", "ModifyVolume", "OfflineNodes", "PauseResumeDataSynchronization", "ResetDbUserPassword", "ResetParamGroupTemplate", "ResetPassword", "ResizeColdVolume", "ResizeInstance", "ResizeInstanceVolume", "RestartInstance", "RestoreExistingInstance", "SaveLtsConfigs", "SetAutoEnlargePolicy", "SetBackupPolicy", "SetInstanceDataDump", "SetRecyclePolicy", "ShowAllInstancesBackups", "ShowAllInstancesBackupsNew", "ShowApiVersion", "ShowApplicableInstances", "ShowApplyHistory", "ShowAutoEnlargePolicy", "ShowBackupPolicies", "ShowBackupPolicy", "ShowConfigurationDetail", "ShowElbIpGroup", "ShowErrorLog", "ShowHighRiskCommands", "ShowInstanceBiactiveRegions", "ShowInstanceConfiguration", "ShowInstanceRole", "ShowIpNumRequirement"]

[lib]
name = "huawei_cloud_api_definitions_GaussDBforNoSQL"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-GaussDBforNoSQL"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
