#[cfg(feature = "AddServerNics")]
pub mod AddServerNics;
#[cfg(feature = "AttachBaremetalServerVolume")]
pub mod AttachBaremetalServerVolume;
#[cfg(feature = "BatchCreateBaremetalServerTags")]
pub mod BatchCreateBaremetalServerTags;
#[cfg(feature = "BatchDeleteBaremetalServerTags")]
pub mod BatchDeleteBaremetalServerTags;
#[cfg(feature = "BatchRebootBaremetalServers")]
pub mod BatchRebootBaremetalServers;
#[cfg(feature = "BatchStartBaremetalServers")]
pub mod BatchStartBaremetalServers;
#[cfg(feature = "BatchStopBaremetalServers")]
pub mod BatchStopBaremetalServers;
#[cfg(feature = "ChangeBaremetalServerName")]
pub mod ChangeBaremetalServerName;
#[cfg(feature = "ChangeBaremetalServerOs")]
pub mod ChangeBaremetalServerOs;
#[cfg(feature = "CreateBareMetalServers")]
pub mod CreateBareMetalServers;
#[cfg(feature = "DeleteServerNics")]
pub mod DeleteServerNics;
#[cfg(feature = "DeleteWindowsBareMetalServerPassword")]
pub mod DeleteWindowsBareMetalServerPassword;
#[cfg(feature = "DetachBaremetalServerVolume")]
pub mod DetachBaremetalServerVolume;
#[cfg(feature = "ListBaremetalFlavorDetailExtends")]
pub mod ListBaremetalFlavorDetailExtends;
#[cfg(feature = "ListBareMetalServerDetails")]
pub mod ListBareMetalServerDetails;
#[cfg(feature = "ListBareMetalServers")]
pub mod ListBareMetalServers;
#[cfg(feature = "ReinstallBaremetalServerOs")]
pub mod ReinstallBaremetalServerOs;
#[cfg(feature = "ResetPwdOneClick")]
pub mod ResetPwdOneClick;
#[cfg(feature = "ShowBaremetalServerInterfaceAttachments")]
pub mod ShowBaremetalServerInterfaceAttachments;
#[cfg(feature = "ShowBaremetalServerTags")]
pub mod ShowBaremetalServerTags;
#[cfg(feature = "ShowBaremetalServerVolumeInfo")]
pub mod ShowBaremetalServerVolumeInfo;
#[cfg(feature = "ShowJobInfos")]
pub mod ShowJobInfos;
#[cfg(feature = "ShowResetPwd")]
pub mod ShowResetPwd;
#[cfg(feature = "ShowServerRemoteConsole")]
pub mod ShowServerRemoteConsole;
#[cfg(feature = "ShowSpecifiedVersion")]
pub mod ShowSpecifiedVersion;
#[cfg(feature = "ShowTenantQuota")]
pub mod ShowTenantQuota;
#[cfg(feature = "ShowVersionsInfo")]
pub mod ShowVersionsInfo;
#[cfg(feature = "ShowWindowsBaremetalServerPwd")]
pub mod ShowWindowsBaremetalServerPwd;
#[cfg(feature = "UpdateBaremetalServerInterfaceAttachments")]
pub mod UpdateBaremetalServerInterfaceAttachments;
#[cfg(feature = "UpdateBaremetalServerMetadata")]
pub mod UpdateBaremetalServerMetadata;
