#[cfg(feature = "AddDevData")]
pub mod AddDevData;
#[cfg(feature = "AddPipelineJob")]
pub mod AddPipelineJob;
#[cfg(feature = "CreateAssetModel")]
pub mod CreateAssetModel;
#[cfg(feature = "CreateAssetNew")]
pub mod CreateAssetNew;
#[cfg(feature = "CreateBatchJob")]
pub mod CreateBatchJob;
#[cfg(feature = "CreateComputingResource")]
pub mod CreateComputingResource;
#[cfg(feature = "CreateDatasource")]
pub mod CreateDatasource;
#[cfg(feature = "CreateGroup")]
pub mod CreateGroup;
#[cfg(feature = "CreateRun")]
pub mod CreateRun;
#[cfg(feature = "CreateStreamingJob")]
pub mod CreateStreamingJob;
#[cfg(feature = "CreateTable")]
pub mod CreateTable;
#[cfg(feature = "DeleteAssetModel")]
pub mod DeleteAssetModel;
#[cfg(feature = "DeleteAssetNew")]
pub mod DeleteAssetNew;
#[cfg(feature = "DeleteBatchJob")]
pub mod DeleteBatchJob;
#[cfg(feature = "DeleteComputingResource")]
pub mod DeleteComputingResource;
#[cfg(feature = "DeleteDatasource")]
pub mod DeleteDatasource;
#[cfg(feature = "DeleteDataStore")]
pub mod DeleteDataStore;
#[cfg(feature = "DeleteGroup")]
pub mod DeleteGroup;
#[cfg(feature = "DeletePipelineJob")]
pub mod DeletePipelineJob;
#[cfg(feature = "DeleteRun")]
pub mod DeleteRun;
#[cfg(feature = "DeleteStreamingJobById")]
pub mod DeleteStreamingJobById;
#[cfg(feature = "DeleteTable")]
pub mod DeleteTable;
#[cfg(feature = "ExportDataset")]
pub mod ExportDataset;
#[cfg(feature = "ImportData")]
pub mod ImportData;
#[cfg(feature = "ListAssetModels")]
pub mod ListAssetModels;
#[cfg(feature = "ListAssetsNew")]
pub mod ListAssetsNew;
#[cfg(feature = "ListBatchJobs")]
pub mod ListBatchJobs;
#[cfg(feature = "ListComputingResources")]
pub mod ListComputingResources;
#[cfg(feature = "ListGroups")]
pub mod ListGroups;
#[cfg(feature = "ListHistory")]
pub mod ListHistory;
#[cfg(feature = "ListMetrics")]
pub mod ListMetrics;
#[cfg(feature = "ListPipelineJobs")]
pub mod ListPipelineJobs;
#[cfg(feature = "ListRuns")]
pub mod ListRuns;
#[cfg(feature = "ListTables")]
pub mod ListTables;
#[cfg(feature = "ListTagValues")]
pub mod ListTagValues;
#[cfg(feature = "PublishRootAsset")]
pub mod PublishRootAsset;
#[cfg(feature = "ShowAllDataSource")]
pub mod ShowAllDataSource;
#[cfg(feature = "ShowAssetModel")]
pub mod ShowAssetModel;
#[cfg(feature = "ShowAssetNew")]
pub mod ShowAssetNew;
#[cfg(feature = "ShowBatchJob")]
pub mod ShowBatchJob;
#[cfg(feature = "ShowDataset")]
pub mod ShowDataset;
#[cfg(feature = "ShowDataSource")]
pub mod ShowDataSource;
#[cfg(feature = "ShowJobById")]
pub mod ShowJobById;
#[cfg(feature = "ShowJobs")]
pub mod ShowJobs;
#[cfg(feature = "ShowLastPropertyValue")]
pub mod ShowLastPropertyValue;
#[cfg(feature = "ShowMetricValue")]
pub mod ShowMetricValue;
#[cfg(feature = "ShowPipelineJob")]
pub mod ShowPipelineJob;
#[cfg(feature = "ShowPropertyRawValue")]
pub mod ShowPropertyRawValue;
#[cfg(feature = "ShowPropertyValues")]
pub mod ShowPropertyValues;
#[cfg(feature = "ShowRun")]
pub mod ShowRun;
#[cfg(feature = "ShowTablePreview")]
pub mod ShowTablePreview;
#[cfg(feature = "ShowTableSchema")]
pub mod ShowTableSchema;
#[cfg(feature = "StartJob")]
pub mod StartJob;
#[cfg(feature = "StartPipelineJob")]
pub mod StartPipelineJob;
#[cfg(feature = "StopJob")]
pub mod StopJob;
#[cfg(feature = "StopPipelineJob")]
pub mod StopPipelineJob;
#[cfg(feature = "UpdateAssetModel")]
pub mod UpdateAssetModel;
#[cfg(feature = "UpdateAssetNew")]
pub mod UpdateAssetNew;
#[cfg(feature = "UpdateBatchJob")]
pub mod UpdateBatchJob;
#[cfg(feature = "UpdateDataSource")]
pub mod UpdateDataSource;
#[cfg(feature = "UpdateDataStore")]
pub mod UpdateDataStore;
#[cfg(feature = "UpdateGroup")]
pub mod UpdateGroup;
#[cfg(feature = "UpdatePipelineJob")]
pub mod UpdatePipelineJob;
#[cfg(feature = "UpdateStreamingJob")]
pub mod UpdateStreamingJob;
#[cfg(feature = "ValidateSql")]
pub mod ValidateSql;
