#[cfg(feature = "BatchCreateCaTags")]
pub mod BatchCreateCaTags;
#[cfg(feature = "BatchCreateCertTags")]
pub mod BatchCreateCertTags;
#[cfg(feature = "BatchDeleteCaTags")]
pub mod BatchDeleteCaTags;
#[cfg(feature = "BatchDeleteCertTags")]
pub mod BatchDeleteCertTags;
#[cfg(feature = "CountCaResourceInstances")]
pub mod CountCaResourceInstances;
#[cfg(feature = "CountCertResourceInstances")]
pub mod CountCertResourceInstances;
#[cfg(feature = "CreateAgency")]
pub mod CreateAgency;
#[cfg(feature = "CreateCaTag")]
pub mod CreateCaTag;
#[cfg(feature = "CreateCertificate")]
pub mod CreateCertificate;
#[cfg(feature = "CreateCertificateAuthority")]
pub mod CreateCertificateAuthority;
#[cfg(feature = "CreateCertificateAuthorityObsAgency")]
pub mod CreateCertificateAuthorityObsAgency;
#[cfg(feature = "CreateCertificateAuthorityOrder")]
pub mod CreateCertificateAuthorityOrder;
#[cfg(feature = "CreateCertificateByCsr")]
pub mod CreateCertificateByCsr;
#[cfg(feature = "CreateCertTag")]
pub mod CreateCertTag;
#[cfg(feature = "DeleteCertificate")]
pub mod DeleteCertificate;
#[cfg(feature = "DeleteCertificateAuthority")]
pub mod DeleteCertificateAuthority;
#[cfg(feature = "DisableCertificateAuthority")]
pub mod DisableCertificateAuthority;
#[cfg(feature = "DisableCertificateAuthorityCrl")]
pub mod DisableCertificateAuthorityCrl;
#[cfg(feature = "EnableCertificateAuthority")]
pub mod EnableCertificateAuthority;
#[cfg(feature = "EnableCertificateAuthorityCrl")]
pub mod EnableCertificateAuthorityCrl;
#[cfg(feature = "ExportCertificate")]
pub mod ExportCertificate;
#[cfg(feature = "ExportCertificateAuthorityCertificate")]
pub mod ExportCertificateAuthorityCertificate;
#[cfg(feature = "ExportCertificateAuthorityCsr")]
pub mod ExportCertificateAuthorityCsr;
#[cfg(feature = "ImportCertificateAuthorityCertificate")]
pub mod ImportCertificateAuthorityCertificate;
#[cfg(feature = "IssueCertificateAuthorityCertificate")]
pub mod IssueCertificateAuthorityCertificate;
#[cfg(feature = "ListCaResourceInstances")]
pub mod ListCaResourceInstances;
#[cfg(feature = "ListCaTags")]
pub mod ListCaTags;
#[cfg(feature = "ListCertificate")]
pub mod ListCertificate;
#[cfg(feature = "ListCertificateAuthority")]
pub mod ListCertificateAuthority;
#[cfg(feature = "ListCertificateAuthorityObsBucket")]
pub mod ListCertificateAuthorityObsBucket;
#[cfg(feature = "ListCertResourceInstances")]
pub mod ListCertResourceInstances;
#[cfg(feature = "ListCertTags")]
pub mod ListCertTags;
#[cfg(feature = "ListDomainCaTags")]
pub mod ListDomainCaTags;
#[cfg(feature = "ListDomainCertTags")]
pub mod ListDomainCertTags;
#[cfg(feature = "ParseCertificateSigningRequest")]
pub mod ParseCertificateSigningRequest;
#[cfg(feature = "RestoreCertificateAuthority")]
pub mod RestoreCertificateAuthority;
#[cfg(feature = "RevokeCertificate")]
pub mod RevokeCertificate;
#[cfg(feature = "RevokeCertificateAuthority")]
pub mod RevokeCertificateAuthority;
#[cfg(feature = "ShowAgency")]
pub mod ShowAgency;
#[cfg(feature = "ShowCertificate")]
pub mod ShowCertificate;
#[cfg(feature = "ShowCertificateAuthority")]
pub mod ShowCertificateAuthority;
#[cfg(feature = "ShowCertificateAuthorityObsAgency")]
pub mod ShowCertificateAuthorityObsAgency;
#[cfg(feature = "ShowCertificateAuthorityQuota")]
pub mod ShowCertificateAuthorityQuota;
#[cfg(feature = "ShowCertificateQuota")]
pub mod ShowCertificateQuota;
#[cfg(feature = "ShowConsoleConfig")]
pub mod ShowConsoleConfig;
#[cfg(feature = "UpdateOcspSwitch")]
pub mod UpdateOcspSwitch;
