[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddAppConfigsTemplates = []
AddDevice = []
AddGeneralAppConfigsTemplate = []
AddGeneralOtTemplate = []
AddOtTemplates = []
BatchAssociateNaToNodes = []
BatchConfirmConfigsNew = []
BatchImportConfigs = []
BatchListAppConfigsTemplates = []
BatchListDcDevices = []
BatchListDcDs = []
BatchListDcPoints = []
BatchListEdgeAppVersions = []
BatchListEdgeApps = []
BatchListModules = []
BatchListOtTemplates = []
CreateApp = []
CreateAppInstance = []
CreateAppVersion = []
CreateCluster = []
CreateClusterInstallCmd = []
CreateDcPoint = []
CreateDs = []
CreateEdgeApp = []
CreateEdgeApplicationVersion = []
CreateEdgeNode = []
CreateExternalEntity = []
CreateInstallCmd = []
CreateModule = []
CreateSchedule = []
DeleteApp = []
DeleteAppConfigsTemplate = []
DeleteAppInstance = []
DeleteAppVersion = []
DeleteCluster = []
DeleteDcDs = []
DeleteDcPoint = []
DeleteDevice = []
DeleteEdgeApp = []
DeleteEdgeApplicationVersion = []
DeleteEdgeNode = []
DeleteExternalEntity = []
DeleteIaConfig = []
DeleteModule = []
DeleteNa = []
DeleteOtTemplate = []
DeleteSchedule = []
DownloadAppVersion = []
ExecuteDeviceControlsRelease = []
ExecuteDeviceControlsSet = []
ImportPoints = []
InvokeDeleteProxy = []
InvokeGetProxy = []
InvokePatchProxy = []
InvokePostProxy = []
InvokePutProxy = []
ListAppImage = []
ListAppInstanceHistory = []
ListAppInstances = []
ListAppVersions = []
ListApps = []
ListClusters = []
ListDevices = []
ListEdgeNodes = []
ListExternalEntity = []
ListIaConfigs = []
ListNaAuthorizedNodes = []
ListNas = []
ListRoutes = []
ShowApp = []
ShowAppConfigsTemplate = []
ShowAppVersion = []
ShowCluster = []
ShowDcDs = []
ShowDcPoint = []
ShowEdgeApp = []
ShowEdgeApplicationVersion = []
ShowEdgeNode = []
ShowIaConfig = []
ShowModule = []
ShowModuleShadow = []
ShowNa = []
ShowOtTemplate = []
ShowPointTemplate = []
ShowPoints = []
ShowProductConfig = []
SynchronizeDcConfigs = []
UpdateAppInstance = []
UpdateDcDs = []
UpdateDcPoint = []
UpdateDevice = []
UpdateEdgeApplicationVersion = []
UpdateEdgeApplicationVersionState = []
UpdateExternalEntity = []
UpdateIaConfig = []
UpdateModule = []
UpdateModuleShadow = []
UpdateModuleState = []
UpdateNa = []
UpdateRoutes = []
full = ["AddAppConfigsTemplates", "AddDevice", "AddGeneralAppConfigsTemplate", "AddGeneralOtTemplate", "AddOtTemplates", "BatchAssociateNaToNodes", "BatchConfirmConfigsNew", "BatchImportConfigs", "BatchListAppConfigsTemplates", "BatchListDcDevices", "BatchListDcDs", "BatchListDcPoints", "BatchListEdgeApps", "BatchListEdgeAppVersions", "BatchListModules", "BatchListOtTemplates", "CreateApp", "CreateAppInstance", "CreateAppVersion", "CreateCluster", "CreateClusterInstallCmd", "CreateDcPoint", "CreateDs", "CreateEdgeApp", "CreateEdgeApplicationVersion", "CreateEdgeNode", "CreateExternalEntity", "CreateInstallCmd", "CreateModule", "CreateSchedule", "DeleteApp", "DeleteAppConfigsTemplate", "DeleteAppInstance", "DeleteAppVersion", "DeleteCluster", "DeleteDcDs", "DeleteDcPoint", "DeleteDevice", "DeleteEdgeApp", "DeleteEdgeApplicationVersion", "DeleteEdgeNode", "DeleteExternalEntity", "DeleteIaConfig", "DeleteModule", "DeleteNa", "DeleteOtTemplate", "DeleteSchedule", "DownloadAppVersion", "ExecuteDeviceControlsRelease", "ExecuteDeviceControlsSet", "ImportPoints", "InvokeDeleteProxy", "InvokeGetProxy", "InvokePatchProxy", "InvokePostProxy", "InvokePutProxy", "ListAppImage", "ListAppInstanceHistory", "ListAppInstances", "ListApps", "ListAppVersions", "ListClusters", "ListDevices", "ListEdgeNodes", "ListExternalEntity", "ListIaConfigs", "ListNaAuthorizedNodes", "ListNas", "ListRoutes", "ShowApp", "ShowAppConfigsTemplate", "ShowAppVersion", "ShowCluster", "ShowDcDs", "ShowDcPoint", "ShowEdgeApp", "ShowEdgeApplicationVersion", "ShowEdgeNode", "ShowIaConfig", "ShowModule", "ShowModuleShadow", "ShowNa", "ShowOtTemplate", "ShowPoints", "ShowPointTemplate", "ShowProductConfig", "SynchronizeDcConfigs", "UpdateAppInstance", "UpdateDcDs", "UpdateDcPoint", "UpdateDevice", "UpdateEdgeApplicationVersion", "UpdateEdgeApplicationVersionState", "UpdateExternalEntity", "UpdateIaConfig", "UpdateModule", "UpdateModuleShadow", "UpdateModuleState", "UpdateNa", "UpdateRoutes"]

[lib]
name = "huawei_cloud_api_definitions_IoTEdge"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-IoTEdge"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
