#[cfg(feature = "BatchCreateOrDeleteKafkaTag")]
pub mod BatchCreateOrDeleteKafkaTag;
#[cfg(feature = "BatchDeleteGroup")]
pub mod BatchDeleteGroup;
#[cfg(feature = "BatchDeleteInstanceTopic")]
pub mod BatchDeleteInstanceTopic;
#[cfg(feature = "BatchDeleteInstanceUsers")]
pub mod BatchDeleteInstanceUsers;
#[cfg(feature = "BatchDeleteMessageDiagnosisReports")]
pub mod BatchDeleteMessageDiagnosisReports;
#[cfg(feature = "BatchRestartOrDeleteInstances")]
pub mod BatchRestartOrDeleteInstances;
#[cfg(feature = "CloseKafkaManager")]
pub mod CloseKafkaManager;
#[cfg(feature = "CreateConnector")]
pub mod CreateConnector;
#[cfg(feature = "CreateConnectorTask")]
pub mod CreateConnectorTask;
#[cfg(feature = "CreateInstanceTopic")]
pub mod CreateInstanceTopic;
#[cfg(feature = "CreateInstanceUser")]
pub mod CreateInstanceUser;
#[cfg(feature = "CreateKafkaConsumerGroup")]
pub mod CreateKafkaConsumerGroup;
#[cfg(feature = "CreateKafkaReassignmentTask")]
pub mod CreateKafkaReassignmentTask;
#[cfg(feature = "CreateKafkaRebalanceLogTask")]
pub mod CreateKafkaRebalanceLogTask;
#[cfg(feature = "CreateKafkaTopicQuota")]
pub mod CreateKafkaTopicQuota;
#[cfg(feature = "CreateKafkaUserClientQuotaTask")]
pub mod CreateKafkaUserClientQuotaTask;
#[cfg(feature = "CreateMessageDiagnosisTask")]
pub mod CreateMessageDiagnosisTask;
#[cfg(feature = "CreatePostPaidKafkaInstance")]
pub mod CreatePostPaidKafkaInstance;
#[cfg(feature = "CreateReassignmentTask")]
pub mod CreateReassignmentTask;
#[cfg(feature = "DeleteBackgroundTask")]
pub mod DeleteBackgroundTask;
#[cfg(feature = "DeleteConnector")]
pub mod DeleteConnector;
#[cfg(feature = "DeleteConnectorTask")]
pub mod DeleteConnectorTask;
#[cfg(feature = "DeleteConsumerGroupOffsets")]
pub mod DeleteConsumerGroupOffsets;
#[cfg(feature = "DeleteInstance")]
pub mod DeleteInstance;
#[cfg(feature = "DeleteInstanceConsumerGroup")]
pub mod DeleteInstanceConsumerGroup;
#[cfg(feature = "DeleteKafkaMessage")]
pub mod DeleteKafkaMessage;
#[cfg(feature = "DeleteKafkaTopicMessages")]
pub mod DeleteKafkaTopicMessages;
#[cfg(feature = "DeleteKafkaTopicQuota")]
pub mod DeleteKafkaTopicQuota;
#[cfg(feature = "DeleteKafkaUserClientQuotaTask")]
pub mod DeleteKafkaUserClientQuotaTask;
#[cfg(feature = "DeleteScheduledTask")]
pub mod DeleteScheduledTask;
#[cfg(feature = "ListAvailableZones")]
pub mod ListAvailableZones;
#[cfg(feature = "ListBackgroundTasks")]
pub mod ListBackgroundTasks;
#[cfg(feature = "ListConfigFeatures")]
pub mod ListConfigFeatures;
#[cfg(feature = "ListConnectorTasks")]
pub mod ListConnectorTasks;
#[cfg(feature = "ListEngineProducts")]
pub mod ListEngineProducts;
#[cfg(feature = "ListInstanceConsumerGroup")]
pub mod ListInstanceConsumerGroup;
#[cfg(feature = "ListInstanceConsumerGroupMembers")]
pub mod ListInstanceConsumerGroupMembers;
#[cfg(feature = "ListInstanceConsumerGroupMessageOffset")]
pub mod ListInstanceConsumerGroupMessageOffset;
#[cfg(feature = "ListInstanceConsumerGroups")]
pub mod ListInstanceConsumerGroups;
#[cfg(feature = "ListInstanceConsumerGroupTopics")]
pub mod ListInstanceConsumerGroupTopics;
#[cfg(feature = "ListInstances")]
pub mod ListInstances;
#[cfg(feature = "ListInstanceTopics")]
pub mod ListInstanceTopics;
#[cfg(feature = "ListMessageDiagnosisReports")]
pub mod ListMessageDiagnosisReports;
#[cfg(feature = "ListObsBuckets")]
pub mod ListObsBuckets;
#[cfg(feature = "ListScheduledTasks")]
pub mod ListScheduledTasks;
#[cfg(feature = "ListTopicPartitions")]
pub mod ListTopicPartitions;
#[cfg(feature = "ListTopicProducers")]
pub mod ListTopicProducers;
#[cfg(feature = "ModifyConnectorTask")]
pub mod ModifyConnectorTask;
#[cfg(feature = "ModifyInstanceConfigs")]
pub mod ModifyInstanceConfigs;
#[cfg(feature = "ModifyKafkaPublicIpAccessSwitch")]
pub mod ModifyKafkaPublicIpAccessSwitch;
#[cfg(feature = "ModifyKafkaTopicQuota")]
pub mod ModifyKafkaTopicQuota;
#[cfg(feature = "ModifyRecyclePolicy")]
pub mod ModifyRecyclePolicy;
#[cfg(feature = "PauseConnectorTask")]
pub mod PauseConnectorTask;
#[cfg(feature = "ResetManagerPassword")]
pub mod ResetManagerPassword;
#[cfg(feature = "ResetMessageOffsetWithEngine")]
pub mod ResetMessageOffsetWithEngine;
#[cfg(feature = "ResetPassword")]
pub mod ResetPassword;
#[cfg(feature = "ResetUserPasswrod")]
pub mod ResetUserPasswrod;
#[cfg(feature = "ResizeEngineInstance")]
pub mod ResizeEngineInstance;
#[cfg(feature = "RestartConnectorTask")]
pub mod RestartConnectorTask;
#[cfg(feature = "RestartManager")]
pub mod RestartManager;
#[cfg(feature = "RestoreRecycleInstance")]
pub mod RestoreRecycleInstance;
#[cfg(feature = "ResumeConnectorTask")]
pub mod ResumeConnectorTask;
#[cfg(feature = "SendKafkaMessage")]
pub mod SendKafkaMessage;
#[cfg(feature = "ShowBackgroundTask")]
pub mod ShowBackgroundTask;
#[cfg(feature = "ShowBackgroundTaskProgress")]
pub mod ShowBackgroundTaskProgress;
#[cfg(feature = "ShowCesHierarchy")]
pub mod ShowCesHierarchy;
#[cfg(feature = "ShowCluster")]
pub mod ShowCluster;
#[cfg(feature = "ShowConnectorResourceInfo")]
pub mod ShowConnectorResourceInfo;
#[cfg(feature = "ShowConnectorTask")]
pub mod ShowConnectorTask;
#[cfg(feature = "ShowCoordinators")]
pub mod ShowCoordinators;
#[cfg(feature = "ShowDiagnosisPreCheck")]
pub mod ShowDiagnosisPreCheck;
#[cfg(feature = "ShowEngineInstanceExtendProductInfo")]
pub mod ShowEngineInstanceExtendProductInfo;
#[cfg(feature = "ShowGroups")]
pub mod ShowGroups;
#[cfg(feature = "ShowInstance")]
pub mod ShowInstance;
#[cfg(feature = "ShowInstanceConfigs")]
pub mod ShowInstanceConfigs;
#[cfg(feature = "ShowInstanceMessages")]
pub mod ShowInstanceMessages;
#[cfg(feature = "ShowInstanceUsers")]
pub mod ShowInstanceUsers;
#[cfg(feature = "ShowKafkaCluster")]
pub mod ShowKafkaCluster;
#[cfg(feature = "ShowKafkaProductCores")]
pub mod ShowKafkaProductCores;
#[cfg(feature = "ShowKafkaProjectTags")]
pub mod ShowKafkaProjectTags;
#[cfg(feature = "ShowKafkaRebalanceLog")]
pub mod ShowKafkaRebalanceLog;
#[cfg(feature = "ShowKafkaScalePreCheckInfo")]
pub mod ShowKafkaScalePreCheckInfo;
#[cfg(feature = "ShowKafkaTags")]
pub mod ShowKafkaTags;
#[cfg(feature = "ShowKafkaTopicDetail")]
pub mod ShowKafkaTopicDetail;
#[cfg(feature = "ShowKafkaTopicPartitionDiskusage")]
pub mod ShowKafkaTopicPartitionDiskusage;
#[cfg(feature = "ShowKafkaTopicQuota")]
pub mod ShowKafkaTopicQuota;
#[cfg(feature = "ShowKafkaUserClientQuota")]
pub mod ShowKafkaUserClientQuota;
#[cfg(feature = "ShowMaintainWindows")]
pub mod ShowMaintainWindows;
#[cfg(feature = "ShowMessageDiagnosisReport")]
pub mod ShowMessageDiagnosisReport;
#[cfg(feature = "ShowMessages")]
pub mod ShowMessages;
#[cfg(feature = "ShowPartitionBeginningMessage")]
pub mod ShowPartitionBeginningMessage;
#[cfg(feature = "ShowPartitionEndMessage")]
pub mod ShowPartitionEndMessage;
#[cfg(feature = "ShowPartitionMessage")]
pub mod ShowPartitionMessage;
#[cfg(feature = "ShowRecycleInstances")]
pub mod ShowRecycleInstances;
#[cfg(feature = "ShowSpecConvertProduct")]
pub mod ShowSpecConvertProduct;
#[cfg(feature = "ShowTopicAccessPolicy")]
pub mod ShowTopicAccessPolicy;
#[cfg(feature = "ShowUpgradeInstanceVersion")]
pub mod ShowUpgradeInstanceVersion;
#[cfg(feature = "ShowVolumeExpandConfig")]
pub mod ShowVolumeExpandConfig;
#[cfg(feature = "StopKafkaRebalanceLogTask")]
pub mod StopKafkaRebalanceLogTask;
#[cfg(feature = "UpdateInstance")]
pub mod UpdateInstance;
