#[cfg(feature = "ApplyJudgement")]
pub mod ApplyJudgement;
#[cfg(feature = "ExecuteExercise")]
pub mod ExecuteExercise;
#[cfg(feature = "ListAllDifficults")]
pub mod ListAllDifficults;
#[cfg(feature = "ListClassroomMemberJobs")]
pub mod ListClassroomMemberJobs;
#[cfg(feature = "ListClassroomMembers")]
pub mod ListClassroomMembers;
#[cfg(feature = "ListClassrooms")]
pub mod ListClassrooms;
#[cfg(feature = "ListExercises")]
pub mod ListExercises;
#[cfg(feature = "ListJobs")]
pub mod ListJobs;
#[cfg(feature = "ListMemberJobRecords")]
pub mod ListMemberJobRecords;
#[cfg(feature = "ListMyKnowledgePoints")]
pub mod ListMyKnowledgePoints;
#[cfg(feature = "ListPackages")]
pub mod ListPackages;
#[cfg(feature = "ShowClassroomDetail")]
pub mod ShowClassroomDetail;
#[cfg(feature = "ShowExerciseDetail")]
pub mod ShowExerciseDetail;
#[cfg(feature = "ShowJobDetail")]
pub mod ShowJobDetail;
#[cfg(feature = "ShowJobExercises")]
pub mod ShowJobExercises;
#[cfg(feature = "ShowJudgementDetail")]
pub mod ShowJudgementDetail;
#[cfg(feature = "ShowJudgementFile")]
pub mod ShowJudgementFile;
#[cfg(feature = "ShowPackageDetail")]
pub mod ShowPackageDetail;
