#[cfg(feature = "AcceptAttachment")]
pub mod AcceptAttachment;
#[cfg(feature = "AssociateRouteTable")]
pub mod AssociateRouteTable;
#[cfg(feature = "BatchCreateResourceTags")]
pub mod BatchCreateResourceTags;
#[cfg(feature = "ChangeAvailabilityZone")]
pub mod ChangeAvailabilityZone;
#[cfg(feature = "CreateEnterpriseRouter")]
pub mod CreateEnterpriseRouter;
#[cfg(feature = "CreateFlowLog")]
pub mod CreateFlowLog;
#[cfg(feature = "CreateResourceTag")]
pub mod CreateResourceTag;
#[cfg(feature = "CreateRouteTable")]
pub mod CreateRouteTable;
#[cfg(feature = "CreateStaticRoute")]
pub mod CreateStaticRoute;
#[cfg(feature = "CreateVpcAttachment")]
pub mod CreateVpcAttachment;
#[cfg(feature = "DeleteEnterpriseRouter")]
pub mod DeleteEnterpriseRouter;
#[cfg(feature = "DeleteFlowLog")]
pub mod DeleteFlowLog;
#[cfg(feature = "DeleteResourceTag")]
pub mod DeleteResourceTag;
#[cfg(feature = "DeleteRouteTable")]
pub mod DeleteRouteTable;
#[cfg(feature = "DeleteStaticRoute")]
pub mod DeleteStaticRoute;
#[cfg(feature = "DeleteVpcAttachment")]
pub mod DeleteVpcAttachment;
#[cfg(feature = "DisableFlowLog")]
pub mod DisableFlowLog;
#[cfg(feature = "DisablePropagation")]
pub mod DisablePropagation;
#[cfg(feature = "DisassociateRouteTable")]
pub mod DisassociateRouteTable;
#[cfg(feature = "EnableFlowLog")]
pub mod EnableFlowLog;
#[cfg(feature = "EnablePropagation")]
pub mod EnablePropagation;
#[cfg(feature = "ListAssociations")]
pub mod ListAssociations;
#[cfg(feature = "ListAttachments")]
pub mod ListAttachments;
#[cfg(feature = "ListAvailabilityZone")]
pub mod ListAvailabilityZone;
#[cfg(feature = "ListEffectiveRoutes")]
pub mod ListEffectiveRoutes;
#[cfg(feature = "ListEnterpriseRouters")]
pub mod ListEnterpriseRouters;
#[cfg(feature = "ListFlowLogs")]
pub mod ListFlowLogs;
#[cfg(feature = "ListProjectTags")]
pub mod ListProjectTags;
#[cfg(feature = "ListPropagations")]
pub mod ListPropagations;
#[cfg(feature = "ListRouteTables")]
pub mod ListRouteTables;
#[cfg(feature = "ListStaticRoutes")]
pub mod ListStaticRoutes;
#[cfg(feature = "ListVpcAttachments")]
pub mod ListVpcAttachments;
#[cfg(feature = "RejectAttachment")]
pub mod RejectAttachment;
#[cfg(feature = "ShowAttachment")]
pub mod ShowAttachment;
#[cfg(feature = "ShowEnterpriseRouter")]
pub mod ShowEnterpriseRouter;
#[cfg(feature = "ShowFlowLog")]
pub mod ShowFlowLog;
#[cfg(feature = "ShowQuotas")]
pub mod ShowQuotas;
#[cfg(feature = "ShowResourceTag")]
pub mod ShowResourceTag;
#[cfg(feature = "ShowRouteTable")]
pub mod ShowRouteTable;
#[cfg(feature = "ShowStaticRoute")]
pub mod ShowStaticRoute;
#[cfg(feature = "ShowVpcAttachment")]
pub mod ShowVpcAttachment;
#[cfg(feature = "UpdateAttachment")]
pub mod UpdateAttachment;
#[cfg(feature = "UpdateEnterpriseRouter")]
pub mod UpdateEnterpriseRouter;
#[cfg(feature = "UpdateFlowLog")]
pub mod UpdateFlowLog;
#[cfg(feature = "UpdateRouteTable")]
pub mod UpdateRouteTable;
#[cfg(feature = "UpdateStaticRoute")]
pub mod UpdateStaticRoute;
#[cfg(feature = "UpdateVpcAttachment")]
pub mod UpdateVpcAttachment;
