#[cfg(feature = "AddNics")]
pub mod AddNics;
#[cfg(feature = "AssociateSubnet")]
pub mod AssociateSubnet;
#[cfg(feature = "AttachVipBandwidth")]
pub mod AttachVipBandwidth;
#[cfg(feature = "BatchRebootInstance")]
pub mod BatchRebootInstance;
#[cfg(feature = "BatchStartInstance")]
pub mod BatchStartInstance;
#[cfg(feature = "BatchStopInstance")]
pub mod BatchStopInstance;
#[cfg(feature = "ChangeOs")]
pub mod ChangeOs;
#[cfg(feature = "CreateDeployment")]
pub mod CreateDeployment;
#[cfg(feature = "CreateFirewall")]
pub mod CreateFirewall;
#[cfg(feature = "CreateImage")]
pub mod CreateImage;
#[cfg(feature = "CreateInstance")]
pub mod CreateInstance;
#[cfg(feature = "CreateKeypair")]
pub mod CreateKeypair;
#[cfg(feature = "CreatePort")]
pub mod CreatePort;
#[cfg(feature = "CreatePublicIp")]
pub mod CreatePublicIp;
#[cfg(feature = "CreateRoutes")]
pub mod CreateRoutes;
#[cfg(feature = "CreateRoutetable")]
pub mod CreateRoutetable;
#[cfg(feature = "CreateSecurityGroup")]
pub mod CreateSecurityGroup;
#[cfg(feature = "CreateSecurityGroupRule")]
pub mod CreateSecurityGroupRule;
#[cfg(feature = "CreateSubnet")]
pub mod CreateSubnet;
#[cfg(feature = "CreateVpc")]
pub mod CreateVpc;
#[cfg(feature = "DeleteBandwidth")]
pub mod DeleteBandwidth;
#[cfg(feature = "DeleteDeployment")]
pub mod DeleteDeployment;
#[cfg(feature = "DeleteEdgeCloud")]
pub mod DeleteEdgeCloud;
#[cfg(feature = "DeleteFirewall")]
pub mod DeleteFirewall;
#[cfg(feature = "DeleteImage")]
pub mod DeleteImage;
#[cfg(feature = "DeleteInstances")]
pub mod DeleteInstances;
#[cfg(feature = "DeleteKeypair")]
pub mod DeleteKeypair;
#[cfg(feature = "DeletePort")]
pub mod DeletePort;
#[cfg(feature = "DeletePublicIp")]
pub mod DeletePublicIp;
#[cfg(feature = "DeleteRoutes")]
pub mod DeleteRoutes;
#[cfg(feature = "DeleteRoutetable")]
pub mod DeleteRoutetable;
#[cfg(feature = "DeleteSecurityGroup")]
pub mod DeleteSecurityGroup;
#[cfg(feature = "DeleteSecurityGroupRule")]
pub mod DeleteSecurityGroupRule;
#[cfg(feature = "DeleteSubnet")]
pub mod DeleteSubnet;
#[cfg(feature = "DeleteVpc")]
pub mod DeleteVpc;
#[cfg(feature = "DetachVipBandwidth")]
pub mod DetachVipBandwidth;
#[cfg(feature = "DisassociateSubnet")]
pub mod DisassociateSubnet;
#[cfg(feature = "ExecuteDeployment")]
pub mod ExecuteDeployment;
#[cfg(feature = "ExpandEdgecloud")]
pub mod ExpandEdgecloud;
#[cfg(feature = "ListBandwidths")]
pub mod ListBandwidths;
#[cfg(feature = "ListBandwidthTypes")]
pub mod ListBandwidthTypes;
#[cfg(feature = "ListCloudImages")]
pub mod ListCloudImages;
#[cfg(feature = "ListDeployments")]
pub mod ListDeployments;
#[cfg(feature = "ListEdgeCloud")]
pub mod ListEdgeCloud;
#[cfg(feature = "ListFirewalls")]
pub mod ListFirewalls;
#[cfg(feature = "ListFlavors")]
pub mod ListFlavors;
#[cfg(feature = "ListImages")]
pub mod ListImages;
#[cfg(feature = "ListInstances")]
pub mod ListInstances;
#[cfg(feature = "ListKeypairs")]
pub mod ListKeypairs;
#[cfg(feature = "ListPorts")]
pub mod ListPorts;
#[cfg(feature = "ListPublicIps")]
pub mod ListPublicIps;
#[cfg(feature = "ListQuota")]
pub mod ListQuota;
#[cfg(feature = "ListRelatedRoutetables")]
pub mod ListRelatedRoutetables;
#[cfg(feature = "ListRoutes")]
pub mod ListRoutes;
#[cfg(feature = "ListRoutetables")]
pub mod ListRoutetables;
#[cfg(feature = "ListSecurityGroupRules")]
pub mod ListSecurityGroupRules;
#[cfg(feature = "ListSecurityGroups")]
pub mod ListSecurityGroups;
#[cfg(feature = "ListSites")]
pub mod ListSites;
#[cfg(feature = "ListSubnets")]
pub mod ListSubnets;
#[cfg(feature = "ListVolume")]
pub mod ListVolume;
#[cfg(feature = "ListVpcs")]
pub mod ListVpcs;
#[cfg(feature = "RebuildImage")]
pub mod RebuildImage;
#[cfg(feature = "RegisterImage")]
pub mod RegisterImage;
#[cfg(feature = "ShowBandwidth")]
pub mod ShowBandwidth;
#[cfg(feature = "ShowEdgeCloud")]
pub mod ShowEdgeCloud;
#[cfg(feature = "ShowFirewall")]
pub mod ShowFirewall;
#[cfg(feature = "ShowImage")]
pub mod ShowImage;
#[cfg(feature = "ShowInstance")]
pub mod ShowInstance;
#[cfg(feature = "ShowKeypair")]
pub mod ShowKeypair;
#[cfg(feature = "ShowPort")]
pub mod ShowPort;
#[cfg(feature = "ShowPublicIp")]
pub mod ShowPublicIp;
#[cfg(feature = "ShowRoutetable")]
pub mod ShowRoutetable;
#[cfg(feature = "ShowSecurityGroup")]
pub mod ShowSecurityGroup;
#[cfg(feature = "ShowSecurityGroupRule")]
pub mod ShowSecurityGroupRule;
#[cfg(feature = "ShowSubnet")]
pub mod ShowSubnet;
#[cfg(feature = "ShowVolume")]
pub mod ShowVolume;
#[cfg(feature = "ShowVolumeTypes")]
pub mod ShowVolumeTypes;
#[cfg(feature = "ShowVpc")]
pub mod ShowVpc;
#[cfg(feature = "UpdateBandwidth")]
pub mod UpdateBandwidth;
#[cfg(feature = "UpdateFirewall")]
pub mod UpdateFirewall;
#[cfg(feature = "UpdateFirewallRule")]
pub mod UpdateFirewallRule;
#[cfg(feature = "UpdateInstance")]
pub mod UpdateInstance;
#[cfg(feature = "UpdatePort")]
pub mod UpdatePort;
#[cfg(feature = "UpdatePublicIp")]
pub mod UpdatePublicIp;
#[cfg(feature = "UpdateRoutes")]
pub mod UpdateRoutes;
#[cfg(feature = "UpdateRoutetable")]
pub mod UpdateRoutetable;
#[cfg(feature = "UpdateSubnet")]
pub mod UpdateSubnet;
#[cfg(feature = "UpdateVpc")]
pub mod UpdateVpc;
