[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AttachManagedPolicyToPermissionSet = []
AttachRoleToPermissionSet = []
CreateAccountAssignment = []
CreateInstanceAccessControlAttributeConfiguration = []
CreatePermissionSet = []
CreateTagResource = []
DeleteAccountAssignment = []
DeleteCustomPolicyFromPermissionSet = []
DeleteCustomRoleFromPermissionSet = []
DeleteInstanceAccessControlAttributeConfiguration = []
DeletePermissionSet = []
DeleteTagResource = []
DescribeAccountAssignmentCreationStatus = []
DescribeAccountAssignmentDeletionStatus = []
DescribeInstanceAccessControlAttributeConfiguration = []
DescribePermissionSet = []
DescribePermissionSetProvisioningStatus = []
DetachManagedPolicyFromPermissionSet = []
DetachManagedRoleFromPermissionSet = []
GetCustomPolicyForPermissionSet = []
GetCustomRoleForPermissionSet = []
ListAccountAssignmentCreationStatus = []
ListAccountAssignmentDeletionStatus = []
ListAccountAssignments = []
ListAccountsForProvisionedPermissionSet = []
ListInstances = []
ListManagedPoliciesInPermissionSet = []
ListManagedRolesInPermissionSet = []
ListPermissionSetProvisioningStatus = []
ListPermissionSets = []
ListPermissionSetsProvisionedToAccount = []
ListTagResources = []
ProvisionPermissionSet = []
PutCustomPolicyToPermissionSet = []
PutCustomRoleToPermissionSet = []
UpdateInstanceAccessControlAttributeConfiguration = []
UpdatePermissionSet = []
full = ["AttachManagedPolicyToPermissionSet", "AttachRoleToPermissionSet", "CreateAccountAssignment", "CreateInstanceAccessControlAttributeConfiguration", "CreatePermissionSet", "CreateTagResource", "DeleteAccountAssignment", "DeleteCustomPolicyFromPermissionSet", "DeleteCustomRoleFromPermissionSet", "DeleteInstanceAccessControlAttributeConfiguration", "DeletePermissionSet", "DeleteTagResource", "DescribeAccountAssignmentCreationStatus", "DescribeAccountAssignmentDeletionStatus", "DescribeInstanceAccessControlAttributeConfiguration", "DescribePermissionSet", "DescribePermissionSetProvisioningStatus", "DetachManagedPolicyFromPermissionSet", "DetachManagedRoleFromPermissionSet", "GetCustomPolicyForPermissionSet", "GetCustomRoleForPermissionSet", "ListAccountAssignmentCreationStatus", "ListAccountAssignmentDeletionStatus", "ListAccountAssignments", "ListAccountsForProvisionedPermissionSet", "ListInstances", "ListManagedPoliciesInPermissionSet", "ListManagedRolesInPermissionSet", "ListPermissionSetProvisioningStatus", "ListPermissionSets", "ListPermissionSetsProvisionedToAccount", "ListTagResources", "ProvisionPermissionSet", "PutCustomPolicyToPermissionSet", "PutCustomRoleToPermissionSet", "UpdateInstanceAccessControlAttributeConfiguration", "UpdatePermissionSet"]

[lib]
name = "huawei_cloud_api_definitions_IdentityCenter"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-IdentityCenter"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
