[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AttachManagedPolicyToPermissionSet = []
AttachManagedRoleToPermissionSet = []
CreateAccountAssignment = []
CreateAlias = []
CreateApplicationAssignment = []
CreateApplicationInstance = []
CreateApplicationInstanceCertificate = []
CreateInstanceAccessControlAttributeConfiguration = []
CreatePermissionSet = []
CreateTagResource = []
DeleteAccountAssignment = []
DeleteApplicationAssignment = []
DeleteApplicationInstance = []
DeleteApplicationInstanceCertificate = []
DeleteCustomPolicyFromPermissionSet = []
DeleteCustomRoleFromPermissionSet = []
DeleteIdentityCenter = []
DeleteInstanceAccessControlAttributeConfiguration = []
DeletePermissionSet = []
DeleteProfile = []
DeleteTagResource = []
DescribeAccountAssignmentCreationStatus = []
DescribeAccountAssignmentDeletionStatus = []
DescribeApplication = []
DescribeApplicationProvider = []
DescribeInstanceAccessControlAttributeConfiguration = []
DescribePermissionSet = []
DescribePermissionSetProvisioningStatus = []
DescribeRegisteredRegions = []
DetachManagedPolicyFromPermissionSet = []
DetachManagedRoleFromPermissionSet = []
DisassociateProfile = []
GetApplicationAssignmentConfiguration = []
GetApplicationInstance = []
GetCustomPolicyForPermissionSet = []
GetCustomRoleForPermissionSet = []
GetHaConfiguration = []
GetIdentityCenterServiceStatus = []
GetMfaDeviceManagementForIdentityStore = []
GetPermissionSetSummary = []
GetSsoConfiguration = []
ImportApplicationInstanceServiceProviderMetadata = []
ListAccountAssignmentCreationStatus = []
ListAccountAssignmentDeletionStatus = []
ListAccountAssignments = []
ListAccountAssignmentsForPrincipal = []
ListAccountsForProvisionedPermissionSet = []
ListApplicationAssignments = []
ListApplicationAssignmentsForPrincipal = []
ListApplicationInstanceCertificates = []
ListApplicationInstances = []
ListApplicationProviders = []
ListApplicationTemplates = []
ListApplications = []
ListCatalogApplications = []
ListIdentityStoreAssociation = []
ListInstances = []
ListManagedPoliciesInPermissionSet = []
ListManagedRolesInPermissionSet = []
ListPermissionSetProvisioningStatus = []
ListPermissionSets = []
ListPermissionSetsProvisionedToAccount = []
ListProfiles = []
ListTagResources = []
ProvisionPermissionSet = []
PutCustomPolicyToPermissionSet = []
PutCustomRoleToPermissionSet = []
PutMfaDeviceManagementForIdentityStore = []
RegisterRegion = []
StartIdentityCenter = []
UpdateApplicationInstanceActiveCertificate = []
UpdateApplicationInstanceDisplayData = []
UpdateApplicationInstanceResponseConfiguration = []
UpdateApplicationInstanceResponseSchemaConfiguration = []
UpdateApplicationInstanceSecurityConfiguration = []
UpdateApplicationInstanceServiceProviderConfiguration = []
UpdateApplicationInstanceStatus = []
UpdateHaConfiguration = []
UpdateInstanceAccessControlAttributeConfiguration = []
UpdatePermissionSet = []
UpdateSsoConfiguration = []
full = ["AttachManagedPolicyToPermissionSet", "AttachManagedRoleToPermissionSet", "CreateAccountAssignment", "CreateAlias", "CreateApplicationAssignment", "CreateApplicationInstance", "CreateApplicationInstanceCertificate", "CreateInstanceAccessControlAttributeConfiguration", "CreatePermissionSet", "CreateTagResource", "DeleteAccountAssignment", "DeleteApplicationAssignment", "DeleteApplicationInstance", "DeleteApplicationInstanceCertificate", "DeleteCustomPolicyFromPermissionSet", "DeleteCustomRoleFromPermissionSet", "DeleteIdentityCenter", "DeleteInstanceAccessControlAttributeConfiguration", "DeletePermissionSet", "DeleteProfile", "DeleteTagResource", "DescribeAccountAssignmentCreationStatus", "DescribeAccountAssignmentDeletionStatus", "DescribeApplication", "DescribeApplicationProvider", "DescribeInstanceAccessControlAttributeConfiguration", "DescribePermissionSet", "DescribePermissionSetProvisioningStatus", "DescribeRegisteredRegions", "DetachManagedPolicyFromPermissionSet", "DetachManagedRoleFromPermissionSet", "DisassociateProfile", "GetApplicationAssignmentConfiguration", "GetApplicationInstance", "GetCustomPolicyForPermissionSet", "GetCustomRoleForPermissionSet", "GetHaConfiguration", "GetIdentityCenterServiceStatus", "GetMfaDeviceManagementForIdentityStore", "GetPermissionSetSummary", "GetSsoConfiguration", "ImportApplicationInstanceServiceProviderMetadata", "ListAccountAssignmentCreationStatus", "ListAccountAssignmentDeletionStatus", "ListAccountAssignments", "ListAccountAssignmentsForPrincipal", "ListAccountsForProvisionedPermissionSet", "ListApplicationAssignments", "ListApplicationAssignmentsForPrincipal", "ListApplicationInstanceCertificates", "ListApplicationInstances", "ListApplicationProviders", "ListApplications", "ListApplicationTemplates", "ListCatalogApplications", "ListIdentityStoreAssociation", "ListInstances", "ListManagedPoliciesInPermissionSet", "ListManagedRolesInPermissionSet", "ListPermissionSetProvisioningStatus", "ListPermissionSets", "ListPermissionSetsProvisionedToAccount", "ListProfiles", "ListTagResources", "ProvisionPermissionSet", "PutCustomPolicyToPermissionSet", "PutCustomRoleToPermissionSet", "PutMfaDeviceManagementForIdentityStore", "RegisterRegion", "StartIdentityCenter", "UpdateApplicationInstanceActiveCertificate", "UpdateApplicationInstanceDisplayData", "UpdateApplicationInstanceResponseConfiguration", "UpdateApplicationInstanceResponseSchemaConfiguration", "UpdateApplicationInstanceSecurityConfiguration", "UpdateApplicationInstanceServiceProviderConfiguration", "UpdateApplicationInstanceStatus", "UpdateHaConfiguration", "UpdateInstanceAccessControlAttributeConfiguration", "UpdatePermissionSet", "UpdateSsoConfiguration"]

[lib]
name = "huawei_cloud_api_definitions_IdentityCenter"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-IdentityCenter"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
