#[cfg(feature = "BatchCreateDeleteNatGatewayTag")]
pub mod BatchCreateDeleteNatGatewayTag;
#[cfg(feature = "BatchCreateDeletePrivateNatTags")]
pub mod BatchCreateDeletePrivateNatTags;
#[cfg(feature = "BatchCreateDeleteTransitIpTags")]
pub mod BatchCreateDeleteTransitIpTags;
#[cfg(feature = "BatchCreateNatGatewayDnatRules")]
pub mod BatchCreateNatGatewayDnatRules;
#[cfg(feature = "CreateNatGateway")]
pub mod CreateNatGateway;
#[cfg(feature = "CreateNatGatewayDnatRule")]
pub mod CreateNatGatewayDnatRule;
#[cfg(feature = "CreateNatGatewaySnatRule")]
pub mod CreateNatGatewaySnatRule;
#[cfg(feature = "CreateNatGatewayTag")]
pub mod CreateNatGatewayTag;
#[cfg(feature = "CreatePrivateDnat")]
pub mod CreatePrivateDnat;
#[cfg(feature = "CreatePrivateNat")]
pub mod CreatePrivateNat;
#[cfg(feature = "CreatePrivateNatTag")]
pub mod CreatePrivateNatTag;
#[cfg(feature = "CreatePrivateSnat")]
pub mod CreatePrivateSnat;
#[cfg(feature = "CreateTransitIp")]
pub mod CreateTransitIp;
#[cfg(feature = "CreateTransitIpTag")]
pub mod CreateTransitIpTag;
#[cfg(feature = "DeleteNatGateway")]
pub mod DeleteNatGateway;
#[cfg(feature = "DeleteNatGatewayDnatRule")]
pub mod DeleteNatGatewayDnatRule;
#[cfg(feature = "DeleteNatGatewaySnatRule")]
pub mod DeleteNatGatewaySnatRule;
#[cfg(feature = "DeleteNatGatewayTag")]
pub mod DeleteNatGatewayTag;
#[cfg(feature = "DeletePrivateDnat")]
pub mod DeletePrivateDnat;
#[cfg(feature = "DeletePrivateNat")]
pub mod DeletePrivateNat;
#[cfg(feature = "DeletePrivateNatTag")]
pub mod DeletePrivateNatTag;
#[cfg(feature = "DeletePrivateSnat")]
pub mod DeletePrivateSnat;
#[cfg(feature = "DeleteTransitIp")]
pub mod DeleteTransitIp;
#[cfg(feature = "DeleteTransitIpTag")]
pub mod DeleteTransitIpTag;
#[cfg(feature = "ListNatGatewayByTag")]
pub mod ListNatGatewayByTag;
#[cfg(feature = "ListNatGatewayDnatRules")]
pub mod ListNatGatewayDnatRules;
#[cfg(feature = "ListNatGateways")]
pub mod ListNatGateways;
#[cfg(feature = "ListNatGatewaySnatRules")]
pub mod ListNatGatewaySnatRules;
#[cfg(feature = "ListNatGatewayTag")]
pub mod ListNatGatewayTag;
#[cfg(feature = "ListPrivateDnats")]
pub mod ListPrivateDnats;
#[cfg(feature = "ListPrivateNats")]
pub mod ListPrivateNats;
#[cfg(feature = "ListPrivateNatsByTags")]
pub mod ListPrivateNatsByTags;
#[cfg(feature = "ListPrivateNatTags")]
pub mod ListPrivateNatTags;
#[cfg(feature = "ListPrivateSnats")]
pub mod ListPrivateSnats;
#[cfg(feature = "ListTransitIps")]
pub mod ListTransitIps;
#[cfg(feature = "ListTransitIpsByTags")]
pub mod ListTransitIpsByTags;
#[cfg(feature = "ListTransitIpTags")]
pub mod ListTransitIpTags;
#[cfg(feature = "ShowNatGateway")]
pub mod ShowNatGateway;
#[cfg(feature = "ShowNatGatewayDnatRule")]
pub mod ShowNatGatewayDnatRule;
#[cfg(feature = "ShowNatGatewaySnatRule")]
pub mod ShowNatGatewaySnatRule;
#[cfg(feature = "ShowNatGatewayTag")]
pub mod ShowNatGatewayTag;
#[cfg(feature = "ShowPrivateDnat")]
pub mod ShowPrivateDnat;
#[cfg(feature = "ShowPrivateNat")]
pub mod ShowPrivateNat;
#[cfg(feature = "ShowPrivateNatTags")]
pub mod ShowPrivateNatTags;
#[cfg(feature = "ShowPrivateSnat")]
pub mod ShowPrivateSnat;
#[cfg(feature = "ShowTransitIp")]
pub mod ShowTransitIp;
#[cfg(feature = "ShowTransitIpTags")]
pub mod ShowTransitIpTags;
#[cfg(feature = "UpdateNatGatewayDnatRule")]
pub mod UpdateNatGatewayDnatRule;
#[cfg(feature = "UpdateNatGatewaySnatRule")]
pub mod UpdateNatGatewaySnatRule;
#[cfg(feature = "UpdatePrivateDnat")]
pub mod UpdatePrivateDnat;
#[cfg(feature = "UpdatePrivateNat")]
pub mod UpdatePrivateNat;
#[cfg(feature = "UpdatePrivateSnat")]
pub mod UpdatePrivateSnat;
