#[cfg(feature = "BatchSaveAuth")]
pub mod BatchSaveAuth;
#[cfg(feature = "CreateWorkspace")]
pub mod CreateWorkspace;
#[cfg(feature = "DeleteWorkspace")]
pub mod DeleteWorkspace;
#[cfg(feature = "ListAuthed")]
pub mod ListAuthed;
#[cfg(feature = "ListAuthProperties")]
pub mod ListAuthProperties;
#[cfg(feature = "ListWorkspaces")]
pub mod ListWorkspaces;
#[cfg(feature = "SaveOrUpdateAuthProperties")]
pub mod SaveOrUpdateAuthProperties;
#[cfg(feature = "UpdateWorkspace")]
pub mod UpdateWorkspace;
