#[cfg(feature = "AcceptManualReview")]
pub mod AcceptManualReview;
#[cfg(feature = "BatchMovePipelineToGroup")]
pub mod BatchMovePipelineToGroup;
#[cfg(feature = "BatchShowPipelinesLatestStatus")]
pub mod BatchShowPipelinesLatestStatus;
#[cfg(feature = "BatchShowPipelinesStatus")]
pub mod BatchShowPipelinesStatus;
#[cfg(feature = "CreateBasicPlugin")]
pub mod CreateBasicPlugin;
#[cfg(feature = "CreatePipelineByTemplate")]
pub mod CreatePipelineByTemplate;
#[cfg(feature = "CreatePipelineByTemplateId")]
pub mod CreatePipelineByTemplateId;
#[cfg(feature = "CreatePipelineGroup")]
pub mod CreatePipelineGroup;
#[cfg(feature = "CreatePipelineNew")]
pub mod CreatePipelineNew;
#[cfg(feature = "CreatePipelineTemplate")]
pub mod CreatePipelineTemplate;
#[cfg(feature = "CreatePluginDraft")]
pub mod CreatePluginDraft;
#[cfg(feature = "CreatePluginVersion")]
pub mod CreatePluginVersion;
#[cfg(feature = "CreatePublisher")]
pub mod CreatePublisher;
#[cfg(feature = "CreateRule")]
pub mod CreateRule;
#[cfg(feature = "CreateStrategy")]
pub mod CreateStrategy;
#[cfg(feature = "DeleteBasicPlugin")]
pub mod DeleteBasicPlugin;
#[cfg(feature = "DeletePipeline")]
pub mod DeletePipeline;
#[cfg(feature = "DeletePipelineGroup")]
pub mod DeletePipelineGroup;
#[cfg(feature = "DeletePipelineTemplate")]
pub mod DeletePipelineTemplate;
#[cfg(feature = "DeletePluginDraft")]
pub mod DeletePluginDraft;
#[cfg(feature = "DeletePublisher")]
pub mod DeletePublisher;
#[cfg(feature = "DeleteRule")]
pub mod DeleteRule;
#[cfg(feature = "DeleteStrategy")]
pub mod DeleteStrategy;
#[cfg(feature = "ListAvailablePublisher")]
pub mod ListAvailablePublisher;
#[cfg(feature = "ListBasePlugins")]
pub mod ListBasePlugins;
#[cfg(feature = "ListBasePluginsNewPost")]
pub mod ListBasePluginsNewPost;
#[cfg(feature = "ListPipelineRuns")]
pub mod ListPipelineRuns;
#[cfg(feature = "ListPipelines")]
pub mod ListPipelines;
#[cfg(feature = "ListPipelineSimpleInfo")]
pub mod ListPipelineSimpleInfo;
#[cfg(feature = "ListPipelineTemplates")]
pub mod ListPipelineTemplates;
#[cfg(feature = "ListPipleineBuildResult")]
pub mod ListPipleineBuildResult;
#[cfg(feature = "ListPlugins")]
pub mod ListPlugins;
#[cfg(feature = "ListPLuginVersion")]
pub mod ListPLuginVersion;
#[cfg(feature = "ListPluginVersionNumber")]
pub mod ListPluginVersionNumber;
#[cfg(feature = "ListProjectStrategy")]
pub mod ListProjectStrategy;
#[cfg(feature = "ListPublisher")]
pub mod ListPublisher;
#[cfg(feature = "ListRule")]
pub mod ListRule;
#[cfg(feature = "ListStagePlugins")]
pub mod ListStagePlugins;
#[cfg(feature = "ListStrategy")]
pub mod ListStrategy;
#[cfg(feature = "ListTemplates")]
pub mod ListTemplates;
#[cfg(feature = "PublishPlugin")]
pub mod PublishPlugin;
#[cfg(feature = "PublishPluginBind")]
pub mod PublishPluginBind;
#[cfg(feature = "PublishPluginDraft")]
pub mod PublishPluginDraft;
#[cfg(feature = "RejectManualReview")]
pub mod RejectManualReview;
#[cfg(feature = "RemovePipeline")]
pub mod RemovePipeline;
#[cfg(feature = "RetryPipelineRun")]
pub mod RetryPipelineRun;
#[cfg(feature = "RunPipeline")]
pub mod RunPipeline;
#[cfg(feature = "ShowBasicPlugin")]
pub mod ShowBasicPlugin;
#[cfg(feature = "ShowInstanceStatus")]
pub mod ShowInstanceStatus;
#[cfg(feature = "ShowPipelineDetail")]
pub mod ShowPipelineDetail;
#[cfg(feature = "ShowPipelineGroupTree")]
pub mod ShowPipelineGroupTree;
#[cfg(feature = "ShowPipelineLog")]
pub mod ShowPipelineLog;
#[cfg(feature = "ShowPipelineRunDetail")]
pub mod ShowPipelineRunDetail;
#[cfg(feature = "ShowPipelineTemplateDetail")]
pub mod ShowPipelineTemplateDetail;
#[cfg(feature = "ShowPipleineStatus")]
pub mod ShowPipleineStatus;
#[cfg(feature = "ShowPluginInputs")]
pub mod ShowPluginInputs;
#[cfg(feature = "ShowPluginMetrics")]
pub mod ShowPluginMetrics;
#[cfg(feature = "ShowPluginOutputs")]
pub mod ShowPluginOutputs;
#[cfg(feature = "ShowPluginVersion")]
pub mod ShowPluginVersion;
#[cfg(feature = "ShowProjectStrategy")]
pub mod ShowProjectStrategy;
#[cfg(feature = "ShowPublisher")]
pub mod ShowPublisher;
#[cfg(feature = "ShowRule")]
pub mod ShowRule;
#[cfg(feature = "ShowStrategy")]
pub mod ShowStrategy;
#[cfg(feature = "ShowTemplateDetail")]
pub mod ShowTemplateDetail;
#[cfg(feature = "StartNewPipeline")]
pub mod StartNewPipeline;
#[cfg(feature = "StopPipelineNew")]
pub mod StopPipelineNew;
#[cfg(feature = "StopPipelineRun")]
pub mod StopPipelineRun;
#[cfg(feature = "SwitchStrategy")]
pub mod SwitchStrategy;
#[cfg(feature = "UpdateBasicPlugin")]
pub mod UpdateBasicPlugin;
#[cfg(feature = "UpdatePipelineGroup")]
pub mod UpdatePipelineGroup;
#[cfg(feature = "UpdatePipelineTemplate")]
pub mod UpdatePipelineTemplate;
#[cfg(feature = "UpdatePluginBaseInfo")]
pub mod UpdatePluginBaseInfo;
#[cfg(feature = "UpdatePluginDraft")]
pub mod UpdatePluginDraft;
#[cfg(feature = "UpdateRule")]
pub mod UpdateRule;
#[cfg(feature = "UpdateStrategy")]
pub mod UpdateStrategy;
#[cfg(feature = "UploadBasicPlugin")]
pub mod UploadBasicPlugin;
#[cfg(feature = "UploadPluginIcon")]
pub mod UploadPluginIcon;
#[cfg(feature = "UploadPublisherIcon")]
pub mod UploadPublisherIcon;
