#[cfg(feature = "ListAgents")]
pub mod ListAgents;
#[cfg(feature = "ListAuditInfo")]
pub mod ListAuditInfo;
#[cfg(feature = "ListFlJob")]
pub mod ListFlJob;
#[cfg(feature = "ListInstanceHistory")]
pub mod ListInstanceHistory;
#[cfg(feature = "ListLeagueDatasets")]
pub mod ListLeagueDatasets;
#[cfg(feature = "ListLeagues")]
pub mod ListLeagues;
#[cfg(feature = "ListNodes")]
pub mod ListNodes;
#[cfg(feature = "ListNotices")]
pub mod ListNotices;
#[cfg(feature = "ListPartners")]
pub mod ListPartners;
#[cfg(feature = "ListSqlJob")]
pub mod ListSqlJob;
#[cfg(feature = "ShowAgentDetail")]
pub mod ShowAgentDetail;
#[cfg(feature = "ShowDatasetStatistics")]
pub mod ShowDatasetStatistics;
#[cfg(feature = "ShowInstanceReport")]
pub mod ShowInstanceReport;
#[cfg(feature = "ShowJobInstanceDag")]
pub mod ShowJobInstanceDag;
#[cfg(feature = "ShowJobStatistics")]
pub mod ShowJobStatistics;
#[cfg(feature = "ShowLeague")]
pub mod ShowLeague;
#[cfg(feature = "ShowOverview")]
pub mod ShowOverview;
#[cfg(feature = "ShowPartnerStatistics")]
pub mod ShowPartnerStatistics;
#[cfg(feature = "UpdateLeague")]
pub mod UpdateLeague;
