#[cfg(feature = "BatchCopyDomain")]
pub mod BatchCopyDomain;
#[cfg(feature = "BatchDeleteTags")]
pub mod BatchDeleteTags;
#[cfg(feature = "CreateDomain")]
pub mod CreateDomain;
#[cfg(feature = "CreatePreheatingTasks")]
pub mod CreatePreheatingTasks;
#[cfg(feature = "CreateRefreshTasks")]
pub mod CreateRefreshTasks;
#[cfg(feature = "CreateTags")]
pub mod CreateTags;
#[cfg(feature = "DeleteDomain")]
pub mod DeleteDomain;
#[cfg(feature = "DisableDomain")]
pub mod DisableDomain;
#[cfg(feature = "DownloadRegionCarrierExcel")]
pub mod DownloadRegionCarrierExcel;
#[cfg(feature = "DownloadStatisticsExcel")]
pub mod DownloadStatisticsExcel;
#[cfg(feature = "EnableDomain")]
pub mod EnableDomain;
#[cfg(feature = "ListCdnDomainTopRefers")]
pub mod ListCdnDomainTopRefers;
#[cfg(feature = "ListDomains")]
pub mod ListDomains;
#[cfg(feature = "SetChargeModes")]
pub mod SetChargeModes;
#[cfg(feature = "ShowBandwidthCalc")]
pub mod ShowBandwidthCalc;
#[cfg(feature = "ShowBlackWhiteList")]
pub mod ShowBlackWhiteList;
#[cfg(feature = "ShowCacheRules")]
pub mod ShowCacheRules;
#[cfg(feature = "ShowCertificatesHttpsInfo")]
pub mod ShowCertificatesHttpsInfo;
#[cfg(feature = "ShowChargeModes")]
pub mod ShowChargeModes;
#[cfg(feature = "ShowDomainDetail")]
pub mod ShowDomainDetail;
#[cfg(feature = "ShowDomainDetailByName")]
pub mod ShowDomainDetailByName;
#[cfg(feature = "ShowDomainFullConfig")]
pub mod ShowDomainFullConfig;
#[cfg(feature = "ShowDomainLocationStats")]
pub mod ShowDomainLocationStats;
#[cfg(feature = "ShowDomainStats")]
pub mod ShowDomainStats;
#[cfg(feature = "ShowHistoryTaskDetails")]
pub mod ShowHistoryTaskDetails;
#[cfg(feature = "ShowHistoryTasks")]
pub mod ShowHistoryTasks;
#[cfg(feature = "ShowHttpInfo")]
pub mod ShowHttpInfo;
#[cfg(feature = "ShowIpInfo")]
pub mod ShowIpInfo;
#[cfg(feature = "ShowLogs")]
pub mod ShowLogs;
#[cfg(feature = "ShowOriginHost")]
pub mod ShowOriginHost;
#[cfg(feature = "ShowQuota")]
pub mod ShowQuota;
#[cfg(feature = "ShowRefer")]
pub mod ShowRefer;
#[cfg(feature = "ShowResponseHeader")]
pub mod ShowResponseHeader;
#[cfg(feature = "ShowTags")]
pub mod ShowTags;
#[cfg(feature = "ShowTopDomainNames")]
pub mod ShowTopDomainNames;
#[cfg(feature = "ShowTopUrl")]
pub mod ShowTopUrl;
#[cfg(feature = "ShowUrlTaskInfo")]
pub mod ShowUrlTaskInfo;
#[cfg(feature = "ShowVerifyDomainOwnerInfo")]
pub mod ShowVerifyDomainOwnerInfo;
#[cfg(feature = "UpdateBlackWhiteList")]
pub mod UpdateBlackWhiteList;
#[cfg(feature = "UpdateCacheRules")]
pub mod UpdateCacheRules;
#[cfg(feature = "UpdateDomainFullConfig")]
pub mod UpdateDomainFullConfig;
#[cfg(feature = "UpdateDomainMultiCertificates")]
pub mod UpdateDomainMultiCertificates;
#[cfg(feature = "UpdateDomainOrigin")]
pub mod UpdateDomainOrigin;
#[cfg(feature = "UpdateFollow302Switch")]
pub mod UpdateFollow302Switch;
#[cfg(feature = "UpdateHttpsInfo")]
pub mod UpdateHttpsInfo;
#[cfg(feature = "UpdateOriginHost")]
pub mod UpdateOriginHost;
#[cfg(feature = "UpdatePrivateBucketAccess")]
pub mod UpdatePrivateBucketAccess;
#[cfg(feature = "UpdateRangeSwitch")]
pub mod UpdateRangeSwitch;
#[cfg(feature = "UpdateRefer")]
pub mod UpdateRefer;
#[cfg(feature = "UpdateResponseHeader")]
pub mod UpdateResponseHeader;
#[cfg(feature = "VerifyDomainOwner")]
pub mod VerifyDomainOwner;
