#[cfg(feature = "ApplyDomainTemplate")]
pub mod ApplyDomainTemplate;
#[cfg(feature = "BatchCopyDomain")]
pub mod BatchCopyDomain;
#[cfg(feature = "BatchDeleteTags")]
pub mod BatchDeleteTags;
#[cfg(feature = "BatchUpdateRuleStatus")]
pub mod BatchUpdateRuleStatus;
#[cfg(feature = "CreateDomain")]
pub mod CreateDomain;
#[cfg(feature = "CreateDomainTemplate")]
pub mod CreateDomainTemplate;
#[cfg(feature = "CreatePreheatingTasks")]
pub mod CreatePreheatingTasks;
#[cfg(feature = "CreateRefreshTasks")]
pub mod CreateRefreshTasks;
#[cfg(feature = "CreateRuleNew")]
pub mod CreateRuleNew;
#[cfg(feature = "CreateShareCacheGroups")]
pub mod CreateShareCacheGroups;
#[cfg(feature = "CreateSubscriptionTask")]
pub mod CreateSubscriptionTask;
#[cfg(feature = "CreateTags")]
pub mod CreateTags;
#[cfg(feature = "DeleteDomain")]
pub mod DeleteDomain;
#[cfg(feature = "DeleteDomainTemplate")]
pub mod DeleteDomainTemplate;
#[cfg(feature = "DeleteRuleNew")]
pub mod DeleteRuleNew;
#[cfg(feature = "DeleteShareCacheGroups")]
pub mod DeleteShareCacheGroups;
#[cfg(feature = "DeleteSubscriptionTask")]
pub mod DeleteSubscriptionTask;
#[cfg(feature = "DisableDomain")]
pub mod DisableDomain;
#[cfg(feature = "DownloadRegionCarrierExcel")]
pub mod DownloadRegionCarrierExcel;
#[cfg(feature = "DownloadStatisticsExcel")]
pub mod DownloadStatisticsExcel;
#[cfg(feature = "EnableDomain")]
pub mod EnableDomain;
#[cfg(feature = "ListCdnDomainTopIps")]
pub mod ListCdnDomainTopIps;
#[cfg(feature = "ListCdnDomainTopOriginUrl")]
pub mod ListCdnDomainTopOriginUrl;
#[cfg(feature = "ListCdnDomainTopRefers")]
pub mod ListCdnDomainTopRefers;
#[cfg(feature = "ListCdnDomainTopUas")]
pub mod ListCdnDomainTopUas;
#[cfg(feature = "ListDomainClientStats")]
pub mod ListDomainClientStats;
#[cfg(feature = "ListDomains")]
pub mod ListDomains;
#[cfg(feature = "ListRuleDetails")]
pub mod ListRuleDetails;
#[cfg(feature = "ListShareCacheGroups")]
pub mod ListShareCacheGroups;
#[cfg(feature = "ListSubscriptionTasks")]
pub mod ListSubscriptionTasks;
#[cfg(feature = "ModifyAccountInfo")]
pub mod ModifyAccountInfo;
#[cfg(feature = "SetChargeModes")]
pub mod SetChargeModes;
#[cfg(feature = "SetStatsConfig")]
pub mod SetStatsConfig;
#[cfg(feature = "ShowAppliedTemplateRecord")]
pub mod ShowAppliedTemplateRecord;
#[cfg(feature = "ShowBandwidthCalc")]
pub mod ShowBandwidthCalc;
#[cfg(feature = "ShowBlackWhiteList")]
pub mod ShowBlackWhiteList;
#[cfg(feature = "ShowCacheRules")]
pub mod ShowCacheRules;
#[cfg(feature = "ShowCertificatesHttpsInfo")]
pub mod ShowCertificatesHttpsInfo;
#[cfg(feature = "ShowChargeModes")]
pub mod ShowChargeModes;
#[cfg(feature = "ShowDomainDetail")]
pub mod ShowDomainDetail;
#[cfg(feature = "ShowDomainDetailByName")]
pub mod ShowDomainDetailByName;
#[cfg(feature = "ShowDomainFullConfig")]
pub mod ShowDomainFullConfig;
#[cfg(feature = "ShowDomainLocationStats")]
pub mod ShowDomainLocationStats;
#[cfg(feature = "ShowDomainStats")]
pub mod ShowDomainStats;
#[cfg(feature = "ShowDomainTemplate")]
pub mod ShowDomainTemplate;
#[cfg(feature = "ShowHistoryTaskDetails")]
pub mod ShowHistoryTaskDetails;
#[cfg(feature = "ShowHistoryTasks")]
pub mod ShowHistoryTasks;
#[cfg(feature = "ShowHttpInfo")]
pub mod ShowHttpInfo;
#[cfg(feature = "ShowIpInfo")]
pub mod ShowIpInfo;
#[cfg(feature = "ShowLogs")]
pub mod ShowLogs;
#[cfg(feature = "ShowOriginHost")]
pub mod ShowOriginHost;
#[cfg(feature = "ShowQuota")]
pub mod ShowQuota;
#[cfg(feature = "ShowRefer")]
pub mod ShowRefer;
#[cfg(feature = "ShowResponseHeader")]
pub mod ShowResponseHeader;
#[cfg(feature = "ShowStatsConfigs")]
pub mod ShowStatsConfigs;
#[cfg(feature = "ShowTags")]
pub mod ShowTags;
#[cfg(feature = "ShowTopDomainNames")]
pub mod ShowTopDomainNames;
#[cfg(feature = "ShowTopUrl")]
pub mod ShowTopUrl;
#[cfg(feature = "ShowUrlTaskInfo")]
pub mod ShowUrlTaskInfo;
#[cfg(feature = "ShowVerifyDomainOwnerInfo")]
pub mod ShowVerifyDomainOwnerInfo;
#[cfg(feature = "UpdateBlackWhiteList")]
pub mod UpdateBlackWhiteList;
#[cfg(feature = "UpdateCacheRules")]
pub mod UpdateCacheRules;
#[cfg(feature = "UpdateDomainFullConfig")]
pub mod UpdateDomainFullConfig;
#[cfg(feature = "UpdateDomainMultiCertificates")]
pub mod UpdateDomainMultiCertificates;
#[cfg(feature = "UpdateDomainOrigin")]
pub mod UpdateDomainOrigin;
#[cfg(feature = "UpdateDomainTemplate")]
pub mod UpdateDomainTemplate;
#[cfg(feature = "UpdateFollow302Switch")]
pub mod UpdateFollow302Switch;
#[cfg(feature = "UpdateFullRule")]
pub mod UpdateFullRule;
#[cfg(feature = "UpdateHttpsInfo")]
pub mod UpdateHttpsInfo;
#[cfg(feature = "UpdateOriginHost")]
pub mod UpdateOriginHost;
#[cfg(feature = "UpdatePrivateBucketAccess")]
pub mod UpdatePrivateBucketAccess;
#[cfg(feature = "UpdateRangeSwitch")]
pub mod UpdateRangeSwitch;
#[cfg(feature = "UpdateRefer")]
pub mod UpdateRefer;
#[cfg(feature = "UpdateResponseHeader")]
pub mod UpdateResponseHeader;
#[cfg(feature = "UpdateRuleNew")]
pub mod UpdateRuleNew;
#[cfg(feature = "UpdateShareCacheGroups")]
pub mod UpdateShareCacheGroups;
#[cfg(feature = "UpdateSubscriptionTask")]
pub mod UpdateSubscriptionTask;
#[cfg(feature = "VerifyDomainOwner")]
pub mod VerifyDomainOwner;
