[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
ChangeAlert = []
ChangeIncident = []
ChangePlaybookInstance = []
CheckProductHealthy = []
CopyPlaybookVersion = []
CreateAlert = []
CreateAlertRule = []
CreateAlertRuleSimulation = []
CreateBatchOrderAlerts = []
CreateDataobjectRelation = []
CreateIncident = []
CreateIndicator = []
CreatePlaybook = []
CreatePlaybookAction = []
CreatePlaybookApprove = []
CreatePlaybookRule = []
CreatePlaybookVersion = []
DeleteAlert = []
DeleteAlertRule = []
DeleteDataobjectRelation = []
DeleteIncident = []
DeleteIndicator = []
DeletePlaybook = []
DeletePlaybookAction = []
DeletePlaybookRule = []
DeletePlaybookVersion = []
DisableAlertRule = []
EnableAlertRule = []
ImportEvents = []
ListAlertRuleMetrics = []
ListAlertRuleTemplates = []
ListAlertRules = []
ListAlerts = []
ListDataobjectRelation = []
ListIncidentTypes = []
ListIncidents = []
ListIndicators = []
ListPlaybookActions = []
ListPlaybookApproves = []
ListPlaybookAuditLogs = []
ListPlaybookInstances = []
ListPlaybookVersions = []
ListPlaybooks = []
ShowAlert = []
ShowAlertRule = []
ShowAlertRuleTemplate = []
ShowIncident = []
ShowIndicatorDetail = []
ShowPlaybook = []
ShowPlaybookInstance = []
ShowPlaybookMonitors = []
ShowPlaybookRule = []
ShowPlaybookStatistics = []
ShowPlaybookTopology = []
ShowPlaybookVersion = []
UpdateAlertRule = []
UpdateIndicator = []
UpdatePlaybook = []
UpdatePlaybookAction = []
UpdatePlaybookRule = []
UpdatePlaybookVersion = []
full = ["ChangeAlert", "ChangeIncident", "ChangePlaybookInstance", "CheckProductHealthy", "CopyPlaybookVersion", "CreateAlert", "CreateAlertRule", "CreateAlertRuleSimulation", "CreateBatchOrderAlerts", "CreateDataobjectRelation", "CreateIncident", "CreateIndicator", "CreatePlaybook", "CreatePlaybookAction", "CreatePlaybookApprove", "CreatePlaybookRule", "CreatePlaybookVersion", "DeleteAlert", "DeleteAlertRule", "DeleteDataobjectRelation", "DeleteIncident", "DeleteIndicator", "DeletePlaybook", "DeletePlaybookAction", "DeletePlaybookRule", "DeletePlaybookVersion", "DisableAlertRule", "EnableAlertRule", "ImportEvents", "ListAlertRuleMetrics", "ListAlertRules", "ListAlertRuleTemplates", "ListAlerts", "ListDataobjectRelation", "ListIncidents", "ListIncidentTypes", "ListIndicators", "ListPlaybookActions", "ListPlaybookApproves", "ListPlaybookAuditLogs", "ListPlaybookInstances", "ListPlaybooks", "ListPlaybookVersions", "ShowAlert", "ShowAlertRule", "ShowAlertRuleTemplate", "ShowIncident", "ShowIndicatorDetail", "ShowPlaybook", "ShowPlaybookInstance", "ShowPlaybookMonitors", "ShowPlaybookRule", "ShowPlaybookStatistics", "ShowPlaybookTopology", "ShowPlaybookVersion", "UpdateAlertRule", "UpdateIndicator", "UpdatePlaybook", "UpdatePlaybookAction", "UpdatePlaybookRule", "UpdatePlaybookVersion"]

[lib]
name = "huawei_cloud_api_definitions_SA"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-SA"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
