#[cfg(feature = "CheckPermission")]
pub mod CheckPermission;
#[cfg(feature = "CommitSyntaxConversion")]
pub mod CommitSyntaxConversion;
#[cfg(feature = "CommitVerification")]
pub mod CommitVerification;
#[cfg(feature = "ConfirmTargetDbType")]
pub mod ConfirmTargetDbType;
#[cfg(feature = "CreateEvaluationProject")]
pub mod CreateEvaluationProject;
#[cfg(feature = "CreateMigrationProject")]
pub mod CreateMigrationProject;
#[cfg(feature = "DeleteEvaluationProject")]
pub mod DeleteEvaluationProject;
#[cfg(feature = "DeleteMigrationProject")]
pub mod DeleteMigrationProject;
#[cfg(feature = "DownloadFailureReport")]
pub mod DownloadFailureReport;
#[cfg(feature = "ListApiVersions")]
pub mod ListApiVersions;
#[cfg(feature = "ListEvaluationProjects")]
pub mod ListEvaluationProjects;
#[cfg(feature = "ListMigrationProjects")]
pub mod ListMigrationProjects;
#[cfg(feature = "ListPermissionCheckResult")]
pub mod ListPermissionCheckResult;
#[cfg(feature = "ListQuotas")]
pub mod ListQuotas;
#[cfg(feature = "ListSyntaxConversionProgress")]
pub mod ListSyntaxConversionProgress;
#[cfg(feature = "ListVerificationProgress")]
pub mod ListVerificationProgress;
#[cfg(feature = "RunSqlConversion")]
pub mod RunSqlConversion;
#[cfg(feature = "ShowApiVersionInfo")]
pub mod ShowApiVersionInfo;
#[cfg(feature = "ShowEvaluationProjectDetail")]
pub mod ShowEvaluationProjectDetail;
#[cfg(feature = "ShowEvaluationProjectStatus")]
pub mod ShowEvaluationProjectStatus;
#[cfg(feature = "ShowMigrationProjectDetail")]
pub mod ShowMigrationProjectDetail;
#[cfg(feature = "ShowMigrationProjectStatus")]
pub mod ShowMigrationProjectStatus;
