#[cfg(feature = "CheckNetAcl")]
pub mod CheckNetAcl;
#[cfg(feature = "CollectLog")]
pub mod CollectLog;
#[cfg(feature = "CreateMigproject")]
pub mod CreateMigproject;
#[cfg(feature = "CreatePrivacyAgreements")]
pub mod CreatePrivacyAgreements;
#[cfg(feature = "CreateTask")]
pub mod CreateTask;
#[cfg(feature = "CreateTemplate")]
pub mod CreateTemplate;
#[cfg(feature = "DeleteMigproject")]
pub mod DeleteMigproject;
#[cfg(feature = "DeleteServer")]
pub mod DeleteServer;
#[cfg(feature = "DeleteServers")]
pub mod DeleteServers;
#[cfg(feature = "DeleteTask")]
pub mod DeleteTask;
#[cfg(feature = "DeleteTasks")]
pub mod DeleteTasks;
#[cfg(feature = "DeleteTemplate")]
pub mod DeleteTemplate;
#[cfg(feature = "DeleteTemplates")]
pub mod DeleteTemplates;
#[cfg(feature = "ExportConsistencyResults")]
pub mod ExportConsistencyResults;
#[cfg(feature = "ListApiVersion")]
pub mod ListApiVersion;
#[cfg(feature = "ListErrorServers")]
pub mod ListErrorServers;
#[cfg(feature = "ListMigprojects")]
pub mod ListMigprojects;
#[cfg(feature = "ListServers")]
pub mod ListServers;
#[cfg(feature = "ListTasks")]
pub mod ListTasks;
#[cfg(feature = "ListTemplates")]
pub mod ListTemplates;
#[cfg(feature = "RegisterServer")]
pub mod RegisterServer;
#[cfg(feature = "ShowApiVersion")]
pub mod ShowApiVersion;
#[cfg(feature = "ShowCertKey")]
pub mod ShowCertKey;
#[cfg(feature = "ShowCommand")]
pub mod ShowCommand;
#[cfg(feature = "ShowConfig")]
pub mod ShowConfig;
#[cfg(feature = "ShowConfigSetting")]
pub mod ShowConfigSetting;
#[cfg(feature = "ShowConsistencyResult")]
pub mod ShowConsistencyResult;
#[cfg(feature = "ShowMigproject")]
pub mod ShowMigproject;
#[cfg(feature = "ShowOverview")]
pub mod ShowOverview;
#[cfg(feature = "ShowPassphrase")]
pub mod ShowPassphrase;
#[cfg(feature = "ShowPrivacyAgreements")]
pub mod ShowPrivacyAgreements;
#[cfg(feature = "ShowServer")]
pub mod ShowServer;
#[cfg(feature = "ShowSha256")]
pub mod ShowSha256;
#[cfg(feature = "ShowsSpeedLimits")]
pub mod ShowsSpeedLimits;
#[cfg(feature = "ShowTargetPassword")]
pub mod ShowTargetPassword;
#[cfg(feature = "ShowTask")]
pub mod ShowTask;
#[cfg(feature = "ShowTemplate")]
pub mod ShowTemplate;
#[cfg(feature = "UnlockTargetEcs")]
pub mod UnlockTargetEcs;
#[cfg(feature = "UpdateCommandResult")]
pub mod UpdateCommandResult;
#[cfg(feature = "UpdateConsistencyResult")]
pub mod UpdateConsistencyResult;
#[cfg(feature = "UpdateCopyState")]
pub mod UpdateCopyState;
#[cfg(feature = "UpdateDefaultMigproject")]
pub mod UpdateDefaultMigproject;
#[cfg(feature = "UpdateDiskInfo")]
pub mod UpdateDiskInfo;
#[cfg(feature = "UpdateMigproject")]
pub mod UpdateMigproject;
#[cfg(feature = "UpdateNetworkCheckInfo")]
pub mod UpdateNetworkCheckInfo;
#[cfg(feature = "UpdateServerName")]
pub mod UpdateServerName;
#[cfg(feature = "UpdateSpeed")]
pub mod UpdateSpeed;
#[cfg(feature = "UpdateTask")]
pub mod UpdateTask;
#[cfg(feature = "UpdateTaskSpeed")]
pub mod UpdateTaskSpeed;
#[cfg(feature = "UpdateTaskStatus")]
pub mod UpdateTaskStatus;
#[cfg(feature = "UpdateTemplate")]
pub mod UpdateTemplate;
#[cfg(feature = "UploadSpecialConfigurationSetting")]
pub mod UploadSpecialConfigurationSetting;
