[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
CheckLaunch = []
CreateAccount = []
CreateBestPracticeDetect = []
CreateManagedOrganizationalUnit = []
CreateTemplate = []
DeleteLandingZone = []
DeleteManagedOrganizationalUnits = []
DeleteTemplate = []
DeregisterOrganizationalUnit = []
DisableControl = []
EnableControl = []
EnrollAccount = []
ListConfigRuleCompliances = []
ListControlViolations = []
ListControls = []
ListControlsForAccount = []
ListControlsForOrganizationalUnit = []
ListDriftDetails = []
ListEnabledControls = []
ListExternalConfigRuleCompliances = []
ListManagedAccounts = []
ListManagedAccountsForParent = []
ListManagedOrganizationalUnits = []
ListOperation = []
ListPredefinedTemplates = []
ReRegisterOrganizationalUnit = []
RegisterOrganizationalUnit = []
SetupLandingZone = []
ShowAvailableUpdates = []
ShowBestPracticeDetails = []
ShowBestPracticeOverview = []
ShowBestPracticeStatus = []
ShowComplianceStatusForAccount = []
ShowComplianceStatusForOrganizationalUnit = []
ShowControl = []
ShowControlOperate = []
ShowControlsForAccount = []
ShowControlsForOrganizationalUnit = []
ShowHomeRegion = []
ShowLandingZoneConfiguration = []
ShowLandingZoneIdentityCenter = []
ShowLandingZoneStatus = []
ShowManagedAccount = []
ShowManagedAccountTemplate = []
ShowManagedCoreAccount = []
ShowManagedOrganizationalUnit = []
ShowOperation = []
ShowTemplateDeployParams = []
UnEnrollAccount = []
UpdateManagedAccount = []
full = ["CheckLaunch", "CreateAccount", "CreateBestPracticeDetect", "CreateManagedOrganizationalUnit", "CreateTemplate", "DeleteLandingZone", "DeleteManagedOrganizationalUnits", "DeleteTemplate", "DeregisterOrganizationalUnit", "DisableControl", "EnableControl", "EnrollAccount", "ListConfigRuleCompliances", "ListControls", "ListControlsForAccount", "ListControlsForOrganizationalUnit", "ListControlViolations", "ListDriftDetails", "ListEnabledControls", "ListExternalConfigRuleCompliances", "ListManagedAccounts", "ListManagedAccountsForParent", "ListManagedOrganizationalUnits", "ListOperation", "ListPredefinedTemplates", "RegisterOrganizationalUnit", "ReRegisterOrganizationalUnit", "SetupLandingZone", "ShowAvailableUpdates", "ShowBestPracticeDetails", "ShowBestPracticeOverview", "ShowBestPracticeStatus", "ShowComplianceStatusForAccount", "ShowComplianceStatusForOrganizationalUnit", "ShowControl", "ShowControlOperate", "ShowControlsForAccount", "ShowControlsForOrganizationalUnit", "ShowHomeRegion", "ShowLandingZoneConfiguration", "ShowLandingZoneIdentityCenter", "ShowLandingZoneStatus", "ShowManagedAccount", "ShowManagedAccountTemplate", "ShowManagedCoreAccount", "ShowManagedOrganizationalUnit", "ShowOperation", "ShowTemplateDeployParams", "UnEnrollAccount", "UpdateManagedAccount"]

[lib]
name = "huawei_cloud_api_definitions_RGC"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-RGC"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
