[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
CheckLaunch = []
CreateAccount = []
CreateManagedOrganizationalUnit = []
DeleteManagedOrganizationalUnits = []
DeregisterOrganizationalUnit = []
DisableControl = []
EnableControl = []
EnrollAccount = []
ListConfigRuleCompliance = []
ListControlViolations = []
ListControls = []
ListControlsForAccount = []
ListControlsForOrganizationUnit = []
ListDriftDetails = []
ListEnabledControls = []
ListManagedAccounts = []
ListManagedAccountsForParent = []
ListManagedOrganizationalUnits = []
ReRegisterOrganizationalUnit = []
RegisterOrganizationalUnit = []
SetupLandingZone = []
ShowAvailableUpdates = []
ShowComplianceStatusForAccount = []
ShowComplianceStatusForOrganizationUnit = []
ShowControl = []
ShowControlOperate = []
ShowControlsForOrganizationUnit = []
ShowHomeRegion = []
ShowLandingZoneConfiguration = []
ShowLandingZoneIdentityCenter = []
ShowLandingZoneStatus = []
ShowManagedAccount = []
ShowManagedCoreAccount = []
ShowManagedOrganizationalUnit = []
ShowOperation = []
UnEnrollAccount = []
UpdateManagedAccount = []
full = ["CheckLaunch", "CreateAccount", "CreateManagedOrganizationalUnit", "DeleteManagedOrganizationalUnits", "DeregisterOrganizationalUnit", "DisableControl", "EnableControl", "EnrollAccount", "ListConfigRuleCompliance", "ListControls", "ListControlsForAccount", "ListControlsForOrganizationUnit", "ListControlViolations", "ListDriftDetails", "ListEnabledControls", "ListManagedAccounts", "ListManagedAccountsForParent", "ListManagedOrganizationalUnits", "RegisterOrganizationalUnit", "ReRegisterOrganizationalUnit", "SetupLandingZone", "ShowAvailableUpdates", "ShowComplianceStatusForAccount", "ShowComplianceStatusForOrganizationUnit", "ShowControl", "ShowControlOperate", "ShowControlsForOrganizationUnit", "ShowHomeRegion", "ShowLandingZoneConfiguration", "ShowLandingZoneIdentityCenter", "ShowLandingZoneStatus", "ShowManagedAccount", "ShowManagedCoreAccount", "ShowManagedOrganizationalUnit", "ShowOperation", "UnEnrollAccount", "UpdateManagedAccount"]

[lib]
name = "huawei_cloud_api_definitions_RGC"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-RGC"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
