#[cfg(feature = "BatchCreateResourceTags")]
pub mod BatchCreateResourceTags;
#[cfg(feature = "CreateHostedDirectConnect")]
pub mod CreateHostedDirectConnect;
#[cfg(feature = "CreateResourceTag")]
pub mod CreateResourceTag;
#[cfg(feature = "CreateVifPeer")]
pub mod CreateVifPeer;
#[cfg(feature = "CreateVirtualGateway")]
pub mod CreateVirtualGateway;
#[cfg(feature = "CreateVirtualInterface")]
pub mod CreateVirtualInterface;
#[cfg(feature = "DeleteDirectConnect")]
pub mod DeleteDirectConnect;
#[cfg(feature = "DeleteHostedDirectConnect")]
pub mod DeleteHostedDirectConnect;
#[cfg(feature = "DeleteResourceTag")]
pub mod DeleteResourceTag;
#[cfg(feature = "DeleteVifPeer")]
pub mod DeleteVifPeer;
#[cfg(feature = "DeleteVirtualGateway")]
pub mod DeleteVirtualGateway;
#[cfg(feature = "DeleteVirtualInterface")]
pub mod DeleteVirtualInterface;
#[cfg(feature = "ListDirectConnects")]
pub mod ListDirectConnects;
#[cfg(feature = "ListHostedDirectConnects")]
pub mod ListHostedDirectConnects;
#[cfg(feature = "ListProjectTags")]
pub mod ListProjectTags;
#[cfg(feature = "ListSwitchoverTestRecords")]
pub mod ListSwitchoverTestRecords;
#[cfg(feature = "ListTagResourceInstances")]
pub mod ListTagResourceInstances;
#[cfg(feature = "ListVirtualGateways")]
pub mod ListVirtualGateways;
#[cfg(feature = "ListVirtualInterfaces")]
pub mod ListVirtualInterfaces;
#[cfg(feature = "ShowDirectConnect")]
pub mod ShowDirectConnect;
#[cfg(feature = "ShowHostedDirectConnect")]
pub mod ShowHostedDirectConnect;
#[cfg(feature = "ShowQuotas")]
pub mod ShowQuotas;
#[cfg(feature = "ShowResourceTag")]
pub mod ShowResourceTag;
#[cfg(feature = "ShowVirtualGateway")]
pub mod ShowVirtualGateway;
#[cfg(feature = "ShowVirtualInterface")]
pub mod ShowVirtualInterface;
#[cfg(feature = "SwitchoverTest")]
pub mod SwitchoverTest;
#[cfg(feature = "UpdateDirectConnect")]
pub mod UpdateDirectConnect;
#[cfg(feature = "UpdateHostedDirectConnect")]
pub mod UpdateHostedDirectConnect;
#[cfg(feature = "UpdateVifPeer")]
pub mod UpdateVifPeer;
#[cfg(feature = "UpdateVirtualGateway")]
pub mod UpdateVirtualGateway;
#[cfg(feature = "UpdateVirtualInterface")]
pub mod UpdateVirtualInterface;
