#[cfg(feature = "BatchDeletePacifyWords")]
pub mod BatchDeletePacifyWords;
#[cfg(feature = "BatchExecuteAssetAction")]
pub mod BatchExecuteAssetAction;
#[cfg(feature = "Cancel2DDigitalHumanVideo")]
pub mod Cancel2DDigitalHumanVideo;
#[cfg(feature = "CancelPhotoDigitalHumanVideo")]
pub mod CancelPhotoDigitalHumanVideo;
#[cfg(feature = "CheckRecallKnowledgeLibrary")]
pub mod CheckRecallKnowledgeLibrary;
#[cfg(feature = "CheckVoiceAsset")]
pub mod CheckVoiceAsset;
#[cfg(feature = "CommitVoiceTrainingJob")]
pub mod CommitVoiceTrainingJob;
#[cfg(feature = "ConfirmFileUpload")]
pub mod ConfirmFileUpload;
#[cfg(feature = "ConfirmTrainingSegment")]
pub mod ConfirmTrainingSegment;
#[cfg(feature = "CopyVideoScripts")]
pub mod CopyVideoScripts;
#[cfg(feature = "CountTenantResources")]
pub mod CountTenantResources;
#[cfg(feature = "Create2DDigitalHumanVideo")]
pub mod Create2DDigitalHumanVideo;
#[cfg(feature = "Create2dModelTrainingJob")]
pub mod Create2dModelTrainingJob;
#[cfg(feature = "CreateActiveCode")]
pub mod CreateActiveCode;
#[cfg(feature = "CreateAgencyWithRoleType")]
pub mod CreateAgencyWithRoleType;
#[cfg(feature = "CreateAssetByReplicationInfo")]
pub mod CreateAssetByReplicationInfo;
#[cfg(feature = "CreateAsyncTtsJob")]
pub mod CreateAsyncTtsJob;
#[cfg(feature = "CreateBatchKnowledgeQuestion")]
pub mod CreateBatchKnowledgeQuestion;
#[cfg(feature = "CreateDialogReportConfig")]
pub mod CreateDialogReportConfig;
#[cfg(feature = "CreateDialogUrl")]
pub mod CreateDialogUrl;
#[cfg(feature = "CreateDigitalAsset")]
pub mod CreateDigitalAsset;
#[cfg(feature = "CreateDigitalHumanBusinessCard")]
pub mod CreateDigitalHumanBusinessCard;
#[cfg(feature = "CreateDocument")]
pub mod CreateDocument;
#[cfg(feature = "CreateFacialAnimations")]
pub mod CreateFacialAnimations;
#[cfg(feature = "CreateFile")]
pub mod CreateFile;
#[cfg(feature = "CreateHotQuestion")]
pub mod CreateHotQuestion;
#[cfg(feature = "CreateHotWords")]
pub mod CreateHotWords;
#[cfg(feature = "CreateInstruction")]
pub mod CreateInstruction;
#[cfg(feature = "CreateInstructionLibrary")]
pub mod CreateInstructionLibrary;
#[cfg(feature = "CreateIntentAndQuestion")]
pub mod CreateIntentAndQuestion;
#[cfg(feature = "CreateInteractionRuleGroup")]
pub mod CreateInteractionRuleGroup;
#[cfg(feature = "CreateInteractiveChat")]
pub mod CreateInteractiveChat;
#[cfg(feature = "CreateKnowledgeIntent")]
pub mod CreateKnowledgeIntent;
#[cfg(feature = "CreateKnowledgeLibrary")]
pub mod CreateKnowledgeLibrary;
#[cfg(feature = "CreateKnowledgeQuestion")]
pub mod CreateKnowledgeQuestion;
#[cfg(feature = "CreateKnowledgeSkill")]
pub mod CreateKnowledgeSkill;
#[cfg(feature = "CreateLargeFile")]
pub mod CreateLargeFile;
#[cfg(feature = "CreateLivePlatform")]
pub mod CreateLivePlatform;
#[cfg(feature = "CreateLlmConfig")]
pub mod CreateLlmConfig;
#[cfg(feature = "CreateMcpServer")]
pub mod CreateMcpServer;
#[cfg(feature = "CreateMetaStudioOrders")]
pub mod CreateMetaStudioOrders;
#[cfg(feature = "CreateOnceCode")]
pub mod CreateOnceCode;
#[cfg(feature = "CreatePacifyWords")]
pub mod CreatePacifyWords;
#[cfg(feature = "CreatePhotoDetection")]
pub mod CreatePhotoDetection;
#[cfg(feature = "CreatePhotoDigitalHumanVideo")]
pub mod CreatePhotoDigitalHumanVideo;
#[cfg(feature = "CreatePictureModelingByUrlJob")]
pub mod CreatePictureModelingByUrlJob;
#[cfg(feature = "CreatePictureModelingJob")]
pub mod CreatePictureModelingJob;
#[cfg(feature = "CreatePluginConfig")]
pub mod CreatePluginConfig;
#[cfg(feature = "CreateProduct")]
pub mod CreateProduct;
#[cfg(feature = "CreateQuestionAnswer")]
pub mod CreateQuestionAnswer;
#[cfg(feature = "CreateRobot")]
pub mod CreateRobot;
#[cfg(feature = "CreateRole")]
pub mod CreateRole;
#[cfg(feature = "CreateSmartChatRoom")]
pub mod CreateSmartChatRoom;
#[cfg(feature = "CreateSmartLiveRoom")]
pub mod CreateSmartLiveRoom;
#[cfg(feature = "CreateSubtitleFile")]
pub mod CreateSubtitleFile;
#[cfg(feature = "CreateTrainingAdvanceJob")]
pub mod CreateTrainingAdvanceJob;
#[cfg(feature = "CreateTrainingBasicJob")]
pub mod CreateTrainingBasicJob;
#[cfg(feature = "CreateTrainingMiddleJob")]
pub mod CreateTrainingMiddleJob;
#[cfg(feature = "CreateTtsa")]
pub mod CreateTtsa;
#[cfg(feature = "CreateTtsAudition")]
pub mod CreateTtsAudition;
#[cfg(feature = "CreateTtscVocabularyConfigs")]
pub mod CreateTtscVocabularyConfigs;
#[cfg(feature = "CreateTtscVocabularyGroups")]
pub mod CreateTtscVocabularyGroups;
#[cfg(feature = "CreateVideoMotionCaptureJob")]
pub mod CreateVideoMotionCaptureJob;
#[cfg(feature = "CreateVideoScripts")]
pub mod CreateVideoScripts;
#[cfg(feature = "CreateWelcomeSpeech")]
pub mod CreateWelcomeSpeech;
#[cfg(feature = "Delete2dModelTrainingJob")]
pub mod Delete2dModelTrainingJob;
#[cfg(feature = "DeleteActiveCode")]
pub mod DeleteActiveCode;
#[cfg(feature = "DeleteAgencyWithRoleType")]
pub mod DeleteAgencyWithRoleType;
#[cfg(feature = "DeleteAsset")]
pub mod DeleteAsset;
#[cfg(feature = "DeleteDialogReportConfig")]
pub mod DeleteDialogReportConfig;
#[cfg(feature = "DeleteDigitalHumanBusinessCard")]
pub mod DeleteDigitalHumanBusinessCard;
#[cfg(feature = "DeleteDocument")]
pub mod DeleteDocument;
#[cfg(feature = "DeleteFile")]
pub mod DeleteFile;
#[cfg(feature = "DeleteHotQuestion")]
pub mod DeleteHotQuestion;
#[cfg(feature = "DeleteHotWords")]
pub mod DeleteHotWords;
#[cfg(feature = "DeleteInstruction")]
pub mod DeleteInstruction;
#[cfg(feature = "DeleteInstructionLibrary")]
pub mod DeleteInstructionLibrary;
#[cfg(feature = "DeleteInteractionRuleGroup")]
pub mod DeleteInteractionRuleGroup;
#[cfg(feature = "DeleteKnowledgeIntent")]
pub mod DeleteKnowledgeIntent;
#[cfg(feature = "DeleteKnowledgeLibrary")]
pub mod DeleteKnowledgeLibrary;
#[cfg(feature = "DeleteKnowledgeQuestion")]
pub mod DeleteKnowledgeQuestion;
#[cfg(feature = "DeleteKnowledgeSkill")]
pub mod DeleteKnowledgeSkill;
#[cfg(feature = "DeleteLivePlatform")]
pub mod DeleteLivePlatform;
#[cfg(feature = "DeleteLlmConfig")]
pub mod DeleteLlmConfig;
#[cfg(feature = "DeleteMcpServer")]
pub mod DeleteMcpServer;
#[cfg(feature = "DeletePacifyWords")]
pub mod DeletePacifyWords;
#[cfg(feature = "DeletePluginConfig")]
pub mod DeletePluginConfig;
#[cfg(feature = "DeleteProduct")]
pub mod DeleteProduct;
#[cfg(feature = "DeleteQuestionAnswer")]
pub mod DeleteQuestionAnswer;
#[cfg(feature = "DeleteRobot")]
pub mod DeleteRobot;
#[cfg(feature = "DeleteRole")]
pub mod DeleteRole;
#[cfg(feature = "DeleteSmartChatRoom")]
pub mod DeleteSmartChatRoom;
#[cfg(feature = "DeleteSmartLiveRoom")]
pub mod DeleteSmartLiveRoom;
#[cfg(feature = "DeleteTask")]
pub mod DeleteTask;
#[cfg(feature = "DeleteTtscVocabularyConfigs")]
pub mod DeleteTtscVocabularyConfigs;
#[cfg(feature = "DeleteTtscVocabularyGroups")]
pub mod DeleteTtscVocabularyGroups;
#[cfg(feature = "DeleteVideoScript")]
pub mod DeleteVideoScript;
#[cfg(feature = "DeleteVoiceTrainingJob")]
pub mod DeleteVoiceTrainingJob;
#[cfg(feature = "DeleteWelcomeSpeech")]
pub mod DeleteWelcomeSpeech;
#[cfg(feature = "DownloadDocument")]
pub mod DownloadDocument;
