#[cfg(feature = "BatchExecuteAssetAction")]
pub mod BatchExecuteAssetAction;
#[cfg(feature = "Cancel2DDigitalHumanVideo")]
pub mod Cancel2DDigitalHumanVideo;
#[cfg(feature = "CancelPhotoDigitalHumanVideo")]
pub mod CancelPhotoDigitalHumanVideo;
#[cfg(feature = "CommitVoiceTrainingJob")]
pub mod CommitVoiceTrainingJob;
#[cfg(feature = "ConfirmFileUpload")]
pub mod ConfirmFileUpload;
#[cfg(feature = "ConfirmTrainingSegment")]
pub mod ConfirmTrainingSegment;
#[cfg(feature = "CopyVideoScripts")]
pub mod CopyVideoScripts;
#[cfg(feature = "Create2DDigitalHumanVideo")]
pub mod Create2DDigitalHumanVideo;
#[cfg(feature = "Create2dModelTrainingJob")]
pub mod Create2dModelTrainingJob;
#[cfg(feature = "CreateActiveCode")]
pub mod CreateActiveCode;
#[cfg(feature = "CreateAgencyWithRoleType")]
pub mod CreateAgencyWithRoleType;
#[cfg(feature = "CreateAssetByReplicationInfo")]
pub mod CreateAssetByReplicationInfo;
#[cfg(feature = "CreateBatchKnowledgeQuestion")]
pub mod CreateBatchKnowledgeQuestion;
#[cfg(feature = "CreateDialogUrl")]
pub mod CreateDialogUrl;
#[cfg(feature = "CreateDigitalAsset")]
pub mod CreateDigitalAsset;
#[cfg(feature = "CreateDigitalHumanBusinessCard")]
pub mod CreateDigitalHumanBusinessCard;
#[cfg(feature = "CreateFacialAnimations")]
pub mod CreateFacialAnimations;
#[cfg(feature = "CreateFile")]
pub mod CreateFile;
#[cfg(feature = "CreateHotQuestion")]
pub mod CreateHotQuestion;
#[cfg(feature = "CreateHotWords")]
pub mod CreateHotWords;
#[cfg(feature = "CreateIntentAndQuestion")]
pub mod CreateIntentAndQuestion;
#[cfg(feature = "CreateInteractionRuleGroup")]
pub mod CreateInteractionRuleGroup;
#[cfg(feature = "CreateKnowledgeIntent")]
pub mod CreateKnowledgeIntent;
#[cfg(feature = "CreateKnowledgeQuestion")]
pub mod CreateKnowledgeQuestion;
#[cfg(feature = "CreateKnowledgeSkill")]
pub mod CreateKnowledgeSkill;
#[cfg(feature = "CreateLargeFile")]
pub mod CreateLargeFile;
#[cfg(feature = "CreateOnceCode")]
pub mod CreateOnceCode;
#[cfg(feature = "CreatePhotoDetection")]
pub mod CreatePhotoDetection;
#[cfg(feature = "CreatePhotoDigitalHumanVideo")]
pub mod CreatePhotoDigitalHumanVideo;
#[cfg(feature = "CreatePictureModelingByUrlJob")]
pub mod CreatePictureModelingByUrlJob;
#[cfg(feature = "CreatePictureModelingJob")]
pub mod CreatePictureModelingJob;
#[cfg(feature = "CreateProduct")]
pub mod CreateProduct;
#[cfg(feature = "CreateRobot")]
pub mod CreateRobot;
#[cfg(feature = "CreateSmartChatRoom")]
pub mod CreateSmartChatRoom;
#[cfg(feature = "CreateSmartLiveRoom")]
pub mod CreateSmartLiveRoom;
#[cfg(feature = "CreateTrainingAdvanceJob")]
pub mod CreateTrainingAdvanceJob;
#[cfg(feature = "CreateTrainingBasicJob")]
pub mod CreateTrainingBasicJob;
#[cfg(feature = "CreateTrainingMiddleJob")]
pub mod CreateTrainingMiddleJob;
#[cfg(feature = "CreateTtsa")]
pub mod CreateTtsa;
#[cfg(feature = "CreateTtsAudition")]
pub mod CreateTtsAudition;
#[cfg(feature = "CreateVideoMotionCaptureJob")]
pub mod CreateVideoMotionCaptureJob;
#[cfg(feature = "CreateVideoScripts")]
pub mod CreateVideoScripts;
#[cfg(feature = "CreateWelcomeSpeech")]
pub mod CreateWelcomeSpeech;
#[cfg(feature = "Delete2dModelTrainingJob")]
pub mod Delete2dModelTrainingJob;
#[cfg(feature = "DeleteActiveCode")]
pub mod DeleteActiveCode;
#[cfg(feature = "DeleteAgencyWithRoleType")]
pub mod DeleteAgencyWithRoleType;
#[cfg(feature = "DeleteAsset")]
pub mod DeleteAsset;
#[cfg(feature = "DeleteDigitalHumanBusinessCard")]
pub mod DeleteDigitalHumanBusinessCard;
#[cfg(feature = "DeleteFile")]
pub mod DeleteFile;
#[cfg(feature = "DeleteHotQuestion")]
pub mod DeleteHotQuestion;
#[cfg(feature = "DeleteHotWords")]
pub mod DeleteHotWords;
#[cfg(feature = "DeleteInteractionRuleGroup")]
pub mod DeleteInteractionRuleGroup;
#[cfg(feature = "DeleteKnowledgeIntent")]
pub mod DeleteKnowledgeIntent;
#[cfg(feature = "DeleteKnowledgeQuestion")]
pub mod DeleteKnowledgeQuestion;
#[cfg(feature = "DeleteKnowledgeSkill")]
pub mod DeleteKnowledgeSkill;
#[cfg(feature = "DeleteProduct")]
pub mod DeleteProduct;
#[cfg(feature = "DeleteRobot")]
pub mod DeleteRobot;
#[cfg(feature = "DeleteSmartChatRoom")]
pub mod DeleteSmartChatRoom;
#[cfg(feature = "DeleteSmartLiveRoom")]
pub mod DeleteSmartLiveRoom;
#[cfg(feature = "DeleteVideoScript")]
pub mod DeleteVideoScript;
#[cfg(feature = "DeleteVoiceTrainingJob")]
pub mod DeleteVoiceTrainingJob;
#[cfg(feature = "DeleteWelcomeSpeech")]
pub mod DeleteWelcomeSpeech;
#[cfg(feature = "Execute2dModelTrainingCommandByUser")]
pub mod Execute2dModelTrainingCommandByUser;
#[cfg(feature = "ExecuteSmartLiveCommand")]
pub mod ExecuteSmartLiveCommand;
#[cfg(feature = "ExecuteVideoMotionCaptureCommand")]
pub mod ExecuteVideoMotionCaptureCommand;
#[cfg(feature = "ExportKnowledgeSkill")]
pub mod ExportKnowledgeSkill;
#[cfg(feature = "List2dModelTrainingJob")]
pub mod List2dModelTrainingJob;
#[cfg(feature = "ListActiveCode")]
pub mod ListActiveCode;
#[cfg(feature = "ListAssets")]
pub mod ListAssets;
#[cfg(feature = "ListAssetSummary")]
pub mod ListAssetSummary;
#[cfg(feature = "ListDigitalHumanBusinessCard")]
pub mod ListDigitalHumanBusinessCard;
#[cfg(feature = "ListDigitalHumanVideo")]
pub mod ListDigitalHumanVideo;
#[cfg(feature = "ListFacialAnimationsData")]
pub mod ListFacialAnimationsData;
#[cfg(feature = "ListHotQuestion")]
pub mod ListHotQuestion;
#[cfg(feature = "ListHotWords")]
pub mod ListHotWords;
#[cfg(feature = "ListInteractionRuleGroups")]
pub mod ListInteractionRuleGroups;
#[cfg(feature = "ListJobOperationLog")]
pub mod ListJobOperationLog;
#[cfg(feature = "ListKnowledgeIntent")]
pub mod ListKnowledgeIntent;
#[cfg(feature = "ListKnowledgeQuestion")]
pub mod ListKnowledgeQuestion;
#[cfg(feature = "ListKnowledgeSkill")]
pub mod ListKnowledgeSkill;
#[cfg(feature = "ListPictureModelingJobs")]
pub mod ListPictureModelingJobs;
#[cfg(feature = "ListProducts")]
pub mod ListProducts;
#[cfg(feature = "ListRobot")]
pub mod ListRobot;
#[cfg(feature = "ListSmartChatRooms")]
pub mod ListSmartChatRooms;
#[cfg(feature = "ListSmartLive")]
pub mod ListSmartLive;
#[cfg(feature = "ListSmartLiveJobs")]
pub mod ListSmartLiveJobs;
#[cfg(feature = "ListSmartLiveRooms")]
pub mod ListSmartLiveRooms;
#[cfg(feature = "ListStyles")]
pub mod ListStyles;
#[cfg(feature = "ListTtsaData")]
pub mod ListTtsaData;
#[cfg(feature = "ListTtsaJobs")]
pub mod ListTtsaJobs;
#[cfg(feature = "ListVideoMotionCaptureJobs")]
pub mod ListVideoMotionCaptureJobs;
#[cfg(feature = "ListVideoScripts")]
pub mod ListVideoScripts;
#[cfg(feature = "ListVoiceTrainingJob")]
pub mod ListVoiceTrainingJob;
#[cfg(feature = "ListWelcomeSpeech")]
pub mod ListWelcomeSpeech;
#[cfg(feature = "LiveEventReport")]
pub mod LiveEventReport;
#[cfg(feature = "ResetActiveCode")]
pub mod ResetActiveCode;
#[cfg(feature = "RestoreAsset")]
pub mod RestoreAsset;
#[cfg(feature = "SetProductAsset")]
pub mod SetProductAsset;
#[cfg(feature = "Show2DDigitalHumanVideo")]
pub mod Show2DDigitalHumanVideo;
#[cfg(feature = "Show2dModelTrainingJob")]
pub mod Show2dModelTrainingJob;
