#[cfg(feature = "Cancel2DDigitalHumanVideo")]
pub mod Cancel2DDigitalHumanVideo;
#[cfg(feature = "CancelPhotoDigitalHumanVideo")]
pub mod CancelPhotoDigitalHumanVideo;
#[cfg(feature = "CheckTextLanguage")]
pub mod CheckTextLanguage;
#[cfg(feature = "CommitVoiceTrainingJob")]
pub mod CommitVoiceTrainingJob;
#[cfg(feature = "ConfirmFileUpload")]
pub mod ConfirmFileUpload;
#[cfg(feature = "ConfirmTrainingSegment")]
pub mod ConfirmTrainingSegment;
#[cfg(feature = "CopyVideoScripts")]
pub mod CopyVideoScripts;
#[cfg(feature = "Create2DDigitalHumanVideo")]
pub mod Create2DDigitalHumanVideo;
#[cfg(feature = "Create2dModelTrainingJob")]
pub mod Create2dModelTrainingJob;
#[cfg(feature = "CreateActiveCode")]
pub mod CreateActiveCode;
#[cfg(feature = "CreateAssetbyReplicationInfo")]
pub mod CreateAssetbyReplicationInfo;
#[cfg(feature = "CreateDialogUrl")]
pub mod CreateDialogUrl;
#[cfg(feature = "CreateDigitalAsset")]
pub mod CreateDigitalAsset;
#[cfg(feature = "CreateDigitalHumanBusinessCard")]
pub mod CreateDigitalHumanBusinessCard;
#[cfg(feature = "CreateFacialAnimations")]
pub mod CreateFacialAnimations;
#[cfg(feature = "CreateFile")]
pub mod CreateFile;
#[cfg(feature = "CreateInteractionRuleGroup")]
pub mod CreateInteractionRuleGroup;
#[cfg(feature = "CreateLargeFile")]
pub mod CreateLargeFile;
#[cfg(feature = "CreateOnceCode")]
pub mod CreateOnceCode;
#[cfg(feature = "CreatePhotoDetection")]
pub mod CreatePhotoDetection;
#[cfg(feature = "CreatePhotoDigitalHumanVideo")]
pub mod CreatePhotoDigitalHumanVideo;
#[cfg(feature = "CreatePictureModelingByUrlJob")]
pub mod CreatePictureModelingByUrlJob;
#[cfg(feature = "CreatePictureModelingJob")]
pub mod CreatePictureModelingJob;
#[cfg(feature = "CreateRobot")]
pub mod CreateRobot;
#[cfg(feature = "CreateSmartChatRoom")]
pub mod CreateSmartChatRoom;
#[cfg(feature = "CreateSmartLiveRoom")]
pub mod CreateSmartLiveRoom;
#[cfg(feature = "CreateTrainingAdvanceJob")]
pub mod CreateTrainingAdvanceJob;
#[cfg(feature = "CreateTrainingBasicJob")]
pub mod CreateTrainingBasicJob;
#[cfg(feature = "CreateTrainingMiddleJob")]
pub mod CreateTrainingMiddleJob;
#[cfg(feature = "CreateTtsa")]
pub mod CreateTtsa;
#[cfg(feature = "CreateTtsAudition")]
pub mod CreateTtsAudition;
#[cfg(feature = "CreateVideoMotionCaptureJob")]
pub mod CreateVideoMotionCaptureJob;
#[cfg(feature = "CreateVideoScripts")]
pub mod CreateVideoScripts;
#[cfg(feature = "Delete2dModelTrainingJob")]
pub mod Delete2dModelTrainingJob;
#[cfg(feature = "DeleteActiveCode")]
pub mod DeleteActiveCode;
#[cfg(feature = "DeleteAsset")]
pub mod DeleteAsset;
#[cfg(feature = "DeleteDigitalHumanBusinessCard")]
pub mod DeleteDigitalHumanBusinessCard;
#[cfg(feature = "DeleteFile")]
pub mod DeleteFile;
#[cfg(feature = "DeleteInteractionRuleGroup")]
pub mod DeleteInteractionRuleGroup;
#[cfg(feature = "DeleteRobot")]
pub mod DeleteRobot;
#[cfg(feature = "DeleteSmartChatRoom")]
pub mod DeleteSmartChatRoom;
#[cfg(feature = "DeleteSmartLiveRoom")]
pub mod DeleteSmartLiveRoom;
#[cfg(feature = "DeleteVideoScript")]
pub mod DeleteVideoScript;
#[cfg(feature = "DeleteVoiceTrainingJob")]
pub mod DeleteVoiceTrainingJob;
#[cfg(feature = "Execute2dModelTrainingCommandByUser")]
pub mod Execute2dModelTrainingCommandByUser;
#[cfg(feature = "ExecuteSmartLiveCommand")]
pub mod ExecuteSmartLiveCommand;
#[cfg(feature = "ExecuteVideoMotionCaptureCommand")]
pub mod ExecuteVideoMotionCaptureCommand;
#[cfg(feature = "List2dModelTrainingJob")]
pub mod List2dModelTrainingJob;
#[cfg(feature = "ListActiveCode")]
pub mod ListActiveCode;
#[cfg(feature = "ListAssets")]
pub mod ListAssets;
#[cfg(feature = "ListAssetSummary")]
pub mod ListAssetSummary;
#[cfg(feature = "ListDigitalHumanBusinessCard")]
pub mod ListDigitalHumanBusinessCard;
#[cfg(feature = "ListDigitalHumanVideo")]
pub mod ListDigitalHumanVideo;
#[cfg(feature = "ListFacialAnimationsData")]
pub mod ListFacialAnimationsData;
#[cfg(feature = "ListInteractionRuleGroups")]
pub mod ListInteractionRuleGroups;
#[cfg(feature = "ListPictureModelingJobs")]
pub mod ListPictureModelingJobs;
#[cfg(feature = "ListRobot")]
pub mod ListRobot;
#[cfg(feature = "ListSmartChatRooms")]
pub mod ListSmartChatRooms;
#[cfg(feature = "ListSmartLive")]
pub mod ListSmartLive;
#[cfg(feature = "ListSmartLiveJobs")]
pub mod ListSmartLiveJobs;
#[cfg(feature = "ListSmartLiveRooms")]
pub mod ListSmartLiveRooms;
#[cfg(feature = "ListStyles")]
pub mod ListStyles;
#[cfg(feature = "ListTtsaData")]
pub mod ListTtsaData;
#[cfg(feature = "ListTtsaJobs")]
pub mod ListTtsaJobs;
#[cfg(feature = "ListVideoMotionCaptureJobs")]
pub mod ListVideoMotionCaptureJobs;
#[cfg(feature = "ListVideoScripts")]
pub mod ListVideoScripts;
#[cfg(feature = "ListVoiceTrainingJob")]
pub mod ListVoiceTrainingJob;
#[cfg(feature = "LiveEventReport")]
pub mod LiveEventReport;
#[cfg(feature = "ResetActiveCode")]
pub mod ResetActiveCode;
#[cfg(feature = "RestoreAsset")]
pub mod RestoreAsset;
#[cfg(feature = "Show2DDigitalHumanVideo")]
pub mod Show2DDigitalHumanVideo;
#[cfg(feature = "Show2dModelTrainingJob")]
pub mod Show2dModelTrainingJob;
#[cfg(feature = "ShowActiveCode")]
pub mod ShowActiveCode;
#[cfg(feature = "ShowAsset")]
pub mod ShowAsset;
#[cfg(feature = "ShowAssetReplicationInfo")]
pub mod ShowAssetReplicationInfo;
#[cfg(feature = "ShowDigitalHumanBusinessCard")]
pub mod ShowDigitalHumanBusinessCard;
#[cfg(feature = "ShowJobAuditResult")]
pub mod ShowJobAuditResult;
#[cfg(feature = "ShowJobUploadingAddress")]
pub mod ShowJobUploadingAddress;
#[cfg(feature = "ShowPhotoDetection")]
pub mod ShowPhotoDetection;
#[cfg(feature = "ShowPhotoDigitalHumanVideo")]
pub mod ShowPhotoDigitalHumanVideo;
#[cfg(feature = "ShowPictureModelingJob")]
pub mod ShowPictureModelingJob;
#[cfg(feature = "ShowRobot")]
pub mod ShowRobot;
#[cfg(feature = "ShowSmartChatJob")]
pub mod ShowSmartChatJob;
#[cfg(feature = "ShowSmartChatRoom")]
pub mod ShowSmartChatRoom;
#[cfg(feature = "ShowSmartLive")]
pub mod ShowSmartLive;
#[cfg(feature = "ShowSmartLiveRoom")]
pub mod ShowSmartLiveRoom;
#[cfg(feature = "ShowTrainingSegmentInfo")]
pub mod ShowTrainingSegmentInfo;
#[cfg(feature = "ShowTtsAuditionFile")]
pub mod ShowTtsAuditionFile;
#[cfg(feature = "ShowVideoMotionCaptureJob")]
pub mod ShowVideoMotionCaptureJob;
#[cfg(feature = "ShowVideoScript")]
pub mod ShowVideoScript;
#[cfg(feature = "ShowVoiceTrainingJob")]
pub mod ShowVoiceTrainingJob;
#[cfg(feature = "StartSmartChatJob")]
pub mod StartSmartChatJob;
#[cfg(feature = "StartSmartLive")]
pub mod StartSmartLive;
#[cfg(feature = "StopSmartChatJob")]
pub mod StopSmartChatJob;
#[cfg(feature = "StopSmartLive")]
pub mod StopSmartLive;
#[cfg(feature = "StopVideoMotionCaptureJob")]
pub mod StopVideoMotionCaptureJob;
#[cfg(feature = "Update2dModelTrainingJob")]
pub mod Update2dModelTrainingJob;
#[cfg(feature = "UpdateActiveCode")]
pub mod UpdateActiveCode;
#[cfg(feature = "UpdateDigitalAsset")]
pub mod UpdateDigitalAsset;
#[cfg(feature = "UpdateDigitalHumanBusinessCard")]
pub mod UpdateDigitalHumanBusinessCard;
