#[cfg(feature = "AcceptVpcPeeringEii")]
pub mod AcceptVpcPeeringEii;
#[cfg(feature = "AcceptVpcPeeringReq")]
pub mod AcceptVpcPeeringReq;
#[cfg(feature = "AddPeeringRoutersCom")]
pub mod AddPeeringRoutersCom;
#[cfg(feature = "AddRouterInterface")]
pub mod AddRouterInterface;
#[cfg(feature = "AttachsubNetworkInterface")]
pub mod AttachsubNetworkInterface;
#[cfg(feature = "BatchAddExtendCidr")]
pub mod BatchAddExtendCidr;
#[cfg(feature = "BatchCreateSecurityGroupRulesEiii")]
pub mod BatchCreateSecurityGroupRulesEiii;
#[cfg(feature = "BatchRemoveExtendCidr")]
pub mod BatchRemoveExtendCidr;
#[cfg(feature = "BindVportCom")]
pub mod BindVportCom;
#[cfg(feature = "CreateBandwidthLimitRule")]
pub mod CreateBandwidthLimitRule;
#[cfg(feature = "CreateBaremetalDedicatedSubnet")]
pub mod CreateBaremetalDedicatedSubnet;
#[cfg(feature = "CreateExpressGateway")]
pub mod CreateExpressGateway;
#[cfg(feature = "CreateL2brAccesspoints")]
pub mod CreateL2brAccesspoints;
#[cfg(feature = "CreateL2brInstances")]
pub mod CreateL2brInstances;
#[cfg(feature = "CreateNetwork")]
pub mod CreateNetwork;
#[cfg(feature = "CreatePort")]
pub mod CreatePort;
#[cfg(feature = "CreatePortCom")]
pub mod CreatePortCom;
#[cfg(feature = "CreatePortEii")]
pub mod CreatePortEii;
#[cfg(feature = "CreatePortLimitRule")]
pub mod CreatePortLimitRule;
#[cfg(feature = "CreatePrivateVpcPorts")]
pub mod CreatePrivateVpcPorts;
#[cfg(feature = "CreateQosPolicy")]
pub mod CreateQosPolicy;
#[cfg(feature = "CreateRouter")]
pub mod CreateRouter;
#[cfg(feature = "CreateSecurityGroupEii")]
pub mod CreateSecurityGroupEii;
#[cfg(feature = "CreateSecurityGroupEiii")]
pub mod CreateSecurityGroupEiii;
#[cfg(feature = "CreateSecurityGroupInternal")]
pub mod CreateSecurityGroupInternal;
#[cfg(feature = "CreateSecurityGroupRuleEii")]
pub mod CreateSecurityGroupRuleEii;
#[cfg(feature = "CreateSecurityGroupRuleEiiCom")]
pub mod CreateSecurityGroupRuleEiiCom;
#[cfg(feature = "CreateSecurityGroupRuleEiii")]
pub mod CreateSecurityGroupRuleEiii;
#[cfg(feature = "CreateSecurityGroupRulesInternal")]
pub mod CreateSecurityGroupRulesInternal;
#[cfg(feature = "CreateSubnet")]
pub mod CreateSubnet;
#[cfg(feature = "CreateSubnetCom")]
pub mod CreateSubnetCom;
#[cfg(feature = "CreateSubnetworkInterfaces")]
pub mod CreateSubnetworkInterfaces;
#[cfg(feature = "CreateVpcCom")]
pub mod CreateVpcCom;
#[cfg(feature = "CreateVpcPeeringCom")]
pub mod CreateVpcPeeringCom;
#[cfg(feature = "CreateVpcPeeringEii")]
pub mod CreateVpcPeeringEii;
#[cfg(feature = "CreateVpcRoutes")]
pub mod CreateVpcRoutes;
#[cfg(feature = "DeleteBandwidthLimitRule")]
pub mod DeleteBandwidthLimitRule;
#[cfg(feature = "DeleteBaremetalDedicatedSubnet")]
pub mod DeleteBaremetalDedicatedSubnet;
#[cfg(feature = "DeleteComSubnet")]
pub mod DeleteComSubnet;
#[cfg(feature = "DeleteExpressGateway")]
pub mod DeleteExpressGateway;
#[cfg(feature = "DeleteL2brAccesspoints")]
pub mod DeleteL2brAccesspoints;
#[cfg(feature = "DeleteL2brInstances")]
pub mod DeleteL2brInstances;
#[cfg(feature = "DeleteNetwork")]
pub mod DeleteNetwork;
#[cfg(feature = "DeletePeeringRoutersCom")]
pub mod DeletePeeringRoutersCom;
#[cfg(feature = "DeletePort")]
pub mod DeletePort;
#[cfg(feature = "DeletePortCom")]
pub mod DeletePortCom;
#[cfg(feature = "DeletePortEii")]
pub mod DeletePortEii;
#[cfg(feature = "DeletePortLimitRule")]
pub mod DeletePortLimitRule;
#[cfg(feature = "DeletePrivateVpcPort")]
pub mod DeletePrivateVpcPort;
#[cfg(feature = "DeleteQosPolicy")]
pub mod DeleteQosPolicy;
#[cfg(feature = "DeleteRouter")]
pub mod DeleteRouter;
#[cfg(feature = "DeleteSecurityGroupById")]
pub mod DeleteSecurityGroupById;
#[cfg(feature = "DeleteSecurityGroupEii")]
pub mod DeleteSecurityGroupEii;
#[cfg(feature = "DeleteSecurityGroupEiii")]
pub mod DeleteSecurityGroupEiii;
#[cfg(feature = "DeleteSecurityGroupInternal")]
pub mod DeleteSecurityGroupInternal;
#[cfg(feature = "DeleteSecurityGroupRuleByRuleId")]
pub mod DeleteSecurityGroupRuleByRuleId;
#[cfg(feature = "DeleteSecurityGroupRuleEii")]
pub mod DeleteSecurityGroupRuleEii;
#[cfg(feature = "DeleteSecurityGroupRuleEiii")]
pub mod DeleteSecurityGroupRuleEiii;
#[cfg(feature = "DeleteSecurityGroupRuleInternal")]
pub mod DeleteSecurityGroupRuleInternal;
#[cfg(feature = "DeleteSubnet")]
pub mod DeleteSubnet;
#[cfg(feature = "DeleteSubnetCom")]
pub mod DeleteSubnetCom;
#[cfg(feature = "DeleteSubnetworkInterface")]
pub mod DeleteSubnetworkInterface;
#[cfg(feature = "DeleteVpcCom")]
pub mod DeleteVpcCom;
#[cfg(feature = "DeleteVpcPeeringCom")]
pub mod DeleteVpcPeeringCom;
#[cfg(feature = "DeleteVpcPeeringEii")]
pub mod DeleteVpcPeeringEii;
#[cfg(feature = "DeleteVpcRoute")]
pub mod DeleteVpcRoute;
#[cfg(feature = "DetachSubnetworkInterface")]
pub mod DetachSubnetworkInterface;
#[cfg(feature = "ListBandwidthLimitRules")]
pub mod ListBandwidthLimitRules;
#[cfg(feature = "ListBaremetalDedicatedSubnets")]
pub mod ListBaremetalDedicatedSubnets;
#[cfg(feature = "ListComgetExNetworks")]
pub mod ListComgetExNetworks;
#[cfg(feature = "ListExpressGateway")]
pub mod ListExpressGateway;
#[cfg(feature = "ListExpressGatewayProviders")]
pub mod ListExpressGatewayProviders;
#[cfg(feature = "ListExSubnet")]
pub mod ListExSubnet;
#[cfg(feature = "ListL2brAccesspoints")]
pub mod ListL2brAccesspoints;
#[cfg(feature = "ListL2brInstances")]
pub mod ListL2brInstances;
#[cfg(feature = "ListNetworks")]
pub mod ListNetworks;
#[cfg(feature = "ListPortCom")]
pub mod ListPortCom;
#[cfg(feature = "ListPortLimitRules")]
pub mod ListPortLimitRules;
#[cfg(feature = "ListPorts")]
pub mod ListPorts;
#[cfg(feature = "ListPortsEii")]
pub mod ListPortsEii;
#[cfg(feature = "ListPrivateVpcPorts")]
pub mod ListPrivateVpcPorts;
#[cfg(feature = "ListQosPolicies")]
pub mod ListQosPolicies;
#[cfg(feature = "ListRouters")]
pub mod ListRouters;
#[cfg(feature = "ListRoutetablesEi")]
pub mod ListRoutetablesEi;
#[cfg(feature = "ListSecurityGroupById")]
pub mod ListSecurityGroupById;
#[cfg(feature = "ListSecurityGroupRulesEii")]
pub mod ListSecurityGroupRulesEii;
#[cfg(feature = "ListSecurityGroupRulesEiii")]
pub mod ListSecurityGroupRulesEiii;
#[cfg(feature = "ListSecurityGroupRulesInternal")]
pub mod ListSecurityGroupRulesInternal;
#[cfg(feature = "ListSecurityGroups")]
pub mod ListSecurityGroups;
#[cfg(feature = "ListSecurityGroupsEii")]
pub mod ListSecurityGroupsEii;
#[cfg(feature = "ListSecurityGroupsEiiCom")]
pub mod ListSecurityGroupsEiiCom;
#[cfg(feature = "ListSecurityGroupsEiii")]
pub mod ListSecurityGroupsEiii;
#[cfg(feature = "ListSecurityGroupsInternal")]
pub mod ListSecurityGroupsInternal;
#[cfg(feature = "ListServiceProviders")]
pub mod ListServiceProviders;
#[cfg(feature = "ListSubnetCom")]
pub mod ListSubnetCom;
#[cfg(feature = "ListSubnetpools")]
pub mod ListSubnetpools;
#[cfg(feature = "ListSubnets")]
pub mod ListSubnets;
#[cfg(feature = "ListSubnets2")]
pub mod ListSubnets2;
#[cfg(feature = "ListSubnetworkInterface")]
pub mod ListSubnetworkInterface;
#[cfg(feature = "ListSubNetworkInterfaces")]
pub mod ListSubNetworkInterfaces;
