#[cfg(feature = "BatchCreateDedicatedHostTags")]
pub mod BatchCreateDedicatedHostTags;
#[cfg(feature = "BatchDeleteDedicatedHostTags")]
pub mod BatchDeleteDedicatedHostTags;
#[cfg(feature = "ListDedicatedHosts")]
pub mod ListDedicatedHosts;
#[cfg(feature = "ListDedicatedHostsByTags")]
pub mod ListDedicatedHostsByTags;
#[cfg(feature = "ListDedicatedHostTypes")]
pub mod ListDedicatedHostTypes;
#[cfg(feature = "ListDehVersions")]
pub mod ListDehVersions;
#[cfg(feature = "ListServersDedicatedHost")]
pub mod ListServersDedicatedHost;
#[cfg(feature = "ShowDedicatedHost")]
pub mod ShowDedicatedHost;
#[cfg(feature = "ShowDedicatedHostTags")]
pub mod ShowDedicatedHostTags;
#[cfg(feature = "ShowDehVersion")]
pub mod ShowDehVersion;
#[cfg(feature = "ShowQuotaSets")]
pub mod ShowQuotaSets;
#[cfg(feature = "UpdateDedicatedHost")]
pub mod UpdateDedicatedHost;
