[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
ApplyExecutionPlan = []
ContinueDeployStack = []
ContinueRollbackStack = []
CreateExecutionPlan = []
CreatePrivateHook = []
CreatePrivateHookVersion = []
CreatePrivateModule = []
CreatePrivateModuleVersion = []
CreatePrivateProvider = []
CreatePrivateProviderVersion = []
CreateStack = []
CreateStackInstance = []
CreateStackSet = []
CreateTemplate = []
CreateTemplateVersion = []
DeleteExecutionPlan = []
DeletePrivateHook = []
DeletePrivateHookVersion = []
DeletePrivateModule = []
DeletePrivateModuleVersion = []
DeletePrivateProvider = []
DeletePrivateProviderVersion = []
DeleteStack = []
DeleteStackEnhanced = []
DeleteStackInstance = []
DeleteStackInstanceDeprecated = []
DeleteStackSet = []
DeleteTemplate = []
DeleteTemplateVersion = []
DeployStack = []
DeployStackSet = []
EstimateExecutionPlanPrice = []
GetExecutionPlan = []
GetExecutionPlanMetadata = []
GetStackMetadata = []
GetStackTemplate = []
ListExecutionPlans = []
ListPrivateHookVersions = []
ListPrivateHooks = []
ListPrivateModuleVersions = []
ListPrivateModules = []
ListPrivateProviderVersions = []
ListPrivateProviders = []
ListStackEvents = []
ListStackInstances = []
ListStackOutputs = []
ListStackResources = []
ListStackSetOperations = []
ListStackSets = []
ListStacks = []
ListTemplateVersions = []
ListTemplates = []
ParseTemplateVariables = []
ShowPrivateHookMetadata = []
ShowPrivateHookVersionMetadata = []
ShowPrivateHookVersionPolicy = []
ShowPrivateModuleMetadata = []
ShowPrivateModuleVersionContent = []
ShowPrivateModuleVersionMetadata = []
ShowPrivateProviderMetadata = []
ShowPrivateProviderVersionMetadata = []
ShowStackInstance = []
ShowStackSetMetadata = []
ShowStackSetOperationMetadata = []
ShowStackSetTemplate = []
ShowTemplateMetadata = []
ShowTemplateVersionContent = []
ShowTemplateVersionMetadata = []
UpdatePrivateHookMetadata = []
UpdatePrivateModuleMetadata = []
UpdatePrivateProviderMetadata = []
UpdateStack = []
UpdateStackInstances = []
UpdateStackSet = []
UpdateTemplateMetadata = []
full = ["ApplyExecutionPlan", "ContinueDeployStack", "ContinueRollbackStack", "CreateExecutionPlan", "CreatePrivateHook", "CreatePrivateHookVersion", "CreatePrivateModule", "CreatePrivateModuleVersion", "CreatePrivateProvider", "CreatePrivateProviderVersion", "CreateStack", "CreateStackInstance", "CreateStackSet", "CreateTemplate", "CreateTemplateVersion", "DeleteExecutionPlan", "DeletePrivateHook", "DeletePrivateHookVersion", "DeletePrivateModule", "DeletePrivateModuleVersion", "DeletePrivateProvider", "DeletePrivateProviderVersion", "DeleteStack", "DeleteStackEnhanced", "DeleteStackInstance", "DeleteStackInstanceDeprecated", "DeleteStackSet", "DeleteTemplate", "DeleteTemplateVersion", "DeployStack", "DeployStackSet", "EstimateExecutionPlanPrice", "GetExecutionPlan", "GetExecutionPlanMetadata", "GetStackMetadata", "GetStackTemplate", "ListExecutionPlans", "ListPrivateHooks", "ListPrivateHookVersions", "ListPrivateModules", "ListPrivateModuleVersions", "ListPrivateProviders", "ListPrivateProviderVersions", "ListStackEvents", "ListStackInstances", "ListStackOutputs", "ListStackResources", "ListStacks", "ListStackSetOperations", "ListStackSets", "ListTemplates", "ListTemplateVersions", "ParseTemplateVariables", "ShowPrivateHookMetadata", "ShowPrivateHookVersionMetadata", "ShowPrivateHookVersionPolicy", "ShowPrivateModuleMetadata", "ShowPrivateModuleVersionContent", "ShowPrivateModuleVersionMetadata", "ShowPrivateProviderMetadata", "ShowPrivateProviderVersionMetadata", "ShowStackInstance", "ShowStackSetMetadata", "ShowStackSetOperationMetadata", "ShowStackSetTemplate", "ShowTemplateMetadata", "ShowTemplateVersionContent", "ShowTemplateVersionMetadata", "UpdatePrivateHookMetadata", "UpdatePrivateModuleMetadata", "UpdatePrivateProviderMetadata", "UpdateStack", "UpdateStackInstances", "UpdateStackSet", "UpdateTemplateMetadata"]

[lib]
name = "huawei_cloud_api_definitions_AOS"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-AOS"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
