[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
ApplyExecutionPlan = []
ContinueDeployStack = []
ContinueRollbackStack = []
CreateExecutionPlan = []
CreateStack = []
CreateStackInstance = []
CreateStackSet = []
CreateTemplate = []
DeleteExecutionPlan = []
DeleteStack = []
DeleteStackEnhanced = []
DeleteStackInstance = []
DeleteStackInstanceDeprecated = []
DeleteStackSet = []
DeleteTemplate = []
DeleteTemplateVersion = []
DeployStack = []
DeployStackSet = []
DownloadTemplate = []
EstimateExecutionPlanPrice = []
GetExecutionPlan = []
GetExecutionPlanMetadata = []
GetStackMetadata = []
GetStackTemplate = []
ListBriefStack = []
ListBriefTemplates = []
ListExecutionPlans = []
ListStack = []
ListStackActions = []
ListStackElements = []
ListStackEvents = []
ListStackInputs = []
ListStackInstances = []
ListStackOutputs = []
ListStackResources = []
ListStackSetOperations = []
ListStackSets = []
ListStacks = []
ListTemplateInputs = []
ListTemplateVersions = []
ListTemplates = []
ParseTemplateVariables = []
ShowStackAction = []
ShowStackDetail = []
ShowStackElement = []
ShowStackInstance = []
ShowStackSetMetadata = []
ShowStackSetOperationMetadata = []
ShowStackSetTemplate = []
ShowTemplateDetail = []
ShowTemplateMetadata = []
ShowTemplateVersionContent = []
ShowTemplateVersionMetadata = []
UpdateStack = []
UpdateStackActions = []
UpdateStackInstances = []
UpdateStackSet = []
UpdateTemplate = []
UpdateTemplateMetadata = []
full = ["ApplyExecutionPlan", "ContinueDeployStack", "ContinueRollbackStack", "CreateExecutionPlan", "CreateStack", "CreateStackInstance", "CreateStackSet", "CreateTemplate", "DeleteExecutionPlan", "DeleteStack", "DeleteStackEnhanced", "DeleteStackInstance", "DeleteStackInstanceDeprecated", "DeleteStackSet", "DeleteTemplate", "DeleteTemplateVersion", "DeployStack", "DeployStackSet", "DownloadTemplate", "EstimateExecutionPlanPrice", "GetExecutionPlan", "GetExecutionPlanMetadata", "GetStackMetadata", "GetStackTemplate", "ListBriefStack", "ListBriefTemplates", "ListExecutionPlans", "ListStack", "ListStackActions", "ListStackElements", "ListStackEvents", "ListStackInputs", "ListStackInstances", "ListStackOutputs", "ListStackResources", "ListStacks", "ListStackSetOperations", "ListStackSets", "ListTemplateInputs", "ListTemplates", "ListTemplateVersions", "ParseTemplateVariables", "ShowStackAction", "ShowStackDetail", "ShowStackElement", "ShowStackInstance", "ShowStackSetMetadata", "ShowStackSetOperationMetadata", "ShowStackSetTemplate", "ShowTemplateDetail", "ShowTemplateMetadata", "ShowTemplateVersionContent", "ShowTemplateVersionMetadata", "UpdateStack", "UpdateStackActions", "UpdateStackInstances", "UpdateStackSet", "UpdateTemplate", "UpdateTemplateMetadata"]

[lib]
name = "huawei_cloud_api_definitions_AOS"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-AOS"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "0.1.1"
