[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddDevData = []
AddPipelineJob = []
CreateAssetModel = []
CreateAssetNew = []
CreateBatchJob = []
CreateComputingResource = []
CreateDatasource = []
CreateGroup = []
CreateRun = []
CreateStreamingJob = []
CreateTable = []
DeleteAssetModel = []
DeleteAssetNew = []
DeleteBatchJob = []
DeleteComputingResource = []
DeleteDataStore = []
DeleteDatasource = []
DeleteGroup = []
DeletePipelineJob = []
DeleteRun = []
DeleteStreamingJobById = []
DeleteTable = []
ExportDataset = []
ImportData = []
ListAssetModels = []
ListAssetsNew = []
ListBatchJobs = []
ListComputingResources = []
ListDataStores = []
ListGroups = []
ListHistory = []
ListMetrics = []
ListPipelineJobs = []
ListRuns = []
ListTables = []
ListTagValues = []
PublishRootAsset = []
ShowAllDataSource = []
ShowAssetModel = []
ShowAssetNew = []
ShowBatchJob = []
ShowDataSource = []
ShowDataset = []
ShowJobById = []
ShowJobs = []
ShowLastPropertyValue = []
ShowMetricValue = []
ShowPipelineJob = []
ShowPropertyRawValue = []
ShowPropertyValues = []
ShowRun = []
ShowTablePreview = []
ShowTableSchema = []
StartJob = []
StartPipelineJob = []
StopJob = []
StopPipelineJob = []
UpdateAssetModel = []
UpdateAssetNew = []
UpdateBatchJob = []
UpdateDataSource = []
UpdateDataStore = []
UpdateGroup = []
UpdatePipelineJob = []
UpdateStreamingJob = []
ValidateSql = []
full = ["AddDevData", "AddPipelineJob", "CreateAssetModel", "CreateAssetNew", "CreateBatchJob", "CreateComputingResource", "CreateDatasource", "CreateGroup", "CreateRun", "CreateStreamingJob", "CreateTable", "DeleteAssetModel", "DeleteAssetNew", "DeleteBatchJob", "DeleteComputingResource", "DeleteDatasource", "DeleteDataStore", "DeleteGroup", "DeletePipelineJob", "DeleteRun", "DeleteStreamingJobById", "DeleteTable", "ExportDataset", "ImportData", "ListAssetModels", "ListAssetsNew", "ListBatchJobs", "ListComputingResources", "ListDataStores", "ListGroups", "ListHistory", "ListMetrics", "ListPipelineJobs", "ListRuns", "ListTables", "ListTagValues", "PublishRootAsset", "ShowAllDataSource", "ShowAssetModel", "ShowAssetNew", "ShowBatchJob", "ShowDataset", "ShowDataSource", "ShowJobById", "ShowJobs", "ShowLastPropertyValue", "ShowMetricValue", "ShowPipelineJob", "ShowPropertyRawValue", "ShowPropertyValues", "ShowRun", "ShowTablePreview", "ShowTableSchema", "StartJob", "StartPipelineJob", "StopJob", "StopPipelineJob", "UpdateAssetModel", "UpdateAssetNew", "UpdateBatchJob", "UpdateDataSource", "UpdateDataStore", "UpdateGroup", "UpdatePipelineJob", "UpdateStreamingJob", "ValidateSql"]

[lib]
name = "huawei_cloud_api_definitions_IoTAnalytics"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-IoTAnalytics"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
