#[cfg(feature = "AddForwardingConfigs")]
pub mod AddForwardingConfigs;
#[cfg(feature = "BatchShowEdgeApps")]
pub mod BatchShowEdgeApps;
#[cfg(feature = "BatchShowEdgeAppVersions")]
pub mod BatchShowEdgeAppVersions;
#[cfg(feature = "BatchShowIpcs")]
pub mod BatchShowIpcs;
#[cfg(feature = "BatchShowRadars")]
pub mod BatchShowRadars;
#[cfg(feature = "BatchShowRsus")]
pub mod BatchShowRsus;
#[cfg(feature = "BatchShowTrafficControllers")]
pub mod BatchShowTrafficControllers;
#[cfg(feature = "BatchShowTrafficEvents")]
pub mod BatchShowTrafficEvents;
#[cfg(feature = "BatchShowVehicles")]
pub mod BatchShowVehicles;
#[cfg(feature = "CreateDataChannel")]
pub mod CreateDataChannel;
#[cfg(feature = "CreateEdgeApp")]
pub mod CreateEdgeApp;
#[cfg(feature = "CreateEdgeApplicationVersion")]
pub mod CreateEdgeApplicationVersion;
#[cfg(feature = "CreateRsu")]
pub mod CreateRsu;
#[cfg(feature = "CreateRsuModel")]
pub mod CreateRsuModel;
#[cfg(feature = "CreateTrafficController")]
pub mod CreateTrafficController;
#[cfg(feature = "CreateTrafficEvent")]
pub mod CreateTrafficEvent;
#[cfg(feature = "CreateV2xEdge")]
pub mod CreateV2xEdge;
#[cfg(feature = "CreateV2xEdgeApp")]
pub mod CreateV2xEdgeApp;
#[cfg(feature = "CreateVehicle")]
pub mod CreateVehicle;
#[cfg(feature = "DeleteDataChannel")]
pub mod DeleteDataChannel;
#[cfg(feature = "DeleteEdgeApp")]
pub mod DeleteEdgeApp;
#[cfg(feature = "DeleteEdgeApplicationVersion")]
pub mod DeleteEdgeApplicationVersion;
#[cfg(feature = "DeleteForwardingConfig")]
pub mod DeleteForwardingConfig;
#[cfg(feature = "DeleteRsu")]
pub mod DeleteRsu;
#[cfg(feature = "DeleteRsuModel")]
pub mod DeleteRsuModel;
#[cfg(feature = "DeleteTrafficController")]
pub mod DeleteTrafficController;
#[cfg(feature = "DeleteTrafficEvent")]
pub mod DeleteTrafficEvent;
#[cfg(feature = "DeleteV2XEdgeAppByEdgeAppId")]
pub mod DeleteV2XEdgeAppByEdgeAppId;
#[cfg(feature = "DeleteV2XEdgeByV2xEdgeId")]
pub mod DeleteV2XEdgeByV2xEdgeId;
#[cfg(feature = "DeleteVehicle")]
pub mod DeleteVehicle;
#[cfg(feature = "ListEdgeFlows")]
pub mod ListEdgeFlows;
#[cfg(feature = "ListRsuModels")]
pub mod ListRsuModels;
#[cfg(feature = "ListV2xEdgeApp")]
pub mod ListV2xEdgeApp;
#[cfg(feature = "ListV2xEdges")]
pub mod ListV2xEdges;
#[cfg(feature = "SendImmediateEvent")]
pub mod SendImmediateEvent;
#[cfg(feature = "ShowDataChannel")]
pub mod ShowDataChannel;
#[cfg(feature = "ShowDeploymentCode")]
pub mod ShowDeploymentCode;
#[cfg(feature = "ShowEdgeApplicationVersion")]
pub mod ShowEdgeApplicationVersion;
#[cfg(feature = "ShowForwardingConfig")]
pub mod ShowForwardingConfig;
#[cfg(feature = "ShowForwardingConfigs")]
pub mod ShowForwardingConfigs;
#[cfg(feature = "ShowHistoryTrafficEvents")]
pub mod ShowHistoryTrafficEvents;
#[cfg(feature = "ShowIpc")]
pub mod ShowIpc;
#[cfg(feature = "ShowRsuModel")]
pub mod ShowRsuModel;
#[cfg(feature = "ShowTrafficEvent")]
pub mod ShowTrafficEvent;
#[cfg(feature = "ShowV2XEdgeAppDetailByEdgeAppId")]
pub mod ShowV2XEdgeAppDetailByEdgeAppId;
#[cfg(feature = "ShowV2xEdgeDetail")]
pub mod ShowV2xEdgeDetail;
#[cfg(feature = "UpdateDataChannel")]
pub mod UpdateDataChannel;
#[cfg(feature = "UpdateEdgeApp")]
pub mod UpdateEdgeApp;
#[cfg(feature = "UpdateEdgeApplicationVersion")]
pub mod UpdateEdgeApplicationVersion;
#[cfg(feature = "UpdateEdgeApplicationVersionState")]
pub mod UpdateEdgeApplicationVersionState;
#[cfg(feature = "UpdateForwardingConfig")]
pub mod UpdateForwardingConfig;
#[cfg(feature = "UpdateRsu")]
pub mod UpdateRsu;
#[cfg(feature = "UpdateRsuModel")]
pub mod UpdateRsuModel;
#[cfg(feature = "UpdateTrafficController")]
pub mod UpdateTrafficController;
#[cfg(feature = "UpdateTrafficEvent")]
pub mod UpdateTrafficEvent;
#[cfg(feature = "UpdateV2xEdge")]
pub mod UpdateV2xEdge;
#[cfg(feature = "UpdateV2xEdgeApp")]
pub mod UpdateV2xEdgeApp;
#[cfg(feature = "UpdateVehicle")]
pub mod UpdateVehicle;
