#[cfg(feature = "AddSubscription")]
pub mod AddSubscription;
#[cfg(feature = "AddSubscriptionFromSubscriptionUser")]
pub mod AddSubscriptionFromSubscriptionUser;
#[cfg(feature = "BatchCreateOrDeleteResourceTags")]
pub mod BatchCreateOrDeleteResourceTags;
#[cfg(feature = "BatchCreateSubscriptionsFilterPolices")]
pub mod BatchCreateSubscriptionsFilterPolices;
#[cfg(feature = "BatchDeleteSubscriptionsFilterPolices")]
pub mod BatchDeleteSubscriptionsFilterPolices;
#[cfg(feature = "BatchUpdateSubscriptionsFilterPolices")]
pub mod BatchUpdateSubscriptionsFilterPolices;
#[cfg(feature = "CancelSubscription")]
pub mod CancelSubscription;
#[cfg(feature = "CreateApplication")]
pub mod CreateApplication;
#[cfg(feature = "CreateApplicationEndpoint")]
pub mod CreateApplicationEndpoint;
#[cfg(feature = "CreateLogtank")]
pub mod CreateLogtank;
#[cfg(feature = "CreateMessageTemplate")]
pub mod CreateMessageTemplate;
#[cfg(feature = "CreateNotifyPolicy")]
pub mod CreateNotifyPolicy;
#[cfg(feature = "CreateResourceTag")]
pub mod CreateResourceTag;
#[cfg(feature = "CreateTopic")]
pub mod CreateTopic;
#[cfg(feature = "DeleteApplication")]
pub mod DeleteApplication;
#[cfg(feature = "DeleteApplicationEndpoint")]
pub mod DeleteApplicationEndpoint;
#[cfg(feature = "DeleteLogtank")]
pub mod DeleteLogtank;
#[cfg(feature = "DeleteMessageTemplate")]
pub mod DeleteMessageTemplate;
#[cfg(feature = "DeleteNotifyPolicy")]
pub mod DeleteNotifyPolicy;
#[cfg(feature = "DeleteResourceTag")]
pub mod DeleteResourceTag;
#[cfg(feature = "DeleteTopic")]
pub mod DeleteTopic;
#[cfg(feature = "DeleteTopicAttributeByName")]
pub mod DeleteTopicAttributeByName;
#[cfg(feature = "DeleteTopicAttributes")]
pub mod DeleteTopicAttributes;
#[cfg(feature = "ListApplicationAttributes")]
pub mod ListApplicationAttributes;
#[cfg(feature = "ListApplicationEndpointAttributes")]
pub mod ListApplicationEndpointAttributes;
#[cfg(feature = "ListApplicationEndpoints")]
pub mod ListApplicationEndpoints;
#[cfg(feature = "ListApplications")]
pub mod ListApplications;
#[cfg(feature = "ListLogtank")]
pub mod ListLogtank;
#[cfg(feature = "ListMessageTemplateDetails")]
pub mod ListMessageTemplateDetails;
#[cfg(feature = "ListMessageTemplates")]
pub mod ListMessageTemplates;
#[cfg(feature = "ListProjectTags")]
pub mod ListProjectTags;
#[cfg(feature = "ListResourceInstances")]
pub mod ListResourceInstances;
#[cfg(feature = "ListResourceTags")]
pub mod ListResourceTags;
#[cfg(feature = "ListSubscriptions")]
pub mod ListSubscriptions;
#[cfg(feature = "ListSubscriptionsByTopic")]
pub mod ListSubscriptionsByTopic;
#[cfg(feature = "ListTopicAttributes")]
pub mod ListTopicAttributes;
#[cfg(feature = "ListTopicDetails")]
pub mod ListTopicDetails;
#[cfg(feature = "ListTopicMessageStatistics")]
pub mod ListTopicMessageStatistics;
#[cfg(feature = "ListTopics")]
pub mod ListTopics;
#[cfg(feature = "ListVersion")]
pub mod ListVersion;
#[cfg(feature = "ListVersions")]
pub mod ListVersions;
#[cfg(feature = "PublishAppMessage")]
pub mod PublishAppMessage;
#[cfg(feature = "PublishHttpDetect")]
pub mod PublishHttpDetect;
#[cfg(feature = "PublishMessage")]
pub mod PublishMessage;
#[cfg(feature = "ShowHttpDetectResult")]
pub mod ShowHttpDetectResult;
#[cfg(feature = "ShowNotifyPolicy")]
pub mod ShowNotifyPolicy;
#[cfg(feature = "UpdateApplication")]
pub mod UpdateApplication;
#[cfg(feature = "UpdateApplicationEndpoint")]
pub mod UpdateApplicationEndpoint;
#[cfg(feature = "UpdateLogtank")]
pub mod UpdateLogtank;
#[cfg(feature = "UpdateMessageTemplate")]
pub mod UpdateMessageTemplate;
#[cfg(feature = "UpdateNotifyPolicy")]
pub mod UpdateNotifyPolicy;
#[cfg(feature = "UpdateSubscription")]
pub mod UpdateSubscription;
#[cfg(feature = "UpdateTopic")]
pub mod UpdateTopic;
#[cfg(feature = "UpdateTopicAttribute")]
pub mod UpdateTopicAttribute;
