#[cfg(feature = "AddSpurPoint")]
pub mod AddSpurPoint;
#[cfg(feature = "CreateCommonWorkspace")]
pub mod CreateCommonWorkspace;
#[cfg(feature = "CreateMarkerInfo")]
pub mod CreateMarkerInfo;
#[cfg(feature = "CreateReal3DTask")]
pub mod CreateReal3DTask;
#[cfg(feature = "CreateTask")]
pub mod CreateTask;
#[cfg(feature = "DeleteCommonWorkspace")]
pub mod DeleteCommonWorkspace;
#[cfg(feature = "DeleteReal3DProduct")]
pub mod DeleteReal3DProduct;
#[cfg(feature = "DeleteReal3DTask")]
pub mod DeleteReal3DTask;
#[cfg(feature = "DeleteSpurPoint")]
pub mod DeleteSpurPoint;
#[cfg(feature = "DeleteTask")]
pub mod DeleteTask;
#[cfg(feature = "ListCommonWorkspace")]
pub mod ListCommonWorkspace;
#[cfg(feature = "ListFolder")]
pub mod ListFolder;
#[cfg(feature = "ListImageBaseInfo")]
pub mod ListImageBaseInfo;
#[cfg(feature = "ListReal3DProducts")]
pub mod ListReal3DProducts;
#[cfg(feature = "ListSpurPoints")]
pub mod ListSpurPoints;
#[cfg(feature = "ListTaskInfo")]
pub mod ListTaskInfo;
#[cfg(feature = "ListTasksInWorkspace")]
pub mod ListTasksInWorkspace;
#[cfg(feature = "ListUsageInfo")]
pub mod ListUsageInfo;
#[cfg(feature = "ShowReal3DUsage")]
pub mod ShowReal3DUsage;
#[cfg(feature = "ShowSpurCount")]
pub mod ShowSpurCount;
#[cfg(feature = "ShowTaskOverview")]
pub mod ShowTaskOverview;
#[cfg(feature = "ShowTaskOverviewInWorkspace")]
pub mod ShowTaskOverviewInWorkspace;
#[cfg(feature = "StartNavi")]
pub mod StartNavi;
#[cfg(feature = "StartReal3DTask")]
pub mod StartReal3DTask;
#[cfg(feature = "StartTask")]
pub mod StartTask;
#[cfg(feature = "StartVps")]
pub mod StartVps;
#[cfg(feature = "StopReal3DTask")]
pub mod StopReal3DTask;
#[cfg(feature = "StopTask")]
pub mod StopTask;
#[cfg(feature = "UpdateCommonWorkspace")]
pub mod UpdateCommonWorkspace;
#[cfg(feature = "UpdateReal3DTask")]
pub mod UpdateReal3DTask;
#[cfg(feature = "UpdateReal3DTaskArchivedStatus")]
pub mod UpdateReal3DTaskArchivedStatus;
#[cfg(feature = "UpdateTaskArchivedStatus")]
pub mod UpdateTaskArchivedStatus;
#[cfg(feature = "ValidateImage")]
pub mod ValidateImage;
