[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
BatchChangeData = []
BatchCheckJobs = []
BatchCheckResults = []
BatchCreateJobs = []
BatchCreateJobsAsync = []
BatchCreateTags = []
BatchDeleteJobs = []
BatchDeleteJobsById = []
BatchDeleteTags = []
BatchExecuteJobActions = []
BatchListJobDetails = []
BatchListJobStatus = []
BatchListProgresses = []
BatchListRposAndRtos = []
BatchListStructDetail = []
BatchListStructProcess = []
BatchResetPassword = []
BatchRestoreTask = []
BatchSetDefiner = []
BatchSetObjects = []
BatchSetPolicy = []
BatchSetSmn = []
BatchSetSpeed = []
BatchShowParams = []
BatchStartJobs = []
BatchStopJobs = []
BatchStopJobsAction = []
BatchSwitchover = []
BatchTagAction = []
BatchUpdateJob = []
BatchUpdateUser = []
BatchValidateClustersConnections = []
BatchValidateConnections = []
CheckDataFilter = []
CollectColumns = []
CollectDbObjectsAsync = []
CollectDbObjectsInfo = []
CollectPositionAsync = []
CommitAsyncJob = []
CopyJob = []
CountInstanceByTags = []
CreateCompareTask = []
CreateDataLevelTableCompareJob = []
CreateJob = []
DeleteCompareJob = []
DeleteJdbcDriver = []
DeleteJob = []
DownloadBatchCreateTemplate = []
DownloadDbObjectTemplate = []
ExecuteJobAction = []
ExportOperationInfo = []
ImportBatchCreateJobs = []
ListAsyncJobDetail = []
ListAsyncJobs = []
ListAvailableNodeTypes = []
ListAvailableZone = []
ListCompareResult = []
ListContentCompareDetail = []
ListContentCompareOverview = []
ListDataCompareDetail = []
ListDataCompareOverview = []
ListDataLevelTableCompareJobs = []
ListDbObjects = []
ListInstanceByTags = []
ListInstanceTags = []
ListJdbcDrivers = []
ListJobHistoryParameters = []
ListJobParameters = []
ListJobs = []
ListLinks = []
ListProjectTags = []
ListTags = []
ListUsers = []
ListsAgencyPermissions = []
ShowActions = []
ShowColumnInfoResult = []
ShowComparePolicy = []
ShowDataFilteringResult = []
ShowDataProcessingRulesResult = []
ShowDataProgress = []
ShowDbObjectCollectionStatus = []
ShowDbObjectTemplateProgress = []
ShowDbObjectTemplateResult = []
ShowDbObjectsList = []
ShowDirtyData = []
ShowEnterpriseProject = []
ShowHealthCompareJobList = []
ShowIncrementComponentsDetail = []
ShowInstanceTags = []
ShowJobDetail = []
ShowJobList = []
ShowMetering = []
ShowMonitorData = []
ShowMonitoringData = []
ShowObjectMapping = []
ShowPositionResult = []
ShowProgressData = []
ShowQuotas = []
ShowReplayResults = []
ShowSupportObjectType = []
full = ["BatchChangeData", "BatchCheckJobs", "BatchCheckResults", "BatchCreateJobs", "BatchCreateJobsAsync", "BatchCreateTags", "BatchDeleteJobs", "BatchDeleteJobsById", "BatchDeleteTags", "BatchExecuteJobActions", "BatchListJobDetails", "BatchListJobStatus", "BatchListProgresses", "BatchListRposAndRtos", "BatchListStructDetail", "BatchListStructProcess", "BatchResetPassword", "BatchRestoreTask", "BatchSetDefiner", "BatchSetObjects", "BatchSetPolicy", "BatchSetSmn", "BatchSetSpeed", "BatchShowParams", "BatchStartJobs", "BatchStopJobs", "BatchStopJobsAction", "BatchSwitchover", "BatchTagAction", "BatchUpdateJob", "BatchUpdateUser", "BatchValidateClustersConnections", "BatchValidateConnections", "CheckDataFilter", "CollectColumns", "CollectDbObjectsAsync", "CollectDbObjectsInfo", "CollectPositionAsync", "CommitAsyncJob", "CopyJob", "CountInstanceByTags", "CreateCompareTask", "CreateDataLevelTableCompareJob", "CreateJob", "DeleteCompareJob", "DeleteJdbcDriver", "DeleteJob", "DownloadBatchCreateTemplate", "DownloadDbObjectTemplate", "ExecuteJobAction", "ExportOperationInfo", "ImportBatchCreateJobs", "ListAsyncJobDetail", "ListAsyncJobs", "ListAvailableNodeTypes", "ListAvailableZone", "ListCompareResult", "ListContentCompareDetail", "ListContentCompareOverview", "ListDataCompareDetail", "ListDataCompareOverview", "ListDataLevelTableCompareJobs", "ListDbObjects", "ListInstanceByTags", "ListInstanceTags", "ListJdbcDrivers", "ListJobHistoryParameters", "ListJobParameters", "ListJobs", "ListLinks", "ListProjectTags", "ListsAgencyPermissions", "ListTags", "ListUsers", "ShowActions", "ShowColumnInfoResult", "ShowComparePolicy", "ShowDataFilteringResult", "ShowDataProcessingRulesResult", "ShowDataProgress", "ShowDbObjectCollectionStatus", "ShowDbObjectsList", "ShowDbObjectTemplateProgress", "ShowDbObjectTemplateResult", "ShowDirtyData", "ShowEnterpriseProject", "ShowHealthCompareJobList", "ShowIncrementComponentsDetail", "ShowInstanceTags", "ShowJobDetail", "ShowJobList", "ShowMetering", "ShowMonitorData", "ShowMonitoringData", "ShowObjectMapping", "ShowPositionResult", "ShowProgressData", "ShowQuotas", "ShowReplayResults", "ShowSupportObjectType"]

[lib]
name = "huawei_cloud_api_definitions_DRS"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-DRS"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
