[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
BatchChangeData = []
BatchCheckJobs = []
BatchCheckResults = []
BatchCreateJobs = []
BatchCreateJobsAsync = []
BatchCreateTags = []
BatchDeleteJobs = []
BatchDeleteJobsById = []
BatchDeleteTags = []
BatchExecuteJobActions = []
BatchListJobDetails = []
BatchListJobStatus = []
BatchListProgresses = []
BatchListRposAndRtos = []
BatchListStructDetail = []
BatchListStructProcess = []
BatchResetPassword = []
BatchRestoreTask = []
BatchSetDefiner = []
BatchSetObjects = []
BatchSetPolicy = []
BatchSetSmn = []
BatchSetSpeed = []
BatchShowParams = []
BatchStartJobs = []
BatchStopJobs = []
BatchStopJobsAction = []
BatchSwitchover = []
BatchTagAction = []
BatchUpdateJob = []
BatchUpdateUser = []
BatchValidateClustersConnections = []
BatchValidateConnections = []
ChangeToPeriod = []
CheckDataFilter = []
CleanAlarms = []
CollectColumns = []
CollectDbObjectsAsync = []
CollectDbObjectsInfo = []
CollectPositionAsync = []
CommitAsyncJob = []
CopyJob = []
CountInstanceByTags = []
CreateCompareResultFile = []
CreateCompareTask = []
CreateConnection = []
CreateDataLevelTableCompareJob = []
CreateJob = []
CreateObjectLevelCompareJob = []
CreateReplicationJob = []
DeleteCompareJob = []
DeleteConnection = []
DeleteJdbcDriver = []
DeleteJob = []
DeleteReplicationJob = []
DeleteUserJdbcDriver = []
DownloadBatchCreateTemplate = []
DownloadCompareResultFile = []
DownloadCreateTemplate = []
DownloadDbObjectTemplate = []
ExecuteJobAction = []
ExportCreationTemplate = []
ExportOperationInfo = []
ImportBatchCreateJobs = []
ListAsyncJobDetail = []
ListAsyncJobs = []
ListAvailableNodeTypes = []
ListAvailableZone = []
ListCompareResult = []
ListConnections = []
ListContentCompareDetail = []
ListContentCompareDifference = []
ListContentCompareOverview = []
ListDataCompareDetail = []
ListDataCompareOverview = []
ListDataLevelTableCompareJobs = []
ListDbObjects = []
ListFeatures = []
ListInstanceByTags = []
ListInstanceTags = []
ListJdbcDrivers = []
ListJobDdls = []
ListJobHistoryParameters = []
ListJobParameters = []
ListJobs = []
ListLinks = []
ListObejectLevelCompareDetail = []
ListObejectLevelCompareOverview = []
ListProjectTags = []
ListReplicationJobs = []
ListTags = []
ListTemplates = []
ListUserJdbcDrivers = []
ListUsers = []
ListsAgencyPermissions = []
ModifyConnection = []
ShowActions = []
ShowAgencyInfo = []
ShowColumnInfoResult = []
ShowComparePolicy = []
full = ["BatchChangeData", "BatchCheckJobs", "BatchCheckResults", "BatchCreateJobs", "BatchCreateJobsAsync", "BatchCreateTags", "BatchDeleteJobs", "BatchDeleteJobsById", "BatchDeleteTags", "BatchExecuteJobActions", "BatchListJobDetails", "BatchListJobStatus", "BatchListProgresses", "BatchListRposAndRtos", "BatchListStructDetail", "BatchListStructProcess", "BatchResetPassword", "BatchRestoreTask", "BatchSetDefiner", "BatchSetObjects", "BatchSetPolicy", "BatchSetSmn", "BatchSetSpeed", "BatchShowParams", "BatchStartJobs", "BatchStopJobs", "BatchStopJobsAction", "BatchSwitchover", "BatchTagAction", "BatchUpdateJob", "BatchUpdateUser", "BatchValidateClustersConnections", "BatchValidateConnections", "ChangeToPeriod", "CheckDataFilter", "CleanAlarms", "CollectColumns", "CollectDbObjectsAsync", "CollectDbObjectsInfo", "CollectPositionAsync", "CommitAsyncJob", "CopyJob", "CountInstanceByTags", "CreateCompareResultFile", "CreateCompareTask", "CreateConnection", "CreateDataLevelTableCompareJob", "CreateJob", "CreateObjectLevelCompareJob", "CreateReplicationJob", "DeleteCompareJob", "DeleteConnection", "DeleteJdbcDriver", "DeleteJob", "DeleteReplicationJob", "DeleteUserJdbcDriver", "DownloadBatchCreateTemplate", "DownloadCompareResultFile", "DownloadCreateTemplate", "DownloadDbObjectTemplate", "ExecuteJobAction", "ExportCreationTemplate", "ExportOperationInfo", "ImportBatchCreateJobs", "ListAsyncJobDetail", "ListAsyncJobs", "ListAvailableNodeTypes", "ListAvailableZone", "ListCompareResult", "ListConnections", "ListContentCompareDetail", "ListContentCompareDifference", "ListContentCompareOverview", "ListDataCompareDetail", "ListDataCompareOverview", "ListDataLevelTableCompareJobs", "ListDbObjects", "ListFeatures", "ListInstanceByTags", "ListInstanceTags", "ListJdbcDrivers", "ListJobDdls", "ListJobHistoryParameters", "ListJobParameters", "ListJobs", "ListLinks", "ListObejectLevelCompareDetail", "ListObejectLevelCompareOverview", "ListProjectTags", "ListReplicationJobs", "ListsAgencyPermissions", "ListTags", "ListTemplates", "ListUserJdbcDrivers", "ListUsers", "ModifyConnection", "ShowActions", "ShowAgencyInfo", "ShowColumnInfoResult", "ShowComparePolicy"]

[lib]
name = "huawei_cloud_api_definitions_DRS"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-DRS"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
