#[cfg(feature = "BatchAddDeleteTags")]
pub mod BatchAddDeleteTags;
#[cfg(feature = "CreateApp")]
pub mod CreateApp;
#[cfg(feature = "CreateAppVersions")]
pub mod CreateAppVersions;
#[cfg(feature = "CreateBatchJob")]
pub mod CreateBatchJob;
#[cfg(feature = "CreateConfigMap")]
pub mod CreateConfigMap;
#[cfg(feature = "CreateDeployments")]
pub mod CreateDeployments;
#[cfg(feature = "CreateDevice")]
pub mod CreateDevice;
#[cfg(feature = "CreateDeviceTemplate")]
pub mod CreateDeviceTemplate;
#[cfg(feature = "CreateEdgeGroup")]
pub mod CreateEdgeGroup;
#[cfg(feature = "CreateEdgeGroupCert")]
pub mod CreateEdgeGroupCert;
#[cfg(feature = "CreateEdgeNode")]
pub mod CreateEdgeNode;
#[cfg(feature = "CreateEdgeNodeCerts")]
pub mod CreateEdgeNodeCerts;
#[cfg(feature = "CreateEncryptdatas")]
pub mod CreateEncryptdatas;
#[cfg(feature = "CreateEndpoint")]
pub mod CreateEndpoint;
#[cfg(feature = "CreateNodeEncryptdatas")]
pub mod CreateNodeEncryptdatas;
#[cfg(feature = "CreateProduct")]
pub mod CreateProduct;
#[cfg(feature = "CreateRule")]
pub mod CreateRule;
#[cfg(feature = "CreateSecret")]
pub mod CreateSecret;
#[cfg(feature = "CreateService")]
pub mod CreateService;
#[cfg(feature = "CreateSystemEvent")]
pub mod CreateSystemEvent;
#[cfg(feature = "CreateTag")]
pub mod CreateTag;
#[cfg(feature = "DeleteApp")]
pub mod DeleteApp;
#[cfg(feature = "DeleteAppVersion")]
pub mod DeleteAppVersion;
#[cfg(feature = "DeleteBatchJob")]
pub mod DeleteBatchJob;
#[cfg(feature = "DeleteConfigMap")]
pub mod DeleteConfigMap;
#[cfg(feature = "DeleteDeployment")]
pub mod DeleteDeployment;
#[cfg(feature = "DeleteDevice")]
pub mod DeleteDevice;
#[cfg(feature = "DeleteDeviceTemplate")]
pub mod DeleteDeviceTemplate;
#[cfg(feature = "DeleteEdgeGroup")]
pub mod DeleteEdgeGroup;
#[cfg(feature = "DeleteEdgeGroupCert")]
pub mod DeleteEdgeGroupCert;
#[cfg(feature = "DeleteEdgeNode")]
pub mod DeleteEdgeNode;
#[cfg(feature = "DeleteEdgeNodeCerts")]
pub mod DeleteEdgeNodeCerts;
#[cfg(feature = "DeleteEncryptdatas")]
pub mod DeleteEncryptdatas;
#[cfg(feature = "DeleteEndPoint")]
pub mod DeleteEndPoint;
#[cfg(feature = "DeleteNodeEncryptdatas")]
pub mod DeleteNodeEncryptdatas;
#[cfg(feature = "DeletePod")]
pub mod DeletePod;
#[cfg(feature = "DeleteProduct")]
pub mod DeleteProduct;
#[cfg(feature = "DeleteResourceTag")]
pub mod DeleteResourceTag;
#[cfg(feature = "DeleteRule")]
pub mod DeleteRule;
#[cfg(feature = "DeleteSecret")]
pub mod DeleteSecret;
#[cfg(feature = "DeleteService")]
pub mod DeleteService;
#[cfg(feature = "DeleteSystemEvent")]
pub mod DeleteSystemEvent;
#[cfg(feature = "EnableDisableEdgeNodes")]
pub mod EnableDisableEdgeNodes;
#[cfg(feature = "ListApps")]
pub mod ListApps;
#[cfg(feature = "ListAppVersions")]
pub mod ListAppVersions;
#[cfg(feature = "ListBatchJob")]
pub mod ListBatchJob;
#[cfg(feature = "ListConfigMaps")]
pub mod ListConfigMaps;
#[cfg(feature = "ListDeployments")]
pub mod ListDeployments;
#[cfg(feature = "ListDevices")]
pub mod ListDevices;
#[cfg(feature = "ListDeviceTemplates")]
pub mod ListDeviceTemplates;
#[cfg(feature = "ListEdgeGroupCerts")]
pub mod ListEdgeGroupCerts;
#[cfg(feature = "ListEdgeGroups")]
pub mod ListEdgeGroups;
#[cfg(feature = "ListEdgeNodeCerts")]
pub mod ListEdgeNodeCerts;
#[cfg(feature = "ListEdgeNodes")]
pub mod ListEdgeNodes;
#[cfg(feature = "ListEncryptdataNodes")]
pub mod ListEncryptdataNodes;
#[cfg(feature = "ListEncryptdatas")]
pub mod ListEncryptdatas;
#[cfg(feature = "ListEndpoints")]
pub mod ListEndpoints;
#[cfg(feature = "ListNodeEncryptdatas")]
pub mod ListNodeEncryptdatas;
#[cfg(feature = "ListPods")]
pub mod ListPods;
#[cfg(feature = "ListProducts")]
pub mod ListProducts;
#[cfg(feature = "ListResourceByTags")]
pub mod ListResourceByTags;
#[cfg(feature = "ListRuleErrors")]
pub mod ListRuleErrors;
#[cfg(feature = "ListRules")]
pub mod ListRules;
#[cfg(feature = "ListSecrets")]
pub mod ListSecrets;
#[cfg(feature = "ListServices")]
pub mod ListServices;
#[cfg(feature = "ListSystemEvents")]
pub mod ListSystemEvents;
#[cfg(feature = "ListTags")]
pub mod ListTags;
#[cfg(feature = "ListTagsByResourceType")]
pub mod ListTagsByResourceType;
#[cfg(feature = "RestartDeploymentsPod")]
pub mod RestartDeploymentsPod;
#[cfg(feature = "RestoreBatchJob")]
pub mod RestoreBatchJob;
#[cfg(feature = "RetryBatchJob")]
pub mod RetryBatchJob;
#[cfg(feature = "ShowAppDetail")]
pub mod ShowAppDetail;
#[cfg(feature = "ShowAppVersionDetail")]
pub mod ShowAppVersionDetail;
#[cfg(feature = "ShowBatchJob")]
pub mod ShowBatchJob;
#[cfg(feature = "ShowConfigMap")]
pub mod ShowConfigMap;
#[cfg(feature = "ShowDeployment")]
pub mod ShowDeployment;
#[cfg(feature = "ShowDevice")]
pub mod ShowDevice;
#[cfg(feature = "ShowDeviceTemplate")]
pub mod ShowDeviceTemplate;
#[cfg(feature = "ShowDeviceTwin")]
pub mod ShowDeviceTwin;
#[cfg(feature = "ShowEdgeGroupCertDetail")]
pub mod ShowEdgeGroupCertDetail;
#[cfg(feature = "ShowEdgeGroupDetail")]
pub mod ShowEdgeGroupDetail;
#[cfg(feature = "ShowEdgeNodeDetail")]
pub mod ShowEdgeNodeDetail;
#[cfg(feature = "ShowEncryptdatas")]
pub mod ShowEncryptdatas;
#[cfg(feature = "ShowEndPointDetail")]
pub mod ShowEndPointDetail;
#[cfg(feature = "ShowProductDetail")]
pub mod ShowProductDetail;
#[cfg(feature = "ShowQuota")]
pub mod ShowQuota;
#[cfg(feature = "ShowRuleDetail")]
pub mod ShowRuleDetail;
#[cfg(feature = "ShowSecret")]
pub mod ShowSecret;
#[cfg(feature = "ShowServiceDetail")]
pub mod ShowServiceDetail;
#[cfg(feature = "ShowSystemEventDetail")]
pub mod ShowSystemEventDetail;
#[cfg(feature = "StartRule")]
pub mod StartRule;
#[cfg(feature = "StartSystemEvent")]
pub mod StartSystemEvent;
#[cfg(feature = "StopBatchJob")]
pub mod StopBatchJob;
#[cfg(feature = "StopRule")]
pub mod StopRule;
#[cfg(feature = "StopSystemEvent")]
pub mod StopSystemEvent;
#[cfg(feature = "UpdateApp")]
pub mod UpdateApp;
#[cfg(feature = "UpdateAppVersion")]
pub mod UpdateAppVersion;
#[cfg(feature = "UpdateConfigMap")]
pub mod UpdateConfigMap;
#[cfg(feature = "UpdateDeployment")]
pub mod UpdateDeployment;
#[cfg(feature = "UpdateDevice")]
pub mod UpdateDevice;
