[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AssociateKeypair = []
BatchAssociateKeypair = []
ClearPrivateKey = []
CreateKeypair = []
DeleteAllFailedTask = []
DeleteFailedTask = []
DeleteKeypair = []
DisassociateKeypair = []
ExportPrivateKey = []
ImportPrivateKey = []
ListFailedTask = []
ListKeypairDetail = []
ListKeypairTask = []
ListKeypairs = []
ListRunningTask = []
UpdateKeypairDescription = []
full = ["AssociateKeypair", "BatchAssociateKeypair", "ClearPrivateKey", "CreateKeypair", "DeleteAllFailedTask", "DeleteFailedTask", "DeleteKeypair", "DisassociateKeypair", "ExportPrivateKey", "ImportPrivateKey", "ListFailedTask", "ListKeypairDetail", "ListKeypairs", "ListKeypairTask", "ListRunningTask", "UpdateKeypairDescription"]

[lib]
name = "huawei_cloud_api_definitions_KPS"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-KPS"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "0.1.0"
