
		// This file is generated by hw-cloud-schema/build.rs
		// Definition: https://console.huaweicloud.com/apiexplorer/new/v4/apis/detail?product_short=CFW&name=AddServiceItems&region_id=cn-north-4
		#![allow(dead_code)]
		#![allow(unused_imports)]
		#![allow(non_snake_case)]
		use std::fmt::Debug;
		use serde::{Serialize, Deserialize};
		use typify::import_types;
		import_types!(schema="/Users/famer.me/Repository/huawei-cloud-api-definitions/schemas/CFW/src/AddServiceItems.json", struct_builder = true);
	