#[cfg(feature = "AddImageTag")]
pub mod AddImageTag;
#[cfg(feature = "BatchAddMembers")]
pub mod BatchAddMembers;
#[cfg(feature = "BatchAddOrDeleteTags")]
pub mod BatchAddOrDeleteTags;
#[cfg(feature = "BatchDeleteMembers")]
pub mod BatchDeleteMembers;
#[cfg(feature = "BatchUpdateMembers")]
pub mod BatchUpdateMembers;
#[cfg(feature = "CopyImageCrossRegion")]
pub mod CopyImageCrossRegion;
#[cfg(feature = "CopyImageInRegion")]
pub mod CopyImageInRegion;
#[cfg(feature = "CreateDataImage")]
pub mod CreateDataImage;
#[cfg(feature = "CreateImage")]
pub mod CreateImage;
#[cfg(feature = "CreateOrUpdateTags")]
pub mod CreateOrUpdateTags;
#[cfg(feature = "CreateWholeImage")]
pub mod CreateWholeImage;
#[cfg(feature = "DeleteImageTag")]
pub mod DeleteImageTag;
#[cfg(feature = "ExportImage")]
pub mod ExportImage;
#[cfg(feature = "GlanceAddImageMember")]
pub mod GlanceAddImageMember;
#[cfg(feature = "GlanceCreateImageMetadata")]
pub mod GlanceCreateImageMetadata;
#[cfg(feature = "GlanceCreateTag")]
pub mod GlanceCreateTag;
#[cfg(feature = "GlanceDeleteImage")]
pub mod GlanceDeleteImage;
#[cfg(feature = "GlanceDeleteImageMember")]
pub mod GlanceDeleteImageMember;
#[cfg(feature = "GlanceDeleteTag")]
pub mod GlanceDeleteTag;
#[cfg(feature = "GlanceListImageMembers")]
pub mod GlanceListImageMembers;
#[cfg(feature = "GlanceListImageMemberSchemas")]
pub mod GlanceListImageMemberSchemas;
#[cfg(feature = "GlanceListImages")]
pub mod GlanceListImages;
#[cfg(feature = "GlanceListImageSchemas")]
pub mod GlanceListImageSchemas;
#[cfg(feature = "GlanceShowImage")]
pub mod GlanceShowImage;
#[cfg(feature = "GlanceShowImageMember")]
pub mod GlanceShowImageMember;
#[cfg(feature = "GlanceShowImageMemberSchemas")]
pub mod GlanceShowImageMemberSchemas;
#[cfg(feature = "GlanceShowImageSchemas")]
pub mod GlanceShowImageSchemas;
#[cfg(feature = "GlanceUpdateImage")]
pub mod GlanceUpdateImage;
#[cfg(feature = "GlanceUpdateImageMember")]
pub mod GlanceUpdateImageMember;
#[cfg(feature = "ImportImageQuick")]
pub mod ImportImageQuick;
#[cfg(feature = "ListImageByTags")]
pub mod ListImageByTags;
#[cfg(feature = "ListImages")]
pub mod ListImages;
#[cfg(feature = "ListImagesTags")]
pub mod ListImagesTags;
#[cfg(feature = "ListImageTags")]
pub mod ListImageTags;
#[cfg(feature = "ListOsVersions")]
pub mod ListOsVersions;
#[cfg(feature = "ListTags")]
pub mod ListTags;
#[cfg(feature = "ListVersions")]
pub mod ListVersions;
#[cfg(feature = "RegisterImage")]
pub mod RegisterImage;
#[cfg(feature = "ShowImageQuota")]
pub mod ShowImageQuota;
#[cfg(feature = "ShowJob")]
pub mod ShowJob;
#[cfg(feature = "ShowJobProgress")]
pub mod ShowJobProgress;
#[cfg(feature = "ShowVersion")]
pub mod ShowVersion;
#[cfg(feature = "UpdateImage")]
pub mod UpdateImage;
