#[cfg(feature = "AddingBackendInstancesV2")]
pub mod AddingBackendInstancesV2;
#[cfg(feature = "AddSubsetsToGateway")]
pub mod AddSubsetsToGateway;
#[cfg(feature = "AddUserToApp")]
pub mod AddUserToApp;
#[cfg(feature = "AssociateAppsForAppQuota")]
pub mod AssociateAppsForAppQuota;
#[cfg(feature = "AssociateCertificateV2")]
pub mod AssociateCertificateV2;
#[cfg(feature = "AssociateDomainV2")]
pub mod AssociateDomainV2;
#[cfg(feature = "AssociateRequestThrottlingPolicyV2")]
pub mod AssociateRequestThrottlingPolicyV2;
#[cfg(feature = "AssociateSignatureKeyV2")]
pub mod AssociateSignatureKeyV2;
#[cfg(feature = "AttachApiToPlugin")]
pub mod AttachApiToPlugin;
#[cfg(feature = "AttachPluginToApi")]
pub mod AttachPluginToApi;
#[cfg(feature = "BatchAddDeviceToGroup")]
pub mod BatchAddDeviceToGroup;
#[cfg(feature = "BatchAssociateCertsV2")]
pub mod BatchAssociateCertsV2;
#[cfg(feature = "BatchAssociateDomainsV2")]
pub mod BatchAssociateDomainsV2;
#[cfg(feature = "BatchDeleteAclV2")]
pub mod BatchDeleteAclV2;
#[cfg(feature = "BatchDeleteApiAclBindingV2")]
pub mod BatchDeleteApiAclBindingV2;
#[cfg(feature = "BatchDeleteMqsInstanceTopic")]
pub mod BatchDeleteMqsInstanceTopic;
#[cfg(feature = "BatchDeleteRules")]
pub mod BatchDeleteRules;
#[cfg(feature = "BatchDeleteThrottlingPolicyV2")]
pub mod BatchDeleteThrottlingPolicyV2;
#[cfg(feature = "BatchDisableMembers")]
pub mod BatchDisableMembers;
#[cfg(feature = "BatchDisassociateCertsV2")]
pub mod BatchDisassociateCertsV2;
#[cfg(feature = "BatchDisassociateDomainsV2")]
pub mod BatchDisassociateDomainsV2;
#[cfg(feature = "BatchDisassociateThrottlingPolicyV2")]
pub mod BatchDisassociateThrottlingPolicyV2;
#[cfg(feature = "BatchEnableMembers")]
pub mod BatchEnableMembers;
#[cfg(feature = "BatchFreezeDevices")]
pub mod BatchFreezeDevices;
#[cfg(feature = "BatchPublishOrOfflineApiV2")]
pub mod BatchPublishOrOfflineApiV2;
#[cfg(feature = "BatchStartOrStopTasks")]
pub mod BatchStartOrStopTasks;
#[cfg(feature = "CancelingAuthorizationV2")]
pub mod CancelingAuthorizationV2;
#[cfg(feature = "ChangeApiVersionV2")]
pub mod ChangeApiVersionV2;
#[cfg(feature = "CheckApiGroupsV2")]
pub mod CheckApiGroupsV2;
#[cfg(feature = "CheckApisV2")]
pub mod CheckApisV2;
#[cfg(feature = "CheckAssetJobStatus")]
pub mod CheckAssetJobStatus;
#[cfg(feature = "CheckAuthUsersOfApp")]
pub mod CheckAuthUsersOfApp;
#[cfg(feature = "CheckCanAuthUsersOfApp")]
pub mod CheckCanAuthUsersOfApp;
#[cfg(feature = "CheckDictionary")]
pub mod CheckDictionary;
#[cfg(feature = "CheckLivedataApisV2")]
pub mod CheckLivedataApisV2;
#[cfg(feature = "CheckRomaAppDetails")]
pub mod CheckRomaAppDetails;
#[cfg(feature = "CheckRomaAppSecret")]
pub mod CheckRomaAppSecret;
#[cfg(feature = "CheckRomaInstanceListV2")]
pub mod CheckRomaInstanceListV2;
#[cfg(feature = "CheckVersion")]
pub mod CheckVersion;
#[cfg(feature = "CountTasks")]
pub mod CountTasks;
#[cfg(feature = "CreateAclStrategyV2")]
pub mod CreateAclStrategyV2;
#[cfg(feature = "CreateApiAclBindingV2")]
pub mod CreateApiAclBindingV2;
#[cfg(feature = "CreateApiGroupV2")]
pub mod CreateApiGroupV2;
#[cfg(feature = "CreateApiV2")]
pub mod CreateApiV2;
#[cfg(feature = "CreateAppCodeAutoV2")]
pub mod CreateAppCodeAutoV2;
#[cfg(feature = "CreateAppCodeV2")]
pub mod CreateAppCodeV2;
#[cfg(feature = "CreateAppConfigV2")]
pub mod CreateAppConfigV2;
#[cfg(feature = "CreateAppQuota")]
pub mod CreateAppQuota;
#[cfg(feature = "CreateAuthorizingAppsV2")]
pub mod CreateAuthorizingAppsV2;
#[cfg(feature = "CreateCertificateV2")]
pub mod CreateCertificateV2;
#[cfg(feature = "CreateCommand")]
pub mod CreateCommand;
#[cfg(feature = "CreateCommonTask")]
pub mod CreateCommonTask;
#[cfg(feature = "CreateCustomAuthorizerV2")]
pub mod CreateCustomAuthorizerV2;
#[cfg(feature = "CreateDatasourceInfo")]
pub mod CreateDatasourceInfo;
#[cfg(feature = "CreateDestination")]
pub mod CreateDestination;
#[cfg(feature = "CreateDevice")]
pub mod CreateDevice;
#[cfg(feature = "CreateDeviceGroup")]
pub mod CreateDeviceGroup;
#[cfg(feature = "CreateDictionary")]
pub mod CreateDictionary;
#[cfg(feature = "CreateDispatches")]
pub mod CreateDispatches;
#[cfg(feature = "CreateEnvironmentV2")]
pub mod CreateEnvironmentV2;
#[cfg(feature = "CreateEnvironmentVariableV2")]
pub mod CreateEnvironmentVariableV2;
#[cfg(feature = "CreateFeatureV2")]
pub mod CreateFeatureV2;
#[cfg(feature = "CreateLiveDataApiScriptV2")]
pub mod CreateLiveDataApiScriptV2;
#[cfg(feature = "CreateLiveDataApiV2")]
pub mod CreateLiveDataApiV2;
#[cfg(feature = "CreateMemberGroup")]
pub mod CreateMemberGroup;
#[cfg(feature = "CreateMqsInstanceTopic")]
pub mod CreateMqsInstanceTopic;
#[cfg(feature = "CreateMultiTaskMappings")]
pub mod CreateMultiTaskMappings;
#[cfg(feature = "CreateMultiTasks")]
pub mod CreateMultiTasks;
#[cfg(feature = "CreateNotification")]
pub mod CreateNotification;
#[cfg(feature = "CreateOrDeletePublishRecordForApiV2")]
pub mod CreateOrDeletePublishRecordForApiV2;
#[cfg(feature = "CreatePlugin")]
pub mod CreatePlugin;
#[cfg(feature = "CreateProduct")]
pub mod CreateProduct;
#[cfg(feature = "CreateProductTemplate")]
pub mod CreateProductTemplate;
#[cfg(feature = "CreateProductTopic")]
pub mod CreateProductTopic;
#[cfg(feature = "CreateProjectVpcChannel")]
pub mod CreateProjectVpcChannel;
#[cfg(feature = "CreateProjectVpcChannelSyncs")]
pub mod CreateProjectVpcChannelSyncs;
#[cfg(feature = "CreateProperty")]
pub mod CreateProperty;
#[cfg(feature = "CreateRequestProperty")]
pub mod CreateRequestProperty;
#[cfg(feature = "CreateRequestThrottlingPolicyV2")]
pub mod CreateRequestThrottlingPolicyV2;
#[cfg(feature = "CreateResponseProperty")]
pub mod CreateResponseProperty;
#[cfg(feature = "CreateRomaApp")]
pub mod CreateRomaApp;
#[cfg(feature = "CreateRule")]
pub mod CreateRule;
#[cfg(feature = "CreateService")]
pub mod CreateService;
#[cfg(feature = "CreateSignatureKeyV2")]
pub mod CreateSignatureKeyV2;
#[cfg(feature = "CreateSource")]
pub mod CreateSource;
#[cfg(feature = "CreateSpecialThrottlingConfigurationV2")]
pub mod CreateSpecialThrottlingConfigurationV2;
#[cfg(feature = "CreateVpcChannelV2")]
pub mod CreateVpcChannelV2;
#[cfg(feature = "DebugApiV2")]
pub mod DebugApiV2;
#[cfg(feature = "DebugLiveDataApiV2")]
pub mod DebugLiveDataApiV2;
#[cfg(feature = "DebugRule")]
pub mod DebugRule;
#[cfg(feature = "DeleteAclV2")]
pub mod DeleteAclV2;
#[cfg(feature = "DeleteApiAclBindingV2")]
pub mod DeleteApiAclBindingV2;
#[cfg(feature = "DeleteApiByVersionIdV2")]
pub mod DeleteApiByVersionIdV2;
#[cfg(feature = "DeleteApiGroupV2")]
pub mod DeleteApiGroupV2;
#[cfg(feature = "DeleteApiV2")]
pub mod DeleteApiV2;
#[cfg(feature = "DeleteAppAcl")]
pub mod DeleteAppAcl;
#[cfg(feature = "DeleteAppCodeV2")]
pub mod DeleteAppCodeV2;
#[cfg(feature = "DeleteAppConfigV2")]
pub mod DeleteAppConfigV2;
#[cfg(feature = "DeleteAppQuota")]
pub mod DeleteAppQuota;
#[cfg(feature = "DeleteAsset")]
pub mod DeleteAsset;
