#[cfg(feature = "CreateApp")]
pub mod CreateApp;
#[cfg(feature = "CreateDeploymentGroup")]
pub mod CreateDeploymentGroup;
#[cfg(feature = "CreateDeploymentHost")]
pub mod CreateDeploymentHost;
#[cfg(feature = "CreateDeployTaskByTemplate")]
pub mod CreateDeployTaskByTemplate;
#[cfg(feature = "CreateEnvironment")]
pub mod CreateEnvironment;
#[cfg(feature = "CreateHost")]
pub mod CreateHost;
#[cfg(feature = "CreateHostCluster")]
pub mod CreateHostCluster;
#[cfg(feature = "DeleteApplication")]
pub mod DeleteApplication;
#[cfg(feature = "DeleteDeploymentGroup")]
pub mod DeleteDeploymentGroup;
#[cfg(feature = "DeleteDeploymentHost")]
pub mod DeleteDeploymentHost;
#[cfg(feature = "DeleteDeployTask")]
pub mod DeleteDeployTask;
#[cfg(feature = "DeleteEnvironment")]
pub mod DeleteEnvironment;
#[cfg(feature = "DeleteHostFromEnvironment")]
pub mod DeleteHostFromEnvironment;
#[cfg(feature = "ImportHostToEnvironment")]
pub mod ImportHostToEnvironment;
#[cfg(feature = "ListAllApp")]
pub mod ListAllApp;
#[cfg(feature = "ListDeployTaskHistoryByDate")]
pub mod ListDeployTaskHistoryByDate;
#[cfg(feature = "ListDeployTasks")]
pub mod ListDeployTasks;
#[cfg(feature = "ListEnvironments")]
pub mod ListEnvironments;
#[cfg(feature = "ListHostClusters")]
pub mod ListHostClusters;
#[cfg(feature = "ListHostGroups")]
pub mod ListHostGroups;
#[cfg(feature = "ListHosts")]
pub mod ListHosts;
#[cfg(feature = "ListNewHosts")]
pub mod ListNewHosts;
#[cfg(feature = "ListTaskSuccessRate")]
pub mod ListTaskSuccessRate;
#[cfg(feature = "ShowAppDetailById")]
pub mod ShowAppDetailById;
#[cfg(feature = "ShowDeploymentGroupDetail")]
pub mod ShowDeploymentGroupDetail;
#[cfg(feature = "ShowDeploymentHostDetail")]
pub mod ShowDeploymentHostDetail;
#[cfg(feature = "ShowDeployTaskDetail")]
pub mod ShowDeployTaskDetail;
#[cfg(feature = "ShowEnvironmentDetail")]
pub mod ShowEnvironmentDetail;
#[cfg(feature = "ShowExecutionParams")]
pub mod ShowExecutionParams;
#[cfg(feature = "ShowHostClusterDetail")]
pub mod ShowHostClusterDetail;
#[cfg(feature = "ShowHostDetail")]
pub mod ShowHostDetail;
#[cfg(feature = "ShowProjectSuccessRate")]
pub mod ShowProjectSuccessRate;
#[cfg(feature = "StartDeployTask")]
pub mod StartDeployTask;
#[cfg(feature = "UpdateDeploymentGroup")]
pub mod UpdateDeploymentGroup;
#[cfg(feature = "UpdateDeploymentHost")]
pub mod UpdateDeploymentHost;
