#[cfg(feature = "BatchDeleteApp")]
pub mod BatchDeleteApp;
#[cfg(feature = "BatchDeleteHosts")]
pub mod BatchDeleteHosts;
#[cfg(feature = "BatchUpdateApplicationPermissions")]
pub mod BatchUpdateApplicationPermissions;
#[cfg(feature = "BatchUpdatePermissionLevel")]
pub mod BatchUpdatePermissionLevel;
#[cfg(feature = "CheckCanCreate")]
pub mod CheckCanCreate;
#[cfg(feature = "CheckDeployStatus")]
pub mod CheckDeployStatus;
#[cfg(feature = "CheckIsDuplicateAppName")]
pub mod CheckIsDuplicateAppName;
#[cfg(feature = "CheckWhetherHostGroupCanBeCreated")]
pub mod CheckWhetherHostGroupCanBeCreated;
#[cfg(feature = "CopyApplication")]
pub mod CopyApplication;
#[cfg(feature = "CopyHostsToTarget")]
pub mod CopyHostsToTarget;
#[cfg(feature = "CreateApp")]
pub mod CreateApp;
#[cfg(feature = "CreateAppGroups")]
pub mod CreateAppGroups;
#[cfg(feature = "CreateDeploymentGroup")]
pub mod CreateDeploymentGroup;
#[cfg(feature = "CreateDeploymentHost")]
pub mod CreateDeploymentHost;
#[cfg(feature = "CreateDeployTaskByTemplate")]
pub mod CreateDeployTaskByTemplate;
#[cfg(feature = "CreateEnvironment")]
pub mod CreateEnvironment;
#[cfg(feature = "CreateHost")]
pub mod CreateHost;
#[cfg(feature = "CreateHostCluster")]
pub mod CreateHostCluster;
#[cfg(feature = "DeleteAppGroups")]
pub mod DeleteAppGroups;
#[cfg(feature = "DeleteApplication")]
pub mod DeleteApplication;
#[cfg(feature = "DeleteDeploymentGroup")]
pub mod DeleteDeploymentGroup;
#[cfg(feature = "DeleteDeploymentHost")]
pub mod DeleteDeploymentHost;
#[cfg(feature = "DeleteDeployTask")]
pub mod DeleteDeployTask;
#[cfg(feature = "DeleteEnvironment")]
pub mod DeleteEnvironment;
#[cfg(feature = "DeleteHost")]
pub mod DeleteHost;
#[cfg(feature = "DeleteHostCluster")]
pub mod DeleteHostCluster;
#[cfg(feature = "DeleteHostFromEnvironment")]
pub mod DeleteHostFromEnvironment;
#[cfg(feature = "ImportHostToEnvironment")]
pub mod ImportHostToEnvironment;
#[cfg(feature = "ListAllApp")]
pub mod ListAllApp;
#[cfg(feature = "ListAppGroups")]
pub mod ListAppGroups;
#[cfg(feature = "ListApplicationPermissions")]
pub mod ListApplicationPermissions;
#[cfg(feature = "ListAssociateEnvironmentsInfos")]
pub mod ListAssociateEnvironmentsInfos;
#[cfg(feature = "ListDeployTaskHistoryByDate")]
pub mod ListDeployTaskHistoryByDate;
#[cfg(feature = "ListDeployTasks")]
pub mod ListDeployTasks;
#[cfg(feature = "ListEnvironmentHosts")]
pub mod ListEnvironmentHosts;
#[cfg(feature = "ListEnvironmentPermissions")]
pub mod ListEnvironmentPermissions;
#[cfg(feature = "ListEnvironments")]
pub mod ListEnvironments;
#[cfg(feature = "ListHostClusters")]
pub mod ListHostClusters;
#[cfg(feature = "ListHostGroupBaseInfos")]
pub mod ListHostGroupBaseInfos;
#[cfg(feature = "ListHostGroupPermissions")]
pub mod ListHostGroupPermissions;
#[cfg(feature = "ListHostGroups")]
pub mod ListHostGroups;
#[cfg(feature = "ListHosts")]
pub mod ListHosts;
#[cfg(feature = "ListNewHosts")]
pub mod ListNewHosts;
#[cfg(feature = "ListTaskSuccessRate")]
pub mod ListTaskSuccessRate;
#[cfg(feature = "MoveAppGroups")]
pub mod MoveAppGroups;
#[cfg(feature = "MoveAppToGroup")]
pub mod MoveAppToGroup;
#[cfg(feature = "ShowAppDetailById")]
pub mod ShowAppDetailById;
#[cfg(feature = "ShowApplicationMsgList")]
pub mod ShowApplicationMsgList;
#[cfg(feature = "ShowDeploymentGroupDetail")]
pub mod ShowDeploymentGroupDetail;
#[cfg(feature = "ShowDeploymentHostDetail")]
pub mod ShowDeploymentHostDetail;
#[cfg(feature = "ShowDeployTaskDetail")]
pub mod ShowDeployTaskDetail;
#[cfg(feature = "ShowEnvironmentDetail")]
pub mod ShowEnvironmentDetail;
#[cfg(feature = "ShowExecutionParams")]
pub mod ShowExecutionParams;
#[cfg(feature = "ShowHostClusterDetail")]
pub mod ShowHostClusterDetail;
#[cfg(feature = "ShowHostDetail")]
pub mod ShowHostDetail;
#[cfg(feature = "ShowProjectSuccessRate")]
pub mod ShowProjectSuccessRate;
#[cfg(feature = "StartDeployTask")]
pub mod StartDeployTask;
#[cfg(feature = "StopDeployTask")]
pub mod StopDeployTask;
#[cfg(feature = "UpdateAppDisableStatus")]
pub mod UpdateAppDisableStatus;
#[cfg(feature = "UpdateAppGroups")]
pub mod UpdateAppGroups;
#[cfg(feature = "UpdateAppInfo")]
pub mod UpdateAppInfo;
#[cfg(feature = "UpdateApplicationMsgV2")]
pub mod UpdateApplicationMsgV2;
#[cfg(feature = "UpdateDeploymentGroup")]
pub mod UpdateDeploymentGroup;
#[cfg(feature = "UpdateDeploymentHost")]
pub mod UpdateDeploymentHost;
#[cfg(feature = "UpdateEnvironment")]
pub mod UpdateEnvironment;
#[cfg(feature = "UpdateEnvironmentPermission")]
pub mod UpdateEnvironmentPermission;
#[cfg(feature = "UpdateHostCluster")]
pub mod UpdateHostCluster;
#[cfg(feature = "UpdateHostGroupPermissions")]
pub mod UpdateHostGroupPermissions;
#[cfg(feature = "UpdateHostInfo")]
pub mod UpdateHostInfo;
