[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
CheckHosts = []
CheckNeedVerify = []
CheckVerifyCodes = []
ConfirmAuthorizations = []
CreateCaseExtendsParam = []
CreateCaseLabels = []
CreateCases = []
CreateDiagnoseFeedback = []
CreateDiagnoseJob = []
CreateFeedback = []
CreateLabels = []
CreateMessages = []
CreatePrivileges = []
CreateRelations = []
CreateScores = []
DeleteAccessories = []
DeleteCaseLabels = []
DeleteLabels = []
DeleteRelation = []
DownloadAccessories = []
DownloadCases = []
DownloadImages = []
ListAccessoryAccessUrls = []
ListAgencies = []
ListAreaCodes = []
ListAuthorizations = []
ListCaseCategories = []
ListCaseCcEmails = []
ListCaseCounts = []
ListCaseLabels = []
ListCaseLimits = []
ListCaseOperateLogs = []
ListCaseQuotas = []
ListCaseTemplates = []
ListCases = []
ListCustomersRegions = []
ListDiagnoseItems = []
ListDiagnoseJob = []
ListDiagnoseRecords = []
ListDiagnoseResources = []
ListExtendsParams = []
ListHasVerifiedContacts = []
ListHistoryOperateLogs = []
ListHistorySessions = []
ListLabels = []
ListMessages = []
ListMoreInstantMessages = []
ListNewInstantMessages = []
ListOrderIncident = []
ListPrivileges = []
ListProblemTypes = []
ListProductCategories = []
ListRegions = []
ListRelation = []
ListSatisfactionDimensions = []
ListSeverities = []
ListSubCustomers = []
ListTransportHistories = []
ListUnreadNewInstantMessages = []
RevokeMessage = []
SendVerifyCodes = []
ShowAccessoryLimits = []
ShowAuthorizationDetail = []
ShowCaseDetail = []
ShowCaseExtendsParam = []
ShowCaseStatus = []
ShowConfiguration = []
ShowCustomerPrivilegePolicy = []
ShowDownloadAccessoryUrl = []
ShowLatestPublishedAgreement = []
ShowLoginType = []
ShowPartnersCasesPrivilege = []
ShowPartnersServiceInfo = []
ShowSignedLatestPublishedAgreement = []
SignPublishedAgreement = []
UpdateAuthorizations = []
UpdateCaseContactInfo = []
UpdateCases = []
UpdateLabels = []
UpdateNewInstantMessagesRead = []
UploadAccessory = []
UploadJsonAccessories = []
full = ["CheckHosts", "CheckNeedVerify", "CheckVerifyCodes", "ConfirmAuthorizations", "CreateCaseExtendsParam", "CreateCaseLabels", "CreateCases", "CreateDiagnoseFeedback", "CreateDiagnoseJob", "CreateFeedback", "CreateLabels", "CreateMessages", "CreatePrivileges", "CreateRelations", "CreateScores", "DeleteAccessories", "DeleteCaseLabels", "DeleteLabels", "DeleteRelation", "DownloadAccessories", "DownloadCases", "DownloadImages", "ListAccessoryAccessUrls", "ListAgencies", "ListAreaCodes", "ListAuthorizations", "ListCaseCategories", "ListCaseCcEmails", "ListCaseCounts", "ListCaseLabels", "ListCaseLimits", "ListCaseOperateLogs", "ListCaseQuotas", "ListCases", "ListCaseTemplates", "ListCustomersRegions", "ListDiagnoseItems", "ListDiagnoseJob", "ListDiagnoseRecords", "ListDiagnoseResources", "ListExtendsParams", "ListHasVerifiedContacts", "ListHistoryOperateLogs", "ListHistorySessions", "ListLabels", "ListMessages", "ListMoreInstantMessages", "ListNewInstantMessages", "ListOrderIncident", "ListPrivileges", "ListProblemTypes", "ListProductCategories", "ListRegions", "ListRelation", "ListSatisfactionDimensions", "ListSeverities", "ListSubCustomers", "ListTransportHistories", "ListUnreadNewInstantMessages", "RevokeMessage", "SendVerifyCodes", "ShowAccessoryLimits", "ShowAuthorizationDetail", "ShowCaseDetail", "ShowCaseExtendsParam", "ShowCaseStatus", "ShowConfiguration", "ShowCustomerPrivilegePolicy", "ShowDownloadAccessoryUrl", "ShowLatestPublishedAgreement", "ShowLoginType", "ShowPartnersCasesPrivilege", "ShowPartnersServiceInfo", "ShowSignedLatestPublishedAgreement", "SignPublishedAgreement", "UpdateAuthorizations", "UpdateCaseContactInfo", "UpdateCases", "UpdateLabels", "UpdateNewInstantMessagesRead", "UploadAccessory", "UploadJsonAccessories"]

[lib]
name = "huawei_cloud_api_definitions_OSM"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-OSM"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
