#[cfg(feature = "CreateCollection")]
pub mod CreateCollection;
#[cfg(feature = "CreateIndex")]
pub mod CreateIndex;
#[cfg(feature = "CreateStore")]
pub mod CreateStore;
#[cfg(feature = "DeleteCollection")]
pub mod DeleteCollection;
#[cfg(feature = "DeleteEntities")]
pub mod DeleteEntities;
#[cfg(feature = "DeleteIndex")]
pub mod DeleteIndex;
#[cfg(feature = "DeleteStore")]
pub mod DeleteStore;
#[cfg(feature = "DescribeCollection")]
pub mod DescribeCollection;
#[cfg(feature = "DescribeIndex")]
pub mod DescribeIndex;
#[cfg(feature = "DescribeJob")]
pub mod DescribeJob;
#[cfg(feature = "DescribeStore")]
pub mod DescribeStore;
#[cfg(feature = "GetProgress")]
pub mod GetProgress;
#[cfg(feature = "HybridSearch")]
pub mod HybridSearch;
#[cfg(feature = "InsertEntities")]
pub mod InsertEntities;
#[cfg(feature = "ListCollections")]
pub mod ListCollections;
#[cfg(feature = "ListJobs")]
pub mod ListJobs;
#[cfg(feature = "ListStores")]
pub mod ListStores;
#[cfg(feature = "LoadCollection")]
pub mod LoadCollection;
#[cfg(feature = "QueryEntities")]
pub mod QueryEntities;
#[cfg(feature = "ReleaseCollection")]
pub mod ReleaseCollection;
#[cfg(feature = "SearchEntities")]
pub mod SearchEntities;
#[cfg(feature = "UpsertEntities")]
pub mod UpsertEntities;
