#[cfg(feature = "ChangeApplication")]
pub mod ChangeApplication;
#[cfg(feature = "ChangeApplicationConfiguration")]
pub mod ChangeApplicationConfiguration;
#[cfg(feature = "ChangeComponent")]
pub mod ChangeComponent;
#[cfg(feature = "ChangeEnvironment")]
pub mod ChangeEnvironment;
#[cfg(feature = "ChangeInstance")]
pub mod ChangeInstance;
#[cfg(feature = "ChangeResourceInEnvironment")]
pub mod ChangeResourceInEnvironment;
#[cfg(feature = "CreateApplication")]
pub mod CreateApplication;
#[cfg(feature = "CreateCamInstance")]
pub mod CreateCamInstance;
#[cfg(feature = "CreateComponent")]
pub mod CreateComponent;
#[cfg(feature = "CreateEnvironment")]
pub mod CreateEnvironment;
#[cfg(feature = "CreateFile")]
pub mod CreateFile;
#[cfg(feature = "CreateHook")]
pub mod CreateHook;
#[cfg(feature = "CreateInstance")]
pub mod CreateInstance;
#[cfg(feature = "CreateOAuth")]
pub mod CreateOAuth;
#[cfg(feature = "CreatePasswordAuth")]
pub mod CreatePasswordAuth;
#[cfg(feature = "CreatePersonalAuth")]
pub mod CreatePersonalAuth;
#[cfg(feature = "CreateProject")]
pub mod CreateProject;
#[cfg(feature = "CreateTag")]
pub mod CreateTag;
#[cfg(feature = "CreateTemplate")]
pub mod CreateTemplate;
#[cfg(feature = "DeleteApplication")]
pub mod DeleteApplication;
#[cfg(feature = "DeleteApplicationConfiguration")]
pub mod DeleteApplicationConfiguration;
#[cfg(feature = "DeleteAuthorize")]
pub mod DeleteAuthorize;
#[cfg(feature = "DeleteComponent")]
pub mod DeleteComponent;
#[cfg(feature = "DeleteEnvironment")]
pub mod DeleteEnvironment;
#[cfg(feature = "DeleteFile")]
pub mod DeleteFile;
#[cfg(feature = "DeleteHook")]
pub mod DeleteHook;
#[cfg(feature = "DeleteInstance")]
pub mod DeleteInstance;
#[cfg(feature = "DeleteInstanceById")]
pub mod DeleteInstanceById;
#[cfg(feature = "DeleteTag")]
pub mod DeleteTag;
#[cfg(feature = "DeleteTemplate")]
pub mod DeleteTemplate;
#[cfg(feature = "DeployInstance")]
pub mod DeployInstance;
#[cfg(feature = "ListApplications")]
pub mod ListApplications;
#[cfg(feature = "ListAuthorizations")]
pub mod ListAuthorizations;
#[cfg(feature = "ListBranches")]
pub mod ListBranches;
#[cfg(feature = "ListCommits")]
pub mod ListCommits;
#[cfg(feature = "ListComponents")]
pub mod ListComponents;
#[cfg(feature = "ListEnvironments")]
pub mod ListEnvironments;
#[cfg(feature = "ListFlavors")]
pub mod ListFlavors;
#[cfg(feature = "ListHooks")]
pub mod ListHooks;
#[cfg(feature = "ListInstances")]
pub mod ListInstances;
#[cfg(feature = "ListInstanceSnapshots")]
pub mod ListInstanceSnapshots;
#[cfg(feature = "ListNamespaces")]
pub mod ListNamespaces;
#[cfg(feature = "ListProjects")]
pub mod ListProjects;
#[cfg(feature = "ListRuntimes")]
pub mod ListRuntimes;
#[cfg(feature = "ListTags")]
pub mod ListTags;
#[cfg(feature = "ListTemplates")]
pub mod ListTemplates;
#[cfg(feature = "ListTrees")]
pub mod ListTrees;
#[cfg(feature = "ModifyApplication")]
pub mod ModifyApplication;
#[cfg(feature = "ModifyApplicationConfiguration")]
pub mod ModifyApplicationConfiguration;
#[cfg(feature = "ModifyComponent")]
pub mod ModifyComponent;
#[cfg(feature = "ModifyEnvironment")]
pub mod ModifyEnvironment;
#[cfg(feature = "ModifyResourceInEnvironment")]
pub mod ModifyResourceInEnvironment;
#[cfg(feature = "ShowApplicationConfiguration")]
pub mod ShowApplicationConfiguration;
#[cfg(feature = "ShowApplicationDetail")]
pub mod ShowApplicationDetail;
#[cfg(feature = "ShowApplicationInfo")]
pub mod ShowApplicationInfo;
#[cfg(feature = "ShowApplications")]
pub mod ShowApplications;
#[cfg(feature = "ShowComponentDetail")]
pub mod ShowComponentDetail;
#[cfg(feature = "ShowComponentInfo")]
pub mod ShowComponentInfo;
#[cfg(feature = "ShowComponentRecords")]
pub mod ShowComponentRecords;
#[cfg(feature = "ShowComponents")]
pub mod ShowComponents;
#[cfg(feature = "ShowComponentsInApplication")]
pub mod ShowComponentsInApplication;
#[cfg(feature = "ShowContent")]
pub mod ShowContent;
#[cfg(feature = "ShowEnvironmentDetail")]
pub mod ShowEnvironmentDetail;
#[cfg(feature = "ShowEnvironmentInfo")]
pub mod ShowEnvironmentInfo;
#[cfg(feature = "ShowEnvironmentResources")]
pub mod ShowEnvironmentResources;
#[cfg(feature = "ShowEnvironments")]
pub mod ShowEnvironments;
#[cfg(feature = "ShowInstanceDetail")]
pub mod ShowInstanceDetail;
#[cfg(feature = "ShowJobDetail")]
pub mod ShowJobDetail;
#[cfg(feature = "ShowJobInfo")]
pub mod ShowJobInfo;
#[cfg(feature = "ShowProjectDetail")]
pub mod ShowProjectDetail;
#[cfg(feature = "ShowRedirectUrl")]
pub mod ShowRedirectUrl;
#[cfg(feature = "ShowRuntimeStacks")]
pub mod ShowRuntimeStacks;
#[cfg(feature = "UpdateComponentAction")]
pub mod UpdateComponentAction;
#[cfg(feature = "UpdateFile")]
pub mod UpdateFile;
#[cfg(feature = "UpdateInstanceAction")]
pub mod UpdateInstanceAction;
#[cfg(feature = "UpdateTemplate")]
pub mod UpdateTemplate;
