[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
CheckNetAcl = []
CollectLog = []
CreateMigproject = []
CreatePrivacyAgreements = []
CreateTask = []
CreateTemplate = []
DeleteMigproject = []
DeleteServer = []
DeleteServers = []
DeleteTask = []
DeleteTasks = []
DeleteTemplate = []
DeleteTemplates = []
ListApiVersion = []
ListErrorServers = []
ListMigprojects = []
ListServers = []
ListTasks = []
ListTemplates = []
RegisterServer = []
ShowApiVersion = []
ShowCertKey = []
ShowCommand = []
ShowConfig = []
ShowConfigSetting = []
ShowConsistencyResult = []
ShowMigproject = []
ShowOverview = []
ShowPassphrase = []
ShowPrivacyAgreements = []
ShowServer = []
ShowSha256 = []
ShowTargetPassword = []
ShowTask = []
ShowTemplate = []
ShowsSpeedLimits = []
UnlockTargetEcs = []
UpdateCommandResult = []
UpdateConsistencyResult = []
UpdateCopyState = []
UpdateDefaultMigproject = []
UpdateDiskInfo = []
UpdateMigproject = []
UpdateNetworkCheckInfo = []
UpdateServerName = []
UpdateSpeed = []
UpdateTask = []
UpdateTaskSpeed = []
UpdateTaskStatus = []
UpdateTemplate = []
UploadSpecialConfigurationSetting = []
full = ["CheckNetAcl", "CollectLog", "CreateMigproject", "CreatePrivacyAgreements", "CreateTask", "CreateTemplate", "DeleteMigproject", "DeleteServer", "DeleteServers", "DeleteTask", "DeleteTasks", "DeleteTemplate", "DeleteTemplates", "ListApiVersion", "ListErrorServers", "ListMigprojects", "ListServers", "ListTasks", "ListTemplates", "RegisterServer", "ShowApiVersion", "ShowCertKey", "ShowCommand", "ShowConfig", "ShowConfigSetting", "ShowConsistencyResult", "ShowMigproject", "ShowOverview", "ShowPassphrase", "ShowPrivacyAgreements", "ShowServer", "ShowSha256", "ShowsSpeedLimits", "ShowTargetPassword", "ShowTask", "ShowTemplate", "UnlockTargetEcs", "UpdateCommandResult", "UpdateConsistencyResult", "UpdateCopyState", "UpdateDefaultMigproject", "UpdateDiskInfo", "UpdateMigproject", "UpdateNetworkCheckInfo", "UpdateServerName", "UpdateSpeed", "UpdateTask", "UpdateTaskSpeed", "UpdateTaskStatus", "UpdateTemplate", "UploadSpecialConfigurationSetting"]

[lib]
name = "huawei_cloud_api_definitions_SMS"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-SMS"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "0.1.0"
