
		// This file is generated by hw-cloud-schema/build.rs
		// Definition: https://console.huaweicloud.com/apiexplorer/new/v4/apis/detail?product_short=CC&name=CreateCentralNetworkGdgwAttachment&region_id=cn-north-4
		#![allow(dead_code)]
		#![allow(unused_imports)]
		#![allow(non_snake_case)]
		use std::fmt::Debug;
		use serde::{Serialize, Deserialize};
		use typify::import_types;
		import_types!(schema="src/CreateCentralNetworkGdgwAttachment.json", struct_builder = true);
	