#[cfg(feature = "ApplyCentralNetworkPolicy")]
pub mod ApplyCentralNetworkPolicy;
#[cfg(feature = "AssociateBandwidthPackage")]
pub mod AssociateBandwidthPackage;
#[cfg(feature = "AssociateGlobalConnectionBandwidthInstance")]
pub mod AssociateGlobalConnectionBandwidthInstance;
#[cfg(feature = "AssociateSiteNetworkBandwidth")]
pub mod AssociateSiteNetworkBandwidth;
#[cfg(feature = "BatchCreateDeleteTags")]
pub mod BatchCreateDeleteTags;
#[cfg(feature = "BatchCreateGcbResourceTags")]
pub mod BatchCreateGcbResourceTags;
#[cfg(feature = "BatchDeleteGcbResourceTags")]
pub mod BatchDeleteGcbResourceTags;
#[cfg(feature = "CountGcbResourceByTag")]
pub mod CountGcbResourceByTag;
#[cfg(feature = "CreateAuthorisation")]
pub mod CreateAuthorisation;
#[cfg(feature = "CreateBandwidthPackage")]
pub mod CreateBandwidthPackage;
#[cfg(feature = "CreateCentralNetwork")]
pub mod CreateCentralNetwork;
#[cfg(feature = "CreateCentralNetworkErRouteTableAttachment")]
pub mod CreateCentralNetworkErRouteTableAttachment;
#[cfg(feature = "CreateCentralNetworkGdgwAttachment")]
pub mod CreateCentralNetworkGdgwAttachment;
#[cfg(feature = "CreateCentralNetworkPolicy")]
pub mod CreateCentralNetworkPolicy;
#[cfg(feature = "CreateCloudConnection")]
pub mod CreateCloudConnection;
#[cfg(feature = "CreateGcbResourceTag")]
pub mod CreateGcbResourceTag;
#[cfg(feature = "CreateGlobalConnectionBandwidth")]
pub mod CreateGlobalConnectionBandwidth;
#[cfg(feature = "CreateInterRegionBandwidth")]
pub mod CreateInterRegionBandwidth;
#[cfg(feature = "CreateNetworkInstance")]
pub mod CreateNetworkInstance;
#[cfg(feature = "CreateP2PSiteNetwork")]
pub mod CreateP2PSiteNetwork;
#[cfg(feature = "CreateTag")]
pub mod CreateTag;
#[cfg(feature = "DeleteAuthorisation")]
pub mod DeleteAuthorisation;
#[cfg(feature = "DeleteBandwidthPackage")]
pub mod DeleteBandwidthPackage;
#[cfg(feature = "DeleteCentralNetwork")]
pub mod DeleteCentralNetwork;
#[cfg(feature = "DeleteCentralNetworkAttachment")]
pub mod DeleteCentralNetworkAttachment;
#[cfg(feature = "DeleteCentralNetworkPolicy")]
pub mod DeleteCentralNetworkPolicy;
#[cfg(feature = "DeleteCloudConnection")]
pub mod DeleteCloudConnection;
#[cfg(feature = "DeleteGcbResourceTag")]
pub mod DeleteGcbResourceTag;
#[cfg(feature = "DeleteGlobalConnectionBandwidth")]
pub mod DeleteGlobalConnectionBandwidth;
#[cfg(feature = "DeleteInterRegionBandwidth")]
pub mod DeleteInterRegionBandwidth;
#[cfg(feature = "DeleteNetworkInstance")]
pub mod DeleteNetworkInstance;
#[cfg(feature = "DeleteSiteNetwork")]
pub mod DeleteSiteNetwork;
#[cfg(feature = "DeleteTag")]
pub mod DeleteTag;
#[cfg(feature = "DisassociateBandwidthPackage")]
pub mod DisassociateBandwidthPackage;
#[cfg(feature = "DisassociateGlobalConnectionBandwidthInstance")]
pub mod DisassociateGlobalConnectionBandwidthInstance;
#[cfg(feature = "DisassociateSiteNetworkBandwidth")]
pub mod DisassociateSiteNetworkBandwidth;
#[cfg(feature = "ListAuthorisations")]
pub mod ListAuthorisations;
#[cfg(feature = "ListBandwidthPackageLevels")]
pub mod ListBandwidthPackageLevels;
#[cfg(feature = "ListBandwidthPackageLines")]
pub mod ListBandwidthPackageLines;
#[cfg(feature = "ListBandwidthPackages")]
pub mod ListBandwidthPackages;
#[cfg(feature = "ListBandwidthPackagesByTags")]
pub mod ListBandwidthPackagesByTags;
#[cfg(feature = "ListBandwidthPackageSites")]
pub mod ListBandwidthPackageSites;
#[cfg(feature = "ListBandwidthPackageTags")]
pub mod ListBandwidthPackageTags;
#[cfg(feature = "ListCentralNetworkAttachments")]
pub mod ListCentralNetworkAttachments;
#[cfg(feature = "ListCentralNetworkCapabilities")]
pub mod ListCentralNetworkCapabilities;
#[cfg(feature = "ListCentralNetworkConnections")]
pub mod ListCentralNetworkConnections;
#[cfg(feature = "ListCentralNetworkErRouteTableAttachments")]
pub mod ListCentralNetworkErRouteTableAttachments;
#[cfg(feature = "ListCentralNetworkGdgwAttachments")]
pub mod ListCentralNetworkGdgwAttachments;
#[cfg(feature = "ListCentralNetworkPolicies")]
pub mod ListCentralNetworkPolicies;
#[cfg(feature = "ListCentralNetworkPolicyChangeSet")]
pub mod ListCentralNetworkPolicyChangeSet;
#[cfg(feature = "ListCentralNetworkQuotas")]
pub mod ListCentralNetworkQuotas;
#[cfg(feature = "ListCentralNetworks")]
pub mod ListCentralNetworks;
#[cfg(feature = "ListCentralNetworksByTags")]
pub mod ListCentralNetworksByTags;
#[cfg(feature = "ListCentralNetworkTags")]
pub mod ListCentralNetworkTags;
#[cfg(feature = "ListCloudConnectionQuotas")]
pub mod ListCloudConnectionQuotas;
#[cfg(feature = "ListCloudConnectionRoutes")]
pub mod ListCloudConnectionRoutes;
#[cfg(feature = "ListCloudConnections")]
pub mod ListCloudConnections;
#[cfg(feature = "ListCloudConnectionsByTags")]
pub mod ListCloudConnectionsByTags;
#[cfg(feature = "ListCloudConnectionTags")]
pub mod ListCloudConnectionTags;
#[cfg(feature = "ListDomainTags")]
pub mod ListDomainTags;
#[cfg(feature = "ListGcbResourceByTag")]
pub mod ListGcbResourceByTag;
#[cfg(feature = "ListGcbResourceTags")]
pub mod ListGcbResourceTags;
#[cfg(feature = "ListGcbTenantTags")]
pub mod ListGcbTenantTags;
#[cfg(feature = "ListGlobalConnectionBandwidthConfigs")]
pub mod ListGlobalConnectionBandwidthConfigs;
#[cfg(feature = "ListGlobalConnectionBandwidthLineLevels")]
pub mod ListGlobalConnectionBandwidthLineLevels;
#[cfg(feature = "ListGlobalConnectionBandwidths")]
pub mod ListGlobalConnectionBandwidths;
#[cfg(feature = "ListGlobalConnectionBandwidthSites")]
pub mod ListGlobalConnectionBandwidthSites;
#[cfg(feature = "ListGlobalConnectionBandwidthSpecCodes")]
pub mod ListGlobalConnectionBandwidthSpecCodes;
#[cfg(feature = "ListInterRegionBandwidths")]
pub mod ListInterRegionBandwidths;
#[cfg(feature = "ListNetworkInstances")]
pub mod ListNetworkInstances;
#[cfg(feature = "ListPermissions")]
pub mod ListPermissions;
#[cfg(feature = "ListResourceByFilterTag")]
pub mod ListResourceByFilterTag;
#[cfg(feature = "ListSiteNetworkCapabilities")]
pub mod ListSiteNetworkCapabilities;
#[cfg(feature = "ListSiteNetworkQuotas")]
pub mod ListSiteNetworkQuotas;
#[cfg(feature = "ListSiteNetworks")]
pub mod ListSiteNetworks;
#[cfg(feature = "ListSupportBindingConnectionBandwidths")]
pub mod ListSupportBindingConnectionBandwidths;
#[cfg(feature = "ListTags")]
pub mod ListTags;
#[cfg(feature = "ShowBandwidthPackage")]
pub mod ShowBandwidthPackage;
#[cfg(feature = "ShowCentralNetwork")]
pub mod ShowCentralNetwork;
#[cfg(feature = "ShowCentralNetworkErRouteTableAttachment")]
pub mod ShowCentralNetworkErRouteTableAttachment;
#[cfg(feature = "ShowCentralNetworkGdgwAttachment")]
pub mod ShowCentralNetworkGdgwAttachment;
#[cfg(feature = "ShowCloudConnection")]
pub mod ShowCloudConnection;
#[cfg(feature = "ShowCloudConnectionRoutes")]
pub mod ShowCloudConnectionRoutes;
#[cfg(feature = "ShowGlobalConnectionBandwidth")]
pub mod ShowGlobalConnectionBandwidth;
#[cfg(feature = "ShowInterRegionBandwidth")]
pub mod ShowInterRegionBandwidth;
#[cfg(feature = "ShowNetworkInstance")]
pub mod ShowNetworkInstance;
#[cfg(feature = "ShowSiteNetwork")]
pub mod ShowSiteNetwork;
#[cfg(feature = "TagBandwidthPackage")]
pub mod TagBandwidthPackage;
#[cfg(feature = "TagCentralNetwork")]
pub mod TagCentralNetwork;
#[cfg(feature = "TagCloudConnection")]
pub mod TagCloudConnection;
#[cfg(feature = "UntagBandwidthPackage")]
pub mod UntagBandwidthPackage;
#[cfg(feature = "UntagCentralNetwork")]
pub mod UntagCentralNetwork;
#[cfg(feature = "UntagCloudConnection")]
pub mod UntagCloudConnection;
#[cfg(feature = "UpdateAuthorisation")]
pub mod UpdateAuthorisation;
#[cfg(feature = "UpdateBandwidthPackage")]
pub mod UpdateBandwidthPackage;
#[cfg(feature = "UpdateCentralNetwork")]
pub mod UpdateCentralNetwork;
#[cfg(feature = "UpdateCentralNetworkConnection")]
pub mod UpdateCentralNetworkConnection;
#[cfg(feature = "UpdateCentralNetworkErRouteTableAttachment")]
pub mod UpdateCentralNetworkErRouteTableAttachment;
#[cfg(feature = "UpdateCentralNetworkGdgwAttachment")]
pub mod UpdateCentralNetworkGdgwAttachment;
#[cfg(feature = "UpdateCloudConnection")]
pub mod UpdateCloudConnection;
