[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddKeystorePermission = []
CheckJobCountIsTopLimit = []
CheckJobNameIsExists = []
CheckWebhookUrl = []
ClearRecyclingJobs = []
CopyJob = []
CreateBuildJob = []
CreateNewJob = []
CreateTemplate = []
CreateTemplates = []
DeleteBuildJob = []
DeleteKeystore = []
DeleteKeystorePermission = []
DeleteRecyclingJobs = []
DeleteTemplate = []
DeleteTemplates = []
DeleteTheJob = []
DisableBuildJob = []
DisableNotice = []
DisableTheJob = []
DownloadBuildLog = []
DownloadJunitCoverageZip = []
DownloadKeystore = []
DownloadKeystoreByName = []
DownloadLogByRecordId = []
DownloadRealTimeLog = []
DownloadTaskLog = []
EnableBuildJob = []
ExecuteJob = []
ListBriefRecord = []
ListBuildInfoRecord = []
ListBuildInfoRecordByJobId = []
ListBuildParameter = []
ListCustomTemplate = []
ListJob = []
ListJobConfig = []
ListJunitCoverageSummary = []
ListKeystore = []
ListKeystoreSearch = []
ListNotice = []
ListOfficialTemplate = []
ListProjectJobs = []
ListRecommendOfficialTemplate = []
ListRecords = []
ListRecyclingJob = []
ListRelatedProjectInfo = []
ListRepoBranch = []
ListRepository = []
ListTemplates = []
ListUpdateJobHistory = []
RestoreRecyclingJobs = []
RunJob = []
SaveTemplateUsedInfo = []
SetKeepTime = []
ShowBuildInfoRecord = []
ShowBuildParamsList = []
ShowBuildRecord = []
ShowBuildRecordBuildScript = []
ShowBuildRecordFlowGraph = []
ShowBuildRecordFullStages = []
ShowCopyName = []
ShowDefaultBuildParameters = []
ShowDefaultProjectPermission = []
ShowDisable = []
ShowDockerfileTemplate = []
ShowFlowGraph = []
ShowHistoryDetails = []
ShowImageTemplateList = []
ShowJobBuildRecordDetail = []
ShowJobBuildSuccessRatio = []
ShowJobBuildTime = []
ShowJobConfig = []
ShowJobConfigDiff = []
ShowJobInfo = []
ShowJobListByProjectId = []
ShowJobNoticeConfigInfo = []
ShowJobPipelineInfo = []
ShowJobRolePermission = []
ShowJobStatus = []
ShowJobStepStatus = []
ShowJobSuccessRatio = []
ShowJobSystemParameters = []
ShowJobTotal = []
ShowKeystorePermission = []
ShowLastHistory = []
ShowListHistory = []
ShowListPeriodHistory = []
ShowOutputInfo = []
ShowProjectJobPermission = []
ShowProjectPermission = []
ShowRecordDetail = []
ShowRecordInfo = []
ShowRelatedProject = []
ShowReportSummary = []
ShowRunningStatus = []
ShowSummaryBuildJobInfo = []
ShowUserOverPackageQuota = []
ShowYamlTemplate = []
StopBuildJob = []
StopJob = []
full = ["AddKeystorePermission", "CheckJobCountIsTopLimit", "CheckJobNameIsExists", "CheckWebhookUrl", "ClearRecyclingJobs", "CopyJob", "CreateBuildJob", "CreateNewJob", "CreateTemplate", "CreateTemplates", "DeleteBuildJob", "DeleteKeystore", "DeleteKeystorePermission", "DeleteRecyclingJobs", "DeleteTemplate", "DeleteTemplates", "DeleteTheJob", "DisableBuildJob", "DisableNotice", "DisableTheJob", "DownloadBuildLog", "DownloadJunitCoverageZip", "DownloadKeystore", "DownloadKeystoreByName", "DownloadLogByRecordId", "DownloadRealTimeLog", "DownloadTaskLog", "EnableBuildJob", "ExecuteJob", "ListBriefRecord", "ListBuildInfoRecord", "ListBuildInfoRecordByJobId", "ListBuildParameter", "ListCustomTemplate", "ListJob", "ListJobConfig", "ListJunitCoverageSummary", "ListKeystore", "ListKeystoreSearch", "ListNotice", "ListOfficialTemplate", "ListProjectJobs", "ListRecommendOfficialTemplate", "ListRecords", "ListRecyclingJob", "ListRelatedProjectInfo", "ListRepoBranch", "ListRepository", "ListTemplates", "ListUpdateJobHistory", "RestoreRecyclingJobs", "RunJob", "SaveTemplateUsedInfo", "SetKeepTime", "ShowBuildInfoRecord", "ShowBuildParamsList", "ShowBuildRecord", "ShowBuildRecordBuildScript", "ShowBuildRecordFlowGraph", "ShowBuildRecordFullStages", "ShowCopyName", "ShowDefaultBuildParameters", "ShowDefaultProjectPermission", "ShowDisable", "ShowDockerfileTemplate", "ShowFlowGraph", "ShowHistoryDetails", "ShowImageTemplateList", "ShowJobBuildRecordDetail", "ShowJobBuildSuccessRatio", "ShowJobBuildTime", "ShowJobConfig", "ShowJobConfigDiff", "ShowJobInfo", "ShowJobListByProjectId", "ShowJobNoticeConfigInfo", "ShowJobPipelineInfo", "ShowJobRolePermission", "ShowJobStatus", "ShowJobStepStatus", "ShowJobSuccessRatio", "ShowJobSystemParameters", "ShowJobTotal", "ShowKeystorePermission", "ShowLastHistory", "ShowListHistory", "ShowListPeriodHistory", "ShowOutputInfo", "ShowProjectJobPermission", "ShowProjectPermission", "ShowRecordDetail", "ShowRecordInfo", "ShowRelatedProject", "ShowReportSummary", "ShowRunningStatus", "ShowSummaryBuildJobInfo", "ShowUserOverPackageQuota", "ShowYamlTemplate", "StopBuildJob", "StopJob"]

[lib]
name = "huawei_cloud_api_definitions_CodeArtsBuild"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-CodeArtsBuild"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
