[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
CheckJobCountIsTopLimit = []
CheckJobNameIsExists = []
CreateBuildJob = []
CreateTemplates = []
DeleteBuildJob = []
DeleteTemplates = []
DisableBuildJob = []
DisableNotice = []
DownloadBuildLog = []
DownloadJunitCoverageZip = []
DownloadKeystore = []
DownloadKeystoreByName = []
DownloadLogByRecordId = []
DownloadRealTimeLog = []
DownloadTaskLog = []
EnableBuildJob = []
ListBuildInfoRecord = []
ListBuildInfoRecordByJobId = []
ListBuildParameter = []
ListCustomTemplate = []
ListJob = []
ListJobConfig = []
ListJunitCoverageSummary = []
ListKeystore = []
ListKeystoreSearch = []
ListNotice = []
ListOfficialTemplate = []
ListProjectJobs = []
ListRecords = []
ListRecyclingJob = []
ListRelatedProjectInfo = []
ListRepoBranch = []
ListRepository = []
ListTemplates = []
ListUpdateJobHistory = []
RunJob = []
ShowBuildInfoRecord = []
ShowBuildParamsList = []
ShowBuildRecord = []
ShowBuildRecordBuildScript = []
ShowBuildRecordFlowGraph = []
ShowBuildRecordFullStages = []
ShowCopyName = []
ShowDefaultBuildParameters = []
ShowDefaultProjectPermission = []
ShowDisable = []
ShowDockerfileTemplate = []
ShowFlowGraph = []
ShowHistoryDetails = []
ShowImageTemplateList = []
ShowJobBuildRecordDetail = []
ShowJobBuildSuccessRatio = []
ShowJobBuildTime = []
ShowJobConfig = []
ShowJobConfigDiff = []
ShowJobInfo = []
ShowJobListByProjectId = []
ShowJobNoticeConfigInfo = []
ShowJobRolePermission = []
ShowJobStatus = []
ShowJobStepStatus = []
ShowJobSuccessRatio = []
ShowJobSystemParameters = []
ShowJobTotal = []
ShowKeystorePermission = []
ShowLastHistory = []
ShowListHistory = []
ShowListPeriodHistory = []
ShowOutputInfo = []
ShowProjectPermission = []
ShowRecordDetail = []
ShowRecordInfo = []
ShowRelatedProject = []
ShowReportSummary = []
ShowRunningStatus = []
ShowSummaryBuildJobInfo = []
ShowUserOverPackageQuota = []
ShowYamlTemplate = []
StopBuildJob = []
StopJob = []
UpdateBuildJob = []
UpdateNotice = []
full = ["CheckJobCountIsTopLimit", "CheckJobNameIsExists", "CreateBuildJob", "CreateTemplates", "DeleteBuildJob", "DeleteTemplates", "DisableBuildJob", "DisableNotice", "DownloadBuildLog", "DownloadJunitCoverageZip", "DownloadKeystore", "DownloadKeystoreByName", "DownloadLogByRecordId", "DownloadRealTimeLog", "DownloadTaskLog", "EnableBuildJob", "ListBuildInfoRecord", "ListBuildInfoRecordByJobId", "ListBuildParameter", "ListCustomTemplate", "ListJob", "ListJobConfig", "ListJunitCoverageSummary", "ListKeystore", "ListKeystoreSearch", "ListNotice", "ListOfficialTemplate", "ListProjectJobs", "ListRecords", "ListRecyclingJob", "ListRelatedProjectInfo", "ListRepoBranch", "ListRepository", "ListTemplates", "ListUpdateJobHistory", "RunJob", "ShowBuildInfoRecord", "ShowBuildParamsList", "ShowBuildRecord", "ShowBuildRecordBuildScript", "ShowBuildRecordFlowGraph", "ShowBuildRecordFullStages", "ShowCopyName", "ShowDefaultBuildParameters", "ShowDefaultProjectPermission", "ShowDisable", "ShowDockerfileTemplate", "ShowFlowGraph", "ShowHistoryDetails", "ShowImageTemplateList", "ShowJobBuildRecordDetail", "ShowJobBuildSuccessRatio", "ShowJobBuildTime", "ShowJobConfig", "ShowJobConfigDiff", "ShowJobInfo", "ShowJobListByProjectId", "ShowJobNoticeConfigInfo", "ShowJobRolePermission", "ShowJobStatus", "ShowJobStepStatus", "ShowJobSuccessRatio", "ShowJobSystemParameters", "ShowJobTotal", "ShowKeystorePermission", "ShowLastHistory", "ShowListHistory", "ShowListPeriodHistory", "ShowOutputInfo", "ShowProjectPermission", "ShowRecordDetail", "ShowRecordInfo", "ShowRelatedProject", "ShowReportSummary", "ShowRunningStatus", "ShowSummaryBuildJobInfo", "ShowUserOverPackageQuota", "ShowYamlTemplate", "StopBuildJob", "StopJob", "UpdateBuildJob", "UpdateNotice"]

[lib]
name = "huawei_cloud_api_definitions_CodeArtsBuild"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-CodeArtsBuild"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
