[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddFavouriteCustomTemplate = []
AddFavouriteOfficialTemplate = []
AddFavouriteTask = []
AddKeystorePermission = []
ApplyProjectPermission = []
BatchDeleteBuildJobs = []
BatchUpdateJobRolePermission = []
CheckJobCountIsTopLimit = []
CheckJobInternal = []
CheckJobNameIsExists = []
CheckWebhookUrl = []
ClearRecyclingJobs = []
CopyJob = []
CreateBuildJob = []
CreateJobGroup = []
CreateNewJob = []
CreateTemplate = []
CreateTemplates = []
DeleteBuildJob = []
DeleteGroup = []
DeleteKeystore = []
DeleteKeystorePermission = []
DeleteRecyclingJobs = []
DeleteTemplate = []
DeleteTemplates = []
DeleteTheJob = []
DisableBuildJob = []
DisableNotice = []
DisableTheJob = []
DownloadBuildFullLog = []
DownloadBuildLog = []
DownloadBuildRealTimeLog = []
DownloadJunitCoverageZip = []
DownloadKeystore = []
DownloadKeystoreByName = []
DownloadLogByRecordId = []
DownloadRealTimeLog = []
DownloadTaskLog = []
EnableBuildJob = []
ExecuteJob = []
ListBriefRecord = []
ListBuildInfoRecord = []
ListBuildInfoRecordByJobId = []
ListBuildParameter = []
ListCustomTemplate = []
ListEndPoints = []
ListGroupTree = []
ListJob = []
ListJobConfig = []
ListJunitCoverageSummary = []
ListKeystore = []
ListKeystoreSearch = []
ListNotice = []
ListOfficialTemplate = []
ListProjectJobs = []
ListRecommendOfficialTemplate = []
ListRecords = []
ListRecyclingJob = []
ListRelatedProjectInfo = []
ListRepoBranch = []
ListRepository = []
ListTemplates = []
ListUpdateJobHistory = []
MoveGroup = []
RemoverFavouriteCustomTemplate = []
RemoverFavouriteOfficialTemplate = []
RemoverFavouriteTask = []
RestoreRecyclingJobs = []
RunJob = []
SaveTemplateUsedInfo = []
SetKeepTime = []
ShowActionIInfo = []
ShowAvailableInnerSpec = []
ShowBuildDetails = []
ShowBuildInfoRecord = []
ShowBuildParamsList = []
ShowBuildRecord = []
ShowBuildRecordBuildScript = []
ShowBuildRecordFlowGraph = []
ShowBuildRecordFullStages = []
ShowCopyName = []
ShowDefaultBuildParameters = []
ShowDefaultProjectPermission = []
ShowDisable = []
ShowDockerfileTemplate = []
ShowDomainStatus = []
ShowDomainsStatuses = []
ShowFlowGraph = []
ShowHistoryDetails = []
ShowImageTemplateList = []
ShowJobBuildRecordDetail = []
ShowJobBuildSuccessRatio = []
ShowJobBuildTime = []
ShowJobConfig = []
ShowJobConfigDiff = []
ShowJobInfo = []
ShowJobListByProjectId = []
ShowJobNoticeConfigInfo = []
ShowJobPipelineInfo = []
ShowJobRolePermission = []
full = ["AddFavouriteCustomTemplate", "AddFavouriteOfficialTemplate", "AddFavouriteTask", "AddKeystorePermission", "ApplyProjectPermission", "BatchDeleteBuildJobs", "BatchUpdateJobRolePermission", "CheckJobCountIsTopLimit", "CheckJobInternal", "CheckJobNameIsExists", "CheckWebhookUrl", "ClearRecyclingJobs", "CopyJob", "CreateBuildJob", "CreateJobGroup", "CreateNewJob", "CreateTemplate", "CreateTemplates", "DeleteBuildJob", "DeleteGroup", "DeleteKeystore", "DeleteKeystorePermission", "DeleteRecyclingJobs", "DeleteTemplate", "DeleteTemplates", "DeleteTheJob", "DisableBuildJob", "DisableNotice", "DisableTheJob", "DownloadBuildFullLog", "DownloadBuildLog", "DownloadBuildRealTimeLog", "DownloadJunitCoverageZip", "DownloadKeystore", "DownloadKeystoreByName", "DownloadLogByRecordId", "DownloadRealTimeLog", "DownloadTaskLog", "EnableBuildJob", "ExecuteJob", "ListBriefRecord", "ListBuildInfoRecord", "ListBuildInfoRecordByJobId", "ListBuildParameter", "ListCustomTemplate", "ListEndPoints", "ListGroupTree", "ListJob", "ListJobConfig", "ListJunitCoverageSummary", "ListKeystore", "ListKeystoreSearch", "ListNotice", "ListOfficialTemplate", "ListProjectJobs", "ListRecommendOfficialTemplate", "ListRecords", "ListRecyclingJob", "ListRelatedProjectInfo", "ListRepoBranch", "ListRepository", "ListTemplates", "ListUpdateJobHistory", "MoveGroup", "RemoverFavouriteCustomTemplate", "RemoverFavouriteOfficialTemplate", "RemoverFavouriteTask", "RestoreRecyclingJobs", "RunJob", "SaveTemplateUsedInfo", "SetKeepTime", "ShowActionIInfo", "ShowAvailableInnerSpec", "ShowBuildDetails", "ShowBuildInfoRecord", "ShowBuildParamsList", "ShowBuildRecord", "ShowBuildRecordBuildScript", "ShowBuildRecordFlowGraph", "ShowBuildRecordFullStages", "ShowCopyName", "ShowDefaultBuildParameters", "ShowDefaultProjectPermission", "ShowDisable", "ShowDockerfileTemplate", "ShowDomainsStatuses", "ShowDomainStatus", "ShowFlowGraph", "ShowHistoryDetails", "ShowImageTemplateList", "ShowJobBuildRecordDetail", "ShowJobBuildSuccessRatio", "ShowJobBuildTime", "ShowJobConfig", "ShowJobConfigDiff", "ShowJobInfo", "ShowJobListByProjectId", "ShowJobNoticeConfigInfo", "ShowJobPipelineInfo", "ShowJobRolePermission"]

[lib]
name = "huawei_cloud_api_definitions_CodeArtsBuild"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-CodeArtsBuild"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
