#[cfg(feature = "AddEcnWithEr")]
pub mod AddEcnWithEr;
#[cfg(feature = "AddEcnWithIeg")]
pub mod AddEcnWithIeg;
#[cfg(feature = "AddVrrpConfig")]
pub mod AddVrrpConfig;
#[cfg(feature = "ChangeIegPassword")]
pub mod ChangeIegPassword;
#[cfg(feature = "CreateEcnAccessPoint")]
pub mod CreateEcnAccessPoint;
#[cfg(feature = "CreateEquipment")]
pub mod CreateEquipment;
#[cfg(feature = "CreateEquipmentLanConfig")]
pub mod CreateEquipmentLanConfig;
#[cfg(feature = "CreateEquipmentStaticRouteConfig")]
pub mod CreateEquipmentStaticRouteConfig;
#[cfg(feature = "DeleteEcnAccessPoint")]
pub mod DeleteEcnAccessPoint;
#[cfg(feature = "DeleteEcnWithEr")]
pub mod DeleteEcnWithEr;
#[cfg(feature = "DeleteEcnWithIeg")]
pub mod DeleteEcnWithIeg;
#[cfg(feature = "DeleteEquipment")]
pub mod DeleteEquipment;
#[cfg(feature = "DeleteEquipmentLanConfig")]
pub mod DeleteEquipmentLanConfig;
#[cfg(feature = "DeleteEquipmentStaticRouteConfig")]
pub mod DeleteEquipmentStaticRouteConfig;
#[cfg(feature = "DeleteVrrpConfig")]
pub mod DeleteVrrpConfig;
#[cfg(feature = "GenerateInitialConfiguration")]
pub mod GenerateInitialConfiguration;
#[cfg(feature = "ListEcn")]
pub mod ListEcn;
#[cfg(feature = "ListEcnAccessPointByEcnId")]
pub mod ListEcnAccessPointByEcnId;
#[cfg(feature = "ListEcnWithEr")]
pub mod ListEcnWithEr;
#[cfg(feature = "ListEcnWithIeg")]
pub mod ListEcnWithIeg;
#[cfg(feature = "ListEquipmentInterfaceName")]
pub mod ListEquipmentInterfaceName;
#[cfg(feature = "ListEquipments")]
pub mod ListEquipments;
#[cfg(feature = "ListIeg")]
pub mod ListIeg;
#[cfg(feature = "RebootEquipment")]
pub mod RebootEquipment;
#[cfg(feature = "ShowEcnInfo")]
pub mod ShowEcnInfo;
#[cfg(feature = "ShowEcnWithIeg")]
pub mod ShowEcnWithIeg;
#[cfg(feature = "ShowEquipmentDnsInfo")]
pub mod ShowEquipmentDnsInfo;
#[cfg(feature = "ShowEquipmentInfo")]
pub mod ShowEquipmentInfo;
#[cfg(feature = "ShowEquipmentLanInfo")]
pub mod ShowEquipmentLanInfo;
#[cfg(feature = "ShowEquipmentOspf")]
pub mod ShowEquipmentOspf;
#[cfg(feature = "ShowEquipmentSpecificConfig")]
pub mod ShowEquipmentSpecificConfig;
#[cfg(feature = "ShowEquipmentStaticRouteInfo")]
pub mod ShowEquipmentStaticRouteInfo;
#[cfg(feature = "ShowEquipmentWanInfo")]
pub mod ShowEquipmentWanInfo;
#[cfg(feature = "ShowEquipmentWlan")]
pub mod ShowEquipmentWlan;
#[cfg(feature = "ShowIegInfo")]
pub mod ShowIegInfo;
#[cfg(feature = "ShowQuotasInfo")]
pub mod ShowQuotasInfo;
#[cfg(feature = "ShowVrrpConfig")]
pub mod ShowVrrpConfig;
#[cfg(feature = "SwitchEquipmentHaType")]
pub mod SwitchEquipmentHaType;
#[cfg(feature = "UpdateEcn")]
pub mod UpdateEcn;
#[cfg(feature = "UpdateEcnAccessPoint")]
pub mod UpdateEcnAccessPoint;
#[cfg(feature = "UpdateEquipmentDnsInfo")]
pub mod UpdateEquipmentDnsInfo;
#[cfg(feature = "UpdateEquipmentEsn")]
pub mod UpdateEquipmentEsn;
#[cfg(feature = "UpdateEquipmentInfo")]
pub mod UpdateEquipmentInfo;
#[cfg(feature = "UpdateEquipmentLanConfig")]
pub mod UpdateEquipmentLanConfig;
#[cfg(feature = "UpdateEquipmentOspf")]
pub mod UpdateEquipmentOspf;
#[cfg(feature = "UpdateEquipmentStaticRouteConfig")]
pub mod UpdateEquipmentStaticRouteConfig;
#[cfg(feature = "UpdateEquipmentWanConfig")]
pub mod UpdateEquipmentWanConfig;
#[cfg(feature = "UpdateEquipmentWlan")]
pub mod UpdateEquipmentWlan;
#[cfg(feature = "UpdateIeg")]
pub mod UpdateIeg;
#[cfg(feature = "UpdateVrrpConfig")]
pub mod UpdateVrrpConfig;
