[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
CreateAndStartRandomClusterJob = []
CreateCluster = []
CreateJob = []
CreateLink = []
DeleteCluster = []
DeleteJob = []
DeleteLink = []
ListClusters = []
RestartCluster = []
ShowClusterDetail = []
ShowJobStatus = []
ShowJobs = []
ShowLink = []
ShowSubmissions = []
StartCluster = []
StartJob = []
StopJob = []
UpdateJob = []
UpdateLink = []
full = ["CreateAndStartRandomClusterJob", "CreateCluster", "CreateJob", "CreateLink", "DeleteCluster", "DeleteJob", "DeleteLink", "ListClusters", "RestartCluster", "ShowClusterDetail", "ShowJobs", "ShowJobStatus", "ShowLink", "ShowSubmissions", "StartCluster", "StartJob", "StopJob", "UpdateJob", "UpdateLink"]

[lib]
name = "huawei_cloud_api_definitions_CDM"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-CDM"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "0.1.0"
