#[cfg(feature = "BatchCancelWos")]
pub mod BatchCancelWos;
#[cfg(feature = "BatchCreateWoInstantiations")]
pub mod BatchCreateWoInstantiations;
#[cfg(feature = "BatchCreateWos")]
pub mod BatchCreateWos;
#[cfg(feature = "BatchDeleteWos")]
pub mod BatchDeleteWos;
#[cfg(feature = "BatchGenerateWoSchemes")]
pub mod BatchGenerateWoSchemes;
#[cfg(feature = "CreateXdmApplication")]
pub mod CreateXdmApplication;
#[cfg(feature = "DeleteXdmApplication")]
pub mod DeleteXdmApplication;
#[cfg(feature = "DeployApplication")]
pub mod DeployApplication;
#[cfg(feature = "ListApps")]
pub mod ListApps;
#[cfg(feature = "ListEnvs")]
pub mod ListEnvs;
#[cfg(feature = "ModifyApplication")]
pub mod ModifyApplication;
#[cfg(feature = "SearchWoInfo")]
pub mod SearchWoInfo;
#[cfg(feature = "SearchWoPartInfo")]
pub mod SearchWoPartInfo;
#[cfg(feature = "SearchWosForPage")]
pub mod SearchWosForPage;
#[cfg(feature = "Uninstall")]
pub mod Uninstall;
