[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddInstanceTags = []
AllowDbPrivileges = []
AllowDbRolePrivileges = []
AttachEip = []
BatchShowUpgradeCandidateVersions = []
CancelScheduleTask = []
ConfirmRestoredData = []
CopyConfiguration = []
CreateConfigurationTemplate = []
CreateCrossCloudConstructDisaster = []
CreateDatabase = []
CreateDatabaseInstance = []
CreateDatabaseSchemas = []
CreateDbInstance = []
CreateDbRole = []
CreateDbUser = []
CreateGaussDbInstance = []
CreateInstance = []
CreateLimitTask = []
CreateManualBackup = []
CreateRestoreInstance = []
CreateScheduleTask = []
CreateSlowLogDownload = []
DeleteConfiguration = []
DeleteDatabase = []
DeleteDatabaseSchema = []
DeleteInstance = []
DeleteInstanceTag = []
DeleteJob = []
DeleteLimitTask = []
DeleteManualBackup = []
DeleteScheduleTask = []
DownloadBackup = []
ExecuteCrossCloudDisasterDataCacheEnd = []
ExecuteCrossCloudDisasterDataCacheStart = []
ExecuteCrossCloudDisasterEndSimulation = []
ExecuteCrossCloudDisasterRecoveryFailover = []
ExecuteCrossCloudDisasterRestore = []
ExecuteCrossCloudDisasterStartSimulation = []
ExecuteCrossCloudDisasterSwitchover = []
ExecuteCrossCloudReleaseDisaster = []
InstallKernelPlugin = []
ListApplicableInstances = []
ListAppliedHistories = []
ListAvailableFlavors = []
ListBackups = []
ListBackupsDetails = []
ListBindedEips = []
ListCnInfosBeforeReduce = []
ListComponentInfos = []
ListConfigurations = []
ListConfigurationsDiff = []
ListDatabaseInstances = []
ListDatabaseRoles = []
ListDatabaseSchemas = []
ListDatabases = []
ListDatastores = []
ListDatastoresDetails = []
ListDbBackups = []
ListDbFlavors = []
ListDbUsers = []
ListDisasterRecoveryRecord = []
ListEpsQuotas = []
ListFeatures = []
ListFlavors = []
ListFlavorsDetails = []
ListGaussDbDatastores = []
ListHistoryOperations = []
ListInstanceDetails = []
ListInstanceEngineDetail = []
ListInstanceErrorLogs = []
ListInstanceTags = []
ListInstances = []
ListInstancesDetails = []
ListKernelPlugins = []
ListLimitTask = []
ListNodeLimitSqlModel = []
ListParamGroupTemplates = []
ListParameterGroupTemplates = []
ListPluginExtensions = []
ListPredefinedTags = []
ListProjectTags = []
ListRecycleInstances = []
ListRecycleInstancesDetails = []
ListRestorableInstances = []
ListRestorableInstancesDetails = []
ListRestoreTimes = []
ListScheduleTask = []
ListStorageTypes = []
ListSupportKernelPlugins = []
ListTasks = []
ModifyEpsQuota = []
ResetConfiguration = []
ResetDrConfig = []
ResetPwd = []
ResizeInstanceFlavor = []
RestartInstance = []
RestoreInstance = []
ResumePluginExtensions = []
RunInstanceAction = []
full = ["AddInstanceTags", "AllowDbPrivileges", "AllowDbRolePrivileges", "AttachEip", "BatchShowUpgradeCandidateVersions", "CancelScheduleTask", "ConfirmRestoredData", "CopyConfiguration", "CreateConfigurationTemplate", "CreateCrossCloudConstructDisaster", "CreateDatabase", "CreateDatabaseInstance", "CreateDatabaseSchemas", "CreateDbInstance", "CreateDbRole", "CreateDbUser", "CreateGaussDbInstance", "CreateInstance", "CreateLimitTask", "CreateManualBackup", "CreateRestoreInstance", "CreateScheduleTask", "CreateSlowLogDownload", "DeleteConfiguration", "DeleteDatabase", "DeleteDatabaseSchema", "DeleteInstance", "DeleteInstanceTag", "DeleteJob", "DeleteLimitTask", "DeleteManualBackup", "DeleteScheduleTask", "DownloadBackup", "ExecuteCrossCloudDisasterDataCacheEnd", "ExecuteCrossCloudDisasterDataCacheStart", "ExecuteCrossCloudDisasterEndSimulation", "ExecuteCrossCloudDisasterRecoveryFailover", "ExecuteCrossCloudDisasterRestore", "ExecuteCrossCloudDisasterStartSimulation", "ExecuteCrossCloudDisasterSwitchover", "ExecuteCrossCloudReleaseDisaster", "InstallKernelPlugin", "ListApplicableInstances", "ListAppliedHistories", "ListAvailableFlavors", "ListBackups", "ListBackupsDetails", "ListBindedEips", "ListCnInfosBeforeReduce", "ListComponentInfos", "ListConfigurations", "ListConfigurationsDiff", "ListDatabaseInstances", "ListDatabaseRoles", "ListDatabases", "ListDatabaseSchemas", "ListDatastores", "ListDatastoresDetails", "ListDbBackups", "ListDbFlavors", "ListDbUsers", "ListDisasterRecoveryRecord", "ListEpsQuotas", "ListFeatures", "ListFlavors", "ListFlavorsDetails", "ListGaussDbDatastores", "ListHistoryOperations", "ListInstanceDetails", "ListInstanceEngineDetail", "ListInstanceErrorLogs", "ListInstances", "ListInstancesDetails", "ListInstanceTags", "ListKernelPlugins", "ListLimitTask", "ListNodeLimitSqlModel", "ListParameterGroupTemplates", "ListParamGroupTemplates", "ListPluginExtensions", "ListPredefinedTags", "ListProjectTags", "ListRecycleInstances", "ListRecycleInstancesDetails", "ListRestorableInstances", "ListRestorableInstancesDetails", "ListRestoreTimes", "ListScheduleTask", "ListStorageTypes", "ListSupportKernelPlugins", "ListTasks", "ModifyEpsQuota", "ResetConfiguration", "ResetDrConfig", "ResetPwd", "ResizeInstanceFlavor", "RestartInstance", "RestoreInstance", "ResumePluginExtensions", "RunInstanceAction"]

[lib]
name = "huawei_cloud_api_definitions_GaussDBforopenGauss"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-GaussDBforopenGauss"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
