[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddHbaConfs = []
AddInstanceTags = []
AllowDbPrivileges = []
AllowDbRolePrivileges = []
AttachEip = []
BatchShowUpgradeCandidateVersions = []
BindLtsConfig = []
CancelScheduleTask = []
CollectWdrSnapshot = []
ConfirmRestoredData = []
CopyConfiguration = []
CreateConfigurationTemplate = []
CreateCrossCloudConstructDisaster = []
CreateDatabase = []
CreateDatabaseInstance = []
CreateDatabaseSchemas = []
CreateDbInstance = []
CreateDbRole = []
CreateDbUser = []
CreateGaussDbInstance = []
CreateInstance = []
CreateLimitTask = []
CreateManualBackup = []
CreateReadonlyNodes = []
CreateRestoreInstance = []
CreateScheduleTask = []
CreateSlowLogDownload = []
CreateWdrSnapshot = []
DeleteConfiguration = []
DeleteDatabase = []
DeleteDatabaseSchema = []
DeleteHbaConfs = []
DeleteInstance = []
DeleteInstanceTag = []
DeleteJob = []
DeleteLimitTask = []
DeleteManualBackup = []
DeleteReadonlyNodes = []
DeleteScheduleTask = []
DownloadBackup = []
ExecuteCrossCloudDisasterDataCacheEnd = []
ExecuteCrossCloudDisasterDataCacheStart = []
ExecuteCrossCloudDisasterEndSimulation = []
ExecuteCrossCloudDisasterRecoveryFailover = []
ExecuteCrossCloudDisasterRestore = []
ExecuteCrossCloudDisasterStartSimulation = []
ExecuteCrossCloudDisasterSwitchover = []
ExecuteCrossCloudReleaseDisaster = []
ExportSlowSql = []
InstallKernelPlugin = []
ListApplicableInstances = []
ListAppliedHistories = []
ListAvailableFlavors = []
ListBackups = []
ListBackupsDetails = []
ListBindedEips = []
ListCnInfosBeforeReduce = []
ListComponentInfos = []
ListConfigurations = []
ListConfigurationsDiff = []
ListDatabaseInstances = []
ListDatabaseRoles = []
ListDatabaseSchemaTables = []
ListDatabaseSchemas = []
ListDatabaseVolumeSummary = []
ListDatabases = []
ListDatastores = []
ListDatastoresDetails = []
ListDbBackups = []
ListDbFlavors = []
ListDbUsers = []
ListDisasterRecoveryRecord = []
ListEnhanceFullSqlStatistics = []
ListEpsQuotas = []
ListFeatures = []
ListFlavors = []
ListFlavorsDetails = []
ListGaussDbDatastores = []
ListHbaInfoHistory = []
ListHbaInfos = []
ListHistoryOperations = []
ListInstanceDetails = []
ListInstanceEngineDetail = []
ListInstanceErrorLogs = []
ListInstanceTags = []
ListInstances = []
ListInstancesDetails = []
ListKernelPlugins = []
ListKeyViewExecuteNode = []
ListKmsTdeKey = []
ListLimitTask = []
ListLtsConfigs = []
ListMetricDatas = []
ListNodeLimitSqlModel = []
ListParamGroupTemplates = []
ListParameterGroupTemplates = []
ListPluginExtensions = []
ListPredefinedTags = []
ListProjectTags = []
ListReadonlyNodes = []
full = ["AddHbaConfs", "AddInstanceTags", "AllowDbPrivileges", "AllowDbRolePrivileges", "AttachEip", "BatchShowUpgradeCandidateVersions", "BindLtsConfig", "CancelScheduleTask", "CollectWdrSnapshot", "ConfirmRestoredData", "CopyConfiguration", "CreateConfigurationTemplate", "CreateCrossCloudConstructDisaster", "CreateDatabase", "CreateDatabaseInstance", "CreateDatabaseSchemas", "CreateDbInstance", "CreateDbRole", "CreateDbUser", "CreateGaussDbInstance", "CreateInstance", "CreateLimitTask", "CreateManualBackup", "CreateReadonlyNodes", "CreateRestoreInstance", "CreateScheduleTask", "CreateSlowLogDownload", "CreateWdrSnapshot", "DeleteConfiguration", "DeleteDatabase", "DeleteDatabaseSchema", "DeleteHbaConfs", "DeleteInstance", "DeleteInstanceTag", "DeleteJob", "DeleteLimitTask", "DeleteManualBackup", "DeleteReadonlyNodes", "DeleteScheduleTask", "DownloadBackup", "ExecuteCrossCloudDisasterDataCacheEnd", "ExecuteCrossCloudDisasterDataCacheStart", "ExecuteCrossCloudDisasterEndSimulation", "ExecuteCrossCloudDisasterRecoveryFailover", "ExecuteCrossCloudDisasterRestore", "ExecuteCrossCloudDisasterStartSimulation", "ExecuteCrossCloudDisasterSwitchover", "ExecuteCrossCloudReleaseDisaster", "ExportSlowSql", "InstallKernelPlugin", "ListApplicableInstances", "ListAppliedHistories", "ListAvailableFlavors", "ListBackups", "ListBackupsDetails", "ListBindedEips", "ListCnInfosBeforeReduce", "ListComponentInfos", "ListConfigurations", "ListConfigurationsDiff", "ListDatabaseInstances", "ListDatabaseRoles", "ListDatabases", "ListDatabaseSchemas", "ListDatabaseSchemaTables", "ListDatabaseVolumeSummary", "ListDatastores", "ListDatastoresDetails", "ListDbBackups", "ListDbFlavors", "ListDbUsers", "ListDisasterRecoveryRecord", "ListEnhanceFullSqlStatistics", "ListEpsQuotas", "ListFeatures", "ListFlavors", "ListFlavorsDetails", "ListGaussDbDatastores", "ListHbaInfoHistory", "ListHbaInfos", "ListHistoryOperations", "ListInstanceDetails", "ListInstanceEngineDetail", "ListInstanceErrorLogs", "ListInstances", "ListInstancesDetails", "ListInstanceTags", "ListKernelPlugins", "ListKeyViewExecuteNode", "ListKmsTdeKey", "ListLimitTask", "ListLtsConfigs", "ListMetricDatas", "ListNodeLimitSqlModel", "ListParameterGroupTemplates", "ListParamGroupTemplates", "ListPluginExtensions", "ListPredefinedTags", "ListProjectTags", "ListReadonlyNodes"]

[lib]
name = "huawei_cloud_api_definitions_GaussDBforopenGauss"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-GaussDBforopenGauss"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
