[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddHbaConfs = []
AddInstanceTags = []
AllowDbPrivileges = []
AllowDbRolePrivileges = []
AttachEip = []
AuthorizeBackupDownload = []
BatchSetBackupPolicy = []
BatchShowUpgradeCandidateVersions = []
BindLtsConfig = []
CancelScheduleTask = []
CollectAsp = []
CollectWdrSnapshot = []
ConfirmRestoredData = []
CopyConfiguration = []
CreateConfigurationTemplate = []
CreateCrossCloudConstructDisaster = []
CreateDatabase = []
CreateDatabaseInstance = []
CreateDatabaseSchemas = []
CreateDbInstance = []
CreateDbRole = []
CreateDbUser = []
CreateGaussDbInstance = []
CreateInstance = []
CreateLimitTask = []
CreateManualBackup = []
CreateReadonlyNodes = []
CreateRestoreInstance = []
CreateScheduleTask = []
CreateSlowLogDownload = []
CreateSqlLimitTask = []
CreateWdrSnapshot = []
DeleteConfiguration = []
DeleteDatabase = []
DeleteDatabaseSchema = []
DeleteHbaConfs = []
DeleteInstance = []
DeleteInstanceTag = []
DeleteJob = []
DeleteLimitTask = []
DeleteManualBackup = []
DeleteReadonlyNodes = []
DeleteScheduleTask = []
DeleteSharding = []
DeleteSqlLimitTask = []
ExecuteCrossCloudDisasterDataCacheEnd = []
ExecuteCrossCloudDisasterDataCacheStart = []
ExecuteCrossCloudDisasterEndSimulation = []
ExecuteCrossCloudDisasterRecoveryFailover = []
ExecuteCrossCloudDisasterRestore = []
ExecuteCrossCloudDisasterStartSimulation = []
ExecuteCrossCloudDisasterSwitchover = []
ExecuteCrossCloudReleaseDisaster = []
ExportSlowSql = []
InstallKernelPlugin = []
ListApplicableInstances = []
ListAppliedHistories = []
ListAspInfos = []
ListAvailableFlavors = []
ListBackups = []
ListBackupsDetails = []
ListBindedEips = []
ListCnInfosBeforeReduce = []
ListComponentInfos = []
ListConfigurations = []
ListConfigurationsDiff = []
ListDatabaseInstances = []
ListDatabaseRoles = []
ListDatabaseSchemaTables = []
ListDatabaseSchemas = []
ListDatabaseVersions = []
ListDatabaseVolumeSummary = []
ListDatabases = []
ListDatastores = []
ListDatastoresDetails = []
ListDbBackups = []
ListDbFlavors = []
ListDbUsers = []
ListDisasterRecoveryRecord = []
ListEnhanceFullSqlStatistics = []
ListEnhanceFullSqls = []
ListEnterpriseProjects = []
ListEpsQuotas = []
ListFeatures = []
ListFlavors = []
ListFlavorsDetails = []
ListFullSqlSwitches = []
ListGaussDbDatastores = []
ListHbaInfoHistory = []
ListHbaInfos = []
ListHistoryOperations = []
ListInstanceDetails = []
ListInstanceEngineDetail = []
ListInstanceErrorLogs = []
ListInstanceTags = []
ListInstances = []
ListInstancesDetails = []
ListKernelPlugins = []
ListKeyViewExecuteNode = []
ListKmsTdeKey = []
full = ["AddHbaConfs", "AddInstanceTags", "AllowDbPrivileges", "AllowDbRolePrivileges", "AttachEip", "AuthorizeBackupDownload", "BatchSetBackupPolicy", "BatchShowUpgradeCandidateVersions", "BindLtsConfig", "CancelScheduleTask", "CollectAsp", "CollectWdrSnapshot", "ConfirmRestoredData", "CopyConfiguration", "CreateConfigurationTemplate", "CreateCrossCloudConstructDisaster", "CreateDatabase", "CreateDatabaseInstance", "CreateDatabaseSchemas", "CreateDbInstance", "CreateDbRole", "CreateDbUser", "CreateGaussDbInstance", "CreateInstance", "CreateLimitTask", "CreateManualBackup", "CreateReadonlyNodes", "CreateRestoreInstance", "CreateScheduleTask", "CreateSlowLogDownload", "CreateSqlLimitTask", "CreateWdrSnapshot", "DeleteConfiguration", "DeleteDatabase", "DeleteDatabaseSchema", "DeleteHbaConfs", "DeleteInstance", "DeleteInstanceTag", "DeleteJob", "DeleteLimitTask", "DeleteManualBackup", "DeleteReadonlyNodes", "DeleteScheduleTask", "DeleteSharding", "DeleteSqlLimitTask", "ExecuteCrossCloudDisasterDataCacheEnd", "ExecuteCrossCloudDisasterDataCacheStart", "ExecuteCrossCloudDisasterEndSimulation", "ExecuteCrossCloudDisasterRecoveryFailover", "ExecuteCrossCloudDisasterRestore", "ExecuteCrossCloudDisasterStartSimulation", "ExecuteCrossCloudDisasterSwitchover", "ExecuteCrossCloudReleaseDisaster", "ExportSlowSql", "InstallKernelPlugin", "ListApplicableInstances", "ListAppliedHistories", "ListAspInfos", "ListAvailableFlavors", "ListBackups", "ListBackupsDetails", "ListBindedEips", "ListCnInfosBeforeReduce", "ListComponentInfos", "ListConfigurations", "ListConfigurationsDiff", "ListDatabaseInstances", "ListDatabaseRoles", "ListDatabases", "ListDatabaseSchemas", "ListDatabaseSchemaTables", "ListDatabaseVersions", "ListDatabaseVolumeSummary", "ListDatastores", "ListDatastoresDetails", "ListDbBackups", "ListDbFlavors", "ListDbUsers", "ListDisasterRecoveryRecord", "ListEnhanceFullSqls", "ListEnhanceFullSqlStatistics", "ListEnterpriseProjects", "ListEpsQuotas", "ListFeatures", "ListFlavors", "ListFlavorsDetails", "ListFullSqlSwitches", "ListGaussDbDatastores", "ListHbaInfoHistory", "ListHbaInfos", "ListHistoryOperations", "ListInstanceDetails", "ListInstanceEngineDetail", "ListInstanceErrorLogs", "ListInstances", "ListInstancesDetails", "ListInstanceTags", "ListKernelPlugins", "ListKeyViewExecuteNode", "ListKmsTdeKey"]

[lib]
name = "huawei_cloud_api_definitions_GaussDBforopenGauss"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-GaussDBforopenGauss"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
