[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddInstanceTags = []
AllowDbPrivileges = []
AllowDbRolePrivileges = []
AttachEip = []
BatchShowUpgradeCandidateVersions = []
ConfirmRestoredData = []
CopyConfiguration = []
CreateConfigurationTemplate = []
CreateDatabase = []
CreateDatabaseInstance = []
CreateDatabaseSchemas = []
CreateDbInstance = []
CreateDbRole = []
CreateDbUser = []
CreateGaussDbInstance = []
CreateInstance = []
CreateLimitTask = []
CreateManualBackup = []
CreateRestoreInstance = []
CreateSlowLogDownload = []
DeleteConfiguration = []
DeleteDatabase = []
DeleteDatabaseSchema = []
DeleteInstance = []
DeleteInstanceTag = []
DeleteJob = []
DeleteLimitTask = []
DeleteManualBackup = []
DownloadBackup = []
InstallKernelPlugin = []
ListApplicableInstances = []
ListAppliedHistories = []
ListAvailableFlavors = []
ListBackups = []
ListBackupsDetails = []
ListBindedEips = []
ListCnInfosBeforeReduce = []
ListComponentInfos = []
ListConfigurations = []
ListConfigurationsDiff = []
ListDatabaseInstances = []
ListDatabaseRoles = []
ListDatabaseSchemas = []
ListDatabases = []
ListDatastores = []
ListDatastoresDetails = []
ListDbBackups = []
ListDbFlavors = []
ListDbUsers = []
ListEpsQuotas = []
ListFeatures = []
ListFlavors = []
ListFlavorsDetails = []
ListGaussDbDatastores = []
ListHistoryOperations = []
ListInstanceDetails = []
ListInstanceErrorLogs = []
ListInstanceTags = []
ListInstances = []
ListInstancesDetails = []
ListKernelPlugins = []
ListLimitTask = []
ListNodeLimitSqlModel = []
ListParamGroupTemplates = []
ListParameterGroupTemplates = []
ListPluginExtensions = []
ListPredefinedTags = []
ListProjectTags = []
ListRecycleInstances = []
ListRecycleInstancesDetails = []
ListRestorableInstances = []
ListRestorableInstancesDetails = []
ListRestoreTimes = []
ListStorageTypes = []
ListSupportKernelPlugins = []
ListTasks = []
ListTopIoTraffics = []
ModifyEpsQuota = []
ResetConfiguration = []
ResetPwd = []
ResizeInstanceFlavor = []
RestartInstance = []
RestoreInstance = []
ResumePluginExtensions = []
RunInstanceAction = []
SearchAutoEnlargePolicy = []
SetBackupPolicy = []
SetDbUserPwd = []
SetKernelPluginLicense = []
SetNewBackupPolicy = []
SetRecyclePolicy = []
ShowBackupPolicy = []
ShowBalanceStatus = []
ShowBatchUpgradeCandidateVersions = []
ShowConfigurationDetail = []
ShowDeploymentForm = []
ShowErrorLogSwitchStatus = []
ShowInstanceConfiguration = []
ShowInstanceDisk = []
ShowInstanceParamGroup = []
full = ["AddInstanceTags", "AllowDbPrivileges", "AllowDbRolePrivileges", "AttachEip", "BatchShowUpgradeCandidateVersions", "ConfirmRestoredData", "CopyConfiguration", "CreateConfigurationTemplate", "CreateDatabase", "CreateDatabaseInstance", "CreateDatabaseSchemas", "CreateDbInstance", "CreateDbRole", "CreateDbUser", "CreateGaussDbInstance", "CreateInstance", "CreateLimitTask", "CreateManualBackup", "CreateRestoreInstance", "CreateSlowLogDownload", "DeleteConfiguration", "DeleteDatabase", "DeleteDatabaseSchema", "DeleteInstance", "DeleteInstanceTag", "DeleteJob", "DeleteLimitTask", "DeleteManualBackup", "DownloadBackup", "InstallKernelPlugin", "ListApplicableInstances", "ListAppliedHistories", "ListAvailableFlavors", "ListBackups", "ListBackupsDetails", "ListBindedEips", "ListCnInfosBeforeReduce", "ListComponentInfos", "ListConfigurations", "ListConfigurationsDiff", "ListDatabaseInstances", "ListDatabaseRoles", "ListDatabases", "ListDatabaseSchemas", "ListDatastores", "ListDatastoresDetails", "ListDbBackups", "ListDbFlavors", "ListDbUsers", "ListEpsQuotas", "ListFeatures", "ListFlavors", "ListFlavorsDetails", "ListGaussDbDatastores", "ListHistoryOperations", "ListInstanceDetails", "ListInstanceErrorLogs", "ListInstances", "ListInstancesDetails", "ListInstanceTags", "ListKernelPlugins", "ListLimitTask", "ListNodeLimitSqlModel", "ListParameterGroupTemplates", "ListParamGroupTemplates", "ListPluginExtensions", "ListPredefinedTags", "ListProjectTags", "ListRecycleInstances", "ListRecycleInstancesDetails", "ListRestorableInstances", "ListRestorableInstancesDetails", "ListRestoreTimes", "ListStorageTypes", "ListSupportKernelPlugins", "ListTasks", "ListTopIoTraffics", "ModifyEpsQuota", "ResetConfiguration", "ResetPwd", "ResizeInstanceFlavor", "RestartInstance", "RestoreInstance", "ResumePluginExtensions", "RunInstanceAction", "SearchAutoEnlargePolicy", "SetBackupPolicy", "SetDbUserPwd", "SetKernelPluginLicense", "SetNewBackupPolicy", "SetRecyclePolicy", "ShowBackupPolicy", "ShowBalanceStatus", "ShowBatchUpgradeCandidateVersions", "ShowConfigurationDetail", "ShowDeploymentForm", "ShowErrorLogSwitchStatus", "ShowInstanceConfiguration", "ShowInstanceDisk", "ShowInstanceParamGroup"]

[lib]
name = "huawei_cloud_api_definitions_GaussDBforopenGauss"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-GaussDBforopenGauss"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
