[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddInstanceTags = []
AllowDbPrivileges = []
AttachEip = []
CopyConfiguration = []
CreateConfigurationTemplate = []
CreateDatabase = []
CreateDatabaseSchemas = []
CreateDbInstance = []
CreateDbUser = []
CreateInstance = []
CreateManualBackup = []
CreateRestoreInstance = []
DeleteConfiguration = []
DeleteDatabase = []
DeleteInstance = []
DeleteJob = []
DeleteManualBackup = []
DownloadBackup = []
ListApplicableInstances = []
ListAppliedHistories = []
ListAvailableFlavors = []
ListBackups = []
ListBindedEips = []
ListComponentInfos = []
ListConfigurations = []
ListConfigurationsDiff = []
ListDatabaseSchemas = []
ListDatabases = []
ListDatastores = []
ListDbBackups = []
ListDbFlavors = []
ListDbUsers = []
ListEpsQuotas = []
ListFlavors = []
ListGaussDbDatastores = []
ListHistoryOperations = []
ListInstanceTags = []
ListInstances = []
ListInstancesDetails = []
ListParamGroupTemplates = []
ListPredefinedTags = []
ListProjectTags = []
ListRecycleInstances = []
ListRestorableInstances = []
ListRestoreTimes = []
ListStorageTypes = []
ListTasks = []
ModifyEpsQuota = []
ResetConfiguration = []
ResetPwd = []
ResizeInstanceFlavor = []
RestartInstance = []
RunInstanceAction = []
SetBackupPolicy = []
SetDbUserPwd = []
SetRecyclePolicy = []
ShowBackupPolicy = []
ShowBalanceStatus = []
ShowConfigurationDetail = []
ShowDeploymentForm = []
ShowInstanceConfiguration = []
ShowInstanceDisk = []
ShowInstanceParamGroup = []
ShowInstanceSnapshot = []
ShowJobDetail = []
ShowProjectQuotas = []
ShowRecyclePolicy = []
ShowSslCertDownloadLink = []
SwitchConfiguration = []
SwitchShard = []
UpdateInstanceConfiguration = []
UpdateInstanceName = []
ValidateParaGroupName = []
ValidateWeakPassword = []
full = ["AddInstanceTags", "AllowDbPrivileges", "AttachEip", "CopyConfiguration", "CreateConfigurationTemplate", "CreateDatabase", "CreateDatabaseSchemas", "CreateDbInstance", "CreateDbUser", "CreateInstance", "CreateManualBackup", "CreateRestoreInstance", "DeleteConfiguration", "DeleteDatabase", "DeleteInstance", "DeleteJob", "DeleteManualBackup", "DownloadBackup", "ListApplicableInstances", "ListAppliedHistories", "ListAvailableFlavors", "ListBackups", "ListBindedEips", "ListComponentInfos", "ListConfigurations", "ListConfigurationsDiff", "ListDatabases", "ListDatabaseSchemas", "ListDatastores", "ListDbBackups", "ListDbFlavors", "ListDbUsers", "ListEpsQuotas", "ListFlavors", "ListGaussDbDatastores", "ListHistoryOperations", "ListInstances", "ListInstancesDetails", "ListInstanceTags", "ListParamGroupTemplates", "ListPredefinedTags", "ListProjectTags", "ListRecycleInstances", "ListRestorableInstances", "ListRestoreTimes", "ListStorageTypes", "ListTasks", "ModifyEpsQuota", "ResetConfiguration", "ResetPwd", "ResizeInstanceFlavor", "RestartInstance", "RunInstanceAction", "SetBackupPolicy", "SetDbUserPwd", "SetRecyclePolicy", "ShowBackupPolicy", "ShowBalanceStatus", "ShowConfigurationDetail", "ShowDeploymentForm", "ShowInstanceConfiguration", "ShowInstanceDisk", "ShowInstanceParamGroup", "ShowInstanceSnapshot", "ShowJobDetail", "ShowProjectQuotas", "ShowRecyclePolicy", "ShowSslCertDownloadLink", "SwitchConfiguration", "SwitchShard", "UpdateInstanceConfiguration", "UpdateInstanceName", "ValidateParaGroupName", "ValidateWeakPassword"]

[lib]
name = "huawei_cloud_api_definitions_GaussDBforopenGauss"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-GaussDBforopenGauss"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
