#[cfg(feature = "ApplyExecutionPlan")]
pub mod ApplyExecutionPlan;
#[cfg(feature = "ContinueDeployStack")]
pub mod ContinueDeployStack;
#[cfg(feature = "ContinueRollbackStack")]
pub mod ContinueRollbackStack;
#[cfg(feature = "CreateExecutionPlan")]
pub mod CreateExecutionPlan;
#[cfg(feature = "CreatePrivateHook")]
pub mod CreatePrivateHook;
#[cfg(feature = "CreatePrivateHookVersion")]
pub mod CreatePrivateHookVersion;
#[cfg(feature = "CreatePrivateModule")]
pub mod CreatePrivateModule;
#[cfg(feature = "CreatePrivateModuleVersion")]
pub mod CreatePrivateModuleVersion;
#[cfg(feature = "CreatePrivateProvider")]
pub mod CreatePrivateProvider;
#[cfg(feature = "CreatePrivateProviderVersion")]
pub mod CreatePrivateProviderVersion;
#[cfg(feature = "CreateStack")]
pub mod CreateStack;
#[cfg(feature = "CreateStackInstance")]
pub mod CreateStackInstance;
#[cfg(feature = "CreateStackSet")]
pub mod CreateStackSet;
#[cfg(feature = "CreateTemplate")]
pub mod CreateTemplate;
#[cfg(feature = "CreateTemplateVersion")]
pub mod CreateTemplateVersion;
#[cfg(feature = "DeleteExecutionPlan")]
pub mod DeleteExecutionPlan;
#[cfg(feature = "DeletePrivateHook")]
pub mod DeletePrivateHook;
#[cfg(feature = "DeletePrivateHookVersion")]
pub mod DeletePrivateHookVersion;
#[cfg(feature = "DeletePrivateModule")]
pub mod DeletePrivateModule;
#[cfg(feature = "DeletePrivateModuleVersion")]
pub mod DeletePrivateModuleVersion;
#[cfg(feature = "DeletePrivateProvider")]
pub mod DeletePrivateProvider;
#[cfg(feature = "DeletePrivateProviderVersion")]
pub mod DeletePrivateProviderVersion;
#[cfg(feature = "DeleteStack")]
pub mod DeleteStack;
#[cfg(feature = "DeleteStackEnhanced")]
pub mod DeleteStackEnhanced;
#[cfg(feature = "DeleteStackInstance")]
pub mod DeleteStackInstance;
#[cfg(feature = "DeleteStackInstanceDeprecated")]
pub mod DeleteStackInstanceDeprecated;
#[cfg(feature = "DeleteStackSet")]
pub mod DeleteStackSet;
#[cfg(feature = "DeleteTemplate")]
pub mod DeleteTemplate;
#[cfg(feature = "DeleteTemplateVersion")]
pub mod DeleteTemplateVersion;
#[cfg(feature = "DeployStack")]
pub mod DeployStack;
#[cfg(feature = "DeployStackSet")]
pub mod DeployStackSet;
#[cfg(feature = "EstimateExecutionPlanPrice")]
pub mod EstimateExecutionPlanPrice;
#[cfg(feature = "GetExecutionPlan")]
pub mod GetExecutionPlan;
#[cfg(feature = "GetExecutionPlanMetadata")]
pub mod GetExecutionPlanMetadata;
#[cfg(feature = "GetStackMetadata")]
pub mod GetStackMetadata;
#[cfg(feature = "GetStackTemplate")]
pub mod GetStackTemplate;
#[cfg(feature = "ListExecutionPlans")]
pub mod ListExecutionPlans;
#[cfg(feature = "ListPrivateHooks")]
pub mod ListPrivateHooks;
#[cfg(feature = "ListPrivateHookVersions")]
pub mod ListPrivateHookVersions;
#[cfg(feature = "ListPrivateModules")]
pub mod ListPrivateModules;
#[cfg(feature = "ListPrivateModuleVersions")]
pub mod ListPrivateModuleVersions;
#[cfg(feature = "ListPrivateProviders")]
pub mod ListPrivateProviders;
#[cfg(feature = "ListPrivateProviderVersions")]
pub mod ListPrivateProviderVersions;
#[cfg(feature = "ListStackEvents")]
pub mod ListStackEvents;
#[cfg(feature = "ListStackInstances")]
pub mod ListStackInstances;
#[cfg(feature = "ListStackOutputs")]
pub mod ListStackOutputs;
#[cfg(feature = "ListStackResources")]
pub mod ListStackResources;
#[cfg(feature = "ListStacks")]
pub mod ListStacks;
#[cfg(feature = "ListStackSetOperations")]
pub mod ListStackSetOperations;
#[cfg(feature = "ListStackSets")]
pub mod ListStackSets;
#[cfg(feature = "ListTemplates")]
pub mod ListTemplates;
#[cfg(feature = "ListTemplateVersions")]
pub mod ListTemplateVersions;
#[cfg(feature = "ParseTemplateVariables")]
pub mod ParseTemplateVariables;
#[cfg(feature = "ShowPrivateHookMetadata")]
pub mod ShowPrivateHookMetadata;
#[cfg(feature = "ShowPrivateHookVersionMetadata")]
pub mod ShowPrivateHookVersionMetadata;
#[cfg(feature = "ShowPrivateHookVersionPolicy")]
pub mod ShowPrivateHookVersionPolicy;
#[cfg(feature = "ShowPrivateModuleMetadata")]
pub mod ShowPrivateModuleMetadata;
#[cfg(feature = "ShowPrivateModuleVersionContent")]
pub mod ShowPrivateModuleVersionContent;
#[cfg(feature = "ShowPrivateModuleVersionMetadata")]
pub mod ShowPrivateModuleVersionMetadata;
#[cfg(feature = "ShowPrivateProviderMetadata")]
pub mod ShowPrivateProviderMetadata;
#[cfg(feature = "ShowPrivateProviderVersionMetadata")]
pub mod ShowPrivateProviderVersionMetadata;
#[cfg(feature = "ShowStackInstance")]
pub mod ShowStackInstance;
#[cfg(feature = "ShowStackSetMetadata")]
pub mod ShowStackSetMetadata;
#[cfg(feature = "ShowStackSetOperationMetadata")]
pub mod ShowStackSetOperationMetadata;
#[cfg(feature = "ShowStackSetTemplate")]
pub mod ShowStackSetTemplate;
#[cfg(feature = "ShowTemplateMetadata")]
pub mod ShowTemplateMetadata;
#[cfg(feature = "ShowTemplateVersionContent")]
pub mod ShowTemplateVersionContent;
#[cfg(feature = "ShowTemplateVersionMetadata")]
pub mod ShowTemplateVersionMetadata;
#[cfg(feature = "UpdatePrivateHookMetadata")]
pub mod UpdatePrivateHookMetadata;
#[cfg(feature = "UpdatePrivateModuleMetadata")]
pub mod UpdatePrivateModuleMetadata;
#[cfg(feature = "UpdatePrivateProviderMetadata")]
pub mod UpdatePrivateProviderMetadata;
#[cfg(feature = "UpdateStack")]
pub mod UpdateStack;
#[cfg(feature = "UpdateStackSet")]
pub mod UpdateStackSet;
#[cfg(feature = "UpdateTemplateMetadata")]
pub mod UpdateTemplateMetadata;
