#[cfg(feature = "AbortMultipartUpload")]
pub mod AbortMultipartUpload;
#[cfg(feature = "AppendObject")]
pub mod AppendObject;
#[cfg(feature = "CheckBucketOptions")]
pub mod CheckBucketOptions;
#[cfg(feature = "CheckObjectOptions")]
pub mod CheckObjectOptions;
#[cfg(feature = "CompleteMultipartUpload")]
pub mod CompleteMultipartUpload;
#[cfg(feature = "CopyObject")]
pub mod CopyObject;
#[cfg(feature = "CopyPart")]
pub mod CopyPart;
#[cfg(feature = "CreateBucket")]
pub mod CreateBucket;
#[cfg(feature = "DeleteBucket")]
pub mod DeleteBucket;
#[cfg(feature = "DeleteBucketCors")]
pub mod DeleteBucketCors;
#[cfg(feature = "DeleteBucketCustomdomain")]
pub mod DeleteBucketCustomdomain;
#[cfg(feature = "DeleteBucketEncryption")]
pub mod DeleteBucketEncryption;
#[cfg(feature = "DeleteBucketInventory")]
pub mod DeleteBucketInventory;
#[cfg(feature = "DeleteBucketLifecycle")]
pub mod DeleteBucketLifecycle;
#[cfg(feature = "DeleteBucketMirrorBackToSource")]
pub mod DeleteBucketMirrorBackToSource;
#[cfg(feature = "DeleteBucketObsCompressPolicy")]
pub mod DeleteBucketObsCompressPolicy;
#[cfg(feature = "DeleteBucketPolicy")]
pub mod DeleteBucketPolicy;
#[cfg(feature = "DeleteBucketReplication")]
pub mod DeleteBucketReplication;
#[cfg(feature = "DeleteBucketTagging")]
pub mod DeleteBucketTagging;
#[cfg(feature = "DeleteBucketWebsite")]
pub mod DeleteBucketWebsite;
#[cfg(feature = "DeleteDirectcoldaccess")]
pub mod DeleteDirectcoldaccess;
#[cfg(feature = "DeleteObject")]
pub mod DeleteObject;
#[cfg(feature = "DeleteObjects")]
pub mod DeleteObjects;
#[cfg(feature = "GetBucketAcl")]
pub mod GetBucketAcl;
#[cfg(feature = "GetBucketCors")]
pub mod GetBucketCors;
#[cfg(feature = "GetBucketCustomdomain")]
pub mod GetBucketCustomdomain;
#[cfg(feature = "GetBucketEncryption")]
pub mod GetBucketEncryption;
#[cfg(feature = "GetBucketInventory")]
pub mod GetBucketInventory;
#[cfg(feature = "GetBucketLifecycle")]
pub mod GetBucketLifecycle;
#[cfg(feature = "GetBucketLocation")]
pub mod GetBucketLocation;
#[cfg(feature = "GetBucketLogging")]
pub mod GetBucketLogging;
#[cfg(feature = "GetBucketMetadata")]
pub mod GetBucketMetadata;
#[cfg(feature = "GetBucketMirrorBackToSource")]
pub mod GetBucketMirrorBackToSource;
#[cfg(feature = "GetBucketNotification")]
pub mod GetBucketNotification;
#[cfg(feature = "GetBucketObsCompressPolicy")]
pub mod GetBucketObsCompressPolicy;
#[cfg(feature = "GetBucketPolicy")]
pub mod GetBucketPolicy;
#[cfg(feature = "GetBucketQuota")]
pub mod GetBucketQuota;
#[cfg(feature = "GetBucketReplication")]
pub mod GetBucketReplication;
#[cfg(feature = "GetBucketStorageInfo")]
pub mod GetBucketStorageInfo;
#[cfg(feature = "GetBucketStoragePolicy")]
pub mod GetBucketStoragePolicy;
#[cfg(feature = "GetBucketTagging")]
pub mod GetBucketTagging;
#[cfg(feature = "GetBucketVersioning")]
pub mod GetBucketVersioning;
#[cfg(feature = "GetBucketWebsite")]
pub mod GetBucketWebsite;
#[cfg(feature = "GetDirectcoldaccess")]
pub mod GetDirectcoldaccess;
#[cfg(feature = "GetObject")]
pub mod GetObject;
#[cfg(feature = "GetObjectAcl")]
pub mod GetObjectAcl;
#[cfg(feature = "GetObjectMetadata")]
pub mod GetObjectMetadata;
#[cfg(feature = "InitiateMultipartUpload")]
pub mod InitiateMultipartUpload;
#[cfg(feature = "ListBucketInventory")]
pub mod ListBucketInventory;
#[cfg(feature = "ListBuckets")]
pub mod ListBuckets;
#[cfg(feature = "ListMultipartUploads")]
pub mod ListMultipartUploads;
#[cfg(feature = "ListObjects")]
pub mod ListObjects;
#[cfg(feature = "ListParts")]
pub mod ListParts;
#[cfg(feature = "ListVersions")]
pub mod ListVersions;
#[cfg(feature = "PutObject")]
pub mod PutObject;
#[cfg(feature = "RenameObject")]
pub mod RenameObject;
#[cfg(feature = "RestoreObject")]
pub mod RestoreObject;
#[cfg(feature = "SetBucketAcl")]
pub mod SetBucketAcl;
#[cfg(feature = "SetBucketCors")]
pub mod SetBucketCors;
#[cfg(feature = "SetBucketCustomedomain")]
pub mod SetBucketCustomedomain;
#[cfg(feature = "SetBucketEncryption")]
pub mod SetBucketEncryption;
#[cfg(feature = "SetBucketInventory")]
pub mod SetBucketInventory;
#[cfg(feature = "SetBucketLifecycle")]
pub mod SetBucketLifecycle;
#[cfg(feature = "SetBucketLogging")]
pub mod SetBucketLogging;
#[cfg(feature = "SetBucketMirrorBackToSource")]
pub mod SetBucketMirrorBackToSource;
#[cfg(feature = "SetBucketNotification")]
pub mod SetBucketNotification;
#[cfg(feature = "SetBucketObsCompressPolicy")]
pub mod SetBucketObsCompressPolicy;
#[cfg(feature = "SetBucketPolicy")]
pub mod SetBucketPolicy;
#[cfg(feature = "SetBucketQuota")]
pub mod SetBucketQuota;
#[cfg(feature = "SetBucketReplication")]
pub mod SetBucketReplication;
#[cfg(feature = "SetBucketStoragePolicy")]
pub mod SetBucketStoragePolicy;
#[cfg(feature = "SetBucketTagging")]
pub mod SetBucketTagging;
#[cfg(feature = "SetBucketVersioning")]
pub mod SetBucketVersioning;
#[cfg(feature = "SetBucketWebsite")]
pub mod SetBucketWebsite;
#[cfg(feature = "SetDirectcoldaccess")]
pub mod SetDirectcoldaccess;
#[cfg(feature = "SetObjectAcl")]
pub mod SetObjectAcl;
#[cfg(feature = "SetObjectMetadata")]
pub mod SetObjectMetadata;
#[cfg(feature = "TruncateObject")]
pub mod TruncateObject;
#[cfg(feature = "UploadModifyObject")]
pub mod UploadModifyObject;
#[cfg(feature = "UploadObject")]
pub mod UploadObject;
#[cfg(feature = "UploadPart")]
pub mod UploadPart;
