#[cfg(feature = "CreateEdgeSite")]
pub mod CreateEdgeSite;
#[cfg(feature = "DeleteEdgeSite")]
pub mod DeleteEdgeSite;
#[cfg(feature = "ListEdgeSiteMetrics")]
pub mod ListEdgeSiteMetrics;
#[cfg(feature = "ListEdgeSites")]
pub mod ListEdgeSites;
#[cfg(feature = "ListQuotas")]
pub mod ListQuotas;
#[cfg(feature = "ListRacks")]
pub mod ListRacks;
#[cfg(feature = "ListStoragePools")]
pub mod ListStoragePools;
#[cfg(feature = "ListSupportedRegions")]
pub mod ListSupportedRegions;
#[cfg(feature = "ListSupportedZones")]
pub mod ListSupportedZones;
#[cfg(feature = "ShowEdgeSite")]
pub mod ShowEdgeSite;
#[cfg(feature = "ShowRack")]
pub mod ShowRack;
#[cfg(feature = "ShowStoragePool")]
pub mod ShowStoragePool;
#[cfg(feature = "UpdateEdgeSite")]
pub mod UpdateEdgeSite;
