#[cfg(feature = "CreateEdgeSite")]
pub mod CreateEdgeSite;
#[cfg(feature = "DeleteEdgeSite")]
pub mod DeleteEdgeSite;
#[cfg(feature = "ListEdgeSiteMetrics")]
pub mod ListEdgeSiteMetrics;
#[cfg(feature = "ListEdgeSites")]
pub mod ListEdgeSites;
#[cfg(feature = "ListNetworkDeviceOfferings")]
pub mod ListNetworkDeviceOfferings;
#[cfg(feature = "ListNetworkDevices")]
pub mod ListNetworkDevices;
#[cfg(feature = "ListQuotas")]
pub mod ListQuotas;
#[cfg(feature = "ListRacks")]
pub mod ListRacks;
#[cfg(feature = "ListSaleCycles")]
pub mod ListSaleCycles;
#[cfg(feature = "ListServerOfferings")]
pub mod ListServerOfferings;
#[cfg(feature = "ListServers")]
pub mod ListServers;
#[cfg(feature = "ListStorageGears")]
pub mod ListStorageGears;
#[cfg(feature = "ListStoragePools")]
pub mod ListStoragePools;
#[cfg(feature = "ListStorageTypes")]
pub mod ListStorageTypes;
#[cfg(feature = "ListSupportedRegions")]
pub mod ListSupportedRegions;
#[cfg(feature = "ListSupportedZones")]
pub mod ListSupportedZones;
#[cfg(feature = "ShowEdgeSite")]
pub mod ShowEdgeSite;
#[cfg(feature = "ShowNetworkDevice")]
pub mod ShowNetworkDevice;
#[cfg(feature = "ShowRack")]
pub mod ShowRack;
#[cfg(feature = "ShowServer")]
pub mod ShowServer;
#[cfg(feature = "ShowStoragePool")]
pub mod ShowStoragePool;
#[cfg(feature = "UpdateEdgeSite")]
pub mod UpdateEdgeSite;
