#[cfg(feature = "AddReadonlyNode")]
pub mod AddReadonlyNode;
#[cfg(feature = "AddShardingNode")]
pub mod AddShardingNode;
#[cfg(feature = "AttachEip")]
pub mod AttachEip;
#[cfg(feature = "AttachInternalIp")]
pub mod AttachInternalIp;
#[cfg(feature = "BatchTagAction")]
pub mod BatchTagAction;
#[cfg(feature = "CancelEip")]
pub mod CancelEip;
#[cfg(feature = "ChangeOpsWindow")]
pub mod ChangeOpsWindow;
#[cfg(feature = "CheckPassword")]
pub mod CheckPassword;
#[cfg(feature = "CheckWeakPassword")]
pub mod CheckWeakPassword;
#[cfg(feature = "CompareConfiguration")]
pub mod CompareConfiguration;
#[cfg(feature = "CopyConfiguration")]
pub mod CopyConfiguration;
#[cfg(feature = "CreateConfiguration")]
pub mod CreateConfiguration;
#[cfg(feature = "CreateDatabaseRole")]
pub mod CreateDatabaseRole;
#[cfg(feature = "CreateDatabaseUser")]
pub mod CreateDatabaseUser;
#[cfg(feature = "CreateInstance")]
pub mod CreateInstance;
#[cfg(feature = "CreateIp")]
pub mod CreateIp;
#[cfg(feature = "CreateKillOpRule")]
pub mod CreateKillOpRule;
#[cfg(feature = "CreateManualBackup")]
pub mod CreateManualBackup;
#[cfg(feature = "DeleteAuditLog")]
pub mod DeleteAuditLog;
#[cfg(feature = "DeleteConfiguration")]
pub mod DeleteConfiguration;
#[cfg(feature = "DeleteDatabaseRole")]
pub mod DeleteDatabaseRole;
#[cfg(feature = "DeleteDatabaseUser")]
pub mod DeleteDatabaseUser;
#[cfg(feature = "DeleteInstance")]
pub mod DeleteInstance;
#[cfg(feature = "DeleteKillOpRuleList")]
pub mod DeleteKillOpRuleList;
#[cfg(feature = "DeleteLtsConfig")]
pub mod DeleteLtsConfig;
#[cfg(feature = "DeleteManualBackup")]
pub mod DeleteManualBackup;
#[cfg(feature = "DeleteReadonlyNode")]
pub mod DeleteReadonlyNode;
#[cfg(feature = "DeleteSession")]
pub mod DeleteSession;
#[cfg(feature = "DownloadErrorlog")]
pub mod DownloadErrorlog;
#[cfg(feature = "DownloadSlowlog")]
pub mod DownloadSlowlog;
#[cfg(feature = "ExpandReplicasetNode")]
pub mod ExpandReplicasetNode;
#[cfg(feature = "ListApiVersion")]
pub mod ListApiVersion;
#[cfg(feature = "ListAppliedInstances")]
pub mod ListAppliedInstances;
#[cfg(feature = "ListAuditlogLinks")]
pub mod ListAuditlogLinks;
#[cfg(feature = "ListAuditlogs")]
pub mod ListAuditlogs;
#[cfg(feature = "ListAz2Migrate")]
pub mod ListAz2Migrate;
#[cfg(feature = "ListBackups")]
pub mod ListBackups;
#[cfg(feature = "ListConfigurations")]
pub mod ListConfigurations;
#[cfg(feature = "ListDatabaseRoles")]
pub mod ListDatabaseRoles;
#[cfg(feature = "ListDatabaseUsers")]
pub mod ListDatabaseUsers;
#[cfg(feature = "ListDatastoreVersions")]
pub mod ListDatastoreVersions;
#[cfg(feature = "ListErrorLogs")]
pub mod ListErrorLogs;
#[cfg(feature = "ListFlavorInfos")]
pub mod ListFlavorInfos;
#[cfg(feature = "ListFlavors")]
pub mod ListFlavors;
#[cfg(feature = "ListInstances")]
pub mod ListInstances;
#[cfg(feature = "ListInstancesByTags")]
pub mod ListInstancesByTags;
#[cfg(feature = "ListInstanceTags")]
pub mod ListInstanceTags;
#[cfg(feature = "ListLtsConfigs")]
pub mod ListLtsConfigs;
#[cfg(feature = "ListLtsErrorLogs")]
pub mod ListLtsErrorLogs;
#[cfg(feature = "ListLtsSlowLogs")]
pub mod ListLtsSlowLogs;
#[cfg(feature = "ListProjectTags")]
pub mod ListProjectTags;
#[cfg(feature = "ListRecycleInstances")]
pub mod ListRecycleInstances;
#[cfg(feature = "ListRestoreCollections")]
pub mod ListRestoreCollections;
#[cfg(feature = "ListRestoreDatabases")]
pub mod ListRestoreDatabases;
#[cfg(feature = "ListRestoreTimes")]
pub mod ListRestoreTimes;
#[cfg(feature = "ListSessions")]
pub mod ListSessions;
#[cfg(feature = "ListSlowLogs")]
pub mod ListSlowLogs;
#[cfg(feature = "ListSslCertDownloadAddress")]
pub mod ListSslCertDownloadAddress;
#[cfg(feature = "ListStorageType")]
pub mod ListStorageType;
#[cfg(feature = "ListTasks")]
pub mod ListTasks;
#[cfg(feature = "MigrateAz")]
pub mod MigrateAz;
#[cfg(feature = "ResetConfiguration")]
pub mod ResetConfiguration;
#[cfg(feature = "ResetPassword")]
pub mod ResetPassword;
#[cfg(feature = "ResizeInstance")]
pub mod ResizeInstance;
#[cfg(feature = "ResizeInstanceVolume")]
pub mod ResizeInstanceVolume;
#[cfg(feature = "RestartInstance")]
pub mod RestartInstance;
#[cfg(feature = "RestoreInstance")]
pub mod RestoreInstance;
#[cfg(feature = "RestoreInstanceFromCollection")]
pub mod RestoreInstanceFromCollection;
#[cfg(feature = "RestoreNewInstance")]
pub mod RestoreNewInstance;
#[cfg(feature = "SetAuditlogPolicy")]
pub mod SetAuditlogPolicy;
#[cfg(feature = "SetBackupPolicy")]
pub mod SetBackupPolicy;
#[cfg(feature = "SetBalancerSwitch")]
pub mod SetBalancerSwitch;
#[cfg(feature = "SetBalancerWindow")]
pub mod SetBalancerWindow;
#[cfg(feature = "SetRecyclePolicy")]
pub mod SetRecyclePolicy;
#[cfg(feature = "ShowApiVersion")]
pub mod ShowApiVersion;
#[cfg(feature = "ShowAuditlogPolicy")]
pub mod ShowAuditlogPolicy;
#[cfg(feature = "ShowBackupDownloadLink")]
pub mod ShowBackupDownloadLink;
#[cfg(feature = "ShowBackupPolicy")]
pub mod ShowBackupPolicy;
#[cfg(feature = "ShowClientNetwork")]
pub mod ShowClientNetwork;
#[cfg(feature = "ShowConfigurationAppliedHistory")]
pub mod ShowConfigurationAppliedHistory;
#[cfg(feature = "ShowConfigurationModifyHistory")]
pub mod ShowConfigurationModifyHistory;
#[cfg(feature = "ShowConfigurationParameter")]
pub mod ShowConfigurationParameter;
#[cfg(feature = "ShowConnectionStatistics")]
pub mod ShowConnectionStatistics;
#[cfg(feature = "ShowDiskUsage")]
pub mod ShowDiskUsage;
#[cfg(feature = "ShowEntityConfiguration")]
pub mod ShowEntityConfiguration;
#[cfg(feature = "ShowJobDetail")]
pub mod ShowJobDetail;
#[cfg(feature = "ShowKillOpRuleRuleList")]
pub mod ShowKillOpRuleRuleList;
#[cfg(feature = "ShowQuotas")]
pub mod ShowQuotas;
#[cfg(feature = "ShowRecyclePolicy")]
pub mod ShowRecyclePolicy;
#[cfg(feature = "ShowReplSetName")]
pub mod ShowReplSetName;
#[cfg(feature = "ShowSecondLevelMonitoringStatus")]
pub mod ShowSecondLevelMonitoringStatus;
#[cfg(feature = "ShowShardingBalancer")]
pub mod ShowShardingBalancer;
#[cfg(feature = "ShowSlowlogDesensitizationSwitch")]
pub mod ShowSlowlogDesensitizationSwitch;
#[cfg(feature = "ShowUpgradeDuration")]
pub mod ShowUpgradeDuration;
#[cfg(feature = "ShrinkInstanceNodes")]
pub mod ShrinkInstanceNodes;
#[cfg(feature = "StopBackup")]
pub mod StopBackup;
#[cfg(feature = "SwitchConfiguration")]
pub mod SwitchConfiguration;
#[cfg(feature = "SwitchInstancePrimary")]
pub mod SwitchInstancePrimary;
#[cfg(feature = "SwitchoverReplicaSet")]
pub mod SwitchoverReplicaSet;
#[cfg(feature = "SwitchSecondLevelMonitoring")]
pub mod SwitchSecondLevelMonitoring;
