[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
CancelAssetTranscodeTask = []
CancelExtractAudioTask = []
CheckMd5Duplication = []
ConfirmAssetUpload = []
ConfirmImageUpload = []
CreateAssetByFileUpload = []
CreateAssetCategory = []
CreateAssetProcessTask = []
CreateAssetReviewTask = []
CreateExtractAudioTask = []
CreatePreheatingAsset = []
CreateTakeOverTask = []
CreateTemplateGroup = []
CreateTemplateGroupCollection = []
CreateTranscodeTemplate = []
CreateWatermarkTemplate = []
DeleteAssetCategory = []
DeleteAssets = []
DeleteTemplateGroup = []
DeleteTemplateGroupCollection = []
DeleteTranscodeTemplate = []
DeleteWatermarkTemplate = []
ListAssetCategory = []
ListAssetDailySummaryLog = []
ListAssetList = []
ListDomainLogs = []
ListTakeOverTask = []
ListTemplateGroup = []
ListTemplateGroupCollection = []
ListTopStatistics = []
ListTranscodeTemplate = []
ListWatermarkTemplate = []
PublishAssetFromObs = []
PublishAssets = []
ShowAssetCipher = []
ShowAssetDetail = []
ShowAssetMeta = []
ShowAssetTempAuthority = []
ShowCdnStatistics = []
ShowPreheatingAsset = []
ShowTakeOverAssetDetails = []
ShowTakeOverTaskDetails = []
ShowVodRetrieval = []
ShowVodStatistics = []
UnpublishAssets = []
UpdateAsset = []
UpdateAssetCategory = []
UpdateAssetMeta = []
UpdateBucketAuthorized = []
UpdateCoverByThumbnail = []
UpdateStorageMode = []
UpdateTemplateGroup = []
UpdateTemplateGroupCollection = []
UpdateTranscodeTemplate = []
UpdateWatermarkTemplate = []
UploadMetaDataByUrl = []
full = ["CancelAssetTranscodeTask", "CancelExtractAudioTask", "CheckMd5Duplication", "ConfirmAssetUpload", "ConfirmImageUpload", "CreateAssetByFileUpload", "CreateAssetCategory", "CreateAssetProcessTask", "CreateAssetReviewTask", "CreateExtractAudioTask", "CreatePreheatingAsset", "CreateTakeOverTask", "CreateTemplateGroup", "CreateTemplateGroupCollection", "CreateTranscodeTemplate", "CreateWatermarkTemplate", "DeleteAssetCategory", "DeleteAssets", "DeleteTemplateGroup", "DeleteTemplateGroupCollection", "DeleteTranscodeTemplate", "DeleteWatermarkTemplate", "ListAssetCategory", "ListAssetDailySummaryLog", "ListAssetList", "ListDomainLogs", "ListTakeOverTask", "ListTemplateGroup", "ListTemplateGroupCollection", "ListTopStatistics", "ListTranscodeTemplate", "ListWatermarkTemplate", "PublishAssetFromObs", "PublishAssets", "ShowAssetCipher", "ShowAssetDetail", "ShowAssetMeta", "ShowAssetTempAuthority", "ShowCdnStatistics", "ShowPreheatingAsset", "ShowTakeOverAssetDetails", "ShowTakeOverTaskDetails", "ShowVodRetrieval", "ShowVodStatistics", "UnpublishAssets", "UpdateAsset", "UpdateAssetCategory", "UpdateAssetMeta", "UpdateBucketAuthorized", "UpdateCoverByThumbnail", "UpdateStorageMode", "UpdateTemplateGroup", "UpdateTemplateGroupCollection", "UpdateTranscodeTemplate", "UpdateWatermarkTemplate", "UploadMetaDataByUrl"]

[lib]
name = "huawei_cloud_api_definitions_VOD"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-VOD"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
