[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddDatabasePermission = []
BatchTagAction = []
CancelGaussMySqlInstanceEip = []
CancelScheduleTask = []
ChangeGaussMySqlInstanceSpecification = []
ChangeGaussMySqlProxySpecification = []
CheckDataBaseConfig = []
CheckResource = []
CheckStarRocksResource = []
CheckTableConfig = []
CopyConfigurations = []
CopyInstanceConfigurations = []
CreateAccessControl = []
CreateGaussMySqlBackup = []
CreateGaussMySqlConfiguration = []
CreateGaussMySqlDatabase = []
CreateGaussMySqlDatabaseUser = []
CreateGaussMySqlInstance = []
CreateGaussMySqlProxy = []
CreateGaussMySqlReadonlyNode = []
CreateGaussMysqlDns = []
CreateRestoreTables = []
CreateStarRocksDataReplication = []
CreateStarRocksDatabaseUser = []
CreateStarrocksInstance = []
DeleteDatabasePermission = []
DeleteGaussMySqlBackup = []
DeleteGaussMySqlConfiguration = []
DeleteGaussMySqlDatabase = []
DeleteGaussMySqlDatabaseUser = []
DeleteGaussMySqlInstance = []
DeleteGaussMySqlProxy = []
DeleteGaussMySqlReadonlyNode = []
DeleteScheduleTasK = []
DeleteSqlFilterRule = []
DeleteStarRocksDataReplication = []
DeleteStarRocksDatabaseUser = []
DeleteStarrocksInstance = []
DeleteTaskRecord = []
DescribeBackupEncryptStatus = []
ExpandGaussMySqlInstanceVolume = []
ExpandGaussMySqlProxy = []
InvokeGaussMySqlInstanceSwitchOver = []
ListAuditLogDownloadLink = []
ListConfigurationsDifferences = []
ListConfigurationsInstances = []
ListEnterpriseProjects = []
ListGaussMySqlConfigurations = []
ListGaussMySqlDatabase = []
ListGaussMySqlDatabaseCharsets = []
ListGaussMySqlDatabaseUser = []
ListGaussMySqlDedicatedResources = []
ListGaussMySqlInstanceDetailInfo = []
ListGaussMySqlInstanceDetailInfoUnifyStatus = []
ListGaussMySqlInstances = []
ListGaussMySqlInstancesUnifyStatus = []
ListHtapDataStore = []
ListHtapFlavor = []
ListHtapInstanceInfo = []
ListHtapStorageType = []
ListImmediateJobs = []
ListInstanceConfigurations = []
ListInstanceTags = []
ListLtsErrorLogDetails = []
ListLtsSlowlogDetails = []
ListModifyHistory = []
ListProjectTags = []
ListScheduleJobs = []
ListStarRocksDataBases = []
ListStarRocksDataReplicationConfig = []
ListStarRocksDataReplications = []
ListStarRocksDbParameters = []
ListStarrocksInstanceInfo = []
ModifyBackupEncryptStatus = []
ModifyGaussMySqlProxyRouteMode = []
ModifyGaussMysqlDns = []
ResetGaussMySqlDatabasePassword = []
ResetGaussMySqlPassword = []
RestartGaussMySqlInstance = []
RestartGaussMySqlNode = []
RestartStarrocksInstance = []
RestartStarrocksNode = []
RestoreOldInstance = []
SetGaussMySqlProxyWeight = []
SetGaussMySqlQuotas = []
SetSqlFilterRule = []
ShowAuditLog = []
ShowAutoScalingPolicy = []
ShowBackupRestoreTime = []
ShowDedicatedResourceInfo = []
ShowGaussMySqlBackupList = []
ShowGaussMySqlBackupPolicy = []
ShowGaussMySqlConfiguration = []
ShowGaussMySqlEngineVersion = []
ShowGaussMySqlFlavors = []
ShowGaussMySqlIncrementalBackupList = []
ShowGaussMySqlInstanceInfo = []
ShowGaussMySqlInstanceInfoUnifyStatus = []
ShowGaussMySqlJobInfo = []
ShowGaussMySqlProjectQuotas = []
full = ["AddDatabasePermission", "BatchTagAction", "CancelGaussMySqlInstanceEip", "CancelScheduleTask", "ChangeGaussMySqlInstanceSpecification", "ChangeGaussMySqlProxySpecification", "CheckDataBaseConfig", "CheckResource", "CheckStarRocksResource", "CheckTableConfig", "CopyConfigurations", "CopyInstanceConfigurations", "CreateAccessControl", "CreateGaussMySqlBackup", "CreateGaussMySqlConfiguration", "CreateGaussMySqlDatabase", "CreateGaussMySqlDatabaseUser", "CreateGaussMysqlDns", "CreateGaussMySqlInstance", "CreateGaussMySqlProxy", "CreateGaussMySqlReadonlyNode", "CreateRestoreTables", "CreateStarRocksDatabaseUser", "CreateStarRocksDataReplication", "CreateStarrocksInstance", "DeleteDatabasePermission", "DeleteGaussMySqlBackup", "DeleteGaussMySqlConfiguration", "DeleteGaussMySqlDatabase", "DeleteGaussMySqlDatabaseUser", "DeleteGaussMySqlInstance", "DeleteGaussMySqlProxy", "DeleteGaussMySqlReadonlyNode", "DeleteScheduleTasK", "DeleteSqlFilterRule", "DeleteStarRocksDatabaseUser", "DeleteStarRocksDataReplication", "DeleteStarrocksInstance", "DeleteTaskRecord", "DescribeBackupEncryptStatus", "ExpandGaussMySqlInstanceVolume", "ExpandGaussMySqlProxy", "InvokeGaussMySqlInstanceSwitchOver", "ListAuditLogDownloadLink", "ListConfigurationsDifferences", "ListConfigurationsInstances", "ListEnterpriseProjects", "ListGaussMySqlConfigurations", "ListGaussMySqlDatabase", "ListGaussMySqlDatabaseCharsets", "ListGaussMySqlDatabaseUser", "ListGaussMySqlDedicatedResources", "ListGaussMySqlInstanceDetailInfo", "ListGaussMySqlInstanceDetailInfoUnifyStatus", "ListGaussMySqlInstances", "ListGaussMySqlInstancesUnifyStatus", "ListHtapDataStore", "ListHtapFlavor", "ListHtapInstanceInfo", "ListHtapStorageType", "ListImmediateJobs", "ListInstanceConfigurations", "ListInstanceTags", "ListLtsErrorLogDetails", "ListLtsSlowlogDetails", "ListModifyHistory", "ListProjectTags", "ListScheduleJobs", "ListStarRocksDataBases", "ListStarRocksDataReplicationConfig", "ListStarRocksDataReplications", "ListStarRocksDbParameters", "ListStarrocksInstanceInfo", "ModifyBackupEncryptStatus", "ModifyGaussMysqlDns", "ModifyGaussMySqlProxyRouteMode", "ResetGaussMySqlDatabasePassword", "ResetGaussMySqlPassword", "RestartGaussMySqlInstance", "RestartGaussMySqlNode", "RestartStarrocksInstance", "RestartStarrocksNode", "RestoreOldInstance", "SetGaussMySqlProxyWeight", "SetGaussMySqlQuotas", "SetSqlFilterRule", "ShowAuditLog", "ShowAutoScalingPolicy", "ShowBackupRestoreTime", "ShowDedicatedResourceInfo", "ShowGaussMySqlBackupList", "ShowGaussMySqlBackupPolicy", "ShowGaussMySqlConfiguration", "ShowGaussMySqlEngineVersion", "ShowGaussMySqlFlavors", "ShowGaussMySqlIncrementalBackupList", "ShowGaussMySqlInstanceInfo", "ShowGaussMySqlInstanceInfoUnifyStatus", "ShowGaussMySqlJobInfo", "ShowGaussMySqlProjectQuotas"]

[lib]
name = "huawei_cloud_api_definitions_GaussDB"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-GaussDB"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
