[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddDatabasePermission = []
BatchTagAction = []
CancelGaussMySqlInstanceEip = []
CancelScheduleTask = []
ChangeGaussMySqlInstanceSpecification = []
ChangeGaussMySqlProxySpecification = []
CheckResource = []
CopyConfigurations = []
CopyInstanceConfigurations = []
CreateAccessControl = []
CreateGaussMySqlBackup = []
CreateGaussMySqlConfiguration = []
CreateGaussMySqlDatabase = []
CreateGaussMySqlDatabaseUser = []
CreateGaussMySqlInstance = []
CreateGaussMySqlProxy = []
CreateGaussMySqlReadonlyNode = []
CreateGaussMysqlDns = []
CreateRestoreTables = []
DeleteDatabasePermission = []
DeleteGaussMySqlBackup = []
DeleteGaussMySqlConfiguration = []
DeleteGaussMySqlDatabase = []
DeleteGaussMySqlDatabaseUser = []
DeleteGaussMySqlInstance = []
DeleteGaussMySqlProxy = []
DeleteGaussMySqlReadonlyNode = []
DeleteScheduleTasK = []
DeleteSqlFilterRule = []
DeleteTaskRecord = []
DescribeBackupEncryptStatus = []
ExpandGaussMySqlInstanceVolume = []
ExpandGaussMySqlProxy = []
InvokeGaussMySqlInstanceSwitchOver = []
ListAuditLogDownloadLink = []
ListConfigurationsDifferences = []
ListConfigurationsInstances = []
ListEnterpriseProjects = []
ListGaussMySqlConfigurations = []
ListGaussMySqlDatabase = []
ListGaussMySqlDatabaseCharsets = []
ListGaussMySqlDatabaseUser = []
ListGaussMySqlDedicatedResources = []
ListGaussMySqlInstanceDetailInfo = []
ListGaussMySqlInstanceDetailInfoUnifyStatus = []
ListGaussMySqlInstances = []
ListGaussMySqlInstancesUnifyStatus = []
ListImmediateJobs = []
ListInstanceConfigurations = []
ListInstanceTags = []
ListLtsErrorLogDetails = []
ListLtsSlowlogDetails = []
ListModifyHistory = []
ListProjectTags = []
ListScheduleJobs = []
ModifyBackupEncryptStatus = []
ModifyGaussMySqlProxyRouteMode = []
ModifyGaussMysqlDns = []
ResetGaussMySqlDatabasePassword = []
ResetGaussMySqlPassword = []
RestartGaussMySqlInstance = []
RestartGaussMySqlNode = []
RestoreOldInstance = []
SetGaussMySqlProxyWeight = []
SetGaussMySqlQuotas = []
SetSqlFilterRule = []
ShowAuditLog = []
ShowAutoScalingPolicy = []
ShowBackupRestoreTime = []
ShowDedicatedResourceInfo = []
ShowGaussMySqlBackupList = []
ShowGaussMySqlBackupPolicy = []
ShowGaussMySqlConfiguration = []
ShowGaussMySqlEngineVersion = []
ShowGaussMySqlFlavors = []
ShowGaussMySqlIncrementalBackupList = []
ShowGaussMySqlInstanceInfo = []
ShowGaussMySqlInstanceInfoUnifyStatus = []
ShowGaussMySqlJobInfo = []
ShowGaussMySqlProjectQuotas = []
ShowGaussMySqlProxyFlavors = []
ShowGaussMySqlProxyList = []
ShowGaussMySqlQuotas = []
ShowInstanceDatabaseVersion = []
ShowInstanceMonitorExtend = []
ShowIntelligentDiagnosisAbnormalCountOfInstances = []
ShowIntelligentDiagnosisInstanceInfosPerMetric = []
ShowRestoreTables = []
ShowSqlFilterControl = []
ShowSqlFilterRule = []
ShrinkGaussMySqlProxy = []
SwitchAccessControl = []
SwitchGaussMySqlConfiguration = []
SwitchGaussMySqlInstanceSsl = []
SwitchGaussMySqlProxySsl = []
UpdateAuditLog = []
UpdateAutoScalingPolicy = []
UpdateBackupOffsitePolicy = []
UpdateGaussMySqlBackupPolicy = []
UpdateGaussMySqlConfiguration = []
full = ["AddDatabasePermission", "BatchTagAction", "CancelGaussMySqlInstanceEip", "CancelScheduleTask", "ChangeGaussMySqlInstanceSpecification", "ChangeGaussMySqlProxySpecification", "CheckResource", "CopyConfigurations", "CopyInstanceConfigurations", "CreateAccessControl", "CreateGaussMySqlBackup", "CreateGaussMySqlConfiguration", "CreateGaussMySqlDatabase", "CreateGaussMySqlDatabaseUser", "CreateGaussMysqlDns", "CreateGaussMySqlInstance", "CreateGaussMySqlProxy", "CreateGaussMySqlReadonlyNode", "CreateRestoreTables", "DeleteDatabasePermission", "DeleteGaussMySqlBackup", "DeleteGaussMySqlConfiguration", "DeleteGaussMySqlDatabase", "DeleteGaussMySqlDatabaseUser", "DeleteGaussMySqlInstance", "DeleteGaussMySqlProxy", "DeleteGaussMySqlReadonlyNode", "DeleteScheduleTasK", "DeleteSqlFilterRule", "DeleteTaskRecord", "DescribeBackupEncryptStatus", "ExpandGaussMySqlInstanceVolume", "ExpandGaussMySqlProxy", "InvokeGaussMySqlInstanceSwitchOver", "ListAuditLogDownloadLink", "ListConfigurationsDifferences", "ListConfigurationsInstances", "ListEnterpriseProjects", "ListGaussMySqlConfigurations", "ListGaussMySqlDatabase", "ListGaussMySqlDatabaseCharsets", "ListGaussMySqlDatabaseUser", "ListGaussMySqlDedicatedResources", "ListGaussMySqlInstanceDetailInfo", "ListGaussMySqlInstanceDetailInfoUnifyStatus", "ListGaussMySqlInstances", "ListGaussMySqlInstancesUnifyStatus", "ListImmediateJobs", "ListInstanceConfigurations", "ListInstanceTags", "ListLtsErrorLogDetails", "ListLtsSlowlogDetails", "ListModifyHistory", "ListProjectTags", "ListScheduleJobs", "ModifyBackupEncryptStatus", "ModifyGaussMysqlDns", "ModifyGaussMySqlProxyRouteMode", "ResetGaussMySqlDatabasePassword", "ResetGaussMySqlPassword", "RestartGaussMySqlInstance", "RestartGaussMySqlNode", "RestoreOldInstance", "SetGaussMySqlProxyWeight", "SetGaussMySqlQuotas", "SetSqlFilterRule", "ShowAuditLog", "ShowAutoScalingPolicy", "ShowBackupRestoreTime", "ShowDedicatedResourceInfo", "ShowGaussMySqlBackupList", "ShowGaussMySqlBackupPolicy", "ShowGaussMySqlConfiguration", "ShowGaussMySqlEngineVersion", "ShowGaussMySqlFlavors", "ShowGaussMySqlIncrementalBackupList", "ShowGaussMySqlInstanceInfo", "ShowGaussMySqlInstanceInfoUnifyStatus", "ShowGaussMySqlJobInfo", "ShowGaussMySqlProjectQuotas", "ShowGaussMySqlProxyFlavors", "ShowGaussMySqlProxyList", "ShowGaussMySqlQuotas", "ShowInstanceDatabaseVersion", "ShowInstanceMonitorExtend", "ShowIntelligentDiagnosisAbnormalCountOfInstances", "ShowIntelligentDiagnosisInstanceInfosPerMetric", "ShowRestoreTables", "ShowSqlFilterControl", "ShowSqlFilterRule", "ShrinkGaussMySqlProxy", "SwitchAccessControl", "SwitchGaussMySqlConfiguration", "SwitchGaussMySqlInstanceSsl", "SwitchGaussMySqlProxySsl", "UpdateAuditLog", "UpdateAutoScalingPolicy", "UpdateBackupOffsitePolicy", "UpdateGaussMySqlBackupPolicy", "UpdateGaussMySqlConfiguration"]

[lib]
name = "huawei_cloud_api_definitions_GaussDB"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-GaussDB"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "0.1.0"
