[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddDatabasePermission = []
BatchTagAction = []
CancelGaussMySqlInstanceEip = []
CancelScheduleTask = []
ChangeGaussMySqlInstanceSpecification = []
ChangeGaussMySqlProxySpecification = []
CheckClickHouseDataBaseConfig = []
CheckClickHouseTableConfig = []
CheckDataBaseConfig = []
CheckResource = []
CheckStarRocksResource = []
CheckStarrocksParams = []
CheckTableConfig = []
CopyConfigurations = []
CopyInstanceConfigurations = []
CreateAccessControl = []
CreateClickHouseDataBaseReplication = []
CreateClickHouseDatabaseUser = []
CreateClickHouseInstance = []
CreateGaussMySqlBackup = []
CreateGaussMySqlConfiguration = []
CreateGaussMySqlDatabase = []
CreateGaussMySqlDatabaseUser = []
CreateGaussMySqlInstance = []
CreateGaussMySqlProxy = []
CreateGaussMySqlReadonlyNode = []
CreateGaussMysqlDns = []
CreateLtsConfigs = []
CreateRestoreTables = []
CreateStarRocksDataReplication = []
CreateStarRocksDatabaseUser = []
CreateStarrocksInstance = []
DeleteClickHouseDataBaseConfig = []
DeleteClickHouseDataBaseReplication = []
DeleteClickHouseDatabaseUser = []
DeleteClickHouseInstance = []
DeleteClickHouseLtsConfig = []
DeleteDatabasePermission = []
DeleteGaussMySqlBackup = []
DeleteGaussMySqlConfiguration = []
DeleteGaussMySqlDatabase = []
DeleteGaussMySqlDatabaseUser = []
DeleteGaussMySqlInstance = []
DeleteGaussMySqlProxy = []
DeleteGaussMySqlReadonlyNode = []
DeleteLtsConfigs = []
DeleteScheduleTasK = []
DeleteSqlFilterRule = []
DeleteStarRocksDataReplication = []
DeleteStarRocksDatabaseUser = []
DeleteStarrocksInstance = []
DeleteTaskRecord = []
DeleteTaurusDbNodeProcesses = []
DescribeBackupEncryptStatus = []
DownloadSlowLogFile = []
ExpandGaussMySqlInstanceVolume = []
ExpandGaussMySqlProxy = []
InvokeGaussMySqlInstanceSwitchOver = []
ListAuditLogDownloadLink = []
ListClickHouseDataBase = []
ListClickHouseDataBaseParameter = []
ListClickHouseDataBaseReplication = []
ListClickHouseDataBaseReplicationConfig = []
ListClickHouseInstance = []
ListClickHouseInstanceNode = []
ListConfigurationsDifferences = []
ListConfigurationsInstances = []
ListEnterpriseProjects = []
ListGaussMySqlConfigurations = []
ListGaussMySqlDatabase = []
ListGaussMySqlDatabaseCharsets = []
ListGaussMySqlDatabaseUser = []
ListGaussMySqlDedicatedResources = []
ListGaussMySqlInstanceDetailInfo = []
ListGaussMySqlInstanceDetailInfoUnifyStatus = []
ListGaussMySqlInstances = []
ListGaussMySqlInstancesUnifyStatus = []
ListHtapDataStore = []
ListHtapFlavor = []
ListHtapInstanceInfo = []
ListHtapStorageType = []
ListImmediateJobs = []
ListInstanceConfigurations = []
ListInstanceTags = []
ListLtsErrorLogDetails = []
ListLtsSlowlogDetails = []
ListModifyHistory = []
ListParamsTemplateApplyHistory = []
ListProjectTags = []
ListRecycleInstances = []
ListScheduleJobs = []
ListStarRocksDataBases = []
ListStarRocksDataReplicationConfig = []
ListStarRocksDataReplicationConfigByDataBase = []
ListStarRocksDataReplications = []
ListStarRocksDbParameters = []
ListStarrocksInstanceInfo = []
ListTaurusDbNodeProcesses = []
ModifyBackupEncryptStatus = []
ModifyDataSync = []
full = ["AddDatabasePermission", "BatchTagAction", "CancelGaussMySqlInstanceEip", "CancelScheduleTask", "ChangeGaussMySqlInstanceSpecification", "ChangeGaussMySqlProxySpecification", "CheckClickHouseDataBaseConfig", "CheckClickHouseTableConfig", "CheckDataBaseConfig", "CheckResource", "CheckStarrocksParams", "CheckStarRocksResource", "CheckTableConfig", "CopyConfigurations", "CopyInstanceConfigurations", "CreateAccessControl", "CreateClickHouseDataBaseReplication", "CreateClickHouseDatabaseUser", "CreateClickHouseInstance", "CreateGaussMySqlBackup", "CreateGaussMySqlConfiguration", "CreateGaussMySqlDatabase", "CreateGaussMySqlDatabaseUser", "CreateGaussMysqlDns", "CreateGaussMySqlInstance", "CreateGaussMySqlProxy", "CreateGaussMySqlReadonlyNode", "CreateLtsConfigs", "CreateRestoreTables", "CreateStarRocksDatabaseUser", "CreateStarRocksDataReplication", "CreateStarrocksInstance", "DeleteClickHouseDataBaseConfig", "DeleteClickHouseDataBaseReplication", "DeleteClickHouseDatabaseUser", "DeleteClickHouseInstance", "DeleteClickHouseLtsConfig", "DeleteDatabasePermission", "DeleteGaussMySqlBackup", "DeleteGaussMySqlConfiguration", "DeleteGaussMySqlDatabase", "DeleteGaussMySqlDatabaseUser", "DeleteGaussMySqlInstance", "DeleteGaussMySqlProxy", "DeleteGaussMySqlReadonlyNode", "DeleteLtsConfigs", "DeleteScheduleTasK", "DeleteSqlFilterRule", "DeleteStarRocksDatabaseUser", "DeleteStarRocksDataReplication", "DeleteStarrocksInstance", "DeleteTaskRecord", "DeleteTaurusDbNodeProcesses", "DescribeBackupEncryptStatus", "DownloadSlowLogFile", "ExpandGaussMySqlInstanceVolume", "ExpandGaussMySqlProxy", "InvokeGaussMySqlInstanceSwitchOver", "ListAuditLogDownloadLink", "ListClickHouseDataBase", "ListClickHouseDataBaseParameter", "ListClickHouseDataBaseReplication", "ListClickHouseDataBaseReplicationConfig", "ListClickHouseInstance", "ListClickHouseInstanceNode", "ListConfigurationsDifferences", "ListConfigurationsInstances", "ListEnterpriseProjects", "ListGaussMySqlConfigurations", "ListGaussMySqlDatabase", "ListGaussMySqlDatabaseCharsets", "ListGaussMySqlDatabaseUser", "ListGaussMySqlDedicatedResources", "ListGaussMySqlInstanceDetailInfo", "ListGaussMySqlInstanceDetailInfoUnifyStatus", "ListGaussMySqlInstances", "ListGaussMySqlInstancesUnifyStatus", "ListHtapDataStore", "ListHtapFlavor", "ListHtapInstanceInfo", "ListHtapStorageType", "ListImmediateJobs", "ListInstanceConfigurations", "ListInstanceTags", "ListLtsErrorLogDetails", "ListLtsSlowlogDetails", "ListModifyHistory", "ListParamsTemplateApplyHistory", "ListProjectTags", "ListRecycleInstances", "ListScheduleJobs", "ListStarRocksDataBases", "ListStarRocksDataReplicationConfig", "ListStarRocksDataReplicationConfigByDataBase", "ListStarRocksDataReplications", "ListStarRocksDbParameters", "ListStarrocksInstanceInfo", "ListTaurusDbNodeProcesses", "ModifyBackupEncryptStatus", "ModifyDataSync"]

[lib]
name = "huawei_cloud_api_definitions_GaussDB"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-GaussDB"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
