[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AsyncInvokeFunction = []
BatchDeleteFunctionTriggers = []
BatchDeleteWorkflows = []
CancelAsyncInvocation = []
CreateCallbackWorkflow = []
CreateDependencyVersion = []
CreateEvent = []
CreateFunction = []
CreateFunctionApp = []
CreateFunctionTrigger = []
CreateFunctionVersion = []
CreateTags = []
CreateVersionAlias = []
CreateVpcEndpoint = []
CreateWorkflow = []
DeleteDependencyVersion = []
DeleteEvent = []
DeleteFunction = []
DeleteFunctionApp = []
DeleteFunctionAsyncInvokeConfig = []
DeleteFunctionTrigger = []
DeleteTags = []
DeleteVersionAlias = []
DeleteVpcEndpoint = []
EnableAsyncStatusLog = []
EnableLtsLogs = []
ExportFunction = []
ImportFunction = []
InvokeFunction = []
ListActiveAsyncInvocations = []
ListAppTemplates = []
ListAsyncInvocations = []
ListBridgeFunctions = []
ListBridgeVersions = []
ListDependencies = []
ListDependencyVersion = []
ListEvents = []
ListFunctionApplications = []
ListFunctionAsMetric = []
ListFunctionAsyncInvokeConfig = []
ListFunctionReservedInstances = []
ListFunctionStatistics = []
ListFunctionTags = []
ListFunctionTemplate = []
ListFunctionTriggers = []
ListFunctionVersions = []
ListFunctions = []
ListQuotas = []
ListReservedInstanceConfigs = []
ListStatistics = []
ListVersionAliases = []
ListWorkflow = []
ListWorkflowExecutions = []
RetryWorkFlow = []
ShowAppTemplate = []
ShowDependencyVersion = []
ShowEvent = []
ShowFuncReservedInstanceMetrics = []
ShowFuncSnapshotState = []
ShowFunctionApp = []
ShowFunctionAsyncInvokeConfig = []
ShowFunctionCode = []
ShowFunctionConfig = []
ShowFunctionMetrics = []
ShowFunctionTemplate = []
ShowFunctionTrigger = []
ShowLtsLogDetails = []
ShowProjectAsyncStatusLogInfo = []
ShowProjectTagsList = []
ShowResInstanceInfo = []
ShowTenantMetric = []
ShowTracing = []
ShowVersionAlias = []
ShowWorkFlow = []
ShowWorkFlowMetric = []
ShowWorkflowExecution = []
ShowWorkflowExecutionForPage = []
StartSyncWorkflowExecution = []
StartWorkflowExecution = []
StopWorkFlow = []
UpdateEvent = []
UpdateFuncSnapshot = []
UpdateFunctionAsyncInvokeConfig = []
UpdateFunctionCode = []
UpdateFunctionCollectState = []
UpdateFunctionConfig = []
UpdateFunctionMaxInstanceConfig = []
UpdateFunctionReservedInstancesCount = []
UpdateTracing = []
UpdateTrigger = []
UpdateVersionAlias = []
UpdateWorkFlow = []
full = ["AsyncInvokeFunction", "BatchDeleteFunctionTriggers", "BatchDeleteWorkflows", "CancelAsyncInvocation", "CreateCallbackWorkflow", "CreateDependencyVersion", "CreateEvent", "CreateFunction", "CreateFunctionApp", "CreateFunctionTrigger", "CreateFunctionVersion", "CreateTags", "CreateVersionAlias", "CreateVpcEndpoint", "CreateWorkflow", "DeleteDependencyVersion", "DeleteEvent", "DeleteFunction", "DeleteFunctionApp", "DeleteFunctionAsyncInvokeConfig", "DeleteFunctionTrigger", "DeleteTags", "DeleteVersionAlias", "DeleteVpcEndpoint", "EnableAsyncStatusLog", "EnableLtsLogs", "ExportFunction", "ImportFunction", "InvokeFunction", "ListActiveAsyncInvocations", "ListAppTemplates", "ListAsyncInvocations", "ListBridgeFunctions", "ListBridgeVersions", "ListDependencies", "ListDependencyVersion", "ListEvents", "ListFunctionApplications", "ListFunctionAsMetric", "ListFunctionAsyncInvokeConfig", "ListFunctionReservedInstances", "ListFunctions", "ListFunctionStatistics", "ListFunctionTags", "ListFunctionTemplate", "ListFunctionTriggers", "ListFunctionVersions", "ListQuotas", "ListReservedInstanceConfigs", "ListStatistics", "ListVersionAliases", "ListWorkflow", "ListWorkflowExecutions", "RetryWorkFlow", "ShowAppTemplate", "ShowDependencyVersion", "ShowEvent", "ShowFuncReservedInstanceMetrics", "ShowFuncSnapshotState", "ShowFunctionApp", "ShowFunctionAsyncInvokeConfig", "ShowFunctionCode", "ShowFunctionConfig", "ShowFunctionMetrics", "ShowFunctionTemplate", "ShowFunctionTrigger", "ShowLtsLogDetails", "ShowProjectAsyncStatusLogInfo", "ShowProjectTagsList", "ShowResInstanceInfo", "ShowTenantMetric", "ShowTracing", "ShowVersionAlias", "ShowWorkFlow", "ShowWorkflowExecution", "ShowWorkflowExecutionForPage", "ShowWorkFlowMetric", "StartSyncWorkflowExecution", "StartWorkflowExecution", "StopWorkFlow", "UpdateEvent", "UpdateFuncSnapshot", "UpdateFunctionAsyncInvokeConfig", "UpdateFunctionCode", "UpdateFunctionCollectState", "UpdateFunctionConfig", "UpdateFunctionMaxInstanceConfig", "UpdateFunctionReservedInstancesCount", "UpdateTracing", "UpdateTrigger", "UpdateVersionAlias", "UpdateWorkFlow"]

[lib]
name = "huawei_cloud_api_definitions_FunctionGraph"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-FunctionGraph"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
