#[cfg(feature = "AddDatabasePermission")]
pub mod AddDatabasePermission;
#[cfg(feature = "BatchTagAction")]
pub mod BatchTagAction;
#[cfg(feature = "CancelGaussMySqlInstanceEip")]
pub mod CancelGaussMySqlInstanceEip;
#[cfg(feature = "CancelScheduleTask")]
pub mod CancelScheduleTask;
#[cfg(feature = "ChangeGaussMySqlInstanceSpecification")]
pub mod ChangeGaussMySqlInstanceSpecification;
#[cfg(feature = "ChangeGaussMySqlProxySpecification")]
pub mod ChangeGaussMySqlProxySpecification;
#[cfg(feature = "CheckDataBaseConfig")]
pub mod CheckDataBaseConfig;
#[cfg(feature = "CheckResource")]
pub mod CheckResource;
#[cfg(feature = "CheckTableConfig")]
pub mod CheckTableConfig;
#[cfg(feature = "CopyConfigurations")]
pub mod CopyConfigurations;
#[cfg(feature = "CopyInstanceConfigurations")]
pub mod CopyInstanceConfigurations;
#[cfg(feature = "CreateAccessControl")]
pub mod CreateAccessControl;
#[cfg(feature = "CreateGaussMySqlBackup")]
pub mod CreateGaussMySqlBackup;
#[cfg(feature = "CreateGaussMySqlConfiguration")]
pub mod CreateGaussMySqlConfiguration;
#[cfg(feature = "CreateGaussMySqlDatabase")]
pub mod CreateGaussMySqlDatabase;
#[cfg(feature = "CreateGaussMySqlDatabaseUser")]
pub mod CreateGaussMySqlDatabaseUser;
#[cfg(feature = "CreateGaussMysqlDns")]
pub mod CreateGaussMysqlDns;
#[cfg(feature = "CreateGaussMySqlInstance")]
pub mod CreateGaussMySqlInstance;
#[cfg(feature = "CreateGaussMySqlProxy")]
pub mod CreateGaussMySqlProxy;
#[cfg(feature = "CreateGaussMySqlReadonlyNode")]
pub mod CreateGaussMySqlReadonlyNode;
#[cfg(feature = "CreateRestoreTables")]
pub mod CreateRestoreTables;
#[cfg(feature = "CreateStarRocksDataReplication")]
pub mod CreateStarRocksDataReplication;
#[cfg(feature = "DeleteDatabasePermission")]
pub mod DeleteDatabasePermission;
#[cfg(feature = "DeleteGaussMySqlBackup")]
pub mod DeleteGaussMySqlBackup;
#[cfg(feature = "DeleteGaussMySqlConfiguration")]
pub mod DeleteGaussMySqlConfiguration;
#[cfg(feature = "DeleteGaussMySqlDatabase")]
pub mod DeleteGaussMySqlDatabase;
#[cfg(feature = "DeleteGaussMySqlDatabaseUser")]
pub mod DeleteGaussMySqlDatabaseUser;
#[cfg(feature = "DeleteGaussMySqlInstance")]
pub mod DeleteGaussMySqlInstance;
#[cfg(feature = "DeleteGaussMySqlProxy")]
pub mod DeleteGaussMySqlProxy;
#[cfg(feature = "DeleteGaussMySqlReadonlyNode")]
pub mod DeleteGaussMySqlReadonlyNode;
#[cfg(feature = "DeleteScheduleTasK")]
pub mod DeleteScheduleTasK;
#[cfg(feature = "DeleteSqlFilterRule")]
pub mod DeleteSqlFilterRule;
#[cfg(feature = "DeleteStarRocksDataReplication")]
pub mod DeleteStarRocksDataReplication;
#[cfg(feature = "DeleteTaskRecord")]
pub mod DeleteTaskRecord;
#[cfg(feature = "DescribeBackupEncryptStatus")]
pub mod DescribeBackupEncryptStatus;
#[cfg(feature = "ExpandGaussMySqlInstanceVolume")]
pub mod ExpandGaussMySqlInstanceVolume;
#[cfg(feature = "ExpandGaussMySqlProxy")]
pub mod ExpandGaussMySqlProxy;
#[cfg(feature = "InvokeGaussMySqlInstanceSwitchOver")]
pub mod InvokeGaussMySqlInstanceSwitchOver;
#[cfg(feature = "ListAuditLogDownloadLink")]
pub mod ListAuditLogDownloadLink;
#[cfg(feature = "ListConfigurationsDifferences")]
pub mod ListConfigurationsDifferences;
#[cfg(feature = "ListConfigurationsInstances")]
pub mod ListConfigurationsInstances;
#[cfg(feature = "ListEnterpriseProjects")]
pub mod ListEnterpriseProjects;
#[cfg(feature = "ListGaussMySqlConfigurations")]
pub mod ListGaussMySqlConfigurations;
#[cfg(feature = "ListGaussMySqlDatabase")]
pub mod ListGaussMySqlDatabase;
#[cfg(feature = "ListGaussMySqlDatabaseCharsets")]
pub mod ListGaussMySqlDatabaseCharsets;
#[cfg(feature = "ListGaussMySqlDatabaseUser")]
pub mod ListGaussMySqlDatabaseUser;
#[cfg(feature = "ListGaussMySqlDedicatedResources")]
pub mod ListGaussMySqlDedicatedResources;
#[cfg(feature = "ListGaussMySqlInstanceDetailInfo")]
pub mod ListGaussMySqlInstanceDetailInfo;
#[cfg(feature = "ListGaussMySqlInstanceDetailInfoUnifyStatus")]
pub mod ListGaussMySqlInstanceDetailInfoUnifyStatus;
#[cfg(feature = "ListGaussMySqlInstances")]
pub mod ListGaussMySqlInstances;
#[cfg(feature = "ListGaussMySqlInstancesUnifyStatus")]
pub mod ListGaussMySqlInstancesUnifyStatus;
#[cfg(feature = "ListImmediateJobs")]
pub mod ListImmediateJobs;
#[cfg(feature = "ListInstanceConfigurations")]
pub mod ListInstanceConfigurations;
#[cfg(feature = "ListInstanceTags")]
pub mod ListInstanceTags;
#[cfg(feature = "ListLtsErrorLogDetails")]
pub mod ListLtsErrorLogDetails;
#[cfg(feature = "ListLtsSlowlogDetails")]
pub mod ListLtsSlowlogDetails;
#[cfg(feature = "ListModifyHistory")]
pub mod ListModifyHistory;
#[cfg(feature = "ListProjectTags")]
pub mod ListProjectTags;
#[cfg(feature = "ListScheduleJobs")]
pub mod ListScheduleJobs;
#[cfg(feature = "ListStarRocksDataBases")]
pub mod ListStarRocksDataBases;
#[cfg(feature = "ListStarRocksDataReplicationConfig")]
pub mod ListStarRocksDataReplicationConfig;
#[cfg(feature = "ListStarRocksDataReplications")]
pub mod ListStarRocksDataReplications;
#[cfg(feature = "ListStarRocksDbParameters")]
pub mod ListStarRocksDbParameters;
#[cfg(feature = "ModifyBackupEncryptStatus")]
pub mod ModifyBackupEncryptStatus;
#[cfg(feature = "ModifyGaussMysqlDns")]
pub mod ModifyGaussMysqlDns;
#[cfg(feature = "ModifyGaussMySqlProxyRouteMode")]
pub mod ModifyGaussMySqlProxyRouteMode;
#[cfg(feature = "ResetGaussMySqlDatabasePassword")]
pub mod ResetGaussMySqlDatabasePassword;
#[cfg(feature = "ResetGaussMySqlPassword")]
pub mod ResetGaussMySqlPassword;
#[cfg(feature = "RestartGaussMySqlInstance")]
pub mod RestartGaussMySqlInstance;
#[cfg(feature = "RestartGaussMySqlNode")]
pub mod RestartGaussMySqlNode;
#[cfg(feature = "RestoreOldInstance")]
pub mod RestoreOldInstance;
#[cfg(feature = "SetGaussMySqlProxyWeight")]
pub mod SetGaussMySqlProxyWeight;
#[cfg(feature = "SetGaussMySqlQuotas")]
pub mod SetGaussMySqlQuotas;
#[cfg(feature = "SetSqlFilterRule")]
pub mod SetSqlFilterRule;
#[cfg(feature = "ShowAuditLog")]
pub mod ShowAuditLog;
#[cfg(feature = "ShowAutoScalingPolicy")]
pub mod ShowAutoScalingPolicy;
#[cfg(feature = "ShowBackupRestoreTime")]
pub mod ShowBackupRestoreTime;
#[cfg(feature = "ShowDedicatedResourceInfo")]
pub mod ShowDedicatedResourceInfo;
#[cfg(feature = "ShowGaussMySqlBackupList")]
pub mod ShowGaussMySqlBackupList;
#[cfg(feature = "ShowGaussMySqlBackupPolicy")]
pub mod ShowGaussMySqlBackupPolicy;
#[cfg(feature = "ShowGaussMySqlConfiguration")]
pub mod ShowGaussMySqlConfiguration;
#[cfg(feature = "ShowGaussMySqlEngineVersion")]
pub mod ShowGaussMySqlEngineVersion;
#[cfg(feature = "ShowGaussMySqlFlavors")]
pub mod ShowGaussMySqlFlavors;
#[cfg(feature = "ShowGaussMySqlIncrementalBackupList")]
pub mod ShowGaussMySqlIncrementalBackupList;
#[cfg(feature = "ShowGaussMySqlInstanceInfo")]
pub mod ShowGaussMySqlInstanceInfo;
#[cfg(feature = "ShowGaussMySqlInstanceInfoUnifyStatus")]
pub mod ShowGaussMySqlInstanceInfoUnifyStatus;
#[cfg(feature = "ShowGaussMySqlJobInfo")]
pub mod ShowGaussMySqlJobInfo;
#[cfg(feature = "ShowGaussMySqlProjectQuotas")]
pub mod ShowGaussMySqlProjectQuotas;
#[cfg(feature = "ShowGaussMySqlProxyFlavors")]
pub mod ShowGaussMySqlProxyFlavors;
#[cfg(feature = "ShowGaussMySqlProxyList")]
pub mod ShowGaussMySqlProxyList;
#[cfg(feature = "ShowGaussMySqlQuotas")]
pub mod ShowGaussMySqlQuotas;
#[cfg(feature = "ShowInstanceDatabaseVersion")]
pub mod ShowInstanceDatabaseVersion;
#[cfg(feature = "ShowInstanceMonitorExtend")]
pub mod ShowInstanceMonitorExtend;
#[cfg(feature = "ShowIntelligentDiagnosisAbnormalCountOfInstances")]
pub mod ShowIntelligentDiagnosisAbnormalCountOfInstances;
#[cfg(feature = "ShowIntelligentDiagnosisInstanceInfosPerMetric")]
pub mod ShowIntelligentDiagnosisInstanceInfosPerMetric;
#[cfg(feature = "ShowRestoreTables")]
pub mod ShowRestoreTables;
#[cfg(feature = "ShowSqlFilterControl")]
pub mod ShowSqlFilterControl;
#[cfg(feature = "ShowSqlFilterRule")]
pub mod ShowSqlFilterRule;
#[cfg(feature = "ShrinkGaussMySqlProxy")]
pub mod ShrinkGaussMySqlProxy;
#[cfg(feature = "SwitchAccessControl")]
pub mod SwitchAccessControl;
