#[cfg(feature = "AddDatabasePermission")]
pub mod AddDatabasePermission;
#[cfg(feature = "BatchDeleteBackup")]
pub mod BatchDeleteBackup;
#[cfg(feature = "BatchTagAction")]
pub mod BatchTagAction;
#[cfg(feature = "BatchUpgradeDatabases")]
pub mod BatchUpgradeDatabases;
#[cfg(feature = "CancelGaussMySqlInstanceEip")]
pub mod CancelGaussMySqlInstanceEip;
#[cfg(feature = "CancelScheduleTask")]
pub mod CancelScheduleTask;
#[cfg(feature = "ChangeGaussMySqlInstanceSpecification")]
pub mod ChangeGaussMySqlInstanceSpecification;
#[cfg(feature = "ChangeGaussMySqlProxySpecification")]
pub mod ChangeGaussMySqlProxySpecification;
#[cfg(feature = "CheckDataBaseConfig")]
pub mod CheckDataBaseConfig;
#[cfg(feature = "CheckResource")]
pub mod CheckResource;
#[cfg(feature = "CheckStarrocksParams")]
pub mod CheckStarrocksParams;
#[cfg(feature = "CheckStarRocksResource")]
pub mod CheckStarRocksResource;
#[cfg(feature = "CheckTableConfig")]
pub mod CheckTableConfig;
#[cfg(feature = "CopyConfigurations")]
pub mod CopyConfigurations;
#[cfg(feature = "CopyInstanceConfigurations")]
pub mod CopyInstanceConfigurations;
#[cfg(feature = "CreateAccessControl")]
pub mod CreateAccessControl;
#[cfg(feature = "CreateGaussMySqlBackup")]
pub mod CreateGaussMySqlBackup;
#[cfg(feature = "CreateGaussMySqlConfiguration")]
pub mod CreateGaussMySqlConfiguration;
#[cfg(feature = "CreateGaussMySqlDatabase")]
pub mod CreateGaussMySqlDatabase;
#[cfg(feature = "CreateGaussMySqlDatabaseUser")]
pub mod CreateGaussMySqlDatabaseUser;
#[cfg(feature = "CreateGaussMysqlDns")]
pub mod CreateGaussMysqlDns;
#[cfg(feature = "CreateGaussMySqlInstance")]
pub mod CreateGaussMySqlInstance;
#[cfg(feature = "CreateGaussMySqlProxy")]
pub mod CreateGaussMySqlProxy;
#[cfg(feature = "CreateGaussMySqlReadonlyNode")]
pub mod CreateGaussMySqlReadonlyNode;
#[cfg(feature = "CreateLtsConfigs")]
pub mod CreateLtsConfigs;
#[cfg(feature = "CreateProxyDnsName")]
pub mod CreateProxyDnsName;
#[cfg(feature = "CreateRestoreTables")]
pub mod CreateRestoreTables;
#[cfg(feature = "CreateStarRocksDatabaseUser")]
pub mod CreateStarRocksDatabaseUser;
#[cfg(feature = "CreateStarRocksDataReplication")]
pub mod CreateStarRocksDataReplication;
#[cfg(feature = "CreateStarrocksInstance")]
pub mod CreateStarrocksInstance;
#[cfg(feature = "DeleteAutoSqlLimiting")]
pub mod DeleteAutoSqlLimiting;
#[cfg(feature = "DeleteDatabasePermission")]
pub mod DeleteDatabasePermission;
#[cfg(feature = "DeleteGaussMySqlBackup")]
pub mod DeleteGaussMySqlBackup;
#[cfg(feature = "DeleteGaussMySqlConfiguration")]
pub mod DeleteGaussMySqlConfiguration;
#[cfg(feature = "DeleteGaussMySqlDatabase")]
pub mod DeleteGaussMySqlDatabase;
#[cfg(feature = "DeleteGaussMySqlDatabaseUser")]
pub mod DeleteGaussMySqlDatabaseUser;
#[cfg(feature = "DeleteGaussMySqlInstance")]
pub mod DeleteGaussMySqlInstance;
#[cfg(feature = "DeleteGaussMySqlProxy")]
pub mod DeleteGaussMySqlProxy;
#[cfg(feature = "DeleteGaussMySqlReadonlyNode")]
pub mod DeleteGaussMySqlReadonlyNode;
#[cfg(feature = "DeleteLtsConfigs")]
pub mod DeleteLtsConfigs;
#[cfg(feature = "DeleteProxyPrivateDnsName")]
pub mod DeleteProxyPrivateDnsName;
#[cfg(feature = "DeleteScheduleTasK")]
pub mod DeleteScheduleTasK;
#[cfg(feature = "DeleteSqlFilterRule")]
pub mod DeleteSqlFilterRule;
#[cfg(feature = "DeleteStarRocksDatabaseUser")]
pub mod DeleteStarRocksDatabaseUser;
#[cfg(feature = "DeleteStarRocksDataReplication")]
pub mod DeleteStarRocksDataReplication;
#[cfg(feature = "DeleteStarrocksInstance")]
pub mod DeleteStarrocksInstance;
#[cfg(feature = "DeleteTaskRecord")]
pub mod DeleteTaskRecord;
#[cfg(feature = "DeleteTaurusDbNodeProcesses")]
pub mod DeleteTaurusDbNodeProcesses;
#[cfg(feature = "DescribeBackupEncryptStatus")]
pub mod DescribeBackupEncryptStatus;
#[cfg(feature = "DownloadImportExcelTemplate")]
pub mod DownloadImportExcelTemplate;
#[cfg(feature = "DownloadSlowLogFile")]
pub mod DownloadSlowLogFile;
#[cfg(feature = "ExpandGaussMySqlInstanceVolume")]
pub mod ExpandGaussMySqlInstanceVolume;
#[cfg(feature = "ExpandGaussMySqlProxy")]
pub mod ExpandGaussMySqlProxy;
#[cfg(feature = "InvokeGaussMySqlInstanceSwitchOver")]
pub mod InvokeGaussMySqlInstanceSwitchOver;
#[cfg(feature = "ListAuditLogDownloadLink")]
pub mod ListAuditLogDownloadLink;
#[cfg(feature = "ListAuditLogs")]
pub mod ListAuditLogs;
#[cfg(feature = "ListConfigurationsDifferences")]
pub mod ListConfigurationsDifferences;
#[cfg(feature = "ListConfigurationsInstances")]
pub mod ListConfigurationsInstances;
#[cfg(feature = "ListEnterpriseProjects")]
pub mod ListEnterpriseProjects;
#[cfg(feature = "ListGaussMySqlConfigurations")]
pub mod ListGaussMySqlConfigurations;
#[cfg(feature = "ListGaussMySqlDatabase")]
pub mod ListGaussMySqlDatabase;
#[cfg(feature = "ListGaussMySqlDatabaseCharsets")]
pub mod ListGaussMySqlDatabaseCharsets;
#[cfg(feature = "ListGaussMySqlDatabaseUser")]
pub mod ListGaussMySqlDatabaseUser;
#[cfg(feature = "ListGaussMySqlDedicatedResources")]
pub mod ListGaussMySqlDedicatedResources;
#[cfg(feature = "ListGaussMySqlInstanceDetailInfo")]
pub mod ListGaussMySqlInstanceDetailInfo;
#[cfg(feature = "ListGaussMySqlInstanceDetailInfoUnifyStatus")]
pub mod ListGaussMySqlInstanceDetailInfoUnifyStatus;
#[cfg(feature = "ListGaussMySqlInstances")]
pub mod ListGaussMySqlInstances;
#[cfg(feature = "ListGaussMySqlInstancesUnifyStatus")]
pub mod ListGaussMySqlInstancesUnifyStatus;
#[cfg(feature = "ListHtapDataStore")]
pub mod ListHtapDataStore;
#[cfg(feature = "ListHtapFlavor")]
pub mod ListHtapFlavor;
#[cfg(feature = "ListHtapInstanceInfo")]
pub mod ListHtapInstanceInfo;
#[cfg(feature = "ListHtapStorageType")]
pub mod ListHtapStorageType;
#[cfg(feature = "ListImmediateJobs")]
pub mod ListImmediateJobs;
#[cfg(feature = "ListInstanceConfigurations")]
pub mod ListInstanceConfigurations;
#[cfg(feature = "ListInstanceNode")]
pub mod ListInstanceNode;
#[cfg(feature = "ListInstanceTags")]
pub mod ListInstanceTags;
#[cfg(feature = "ListLtsErrorLogDetails")]
pub mod ListLtsErrorLogDetails;
#[cfg(feature = "ListLtsSlowlogDetails")]
pub mod ListLtsSlowlogDetails;
#[cfg(feature = "ListModifyHistory")]
pub mod ListModifyHistory;
#[cfg(feature = "ListParamsTemplateApplyHistory")]
pub mod ListParamsTemplateApplyHistory;
#[cfg(feature = "ListProjectTags")]
pub mod ListProjectTags;
#[cfg(feature = "ListRecycleInstances")]
pub mod ListRecycleInstances;
#[cfg(feature = "ListScheduleJobs")]
pub mod ListScheduleJobs;
#[cfg(feature = "ListStarRocksDataBases")]
pub mod ListStarRocksDataBases;
#[cfg(feature = "ListStarRocksDataReplicationConfig")]
pub mod ListStarRocksDataReplicationConfig;
#[cfg(feature = "ListStarRocksDataReplicationConfigByDataBase")]
pub mod ListStarRocksDataReplicationConfigByDataBase;
#[cfg(feature = "ListStarRocksDataReplications")]
pub mod ListStarRocksDataReplications;
#[cfg(feature = "ListStarRocksDbParameters")]
pub mod ListStarRocksDbParameters;
#[cfg(feature = "ListStarrocksInstanceInfo")]
pub mod ListStarrocksInstanceInfo;
#[cfg(feature = "ListTaurusDbNodeProcesses")]
pub mod ListTaurusDbNodeProcesses;
#[cfg(feature = "ModifyAutoExpandPolicy")]
pub mod ModifyAutoExpandPolicy;
#[cfg(feature = "ModifyBackupEncryptStatus")]
pub mod ModifyBackupEncryptStatus;
#[cfg(feature = "ModifyDataSync")]
pub mod ModifyDataSync;
#[cfg(feature = "ModifyGaussMysqlDns")]
pub mod ModifyGaussMysqlDns;
#[cfg(feature = "ModifyGaussMySqlProxyRouteMode")]
pub mod ModifyGaussMySqlProxyRouteMode;
#[cfg(feature = "ModifyNodePriority")]
pub mod ModifyNodePriority;
#[cfg(feature = "ModifyStarRocksSecurityGroup")]
pub mod ModifyStarRocksSecurityGroup;
#[cfg(feature = "PauseStarRocksDataReplication")]
pub mod PauseStarRocksDataReplication;
#[cfg(feature = "RenameInstanceNode")]
pub mod RenameInstanceNode;
#[cfg(feature = "ResetGaussMySqlDatabasePassword")]
pub mod ResetGaussMySqlDatabasePassword;
