[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
CreateGroup = []
CreateGroupMembership = []
CreateUser = []
DeleteGroup = []
DeleteGroupMembership = []
DeleteUser = []
DescribeGroup = []
DescribeGroupMembership = []
DescribeUser = []
ListGroupMemberships = []
ListGroupMembershipsForMember = []
ListGroups = []
ListUsers = []
UpdateGroup = []
UpdateUser = []
full = ["CreateGroup", "CreateGroupMembership", "CreateUser", "DeleteGroup", "DeleteGroupMembership", "DeleteUser", "DescribeGroup", "DescribeGroupMembership", "DescribeUser", "ListGroupMemberships", "ListGroupMembershipsForMember", "ListGroups", "ListUsers", "UpdateGroup", "UpdateUser"]

[lib]
name = "huawei_cloud_api_definitions_IdentityCenterStore"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-IdentityCenterStore"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
