[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
BatchDeleteSessions = []
BatchListMfaDevicesForUser = []
CreateBearerToken = []
CreateExternalIdPConfigurationForDirectory = []
CreateGroup = []
CreateGroupMembership = []
CreateProvisioningTenant = []
CreateSpCertificate = []
CreateUser = []
DeleteBearerToken = []
DeleteExternalIdPCertificate = []
DeleteExternalIdPConfigurationForDirectory = []
DeleteGroup = []
DeleteGroupMembership = []
DeleteMfaDeviceForUser = []
DeleteProvisioningTenant = []
DeleteSpCertificate = []
DeleteUser = []
DescribeGroup = []
DescribeGroupMembership = []
DescribeGroups = []
DescribePasswordPolicy = []
DescribeUser = []
DescribeUsers = []
DisableExternalIdPConfigurationForDirectory = []
DisableUser = []
EnableExternalIdPConfigurationForDirectory = []
EnableUser = []
GetGroupId = []
GetGroupMembershipId = []
GetIdentityStoreSummary = []
GetSpConfigurationForDirectory = []
GetUserId = []
ImportExternalIdPCertificate = []
IsMemberInGroups = []
ListBearerTokens = []
ListExternalIdPCertificates = []
ListExternalIdPConfigurationsForDirectory = []
ListGroupMemberships = []
ListGroupMembershipsForMember = []
ListGroups = []
ListProvisioningTenants = []
ListSessions = []
ListSpCertificates = []
ListUsers = []
RegisterMfaDeviceForUser = []
ResetPwdMode = []
UpdateExternalIdPConfigurationForDirectory = []
UpdateGroup = []
UpdateMfaDeviceForUser = []
UpdatePasswordPolicy = []
UpdateSpActiveCertificate = []
UpdateUser = []
VerifyEmail = []
full = ["BatchDeleteSessions", "BatchListMfaDevicesForUser", "CreateBearerToken", "CreateExternalIdPConfigurationForDirectory", "CreateGroup", "CreateGroupMembership", "CreateProvisioningTenant", "CreateSpCertificate", "CreateUser", "DeleteBearerToken", "DeleteExternalIdPCertificate", "DeleteExternalIdPConfigurationForDirectory", "DeleteGroup", "DeleteGroupMembership", "DeleteMfaDeviceForUser", "DeleteProvisioningTenant", "DeleteSpCertificate", "DeleteUser", "DescribeGroup", "DescribeGroupMembership", "DescribeGroups", "DescribePasswordPolicy", "DescribeUser", "DescribeUsers", "DisableExternalIdPConfigurationForDirectory", "DisableUser", "EnableExternalIdPConfigurationForDirectory", "EnableUser", "GetGroupId", "GetGroupMembershipId", "GetIdentityStoreSummary", "GetSpConfigurationForDirectory", "GetUserId", "ImportExternalIdPCertificate", "IsMemberInGroups", "ListBearerTokens", "ListExternalIdPCertificates", "ListExternalIdPConfigurationsForDirectory", "ListGroupMemberships", "ListGroupMembershipsForMember", "ListGroups", "ListProvisioningTenants", "ListSessions", "ListSpCertificates", "ListUsers", "RegisterMfaDeviceForUser", "ResetPwdMode", "UpdateExternalIdPConfigurationForDirectory", "UpdateGroup", "UpdateMfaDeviceForUser", "UpdatePasswordPolicy", "UpdateSpActiveCertificate", "UpdateUser", "VerifyEmail"]

[lib]
name = "huawei_cloud_api_definitions_IdentityCenterStore"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-IdentityCenterStore"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
