
		// This file is generated by huawei-cloud-api-definitions/src/update.rs
		// Definition: https://console.huaweicloud.com/apiexplorer/new/v4/apis/detail?product_short=CCE&name=AddNodesToNodePool&region_id=cn-north-4
		#![allow(dead_code)]
		#![allow(unused_imports)]
		#![allow(non_snake_case)]
		use std::fmt::Debug;
		use serde::{Serialize, Deserialize};
		use typify::import_types;
		import_types!(schema="src/AddNodesToNodePool.json", struct_builder = true);
	