#[cfg(feature = "AddNode")]
pub mod AddNode;
#[cfg(feature = "AwakeCluster")]
pub mod AwakeCluster;
#[cfg(feature = "BatchCreateAutopilotClusterTags")]
pub mod BatchCreateAutopilotClusterTags;
#[cfg(feature = "BatchCreateClusterTags")]
pub mod BatchCreateClusterTags;
#[cfg(feature = "BatchCreateDeleteResourceTags")]
pub mod BatchCreateDeleteResourceTags;
#[cfg(feature = "BatchDeleteAutopilotClusterTags")]
pub mod BatchDeleteAutopilotClusterTags;
#[cfg(feature = "BatchDeleteClusterTags")]
pub mod BatchDeleteClusterTags;
#[cfg(feature = "BatchSyncNodes")]
pub mod BatchSyncNodes;
#[cfg(feature = "ContinueUpgradeClusterTask")]
pub mod ContinueUpgradeClusterTask;
#[cfg(feature = "CreateAddonInstance")]
pub mod CreateAddonInstance;
#[cfg(feature = "CreateAutopilotAddonInstance")]
pub mod CreateAutopilotAddonInstance;
#[cfg(feature = "CreateAutopilotCluster")]
pub mod CreateAutopilotCluster;
#[cfg(feature = "CreateAutopilotClusterMasterSnapshot")]
pub mod CreateAutopilotClusterMasterSnapshot;
#[cfg(feature = "CreateAutopilotKubernetesClusterCert")]
pub mod CreateAutopilotKubernetesClusterCert;
#[cfg(feature = "CreateAutopilotPostCheck")]
pub mod CreateAutopilotPostCheck;
#[cfg(feature = "CreateAutopilotPreCheck")]
pub mod CreateAutopilotPreCheck;
#[cfg(feature = "CreateAutopilotRelease")]
pub mod CreateAutopilotRelease;
#[cfg(feature = "CreateAutopilotUpgradeWorkFlow")]
pub mod CreateAutopilotUpgradeWorkFlow;
#[cfg(feature = "CreateCloudPersistentVolumeClaims")]
pub mod CreateCloudPersistentVolumeClaims;
#[cfg(feature = "CreateCluster")]
pub mod CreateCluster;
#[cfg(feature = "CreateClusterMasterSnapshot")]
pub mod CreateClusterMasterSnapshot;
#[cfg(feature = "CreateKubernetesClusterCert")]
pub mod CreateKubernetesClusterCert;
#[cfg(feature = "CreateNode")]
pub mod CreateNode;
#[cfg(feature = "CreateNodePool")]
pub mod CreateNodePool;
#[cfg(feature = "CreatePartition")]
pub mod CreatePartition;
#[cfg(feature = "CreatePostCheck")]
pub mod CreatePostCheck;
#[cfg(feature = "CreatePreCheck")]
pub mod CreatePreCheck;
#[cfg(feature = "CreateRelease")]
pub mod CreateRelease;
#[cfg(feature = "CreateUpgradeWorkFlow")]
pub mod CreateUpgradeWorkFlow;
#[cfg(feature = "DeleteAddonInstance")]
pub mod DeleteAddonInstance;
#[cfg(feature = "DeleteAutopilotAddonInstance")]
pub mod DeleteAutopilotAddonInstance;
#[cfg(feature = "DeleteAutopilotChart")]
pub mod DeleteAutopilotChart;
#[cfg(feature = "DeleteAutopilotCluster")]
pub mod DeleteAutopilotCluster;
#[cfg(feature = "DeleteAutopilotRelease")]
pub mod DeleteAutopilotRelease;
#[cfg(feature = "DeleteChart")]
pub mod DeleteChart;
#[cfg(feature = "DeleteCloudPersistentVolumeClaims")]
pub mod DeleteCloudPersistentVolumeClaims;
#[cfg(feature = "DeleteCluster")]
pub mod DeleteCluster;
#[cfg(feature = "DeleteNode")]
pub mod DeleteNode;
#[cfg(feature = "DeleteNodePool")]
pub mod DeleteNodePool;
#[cfg(feature = "DeleteRelease")]
pub mod DeleteRelease;
#[cfg(feature = "DownloadAutopilotChart")]
pub mod DownloadAutopilotChart;
#[cfg(feature = "DownloadChart")]
pub mod DownloadChart;
#[cfg(feature = "HibernateCluster")]
pub mod HibernateCluster;
#[cfg(feature = "ListAddonInstances")]
pub mod ListAddonInstances;
#[cfg(feature = "ListAddonTemplates")]
pub mod ListAddonTemplates;
#[cfg(feature = "ListAutopilotAddonInstances")]
pub mod ListAutopilotAddonInstances;
#[cfg(feature = "ListAutopilotAddonTemplates")]
pub mod ListAutopilotAddonTemplates;
#[cfg(feature = "ListAutopilotCharts")]
pub mod ListAutopilotCharts;
#[cfg(feature = "ListAutopilotClusterMasterSnapshotTasks")]
pub mod ListAutopilotClusterMasterSnapshotTasks;
#[cfg(feature = "ListAutopilotClusters")]
pub mod ListAutopilotClusters;
#[cfg(feature = "ListAutopilotClusterUpgradeFeatureGates")]
pub mod ListAutopilotClusterUpgradeFeatureGates;
#[cfg(feature = "ListAutopilotClusterUpgradePaths")]
pub mod ListAutopilotClusterUpgradePaths;
#[cfg(feature = "ListAutopilotPreCheckTasks")]
pub mod ListAutopilotPreCheckTasks;
#[cfg(feature = "ListAutopilotReleases")]
pub mod ListAutopilotReleases;
#[cfg(feature = "ListAutopilotUpgradeClusterTasks")]
pub mod ListAutopilotUpgradeClusterTasks;
#[cfg(feature = "ListAutopilotUpgradeWorkFlows")]
pub mod ListAutopilotUpgradeWorkFlows;
#[cfg(feature = "ListCharts")]
pub mod ListCharts;
#[cfg(feature = "ListClusterMasterSnapshotTasks")]
pub mod ListClusterMasterSnapshotTasks;
#[cfg(feature = "ListClusters")]
pub mod ListClusters;
#[cfg(feature = "ListClusterUpgradeFeatureGates")]
pub mod ListClusterUpgradeFeatureGates;
#[cfg(feature = "ListClusterUpgradePaths")]
pub mod ListClusterUpgradePaths;
#[cfg(feature = "ListNodePools")]
pub mod ListNodePools;
#[cfg(feature = "ListNodes")]
pub mod ListNodes;
#[cfg(feature = "ListPartitions")]
pub mod ListPartitions;
#[cfg(feature = "ListPreCheckTasks")]
pub mod ListPreCheckTasks;
#[cfg(feature = "ListReleases")]
pub mod ListReleases;
#[cfg(feature = "ListUpgradeClusterTasks")]
pub mod ListUpgradeClusterTasks;
#[cfg(feature = "ListUpgradeWorkFlows")]
pub mod ListUpgradeWorkFlows;
#[cfg(feature = "MigrateNode")]
pub mod MigrateNode;
#[cfg(feature = "PauseUpgradeClusterTask")]
pub mod PauseUpgradeClusterTask;
#[cfg(feature = "RemoveNode")]
pub mod RemoveNode;
#[cfg(feature = "ResetNode")]
pub mod ResetNode;
#[cfg(feature = "ResizeCluster")]
pub mod ResizeCluster;
#[cfg(feature = "RetryAutopilotUpgradeClusterTask")]
pub mod RetryAutopilotUpgradeClusterTask;
#[cfg(feature = "RetryUpgradeClusterTask")]
pub mod RetryUpgradeClusterTask;
#[cfg(feature = "RevokeKubernetesClusterCert")]
pub mod RevokeKubernetesClusterCert;
#[cfg(feature = "RollbackAddonInstance")]
pub mod RollbackAddonInstance;
#[cfg(feature = "RollbackAutopilotAddonInstance")]
pub mod RollbackAutopilotAddonInstance;
#[cfg(feature = "ScaleNodePool")]
pub mod ScaleNodePool;
#[cfg(feature = "ShowAddonInstance")]
pub mod ShowAddonInstance;
#[cfg(feature = "ShowAutopilotAddonInstance")]
pub mod ShowAutopilotAddonInstance;
#[cfg(feature = "ShowAutopilotChart")]
pub mod ShowAutopilotChart;
#[cfg(feature = "ShowAutopilotChartValues")]
pub mod ShowAutopilotChartValues;
#[cfg(feature = "ShowAutopilotCluster")]
pub mod ShowAutopilotCluster;
#[cfg(feature = "ShowAutopilotClusterEndpoints")]
pub mod ShowAutopilotClusterEndpoints;
#[cfg(feature = "ShowAutopilotClusterUpgradeInfo")]
pub mod ShowAutopilotClusterUpgradeInfo;
#[cfg(feature = "ShowAutopilotJob")]
pub mod ShowAutopilotJob;
#[cfg(feature = "ShowAutopilotPreCheck")]
pub mod ShowAutopilotPreCheck;
#[cfg(feature = "ShowAutopilotQuotas")]
pub mod ShowAutopilotQuotas;
#[cfg(feature = "ShowAutopilotRelease")]
pub mod ShowAutopilotRelease;
#[cfg(feature = "ShowAutopilotReleaseHistory")]
pub mod ShowAutopilotReleaseHistory;
#[cfg(feature = "ShowAutopilotUpgradeClusterTask")]
pub mod ShowAutopilotUpgradeClusterTask;
#[cfg(feature = "ShowAutopilotUpgradeWorkFlow")]
pub mod ShowAutopilotUpgradeWorkFlow;
#[cfg(feature = "ShowAutopilotUserChartsQuotas")]
pub mod ShowAutopilotUserChartsQuotas;
#[cfg(feature = "ShowChart")]
pub mod ShowChart;
#[cfg(feature = "ShowChartValues")]
pub mod ShowChartValues;
#[cfg(feature = "ShowCluster")]
pub mod ShowCluster;
#[cfg(feature = "ShowClusterConfig")]
pub mod ShowClusterConfig;
#[cfg(feature = "ShowClusterConfigurationDetails")]
pub mod ShowClusterConfigurationDetails;
#[cfg(feature = "ShowClusterEndpoints")]
pub mod ShowClusterEndpoints;
