#[cfg(feature = "AddNode")]
pub mod AddNode;
#[cfg(feature = "AwakeCluster")]
pub mod AwakeCluster;
#[cfg(feature = "BatchCreateClusterTags")]
pub mod BatchCreateClusterTags;
#[cfg(feature = "BatchDeleteClusterTags")]
pub mod BatchDeleteClusterTags;
#[cfg(feature = "ContinueUpgradeClusterTask")]
pub mod ContinueUpgradeClusterTask;
#[cfg(feature = "CreateAddonInstance")]
pub mod CreateAddonInstance;
#[cfg(feature = "CreateCloudPersistentVolumeClaims")]
pub mod CreateCloudPersistentVolumeClaims;
#[cfg(feature = "CreateCluster")]
pub mod CreateCluster;
#[cfg(feature = "CreateClusterMasterSnapshot")]
pub mod CreateClusterMasterSnapshot;
#[cfg(feature = "CreateKubernetesClusterCert")]
pub mod CreateKubernetesClusterCert;
#[cfg(feature = "CreateNode")]
pub mod CreateNode;
#[cfg(feature = "CreateNodePool")]
pub mod CreateNodePool;
#[cfg(feature = "CreatePartition")]
pub mod CreatePartition;
#[cfg(feature = "CreatePostCheck")]
pub mod CreatePostCheck;
#[cfg(feature = "CreatePreCheck")]
pub mod CreatePreCheck;
#[cfg(feature = "CreateRelease")]
pub mod CreateRelease;
#[cfg(feature = "CreateUpgradeWorkFlow")]
pub mod CreateUpgradeWorkFlow;
#[cfg(feature = "DeleteAddonInstance")]
pub mod DeleteAddonInstance;
#[cfg(feature = "DeleteChart")]
pub mod DeleteChart;
#[cfg(feature = "DeleteCloudPersistentVolumeClaims")]
pub mod DeleteCloudPersistentVolumeClaims;
#[cfg(feature = "DeleteCluster")]
pub mod DeleteCluster;
#[cfg(feature = "DeleteNode")]
pub mod DeleteNode;
#[cfg(feature = "DeleteNodePool")]
pub mod DeleteNodePool;
#[cfg(feature = "DeleteRelease")]
pub mod DeleteRelease;
#[cfg(feature = "DownloadChart")]
pub mod DownloadChart;
#[cfg(feature = "HibernateCluster")]
pub mod HibernateCluster;
#[cfg(feature = "ListAddonInstances")]
pub mod ListAddonInstances;
#[cfg(feature = "ListAddonTemplates")]
pub mod ListAddonTemplates;
#[cfg(feature = "ListCharts")]
pub mod ListCharts;
#[cfg(feature = "ListClusterMasterSnapshotTasks")]
pub mod ListClusterMasterSnapshotTasks;
#[cfg(feature = "ListClusters")]
pub mod ListClusters;
#[cfg(feature = "ListClusterUpgradeFeatureGates")]
pub mod ListClusterUpgradeFeatureGates;
#[cfg(feature = "ListClusterUpgradePaths")]
pub mod ListClusterUpgradePaths;
#[cfg(feature = "ListNodePools")]
pub mod ListNodePools;
#[cfg(feature = "ListNodes")]
pub mod ListNodes;
#[cfg(feature = "ListPartitions")]
pub mod ListPartitions;
#[cfg(feature = "ListPreCheckTasks")]
pub mod ListPreCheckTasks;
#[cfg(feature = "ListReleases")]
pub mod ListReleases;
#[cfg(feature = "ListUpgradeClusterTasks")]
pub mod ListUpgradeClusterTasks;
#[cfg(feature = "ListUpgradeWorkFlows")]
pub mod ListUpgradeWorkFlows;
#[cfg(feature = "MigrateNode")]
pub mod MigrateNode;
#[cfg(feature = "PauseUpgradeClusterTask")]
pub mod PauseUpgradeClusterTask;
#[cfg(feature = "RemoveNode")]
pub mod RemoveNode;
#[cfg(feature = "ResetNode")]
pub mod ResetNode;
#[cfg(feature = "ResizeCluster")]
pub mod ResizeCluster;
#[cfg(feature = "RetryUpgradeClusterTask")]
pub mod RetryUpgradeClusterTask;
#[cfg(feature = "RollbackAddonInstance")]
pub mod RollbackAddonInstance;
#[cfg(feature = "ShowAddonInstance")]
pub mod ShowAddonInstance;
#[cfg(feature = "ShowChart")]
pub mod ShowChart;
#[cfg(feature = "ShowChartValues")]
pub mod ShowChartValues;
#[cfg(feature = "ShowCluster")]
pub mod ShowCluster;
#[cfg(feature = "ShowClusterConfig")]
pub mod ShowClusterConfig;
#[cfg(feature = "ShowClusterConfigurationDetails")]
pub mod ShowClusterConfigurationDetails;
#[cfg(feature = "ShowClusterEndpoints")]
pub mod ShowClusterEndpoints;
#[cfg(feature = "ShowClusterUpgradeInfo")]
pub mod ShowClusterUpgradeInfo;
#[cfg(feature = "ShowJob")]
pub mod ShowJob;
#[cfg(feature = "ShowNode")]
pub mod ShowNode;
#[cfg(feature = "ShowNodePool")]
pub mod ShowNodePool;
#[cfg(feature = "ShowNodePoolConfigurationDetails")]
pub mod ShowNodePoolConfigurationDetails;
#[cfg(feature = "ShowNodePoolConfigurations")]
pub mod ShowNodePoolConfigurations;
#[cfg(feature = "ShowPartition")]
pub mod ShowPartition;
#[cfg(feature = "ShowPreCheck")]
pub mod ShowPreCheck;
#[cfg(feature = "ShowQuotas")]
pub mod ShowQuotas;
#[cfg(feature = "ShowRelease")]
pub mod ShowRelease;
#[cfg(feature = "ShowReleaseHistory")]
pub mod ShowReleaseHistory;
#[cfg(feature = "ShowUpgradeClusterTask")]
pub mod ShowUpgradeClusterTask;
#[cfg(feature = "ShowUpgradeWorkFlow")]
pub mod ShowUpgradeWorkFlow;
#[cfg(feature = "ShowUserChartsQuotas")]
pub mod ShowUserChartsQuotas;
#[cfg(feature = "ShowVersion")]
pub mod ShowVersion;
#[cfg(feature = "UpdateAddonInstance")]
pub mod UpdateAddonInstance;
#[cfg(feature = "UpdateChart")]
pub mod UpdateChart;
#[cfg(feature = "UpdateCluster")]
pub mod UpdateCluster;
#[cfg(feature = "UpdateClusterEip")]
pub mod UpdateClusterEip;
#[cfg(feature = "UpdateClusterLogConfig")]
pub mod UpdateClusterLogConfig;
#[cfg(feature = "UpdateNode")]
pub mod UpdateNode;
#[cfg(feature = "UpdateNodePool")]
pub mod UpdateNodePool;
#[cfg(feature = "UpdateNodePoolConfiguration")]
pub mod UpdateNodePoolConfiguration;
#[cfg(feature = "UpdatePartition")]
pub mod UpdatePartition;
#[cfg(feature = "UpdateRelease")]
pub mod UpdateRelease;
#[cfg(feature = "UpgradeCluster")]
pub mod UpgradeCluster;
#[cfg(feature = "UpgradeWorkFlowUpdate")]
pub mod UpgradeWorkFlowUpdate;
#[cfg(feature = "UploadChart")]
pub mod UploadChart;
