#[cfg(feature = "AddNode")]
pub mod AddNode;
#[cfg(feature = "AddNodesToNodePool")]
pub mod AddNodesToNodePool;
#[cfg(feature = "AwakeCluster")]
pub mod AwakeCluster;
#[cfg(feature = "BatchCreateAddonPrecheck")]
pub mod BatchCreateAddonPrecheck;
#[cfg(feature = "BatchCreateAutopilotClusterTags")]
pub mod BatchCreateAutopilotClusterTags;
#[cfg(feature = "BatchCreateClusterTags")]
pub mod BatchCreateClusterTags;
#[cfg(feature = "BatchDeleteAutopilotClusterTags")]
pub mod BatchDeleteAutopilotClusterTags;
#[cfg(feature = "BatchDeleteClusterTags")]
pub mod BatchDeleteClusterTags;
#[cfg(feature = "BatchSyncNodes")]
pub mod BatchSyncNodes;
#[cfg(feature = "ContinueUpgradeClusterTask")]
pub mod ContinueUpgradeClusterTask;
#[cfg(feature = "CreateAccessPolicy")]
pub mod CreateAccessPolicy;
#[cfg(feature = "CreateAddonInstance")]
pub mod CreateAddonInstance;
#[cfg(feature = "CreateAutopilotAddonInstance")]
pub mod CreateAutopilotAddonInstance;
#[cfg(feature = "CreateAutopilotCluster")]
pub mod CreateAutopilotCluster;
#[cfg(feature = "CreateAutopilotClusterMasterSnapshot")]
pub mod CreateAutopilotClusterMasterSnapshot;
#[cfg(feature = "CreateAutopilotKubernetesClusterCert")]
pub mod CreateAutopilotKubernetesClusterCert;
#[cfg(feature = "CreateAutopilotMaintenanceWindow")]
pub mod CreateAutopilotMaintenanceWindow;
#[cfg(feature = "CreateAutopilotPostCheck")]
pub mod CreateAutopilotPostCheck;
#[cfg(feature = "CreateAutopilotPreCheck")]
pub mod CreateAutopilotPreCheck;
#[cfg(feature = "CreateAutopilotRelease")]
pub mod CreateAutopilotRelease;
#[cfg(feature = "CreateAutopilotUpgradeWorkFlow")]
pub mod CreateAutopilotUpgradeWorkFlow;
#[cfg(feature = "CreateCloudPersistentVolumeClaims")]
pub mod CreateCloudPersistentVolumeClaims;
#[cfg(feature = "CreateCluster")]
pub mod CreateCluster;
#[cfg(feature = "CreateClusterMasterSnapshot")]
pub mod CreateClusterMasterSnapshot;
#[cfg(feature = "CreateImageCache")]
pub mod CreateImageCache;
#[cfg(feature = "CreateKubernetesClusterCert")]
pub mod CreateKubernetesClusterCert;
#[cfg(feature = "CreateNode")]
pub mod CreateNode;
#[cfg(feature = "CreateNodePool")]
pub mod CreateNodePool;
#[cfg(feature = "CreatePartition")]
pub mod CreatePartition;
#[cfg(feature = "CreatePostCheck")]
pub mod CreatePostCheck;
#[cfg(feature = "CreatePreCheck")]
pub mod CreatePreCheck;
#[cfg(feature = "CreateRelease")]
pub mod CreateRelease;
#[cfg(feature = "CreateUpgradeWorkFlow")]
pub mod CreateUpgradeWorkFlow;
#[cfg(feature = "DeleteAccessPolicy")]
pub mod DeleteAccessPolicy;
#[cfg(feature = "DeleteAddonInstance")]
pub mod DeleteAddonInstance;
#[cfg(feature = "DeleteAutopilotAddonInstance")]
pub mod DeleteAutopilotAddonInstance;
#[cfg(feature = "DeleteAutopilotChart")]
pub mod DeleteAutopilotChart;
#[cfg(feature = "DeleteAutopilotCluster")]
pub mod DeleteAutopilotCluster;
#[cfg(feature = "DeleteAutopilotJob")]
pub mod DeleteAutopilotJob;
#[cfg(feature = "DeleteAutopilotMaintenanceWindow")]
pub mod DeleteAutopilotMaintenanceWindow;
#[cfg(feature = "DeleteAutopilotRelease")]
pub mod DeleteAutopilotRelease;
#[cfg(feature = "DeleteChart")]
pub mod DeleteChart;
#[cfg(feature = "DeleteCloudPersistentVolumeClaims")]
pub mod DeleteCloudPersistentVolumeClaims;
#[cfg(feature = "DeleteCluster")]
pub mod DeleteCluster;
#[cfg(feature = "DeleteImageCache")]
pub mod DeleteImageCache;
#[cfg(feature = "DeleteNode")]
pub mod DeleteNode;
#[cfg(feature = "DeleteNodePool")]
pub mod DeleteNodePool;
#[cfg(feature = "DeleteRelease")]
pub mod DeleteRelease;
#[cfg(feature = "DownloadAutopilotChart")]
pub mod DownloadAutopilotChart;
#[cfg(feature = "DownloadChart")]
pub mod DownloadChart;
#[cfg(feature = "GetAccessPolicy")]
pub mod GetAccessPolicy;
#[cfg(feature = "GetAutopilotOneJob")]
pub mod GetAutopilotOneJob;
#[cfg(feature = "GetAvaliableZone")]
pub mod GetAvaliableZone;
#[cfg(feature = "GetClusterFlavorSpecs")]
pub mod GetClusterFlavorSpecs;
#[cfg(feature = "GetClusterLongAkskConfig")]
pub mod GetClusterLongAkskConfig;
#[cfg(feature = "GetClusterQuota")]
pub mod GetClusterQuota;
#[cfg(feature = "GetCustomizeTags")]
pub mod GetCustomizeTags;
#[cfg(feature = "GetLabels")]
pub mod GetLabels;
#[cfg(feature = "GetLongAkskConfig")]
pub mod GetLongAkskConfig;
#[cfg(feature = "GetResourceTags")]
pub mod GetResourceTags;
#[cfg(feature = "HibernateCluster")]
pub mod HibernateCluster;
#[cfg(feature = "ListAccessPolicy")]
pub mod ListAccessPolicy;
#[cfg(feature = "ListAddonInstances")]
pub mod ListAddonInstances;
#[cfg(feature = "ListAddonPrecheckTasks")]
pub mod ListAddonPrecheckTasks;
#[cfg(feature = "ListAddonTemplates")]
pub mod ListAddonTemplates;
#[cfg(feature = "ListAutopilotAddonInstances")]
pub mod ListAutopilotAddonInstances;
#[cfg(feature = "ListAutopilotAddonTemplates")]
pub mod ListAutopilotAddonTemplates;
#[cfg(feature = "ListAutopilotCharts")]
pub mod ListAutopilotCharts;
#[cfg(feature = "ListAutopilotClusterMasterSnapshotTasks")]
pub mod ListAutopilotClusterMasterSnapshotTasks;
#[cfg(feature = "ListAutopilotClusters")]
pub mod ListAutopilotClusters;
#[cfg(feature = "ListAutopilotClusterUpgradeFeatureGates")]
pub mod ListAutopilotClusterUpgradeFeatureGates;
#[cfg(feature = "ListAutopilotClusterUpgradePaths")]
pub mod ListAutopilotClusterUpgradePaths;
#[cfg(feature = "ListAutopilotJobs")]
pub mod ListAutopilotJobs;
#[cfg(feature = "ListAutopilotPreCheckTasks")]
pub mod ListAutopilotPreCheckTasks;
#[cfg(feature = "ListAutopilotReleases")]
pub mod ListAutopilotReleases;
#[cfg(feature = "ListAutopilotUpgradeClusterTasks")]
pub mod ListAutopilotUpgradeClusterTasks;
#[cfg(feature = "ListAutopilotUpgradePlans")]
pub mod ListAutopilotUpgradePlans;
#[cfg(feature = "ListAutopilotUpgradeWorkFlows")]
pub mod ListAutopilotUpgradeWorkFlows;
#[cfg(feature = "ListCharts")]
pub mod ListCharts;
#[cfg(feature = "ListClusterMasterSnapshotTasks")]
pub mod ListClusterMasterSnapshotTasks;
#[cfg(feature = "ListClusters")]
pub mod ListClusters;
#[cfg(feature = "ListClusterUpgradeFeatureGates")]
pub mod ListClusterUpgradeFeatureGates;
#[cfg(feature = "ListClusterUpgradePaths")]
pub mod ListClusterUpgradePaths;
#[cfg(feature = "ListHyperNodes")]
pub mod ListHyperNodes;
#[cfg(feature = "ListImageCaches")]
pub mod ListImageCaches;
#[cfg(feature = "ListNodePools")]
pub mod ListNodePools;
#[cfg(feature = "ListNodes")]
pub mod ListNodes;
#[cfg(feature = "ListPackageProducts")]
pub mod ListPackageProducts;
#[cfg(feature = "ListPartitions")]
pub mod ListPartitions;
#[cfg(feature = "ListPreCheckTasks")]
pub mod ListPreCheckTasks;
#[cfg(feature = "ListReleases")]
pub mod ListReleases;
#[cfg(feature = "ListUpgradeClusterTasks")]
pub mod ListUpgradeClusterTasks;
#[cfg(feature = "ListUpgradeWorkFlows")]
pub mod ListUpgradeWorkFlows;
#[cfg(feature = "LockNodepoolNodeScaleDown")]
pub mod LockNodepoolNodeScaleDown;
#[cfg(feature = "MigrateNode")]
pub mod MigrateNode;
#[cfg(feature = "MigrateToNodePool")]
pub mod MigrateToNodePool;
#[cfg(feature = "PauseUpgradeClusterTask")]
pub mod PauseUpgradeClusterTask;
#[cfg(feature = "RemoveNode")]
pub mod RemoveNode;
#[cfg(feature = "ResetNode")]
pub mod ResetNode;
#[cfg(feature = "ResizeCluster")]
pub mod ResizeCluster;
