#[cfg(feature = "BatchGetKv")]
pub mod BatchGetKv;
#[cfg(feature = "BatchWriteKv")]
pub mod BatchWriteKv;
#[cfg(feature = "CheckHealth")]
pub mod CheckHealth;
#[cfg(feature = "CreateTable")]
pub mod CreateTable;
#[cfg(feature = "DeleteKv")]
pub mod DeleteKv;
#[cfg(feature = "DeleteTable")]
pub mod DeleteTable;
#[cfg(feature = "DescribeTable")]
pub mod DescribeTable;
#[cfg(feature = "GetKv")]
pub mod GetKv;
#[cfg(feature = "ListStore")]
pub mod ListStore;
#[cfg(feature = "ListTable")]
pub mod ListTable;
#[cfg(feature = "PutKv")]
pub mod PutKv;
#[cfg(feature = "ScanKv")]
pub mod ScanKv;
#[cfg(feature = "ScanSkeyKv")]
pub mod ScanSkeyKv;
#[cfg(feature = "UpdateKv")]
pub mod UpdateKv;
