#[cfg(feature = "BatchWriteKv")]
pub mod BatchWriteKv;
#[cfg(feature = "CreateTable")]
pub mod CreateTable;
#[cfg(feature = "DeleteKv")]
pub mod DeleteKv;
#[cfg(feature = "DescribeTable")]
pub mod DescribeTable;
#[cfg(feature = "GetKv")]
pub mod GetKv;
#[cfg(feature = "ListTable")]
pub mod ListTable;
#[cfg(feature = "PutKv")]
pub mod PutKv;
#[cfg(feature = "ScanKv")]
pub mod ScanKv;
#[cfg(feature = "ScanSkeyKv")]
pub mod ScanSkeyKv;
#[cfg(feature = "UpdateKv")]
pub mod UpdateKv;
