#[cfg(feature = "AutoRenewalResources")]
pub mod AutoRenewalResources;
#[cfg(feature = "CancelAutoRenewalResources")]
pub mod CancelAutoRenewalResources;
#[cfg(feature = "CancelCustomerOrder")]
pub mod CancelCustomerOrder;
#[cfg(feature = "CancelResourcesSubscription")]
pub mod CancelResourcesSubscription;
#[cfg(feature = "ChangeEnterpriseRealnameAuthentication")]
pub mod ChangeEnterpriseRealnameAuthentication;
#[cfg(feature = "CheckUserIdentity")]
pub mod CheckUserIdentity;
#[cfg(feature = "ClaimEnterpriseMultiAccountCoupon")]
pub mod ClaimEnterpriseMultiAccountCoupon;
#[cfg(feature = "CreateEnterpriseProjectAuth")]
pub mod CreateEnterpriseProjectAuth;
#[cfg(feature = "CreateEnterpriseRealnameAuthentication")]
pub mod CreateEnterpriseRealnameAuthentication;
#[cfg(feature = "CreatePartnerCoupons")]
pub mod CreatePartnerCoupons;
#[cfg(feature = "CreatePersonalRealnameAuth")]
pub mod CreatePersonalRealnameAuth;
#[cfg(feature = "CreateSubCustomer")]
pub mod CreateSubCustomer;
#[cfg(feature = "CreateSubEnterpriseAccount")]
pub mod CreateSubEnterpriseAccount;
#[cfg(feature = "ListCities")]
pub mod ListCities;
#[cfg(feature = "ListConsumeSubCustomers")]
pub mod ListConsumeSubCustomers;
#[cfg(feature = "ListConversions")]
pub mod ListConversions;
#[cfg(feature = "ListCosts")]
pub mod ListCosts;
#[cfg(feature = "ListCounties")]
pub mod ListCounties;
#[cfg(feature = "ListCouponQuotasRecords")]
pub mod ListCouponQuotasRecords;
#[cfg(feature = "ListCustomerAccountChangeRecords")]
pub mod ListCustomerAccountChangeRecords;
#[cfg(feature = "ListCustomerBillsFeeRecords")]
pub mod ListCustomerBillsFeeRecords;
#[cfg(feature = "ListCustomerBillsMonthlyBreakDown")]
pub mod ListCustomerBillsMonthlyBreakDown;
#[cfg(feature = "ListCustomerOnDemandResources")]
pub mod ListCustomerOnDemandResources;
#[cfg(feature = "ListCustomerOrders")]
pub mod ListCustomerOrders;
#[cfg(feature = "ListCustomersBalancesDetail")]
pub mod ListCustomersBalancesDetail;
#[cfg(feature = "ListCustomerselfResourceRecordDetails")]
pub mod ListCustomerselfResourceRecordDetails;
#[cfg(feature = "ListCustomerselfResourceRecords")]
pub mod ListCustomerselfResourceRecords;
#[cfg(feature = "ListEnterpriseMultiAccount")]
pub mod ListEnterpriseMultiAccount;
#[cfg(feature = "ListEnterpriseOrganizations")]
pub mod ListEnterpriseOrganizations;
#[cfg(feature = "ListEnterpriseSubCustomers")]
pub mod ListEnterpriseSubCustomers;
#[cfg(feature = "ListFreeResourceInfos")]
pub mod ListFreeResourceInfos;
#[cfg(feature = "ListFreeResourcesUsageRecords")]
pub mod ListFreeResourcesUsageRecords;
#[cfg(feature = "ListFreeResourceUsages")]
pub mod ListFreeResourceUsages;
#[cfg(feature = "ListIncentiveDiscountPolicies")]
pub mod ListIncentiveDiscountPolicies;
#[cfg(feature = "ListIndirectPartners")]
pub mod ListIndirectPartners;
#[cfg(feature = "ListIssuedCouponQuotas")]
pub mod ListIssuedCouponQuotas;
#[cfg(feature = "ListIssuedPartnerCoupons")]
pub mod ListIssuedPartnerCoupons;
#[cfg(feature = "ListMeasureUnits")]
pub mod ListMeasureUnits;
#[cfg(feature = "ListMultiAccountRetrieveCoupons")]
pub mod ListMultiAccountRetrieveCoupons;
#[cfg(feature = "ListMultiAccountTransferCoupons")]
pub mod ListMultiAccountTransferCoupons;
#[cfg(feature = "ListOnDemandResourceRatings")]
pub mod ListOnDemandResourceRatings;
#[cfg(feature = "ListOrderCouponsByOrderId")]
pub mod ListOrderCouponsByOrderId;
#[cfg(feature = "ListOrderDiscounts")]
pub mod ListOrderDiscounts;
#[cfg(feature = "ListPartnerAccountChangeRecords")]
pub mod ListPartnerAccountChangeRecords;
#[cfg(feature = "ListPartnerAdjustRecords")]
pub mod ListPartnerAdjustRecords;
#[cfg(feature = "ListPartnerBalances")]
pub mod ListPartnerBalances;
#[cfg(feature = "ListPartnerCouponsRecord")]
pub mod ListPartnerCouponsRecord;
#[cfg(feature = "ListPayPerUseCustomerResources")]
pub mod ListPayPerUseCustomerResources;
#[cfg(feature = "ListProvinces")]
pub mod ListProvinces;
#[cfg(feature = "ListQuotaCoupons")]
pub mod ListQuotaCoupons;
#[cfg(feature = "ListRateOnPeriodDetail")]
pub mod ListRateOnPeriodDetail;
#[cfg(feature = "ListRenewRateOnPeriod")]
pub mod ListRenewRateOnPeriod;
#[cfg(feature = "ListResourceTypes")]
pub mod ListResourceTypes;
#[cfg(feature = "ListResourceUsage")]
pub mod ListResourceUsage;
#[cfg(feature = "ListResourceUsageSummary")]
pub mod ListResourceUsageSummary;
#[cfg(feature = "ListServiceResources")]
pub mod ListServiceResources;
#[cfg(feature = "ListServiceTypes")]
pub mod ListServiceTypes;
#[cfg(feature = "ListStoredValueCards")]
pub mod ListStoredValueCards;
#[cfg(feature = "ListSubCustomerBillDetail")]
pub mod ListSubCustomerBillDetail;
#[cfg(feature = "ListSubCustomerCoupons")]
pub mod ListSubCustomerCoupons;
#[cfg(feature = "ListSubcustomerMonthlyBills")]
pub mod ListSubcustomerMonthlyBills;
#[cfg(feature = "ListSubCustomerNewTag")]
pub mod ListSubCustomerNewTag;
#[cfg(feature = "ListSubCustomers")]
pub mod ListSubCustomers;
#[cfg(feature = "ListUsageTypes")]
pub mod ListUsageTypes;
#[cfg(feature = "PayOrders")]
pub mod PayOrders;
#[cfg(feature = "ReclaimCouponQuotas")]
pub mod ReclaimCouponQuotas;
#[cfg(feature = "ReclaimEnterpriseMultiAccountCoupon")]
pub mod ReclaimEnterpriseMultiAccountCoupon;
#[cfg(feature = "ReclaimIndirectPartnerAccount")]
pub mod ReclaimIndirectPartnerAccount;
#[cfg(feature = "ReclaimPartnerCoupons")]
pub mod ReclaimPartnerCoupons;
#[cfg(feature = "ReclaimSubEnterpriseAmount")]
pub mod ReclaimSubEnterpriseAmount;
#[cfg(feature = "ReclaimToPartnerAccount")]
pub mod ReclaimToPartnerAccount;
#[cfg(feature = "RenewalResources")]
pub mod RenewalResources;
#[cfg(feature = "SendSmsVerificationCode")]
pub mod SendSmsVerificationCode;
#[cfg(feature = "SendVerificationMessageCode")]
pub mod SendVerificationMessageCode;
#[cfg(feature = "SetResourcesRenewConfig")]
pub mod SetResourcesRenewConfig;
#[cfg(feature = "ShowCustomerAccountBalances")]
pub mod ShowCustomerAccountBalances;
#[cfg(feature = "ShowCustomerMonthlySum")]
pub mod ShowCustomerMonthlySum;
#[cfg(feature = "ShowCustomerOrderDetails")]
pub mod ShowCustomerOrderDetails;
#[cfg(feature = "ShowMultiAccountTransferAmount")]
pub mod ShowMultiAccountTransferAmount;
#[cfg(feature = "ShowRealnameAuthenticationReviewResult")]
pub mod ShowRealnameAuthenticationReviewResult;
#[cfg(feature = "ShowRefundOrderDetails")]
pub mod ShowRefundOrderDetails;
#[cfg(feature = "UpdateCouponQuotas")]
pub mod UpdateCouponQuotas;
#[cfg(feature = "UpdateCustomerAccountAmount")]
pub mod UpdateCustomerAccountAmount;
#[cfg(feature = "UpdateIndirectPartnerAccount")]
pub mod UpdateIndirectPartnerAccount;
#[cfg(feature = "UpdatePeriodToOnDemand")]
pub mod UpdatePeriodToOnDemand;
#[cfg(feature = "UpdateSubEnterpriseAmount")]
pub mod UpdateSubEnterpriseAmount;
