#[cfg(feature = "BatchShowIpBelongs")]
pub mod BatchShowIpBelongs;
#[cfg(feature = "CreateDomain")]
pub mod CreateDomain;
#[cfg(feature = "CreateDomainMapping")]
pub mod CreateDomainMapping;
#[cfg(feature = "CreateFlowOutput")]
pub mod CreateFlowOutput;
#[cfg(feature = "CreateFlows")]
pub mod CreateFlows;
#[cfg(feature = "CreateOttChannelInfo")]
pub mod CreateOttChannelInfo;
#[cfg(feature = "CreateRecordCallbackConfig")]
pub mod CreateRecordCallbackConfig;
#[cfg(feature = "CreateRecordIndex")]
pub mod CreateRecordIndex;
#[cfg(feature = "CreateRecordRule")]
pub mod CreateRecordRule;
#[cfg(feature = "CreateSnapshotConfig")]
pub mod CreateSnapshotConfig;
#[cfg(feature = "CreateStreamForbidden")]
pub mod CreateStreamForbidden;
#[cfg(feature = "CreateStreamForbiddenOnce")]
pub mod CreateStreamForbiddenOnce;
#[cfg(feature = "CreateTranscodingsTemplate")]
pub mod CreateTranscodingsTemplate;
#[cfg(feature = "CreateUrlAuthchain")]
pub mod CreateUrlAuthchain;
#[cfg(feature = "DeleteDomain")]
pub mod DeleteDomain;
#[cfg(feature = "DeleteDomainHttpsCert")]
pub mod DeleteDomainHttpsCert;
#[cfg(feature = "DeleteDomainKeyChain")]
pub mod DeleteDomainKeyChain;
#[cfg(feature = "DeleteDomainMapping")]
pub mod DeleteDomainMapping;
#[cfg(feature = "DeleteFlow")]
pub mod DeleteFlow;
#[cfg(feature = "DeleteFlowOutput")]
pub mod DeleteFlowOutput;
#[cfg(feature = "DeleteOttChannelInfo")]
pub mod DeleteOttChannelInfo;
#[cfg(feature = "DeletePublishTemplate")]
pub mod DeletePublishTemplate;
#[cfg(feature = "DeleteRecordCallbackConfig")]
pub mod DeleteRecordCallbackConfig;
#[cfg(feature = "DeleteRecordRule")]
pub mod DeleteRecordRule;
#[cfg(feature = "DeleteRefererChain")]
pub mod DeleteRefererChain;
#[cfg(feature = "DeleteSnapshotConfig")]
pub mod DeleteSnapshotConfig;
#[cfg(feature = "DeleteStreamForbidden")]
pub mod DeleteStreamForbidden;
#[cfg(feature = "DeleteTranscodingsTemplate")]
pub mod DeleteTranscodingsTemplate;
#[cfg(feature = "ListAreaDetail")]
pub mod ListAreaDetail;
#[cfg(feature = "ListBandwidthDetail")]
pub mod ListBandwidthDetail;
#[cfg(feature = "ListCesDimsInfo")]
pub mod ListCesDimsInfo;
#[cfg(feature = "ListCesInstance")]
pub mod ListCesInstance;
#[cfg(feature = "ListDelayConfig")]
pub mod ListDelayConfig;
#[cfg(feature = "ListDomainBandwidthPeak")]
pub mod ListDomainBandwidthPeak;
#[cfg(feature = "ListDomainTrafficDetail")]
pub mod ListDomainTrafficDetail;
#[cfg(feature = "ListDomainTrafficSummary")]
pub mod ListDomainTrafficSummary;
#[cfg(feature = "ListFlows")]
pub mod ListFlows;
#[cfg(feature = "ListGeoBlockingConfig")]
pub mod ListGeoBlockingConfig;
#[cfg(feature = "ListHistoryStreams")]
pub mod ListHistoryStreams;
#[cfg(feature = "ListHlsConfig")]
pub mod ListHlsConfig;
#[cfg(feature = "ListIpAuthList")]
pub mod ListIpAuthList;
#[cfg(feature = "ListLiveSampleLogs")]
pub mod ListLiveSampleLogs;
#[cfg(feature = "ListLiveStreamsOnline")]
pub mod ListLiveStreamsOnline;
#[cfg(feature = "ListOttChannelInfo")]
pub mod ListOttChannelInfo;
#[cfg(feature = "ListPlayDomainStreamInfo")]
pub mod ListPlayDomainStreamInfo;
#[cfg(feature = "ListPublishTemplate")]
pub mod ListPublishTemplate;
#[cfg(feature = "ListQueryHttpCode")]
pub mod ListQueryHttpCode;
#[cfg(feature = "ListRecordCallbackConfigs")]
pub mod ListRecordCallbackConfigs;
#[cfg(feature = "ListRecordData")]
pub mod ListRecordData;
#[cfg(feature = "ListRecordRules")]
pub mod ListRecordRules;
#[cfg(feature = "ListSingleStreamBitrate")]
pub mod ListSingleStreamBitrate;
#[cfg(feature = "ListSingleStreamDetail")]
pub mod ListSingleStreamDetail;
#[cfg(feature = "ListSingleStreamFramerate")]
pub mod ListSingleStreamFramerate;
#[cfg(feature = "ListSnapshotConfigs")]
pub mod ListSnapshotConfigs;
#[cfg(feature = "ListSnapshotData")]
pub mod ListSnapshotData;
#[cfg(feature = "ListStreamForbidden")]
pub mod ListStreamForbidden;
#[cfg(feature = "ListTranscodeConcurrencyNum")]
pub mod ListTranscodeConcurrencyNum;
#[cfg(feature = "ListTranscodeData")]
pub mod ListTranscodeData;
#[cfg(feature = "ListUpStreamDetail")]
pub mod ListUpStreamDetail;
#[cfg(feature = "ListUsersOfStream")]
pub mod ListUsersOfStream;
#[cfg(feature = "ModifyFlowOutput")]
pub mod ModifyFlowOutput;
#[cfg(feature = "ModifyFlowSources")]
pub mod ModifyFlowSources;
#[cfg(feature = "ModifyFlowStart")]
pub mod ModifyFlowStart;
#[cfg(feature = "ModifyFlowStop")]
pub mod ModifyFlowStop;
#[cfg(feature = "ModifyOttChannelInfoEncoderSettings")]
pub mod ModifyOttChannelInfoEncoderSettings;
#[cfg(feature = "ModifyOttChannelInfoEndPoints")]
pub mod ModifyOttChannelInfoEndPoints;
#[cfg(feature = "ModifyOttChannelInfoGeneral")]
pub mod ModifyOttChannelInfoGeneral;
#[cfg(feature = "ModifyOttChannelInfoInput")]
pub mod ModifyOttChannelInfoInput;
#[cfg(feature = "ModifyOttChannelInfoRecordSettings")]
pub mod ModifyOttChannelInfoRecordSettings;
#[cfg(feature = "ModifyOttChannelInfoStats")]
pub mod ModifyOttChannelInfoStats;
#[cfg(feature = "RunRecord")]
pub mod RunRecord;
#[cfg(feature = "SetRefererChain")]
pub mod SetRefererChain;
#[cfg(feature = "ShowChannelStatistic")]
pub mod ShowChannelStatistic;
#[cfg(feature = "ShowDomain")]
pub mod ShowDomain;
#[cfg(feature = "ShowDomainHttpsCert")]
pub mod ShowDomainHttpsCert;
#[cfg(feature = "ShowDomainKeyChain")]
pub mod ShowDomainKeyChain;
#[cfg(feature = "ShowFlowDetail")]
pub mod ShowFlowDetail;
#[cfg(feature = "ShowOutputInfo")]
pub mod ShowOutputInfo;
#[cfg(feature = "ShowPullSourcesConfig")]
pub mod ShowPullSourcesConfig;
#[cfg(feature = "ShowRecordCallbackConfig")]
pub mod ShowRecordCallbackConfig;
#[cfg(feature = "ShowRecordRule")]
pub mod ShowRecordRule;
#[cfg(feature = "ShowRefererChain")]
pub mod ShowRefererChain;
#[cfg(feature = "ShowStreamCount")]
pub mod ShowStreamCount;
#[cfg(feature = "ShowStreamPortrait")]
pub mod ShowStreamPortrait;
#[cfg(feature = "ShowTranscodingsTemplate")]
pub mod ShowTranscodingsTemplate;
#[cfg(feature = "ShowUpBandwidth")]
pub mod ShowUpBandwidth;
#[cfg(feature = "UpdateDelayConfig")]
pub mod UpdateDelayConfig;
#[cfg(feature = "UpdateDomain")]
pub mod UpdateDomain;
#[cfg(feature = "UpdateDomainHttpsCert")]
pub mod UpdateDomainHttpsCert;
#[cfg(feature = "UpdateDomainIp6Switch")]
pub mod UpdateDomainIp6Switch;
#[cfg(feature = "UpdateDomainKeyChain")]
pub mod UpdateDomainKeyChain;
#[cfg(feature = "UpdateGeoBlockingConfig")]
pub mod UpdateGeoBlockingConfig;
#[cfg(feature = "UpdateHlsConfig")]
pub mod UpdateHlsConfig;
#[cfg(feature = "UpdateIpAuthList")]
pub mod UpdateIpAuthList;
#[cfg(feature = "UpdateObsBucketAuthorityPublic")]
pub mod UpdateObsBucketAuthorityPublic;
#[cfg(feature = "UpdatePublishTemplate")]
pub mod UpdatePublishTemplate;
#[cfg(feature = "UpdatePullSourcesConfig")]
pub mod UpdatePullSourcesConfig;
#[cfg(feature = "UpdateRecordCallbackConfig")]
pub mod UpdateRecordCallbackConfig;
#[cfg(feature = "UpdateRecordRule")]
pub mod UpdateRecordRule;
#[cfg(feature = "UpdateSnapshotConfig")]
pub mod UpdateSnapshotConfig;
