#[cfg(feature = "AddHbaConfs")]
pub mod AddHbaConfs;
#[cfg(feature = "AddInstanceTags")]
pub mod AddInstanceTags;
#[cfg(feature = "AllowDbPrivileges")]
pub mod AllowDbPrivileges;
#[cfg(feature = "AllowDbRolePrivileges")]
pub mod AllowDbRolePrivileges;
#[cfg(feature = "AttachEip")]
pub mod AttachEip;
#[cfg(feature = "BatchShowUpgradeCandidateVersions")]
pub mod BatchShowUpgradeCandidateVersions;
#[cfg(feature = "BindLtsConfig")]
pub mod BindLtsConfig;
#[cfg(feature = "CancelScheduleTask")]
pub mod CancelScheduleTask;
#[cfg(feature = "CollectWdrSnapshot")]
pub mod CollectWdrSnapshot;
#[cfg(feature = "ConfirmRestoredData")]
pub mod ConfirmRestoredData;
#[cfg(feature = "CopyConfiguration")]
pub mod CopyConfiguration;
#[cfg(feature = "CreateConfigurationTemplate")]
pub mod CreateConfigurationTemplate;
#[cfg(feature = "CreateCrossCloudConstructDisaster")]
pub mod CreateCrossCloudConstructDisaster;
#[cfg(feature = "CreateDatabase")]
pub mod CreateDatabase;
#[cfg(feature = "CreateDatabaseInstance")]
pub mod CreateDatabaseInstance;
#[cfg(feature = "CreateDatabaseSchemas")]
pub mod CreateDatabaseSchemas;
#[cfg(feature = "CreateDbInstance")]
pub mod CreateDbInstance;
#[cfg(feature = "CreateDbRole")]
pub mod CreateDbRole;
#[cfg(feature = "CreateDbUser")]
pub mod CreateDbUser;
#[cfg(feature = "CreateGaussDbInstance")]
pub mod CreateGaussDbInstance;
#[cfg(feature = "CreateInstance")]
pub mod CreateInstance;
#[cfg(feature = "CreateLimitTask")]
pub mod CreateLimitTask;
#[cfg(feature = "CreateManualBackup")]
pub mod CreateManualBackup;
#[cfg(feature = "CreateReadonlyNodes")]
pub mod CreateReadonlyNodes;
#[cfg(feature = "CreateRestoreInstance")]
pub mod CreateRestoreInstance;
#[cfg(feature = "CreateScheduleTask")]
pub mod CreateScheduleTask;
#[cfg(feature = "CreateSlowLogDownload")]
pub mod CreateSlowLogDownload;
#[cfg(feature = "CreateWdrSnapshot")]
pub mod CreateWdrSnapshot;
#[cfg(feature = "DeleteConfiguration")]
pub mod DeleteConfiguration;
#[cfg(feature = "DeleteDatabase")]
pub mod DeleteDatabase;
#[cfg(feature = "DeleteDatabaseSchema")]
pub mod DeleteDatabaseSchema;
#[cfg(feature = "DeleteHbaConfs")]
pub mod DeleteHbaConfs;
#[cfg(feature = "DeleteInstance")]
pub mod DeleteInstance;
#[cfg(feature = "DeleteInstanceTag")]
pub mod DeleteInstanceTag;
#[cfg(feature = "DeleteJob")]
pub mod DeleteJob;
#[cfg(feature = "DeleteLimitTask")]
pub mod DeleteLimitTask;
#[cfg(feature = "DeleteManualBackup")]
pub mod DeleteManualBackup;
#[cfg(feature = "DeleteReadonlyNodes")]
pub mod DeleteReadonlyNodes;
#[cfg(feature = "DeleteScheduleTask")]
pub mod DeleteScheduleTask;
#[cfg(feature = "DownloadBackup")]
pub mod DownloadBackup;
#[cfg(feature = "ExecuteCrossCloudDisasterDataCacheEnd")]
pub mod ExecuteCrossCloudDisasterDataCacheEnd;
#[cfg(feature = "ExecuteCrossCloudDisasterDataCacheStart")]
pub mod ExecuteCrossCloudDisasterDataCacheStart;
#[cfg(feature = "ExecuteCrossCloudDisasterEndSimulation")]
pub mod ExecuteCrossCloudDisasterEndSimulation;
#[cfg(feature = "ExecuteCrossCloudDisasterRecoveryFailover")]
pub mod ExecuteCrossCloudDisasterRecoveryFailover;
#[cfg(feature = "ExecuteCrossCloudDisasterRestore")]
pub mod ExecuteCrossCloudDisasterRestore;
#[cfg(feature = "ExecuteCrossCloudDisasterStartSimulation")]
pub mod ExecuteCrossCloudDisasterStartSimulation;
#[cfg(feature = "ExecuteCrossCloudDisasterSwitchover")]
pub mod ExecuteCrossCloudDisasterSwitchover;
#[cfg(feature = "ExecuteCrossCloudReleaseDisaster")]
pub mod ExecuteCrossCloudReleaseDisaster;
#[cfg(feature = "ExportSlowSql")]
pub mod ExportSlowSql;
#[cfg(feature = "InstallKernelPlugin")]
pub mod InstallKernelPlugin;
#[cfg(feature = "ListApplicableInstances")]
pub mod ListApplicableInstances;
#[cfg(feature = "ListAppliedHistories")]
pub mod ListAppliedHistories;
#[cfg(feature = "ListAvailableFlavors")]
pub mod ListAvailableFlavors;
#[cfg(feature = "ListBackups")]
pub mod ListBackups;
#[cfg(feature = "ListBackupsDetails")]
pub mod ListBackupsDetails;
#[cfg(feature = "ListBindedEips")]
pub mod ListBindedEips;
#[cfg(feature = "ListCnInfosBeforeReduce")]
pub mod ListCnInfosBeforeReduce;
#[cfg(feature = "ListComponentInfos")]
pub mod ListComponentInfos;
#[cfg(feature = "ListConfigurations")]
pub mod ListConfigurations;
#[cfg(feature = "ListConfigurationsDiff")]
pub mod ListConfigurationsDiff;
#[cfg(feature = "ListDatabaseInstances")]
pub mod ListDatabaseInstances;
#[cfg(feature = "ListDatabaseRoles")]
pub mod ListDatabaseRoles;
#[cfg(feature = "ListDatabases")]
pub mod ListDatabases;
#[cfg(feature = "ListDatabaseSchemas")]
pub mod ListDatabaseSchemas;
#[cfg(feature = "ListDatabaseSchemaTables")]
pub mod ListDatabaseSchemaTables;
#[cfg(feature = "ListDatabaseVolumeSummary")]
pub mod ListDatabaseVolumeSummary;
#[cfg(feature = "ListDatastores")]
pub mod ListDatastores;
#[cfg(feature = "ListDatastoresDetails")]
pub mod ListDatastoresDetails;
#[cfg(feature = "ListDbBackups")]
pub mod ListDbBackups;
#[cfg(feature = "ListDbFlavors")]
pub mod ListDbFlavors;
#[cfg(feature = "ListDbUsers")]
pub mod ListDbUsers;
#[cfg(feature = "ListDisasterRecoveryRecord")]
pub mod ListDisasterRecoveryRecord;
#[cfg(feature = "ListEnhanceFullSqlStatistics")]
pub mod ListEnhanceFullSqlStatistics;
#[cfg(feature = "ListEpsQuotas")]
pub mod ListEpsQuotas;
#[cfg(feature = "ListFeatures")]
pub mod ListFeatures;
#[cfg(feature = "ListFlavors")]
pub mod ListFlavors;
#[cfg(feature = "ListFlavorsDetails")]
pub mod ListFlavorsDetails;
#[cfg(feature = "ListGaussDbDatastores")]
pub mod ListGaussDbDatastores;
#[cfg(feature = "ListHbaInfoHistory")]
pub mod ListHbaInfoHistory;
#[cfg(feature = "ListHbaInfos")]
pub mod ListHbaInfos;
#[cfg(feature = "ListHistoryOperations")]
pub mod ListHistoryOperations;
#[cfg(feature = "ListInstanceDetails")]
pub mod ListInstanceDetails;
#[cfg(feature = "ListInstanceEngineDetail")]
pub mod ListInstanceEngineDetail;
#[cfg(feature = "ListInstanceErrorLogs")]
pub mod ListInstanceErrorLogs;
#[cfg(feature = "ListInstances")]
pub mod ListInstances;
#[cfg(feature = "ListInstancesDetails")]
pub mod ListInstancesDetails;
#[cfg(feature = "ListInstanceTags")]
pub mod ListInstanceTags;
#[cfg(feature = "ListKernelPlugins")]
pub mod ListKernelPlugins;
#[cfg(feature = "ListKeyViewExecuteNode")]
pub mod ListKeyViewExecuteNode;
#[cfg(feature = "ListKmsTdeKey")]
pub mod ListKmsTdeKey;
#[cfg(feature = "ListLimitTask")]
pub mod ListLimitTask;
#[cfg(feature = "ListLtsConfigs")]
pub mod ListLtsConfigs;
#[cfg(feature = "ListMetricDatas")]
pub mod ListMetricDatas;
#[cfg(feature = "ListNodeLimitSqlModel")]
pub mod ListNodeLimitSqlModel;
#[cfg(feature = "ListParameterGroupTemplates")]
pub mod ListParameterGroupTemplates;
#[cfg(feature = "ListParamGroupTemplates")]
pub mod ListParamGroupTemplates;
#[cfg(feature = "ListPluginExtensions")]
pub mod ListPluginExtensions;
#[cfg(feature = "ListPredefinedTags")]
pub mod ListPredefinedTags;
#[cfg(feature = "ListProjectTags")]
pub mod ListProjectTags;
#[cfg(feature = "ListReadonlyNodes")]
pub mod ListReadonlyNodes;
