[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddAuditAgent = []
AddAuditAgentNew = []
AddAuditDatabase = []
AddAuditDatabaseNew = []
AddRdsDatabase = []
AddRdsDatabaseNew = []
AddRdsNoAgentDatabase = []
BatchAddAuditWhitelist = []
BatchAddResourceTag = []
BatchDeleteAuditScope = []
BatchDeleteResourceTag = []
BatchSetAuditAlarmLogStatus = []
BindDbEncryptEip = []
BindDbOmEip = []
ChangeDbEncryptSecurityGroup = []
ChangeDbOmSecurityGroup = []
ConfirmUpgradeAudit = []
CountDbAccountSession = []
CountDbClientSession = []
CountInjectionStatistics = []
CountOperationStatistics = []
CountResourceInstanceByTag = []
CountRiskTrendStatistics = []
CountSessionStatistics = []
CountSqlStatistics = []
CountSqlTrendStatistics = []
CreateAuditDbAgent = []
CreateAuditRiskRule = []
CreateAuditScopeRule = []
CreateAuditSqlRule = []
CreateDbEncryptInstancePeriod = []
CreateDbOmInstancePeriod = []
CreateInstancesPeriodOrder = []
CreateInstancesPeriodOrderNew = []
CreateReport = []
CreateSensitiveMaskRule = []
DeleteAuditAgent = []
DeleteAuditAgentNew = []
DeleteAuditAlarmLog = []
DeleteAuditBackupTask = []
DeleteAuditDatabase = []
DeleteAuditDatabaseNew = []
DeleteAuditReport = []
DeleteAuditRuleRisk = []
DeleteAuditRuleSql = []
DeleteAuditScope = []
DeleteAuditWhitelist = []
DeleteDbEncryptInstance = []
DeleteDbOmInstance = []
DeleteInstances = []
DeleteInstancesNew = []
DeleteSensitiveRules = []
DownloadAuditAgent = []
DownloadAuditAgentNew = []
DownloadAuditReport = []
ListAlarmTopicConfigInfo = []
ListAlarmTopicConfigInfoNew = []
ListAuditAgent = []
ListAuditAgentNew = []
ListAuditAlarmLog = []
ListAuditAlarmLogNew = []
ListAuditBackupInfo = []
ListAuditBackupRiskTemplates = []
ListAuditDatabases = []
ListAuditDatabasesNew = []
ListAuditInstanceJobs = []
ListAuditInstanceJobsNew = []
ListAuditInstances = []
ListAuditInstancesNew = []
ListAuditObsBuckets = []
ListAuditOperateLogs = []
ListAuditOperateLogsNew = []
ListAuditReportTemplates = []
ListAuditReports = []
ListAuditRuleRisks = []
ListAuditRuleRisksNew = []
ListAuditRuleScopes = []
ListAuditRuleScopesNew = []
ListAuditSensitiveMasks = []
ListAuditSensitiveMasksNew = []
ListAuditSqls = []
ListAuditSqlsNew = []
ListAuditSummaryInfos = []
ListAuditTags = []
ListAuditTrendHistory = []
ListAvailabilityZoneInfos = []
ListAvailabilityZoneInfosNew = []
ListDbEncryptInstances = []
ListEcsSpecification = []
ListEcsSpecificationNew = []
ListInstances = []
ListProjectResourceTags = []
ListRdsDatabases = []
ListResourceInstanceByTag = []
ListSqlInjectionRules = []
ListSqlInjectionRulesNew = []
ListWhitelists = []
RebootAuditInstance = []
RebootAuditInstanceNew = []
RebootDbEncryptInstance = []
full = ["AddAuditAgent", "AddAuditAgentNew", "AddAuditDatabase", "AddAuditDatabaseNew", "AddRdsDatabase", "AddRdsDatabaseNew", "AddRdsNoAgentDatabase", "BatchAddAuditWhitelist", "BatchAddResourceTag", "BatchDeleteAuditScope", "BatchDeleteResourceTag", "BatchSetAuditAlarmLogStatus", "BindDbEncryptEip", "BindDbOmEip", "ChangeDbEncryptSecurityGroup", "ChangeDbOmSecurityGroup", "ConfirmUpgradeAudit", "CountDbAccountSession", "CountDbClientSession", "CountInjectionStatistics", "CountOperationStatistics", "CountResourceInstanceByTag", "CountRiskTrendStatistics", "CountSessionStatistics", "CountSqlStatistics", "CountSqlTrendStatistics", "CreateAuditDbAgent", "CreateAuditRiskRule", "CreateAuditScopeRule", "CreateAuditSqlRule", "CreateDbEncryptInstancePeriod", "CreateDbOmInstancePeriod", "CreateInstancesPeriodOrder", "CreateInstancesPeriodOrderNew", "CreateReport", "CreateSensitiveMaskRule", "DeleteAuditAgent", "DeleteAuditAgentNew", "DeleteAuditAlarmLog", "DeleteAuditBackupTask", "DeleteAuditDatabase", "DeleteAuditDatabaseNew", "DeleteAuditReport", "DeleteAuditRuleRisk", "DeleteAuditRuleSql", "DeleteAuditScope", "DeleteAuditWhitelist", "DeleteDbEncryptInstance", "DeleteDbOmInstance", "DeleteInstances", "DeleteInstancesNew", "DeleteSensitiveRules", "DownloadAuditAgent", "DownloadAuditAgentNew", "DownloadAuditReport", "ListAlarmTopicConfigInfo", "ListAlarmTopicConfigInfoNew", "ListAuditAgent", "ListAuditAgentNew", "ListAuditAlarmLog", "ListAuditAlarmLogNew", "ListAuditBackupInfo", "ListAuditBackupRiskTemplates", "ListAuditDatabases", "ListAuditDatabasesNew", "ListAuditInstanceJobs", "ListAuditInstanceJobsNew", "ListAuditInstances", "ListAuditInstancesNew", "ListAuditObsBuckets", "ListAuditOperateLogs", "ListAuditOperateLogsNew", "ListAuditReports", "ListAuditReportTemplates", "ListAuditRuleRisks", "ListAuditRuleRisksNew", "ListAuditRuleScopes", "ListAuditRuleScopesNew", "ListAuditSensitiveMasks", "ListAuditSensitiveMasksNew", "ListAuditSqls", "ListAuditSqlsNew", "ListAuditSummaryInfos", "ListAuditTags", "ListAuditTrendHistory", "ListAvailabilityZoneInfos", "ListAvailabilityZoneInfosNew", "ListDbEncryptInstances", "ListEcsSpecification", "ListEcsSpecificationNew", "ListInstances", "ListProjectResourceTags", "ListRdsDatabases", "ListResourceInstanceByTag", "ListSqlInjectionRules", "ListSqlInjectionRulesNew", "ListWhitelists", "RebootAuditInstance", "RebootAuditInstanceNew", "RebootDbEncryptInstance"]

[lib]
name = "huawei_cloud_api_definitions_DBSS"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-DBSS"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
