#[cfg(feature = "CollectAllResourcesSummary")]
pub mod CollectAllResourcesSummary;
#[cfg(feature = "CountAllResources")]
pub mod CountAllResources;
#[cfg(feature = "CreateAggregationAuthorization")]
pub mod CreateAggregationAuthorization;
#[cfg(feature = "CreateConfigurationAggregator")]
pub mod CreateConfigurationAggregator;
#[cfg(feature = "CreateOrganizationPolicyAssignment")]
pub mod CreateOrganizationPolicyAssignment;
#[cfg(feature = "CreatePolicyAssignments")]
pub mod CreatePolicyAssignments;
#[cfg(feature = "CreateStoredQuery")]
pub mod CreateStoredQuery;
#[cfg(feature = "CreateTrackerConfig")]
pub mod CreateTrackerConfig;
#[cfg(feature = "DeleteAggregationAuthorization")]
pub mod DeleteAggregationAuthorization;
#[cfg(feature = "DeleteConfigurationAggregator")]
pub mod DeleteConfigurationAggregator;
#[cfg(feature = "DeleteOrganizationPolicyAssignment")]
pub mod DeleteOrganizationPolicyAssignment;
#[cfg(feature = "DeletePendingAggregationRequest")]
pub mod DeletePendingAggregationRequest;
#[cfg(feature = "DeletePolicyAssignment")]
pub mod DeletePolicyAssignment;
#[cfg(feature = "DeleteStoredQuery")]
pub mod DeleteStoredQuery;
#[cfg(feature = "DeleteTrackerConfig")]
pub mod DeleteTrackerConfig;
#[cfg(feature = "DisablePolicyAssignment")]
pub mod DisablePolicyAssignment;
#[cfg(feature = "EnablePolicyAssignment")]
pub mod EnablePolicyAssignment;
#[cfg(feature = "ListAggregateComplianceByPolicyAssignment")]
pub mod ListAggregateComplianceByPolicyAssignment;
#[cfg(feature = "ListAggregateDiscoveredResources")]
pub mod ListAggregateDiscoveredResources;
#[cfg(feature = "ListAggregationAuthorizations")]
pub mod ListAggregationAuthorizations;
#[cfg(feature = "ListAllResources")]
pub mod ListAllResources;
#[cfg(feature = "ListAllTags")]
pub mod ListAllTags;
#[cfg(feature = "ListBuiltInPolicyDefinitions")]
pub mod ListBuiltInPolicyDefinitions;
#[cfg(feature = "ListConfigurationAggregators")]
pub mod ListConfigurationAggregators;
#[cfg(feature = "ListOrganizationPolicyAssignments")]
pub mod ListOrganizationPolicyAssignments;
#[cfg(feature = "ListPendingAggregationRequests")]
pub mod ListPendingAggregationRequests;
#[cfg(feature = "ListPolicyAssignments")]
pub mod ListPolicyAssignments;
#[cfg(feature = "ListPolicyStatesByAssignmentId")]
pub mod ListPolicyStatesByAssignmentId;
#[cfg(feature = "ListPolicyStatesByDomainId")]
pub mod ListPolicyStatesByDomainId;
#[cfg(feature = "ListPolicyStatesByResourceId")]
pub mod ListPolicyStatesByResourceId;
#[cfg(feature = "ListProviders")]
pub mod ListProviders;
#[cfg(feature = "ListRegions")]
pub mod ListRegions;
#[cfg(feature = "ListResources")]
pub mod ListResources;
#[cfg(feature = "ListSchemas")]
pub mod ListSchemas;
#[cfg(feature = "ListStoredQueries")]
pub mod ListStoredQueries;
#[cfg(feature = "RunAggregateResourceQuery")]
pub mod RunAggregateResourceQuery;
#[cfg(feature = "RunEvaluationByPolicyAssignmentId")]
pub mod RunEvaluationByPolicyAssignmentId;
#[cfg(feature = "RunQuery")]
pub mod RunQuery;
#[cfg(feature = "ShowAggregateComplianceDetailsByPolicyAssignment")]
pub mod ShowAggregateComplianceDetailsByPolicyAssignment;
#[cfg(feature = "ShowAggregateDiscoveredResourceCounts")]
pub mod ShowAggregateDiscoveredResourceCounts;
#[cfg(feature = "ShowAggregatePolicyAssignmentDetail")]
pub mod ShowAggregatePolicyAssignmentDetail;
#[cfg(feature = "ShowAggregatePolicyStateComplianceSummary")]
pub mod ShowAggregatePolicyStateComplianceSummary;
#[cfg(feature = "ShowAggregateResourceConfig")]
pub mod ShowAggregateResourceConfig;
#[cfg(feature = "ShowBuiltInPolicyDefinition")]
pub mod ShowBuiltInPolicyDefinition;
#[cfg(feature = "ShowConfigurationAggregator")]
pub mod ShowConfigurationAggregator;
#[cfg(feature = "ShowConfigurationAggregatorSourcesStatus")]
pub mod ShowConfigurationAggregatorSourcesStatus;
#[cfg(feature = "ShowEvaluationStateByAssignmentId")]
pub mod ShowEvaluationStateByAssignmentId;
#[cfg(feature = "ShowOrganizationPolicyAssignment")]
pub mod ShowOrganizationPolicyAssignment;
#[cfg(feature = "ShowOrganizationPolicyAssignmentDetailedStatus")]
pub mod ShowOrganizationPolicyAssignmentDetailedStatus;
#[cfg(feature = "ShowOrganizationPolicyAssignmentStatuses")]
pub mod ShowOrganizationPolicyAssignmentStatuses;
#[cfg(feature = "ShowPolicyAssignment")]
pub mod ShowPolicyAssignment;
#[cfg(feature = "ShowResourceById")]
pub mod ShowResourceById;
#[cfg(feature = "ShowResourceDetail")]
pub mod ShowResourceDetail;
#[cfg(feature = "ShowResourceHistory")]
pub mod ShowResourceHistory;
#[cfg(feature = "ShowResourceRelations")]
pub mod ShowResourceRelations;
#[cfg(feature = "ShowResourceRelationsDetail")]
pub mod ShowResourceRelationsDetail;
#[cfg(feature = "ShowStoredQuery")]
pub mod ShowStoredQuery;
#[cfg(feature = "ShowTrackerConfig")]
pub mod ShowTrackerConfig;
#[cfg(feature = "UpdateConfigurationAggregator")]
pub mod UpdateConfigurationAggregator;
#[cfg(feature = "UpdatePolicyAssignment")]
pub mod UpdatePolicyAssignment;
#[cfg(feature = "UpdatePolicyState")]
pub mod UpdatePolicyState;
#[cfg(feature = "UpdateStoredQuery")]
pub mod UpdateStoredQuery;
