[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddAppId = []
AddCorp = []
AddCorpAdmin = []
AddDepartment = []
AddDevice = []
AddMaterial = []
AddProgram = []
AddPublication = []
AddResource = []
AddToPersonalSpace = []
AddUser = []
AllowClientRecord = []
AllowGuestUnmute = []
AllowWaitingParticipant = []
AssociateVmr = []
BatchDeleteCorpAdmins = []
BatchDeleteDevices = []
BatchDeleteMaterials = []
BatchDeletePrograms = []
BatchDeletePublications = []
BatchDeleteUsers = []
BatchHand = []
BatchSearchAppId = []
BatchShowUserDetails = []
BatchUpdateDevicesStatus = []
BatchUpdateUserStatus = []
BroadcastParticipant = []
CancelBroadcast = []
CancelMeeting = []
CancelRecurringMeeting = []
CancelRecurringSubMeeting = []
CheckCallNumberInConf = []
CheckSlideVerifyCode = []
CheckToken = []
CheckVeriCodeForUpdateUserInfo = []
CheckVerifyCode = []
CreateAnonymousAuthRandom = []
CreateAppIdToken = []
CreateAuthRandom = []
CreateConfToken = []
CreateMeeting = []
CreatePortalRefNonce = []
CreateProxyToken = []
CreateRecurringMeeting = []
CreateToken = []
CreateVisionActiveCode = []
CreateWebSocketToken = []
CreateWebinar = []
DeleteAppId = []
DeleteAttendees = []
DeleteCorp = []
DeleteCorpVmr = []
DeleteDepartment = []
DeleteLayout = []
DeleteRecordings = []
DeleteResource = []
DeleteToken = []
DeleteVisionActiveCode = []
DeleteWebHookConfig = []
DeleteWebinar = []
DisassociateVmr = []
Hand = []
HangUp = []
InviteOperateVideo = []
InviteParticipant = []
InviteShare = []
InviteUser = []
InviteWithPwd = []
ListHistoryWebinars = []
ListNetworkQuality = []
ListOngoingWebinars = []
ListOnlineConfAttendee = []
ListUpComingWebinars = []
Live = []
LockMeeting = []
LockView = []
MoveToWaitingRoom = []
MuteMeeting = []
MuteParticipant = []
ProlongMeeting = []
Record = []
RenameParticipant = []
ResetActivecode = []
ResetAppKey = []
ResetPwd = []
ResetPwdByAdmin = []
ResetVisionActiveCode = []
ResumeSimultaneousInterpretation = []
RollcallParticipant = []
SaveLayout = []
SearchAttendanceRecordsOfHisMeeting = []
SearchCorp = []
SearchCorpAdmins = []
SearchCorpDir = []
SearchCorpExternalDir = []
SearchCorpResources = []
SearchCorpVmr = []
SearchCtlRecordsOfHisMeeting = []
SearchDepartmentByName = []
SearchDevices = []
full = ["AddAppId", "AddCorp", "AddCorpAdmin", "AddDepartment", "AddDevice", "AddMaterial", "AddProgram", "AddPublication", "AddResource", "AddToPersonalSpace", "AddUser", "AllowClientRecord", "AllowGuestUnmute", "AllowWaitingParticipant", "AssociateVmr", "BatchDeleteCorpAdmins", "BatchDeleteDevices", "BatchDeleteMaterials", "BatchDeletePrograms", "BatchDeletePublications", "BatchDeleteUsers", "BatchHand", "BatchSearchAppId", "BatchShowUserDetails", "BatchUpdateDevicesStatus", "BatchUpdateUserStatus", "BroadcastParticipant", "CancelBroadcast", "CancelMeeting", "CancelRecurringMeeting", "CancelRecurringSubMeeting", "CheckCallNumberInConf", "CheckSlideVerifyCode", "CheckToken", "CheckVeriCodeForUpdateUserInfo", "CheckVerifyCode", "CreateAnonymousAuthRandom", "CreateAppIdToken", "CreateAuthRandom", "CreateConfToken", "CreateMeeting", "CreatePortalRefNonce", "CreateProxyToken", "CreateRecurringMeeting", "CreateToken", "CreateVisionActiveCode", "CreateWebinar", "CreateWebSocketToken", "DeleteAppId", "DeleteAttendees", "DeleteCorp", "DeleteCorpVmr", "DeleteDepartment", "DeleteLayout", "DeleteRecordings", "DeleteResource", "DeleteToken", "DeleteVisionActiveCode", "DeleteWebHookConfig", "DeleteWebinar", "DisassociateVmr", "Hand", "HangUp", "InviteOperateVideo", "InviteParticipant", "InviteShare", "InviteUser", "InviteWithPwd", "ListHistoryWebinars", "ListNetworkQuality", "ListOngoingWebinars", "ListOnlineConfAttendee", "ListUpComingWebinars", "Live", "LockMeeting", "LockView", "MoveToWaitingRoom", "MuteMeeting", "MuteParticipant", "ProlongMeeting", "Record", "RenameParticipant", "ResetActivecode", "ResetAppKey", "ResetPwd", "ResetPwdByAdmin", "ResetVisionActiveCode", "ResumeSimultaneousInterpretation", "RollcallParticipant", "SaveLayout", "SearchAttendanceRecordsOfHisMeeting", "SearchCorp", "SearchCorpAdmins", "SearchCorpDir", "SearchCorpExternalDir", "SearchCorpResources", "SearchCorpVmr", "SearchCtlRecordsOfHisMeeting", "SearchDepartmentByName", "SearchDevices"]

[lib]
name = "huawei_cloud_api_definitions_Meeting"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-Meeting"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
