#[cfg(feature = "AcceptOrRejectEndpoint")]
pub mod AcceptOrRejectEndpoint;
#[cfg(feature = "AddOrRemoveServicePermissions")]
pub mod AddOrRemoveServicePermissions;
#[cfg(feature = "BatchAddEndpointServicePermissions")]
pub mod BatchAddEndpointServicePermissions;
#[cfg(feature = "BatchAddOrRemoveResourceInstance")]
pub mod BatchAddOrRemoveResourceInstance;
#[cfg(feature = "BatchRemoveEndpointServicePermissions")]
pub mod BatchRemoveEndpointServicePermissions;
#[cfg(feature = "CreateEndpoint")]
pub mod CreateEndpoint;
#[cfg(feature = "CreateEndpointService")]
pub mod CreateEndpointService;
#[cfg(feature = "DeleteEndpoint")]
pub mod DeleteEndpoint;
#[cfg(feature = "DeleteEndpointPolicy")]
pub mod DeleteEndpointPolicy;
#[cfg(feature = "DeleteEndpointService")]
pub mod DeleteEndpointService;
#[cfg(feature = "ListEndpointInfoDetails")]
pub mod ListEndpointInfoDetails;
#[cfg(feature = "ListEndpoints")]
pub mod ListEndpoints;
#[cfg(feature = "ListEndpointService")]
pub mod ListEndpointService;
#[cfg(feature = "ListQueryProjectResourceTags")]
pub mod ListQueryProjectResourceTags;
#[cfg(feature = "ListQuotaDetails")]
pub mod ListQuotaDetails;
#[cfg(feature = "ListResourceInstances")]
pub mod ListResourceInstances;
#[cfg(feature = "ListServiceConnections")]
pub mod ListServiceConnections;
#[cfg(feature = "ListServiceDescribeDetails")]
pub mod ListServiceDescribeDetails;
#[cfg(feature = "ListServiceDetails")]
pub mod ListServiceDetails;
#[cfg(feature = "ListServicePermissionsDetails")]
pub mod ListServicePermissionsDetails;
#[cfg(feature = "ListServicePublicDetails")]
pub mod ListServicePublicDetails;
#[cfg(feature = "ListSpecifiedVersionDetails")]
pub mod ListSpecifiedVersionDetails;
#[cfg(feature = "ListVersionDetails")]
pub mod ListVersionDetails;
#[cfg(feature = "UpdateEndpointConnectionsDesc")]
pub mod UpdateEndpointConnectionsDesc;
#[cfg(feature = "UpdateEndpointPolicy")]
pub mod UpdateEndpointPolicy;
#[cfg(feature = "UpdateEndpointRoutetable")]
pub mod UpdateEndpointRoutetable;
#[cfg(feature = "UpdateEndpointService")]
pub mod UpdateEndpointService;
#[cfg(feature = "UpdateEndpointServiceName")]
pub mod UpdateEndpointServiceName;
#[cfg(feature = "UpdateEndpointServicePermissionDesc")]
pub mod UpdateEndpointServicePermissionDesc;
#[cfg(feature = "UpdateEndpointWhite")]
pub mod UpdateEndpointWhite;
