[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddReadonlyNode = []
AddShardingNode = []
AttachEip = []
AttachInternalIp = []
BatchDeleteBackup = []
BatchTagAction = []
BatchUpgradeDatabaseVersion = []
CancelEip = []
CancelScheduledTask = []
ChangeOpsWindow = []
CheckPassword = []
CheckWeakPassword = []
CompareConfiguration = []
CopyConfiguration = []
CreateConfiguration = []
CreateDatabaseRole = []
CreateDatabaseUser = []
CreateInstance = []
CreateIp = []
CreateKillOpRule = []
CreateManualBackup = []
DeleteAuditLog = []
DeleteConfiguration = []
DeleteDatabaseRole = []
DeleteDatabaseUser = []
DeleteInstance = []
DeleteKillOpRuleList = []
DeleteLtsConfig = []
DeleteManualBackup = []
DeleteMongosNode = []
DeleteReadonlyNode = []
DeleteSession = []
DownloadErrorlog = []
DownloadSlowlog = []
ExpandReplicasetNode = []
ListApiVersion = []
ListAppliedInstances = []
ListAuditlogLinks = []
ListAuditlogs = []
ListAz2Migrate = []
ListBackups = []
ListConfigurations = []
ListDatabaseRoles = []
ListDatabaseUsers = []
ListDatabases = []
ListDatastoreVersions = []
ListErrorLogs = []
ListFlavorInfos = []
ListFlavors = []
ListInstanceTags = []
ListInstances = []
ListInstancesByTags = []
ListLtsConfigs = []
ListLtsErrorLogs = []
ListLtsSlowLogs = []
ListProjectTags = []
ListRecycleInstances = []
ListRestoreCollections = []
ListRestoreDatabases = []
ListRestoreTimes = []
ListScheduledTasks = []
ListSessions = []
ListSlowLogs = []
ListSslCertDownloadAddress = []
ListStorageType = []
ListTasks = []
MigrateAz = []
ResetConfiguration = []
ResetPassword = []
ResizeInstance = []
ResizeInstanceVolume = []
RestartInstance = []
RestoreInstance = []
RestoreInstanceFromCollection = []
RestoreNewInstance = []
SetAuditlogPolicy = []
SetAutoEnlargePolicies = []
SetBackupPolicy = []
SetBalancerSwitch = []
SetBalancerWindow = []
SetRecyclePolicy = []
ShowApiVersion = []
ShowAuditlogPolicy = []
ShowAutoEnlargePolicy = []
ShowBackupDownloadLink = []
ShowBackupPolicy = []
ShowClientNetwork = []
ShowConfigurationAppliedHistory = []
ShowConfigurationModifyHistory = []
ShowConfigurationParameter = []
ShowConnectionStatistics = []
ShowDiskUsage = []
ShowEntityConfiguration = []
ShowInstanceConfigurationModifyHistory = []
ShowJobDetail = []
ShowKillOpRuleRuleList = []
ShowQuotas = []
ShowRecyclePolicy = []
ShowReplSetName = []
ShowSecondLevelMonitoringStatus = []
full = ["AddReadonlyNode", "AddShardingNode", "AttachEip", "AttachInternalIp", "BatchDeleteBackup", "BatchTagAction", "BatchUpgradeDatabaseVersion", "CancelEip", "CancelScheduledTask", "ChangeOpsWindow", "CheckPassword", "CheckWeakPassword", "CompareConfiguration", "CopyConfiguration", "CreateConfiguration", "CreateDatabaseRole", "CreateDatabaseUser", "CreateInstance", "CreateIp", "CreateKillOpRule", "CreateManualBackup", "DeleteAuditLog", "DeleteConfiguration", "DeleteDatabaseRole", "DeleteDatabaseUser", "DeleteInstance", "DeleteKillOpRuleList", "DeleteLtsConfig", "DeleteManualBackup", "DeleteMongosNode", "DeleteReadonlyNode", "DeleteSession", "DownloadErrorlog", "DownloadSlowlog", "ExpandReplicasetNode", "ListApiVersion", "ListAppliedInstances", "ListAuditlogLinks", "ListAuditlogs", "ListAz2Migrate", "ListBackups", "ListConfigurations", "ListDatabaseRoles", "ListDatabases", "ListDatabaseUsers", "ListDatastoreVersions", "ListErrorLogs", "ListFlavorInfos", "ListFlavors", "ListInstances", "ListInstancesByTags", "ListInstanceTags", "ListLtsConfigs", "ListLtsErrorLogs", "ListLtsSlowLogs", "ListProjectTags", "ListRecycleInstances", "ListRestoreCollections", "ListRestoreDatabases", "ListRestoreTimes", "ListScheduledTasks", "ListSessions", "ListSlowLogs", "ListSslCertDownloadAddress", "ListStorageType", "ListTasks", "MigrateAz", "ResetConfiguration", "ResetPassword", "ResizeInstance", "ResizeInstanceVolume", "RestartInstance", "RestoreInstance", "RestoreInstanceFromCollection", "RestoreNewInstance", "SetAuditlogPolicy", "SetAutoEnlargePolicies", "SetBackupPolicy", "SetBalancerSwitch", "SetBalancerWindow", "SetRecyclePolicy", "ShowApiVersion", "ShowAuditlogPolicy", "ShowAutoEnlargePolicy", "ShowBackupDownloadLink", "ShowBackupPolicy", "ShowClientNetwork", "ShowConfigurationAppliedHistory", "ShowConfigurationModifyHistory", "ShowConfigurationParameter", "ShowConnectionStatistics", "ShowDiskUsage", "ShowEntityConfiguration", "ShowInstanceConfigurationModifyHistory", "ShowJobDetail", "ShowKillOpRuleRuleList", "ShowQuotas", "ShowRecyclePolicy", "ShowReplSetName", "ShowSecondLevelMonitoringStatus"]

[lib]
name = "huawei_cloud_api_definitions_DDS"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-DDS"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
