#[cfg(feature = "CreateDcEndpointGroup")]
pub mod CreateDcEndpointGroup;
#[cfg(feature = "CreateDirectConnect")]
pub mod CreateDirectConnect;
#[cfg(feature = "CreateEmergencyChannels")]
pub mod CreateEmergencyChannels;
#[cfg(feature = "CreateHighAvailableGroup")]
pub mod CreateHighAvailableGroup;
#[cfg(feature = "CreateVirtualGateway")]
pub mod CreateVirtualGateway;
#[cfg(feature = "CreateVirtualInterface")]
pub mod CreateVirtualInterface;
#[cfg(feature = "ListDcEndpointGroup")]
pub mod ListDcEndpointGroup;
#[cfg(feature = "ListDirectConnects")]
pub mod ListDirectConnects;
#[cfg(feature = "ListEmergencyChannels")]
pub mod ListEmergencyChannels;
#[cfg(feature = "ListHighAvailableGroups")]
pub mod ListHighAvailableGroups;
#[cfg(feature = "ListHostingDcPreConfigs")]
pub mod ListHostingDcPreConfigs;
#[cfg(feature = "ListVirtualGateways")]
pub mod ListVirtualGateways;
#[cfg(feature = "ListVirtualInterfaces")]
pub mod ListVirtualInterfaces;
#[cfg(feature = "RemoveDcEndpointGroup")]
pub mod RemoveDcEndpointGroup;
#[cfg(feature = "RemoveDirectConnect")]
pub mod RemoveDirectConnect;
#[cfg(feature = "RemoveEmergencyChannel")]
pub mod RemoveEmergencyChannel;
#[cfg(feature = "RemoveHighAvailableGroup")]
pub mod RemoveHighAvailableGroup;
#[cfg(feature = "RemoveVirtualGateway")]
pub mod RemoveVirtualGateway;
#[cfg(feature = "RemoveVirtualInterface")]
pub mod RemoveVirtualInterface;
#[cfg(feature = "ShowDcEndpointGroup")]
pub mod ShowDcEndpointGroup;
#[cfg(feature = "ShowDirectConnect")]
pub mod ShowDirectConnect;
#[cfg(feature = "ShowEmergencyChannel")]
pub mod ShowEmergencyChannel;
#[cfg(feature = "ShowHighAvailableGroup")]
pub mod ShowHighAvailableGroup;
#[cfg(feature = "ShowHostingDcPreconfig")]
pub mod ShowHostingDcPreconfig;
#[cfg(feature = "ShowVirtualGateway")]
pub mod ShowVirtualGateway;
#[cfg(feature = "ShowVirtualInterface")]
pub mod ShowVirtualInterface;
#[cfg(feature = "UpdateDcEndpointGroup")]
pub mod UpdateDcEndpointGroup;
#[cfg(feature = "UpdateDirectConnect")]
pub mod UpdateDirectConnect;
#[cfg(feature = "UpdateEmergencyChannel")]
pub mod UpdateEmergencyChannel;
#[cfg(feature = "UpdateHighAvailableGroup")]
pub mod UpdateHighAvailableGroup;
#[cfg(feature = "UpdateVirtualGateway")]
pub mod UpdateVirtualGateway;
#[cfg(feature = "UpdateVirtualInterface")]
pub mod UpdateVirtualInterface;
