#[cfg(feature = "ApplyConfiguration")]
pub mod ApplyConfiguration;
#[cfg(feature = "ApplyConfigurationToInstances")]
pub mod ApplyConfigurationToInstances;
#[cfg(feature = "BatchDeleteManualBackup")]
pub mod BatchDeleteManualBackup;
#[cfg(feature = "BatchTagAction")]
pub mod BatchTagAction;
#[cfg(feature = "BatchUpgradeDatabaseVersion")]
pub mod BatchUpgradeDatabaseVersion;
#[cfg(feature = "CancelInstanceScheduleWindow")]
pub mod CancelInstanceScheduleWindow;
#[cfg(feature = "CheckDisasterRecoveryOperation")]
pub mod CheckDisasterRecoveryOperation;
#[cfg(feature = "CheckWeekPassword")]
pub mod CheckWeekPassword;
#[cfg(feature = "ClearInstanceSessions")]
pub mod ClearInstanceSessions;
#[cfg(feature = "CompareConfiguration")]
pub mod CompareConfiguration;
#[cfg(feature = "CopyConfiguration")]
pub mod CopyConfiguration;
#[cfg(feature = "CreateBack")]
pub mod CreateBack;
#[cfg(feature = "CreateColdVolume")]
pub mod CreateColdVolume;
#[cfg(feature = "CreateConfiguration")]
pub mod CreateConfiguration;
#[cfg(feature = "CreateDbCacheMapping")]
pub mod CreateDbCacheMapping;
#[cfg(feature = "CreateDbCacheRule")]
pub mod CreateDbCacheRule;
#[cfg(feature = "CreateDbUser")]
pub mod CreateDbUser;
#[cfg(feature = "CreateDisasterRecovery")]
pub mod CreateDisasterRecovery;
#[cfg(feature = "CreateGeminiDbDualActive")]
pub mod CreateGeminiDbDualActive;
#[cfg(feature = "CreateInstance")]
pub mod CreateInstance;
#[cfg(feature = "DeleteBackup")]
pub mod DeleteBackup;
#[cfg(feature = "DeleteConfiguration")]
pub mod DeleteConfiguration;
#[cfg(feature = "DeleteDbCacheMapping")]
pub mod DeleteDbCacheMapping;
#[cfg(feature = "DeleteDbCacheRule")]
pub mod DeleteDbCacheRule;
#[cfg(feature = "DeleteDbUser")]
pub mod DeleteDbUser;
#[cfg(feature = "DeleteDisasterRecovery")]
pub mod DeleteDisasterRecovery;
#[cfg(feature = "DeleteEnlargeFailNode")]
pub mod DeleteEnlargeFailNode;
#[cfg(feature = "DeleteGeminiDbDualActive")]
pub mod DeleteGeminiDbDualActive;
#[cfg(feature = "DeleteInstance")]
pub mod DeleteInstance;
#[cfg(feature = "DeleteInstancesSession")]
pub mod DeleteInstancesSession;
#[cfg(feature = "DeleteLtsConfigs")]
pub mod DeleteLtsConfigs;
#[cfg(feature = "DeleteRedisDisabledCommands")]
pub mod DeleteRedisDisabledCommands;
#[cfg(feature = "ExpandInstanceNode")]
pub mod ExpandInstanceNode;
#[cfg(feature = "ListApiVersion")]
pub mod ListApiVersion;
#[cfg(feature = "ListAvailableFlavorInfos")]
pub mod ListAvailableFlavorInfos;
#[cfg(feature = "ListBackups")]
pub mod ListBackups;
#[cfg(feature = "ListCassandraSlowLogs")]
pub mod ListCassandraSlowLogs;
#[cfg(feature = "ListConfigurationDatastores")]
pub mod ListConfigurationDatastores;
#[cfg(feature = "ListConfigurations")]
pub mod ListConfigurations;
#[cfg(feature = "ListConfigurationTemplates")]
pub mod ListConfigurationTemplates;
#[cfg(feature = "ListDatastores")]
pub mod ListDatastores;
#[cfg(feature = "ListDbCacheMappings")]
pub mod ListDbCacheMappings;
#[cfg(feature = "ListDbCacheRules")]
pub mod ListDbCacheRules;
#[cfg(feature = "ListDbUsers")]
pub mod ListDbUsers;
#[cfg(feature = "ListDedicatedResources")]
pub mod ListDedicatedResources;
#[cfg(feature = "ListEpsQuotas")]
pub mod ListEpsQuotas;
#[cfg(feature = "ListFlavorInfos")]
pub mod ListFlavorInfos;
#[cfg(feature = "ListFlavors")]
pub mod ListFlavors;
#[cfg(feature = "ListInfluxdbSlowLogs")]
pub mod ListInfluxdbSlowLogs;
#[cfg(feature = "ListInstanceDatabases")]
pub mod ListInstanceDatabases;
#[cfg(feature = "ListInstanceMaintenanceWindow")]
pub mod ListInstanceMaintenanceWindow;
#[cfg(feature = "ListInstances")]
pub mod ListInstances;
#[cfg(feature = "ListInstancesByResourceTags")]
pub mod ListInstancesByResourceTags;
#[cfg(feature = "ListInstancesByTags")]
pub mod ListInstancesByTags;
#[cfg(feature = "ListInstanceSessions")]
pub mod ListInstanceSessions;
#[cfg(feature = "ListInstancesSession")]
pub mod ListInstancesSession;
#[cfg(feature = "ListInstancesSessionStatistics")]
pub mod ListInstancesSessionStatistics;
#[cfg(feature = "ListInstanceTags")]
pub mod ListInstanceTags;
#[cfg(feature = "ListJobs")]
pub mod ListJobs;
#[cfg(feature = "ListLtsConfigs")]
pub mod ListLtsConfigs;
#[cfg(feature = "ListMongodbErrorLogs")]
pub mod ListMongodbErrorLogs;
#[cfg(feature = "ListMongodbSlowLogs")]
pub mod ListMongodbSlowLogs;
#[cfg(feature = "ListNosqlTaskList")]
pub mod ListNosqlTaskList;
#[cfg(feature = "ListProjectTags")]
pub mod ListProjectTags;
#[cfg(feature = "ListRecycleInstances")]
pub mod ListRecycleInstances;
#[cfg(feature = "ListRedisPitrRestoreTime")]
pub mod ListRedisPitrRestoreTime;
#[cfg(feature = "ListRedisSlowLogs")]
pub mod ListRedisSlowLogs;
#[cfg(feature = "ListRestoreDatabases")]
pub mod ListRestoreDatabases;
#[cfg(feature = "ListRestoreTables")]
pub mod ListRestoreTables;
#[cfg(feature = "ListRestoreTime")]
pub mod ListRestoreTime;
#[cfg(feature = "ListSlowLogs")]
pub mod ListSlowLogs;
#[cfg(feature = "ListSslCertDownloadAddresses")]
pub mod ListSslCertDownloadAddresses;
#[cfg(feature = "ModifyAutoNodeExpansionPolicy")]
pub mod ModifyAutoNodeExpansionPolicy;
#[cfg(feature = "ModifyDbUserPrivilege")]
pub mod ModifyDbUserPrivilege;
#[cfg(feature = "ModifyEpsQuotas")]
pub mod ModifyEpsQuotas;
#[cfg(feature = "ModifyInstanceMaintenanceWindow")]
pub mod ModifyInstanceMaintenanceWindow;
#[cfg(feature = "ModifyPort")]
pub mod ModifyPort;
#[cfg(feature = "ModifyPublicIp")]
pub mod ModifyPublicIp;
#[cfg(feature = "ModifyVolume")]
pub mod ModifyVolume;
#[cfg(feature = "OfflineNodes")]
pub mod OfflineNodes;
#[cfg(feature = "PauseResumeDataSynchronization")]
pub mod PauseResumeDataSynchronization;
#[cfg(feature = "ResetDbUserPassword")]
pub mod ResetDbUserPassword;
#[cfg(feature = "ResetParamGroupTemplate")]
pub mod ResetParamGroupTemplate;
#[cfg(feature = "ResetPassword")]
pub mod ResetPassword;
#[cfg(feature = "ResizeColdVolume")]
pub mod ResizeColdVolume;
#[cfg(feature = "ResizeInstance")]
pub mod ResizeInstance;
#[cfg(feature = "ResizeInstanceVolume")]
pub mod ResizeInstanceVolume;
#[cfg(feature = "RestartInstance")]
pub mod RestartInstance;
#[cfg(feature = "RestoreExistingInstance")]
pub mod RestoreExistingInstance;
#[cfg(feature = "RestoreRedisData")]
pub mod RestoreRedisData;
#[cfg(feature = "RestoreRedisPitr")]
pub mod RestoreRedisPitr;
#[cfg(feature = "SaveLtsConfigs")]
pub mod SaveLtsConfigs;
#[cfg(feature = "SaveRedisDisabledCommands")]
pub mod SaveRedisDisabledCommands;
#[cfg(feature = "SetAutoEnlargePolicy")]
pub mod SetAutoEnlargePolicy;
#[cfg(feature = "SetBackupPolicy")]
pub mod SetBackupPolicy;
#[cfg(feature = "SetDisasterRecoverySettings")]
pub mod SetDisasterRecoverySettings;
#[cfg(feature = "SetInstanceDataDump")]
pub mod SetInstanceDataDump;
#[cfg(feature = "SetRecyclePolicy")]
pub mod SetRecyclePolicy;
#[cfg(feature = "SetRedisPitrPolicy")]
pub mod SetRedisPitrPolicy;
#[cfg(feature = "ShowAllInstancesBackups")]
pub mod ShowAllInstancesBackups;
