#[cfg(feature = "ChangeAssociatedResourceOpenStatus")]
pub mod ChangeAssociatedResourceOpenStatus;
#[cfg(feature = "CreateAssociatedResourceRules")]
pub mod CreateAssociatedResourceRules;
#[cfg(feature = "CreatePredefineTags")]
pub mod CreatePredefineTags;
#[cfg(feature = "CreateResourceTag")]
pub mod CreateResourceTag;
#[cfg(feature = "DeleteAssociatedResourceRule")]
pub mod DeleteAssociatedResourceRule;
#[cfg(feature = "DeletePredefineTags")]
pub mod DeletePredefineTags;
#[cfg(feature = "DeleteResourceTag")]
pub mod DeleteResourceTag;
#[cfg(feature = "ListApiVersions")]
pub mod ListApiVersions;
#[cfg(feature = "ListAssociatedResourceRules")]
pub mod ListAssociatedResourceRules;
#[cfg(feature = "ListAssociatedResourceSettings")]
pub mod ListAssociatedResourceSettings;
#[cfg(feature = "ListPredefineTags")]
pub mod ListPredefineTags;
#[cfg(feature = "ListProviders")]
pub mod ListProviders;
#[cfg(feature = "ListResource")]
pub mod ListResource;
#[cfg(feature = "ListTagKeys")]
pub mod ListTagKeys;
#[cfg(feature = "ListTags")]
pub mod ListTags;
#[cfg(feature = "ListTagValues")]
pub mod ListTagValues;
#[cfg(feature = "ShowApiVersion")]
pub mod ShowApiVersion;
#[cfg(feature = "ShowAssociatedResourceOpenStatus")]
pub mod ShowAssociatedResourceOpenStatus;
#[cfg(feature = "ShowResourceTag")]
pub mod ShowResourceTag;
#[cfg(feature = "ShowTagQuota")]
pub mod ShowTagQuota;
#[cfg(feature = "UpdateAssociatedResourceRules")]
pub mod UpdateAssociatedResourceRules;
#[cfg(feature = "UpdatePredefineTags")]
pub mod UpdatePredefineTags;
