#[cfg(feature = "CreateAkskCertificate")]
pub mod CreateAkskCertificate;
#[cfg(feature = "CreateDeviceCertificate")]
pub mod CreateDeviceCertificate;
#[cfg(feature = "CreateDeviceChannel")]
pub mod CreateDeviceChannel;
#[cfg(feature = "CreateStream")]
pub mod CreateStream;
#[cfg(feature = "CreateSubscription")]
pub mod CreateSubscription;
#[cfg(feature = "DeleteAkskCertificate")]
pub mod DeleteAkskCertificate;
#[cfg(feature = "DeleteDevice")]
pub mod DeleteDevice;
#[cfg(feature = "DeleteDeviceCertificate")]
pub mod DeleteDeviceCertificate;
#[cfg(feature = "DeleteStream")]
pub mod DeleteStream;
#[cfg(feature = "ListAkskCertificates")]
pub mod ListAkskCertificates;
#[cfg(feature = "ListBucket")]
pub mod ListBucket;
#[cfg(feature = "ListDevices")]
pub mod ListDevices;
#[cfg(feature = "ListDevicesCertificates")]
pub mod ListDevicesCertificates;
#[cfg(feature = "ListLongTermOfflineDevices")]
pub mod ListLongTermOfflineDevices;
#[cfg(feature = "ListNotSendDataDevices")]
pub mod ListNotSendDataDevices;
#[cfg(feature = "ListNvrChannels")]
pub mod ListNvrChannels;
#[cfg(feature = "ListPastOnlineDevices")]
pub mod ListPastOnlineDevices;
#[cfg(feature = "ListShortTermOfflineDevices")]
pub mod ListShortTermOfflineDevices;
#[cfg(feature = "ListStreamInfos")]
pub mod ListStreamInfos;
#[cfg(feature = "ListStreams")]
pub mod ListStreams;
#[cfg(feature = "ListStreamsAddresses")]
pub mod ListStreamsAddresses;
#[cfg(feature = "ListSubscriptions")]
pub mod ListSubscriptions;
#[cfg(feature = "ListTodayDroppedDevices")]
pub mod ListTodayDroppedDevices;
#[cfg(feature = "ListTodayNewOnlineDevices")]
pub mod ListTodayNewOnlineDevices;
#[cfg(feature = "ListTodayPacketReceivedRateDevices")]
pub mod ListTodayPacketReceivedRateDevices;
#[cfg(feature = "UpdateAksk")]
pub mod UpdateAksk;
#[cfg(feature = "UpdateAuthority")]
pub mod UpdateAuthority;
#[cfg(feature = "UpdateDeviceCertificate")]
pub mod UpdateDeviceCertificate;
#[cfg(feature = "UpdateDeviceChannel")]
pub mod UpdateDeviceChannel;
#[cfg(feature = "UpdateDeviceChannelStrategy")]
pub mod UpdateDeviceChannelStrategy;
#[cfg(feature = "UpdateNvrDeviceChannel")]
pub mod UpdateNvrDeviceChannel;
#[cfg(feature = "UpdateRetention")]
pub mod UpdateRetention;
#[cfg(feature = "UpdateStream")]
pub mod UpdateStream;
