[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddFacesByBase64 = []
AddFacesByFile = []
AddFacesByUrl = []
BatchDeleteFaces = []
CompareFaceByBase64 = []
CompareFaceByFile = []
CompareFaceByUrl = []
CreateFaceSet = []
DeleteFaceByExternalImageId = []
DeleteFaceByFaceId = []
DeleteFaceSet = []
DetectFaceByBase64 = []
DetectFaceByFile = []
DetectFaceByUrl = []
DetectLiveByBase64 = []
DetectLiveByFile = []
DetectLiveByUrl = []
DetectLiveFaceByBase64 = []
DetectLiveFaceByFile = []
DetectLiveFaceByUrl = []
SearchFaceByBase64 = []
SearchFaceByFaceId = []
SearchFaceByFile = []
SearchFaceByUrl = []
ShowAllFaceSets = []
ShowFaceSet = []
ShowFacesByFaceId = []
ShowFacesByLimit = []
UpdateFace = []
full = ["AddFacesByBase64", "AddFacesByFile", "AddFacesByUrl", "BatchDeleteFaces", "CompareFaceByBase64", "CompareFaceByFile", "CompareFaceByUrl", "CreateFaceSet", "DeleteFaceByExternalImageId", "DeleteFaceByFaceId", "DeleteFaceSet", "DetectFaceByBase64", "DetectFaceByFile", "DetectFaceByUrl", "DetectLiveByBase64", "DetectLiveByFile", "DetectLiveByUrl", "DetectLiveFaceByBase64", "DetectLiveFaceByFile", "DetectLiveFaceByUrl", "SearchFaceByBase64", "SearchFaceByFaceId", "SearchFaceByFile", "SearchFaceByUrl", "ShowAllFaceSets", "ShowFacesByFaceId", "ShowFacesByLimit", "ShowFaceSet", "UpdateFace"]

[lib]
name = "huawei_cloud_api_definitions_FRS"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-FRS"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
