[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
BatchSetAttributes = []
BatchSetTags = []
CreateAttribute = []
CreateTag = []
DeleteRealName = []
DeleteTag = []
DisableAttribute = []
EnableAttribute = []
EnableSimCard = []
ListAttributes = []
ListBackPoolMembers = []
ListBackPools = []
ListFlowBySimCards = []
ListProPricePlans = []
ListSimCards = []
ListSimPoolMembers = []
ListSimPools = []
ListSimPricePlans = []
ListSmsDetails = []
ListTags = []
ListWorkOrderDetails = []
ListWorkOrders = []
RegisterImei = []
ResetSimCard = []
SendSms = []
SetExceedCutNet = []
SetSpeedValue = []
ShowMonthUsages = []
ShowRealNamed = []
ShowSimCard = []
StartStopNet = []
StopSimCard = []
UpdateAttribute = []
full = ["BatchSetAttributes", "BatchSetTags", "CreateAttribute", "CreateTag", "DeleteRealName", "DeleteTag", "DisableAttribute", "EnableAttribute", "EnableSimCard", "ListAttributes", "ListBackPoolMembers", "ListBackPools", "ListFlowBySimCards", "ListProPricePlans", "ListSimCards", "ListSimPoolMembers", "ListSimPools", "ListSimPricePlans", "ListSmsDetails", "ListTags", "ListWorkOrderDetails", "ListWorkOrders", "RegisterImei", "ResetSimCard", "SendSms", "SetExceedCutNet", "SetSpeedValue", "ShowMonthUsages", "ShowRealNamed", "ShowSimCard", "StartStopNet", "StopSimCard", "UpdateAttribute"]

[lib]
name = "huawei_cloud_api_definitions_GSL"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-GSL"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "0.1.0"
