#[cfg(feature = "AttachCallbackInstanceLifeCycleHook")]
pub mod AttachCallbackInstanceLifeCycleHook;
#[cfg(feature = "BatchAddScalingInstances")]
pub mod BatchAddScalingInstances;
#[cfg(feature = "BatchDeleteScalingConfigs")]
pub mod BatchDeleteScalingConfigs;
#[cfg(feature = "BatchDeleteScalingPolicies")]
pub mod BatchDeleteScalingPolicies;
#[cfg(feature = "BatchPauseScalingPolicies")]
pub mod BatchPauseScalingPolicies;
#[cfg(feature = "BatchProtectScalingInstances")]
pub mod BatchProtectScalingInstances;
#[cfg(feature = "BatchRemoveScalingInstances")]
pub mod BatchRemoveScalingInstances;
#[cfg(feature = "BatchResumeScalingPolicies")]
pub mod BatchResumeScalingPolicies;
#[cfg(feature = "BatchSetScalingInstancesStandby")]
pub mod BatchSetScalingInstancesStandby;
#[cfg(feature = "BatchUnprotectScalingInstances")]
pub mod BatchUnprotectScalingInstances;
#[cfg(feature = "BatchUnsetScalingInstancesStantby")]
pub mod BatchUnsetScalingInstancesStantby;
#[cfg(feature = "CloseWarmPool")]
pub mod CloseWarmPool;
#[cfg(feature = "CloseWarmPoolNew")]
pub mod CloseWarmPoolNew;
#[cfg(feature = "CreateGroupScheduledTask")]
pub mod CreateGroupScheduledTask;
#[cfg(feature = "CreateLifyCycleHook")]
pub mod CreateLifyCycleHook;
#[cfg(feature = "CreateScalingConfig")]
pub mod CreateScalingConfig;
#[cfg(feature = "CreateScalingGroup")]
pub mod CreateScalingGroup;
#[cfg(feature = "CreateScalingNotification")]
pub mod CreateScalingNotification;
#[cfg(feature = "CreateScalingPolicy")]
pub mod CreateScalingPolicy;
#[cfg(feature = "CreateScalingTagInfo")]
pub mod CreateScalingTagInfo;
#[cfg(feature = "CreateScalingV2Policy")]
pub mod CreateScalingV2Policy;
#[cfg(feature = "DeleteGroupScheduledTask")]
pub mod DeleteGroupScheduledTask;
#[cfg(feature = "DeleteLifecycleHook")]
pub mod DeleteLifecycleHook;
#[cfg(feature = "DeleteScalingConfig")]
pub mod DeleteScalingConfig;
#[cfg(feature = "DeleteScalingGroup")]
pub mod DeleteScalingGroup;
#[cfg(feature = "DeleteScalingInstance")]
pub mod DeleteScalingInstance;
#[cfg(feature = "DeleteScalingNotification")]
pub mod DeleteScalingNotification;
#[cfg(feature = "DeleteScalingPolicy")]
pub mod DeleteScalingPolicy;
#[cfg(feature = "DeleteScalingTagInfo")]
pub mod DeleteScalingTagInfo;
#[cfg(feature = "ExecuteScalingPolicy")]
pub mod ExecuteScalingPolicy;
#[cfg(feature = "ListAllScalingV2Policies")]
pub mod ListAllScalingV2Policies;
#[cfg(feature = "ListApiVersions")]
pub mod ListApiVersions;
#[cfg(feature = "ListGroupScheduledTasks")]
pub mod ListGroupScheduledTasks;
#[cfg(feature = "ListHookInstances")]
pub mod ListHookInstances;
#[cfg(feature = "ListLifeCycleHooks")]
pub mod ListLifeCycleHooks;
#[cfg(feature = "ListResourceInstances")]
pub mod ListResourceInstances;
#[cfg(feature = "ListScalingActivityLogs")]
pub mod ListScalingActivityLogs;
#[cfg(feature = "ListScalingActivityV2Logs")]
pub mod ListScalingActivityV2Logs;
#[cfg(feature = "ListScalingConfigs")]
pub mod ListScalingConfigs;
#[cfg(feature = "ListScalingGroups")]
pub mod ListScalingGroups;
#[cfg(feature = "ListScalingInstances")]
pub mod ListScalingInstances;
#[cfg(feature = "ListScalingNotifications")]
pub mod ListScalingNotifications;
#[cfg(feature = "ListScalingPolicies")]
pub mod ListScalingPolicies;
#[cfg(feature = "ListScalingPolicyExecuteLogs")]
pub mod ListScalingPolicyExecuteLogs;
#[cfg(feature = "ListScalingTagInfosByResourceId")]
pub mod ListScalingTagInfosByResourceId;
#[cfg(feature = "ListScalingTagInfosByTenantId")]
pub mod ListScalingTagInfosByTenantId;
#[cfg(feature = "ListScalingV2Policies")]
pub mod ListScalingV2Policies;
#[cfg(feature = "ListWarmPoolInstances")]
pub mod ListWarmPoolInstances;
#[cfg(feature = "ListWarmPoolInstancesNew")]
pub mod ListWarmPoolInstancesNew;
#[cfg(feature = "PauseScalingGroup")]
pub mod PauseScalingGroup;
#[cfg(feature = "PauseScalingPolicy")]
pub mod PauseScalingPolicy;
#[cfg(feature = "PutWarmPool")]
pub mod PutWarmPool;
#[cfg(feature = "PutWarmPoolNew")]
pub mod PutWarmPoolNew;
#[cfg(feature = "ResumeScalingGroup")]
pub mod ResumeScalingGroup;
#[cfg(feature = "ResumeScalingPolicy")]
pub mod ResumeScalingPolicy;
#[cfg(feature = "ShowApiVersion")]
pub mod ShowApiVersion;
#[cfg(feature = "ShowLifeCycleHook")]
pub mod ShowLifeCycleHook;
#[cfg(feature = "ShowPolicyAndInstanceQuota")]
pub mod ShowPolicyAndInstanceQuota;
#[cfg(feature = "ShowResourceQuota")]
pub mod ShowResourceQuota;
#[cfg(feature = "ShowScalingConfig")]
pub mod ShowScalingConfig;
#[cfg(feature = "ShowScalingGroup")]
pub mod ShowScalingGroup;
#[cfg(feature = "ShowScalingPolicy")]
pub mod ShowScalingPolicy;
#[cfg(feature = "ShowScalingV2Policy")]
pub mod ShowScalingV2Policy;
#[cfg(feature = "ShowWarmPool")]
pub mod ShowWarmPool;
#[cfg(feature = "ShowWarmPoolNew")]
pub mod ShowWarmPoolNew;
#[cfg(feature = "UpdateGroupScheduledTask")]
pub mod UpdateGroupScheduledTask;
#[cfg(feature = "UpdateLifeCycleHook")]
pub mod UpdateLifeCycleHook;
#[cfg(feature = "UpdateScalingConfig")]
pub mod UpdateScalingConfig;
#[cfg(feature = "UpdateScalingGroup")]
pub mod UpdateScalingGroup;
#[cfg(feature = "UpdateScalingPolicy")]
pub mod UpdateScalingPolicy;
#[cfg(feature = "UpdateScalingV2Policy")]
pub mod UpdateScalingV2Policy;
