[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddEcnWithEr = []
AddEcnWithIeg = []
AddEcnWithVpc = []
AddVrrpConfig = []
ChangeIegPassword = []
CreateEcnAccessPoint = []
CreateEquipment = []
CreateEquipmentLanConfig = []
CreateEquipmentStaticRouteConfig = []
DeleteEcnAccessPoint = []
DeleteEcnWithEr = []
DeleteEcnWithIeg = []
DeleteEcnWithVpc = []
DeleteEquipment = []
DeleteEquipmentLanConfig = []
DeleteEquipmentStaticRouteConfig = []
DeleteVrrpConfig = []
GenerateInitialConfiguration = []
ListEcn = []
ListEcnAccessPointByEcnId = []
ListEcnWithEr = []
ListEcnWithIeg = []
ListEcnWithVpc = []
ListEquipmentInterfaceName = []
ListEquipments = []
ListIeg = []
RebootEquipment = []
ShowEcnInfo = []
ShowEcnWithIeg = []
ShowEquipmentDnsInfo = []
ShowEquipmentInfo = []
ShowEquipmentLanInfo = []
ShowEquipmentOspf = []
ShowEquipmentSpecificConfig = []
ShowEquipmentStaticRouteInfo = []
ShowEquipmentWanInfo = []
ShowEquipmentWlan = []
ShowIegInfo = []
ShowQuotasInfo = []
ShowVrrpConfig = []
SwitchEquipmentHaType = []
UpdateEcn = []
UpdateEcnAccessPoint = []
UpdateEcnWithVpc = []
UpdateEquipmentDnsInfo = []
UpdateEquipmentEsn = []
UpdateEquipmentInfo = []
UpdateEquipmentLanConfig = []
UpdateEquipmentOspf = []
UpdateEquipmentStaticRouteConfig = []
UpdateEquipmentWanConfig = []
UpdateEquipmentWlan = []
UpdateIeg = []
UpdateVrrpConfig = []
full = ["AddEcnWithEr", "AddEcnWithIeg", "AddEcnWithVpc", "AddVrrpConfig", "ChangeIegPassword", "CreateEcnAccessPoint", "CreateEquipment", "CreateEquipmentLanConfig", "CreateEquipmentStaticRouteConfig", "DeleteEcnAccessPoint", "DeleteEcnWithEr", "DeleteEcnWithIeg", "DeleteEcnWithVpc", "DeleteEquipment", "DeleteEquipmentLanConfig", "DeleteEquipmentStaticRouteConfig", "DeleteVrrpConfig", "GenerateInitialConfiguration", "ListEcn", "ListEcnAccessPointByEcnId", "ListEcnWithEr", "ListEcnWithIeg", "ListEcnWithVpc", "ListEquipmentInterfaceName", "ListEquipments", "ListIeg", "RebootEquipment", "ShowEcnInfo", "ShowEcnWithIeg", "ShowEquipmentDnsInfo", "ShowEquipmentInfo", "ShowEquipmentLanInfo", "ShowEquipmentOspf", "ShowEquipmentSpecificConfig", "ShowEquipmentStaticRouteInfo", "ShowEquipmentWanInfo", "ShowEquipmentWlan", "ShowIegInfo", "ShowQuotasInfo", "ShowVrrpConfig", "SwitchEquipmentHaType", "UpdateEcn", "UpdateEcnAccessPoint", "UpdateEcnWithVpc", "UpdateEquipmentDnsInfo", "UpdateEquipmentEsn", "UpdateEquipmentInfo", "UpdateEquipmentLanConfig", "UpdateEquipmentOspf", "UpdateEquipmentStaticRouteConfig", "UpdateEquipmentWanConfig", "UpdateEquipmentWlan", "UpdateIeg", "UpdateVrrpConfig"]

[lib]
name = "huawei_cloud_api_definitions_EC"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-EC"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "0.1.1"
