[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddGeipSegmentTags = []
AddGlobalEipTags = []
AddInternetBandwidthTags = []
AssociateGeipSegmentInstance = []
AssociateInstance = []
AttachInternetBandwidth = []
BatchAttachGeipSegmentInternetBandwidth = []
BatchAttachInternetBandwidth = []
BatchCreateGeipSegmentTags = []
BatchCreateGlobalEip = []
BatchCreateGlobalEipTags = []
BatchCreateInternetBandwidth = []
BatchCreateInternetBandwidthTags = []
BatchDeleteGeipSegmentTags = []
BatchDeleteGlobalEipTags = []
BatchDeleteInternetBandwidthTags = []
BatchDetachGeipSegmentInternetBandwidth = []
BatchDetachInternetBandwidth = []
CountGlobalEipSegment = []
CountGlobalEips = []
CountInternetBandwidth = []
CreateGlobalEip = []
CreateGlobalEipSegment = []
CreateInternetBandwidth = []
CreateUserDisclaimer = []
DeleteGeipSegmentTag = []
DeleteGlobalEip = []
DeleteGlobalEipSegment = []
DeleteGlobalEipTag = []
DeleteInternetBandwidth = []
DeleteInternetBandwidthTag = []
DeleteUserDisclaimer = []
DetachInternetBandwidth = []
DisassociateGeipSegmentInstance = []
DisassociateInstance = []
ListAccessSites = []
ListGeipPools = []
ListGeipResourceQuotas = []
ListGeipSegmentCountFilterTags = []
ListGeipSegmentDomainTags = []
ListGeipSegmentFilterTags = []
ListGlobalEipCountFilterTags = []
ListGlobalEipDomainTags = []
ListGlobalEipFilterTags = []
ListGlobalEipSegments = []
ListGlobalEips = []
ListInternetBandwidthCountFilterTags = []
ListInternetBandwidthDomainTags = []
ListInternetBandwidthFilterTags = []
ListInternetBandwidthLimits = []
ListInternetBandwidths = []
ListJobs = []
ListSupportMasks = []
ListSupportRegions = []
ListTenantGeipSupportInstances = []
ShowGeipSegmentTags = []
ShowGlobalEip = []
ShowGlobalEipSegment = []
ShowGlobalEipTags = []
ShowInternetBandwidth = []
ShowInternetBandwidthTags = []
ShowJobs = []
ShowUserDisclaimer = []
UpdateGlobalEip = []
UpdateGlobalEipSegment = []
UpdateInternetBandwidth = []
full = ["AddGeipSegmentTags", "AddGlobalEipTags", "AddInternetBandwidthTags", "AssociateGeipSegmentInstance", "AssociateInstance", "AttachInternetBandwidth", "BatchAttachGeipSegmentInternetBandwidth", "BatchAttachInternetBandwidth", "BatchCreateGeipSegmentTags", "BatchCreateGlobalEip", "BatchCreateGlobalEipTags", "BatchCreateInternetBandwidth", "BatchCreateInternetBandwidthTags", "BatchDeleteGeipSegmentTags", "BatchDeleteGlobalEipTags", "BatchDeleteInternetBandwidthTags", "BatchDetachGeipSegmentInternetBandwidth", "BatchDetachInternetBandwidth", "CountGlobalEips", "CountGlobalEipSegment", "CountInternetBandwidth", "CreateGlobalEip", "CreateGlobalEipSegment", "CreateInternetBandwidth", "CreateUserDisclaimer", "DeleteGeipSegmentTag", "DeleteGlobalEip", "DeleteGlobalEipSegment", "DeleteGlobalEipTag", "DeleteInternetBandwidth", "DeleteInternetBandwidthTag", "DeleteUserDisclaimer", "DetachInternetBandwidth", "DisassociateGeipSegmentInstance", "DisassociateInstance", "ListAccessSites", "ListGeipPools", "ListGeipResourceQuotas", "ListGeipSegmentCountFilterTags", "ListGeipSegmentDomainTags", "ListGeipSegmentFilterTags", "ListGlobalEipCountFilterTags", "ListGlobalEipDomainTags", "ListGlobalEipFilterTags", "ListGlobalEips", "ListGlobalEipSegments", "ListInternetBandwidthCountFilterTags", "ListInternetBandwidthDomainTags", "ListInternetBandwidthFilterTags", "ListInternetBandwidthLimits", "ListInternetBandwidths", "ListJobs", "ListSupportMasks", "ListSupportRegions", "ListTenantGeipSupportInstances", "ShowGeipSegmentTags", "ShowGlobalEip", "ShowGlobalEipSegment", "ShowGlobalEipTags", "ShowInternetBandwidth", "ShowInternetBandwidthTags", "ShowJobs", "ShowUserDisclaimer", "UpdateGlobalEip", "UpdateGlobalEipSegment", "UpdateInternetBandwidth"]

[lib]
name = "huawei_cloud_api_definitions_GEIP"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-GEIP"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
