#[cfg(feature = "BatchDeleteConfig")]
pub mod BatchDeleteConfig;
#[cfg(feature = "BatchResumeInstances")]
pub mod BatchResumeInstances;
#[cfg(feature = "ChangeScalingGroup")]
pub mod ChangeScalingGroup;
#[cfg(feature = "ChangeScalingTagInfo")]
pub mod ChangeScalingTagInfo;
#[cfg(feature = "CreateLifecycleHook")]
pub mod CreateLifecycleHook;
#[cfg(feature = "CreatePolicy")]
pub mod CreatePolicy;
#[cfg(feature = "CreateScalingConfig")]
pub mod CreateScalingConfig;
#[cfg(feature = "CreateScalingGroup")]
pub mod CreateScalingGroup;
#[cfg(feature = "DeleteConfig")]
pub mod DeleteConfig;
#[cfg(feature = "DeleteInstance")]
pub mod DeleteInstance;
#[cfg(feature = "DeleteLifecycleHook")]
pub mod DeleteLifecycleHook;
#[cfg(feature = "DeletePolicy")]
pub mod DeletePolicy;
#[cfg(feature = "DeleteScalingGroup")]
pub mod DeleteScalingGroup;
#[cfg(feature = "DeleteScalingNotification")]
pub mod DeleteScalingNotification;
#[cfg(feature = "InvokeInstanceLifecycleHook")]
pub mod InvokeInstanceLifecycleHook;
#[cfg(feature = "ListLifecycleHook")]
pub mod ListLifecycleHook;
#[cfg(feature = "ListPolicy")]
pub mod ListPolicy;
#[cfg(feature = "ListPolicyInstance")]
pub mod ListPolicyInstance;
#[cfg(feature = "ListQuotas")]
pub mod ListQuotas;
#[cfg(feature = "ListScalingActivityLog")]
pub mod ListScalingActivityLog;
#[cfg(feature = "ListScalingConfig")]
pub mod ListScalingConfig;
#[cfg(feature = "ListScalingGroup")]
pub mod ListScalingGroup;
#[cfg(feature = "ListScalingGroupInstance")]
pub mod ListScalingGroupInstance;
#[cfg(feature = "ListScalingNotification")]
pub mod ListScalingNotification;
#[cfg(feature = "ModifyLifecycleHook")]
pub mod ModifyLifecycleHook;
#[cfg(feature = "ModifyPolicy")]
pub mod ModifyPolicy;
#[cfg(feature = "ResumePolicy")]
pub mod ResumePolicy;
#[cfg(feature = "ResumeScalingGroup")]
pub mod ResumeScalingGroup;
#[cfg(feature = "SetScalingNotification")]
pub mod SetScalingNotification;
#[cfg(feature = "ShowInstance")]
pub mod ShowInstance;
#[cfg(feature = "ShowInstanceSuspend")]
pub mod ShowInstanceSuspend;
#[cfg(feature = "ShowLifecycleHook")]
pub mod ShowLifecycleHook;
#[cfg(feature = "ShowPolicy")]
pub mod ShowPolicy;
#[cfg(feature = "ShowScalingConfig")]
pub mod ShowScalingConfig;
#[cfg(feature = "ShowScalingGroup")]
pub mod ShowScalingGroup;
#[cfg(feature = "ShowScalingTagInfoByResourceId")]
pub mod ShowScalingTagInfoByResourceId;
#[cfg(feature = "ShowScalingTagInfoByTenantId")]
pub mod ShowScalingTagInfoByTenantId;
