#[cfg(feature = "CreateConnectionInfo")]
pub mod CreateConnectionInfo;
#[cfg(feature = "CreateCustomConnectorFromOpenapi")]
pub mod CreateCustomConnectorFromOpenapi;
#[cfg(feature = "CreateFlow")]
pub mod CreateFlow;
#[cfg(feature = "CreateFlowTemplateFromFlow")]
pub mod CreateFlowTemplateFromFlow;
#[cfg(feature = "DeleteConnectionInfo")]
pub mod DeleteConnectionInfo;
#[cfg(feature = "DeleteCustomConnector")]
pub mod DeleteCustomConnector;
#[cfg(feature = "DeleteFlow")]
pub mod DeleteFlow;
#[cfg(feature = "SearchFlowById")]
pub mod SearchFlowById;
#[cfg(feature = "ShowAllConnections")]
pub mod ShowAllConnections;
#[cfg(feature = "ShowAllFlows")]
pub mod ShowAllFlows;
#[cfg(feature = "ShowConnectors")]
pub mod ShowConnectors;
#[cfg(feature = "ShowCustomConnector")]
pub mod ShowCustomConnector;
#[cfg(feature = "ShowCustomConnectors")]
pub mod ShowCustomConnectors;
#[cfg(feature = "ShowSingleConnection")]
pub mod ShowSingleConnection;
#[cfg(feature = "UpdateConnectionInfo")]
pub mod UpdateConnectionInfo;
#[cfg(feature = "UpdateFlow")]
pub mod UpdateFlow;
