[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
BatchAddDeleteTags = []
CreateApp = []
CreateAppVersions = []
CreateBatchJob = []
CreateConfigMap = []
CreateDeployments = []
CreateDevice = []
CreateDeviceTemplate = []
CreateEdgeGroup = []
CreateEdgeGroupCert = []
CreateEdgeNode = []
CreateEdgeNodeCerts = []
CreateEncryptdatas = []
CreateEndpoint = []
CreateNodeEncryptdatas = []
CreateProduct = []
CreateRule = []
CreateSecret = []
CreateService = []
CreateSystemEvent = []
CreateTag = []
DeleteApp = []
DeleteAppVersion = []
DeleteBatchJob = []
DeleteConfigMap = []
DeleteDeployment = []
DeleteDevice = []
DeleteDeviceTemplate = []
DeleteEdgeGroup = []
DeleteEdgeGroupCert = []
DeleteEdgeNode = []
DeleteEdgeNodeCerts = []
DeleteEncryptdatas = []
DeleteEndPoint = []
DeleteNodeEncryptdatas = []
DeleteProduct = []
DeleteResourceTag = []
DeleteRule = []
DeleteSecret = []
DeleteService = []
DeleteSystemEvent = []
EnableDisableEdgeNodes = []
ListAppVersions = []
ListApps = []
ListBatchJob = []
ListConfigMaps = []
ListDeployments = []
ListDeviceTemplates = []
ListDevices = []
ListEdgeGroupCerts = []
ListEdgeGroups = []
ListEdgeNodeCerts = []
ListEdgeNodes = []
ListEncryptdataNodes = []
ListEncryptdatas = []
ListEndpoints = []
ListNodeEncryptdatas = []
ListPods = []
ListProducts = []
ListResourceByTags = []
ListRuleErrors = []
ListRules = []
ListSecrets = []
ListServices = []
ListSystemEvents = []
ListTags = []
ListTagsByResourceType = []
RestartDeploymentsPod = []
RestoreBatchJob = []
RetryBatchJob = []
ShowAppDetail = []
ShowAppVersionDetail = []
ShowBatchJob = []
ShowConfigMap = []
ShowDeployment = []
ShowDevice = []
ShowDeviceTemplate = []
ShowDeviceTwin = []
ShowEdgeGroupCertDetail = []
ShowEdgeGroupDetail = []
ShowEdgeNodeDetail = []
ShowEncryptdatas = []
ShowEndPointDetail = []
ShowProductDetail = []
ShowQuota = []
ShowRuleDetail = []
ShowSecret = []
ShowServiceDetail = []
ShowSystemEventDetail = []
StartRule = []
StartSystemEvent = []
StopBatchJob = []
StopRule = []
StopSystemEvent = []
UpdateApp = []
UpdateAppVersion = []
UpdateConfigMap = []
UpdateDeployment = []
UpdateDevice = []
UpdateDeviceTemplateById = []
full = ["BatchAddDeleteTags", "CreateApp", "CreateAppVersions", "CreateBatchJob", "CreateConfigMap", "CreateDeployments", "CreateDevice", "CreateDeviceTemplate", "CreateEdgeGroup", "CreateEdgeGroupCert", "CreateEdgeNode", "CreateEdgeNodeCerts", "CreateEncryptdatas", "CreateEndpoint", "CreateNodeEncryptdatas", "CreateProduct", "CreateRule", "CreateSecret", "CreateService", "CreateSystemEvent", "CreateTag", "DeleteApp", "DeleteAppVersion", "DeleteBatchJob", "DeleteConfigMap", "DeleteDeployment", "DeleteDevice", "DeleteDeviceTemplate", "DeleteEdgeGroup", "DeleteEdgeGroupCert", "DeleteEdgeNode", "DeleteEdgeNodeCerts", "DeleteEncryptdatas", "DeleteEndPoint", "DeleteNodeEncryptdatas", "DeleteProduct", "DeleteResourceTag", "DeleteRule", "DeleteSecret", "DeleteService", "DeleteSystemEvent", "EnableDisableEdgeNodes", "ListApps", "ListAppVersions", "ListBatchJob", "ListConfigMaps", "ListDeployments", "ListDevices", "ListDeviceTemplates", "ListEdgeGroupCerts", "ListEdgeGroups", "ListEdgeNodeCerts", "ListEdgeNodes", "ListEncryptdataNodes", "ListEncryptdatas", "ListEndpoints", "ListNodeEncryptdatas", "ListPods", "ListProducts", "ListResourceByTags", "ListRuleErrors", "ListRules", "ListSecrets", "ListServices", "ListSystemEvents", "ListTags", "ListTagsByResourceType", "RestartDeploymentsPod", "RestoreBatchJob", "RetryBatchJob", "ShowAppDetail", "ShowAppVersionDetail", "ShowBatchJob", "ShowConfigMap", "ShowDeployment", "ShowDevice", "ShowDeviceTemplate", "ShowDeviceTwin", "ShowEdgeGroupCertDetail", "ShowEdgeGroupDetail", "ShowEdgeNodeDetail", "ShowEncryptdatas", "ShowEndPointDetail", "ShowProductDetail", "ShowQuota", "ShowRuleDetail", "ShowSecret", "ShowServiceDetail", "ShowSystemEventDetail", "StartRule", "StartSystemEvent", "StopBatchJob", "StopRule", "StopSystemEvent", "UpdateApp", "UpdateAppVersion", "UpdateConfigMap", "UpdateDeployment", "UpdateDevice", "UpdateDeviceTemplateById"]

[lib]
name = "huawei_cloud_api_definitions_IEF"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-IEF"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "0.1.1"
