[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AcceptAttachment = []
AssociateRouteTable = []
BatchCreateResourceTags = []
ChangeAvailabilityZone = []
CreateEnterpriseRouter = []
CreateFlowLog = []
CreateResourceTag = []
CreateRouteTable = []
CreateStaticRoute = []
CreateVpcAttachment = []
DeleteEnterpriseRouter = []
DeleteFlowLog = []
DeleteResourceTag = []
DeleteRouteTable = []
DeleteStaticRoute = []
DeleteVpcAttachment = []
DisableFlowLog = []
DisablePropagation = []
DisassociateRouteTable = []
EnableFlowLog = []
EnablePropagation = []
ListAssociations = []
ListAttachments = []
ListAvailabilityZone = []
ListEffectiveRoutes = []
ListEnterpriseRouters = []
ListFlowLogs = []
ListProjectTags = []
ListPropagations = []
ListRouteTables = []
ListStaticRoutes = []
ListVpcAttachments = []
RejectAttachment = []
ShowAttachment = []
ShowEnterpriseRouter = []
ShowFlowLog = []
ShowQuotas = []
ShowResourceTag = []
ShowRouteTable = []
ShowStaticRoute = []
ShowVpcAttachment = []
UpdateAttachment = []
UpdateEnterpriseRouter = []
UpdateFlowLog = []
UpdateRouteTable = []
UpdateStaticRoute = []
UpdateVpcAttachment = []
full = ["AcceptAttachment", "AssociateRouteTable", "BatchCreateResourceTags", "ChangeAvailabilityZone", "CreateEnterpriseRouter", "CreateFlowLog", "CreateResourceTag", "CreateRouteTable", "CreateStaticRoute", "CreateVpcAttachment", "DeleteEnterpriseRouter", "DeleteFlowLog", "DeleteResourceTag", "DeleteRouteTable", "DeleteStaticRoute", "DeleteVpcAttachment", "DisableFlowLog", "DisablePropagation", "DisassociateRouteTable", "EnableFlowLog", "EnablePropagation", "ListAssociations", "ListAttachments", "ListAvailabilityZone", "ListEffectiveRoutes", "ListEnterpriseRouters", "ListFlowLogs", "ListProjectTags", "ListPropagations", "ListRouteTables", "ListStaticRoutes", "ListVpcAttachments", "RejectAttachment", "ShowAttachment", "ShowEnterpriseRouter", "ShowFlowLog", "ShowQuotas", "ShowResourceTag", "ShowRouteTable", "ShowStaticRoute", "ShowVpcAttachment", "UpdateAttachment", "UpdateEnterpriseRouter", "UpdateFlowLog", "UpdateRouteTable", "UpdateStaticRoute", "UpdateVpcAttachment"]

[lib]
name = "huawei_cloud_api_definitions_ER"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-ER"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "0.1.1"
