[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AcceptManualReview = []
BatchMovePipelineToGroup = []
BatchShowPipelinesLatestStatus = []
BatchShowPipelinesStatus = []
CreateBasicPlugin = []
CreatePipelineByTemplate = []
CreatePipelineByTemplateId = []
CreatePipelineGroup = []
CreatePipelineNew = []
CreatePipelineTemplate = []
CreatePluginDraft = []
CreatePluginVersion = []
CreatePublisher = []
CreateRule = []
CreateStrategy = []
DeleteBasicPlugin = []
DeletePipeline = []
DeletePipelineGroup = []
DeletePipelineTemplate = []
DeletePluginDraft = []
DeletePublisher = []
DeleteRule = []
DeleteStrategy = []
ListAvailablePublisher = []
ListBasePlugins = []
ListBasePluginsNewPost = []
ListPLuginVersion = []
ListPipelineRuns = []
ListPipelineSimpleInfo = []
ListPipelineTemplates = []
ListPipelines = []
ListPipleineBuildResult = []
ListPluginVersionNumber = []
ListPlugins = []
ListProjectStrategy = []
ListPublisher = []
ListRule = []
ListStagePlugins = []
ListStrategy = []
ListTemplates = []
PublishPlugin = []
PublishPluginBind = []
PublishPluginDraft = []
RejectManualReview = []
RemovePipeline = []
RetryPipelineRun = []
RunPipeline = []
ShowBasicPlugin = []
ShowInstanceStatus = []
ShowPipelineDetail = []
ShowPipelineGroupTree = []
ShowPipelineLog = []
ShowPipelineRunDetail = []
ShowPipelineTemplateDetail = []
ShowPipleineStatus = []
ShowPluginInputs = []
ShowPluginMetrics = []
ShowPluginOutputs = []
ShowPluginVersion = []
ShowProjectStrategy = []
ShowPublisher = []
ShowRule = []
ShowStrategy = []
ShowTemplateDetail = []
StartNewPipeline = []
StopPipelineNew = []
StopPipelineRun = []
SwitchStrategy = []
UpdateBasicPlugin = []
UpdatePipelineGroup = []
UpdatePipelineTemplate = []
UpdatePluginBaseInfo = []
UpdatePluginDraft = []
UpdateRule = []
UpdateStrategy = []
UploadBasicPlugin = []
UploadPluginIcon = []
UploadPublisherIcon = []
full = ["AcceptManualReview", "BatchMovePipelineToGroup", "BatchShowPipelinesLatestStatus", "BatchShowPipelinesStatus", "CreateBasicPlugin", "CreatePipelineByTemplate", "CreatePipelineByTemplateId", "CreatePipelineGroup", "CreatePipelineNew", "CreatePipelineTemplate", "CreatePluginDraft", "CreatePluginVersion", "CreatePublisher", "CreateRule", "CreateStrategy", "DeleteBasicPlugin", "DeletePipeline", "DeletePipelineGroup", "DeletePipelineTemplate", "DeletePluginDraft", "DeletePublisher", "DeleteRule", "DeleteStrategy", "ListAvailablePublisher", "ListBasePlugins", "ListBasePluginsNewPost", "ListPipelineRuns", "ListPipelines", "ListPipelineSimpleInfo", "ListPipelineTemplates", "ListPipleineBuildResult", "ListPlugins", "ListPLuginVersion", "ListPluginVersionNumber", "ListProjectStrategy", "ListPublisher", "ListRule", "ListStagePlugins", "ListStrategy", "ListTemplates", "PublishPlugin", "PublishPluginBind", "PublishPluginDraft", "RejectManualReview", "RemovePipeline", "RetryPipelineRun", "RunPipeline", "ShowBasicPlugin", "ShowInstanceStatus", "ShowPipelineDetail", "ShowPipelineGroupTree", "ShowPipelineLog", "ShowPipelineRunDetail", "ShowPipelineTemplateDetail", "ShowPipleineStatus", "ShowPluginInputs", "ShowPluginMetrics", "ShowPluginOutputs", "ShowPluginVersion", "ShowProjectStrategy", "ShowPublisher", "ShowRule", "ShowStrategy", "ShowTemplateDetail", "StartNewPipeline", "StopPipelineNew", "StopPipelineRun", "SwitchStrategy", "UpdateBasicPlugin", "UpdatePipelineGroup", "UpdatePipelineTemplate", "UpdatePluginBaseInfo", "UpdatePluginDraft", "UpdateRule", "UpdateStrategy", "UploadBasicPlugin", "UploadPluginIcon", "UploadPublisherIcon"]

[lib]
name = "huawei_cloud_api_definitions_CodeArtsPipeline"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-CodeArtsPipeline"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "0.1.0"
