#[cfg(feature = "AssociateKeypair")]
pub mod AssociateKeypair;
#[cfg(feature = "BatchAssociateKeypair")]
pub mod BatchAssociateKeypair;
#[cfg(feature = "ClearPrivateKey")]
pub mod ClearPrivateKey;
#[cfg(feature = "CreateKeypair")]
pub mod CreateKeypair;
#[cfg(feature = "DeleteAllFailedTask")]
pub mod DeleteAllFailedTask;
#[cfg(feature = "DeleteFailedTask")]
pub mod DeleteFailedTask;
#[cfg(feature = "DeleteKeypair")]
pub mod DeleteKeypair;
#[cfg(feature = "DisassociateKeypair")]
pub mod DisassociateKeypair;
#[cfg(feature = "ExportPrivateKey")]
pub mod ExportPrivateKey;
#[cfg(feature = "ImportPrivateKey")]
pub mod ImportPrivateKey;
#[cfg(feature = "ListFailedTask")]
pub mod ListFailedTask;
#[cfg(feature = "ListKeypairDetail")]
pub mod ListKeypairDetail;
#[cfg(feature = "ListKeypairs")]
pub mod ListKeypairs;
#[cfg(feature = "ListKeypairTask")]
pub mod ListKeypairTask;
#[cfg(feature = "ListRunningTask")]
pub mod ListRunningTask;
#[cfg(feature = "UpdateKeypairDescription")]
pub mod UpdateKeypairDescription;
