#[cfg(feature = "CreateAddonInstance")]
pub mod CreateAddonInstance;
#[cfg(feature = "CreateClusterConf")]
pub mod CreateClusterConf;
#[cfg(feature = "CreateClusterGroupPolicyInstance")]
pub mod CreateClusterGroupPolicyInstance;
#[cfg(feature = "CreateClusterKubeconfig")]
pub mod CreateClusterKubeconfig;
#[cfg(feature = "CreateClusterPolicyInstance")]
pub mod CreateClusterPolicyInstance;
#[cfg(feature = "CreateConfigSet")]
pub mod CreateConfigSet;
#[cfg(feature = "CreateFederationCert")]
pub mod CreateFederationCert;
#[cfg(feature = "CreateFederationConnection")]
pub mod CreateFederationConnection;
#[cfg(feature = "CreateProxyUnitedWorkload")]
pub mod CreateProxyUnitedWorkload;
#[cfg(feature = "CreateRecordSet")]
pub mod CreateRecordSet;
#[cfg(feature = "CreateRepo")]
pub mod CreateRepo;
#[cfg(feature = "CreateRule")]
pub mod CreateRule;
#[cfg(feature = "DeleteAddonInstance")]
pub mod DeleteAddonInstance;
#[cfg(feature = "DeleteCluster")]
pub mod DeleteCluster;
#[cfg(feature = "DeleteClusterGroup")]
pub mod DeleteClusterGroup;
#[cfg(feature = "DeleteConfigSet")]
pub mod DeleteConfigSet;
#[cfg(feature = "DeletePolicyInstance")]
pub mod DeletePolicyInstance;
#[cfg(feature = "DeleteProxyUnitedWorkload")]
pub mod DeleteProxyUnitedWorkload;
#[cfg(feature = "DeleteRepo")]
pub mod DeleteRepo;
#[cfg(feature = "DeleteRule")]
pub mod DeleteRule;
#[cfg(feature = "DisableClusterGroupPolicy")]
pub mod DisableClusterGroupPolicy;
#[cfg(feature = "DisableClusterPolicy")]
pub mod DisableClusterPolicy;
#[cfg(feature = "DisableFederation")]
pub mod DisableFederation;
#[cfg(feature = "DisableGitOps")]
pub mod DisableGitOps;
#[cfg(feature = "DownloadFederationKubeconfig")]
pub mod DownloadFederationKubeconfig;
#[cfg(feature = "EnableClusterGroupPolicy")]
pub mod EnableClusterGroupPolicy;
#[cfg(feature = "EnableClusterPolicy")]
pub mod EnableClusterPolicy;
#[cfg(feature = "EnableFederation")]
pub mod EnableFederation;
#[cfg(feature = "EnableGitOps")]
pub mod EnableGitOps;
#[cfg(feature = "JoinGroup")]
pub mod JoinGroup;
#[cfg(feature = "LeaveGroup")]
pub mod LeaveGroup;
#[cfg(feature = "ListAddonInstances")]
pub mod ListAddonInstances;
#[cfg(feature = "ListAddonTemplates")]
pub mod ListAddonTemplates;
#[cfg(feature = "ListClusterGroup")]
pub mod ListClusterGroup;
#[cfg(feature = "ListConfigSets")]
pub mod ListConfigSets;
#[cfg(feature = "ListManagedClusters")]
pub mod ListManagedClusters;
#[cfg(feature = "ListPolicyDefinitions")]
pub mod ListPolicyDefinitions;
#[cfg(feature = "ListPolicyInstances")]
pub mod ListPolicyInstances;
#[cfg(feature = "ListPolicyJobs")]
pub mod ListPolicyJobs;
#[cfg(feature = "ListRecordSets")]
pub mod ListRecordSets;
#[cfg(feature = "ListRegisteredClusterVersions")]
pub mod ListRegisteredClusterVersions;
#[cfg(feature = "ListRepos")]
pub mod ListRepos;
#[cfg(feature = "ListRule")]
pub mod ListRule;
#[cfg(feature = "ListServerConfigs")]
pub mod ListServerConfigs;
#[cfg(feature = "RegisterCluster")]
pub mod RegisterCluster;
#[cfg(feature = "RegisterClusterGroup")]
pub mod RegisterClusterGroup;
#[cfg(feature = "RetryClusterActivation")]
pub mod RetryClusterActivation;
#[cfg(feature = "ShowAddonInstance")]
pub mod ShowAddonInstance;
#[cfg(feature = "ShowCluster")]
pub mod ShowCluster;
#[cfg(feature = "ShowClusterAccessInfo")]
pub mod ShowClusterAccessInfo;
#[cfg(feature = "ShowClusterGroup")]
pub mod ShowClusterGroup;
#[cfg(feature = "ShowClusterList")]
pub mod ShowClusterList;
#[cfg(feature = "ShowConfigSet")]
pub mod ShowConfigSet;
#[cfg(feature = "ShowFederationProgress")]
pub mod ShowFederationProgress;
#[cfg(feature = "ShowGitopsStatistics")]
pub mod ShowGitopsStatistics;
#[cfg(feature = "ShowGitOpsStatus")]
pub mod ShowGitOpsStatus;
#[cfg(feature = "ShowPolicyDefinition")]
pub mod ShowPolicyDefinition;
#[cfg(feature = "ShowPolicyInstance")]
pub mod ShowPolicyInstance;
#[cfg(feature = "ShowPolicyJob")]
pub mod ShowPolicyJob;
#[cfg(feature = "ShowProxyUnitedWorkload")]
pub mod ShowProxyUnitedWorkload;
#[cfg(feature = "ShowQuota")]
pub mod ShowQuota;
#[cfg(feature = "UpdateAddonInstance")]
pub mod UpdateAddonInstance;
#[cfg(feature = "UpdateCluster")]
pub mod UpdateCluster;
#[cfg(feature = "UpdateClusterGroup")]
pub mod UpdateClusterGroup;
#[cfg(feature = "UpdateClusterGroupAssociatedClusters")]
pub mod UpdateClusterGroupAssociatedClusters;
#[cfg(feature = "UpdateClusterGroupAssociatedRules")]
pub mod UpdateClusterGroupAssociatedRules;
#[cfg(feature = "UpdateClusterGroupAssociatedZones")]
pub mod UpdateClusterGroupAssociatedZones;
#[cfg(feature = "UpdateClusterRules")]
pub mod UpdateClusterRules;
#[cfg(feature = "UpdateConfigSet")]
pub mod UpdateConfigSet;
#[cfg(feature = "UpdatePolicyDefination")]
pub mod UpdatePolicyDefination;
#[cfg(feature = "UpdatePolicyInstance")]
pub mod UpdatePolicyInstance;
#[cfg(feature = "UpdateProxyUnitedWorkload")]
pub mod UpdateProxyUnitedWorkload;
#[cfg(feature = "UpdateRepo")]
pub mod UpdateRepo;
#[cfg(feature = "UpdateRule")]
pub mod UpdateRule;
#[cfg(feature = "UpgradeFederation")]
pub mod UpgradeFederation;
