#[cfg(feature = "CreateFederationCert")]
pub mod CreateFederationCert;
#[cfg(feature = "CreateFederationConnection")]
pub mod CreateFederationConnection;
#[cfg(feature = "CreateRule")]
pub mod CreateRule;
#[cfg(feature = "DeleteCluster")]
pub mod DeleteCluster;
#[cfg(feature = "DeleteClusterGroup")]
pub mod DeleteClusterGroup;
#[cfg(feature = "DeleteRule")]
pub mod DeleteRule;
#[cfg(feature = "DisableFederation")]
pub mod DisableFederation;
#[cfg(feature = "DownloadFederationKubeconfig")]
pub mod DownloadFederationKubeconfig;
#[cfg(feature = "EnableFederation")]
pub mod EnableFederation;
#[cfg(feature = "JoinGroup")]
pub mod JoinGroup;
#[cfg(feature = "LeaveGroup")]
pub mod LeaveGroup;
#[cfg(feature = "ListClusterGroup")]
pub mod ListClusterGroup;
#[cfg(feature = "ListManagedClusters")]
pub mod ListManagedClusters;
#[cfg(feature = "ListRegisteredClusterVersions")]
pub mod ListRegisteredClusterVersions;
#[cfg(feature = "ListRule")]
pub mod ListRule;
#[cfg(feature = "RegisterCluster")]
pub mod RegisterCluster;
#[cfg(feature = "RegisterClusterGroup")]
pub mod RegisterClusterGroup;
#[cfg(feature = "RetryClusterActivation")]
pub mod RetryClusterActivation;
#[cfg(feature = "ShowCluster")]
pub mod ShowCluster;
#[cfg(feature = "ShowClusterAccessInfo")]
pub mod ShowClusterAccessInfo;
#[cfg(feature = "ShowClusterGroup")]
pub mod ShowClusterGroup;
#[cfg(feature = "ShowClusterList")]
pub mod ShowClusterList;
#[cfg(feature = "ShowFederationProgress")]
pub mod ShowFederationProgress;
#[cfg(feature = "UpdateCluster")]
pub mod UpdateCluster;
#[cfg(feature = "UpdateClusterGroup")]
pub mod UpdateClusterGroup;
#[cfg(feature = "UpdateClusterGroupAssociatedClusters")]
pub mod UpdateClusterGroupAssociatedClusters;
#[cfg(feature = "UpdateClusterGroupAssociatedRules")]
pub mod UpdateClusterGroupAssociatedRules;
#[cfg(feature = "UpdateClusterGroupAssociatedZones")]
pub mod UpdateClusterGroupAssociatedZones;
#[cfg(feature = "UpdateClusterRules")]
pub mod UpdateClusterRules;
#[cfg(feature = "UpdateRule")]
pub mod UpdateRule;
