[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AssociateQueueToElasticResourcePool = []
AssociateQueueToEnhancedConnection = []
BatchCreateResourceTags = []
BatchDeleteFlinkJobs = []
BatchDeleteQueuePlans = []
BatchDeleteResourceTags = []
BatchDeleteSqlJobTemplates = []
BatchRunFlinkJobs = []
CancelSparkJob = []
CancelSqlJob = []
ChangeAuthorization = []
ChangeFlinkJobStatusReport = []
ChangeQueuePlan = []
CheckSql = []
CountResourcesByTags = []
CreateAuthInfo = []
CreateConnectivityTask = []
CreateDatabase = []
CreateDatasourceConnection = []
CreateDliAgency = []
CreateElasticResourcePool = []
CreateEnhancedConnection = []
CreateEnhancedConnectionRoutes = []
CreateFlinkJarJob = []
CreateFlinkSqlJob = []
CreateFlinkSqlJobGraph = []
CreateFlinkSqlJobTemplate = []
CreateGlobalVariable = []
CreateIefMessageChannel = []
CreateIefSystemEvents = []
CreateJobAuthInfo = []
CreatePeriodElasticResourcePoolOrder = []
CreatePeriodElasticResourcePoolSpecChangeOrder = []
CreateQueue = []
CreateQueuePlan = []
CreateQueueProperty = []
CreateRouteToEnhancedConnection = []
CreateSparkJob = []
CreateSparkJobTemplate = []
CreateSqlJob = []
CreateSqlJobTemplate = []
CreateTable = []
DeleteAuthInfo = []
DeleteDatabase = []
DeleteDatasourceConnection = []
DeleteElasticResourcePool = []
DeleteEnhancedConnection = []
DeleteEnhancedConnectionRoutes = []
DeleteFlinkJob = []
DeleteFlinkSqlJobTemplate = []
DeleteGlobalVariable = []
DeleteJobAuthInfo = []
DeleteQueue = []
DeleteQueuePlan = []
DeleteQueueProperty = []
DeleteResource = []
DeleteRouteFromEnhancedConnection = []
DeleteTable = []
DisassociateQueueFromEnhancedConnection = []
ExecuteFlinkJobSavepoint = []
ExportFlinkJobs = []
ExportSqlJobResult = []
ExportTable = []
ImportFlinkJobSavepoint = []
ImportFlinkJobs = []
ImportTable = []
ListAllTables = []
ListAuthInfo = []
ListAuthorizationPrivileges = []
ListCatalogs = []
ListDatabaseUsers = []
ListDatabases = []
ListDatasourceConnections = []
ListElasticResourcePoolQueues = []
ListElasticResourcePoolScaleRecords = []
ListElasticResourcePools = []
ListEnhancedConnections = []
ListFlinkJobs = []
ListFlinkSqlJobTemplates = []
ListGlobalVariables = []
ListJobAuthInfos = []
ListQueuePlans = []
ListQueueProperties = []
ListQueueUsers = []
ListQueues = []
ListResources = []
ListResourcesByTags = []
ListResourcesTags = []
ListSparkJobTemplates = []
ListSparkJobs = []
ListSqlJobTemplates = []
ListSqlJobs = []
ListTablePrivileges = []
ListTableUsers = []
PreviewSqlJobResult = []
RegisterAuthorizedQueue = []
RegisterBucket = []
RunAuthorizationAction = []
RunCatalogAction = []
RunIefJobActionCallBack = []
full = ["AssociateQueueToElasticResourcePool", "AssociateQueueToEnhancedConnection", "BatchCreateResourceTags", "BatchDeleteFlinkJobs", "BatchDeleteQueuePlans", "BatchDeleteResourceTags", "BatchDeleteSqlJobTemplates", "BatchRunFlinkJobs", "CancelSparkJob", "CancelSqlJob", "ChangeAuthorization", "ChangeFlinkJobStatusReport", "ChangeQueuePlan", "CheckSql", "CountResourcesByTags", "CreateAuthInfo", "CreateConnectivityTask", "CreateDatabase", "CreateDatasourceConnection", "CreateDliAgency", "CreateElasticResourcePool", "CreateEnhancedConnection", "CreateEnhancedConnectionRoutes", "CreateFlinkJarJob", "CreateFlinkSqlJob", "CreateFlinkSqlJobGraph", "CreateFlinkSqlJobTemplate", "CreateGlobalVariable", "CreateIefMessageChannel", "CreateIefSystemEvents", "CreateJobAuthInfo", "CreatePeriodElasticResourcePoolOrder", "CreatePeriodElasticResourcePoolSpecChangeOrder", "CreateQueue", "CreateQueuePlan", "CreateQueueProperty", "CreateRouteToEnhancedConnection", "CreateSparkJob", "CreateSparkJobTemplate", "CreateSqlJob", "CreateSqlJobTemplate", "CreateTable", "DeleteAuthInfo", "DeleteDatabase", "DeleteDatasourceConnection", "DeleteElasticResourcePool", "DeleteEnhancedConnection", "DeleteEnhancedConnectionRoutes", "DeleteFlinkJob", "DeleteFlinkSqlJobTemplate", "DeleteGlobalVariable", "DeleteJobAuthInfo", "DeleteQueue", "DeleteQueuePlan", "DeleteQueueProperty", "DeleteResource", "DeleteRouteFromEnhancedConnection", "DeleteTable", "DisassociateQueueFromEnhancedConnection", "ExecuteFlinkJobSavepoint", "ExportFlinkJobs", "ExportSqlJobResult", "ExportTable", "ImportFlinkJobs", "ImportFlinkJobSavepoint", "ImportTable", "ListAllTables", "ListAuthInfo", "ListAuthorizationPrivileges", "ListCatalogs", "ListDatabases", "ListDatabaseUsers", "ListDatasourceConnections", "ListElasticResourcePoolQueues", "ListElasticResourcePools", "ListElasticResourcePoolScaleRecords", "ListEnhancedConnections", "ListFlinkJobs", "ListFlinkSqlJobTemplates", "ListGlobalVariables", "ListJobAuthInfos", "ListQueuePlans", "ListQueueProperties", "ListQueues", "ListQueueUsers", "ListResources", "ListResourcesByTags", "ListResourcesTags", "ListSparkJobs", "ListSparkJobTemplates", "ListSqlJobs", "ListSqlJobTemplates", "ListTablePrivileges", "ListTableUsers", "PreviewSqlJobResult", "RegisterAuthorizedQueue", "RegisterBucket", "RunAuthorizationAction", "RunCatalogAction", "RunIefJobActionCallBack"]

[lib]
name = "huawei_cloud_api_definitions_DLI"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-DLI"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
