[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
BatchCreateApplicationView = []
CountMultiResources = []
CreateCocIncident = []
CreateCocIssues = []
CreateReportCustomEvent = []
CreateReportPrometheusEvent = []
CreateScheduledTask = []
CreateScript = []
CreateWarRoom = []
DeleteScheduledTask = []
DeleteScript = []
DisableScheduledTask = []
EnableScheduledTask = []
ExecutePublicScript = []
ExecuteScript = []
GetPublicScript = []
GetScript = []
GetScriptJobBatch = []
GetScriptJobInfo = []
GetScriptJobStatistics = []
HandleCocIncident = []
ListAlarmHandleHistories = []
ListApplicationModel = []
ListApplications = []
ListAuthorizableTicketsExternal = []
ListCceCompliant = []
ListCocTicketOperationHistories = []
ListInstanceCompliant = []
ListInterruptRecords = []
ListMultiCloudResources = []
ListPersonnel = []
ListPublicScripts = []
ListResource = []
ListScheduledTask = []
ListScheduledTaskHistory = []
ListScriptJobBatches = []
ListScriptJobs = []
ListScripts = []
ListWarRooms = []
OperateScriptJob = []
ShowAccount = []
ShowAlarm = []
ShowCocIncidentDetail = []
ShowCocIssuesDetail = []
ShowInstancePatchItems = []
ShowPatchBaseline = []
ShowScheduledTask = []
ShowSlaCustomizedTemplate = []
ShowSlaOrder = []
ShowSloDetail = []
SyncAddPersonnel = []
SyncResource = []
UpdateScheduledTask = []
UpdateScript = []
full = ["BatchCreateApplicationView", "CountMultiResources", "CreateCocIncident", "CreateCocIssues", "CreateReportCustomEvent", "CreateReportPrometheusEvent", "CreateScheduledTask", "CreateScript", "CreateWarRoom", "DeleteScheduledTask", "DeleteScript", "DisableScheduledTask", "EnableScheduledTask", "ExecutePublicScript", "ExecuteScript", "GetPublicScript", "GetScript", "GetScriptJobBatch", "GetScriptJobInfo", "GetScriptJobStatistics", "HandleCocIncident", "ListAlarmHandleHistories", "ListApplicationModel", "ListApplications", "ListAuthorizableTicketsExternal", "ListCceCompliant", "ListCocTicketOperationHistories", "ListInstanceCompliant", "ListInterruptRecords", "ListMultiCloudResources", "ListPersonnel", "ListPublicScripts", "ListResource", "ListScheduledTask", "ListScheduledTaskHistory", "ListScriptJobBatches", "ListScriptJobs", "ListScripts", "ListWarRooms", "OperateScriptJob", "ShowAccount", "ShowAlarm", "ShowCocIncidentDetail", "ShowCocIssuesDetail", "ShowInstancePatchItems", "ShowPatchBaseline", "ShowScheduledTask", "ShowSlaCustomizedTemplate", "ShowSlaOrder", "ShowSloDetail", "SyncAddPersonnel", "SyncResource", "UpdateScheduledTask", "UpdateScript"]

[lib]
name = "huawei_cloud_api_definitions_COC"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-COC"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
