[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AcceptScript = []
BatchCreateApplicationView = []
CancelDiagnosisTask = []
CheckScriptRisk = []
CountMultiResources = []
CreateCocIncident = []
CreateCocIssues = []
CreateDiagnosisTask = []
CreateDocument = []
CreateReportCustomEvent = []
CreateReportPrometheusEvent = []
CreateScheduledTask = []
CreateScript = []
CreateWarRoom = []
DeleteDocument = []
DeleteScheduledTask = []
DeleteScript = []
DisableScheduledTask = []
EnableScheduledTask = []
ExecuteDocument = []
ExecutePublicScript = []
ExecuteScript = []
GetDocument = []
GetDocumentAtomicInfo = []
GetExecution = []
GetPublicScript = []
GetScript = []
GetScriptJobBatch = []
GetScriptJobInfo = []
GetScriptJobStatistics = []
HandleCocIncident = []
ListApplicationModel = []
ListApplications = []
ListAuthorizableTicketsExternal = []
ListCocTicketOperationHistories = []
ListDiagnosisTasks = []
ListDocumentAtomics = []
ListDocuments = []
ListExecutionInstances = []
ListExecutionSteps = []
ListExecutions = []
ListInstanceCompliant = []
ListInstancesBatch = []
ListMultiCloudResources = []
ListPublicScripts = []
ListResource = []
ListScheduledTask = []
ListScheduledTaskHistory = []
ListScriptJobBatches = []
ListScriptJobs = []
ListScriptResourceTags = []
ListScripts = []
ListWarRooms = []
OperateExecution = []
OperateScriptJob = []
RetryDiagnosisTask = []
ShowCocIncidentDetail = []
ShowCocIssuesDetail = []
ShowDiagnosisNode = []
ShowDiagnosisSummary = []
ShowDiagnosisTask = []
ShowInstancePatchItems = []
ShowScheduledTask = []
SyncResource = []
UpdateDocument = []
UpdateResourceTags = []
UpdateScheduledTask = []
UpdateScript = []
full = ["AcceptScript", "BatchCreateApplicationView", "CancelDiagnosisTask", "CheckScriptRisk", "CountMultiResources", "CreateCocIncident", "CreateCocIssues", "CreateDiagnosisTask", "CreateDocument", "CreateReportCustomEvent", "CreateReportPrometheusEvent", "CreateScheduledTask", "CreateScript", "CreateWarRoom", "DeleteDocument", "DeleteScheduledTask", "DeleteScript", "DisableScheduledTask", "EnableScheduledTask", "ExecuteDocument", "ExecutePublicScript", "ExecuteScript", "GetDocument", "GetDocumentAtomicInfo", "GetExecution", "GetPublicScript", "GetScript", "GetScriptJobBatch", "GetScriptJobInfo", "GetScriptJobStatistics", "HandleCocIncident", "ListApplicationModel", "ListApplications", "ListAuthorizableTicketsExternal", "ListCocTicketOperationHistories", "ListDiagnosisTasks", "ListDocumentAtomics", "ListDocuments", "ListExecutionInstances", "ListExecutions", "ListExecutionSteps", "ListInstanceCompliant", "ListInstancesBatch", "ListMultiCloudResources", "ListPublicScripts", "ListResource", "ListScheduledTask", "ListScheduledTaskHistory", "ListScriptJobBatches", "ListScriptJobs", "ListScriptResourceTags", "ListScripts", "ListWarRooms", "OperateExecution", "OperateScriptJob", "RetryDiagnosisTask", "ShowCocIncidentDetail", "ShowCocIssuesDetail", "ShowDiagnosisNode", "ShowDiagnosisSummary", "ShowDiagnosisTask", "ShowInstancePatchItems", "ShowScheduledTask", "SyncResource", "UpdateDocument", "UpdateResourceTags", "UpdateScheduledTask", "UpdateScript"]

[lib]
name = "huawei_cloud_api_definitions_COC"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-COC"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
