[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AcceptScript = []
BatchCreateApplicationView = []
CancelDiagnosisTask = []
CheckScriptRisk = []
ClearAlarm = []
CountGroupRmsResourceRelations = []
CountMultiResources = []
CountResources = []
CountResourcesOfResourceView = []
CreateApplication = []
CreateApplicationComponents = []
CreateApplicationGroup = []
CreateAssessTask = []
CreateAttachment = []
CreateCocIncident = []
CreateCocIssues = []
CreateDiagnosisTask = []
CreateDocument = []
CreateExternalCocAttachment = []
CreateGroupRmsResourceRelation = []
CreatePasswordChangePlan = []
CreateReportCustomEvent = []
CreateReportPrometheusEvent = []
CreateResourceTags = []
CreateResourceViews = []
CreateScheduledTask = []
CreateScript = []
CreateTicket = []
CreateWarRoom = []
DeleteApplication = []
DeleteApplicationComponent = []
DeleteApplicationGroup = []
DeleteDocument = []
DeleteGroupRmsResourceRelation = []
DeleteResourceViews = []
DeleteScheduledTask = []
DeleteScript = []
DeleteTicketInfo = []
DisableScheduledTask = []
DownloadAttachment = []
EnableScheduledTask = []
ExecuteDocument = []
ExecutePublicScript = []
ExecuteScript = []
ExecuteTicketAction = []
GetDocument = []
GetDocumentAtomicInfo = []
GetExecution = []
GetPublicScript = []
GetScript = []
GetScriptJobBatch = []
GetScriptJobInfo = []
GetScriptJobStatistics = []
HandleAlarm = []
HandleCocIncident = []
HandleIncident = []
ImportOtherResource = []
ListAlarmHandleHistories = []
ListApplicationComponents = []
ListApplicationGroups = []
ListApplicationModel = []
ListApplicationView = []
ListApplications = []
ListAssessTask = []
ListAuthorizableTicketsExternal = []
ListCapacityOrder = []
ListCapacityView = []
ListCocTicketOperationHistories = []
ListDiagnosisTasks = []
ListDocumentAtomics = []
ListDocuments = []
ListEnterpriseProjectCollect = []
ListExecutionInstances = []
ListExecutionSteps = []
ListExecutions = []
ListGroupRmsResourceRelations = []
ListIncidentSimpleTickets = []
ListIncidents = []
ListIncidentsHistories = []
ListInstanceCompliant = []
ListInstancesBatch = []
ListMultiCloudResources = []
ListPublicScripts = []
ListResource = []
ListResourceTags = []
ListResourceViews = []
ListResourcesOfResourceView = []
ListScheduledTask = []
ListScheduledTaskHistory = []
ListScriptJobBatches = []
ListScriptJobs = []
ListScriptResourceTags = []
ListScripts = []
ListSubTickets = []
ListTicketOperationHistories = []
ListTickets = []
ListWarRooms = []
OperateExecution = []
OperateScriptJob = []
ResetAccountPassword = []
full = ["AcceptScript", "BatchCreateApplicationView", "CancelDiagnosisTask", "CheckScriptRisk", "ClearAlarm", "CountGroupRmsResourceRelations", "CountMultiResources", "CountResources", "CountResourcesOfResourceView", "CreateApplication", "CreateApplicationComponents", "CreateApplicationGroup", "CreateAssessTask", "CreateAttachment", "CreateCocIncident", "CreateCocIssues", "CreateDiagnosisTask", "CreateDocument", "CreateExternalCocAttachment", "CreateGroupRmsResourceRelation", "CreatePasswordChangePlan", "CreateReportCustomEvent", "CreateReportPrometheusEvent", "CreateResourceTags", "CreateResourceViews", "CreateScheduledTask", "CreateScript", "CreateTicket", "CreateWarRoom", "DeleteApplication", "DeleteApplicationComponent", "DeleteApplicationGroup", "DeleteDocument", "DeleteGroupRmsResourceRelation", "DeleteResourceViews", "DeleteScheduledTask", "DeleteScript", "DeleteTicketInfo", "DisableScheduledTask", "DownloadAttachment", "EnableScheduledTask", "ExecuteDocument", "ExecutePublicScript", "ExecuteScript", "ExecuteTicketAction", "GetDocument", "GetDocumentAtomicInfo", "GetExecution", "GetPublicScript", "GetScript", "GetScriptJobBatch", "GetScriptJobInfo", "GetScriptJobStatistics", "HandleAlarm", "HandleCocIncident", "HandleIncident", "ImportOtherResource", "ListAlarmHandleHistories", "ListApplicationComponents", "ListApplicationGroups", "ListApplicationModel", "ListApplications", "ListApplicationView", "ListAssessTask", "ListAuthorizableTicketsExternal", "ListCapacityOrder", "ListCapacityView", "ListCocTicketOperationHistories", "ListDiagnosisTasks", "ListDocumentAtomics", "ListDocuments", "ListEnterpriseProjectCollect", "ListExecutionInstances", "ListExecutions", "ListExecutionSteps", "ListGroupRmsResourceRelations", "ListIncidents", "ListIncidentsHistories", "ListIncidentSimpleTickets", "ListInstanceCompliant", "ListInstancesBatch", "ListMultiCloudResources", "ListPublicScripts", "ListResource", "ListResourcesOfResourceView", "ListResourceTags", "ListResourceViews", "ListScheduledTask", "ListScheduledTaskHistory", "ListScriptJobBatches", "ListScriptJobs", "ListScriptResourceTags", "ListScripts", "ListSubTickets", "ListTicketOperationHistories", "ListTickets", "ListWarRooms", "OperateExecution", "OperateScriptJob", "ResetAccountPassword"]

[lib]
name = "huawei_cloud_api_definitions_COC"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-COC"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
