[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AcceptScript = []
BatchCreateApplicationView = []
CancelDiagnosisTask = []
CheckScriptRisk = []
ClearAlarm = []
CountMultiResources = []
CreateApplication = []
CreateApplicationComponents = []
CreateApplicationGroup = []
CreateAttachment = []
CreateCocIncident = []
CreateCocIssues = []
CreateDiagnosisTask = []
CreateDocument = []
CreateExternalCocAttachment = []
CreateReportCustomEvent = []
CreateReportPrometheusEvent = []
CreateScheduledTask = []
CreateScript = []
CreateTicket = []
CreateWarRoom = []
DeleteApplication = []
DeleteApplicationComponent = []
DeleteApplicationGroup = []
DeleteDocument = []
DeleteScheduledTask = []
DeleteScript = []
DeleteTicketInfo = []
DisableScheduledTask = []
DownloadAttachment = []
EnableScheduledTask = []
ExecuteDocument = []
ExecutePublicScript = []
ExecuteScript = []
ExecuteTicketAction = []
GetDocument = []
GetDocumentAtomicInfo = []
GetExecution = []
GetPublicScript = []
GetScript = []
GetScriptJobBatch = []
GetScriptJobInfo = []
GetScriptJobStatistics = []
HandleCocIncident = []
HandleIncident = []
HandlerAlarm = []
ListAlarmHandleHistories = []
ListApplicationComponents = []
ListApplicationGroups = []
ListApplicationModel = []
ListApplications = []
ListAuthorizableTicketsExternal = []
ListCocTicketOperationHistories = []
ListDiagnosisTasks = []
ListDocumentAtomics = []
ListDocuments = []
ListExecutionInstances = []
ListExecutionSteps = []
ListExecutions = []
ListIncidentSimpleTickets = []
ListIncidents = []
ListIncidentsHistories = []
ListInstanceCompliant = []
ListInstancesBatch = []
ListMultiCloudResources = []
ListPublicScripts = []
ListResource = []
ListScheduledTask = []
ListScheduledTaskHistory = []
ListScriptJobBatches = []
ListScriptJobs = []
ListScriptResourceTags = []
ListScripts = []
ListSubTickets = []
ListTicketOperationHistories = []
ListTickets = []
ListWarRooms = []
OperateExecution = []
OperateScriptJob = []
RetryDiagnosisTask = []
ShowAlarm = []
ShowCocIncidentDetail = []
ShowCocIssuesDetail = []
ShowDiagnosisNode = []
ShowDiagnosisSummary = []
ShowDiagnosisTask = []
ShowIncidentTask = []
ShowInstancePatchItems = []
ShowScheduledTask = []
ShowTicketInfo = []
SyncGroupResource = []
SyncResource = []
TransferAlarmToIncident = []
UpdateApplication = []
UpdateApplicationComponent = []
UpdateApplicationGroup = []
UpdateChange = []
UpdateDocument = []
UpdateResourceTags = []
UpdateScheduledTask = []
full = ["AcceptScript", "BatchCreateApplicationView", "CancelDiagnosisTask", "CheckScriptRisk", "ClearAlarm", "CountMultiResources", "CreateApplication", "CreateApplicationComponents", "CreateApplicationGroup", "CreateAttachment", "CreateCocIncident", "CreateCocIssues", "CreateDiagnosisTask", "CreateDocument", "CreateExternalCocAttachment", "CreateReportCustomEvent", "CreateReportPrometheusEvent", "CreateScheduledTask", "CreateScript", "CreateTicket", "CreateWarRoom", "DeleteApplication", "DeleteApplicationComponent", "DeleteApplicationGroup", "DeleteDocument", "DeleteScheduledTask", "DeleteScript", "DeleteTicketInfo", "DisableScheduledTask", "DownloadAttachment", "EnableScheduledTask", "ExecuteDocument", "ExecutePublicScript", "ExecuteScript", "ExecuteTicketAction", "GetDocument", "GetDocumentAtomicInfo", "GetExecution", "GetPublicScript", "GetScript", "GetScriptJobBatch", "GetScriptJobInfo", "GetScriptJobStatistics", "HandleCocIncident", "HandleIncident", "HandlerAlarm", "ListAlarmHandleHistories", "ListApplicationComponents", "ListApplicationGroups", "ListApplicationModel", "ListApplications", "ListAuthorizableTicketsExternal", "ListCocTicketOperationHistories", "ListDiagnosisTasks", "ListDocumentAtomics", "ListDocuments", "ListExecutionInstances", "ListExecutions", "ListExecutionSteps", "ListIncidents", "ListIncidentsHistories", "ListIncidentSimpleTickets", "ListInstanceCompliant", "ListInstancesBatch", "ListMultiCloudResources", "ListPublicScripts", "ListResource", "ListScheduledTask", "ListScheduledTaskHistory", "ListScriptJobBatches", "ListScriptJobs", "ListScriptResourceTags", "ListScripts", "ListSubTickets", "ListTicketOperationHistories", "ListTickets", "ListWarRooms", "OperateExecution", "OperateScriptJob", "RetryDiagnosisTask", "ShowAlarm", "ShowCocIncidentDetail", "ShowCocIssuesDetail", "ShowDiagnosisNode", "ShowDiagnosisSummary", "ShowDiagnosisTask", "ShowIncidentTask", "ShowInstancePatchItems", "ShowScheduledTask", "ShowTicketInfo", "SyncGroupResource", "SyncResource", "TransferAlarmToIncident", "UpdateApplication", "UpdateApplicationComponent", "UpdateApplicationGroup", "UpdateChange", "UpdateDocument", "UpdateResourceTags", "UpdateScheduledTask"]

[lib]
name = "huawei_cloud_api_definitions_COC"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-COC"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
