#[cfg(feature = "AssociateAgencyWithAllProjectsPermission")]
pub mod AssociateAgencyWithAllProjectsPermission;
#[cfg(feature = "AssociateAgencyWithDomainPermission")]
pub mod AssociateAgencyWithDomainPermission;
#[cfg(feature = "AssociateAgencyWithProjectPermission")]
pub mod AssociateAgencyWithProjectPermission;
#[cfg(feature = "AssociateRoleToAgencyOnEnterpriseProject")]
pub mod AssociateRoleToAgencyOnEnterpriseProject;
#[cfg(feature = "AssociateRoleToGroupOnEnterpriseProject")]
pub mod AssociateRoleToGroupOnEnterpriseProject;
#[cfg(feature = "AssociateRoleToUserOnEnterpriseProject")]
pub mod AssociateRoleToUserOnEnterpriseProject;
#[cfg(feature = "CheckAllProjectsPermissionForAgency")]
pub mod CheckAllProjectsPermissionForAgency;
#[cfg(feature = "CheckDomainPermissionForAgency")]
pub mod CheckDomainPermissionForAgency;
#[cfg(feature = "CheckProjectPermissionForAgency")]
pub mod CheckProjectPermissionForAgency;
#[cfg(feature = "CreateAgency")]
pub mod CreateAgency;
#[cfg(feature = "CreateAgencyCustomPolicy")]
pub mod CreateAgencyCustomPolicy;
#[cfg(feature = "CreateBindingDevice")]
pub mod CreateBindingDevice;
#[cfg(feature = "CreateCloudServiceCustomPolicy")]
pub mod CreateCloudServiceCustomPolicy;
#[cfg(feature = "CreateLoginToken")]
pub mod CreateLoginToken;
#[cfg(feature = "CreateMetadata")]
pub mod CreateMetadata;
#[cfg(feature = "CreateMfaDevice")]
pub mod CreateMfaDevice;
#[cfg(feature = "CreateOpenIdConnectConfig")]
pub mod CreateOpenIdConnectConfig;
#[cfg(feature = "CreatePermanentAccessKey")]
pub mod CreatePermanentAccessKey;
#[cfg(feature = "CreateTemporaryAccessKeyByAgency")]
pub mod CreateTemporaryAccessKeyByAgency;
#[cfg(feature = "CreateTemporaryAccessKeyByToken")]
pub mod CreateTemporaryAccessKeyByToken;
#[cfg(feature = "CreateTokenWithIdToken")]
pub mod CreateTokenWithIdToken;
#[cfg(feature = "CreateUnscopedTokenWithIdToken")]
pub mod CreateUnscopedTokenWithIdToken;
#[cfg(feature = "CreateUnscopeTokenByIdpInitiated")]
pub mod CreateUnscopeTokenByIdpInitiated;
#[cfg(feature = "CreateUser")]
pub mod CreateUser;
#[cfg(feature = "DeleteAgency")]
pub mod DeleteAgency;
#[cfg(feature = "DeleteBindingDevice")]
pub mod DeleteBindingDevice;
#[cfg(feature = "DeleteCustomPolicy")]
pub mod DeleteCustomPolicy;
#[cfg(feature = "DeleteDomainGroupInheritedRole")]
pub mod DeleteDomainGroupInheritedRole;
#[cfg(feature = "DeleteMfaDevice")]
pub mod DeleteMfaDevice;
#[cfg(feature = "DeletePermanentAccessKey")]
pub mod DeletePermanentAccessKey;
#[cfg(feature = "GetAccountSummaryV5")]
pub mod GetAccountSummaryV5;
#[cfg(feature = "KeystoneAddUserToGroup")]
pub mod KeystoneAddUserToGroup;
#[cfg(feature = "KeystoneAssociateGroupWithDomainPermission")]
pub mod KeystoneAssociateGroupWithDomainPermission;
#[cfg(feature = "KeystoneAssociateGroupWithProjectPermission")]
pub mod KeystoneAssociateGroupWithProjectPermission;
#[cfg(feature = "KeystoneCheckDomainPermissionForGroup")]
pub mod KeystoneCheckDomainPermissionForGroup;
#[cfg(feature = "KeystoneCheckProjectPermissionForGroup")]
pub mod KeystoneCheckProjectPermissionForGroup;
#[cfg(feature = "KeystoneCheckroleForGroup")]
pub mod KeystoneCheckroleForGroup;
#[cfg(feature = "KeystoneCheckUserInGroup")]
pub mod KeystoneCheckUserInGroup;
#[cfg(feature = "KeystoneCreateAgencyToken")]
pub mod KeystoneCreateAgencyToken;
#[cfg(feature = "KeystoneCreateGroup")]
pub mod KeystoneCreateGroup;
#[cfg(feature = "KeystoneCreateIdentityProvider")]
pub mod KeystoneCreateIdentityProvider;
#[cfg(feature = "KeystoneCreateMapping")]
pub mod KeystoneCreateMapping;
#[cfg(feature = "KeystoneCreateProject")]
pub mod KeystoneCreateProject;
#[cfg(feature = "KeystoneCreateProtocol")]
pub mod KeystoneCreateProtocol;
#[cfg(feature = "KeystoneCreateScopedToken")]
pub mod KeystoneCreateScopedToken;
#[cfg(feature = "KeystoneCreateUser")]
pub mod KeystoneCreateUser;
#[cfg(feature = "KeystoneCreateUserTokenByPassword")]
pub mod KeystoneCreateUserTokenByPassword;
#[cfg(feature = "KeystoneCreateUserTokenByPasswordAndMfa")]
pub mod KeystoneCreateUserTokenByPasswordAndMfa;
#[cfg(feature = "KeystoneDeleteGroup")]
pub mod KeystoneDeleteGroup;
#[cfg(feature = "KeystoneDeleteIdentityProvider")]
pub mod KeystoneDeleteIdentityProvider;
#[cfg(feature = "KeystoneDeleteMapping")]
pub mod KeystoneDeleteMapping;
#[cfg(feature = "KeystoneDeleteProtocol")]
pub mod KeystoneDeleteProtocol;
#[cfg(feature = "KeystoneDeleteUser")]
pub mod KeystoneDeleteUser;
#[cfg(feature = "KeystoneListAllProjectPermissionsForGroup")]
pub mod KeystoneListAllProjectPermissionsForGroup;
#[cfg(feature = "KeystoneListAuthDomains")]
pub mod KeystoneListAuthDomains;
#[cfg(feature = "KeystoneListAuthProjects")]
pub mod KeystoneListAuthProjects;
#[cfg(feature = "KeystoneListDomainPermissionsForGroup")]
pub mod KeystoneListDomainPermissionsForGroup;
#[cfg(feature = "KeystoneListEndpoints")]
pub mod KeystoneListEndpoints;
#[cfg(feature = "KeystoneListFederationDomains")]
pub mod KeystoneListFederationDomains;
#[cfg(feature = "KeystoneListFederationProjects")]
pub mod KeystoneListFederationProjects;
#[cfg(feature = "KeystoneListGroups")]
pub mod KeystoneListGroups;
#[cfg(feature = "KeystoneListGroupsForUser")]
pub mod KeystoneListGroupsForUser;
#[cfg(feature = "KeystoneListIdentityProviders")]
pub mod KeystoneListIdentityProviders;
#[cfg(feature = "KeystoneListMappings")]
pub mod KeystoneListMappings;
#[cfg(feature = "KeystoneListPermissions")]
pub mod KeystoneListPermissions;
#[cfg(feature = "KeystoneListProjectPermissionsForGroup")]
pub mod KeystoneListProjectPermissionsForGroup;
#[cfg(feature = "KeystoneListProjects")]
pub mod KeystoneListProjects;
#[cfg(feature = "KeystoneListProjectsForUser")]
pub mod KeystoneListProjectsForUser;
#[cfg(feature = "KeystoneListProtocols")]
pub mod KeystoneListProtocols;
#[cfg(feature = "KeystoneListRegions")]
pub mod KeystoneListRegions;
#[cfg(feature = "KeystoneListServices")]
pub mod KeystoneListServices;
#[cfg(feature = "KeystoneListUsers")]
pub mod KeystoneListUsers;
#[cfg(feature = "KeystoneListUsersForGroupByAdmin")]
pub mod KeystoneListUsersForGroupByAdmin;
#[cfg(feature = "KeystoneListVersions")]
pub mod KeystoneListVersions;
#[cfg(feature = "KeystoneRemoveDomainPermissionFromGroup")]
pub mod KeystoneRemoveDomainPermissionFromGroup;
#[cfg(feature = "KeystoneRemoveProjectPermissionFromGroup")]
pub mod KeystoneRemoveProjectPermissionFromGroup;
#[cfg(feature = "KeystoneRemoveUserFromGroup")]
pub mod KeystoneRemoveUserFromGroup;
#[cfg(feature = "KeystoneShowCatalog")]
pub mod KeystoneShowCatalog;
#[cfg(feature = "KeystoneShowEndpoint")]
pub mod KeystoneShowEndpoint;
#[cfg(feature = "KeystoneShowGroup")]
pub mod KeystoneShowGroup;
#[cfg(feature = "KeystoneShowIdentityProvider")]
pub mod KeystoneShowIdentityProvider;
#[cfg(feature = "KeystoneShowMapping")]
pub mod KeystoneShowMapping;
#[cfg(feature = "KeystoneShowPermission")]
pub mod KeystoneShowPermission;
#[cfg(feature = "KeystoneShowProject")]
pub mod KeystoneShowProject;
#[cfg(feature = "KeystoneShowProtocol")]
pub mod KeystoneShowProtocol;
#[cfg(feature = "KeystoneShowRegion")]
pub mod KeystoneShowRegion;
#[cfg(feature = "KeystoneShowSecurityCompliance")]
pub mod KeystoneShowSecurityCompliance;
#[cfg(feature = "KeystoneShowSecurityComplianceByOption")]
pub mod KeystoneShowSecurityComplianceByOption;
#[cfg(feature = "KeystoneShowService")]
pub mod KeystoneShowService;
#[cfg(feature = "KeystoneShowUser")]
pub mod KeystoneShowUser;
#[cfg(feature = "KeystoneShowVersion")]
pub mod KeystoneShowVersion;
#[cfg(feature = "KeystoneUpdateGroup")]
pub mod KeystoneUpdateGroup;
#[cfg(feature = "KeystoneUpdateIdentityProvider")]
pub mod KeystoneUpdateIdentityProvider;
#[cfg(feature = "KeystoneUpdateMapping")]
pub mod KeystoneUpdateMapping;
#[cfg(feature = "KeystoneUpdateProject")]
pub mod KeystoneUpdateProject;
#[cfg(feature = "KeystoneUpdateProtocol")]
pub mod KeystoneUpdateProtocol;
#[cfg(feature = "KeystoneUpdateUserByAdmin")]
pub mod KeystoneUpdateUserByAdmin;
#[cfg(feature = "KeystoneUpdateUserPassword")]
pub mod KeystoneUpdateUserPassword;
#[cfg(feature = "KeystoneValidateToken")]
pub mod KeystoneValidateToken;
#[cfg(feature = "ListAgencies")]
pub mod ListAgencies;
