#[cfg(feature = "AddUserToGroupV5")]
pub mod AddUserToGroupV5;
#[cfg(feature = "AssociateAgencyWithAllProjectsPermission")]
pub mod AssociateAgencyWithAllProjectsPermission;
#[cfg(feature = "AssociateAgencyWithDomainPermission")]
pub mod AssociateAgencyWithDomainPermission;
#[cfg(feature = "AssociateAgencyWithProjectPermission")]
pub mod AssociateAgencyWithProjectPermission;
#[cfg(feature = "AssociateRoleToAgencyOnEnterpriseProject")]
pub mod AssociateRoleToAgencyOnEnterpriseProject;
#[cfg(feature = "AssociateRoleToGroupOnEnterpriseProject")]
pub mod AssociateRoleToGroupOnEnterpriseProject;
#[cfg(feature = "AssociateRoleToUserOnEnterpriseProject")]
pub mod AssociateRoleToUserOnEnterpriseProject;
#[cfg(feature = "AttachAgencyPolicyV5")]
pub mod AttachAgencyPolicyV5;
#[cfg(feature = "AttachGroupPolicyV5")]
pub mod AttachGroupPolicyV5;
#[cfg(feature = "AttachUserPolicyV5")]
pub mod AttachUserPolicyV5;
#[cfg(feature = "ChangePasswordV5")]
pub mod ChangePasswordV5;
#[cfg(feature = "CheckAllProjectsPermissionForAgency")]
pub mod CheckAllProjectsPermissionForAgency;
#[cfg(feature = "CheckDomainPermissionForAgency")]
pub mod CheckDomainPermissionForAgency;
#[cfg(feature = "CheckProjectPermissionForAgency")]
pub mod CheckProjectPermissionForAgency;
#[cfg(feature = "CreateAccessKeyV5")]
pub mod CreateAccessKeyV5;
#[cfg(feature = "CreateAgency")]
pub mod CreateAgency;
#[cfg(feature = "CreateAgencyCustomPolicy")]
pub mod CreateAgencyCustomPolicy;
#[cfg(feature = "CreateAgencyV5")]
pub mod CreateAgencyV5;
#[cfg(feature = "CreateBindingDevice")]
pub mod CreateBindingDevice;
#[cfg(feature = "CreateCloudServiceCustomPolicy")]
pub mod CreateCloudServiceCustomPolicy;
#[cfg(feature = "CreateGroupV5")]
pub mod CreateGroupV5;
#[cfg(feature = "CreateLoginProfileV5")]
pub mod CreateLoginProfileV5;
#[cfg(feature = "CreateLoginToken")]
pub mod CreateLoginToken;
#[cfg(feature = "CreateMetadata")]
pub mod CreateMetadata;
#[cfg(feature = "CreateMfaDevice")]
pub mod CreateMfaDevice;
#[cfg(feature = "CreateOpenIdConnectConfig")]
pub mod CreateOpenIdConnectConfig;
#[cfg(feature = "CreatePermanentAccessKey")]
pub mod CreatePermanentAccessKey;
#[cfg(feature = "CreatePolicyV5")]
pub mod CreatePolicyV5;
#[cfg(feature = "CreatePolicyVersionV5")]
pub mod CreatePolicyVersionV5;
#[cfg(feature = "CreateServiceLinkedAgencyV5")]
pub mod CreateServiceLinkedAgencyV5;
#[cfg(feature = "CreateTemporaryAccessKeyByAgency")]
pub mod CreateTemporaryAccessKeyByAgency;
#[cfg(feature = "CreateTemporaryAccessKeyByToken")]
pub mod CreateTemporaryAccessKeyByToken;
#[cfg(feature = "CreateTokenWithIdToken")]
pub mod CreateTokenWithIdToken;
#[cfg(feature = "CreateUnscopedTokenWithIdToken")]
pub mod CreateUnscopedTokenWithIdToken;
#[cfg(feature = "CreateUnscopeTokenByIdpInitiated")]
pub mod CreateUnscopeTokenByIdpInitiated;
#[cfg(feature = "CreateUser")]
pub mod CreateUser;
#[cfg(feature = "CreateUserV5")]
pub mod CreateUserV5;
#[cfg(feature = "CreateVirtualMfaDeviceV5")]
pub mod CreateVirtualMfaDeviceV5;
#[cfg(feature = "DeleteAccessKeyV5")]
pub mod DeleteAccessKeyV5;
#[cfg(feature = "DeleteAgency")]
pub mod DeleteAgency;
#[cfg(feature = "DeleteAgencyV5")]
pub mod DeleteAgencyV5;
#[cfg(feature = "DeleteBindingDevice")]
pub mod DeleteBindingDevice;
#[cfg(feature = "DeleteCustomPolicy")]
pub mod DeleteCustomPolicy;
#[cfg(feature = "DeleteDomainGroupInheritedRole")]
pub mod DeleteDomainGroupInheritedRole;
#[cfg(feature = "DeleteGroupV5")]
pub mod DeleteGroupV5;
#[cfg(feature = "DeleteLoginProfileV5")]
pub mod DeleteLoginProfileV5;
#[cfg(feature = "DeleteMfaDevice")]
pub mod DeleteMfaDevice;
#[cfg(feature = "DeletePermanentAccessKey")]
pub mod DeletePermanentAccessKey;
#[cfg(feature = "DeletePolicyV5")]
pub mod DeletePolicyV5;
#[cfg(feature = "DeletePolicyVersionV5")]
pub mod DeletePolicyVersionV5;
#[cfg(feature = "DeleteResourceTagsV5")]
pub mod DeleteResourceTagsV5;
#[cfg(feature = "DeleteServiceLinkedAgencyV5")]
pub mod DeleteServiceLinkedAgencyV5;
#[cfg(feature = "DeleteUserV5")]
pub mod DeleteUserV5;
#[cfg(feature = "DeleteVirtualMfaDeviceV5")]
pub mod DeleteVirtualMfaDeviceV5;
#[cfg(feature = "DetachAgencyPolicyV5")]
pub mod DetachAgencyPolicyV5;
#[cfg(feature = "DetachGroupPolicyV5")]
pub mod DetachGroupPolicyV5;
#[cfg(feature = "DetachUserPolicyV5")]
pub mod DetachUserPolicyV5;
#[cfg(feature = "DisableMfaDeviceV5")]
pub mod DisableMfaDeviceV5;
#[cfg(feature = "EnableMfaDeviceV5")]
pub mod EnableMfaDeviceV5;
#[cfg(feature = "GetAccountSummaryV5")]
pub mod GetAccountSummaryV5;
#[cfg(feature = "GetAgencyV5")]
pub mod GetAgencyV5;
#[cfg(feature = "GetAsymmetricSignatureSwitchV5")]
pub mod GetAsymmetricSignatureSwitchV5;
#[cfg(feature = "GetAuthorizationSchemaV5")]
pub mod GetAuthorizationSchemaV5;
#[cfg(feature = "GetFeatureStatusV5")]
pub mod GetFeatureStatusV5;
#[cfg(feature = "GetPolicyV5")]
pub mod GetPolicyV5;
#[cfg(feature = "GetPolicyVersionV5")]
pub mod GetPolicyVersionV5;
#[cfg(feature = "GetServiceLinkedAgencyDeletionStatusV5")]
pub mod GetServiceLinkedAgencyDeletionStatusV5;
#[cfg(feature = "KeystoneAddUserToGroup")]
pub mod KeystoneAddUserToGroup;
#[cfg(feature = "KeystoneAssociateGroupWithDomainPermission")]
pub mod KeystoneAssociateGroupWithDomainPermission;
#[cfg(feature = "KeystoneAssociateGroupWithProjectPermission")]
pub mod KeystoneAssociateGroupWithProjectPermission;
#[cfg(feature = "KeystoneCheckDomainPermissionForGroup")]
pub mod KeystoneCheckDomainPermissionForGroup;
#[cfg(feature = "KeystoneCheckProjectPermissionForGroup")]
pub mod KeystoneCheckProjectPermissionForGroup;
#[cfg(feature = "KeystoneCheckroleForGroup")]
pub mod KeystoneCheckroleForGroup;
#[cfg(feature = "KeystoneCheckUserInGroup")]
pub mod KeystoneCheckUserInGroup;
#[cfg(feature = "KeystoneCreateAgencyToken")]
pub mod KeystoneCreateAgencyToken;
#[cfg(feature = "KeystoneCreateGroup")]
pub mod KeystoneCreateGroup;
#[cfg(feature = "KeystoneCreateIdentityProvider")]
pub mod KeystoneCreateIdentityProvider;
#[cfg(feature = "KeystoneCreateMapping")]
pub mod KeystoneCreateMapping;
#[cfg(feature = "KeystoneCreateProject")]
pub mod KeystoneCreateProject;
#[cfg(feature = "KeystoneCreateProtocol")]
pub mod KeystoneCreateProtocol;
#[cfg(feature = "KeystoneCreateScopedToken")]
pub mod KeystoneCreateScopedToken;
#[cfg(feature = "KeystoneCreateUser")]
pub mod KeystoneCreateUser;
#[cfg(feature = "KeystoneCreateUserTokenByPassword")]
pub mod KeystoneCreateUserTokenByPassword;
#[cfg(feature = "KeystoneCreateUserTokenByPasswordAndMfa")]
pub mod KeystoneCreateUserTokenByPasswordAndMfa;
#[cfg(feature = "KeystoneDeleteGroup")]
pub mod KeystoneDeleteGroup;
#[cfg(feature = "KeystoneDeleteIdentityProvider")]
pub mod KeystoneDeleteIdentityProvider;
#[cfg(feature = "KeystoneDeleteMapping")]
pub mod KeystoneDeleteMapping;
#[cfg(feature = "KeystoneDeleteProtocol")]
pub mod KeystoneDeleteProtocol;
#[cfg(feature = "KeystoneDeleteUser")]
pub mod KeystoneDeleteUser;
#[cfg(feature = "KeystoneListAllProjectPermissionsForGroup")]
pub mod KeystoneListAllProjectPermissionsForGroup;
#[cfg(feature = "KeystoneListAuthDomains")]
pub mod KeystoneListAuthDomains;
#[cfg(feature = "KeystoneListAuthProjects")]
pub mod KeystoneListAuthProjects;
#[cfg(feature = "KeystoneListDomainPermissionsForGroup")]
pub mod KeystoneListDomainPermissionsForGroup;
#[cfg(feature = "KeystoneListEndpoints")]
pub mod KeystoneListEndpoints;
#[cfg(feature = "KeystoneListFederationDomains")]
pub mod KeystoneListFederationDomains;
#[cfg(feature = "KeystoneListFederationProjects")]
pub mod KeystoneListFederationProjects;
#[cfg(feature = "KeystoneListGroups")]
pub mod KeystoneListGroups;
#[cfg(feature = "KeystoneListGroupsForUser")]
pub mod KeystoneListGroupsForUser;
#[cfg(feature = "KeystoneListIdentityProviders")]
pub mod KeystoneListIdentityProviders;
#[cfg(feature = "KeystoneListMappings")]
pub mod KeystoneListMappings;
