#[cfg(feature = "AddBlackWhiteIpList")]
pub mod AddBlackWhiteIpList;
#[cfg(feature = "AddPolicyBlackAndWhiteIpList")]
pub mod AddPolicyBlackAndWhiteIpList;
#[cfg(feature = "AssociateIpToPolicy")]
pub mod AssociateIpToPolicy;
#[cfg(feature = "AssociateIpToPolicyAndPackage")]
pub mod AssociateIpToPolicyAndPackage;
#[cfg(feature = "BatchCreateInstanceIpRule")]
pub mod BatchCreateInstanceIpRule;
#[cfg(feature = "BatchDeleteInstanceIpRule")]
pub mod BatchDeleteInstanceIpRule;
#[cfg(feature = "CreateAadDomain")]
pub mod CreateAadDomain;
#[cfg(feature = "CreateDomain")]
pub mod CreateDomain;
#[cfg(feature = "CreatePolicy")]
pub mod CreatePolicy;
#[cfg(feature = "DeleteAlarmConfig")]
pub mod DeleteAlarmConfig;
#[cfg(feature = "DeleteBlackWhiteIpList")]
pub mod DeleteBlackWhiteIpList;
#[cfg(feature = "DeleteDomain")]
pub mod DeleteDomain;
#[cfg(feature = "DeletePolicy")]
pub mod DeletePolicy;
#[cfg(feature = "DeletePolicyBlackAndWhiteIpList")]
pub mod DeletePolicyBlackAndWhiteIpList;
#[cfg(feature = "DisassociateIpFromPolicy")]
pub mod DisassociateIpFromPolicy;
#[cfg(feature = "DisassociateIpFromPolicyAndPackage")]
pub mod DisassociateIpFromPolicyAndPackage;
#[cfg(feature = "ExecuteUnblockIp")]
pub mod ExecuteUnblockIp;
#[cfg(feature = "ListBlockIps")]
pub mod ListBlockIps;
#[cfg(feature = "ListDDoSAttackEvent")]
pub mod ListDDoSAttackEvent;
#[cfg(feature = "ListDDoSConnectionNumber")]
pub mod ListDDoSConnectionNumber;
#[cfg(feature = "ListDDoSFlow")]
pub mod ListDDoSFlow;
#[cfg(feature = "ListDomain")]
pub mod ListDomain;
#[cfg(feature = "ListFrequencyControlRule")]
pub mod ListFrequencyControlRule;
#[cfg(feature = "ListInstance")]
pub mod ListInstance;
#[cfg(feature = "ListInstanceDomains")]
pub mod ListInstanceDomains;
#[cfg(feature = "ListInstanceId")]
pub mod ListInstanceId;
#[cfg(feature = "ListInstanceIpRule")]
pub mod ListInstanceIpRule;
#[cfg(feature = "ListPackage")]
pub mod ListPackage;
#[cfg(feature = "ListPeak")]
pub mod ListPeak;
#[cfg(feature = "ListPolicy")]
pub mod ListPolicy;
#[cfg(feature = "ListProtectedIp")]
pub mod ListProtectedIp;
#[cfg(feature = "ListSourceIps")]
pub mod ListSourceIps;
#[cfg(feature = "ListUnblockQuotaStatistics")]
pub mod ListUnblockQuotaStatistics;
#[cfg(feature = "ListUnboundProtectedIp")]
pub mod ListUnboundProtectedIp;
#[cfg(feature = "ListWafAttackEvent")]
pub mod ListWafAttackEvent;
#[cfg(feature = "ListWafBandwidth")]
pub mod ListWafBandwidth;
#[cfg(feature = "ListWafCustomRule")]
pub mod ListWafCustomRule;
#[cfg(feature = "ListWafGeoIpRule")]
pub mod ListWafGeoIpRule;
#[cfg(feature = "ListWafQps")]
pub mod ListWafQps;
#[cfg(feature = "ListWafWhiteIpRule")]
pub mod ListWafWhiteIpRule;
#[cfg(feature = "ListWhiteBlackIpRule")]
pub mod ListWhiteBlackIpRule;
#[cfg(feature = "ModifyDomainWebSwitch")]
pub mod ModifyDomainWebSwitch;
#[cfg(feature = "SetCertForDomain")]
pub mod SetCertForDomain;
#[cfg(feature = "ShowAlarmConfig")]
pub mod ShowAlarmConfig;
#[cfg(feature = "ShowBlockStatistics")]
pub mod ShowBlockStatistics;
#[cfg(feature = "ShowDomainCertificate")]
pub mod ShowDomainCertificate;
#[cfg(feature = "ShowFlowBlock")]
pub mod ShowFlowBlock;
#[cfg(feature = "ShowPolicy")]
pub mod ShowPolicy;
#[cfg(feature = "ShowUnblockRecord")]
pub mod ShowUnblockRecord;
#[cfg(feature = "ShowWafPolicy")]
pub mod ShowWafPolicy;
#[cfg(feature = "ShowWafQps")]
pub mod ShowWafQps;
#[cfg(feature = "UpdateAlarmConfig")]
pub mod UpdateAlarmConfig;
#[cfg(feature = "UpdateDomain")]
pub mod UpdateDomain;
#[cfg(feature = "UpdateInstanceIpRule")]
pub mod UpdateInstanceIpRule;
#[cfg(feature = "UpdatePackageIp")]
pub mod UpdatePackageIp;
#[cfg(feature = "UpdatePackageName")]
pub mod UpdatePackageName;
#[cfg(feature = "UpdatePolicy")]
pub mod UpdatePolicy;
#[cfg(feature = "UpdateTagForProtectedIp")]
pub mod UpdateTagForProtectedIp;
#[cfg(feature = "UpgradeInstanceSpec")]
pub mod UpgradeInstanceSpec;
