#[cfg(feature = "AddAttributeattribute")]
pub mod AddAttributeattribute;
#[cfg(feature = "AddTagExaDefinition")]
pub mod AddTagExaDefinition;
#[cfg(feature = "AddTagXdmSearchServDefineMaster")]
pub mod AddTagXdmSearchServDefineMaster;
#[cfg(feature = "AttachTagToExaAttrtag")]
pub mod AttachTagToExaAttrtag;
#[cfg(feature = "CheckHasAccessAccessService")]
pub mod CheckHasAccessAccessService;
#[cfg(feature = "CheckinXdmSearchServDefine")]
pub mod CheckinXdmSearchServDefine;
#[cfg(feature = "CheckoutAndUpdateXdmSearchServDefine")]
pub mod CheckoutAndUpdateXdmSearchServDefine;
#[cfg(feature = "CheckoutLifecycleTemplate")]
pub mod CheckoutLifecycleTemplate;
#[cfg(feature = "CheckoutXdmSearchServDefine")]
pub mod CheckoutXdmSearchServDefine;
#[cfg(feature = "CheckUniqueExaDefinition")]
pub mod CheckUniqueExaDefinition;
#[cfg(feature = "CheckUniqueFolder")]
pub mod CheckUniqueFolder;
#[cfg(feature = "CheckUniqueLifecycleTemplate")]
pub mod CheckUniqueLifecycleTemplate;
#[cfg(feature = "CheckUniquetag")]
pub mod CheckUniquetag;
#[cfg(feature = "CheckUniquetaggroup")]
pub mod CheckUniquetaggroup;
#[cfg(feature = "CheckUniqueunique")]
pub mod CheckUniqueunique;
#[cfg(feature = "CompareBusinessVersionLifecycleTemplate")]
pub mod CompareBusinessVersionLifecycleTemplate;
#[cfg(feature = "CompareBusinessVersionXdmSearchServDefine")]
pub mod CompareBusinessVersionXdmSearchServDefine;
#[cfg(feature = "CompareVersionBaseLine")]
pub mod CompareVersionBaseLine;
#[cfg(feature = "CompareVersionBaseLineLink")]
pub mod CompareVersionBaseLineLink;
#[cfg(feature = "CompareVersionClassificationNode")]
pub mod CompareVersionClassificationNode;
#[cfg(feature = "CompareVersionClassificationNodeGroup")]
pub mod CompareVersionClassificationNodeGroup;
#[cfg(feature = "CompareVersionExaDefinition")]
pub mod CompareVersionExaDefinition;
#[cfg(feature = "CompareVersionExaDefinitionLink")]
pub mod CompareVersionExaDefinitionLink;
#[cfg(feature = "CompareVersionFolder")]
pub mod CompareVersionFolder;
#[cfg(feature = "CompareVersionLifecycleBusinessOperation")]
pub mod CompareVersionLifecycleBusinessOperation;
#[cfg(feature = "CompareVersionLifecycleOperation")]
pub mod CompareVersionLifecycleOperation;
#[cfg(feature = "CompareVersionLifecyclePhase")]
pub mod CompareVersionLifecyclePhase;
#[cfg(feature = "CompareVersionLifecycleState")]
pub mod CompareVersionLifecycleState;
#[cfg(feature = "CompareVersionLifecycleTemplate")]
pub mod CompareVersionLifecycleTemplate;
#[cfg(feature = "CompareVersionLinkxSyncTask")]
pub mod CompareVersionLinkxSyncTask;
#[cfg(feature = "CompareVersionMeasuringUnit")]
pub mod CompareVersionMeasuringUnit;
#[cfg(feature = "CompareVersionTag")]
pub mod CompareVersionTag;
#[cfg(feature = "CompareVersionTagGroup")]
pub mod CompareVersionTagGroup;
#[cfg(feature = "CompareVersionTagLink")]
pub mod CompareVersionTagLink;
#[cfg(feature = "CompareVersionTenant")]
pub mod CompareVersionTenant;
#[cfg(feature = "CompareVersionTypeDefinition")]
pub mod CompareVersionTypeDefinition;
#[cfg(feature = "CompareVersionTypeDefinitionInheritLink")]
pub mod CompareVersionTypeDefinitionInheritLink;
#[cfg(feature = "CompareVersionUnitType")]
pub mod CompareVersionUnitType;
#[cfg(feature = "CompareVersionXDmPermissionAssignmentXdmPermissionAssignment")]
pub mod CompareVersionXDmPermissionAssignmentXdmPermissionAssignment;
#[cfg(feature = "CompareVersionXDmPermissionXdmPermission")]
pub mod CompareVersionXDmPermissionXdmPermission;
#[cfg(feature = "CompareVersionXDmPolicyRuleXdmPolicyRule")]
pub mod CompareVersionXDmPolicyRuleXdmPolicyRule;
#[cfg(feature = "CompareVersionXDmPrincipalRelationOperationHistory")]
pub mod CompareVersionXDmPrincipalRelationOperationHistory;
#[cfg(feature = "CompareVersionXDmRoleXdmRole")]
pub mod CompareVersionXDmRoleXdmRole;
#[cfg(feature = "CompareVersionXDmSearchColumnEntityXdmSearchColumnEntity")]
pub mod CompareVersionXDmSearchColumnEntityXdmSearchColumnEntity;
#[cfg(feature = "CompareVersionXDmUserGroupXdmUserGroup")]
pub mod CompareVersionXDmUserGroupXdmUserGroup;
#[cfg(feature = "CompareVersionXDmUserXdmUser")]
pub mod CompareVersionXDmUserXdmUser;
#[cfg(feature = "CountBaseLine")]
pub mod CountBaseLine;
#[cfg(feature = "CountClassificationNode")]
pub mod CountClassificationNode;
#[cfg(feature = "CountClassificationNodeGroup")]
pub mod CountClassificationNodeGroup;
#[cfg(feature = "CountDimensionBaseAttr")]
pub mod CountDimensionBaseAttr;
#[cfg(feature = "CountExaDefinition")]
pub mod CountExaDefinition;
#[cfg(feature = "CountExaDefinitionLink")]
pub mod CountExaDefinitionLink;
#[cfg(feature = "CountFolder")]
pub mod CountFolder;
#[cfg(feature = "CountFolderedLink")]
pub mod CountFolderedLink;
#[cfg(feature = "CountLegalValue")]
pub mod CountLegalValue;
#[cfg(feature = "CountLegalValueType")]
pub mod CountLegalValueType;
#[cfg(feature = "CountLifecycleBusinessOperation")]
pub mod CountLifecycleBusinessOperation;
#[cfg(feature = "CountLifecycleOperation")]
pub mod CountLifecycleOperation;
#[cfg(feature = "CountLifecycleTemplate")]
pub mod CountLifecycleTemplate;
#[cfg(feature = "CountLinkxSyncTask")]
pub mod CountLinkxSyncTask;
#[cfg(feature = "CountTagGroup")]
pub mod CountTagGroup;
#[cfg(feature = "CountTagLink")]
pub mod CountTagLink;
#[cfg(feature = "CountTypeDefinition")]
pub mod CountTypeDefinition;
#[cfg(feature = "CountTypeDefinitionInheritLink")]
pub mod CountTypeDefinitionInheritLink;
#[cfg(feature = "CountUnitType")]
pub mod CountUnitType;
#[cfg(feature = "CountXDmAspectXdmAspect")]
pub mod CountXDmAspectXdmAspect;
#[cfg(feature = "CountXDmFolderAndPolicySetRelationXdmFolderAndPolicySetRelation")]
pub mod CountXDmFolderAndPolicySetRelationXdmFolderAndPolicySetRelation;
#[cfg(feature = "CountXDmOperationRelationXdmOperationRelation")]
pub mod CountXDmOperationRelationXdmOperationRelation;
#[cfg(feature = "CountXDmPermissionAssignmentXdmPermissionAssignment")]
pub mod CountXDmPermissionAssignmentXdmPermissionAssignment;
#[cfg(feature = "CountXDmPermissionOperationXdmPermissionOperation")]
pub mod CountXDmPermissionOperationXdmPermissionOperation;
#[cfg(feature = "CountXDmPermissionXdmPermission")]
pub mod CountXDmPermissionXdmPermission;
#[cfg(feature = "CountXDmPolicySetXdmPolicySet")]
pub mod CountXDmPolicySetXdmPolicySet;
#[cfg(feature = "CountXDmSearchServDefineApiXdmSearchServDefineApi")]
pub mod CountXDmSearchServDefineApiXdmSearchServDefineApi;
#[cfg(feature = "CountXDmSearchServDefineXdmSearchServDefine")]
pub mod CountXDmSearchServDefineXdmSearchServDefine;
#[cfg(feature = "CountXDmSearchServRelationLogXdmSearchServRelationLog")]
pub mod CountXDmSearchServRelationLogXdmSearchServRelationLog;
#[cfg(feature = "CountXDmTeamAndFolderRelationXdmTeamAndFolderRelation")]
pub mod CountXDmTeamAndFolderRelationXdmTeamAndFolderRelation;
#[cfg(feature = "CountXDmTeamRoleXdmTeamRole")]
pub mod CountXDmTeamRoleXdmTeamRole;
#[cfg(feature = "CountXDmTeamXdmTeam")]
pub mod CountXDmTeamXdmTeam;
#[cfg(feature = "Createauthorization")]
pub mod Createauthorization;
#[cfg(feature = "CreateClassificationNode")]
pub mod CreateClassificationNode;
#[cfg(feature = "Createcustomservice")]
pub mod Createcustomservice;
#[cfg(feature = "CreateExaDefinition")]
pub mod CreateExaDefinition;
#[cfg(feature = "CreateExaDefinitionLink")]
pub mod CreateExaDefinitionLink;
#[cfg(feature = "CreateFolderedLink")]
pub mod CreateFolderedLink;
#[cfg(feature = "CreateLegalValueType")]
pub mod CreateLegalValueType;
#[cfg(feature = "CreateLifecycleBusinessOperation")]
pub mod CreateLifecycleBusinessOperation;
#[cfg(feature = "CreateLifecycleOperation")]
pub mod CreateLifecycleOperation;
#[cfg(feature = "CreateLifecycleState")]
pub mod CreateLifecycleState;
#[cfg(feature = "CreateLifecycleTemplateLink")]
pub mod CreateLifecycleTemplateLink;
#[cfg(feature = "Createtag")]
pub mod Createtag;
#[cfg(feature = "Createtaggroup")]
pub mod Createtaggroup;
#[cfg(feature = "CreateTenant")]
pub mod CreateTenant;
#[cfg(feature = "CreateUnitType")]
pub mod CreateUnitType;
#[cfg(feature = "CreateXDmOperationRelationXdmOperationRelation")]
pub mod CreateXDmOperationRelationXdmOperationRelation;
#[cfg(feature = "CreateXDmPermissionAssignmentXdmPermissionAssignment")]
pub mod CreateXDmPermissionAssignmentXdmPermissionAssignment;
#[cfg(feature = "CreateXDmPermissionOperationXdmPermissionOperation")]
pub mod CreateXDmPermissionOperationXdmPermissionOperation;
#[cfg(feature = "CreateXDmPermissionXdmPermission")]
pub mod CreateXDmPermissionXdmPermission;
#[cfg(feature = "CreateXDmPolicyRuleXdmPolicyRule")]
pub mod CreateXDmPolicyRuleXdmPolicyRule;
#[cfg(feature = "CreateXDmPolicyXdmPolicy")]
pub mod CreateXDmPolicyXdmPolicy;
#[cfg(feature = "CreateXDmRoleMemberXdmRoleMember")]
pub mod CreateXDmRoleMemberXdmRoleMember;
