[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddAlarmRuleResources = []
BatchCreateAgentInvocations = []
BatchCreateResources = []
BatchDeleteAlarmRules = []
BatchDeleteAlarmTemplates = []
BatchDeleteNotificationMasks = []
BatchDeleteOneClickAlarms = []
BatchDeleteResourceGroups = []
BatchDeleteResources = []
BatchEnableAlarmRules = []
BatchListMetricData = []
BatchUpdateNotificationMaskTime = []
BatchUpdateNotificationMasks = []
BatchUpdateOneClickAlarmPoliciesEnabledState = []
BatchUpdateOneClickAlarmsEnabledState = []
BatchUpdateWidgets = []
CreateAlarm = []
CreateAlarmRules = []
CreateAlarmTemplate = []
CreateDashboardWidgets = []
CreateEvents = []
CreateMetricData = []
CreateOneClickAlarm = []
CreateOneDashboard = []
CreateResourceGroup = []
DeleteAlarm = []
DeleteAlarmRuleResources = []
DeleteAlarmTemplate = []
DeleteDashboards = []
DeleteOneWidget = []
DeleteResourceGroup = []
ListAgentDimensionInfo = []
ListAgentInvocations = []
ListAgentStatus = []
ListAlarmHistories = []
ListAlarmRulePolicies = []
ListAlarmRuleResources = []
ListAlarmRules = []
ListAlarmTemplateAssociationAlarms = []
ListAlarmTemplates = []
ListAlarms = []
ListCesTargetProjectTags = []
ListDashboardInfos = []
ListDashboardWidgets = []
ListEventDetail = []
ListEvents = []
ListMetrics = []
ListNotificationMaskResources = []
ListNotificationMasks = []
ListOneClickAlarmRules = []
ListOneClickAlarms = []
ListResourceGroup = []
ListResourceGroups = []
ListResourceGroupsServicesResources = []
ShowAlarm = []
ShowAlarmTemplate = []
ShowEventData = []
ShowMetricData = []
ShowQuotas = []
ShowResourceGroup = []
ShowWidget = []
UpdateAlarm = []
UpdateAlarmAction = []
UpdateAlarmNotifications = []
UpdateAlarmRulePolicies = []
UpdateAlarmTemplate = []
UpdateDashboard = []
UpdateNotificationMask = []
UpdateOneClickAlarmNotifications = []
UpdateResourceGroup = []
UpdateResourceGroupAssociationAlarmTemplate = []
full = ["AddAlarmRuleResources", "BatchCreateAgentInvocations", "BatchCreateResources", "BatchDeleteAlarmRules", "BatchDeleteAlarmTemplates", "BatchDeleteNotificationMasks", "BatchDeleteOneClickAlarms", "BatchDeleteResourceGroups", "BatchDeleteResources", "BatchEnableAlarmRules", "BatchListMetricData", "BatchUpdateNotificationMasks", "BatchUpdateNotificationMaskTime", "BatchUpdateOneClickAlarmPoliciesEnabledState", "BatchUpdateOneClickAlarmsEnabledState", "BatchUpdateWidgets", "CreateAlarm", "CreateAlarmRules", "CreateAlarmTemplate", "CreateDashboardWidgets", "CreateEvents", "CreateMetricData", "CreateOneClickAlarm", "CreateOneDashboard", "CreateResourceGroup", "DeleteAlarm", "DeleteAlarmRuleResources", "DeleteAlarmTemplate", "DeleteDashboards", "DeleteOneWidget", "DeleteResourceGroup", "ListAgentDimensionInfo", "ListAgentInvocations", "ListAgentStatus", "ListAlarmHistories", "ListAlarmRulePolicies", "ListAlarmRuleResources", "ListAlarmRules", "ListAlarms", "ListAlarmTemplateAssociationAlarms", "ListAlarmTemplates", "ListCesTargetProjectTags", "ListDashboardInfos", "ListDashboardWidgets", "ListEventDetail", "ListEvents", "ListMetrics", "ListNotificationMaskResources", "ListNotificationMasks", "ListOneClickAlarmRules", "ListOneClickAlarms", "ListResourceGroup", "ListResourceGroups", "ListResourceGroupsServicesResources", "ShowAlarm", "ShowAlarmTemplate", "ShowEventData", "ShowMetricData", "ShowQuotas", "ShowResourceGroup", "ShowWidget", "UpdateAlarm", "UpdateAlarmAction", "UpdateAlarmNotifications", "UpdateAlarmRulePolicies", "UpdateAlarmTemplate", "UpdateDashboard", "UpdateNotificationMask", "UpdateOneClickAlarmNotifications", "UpdateResourceGroup", "UpdateResourceGroupAssociationAlarmTemplate"]

[lib]
name = "huawei_cloud_api_definitions_CES"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-CES"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
