[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddImageMember = []
BatchCreateTags = []
BatchDeleteTags = []
BatchExportCloudPhoneData = []
BatchImportCloudPhoneData = []
BatchShowPhoneConnectInfos = []
ChangeCloudPhoneServer = []
ChangeCloudPhoneServerModel = []
CreateNet2CloudPhoneServer = []
DeleteImage = []
DeleteImageMember = []
DeleteShareApps = []
DeleteShareFiles = []
ImportTraffic = []
InstallApk = []
ListCloudPhoneImages = []
ListCloudPhoneModels = []
ListCloudPhoneServerModels = []
ListCloudPhoneServers = []
ListCloudPhones = []
ListEncodeServers = []
ListImageMembers = []
ListImages = []
ListJobs = []
ListProjectTags = []
ListResourceInstances = []
ListResourceTags = []
ListShareFiles = []
PushFile = []
PushShareApps = []
PushShareFiles = []
ResetCloudPhone = []
RestartCloudPhone = []
RestartCloudPhoneServer = []
RestartEncodeServer = []
RunShellCommand = []
RunSyncCommand = []
ShowBandwidthDetail = []
ShowCloudPhoneDetail = []
ShowCloudPhoneServerDetail = []
ShowJob = []
StopCloudPhone = []
UninstallApk = []
UpdateBandwidth = []
UpdateCloudPhoneProperty = []
UpdateKeypair = []
UpdatePhoneName = []
UpdateServerName = []
full = ["AddImageMember", "BatchCreateTags", "BatchDeleteTags", "BatchExportCloudPhoneData", "BatchImportCloudPhoneData", "BatchShowPhoneConnectInfos", "ChangeCloudPhoneServer", "ChangeCloudPhoneServerModel", "CreateNet2CloudPhoneServer", "DeleteImage", "DeleteImageMember", "DeleteShareApps", "DeleteShareFiles", "ImportTraffic", "InstallApk", "ListCloudPhoneImages", "ListCloudPhoneModels", "ListCloudPhones", "ListCloudPhoneServerModels", "ListCloudPhoneServers", "ListEncodeServers", "ListImageMembers", "ListImages", "ListJobs", "ListProjectTags", "ListResourceInstances", "ListResourceTags", "ListShareFiles", "PushFile", "PushShareApps", "PushShareFiles", "ResetCloudPhone", "RestartCloudPhone", "RestartCloudPhoneServer", "RestartEncodeServer", "RunShellCommand", "RunSyncCommand", "ShowBandwidthDetail", "ShowCloudPhoneDetail", "ShowCloudPhoneServerDetail", "ShowJob", "StopCloudPhone", "UninstallApk", "UpdateBandwidth", "UpdateCloudPhoneProperty", "UpdateKeypair", "UpdatePhoneName", "UpdateServerName"]

[lib]
name = "huawei_cloud_api_definitions_CPH"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-CPH"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
