[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AbortMultipartUpload = []
AppendObject = []
CheckBucketOptions = []
CheckObjectOptions = []
CompleteMultipartUpload = []
CopyObject = []
CopyPart = []
CreateBucket = []
DeleteBucket = []
DeleteBucketCors = []
DeleteBucketCustomdomain = []
DeleteBucketEncryption = []
DeleteBucketInventory = []
DeleteBucketLifecycle = []
DeleteBucketMirrorBackToSource = []
DeleteBucketObsCompressPolicy = []
DeleteBucketPolicy = []
DeleteBucketReplication = []
DeleteBucketTagging = []
DeleteBucketWebsite = []
DeleteDirectcoldaccess = []
DeleteObject = []
DeleteObjects = []
GetBucketAcl = []
GetBucketCors = []
GetBucketCustomdomain = []
GetBucketEncryption = []
GetBucketInventory = []
GetBucketLifecycle = []
GetBucketLocation = []
GetBucketLogging = []
GetBucketMetadata = []
GetBucketMirrorBackToSource = []
GetBucketNotification = []
GetBucketObsCompressPolicy = []
GetBucketPolicy = []
GetBucketQuota = []
GetBucketReplication = []
GetBucketStorageInfo = []
GetBucketStoragePolicy = []
GetBucketTagging = []
GetBucketVersioning = []
GetBucketWebsite = []
GetDirectcoldaccess = []
GetObject = []
GetObjectAcl = []
GetObjectMetadata = []
InitiateMultipartUpload = []
ListBucketInventory = []
ListBuckets = []
ListMultipartUploads = []
ListObjects = []
ListParts = []
ListVersions = []
PutObject = []
RenameObject = []
RestoreObject = []
SetBucketAcl = []
SetBucketCors = []
SetBucketCustomedomain = []
SetBucketEncryption = []
SetBucketInventory = []
SetBucketLifecycle = []
SetBucketLogging = []
SetBucketMirrorBackToSource = []
SetBucketNotification = []
SetBucketObsCompressPolicy = []
SetBucketPolicy = []
SetBucketQuota = []
SetBucketReplication = []
SetBucketStoragePolicy = []
SetBucketTagging = []
SetBucketVersioning = []
SetBucketWebsite = []
SetDirectcoldaccess = []
SetObjectAcl = []
SetObjectMetadata = []
TruncateObject = []
UploadModifyObject = []
UploadObject = []
UploadPart = []
full = ["AbortMultipartUpload", "AppendObject", "CheckBucketOptions", "CheckObjectOptions", "CompleteMultipartUpload", "CopyObject", "CopyPart", "CreateBucket", "DeleteBucket", "DeleteBucketCors", "DeleteBucketCustomdomain", "DeleteBucketEncryption", "DeleteBucketInventory", "DeleteBucketLifecycle", "DeleteBucketMirrorBackToSource", "DeleteBucketObsCompressPolicy", "DeleteBucketPolicy", "DeleteBucketReplication", "DeleteBucketTagging", "DeleteBucketWebsite", "DeleteDirectcoldaccess", "DeleteObject", "DeleteObjects", "GetBucketAcl", "GetBucketCors", "GetBucketCustomdomain", "GetBucketEncryption", "GetBucketInventory", "GetBucketLifecycle", "GetBucketLocation", "GetBucketLogging", "GetBucketMetadata", "GetBucketMirrorBackToSource", "GetBucketNotification", "GetBucketObsCompressPolicy", "GetBucketPolicy", "GetBucketQuota", "GetBucketReplication", "GetBucketStorageInfo", "GetBucketStoragePolicy", "GetBucketTagging", "GetBucketVersioning", "GetBucketWebsite", "GetDirectcoldaccess", "GetObject", "GetObjectAcl", "GetObjectMetadata", "InitiateMultipartUpload", "ListBucketInventory", "ListBuckets", "ListMultipartUploads", "ListObjects", "ListParts", "ListVersions", "PutObject", "RenameObject", "RestoreObject", "SetBucketAcl", "SetBucketCors", "SetBucketCustomedomain", "SetBucketEncryption", "SetBucketInventory", "SetBucketLifecycle", "SetBucketLogging", "SetBucketMirrorBackToSource", "SetBucketNotification", "SetBucketObsCompressPolicy", "SetBucketPolicy", "SetBucketQuota", "SetBucketReplication", "SetBucketStoragePolicy", "SetBucketTagging", "SetBucketVersioning", "SetBucketWebsite", "SetDirectcoldaccess", "SetObjectAcl", "SetObjectMetadata", "TruncateObject", "UploadModifyObject", "UploadObject", "UploadPart"]

[lib]
name = "huawei_cloud_api_definitions_OBS"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-OBS"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "0.1.0"
