#[cfg(feature = "AcceptOrRejectEndpointConnections")]
pub mod AcceptOrRejectEndpointConnections;
#[cfg(feature = "AddCustomIngressPort")]
pub mod AddCustomIngressPort;
#[cfg(feature = "AddEipV2")]
pub mod AddEipV2;
#[cfg(feature = "AddEndpointPermissions")]
pub mod AddEndpointPermissions;
#[cfg(feature = "AddEngressEipV2")]
pub mod AddEngressEipV2;
#[cfg(feature = "AddingBackendInstancesV2")]
pub mod AddingBackendInstancesV2;
#[cfg(feature = "AddIngressEipV2")]
pub mod AddIngressEipV2;
#[cfg(feature = "AssociateAppsForAppQuota")]
pub mod AssociateAppsForAppQuota;
#[cfg(feature = "AssociateCertificate")]
pub mod AssociateCertificate;
#[cfg(feature = "AssociateCertificateV2")]
pub mod AssociateCertificateV2;
#[cfg(feature = "AssociateDomain")]
pub mod AssociateDomain;
#[cfg(feature = "AssociateDomainV2")]
pub mod AssociateDomainV2;
#[cfg(feature = "AssociateRequestThrottlingPolicy")]
pub mod AssociateRequestThrottlingPolicy;
#[cfg(feature = "AssociateRequestThrottlingPolicyV2")]
pub mod AssociateRequestThrottlingPolicyV2;
#[cfg(feature = "AssociateSignatureKey")]
pub mod AssociateSignatureKey;
#[cfg(feature = "AssociateSignatureKeyV2")]
pub mod AssociateSignatureKeyV2;
#[cfg(feature = "AttachApiToPlugin")]
pub mod AttachApiToPlugin;
#[cfg(feature = "AttachPluginToApi")]
pub mod AttachPluginToApi;
#[cfg(feature = "BatchAssociateCertsV2")]
pub mod BatchAssociateCertsV2;
#[cfg(feature = "BatchAssociateDomainsV2")]
pub mod BatchAssociateDomainsV2;
#[cfg(feature = "BatchCreateOrDeleteInstanceTags")]
pub mod BatchCreateOrDeleteInstanceTags;
#[cfg(feature = "BatchDeleteAclV2")]
pub mod BatchDeleteAclV2;
#[cfg(feature = "BatchDeleteApiAclBindingV2")]
pub mod BatchDeleteApiAclBindingV2;
#[cfg(feature = "BatchDisableMembers")]
pub mod BatchDisableMembers;
#[cfg(feature = "BatchDisassociateCertsV2")]
pub mod BatchDisassociateCertsV2;
#[cfg(feature = "BatchDisassociateDomainsV2")]
pub mod BatchDisassociateDomainsV2;
#[cfg(feature = "BatchDisassociateThrottlingPolicyV2")]
pub mod BatchDisassociateThrottlingPolicyV2;
#[cfg(feature = "BatchEnableMembers")]
pub mod BatchEnableMembers;
#[cfg(feature = "BatchPublishOrOfflineApiV2")]
pub mod BatchPublishOrOfflineApiV2;
#[cfg(feature = "CancelingAuthorization")]
pub mod CancelingAuthorization;
#[cfg(feature = "CancelingAuthorizationV2")]
pub mod CancelingAuthorizationV2;
#[cfg(feature = "ChangeApiVersionV2")]
pub mod ChangeApiVersionV2;
#[cfg(feature = "CheckAnApp")]
pub mod CheckAnApp;
#[cfg(feature = "CheckApiGroupsV2")]
pub mod CheckApiGroupsV2;
#[cfg(feature = "CheckApisV2")]
pub mod CheckApisV2;
#[cfg(feature = "CheckAppV2")]
pub mod CheckAppV2;
#[cfg(feature = "CreateAclStrategyV2")]
pub mod CreateAclStrategyV2;
#[cfg(feature = "CreateAnApp")]
pub mod CreateAnApp;
#[cfg(feature = "CreateAnAppV2")]
pub mod CreateAnAppV2;
#[cfg(feature = "CreateApi")]
pub mod CreateApi;
#[cfg(feature = "CreateApiAclBindingV2")]
pub mod CreateApiAclBindingV2;
#[cfg(feature = "CreateApiGroup")]
pub mod CreateApiGroup;
#[cfg(feature = "CreateApiGroupV2")]
pub mod CreateApiGroupV2;
#[cfg(feature = "CreateApiV2")]
pub mod CreateApiV2;
#[cfg(feature = "CreateAppCodeAutoV2")]
pub mod CreateAppCodeAutoV2;
#[cfg(feature = "CreateAppCodeV2")]
pub mod CreateAppCodeV2;
#[cfg(feature = "CreateAppQuota")]
pub mod CreateAppQuota;
#[cfg(feature = "CreateAuthorizingApps")]
pub mod CreateAuthorizingApps;
#[cfg(feature = "CreateAuthorizingAppsV2")]
pub mod CreateAuthorizingAppsV2;
#[cfg(feature = "CreateCertificateV2")]
pub mod CreateCertificateV2;
#[cfg(feature = "CreateCustomAuthorizerV2")]
pub mod CreateCustomAuthorizerV2;
#[cfg(feature = "CreateEnvironment")]
pub mod CreateEnvironment;
#[cfg(feature = "CreateEnvironmentV2")]
pub mod CreateEnvironmentV2;
#[cfg(feature = "CreateEnvironmentVariable")]
pub mod CreateEnvironmentVariable;
#[cfg(feature = "CreateEnvironmentVariableV2")]
pub mod CreateEnvironmentVariableV2;
#[cfg(feature = "CreateFeatureV2")]
pub mod CreateFeatureV2;
#[cfg(feature = "CreateGatewayResponseV2")]
pub mod CreateGatewayResponseV2;
#[cfg(feature = "CreateInstanceV2")]
pub mod CreateInstanceV2;
#[cfg(feature = "CreateMemberGroup")]
pub mod CreateMemberGroup;
#[cfg(feature = "CreateOrchestration")]
pub mod CreateOrchestration;
#[cfg(feature = "CreateOrDeletePublishRecordForApiV2")]
pub mod CreateOrDeletePublishRecordForApiV2;
#[cfg(feature = "CreateOrder")]
pub mod CreateOrder;
#[cfg(feature = "CreatePlugin")]
pub mod CreatePlugin;
#[cfg(feature = "CreatePostPayResizeOrder")]
pub mod CreatePostPayResizeOrder;
#[cfg(feature = "CreatePrepayResize")]
pub mod CreatePrepayResize;
#[cfg(feature = "CreateRequestThrottlingPolicy")]
pub mod CreateRequestThrottlingPolicy;
#[cfg(feature = "CreateRequestThrottlingPolicyV2")]
pub mod CreateRequestThrottlingPolicyV2;
#[cfg(feature = "CreateSignatureKey")]
pub mod CreateSignatureKey;
#[cfg(feature = "CreateSignatureKeyV2")]
pub mod CreateSignatureKeyV2;
#[cfg(feature = "CreateSpecialThrottlingConfiguration")]
pub mod CreateSpecialThrottlingConfiguration;
#[cfg(feature = "CreateSpecialThrottlingConfigurationV2")]
pub mod CreateSpecialThrottlingConfigurationV2;
#[cfg(feature = "CreateVpcChannelV2")]
pub mod CreateVpcChannelV2;
#[cfg(feature = "DebugApiV2")]
pub mod DebugApiV2;
#[cfg(feature = "DeleteAclV2")]
pub mod DeleteAclV2;
#[cfg(feature = "DeleteAnApp")]
pub mod DeleteAnApp;
#[cfg(feature = "DeleteApi")]
pub mod DeleteApi;
#[cfg(feature = "DeleteApiAclBindingV2")]
pub mod DeleteApiAclBindingV2;
#[cfg(feature = "DeleteApiByVersionIdV2")]
pub mod DeleteApiByVersionIdV2;
#[cfg(feature = "DeleteApiGroup")]
pub mod DeleteApiGroup;
#[cfg(feature = "DeleteApiGroupV2")]
pub mod DeleteApiGroupV2;
#[cfg(feature = "DeleteApiV2")]
pub mod DeleteApiV2;
#[cfg(feature = "DeleteAppAcl")]
pub mod DeleteAppAcl;
#[cfg(feature = "DeleteAppCodeV2")]
pub mod DeleteAppCodeV2;
#[cfg(feature = "DeleteAppQuota")]
pub mod DeleteAppQuota;
#[cfg(feature = "DeleteAppV2")]
pub mod DeleteAppV2;
#[cfg(feature = "DeleteBackendInstanceV2")]
pub mod DeleteBackendInstanceV2;
#[cfg(feature = "DeleteCertificateV2")]
pub mod DeleteCertificateV2;
#[cfg(feature = "DeleteCustomAuthorizerV2")]
pub mod DeleteCustomAuthorizerV2;
#[cfg(feature = "DeleteCustomIngressPort")]
pub mod DeleteCustomIngressPort;
#[cfg(feature = "DeleteEndpointPermissions")]
pub mod DeleteEndpointPermissions;
#[cfg(feature = "DeleteEnvironment")]
pub mod DeleteEnvironment;
#[cfg(feature = "DeleteEnvironmentV2")]
pub mod DeleteEnvironmentV2;
#[cfg(feature = "DeleteEnvironmentVariable")]
pub mod DeleteEnvironmentVariable;
#[cfg(feature = "DeleteEnvironmentVariableV2")]
pub mod DeleteEnvironmentVariableV2;
#[cfg(feature = "DeleteGatewayResponseTypeV2")]
pub mod DeleteGatewayResponseTypeV2;
#[cfg(feature = "DeleteGatewayResponseV2")]
pub mod DeleteGatewayResponseV2;
#[cfg(feature = "DeleteInstancesV2")]
pub mod DeleteInstancesV2;
#[cfg(feature = "DeleteMemberGroup")]
pub mod DeleteMemberGroup;
#[cfg(feature = "DeleteOrchestration")]
pub mod DeleteOrchestration;
#[cfg(feature = "DeletePlugin")]
pub mod DeletePlugin;
