#[cfg(feature = "AddPartitions")]
pub mod AddPartitions;
#[cfg(feature = "ApplyForAccess")]
pub mod ApplyForAccess;
#[cfg(feature = "AssociatePrincipals")]
pub mod AssociatePrincipals;
#[cfg(feature = "AssociateRoles")]
pub mod AssociateRoles;
#[cfg(feature = "AuthorizeAccessService")]
pub mod AuthorizeAccessService;
#[cfg(feature = "BatchAuthorizeInterface")]
pub mod BatchAuthorizeInterface;
#[cfg(feature = "BatchCancelAuthorizationInterface")]
pub mod BatchCancelAuthorizationInterface;
#[cfg(feature = "BatchCheckPermission")]
pub mod BatchCheckPermission;
#[cfg(feature = "BatchDeletePartition")]
pub mod BatchDeletePartition;
#[cfg(feature = "BatchListPartitionByValues")]
pub mod BatchListPartitionByValues;
#[cfg(feature = "BatchShowPartitionColumnStatistics")]
pub mod BatchShowPartitionColumnStatistics;
#[cfg(feature = "BatchUpdateLakeFormationInstanceTags")]
pub mod BatchUpdateLakeFormationInstanceTags;
#[cfg(feature = "BatchUpdatePartition")]
pub mod BatchUpdatePartition;
#[cfg(feature = "CountMetaObj")]
pub mod CountMetaObj;
#[cfg(feature = "CreateAccessClient")]
pub mod CreateAccessClient;
#[cfg(feature = "CreateAgency")]
pub mod CreateAgency;
#[cfg(feature = "CreateAgreement")]
pub mod CreateAgreement;
#[cfg(feature = "CreateCatalog")]
pub mod CreateCatalog;
#[cfg(feature = "CreateDatabase")]
pub mod CreateDatabase;
#[cfg(feature = "CreateFunction")]
pub mod CreateFunction;
#[cfg(feature = "CreateLakeFormationInstance")]
pub mod CreateLakeFormationInstance;
#[cfg(feature = "CreateRole")]
pub mod CreateRole;
#[cfg(feature = "CreateTable")]
pub mod CreateTable;
#[cfg(feature = "DeleteAccessClient")]
pub mod DeleteAccessClient;
#[cfg(feature = "DeleteAgency")]
pub mod DeleteAgency;
#[cfg(feature = "DeleteAgreement")]
pub mod DeleteAgreement;
#[cfg(feature = "DeleteCatalog")]
pub mod DeleteCatalog;
#[cfg(feature = "DeleteDatabase")]
pub mod DeleteDatabase;
#[cfg(feature = "DeleteFunction")]
pub mod DeleteFunction;
#[cfg(feature = "DeleteLakeFormationInstance")]
pub mod DeleteLakeFormationInstance;
#[cfg(feature = "DeletePartitionColumnStatistics")]
pub mod DeletePartitionColumnStatistics;
#[cfg(feature = "DeleteRole")]
pub mod DeleteRole;
#[cfg(feature = "DeleteTable")]
pub mod DeleteTable;
#[cfg(feature = "DeleteTableColumnStatistics")]
pub mod DeleteTableColumnStatistics;
#[cfg(feature = "ListAccessClientInfos")]
pub mod ListAccessClientInfos;
#[cfg(feature = "ListAccessInfos")]
pub mod ListAccessInfos;
#[cfg(feature = "ListAllFunctions")]
pub mod ListAllFunctions;
#[cfg(feature = "ListCatalogs")]
pub mod ListCatalogs;
#[cfg(feature = "ListConfigs")]
pub mod ListConfigs;
#[cfg(feature = "ListDatabaseNames")]
pub mod ListDatabaseNames;
#[cfg(feature = "ListDatabases")]
pub mod ListDatabases;
#[cfg(feature = "ListFunctionNames")]
pub mod ListFunctionNames;
#[cfg(feature = "ListFunctions")]
pub mod ListFunctions;
#[cfg(feature = "ListGroupsForDomain")]
pub mod ListGroupsForDomain;
#[cfg(feature = "ListInterfaces")]
pub mod ListInterfaces;
#[cfg(feature = "ListLakeFormationInstances")]
pub mod ListLakeFormationInstances;
#[cfg(feature = "ListLakeFormationInstanceTags")]
pub mod ListLakeFormationInstanceTags;
#[cfg(feature = "ListObsBuckets")]
pub mod ListObsBuckets;
#[cfg(feature = "ListObsObject")]
pub mod ListObsObject;
#[cfg(feature = "ListPartitionNames")]
pub mod ListPartitionNames;
#[cfg(feature = "ListPartitionNamesWithoutLimit")]
pub mod ListPartitionNamesWithoutLimit;
#[cfg(feature = "ListPartitions")]
pub mod ListPartitions;
#[cfg(feature = "ListPolicy")]
pub mod ListPolicy;
#[cfg(feature = "ListPrincipals")]
pub mod ListPrincipals;
#[cfg(feature = "ListQuotas")]
pub mod ListQuotas;
#[cfg(feature = "ListRoleNames")]
pub mod ListRoleNames;
#[cfg(feature = "ListRoles")]
pub mod ListRoles;
#[cfg(feature = "ListSpecs")]
pub mod ListSpecs;
#[cfg(feature = "ListTableColumnStatistics")]
pub mod ListTableColumnStatistics;
#[cfg(feature = "ListTableMeta")]
pub mod ListTableMeta;
#[cfg(feature = "ListTableNames")]
pub mod ListTableNames;
#[cfg(feature = "ListTables")]
pub mod ListTables;
#[cfg(feature = "ListTablesByName")]
pub mod ListTablesByName;
#[cfg(feature = "ListUserRoles")]
pub mod ListUserRoles;
#[cfg(feature = "ListUsers")]
pub mod ListUsers;
#[cfg(feature = "MoveLakeFormationInstanceOutRecycleBin")]
pub mod MoveLakeFormationInstanceOutRecycleBin;
#[cfg(feature = "RevokePrincipals")]
pub mod RevokePrincipals;
#[cfg(feature = "RevokeRoles")]
pub mod RevokeRoles;
#[cfg(feature = "SetPartitionColumnStatistics")]
pub mod SetPartitionColumnStatistics;
#[cfg(feature = "SetTableColumnStatistics")]
pub mod SetTableColumnStatistics;
#[cfg(feature = "ShowAccessClient")]
pub mod ShowAccessClient;
#[cfg(feature = "ShowAccessService")]
pub mod ShowAccessService;
#[cfg(feature = "ShowAgency")]
pub mod ShowAgency;
#[cfg(feature = "ShowAgreement")]
pub mod ShowAgreement;
#[cfg(feature = "ShowAgreementRule")]
pub mod ShowAgreementRule;
#[cfg(feature = "ShowCatalog")]
pub mod ShowCatalog;
#[cfg(feature = "ShowCredential")]
pub mod ShowCredential;
#[cfg(feature = "ShowDatabase")]
pub mod ShowDatabase;
#[cfg(feature = "ShowFunction")]
pub mod ShowFunction;
#[cfg(feature = "ShowLakeFormationInstance")]
pub mod ShowLakeFormationInstance;
#[cfg(feature = "ShowRole")]
pub mod ShowRole;
#[cfg(feature = "ShowSyncPolicy")]
pub mod ShowSyncPolicy;
#[cfg(feature = "ShowTable")]
pub mod ShowTable;
#[cfg(feature = "UpdateAccessClient")]
pub mod UpdateAccessClient;
#[cfg(feature = "UpdateCatalog")]
pub mod UpdateCatalog;
#[cfg(feature = "UpdateDatabase")]
pub mod UpdateDatabase;
#[cfg(feature = "UpdateFunction")]
pub mod UpdateFunction;
#[cfg(feature = "UpdateLakeFormationInstance")]
pub mod UpdateLakeFormationInstance;
#[cfg(feature = "UpdateLakeFormationInstanceDefault")]
pub mod UpdateLakeFormationInstanceDefault;
#[cfg(feature = "UpdateLakeFormationInstanceScale")]
pub mod UpdateLakeFormationInstanceScale;
#[cfg(feature = "UpdatePrincipals")]
pub mod UpdatePrincipals;
#[cfg(feature = "UpdateRole")]
pub mod UpdateRole;
#[cfg(feature = "UpdateRoles")]
pub mod UpdateRoles;
#[cfg(feature = "UpdateTable")]
pub mod UpdateTable;
