#[cfg(feature = "BatchStartStopTask")]
pub mod BatchStartStopTask;
#[cfg(feature = "CreateBatchTask")]
pub mod CreateBatchTask;
#[cfg(feature = "CreateEdgePool")]
pub mod CreateEdgePool;
#[cfg(feature = "CreateTask")]
pub mod CreateTask;
#[cfg(feature = "CreateVideoGroup")]
pub mod CreateVideoGroup;
#[cfg(feature = "CreateVideoSource")]
pub mod CreateVideoSource;
#[cfg(feature = "DeleteBatchTask")]
pub mod DeleteBatchTask;
#[cfg(feature = "DeleteEdgePool")]
pub mod DeleteEdgePool;
#[cfg(feature = "DeleteTask")]
pub mod DeleteTask;
#[cfg(feature = "DeleteVideoGroup")]
pub mod DeleteVideoGroup;
#[cfg(feature = "DeleteVideoSource")]
pub mod DeleteVideoSource;
#[cfg(feature = "DeployAlgorithm")]
pub mod DeployAlgorithm;
#[cfg(feature = "ListBatchTasks")]
pub mod ListBatchTasks;
#[cfg(feature = "ListEdgePools")]
pub mod ListEdgePools;
#[cfg(feature = "ListTasks")]
pub mod ListTasks;
#[cfg(feature = "ListUserServices")]
pub mod ListUserServices;
#[cfg(feature = "ListVideoGroups")]
pub mod ListVideoGroups;
#[cfg(feature = "ListVideoSources")]
pub mod ListVideoSources;
#[cfg(feature = "ShowEdgePoolInfo")]
pub mod ShowEdgePoolInfo;
#[cfg(feature = "ShowServiceDetail")]
pub mod ShowServiceDetail;
#[cfg(feature = "ShowTaskInfo")]
pub mod ShowTaskInfo;
#[cfg(feature = "ShowVideoGroupDetail")]
pub mod ShowVideoGroupDetail;
#[cfg(feature = "ShowVideoSourceDetail")]
pub mod ShowVideoSourceDetail;
#[cfg(feature = "StartStopTask")]
pub mod StartStopTask;
#[cfg(feature = "StopDeployAlgorithm")]
pub mod StopDeployAlgorithm;
#[cfg(feature = "UpdateBatchTask")]
pub mod UpdateBatchTask;
#[cfg(feature = "UpdateTask")]
pub mod UpdateTask;
#[cfg(feature = "UpdateVideoGroup")]
pub mod UpdateVideoGroup;
#[cfg(feature = "UpdateVideoSource")]
pub mod UpdateVideoSource;
