#[cfg(feature = "BindResourceLevelCompliance")]
pub mod BindResourceLevelCompliance;
#[cfg(feature = "ChangeResourcesLevel")]
pub mod ChangeResourcesLevel;
#[cfg(feature = "CreateComplianceRule")]
pub mod CreateComplianceRule;
#[cfg(feature = "CreatePolicy")]
pub mod CreatePolicy;
#[cfg(feature = "CreateReportSetting")]
pub mod CreateReportSetting;
#[cfg(feature = "CreateResourcesLevel")]
pub mod CreateResourcesLevel;
#[cfg(feature = "CreateTemplate")]
pub mod CreateTemplate;
#[cfg(feature = "DeleteComplianceRule")]
pub mod DeleteComplianceRule;
#[cfg(feature = "DeletePolicy")]
pub mod DeletePolicy;
#[cfg(feature = "DeleteReport")]
pub mod DeleteReport;
#[cfg(feature = "DeleteReportSetting")]
pub mod DeleteReportSetting;
#[cfg(feature = "DeleteTemplate")]
pub mod DeleteTemplate;
#[cfg(feature = "EnableDomain")]
pub mod EnableDomain;
#[cfg(feature = "ListAlarmRules")]
pub mod ListAlarmRules;
#[cfg(feature = "ListAlarms")]
pub mod ListAlarms;
#[cfg(feature = "ListComplianceRule")]
pub mod ListComplianceRule;
#[cfg(feature = "ListEvents")]
pub mod ListEvents;
#[cfg(feature = "ListMetrics")]
pub mod ListMetrics;
#[cfg(feature = "ListOrganizationPolicy")]
pub mod ListOrganizationPolicy;
#[cfg(feature = "ListPolicy")]
pub mod ListPolicy;
#[cfg(feature = "ListReports")]
pub mod ListReports;
#[cfg(feature = "ListReportSettings")]
pub mod ListReportSettings;
#[cfg(feature = "ListResourceCopies")]
pub mod ListResourceCopies;
#[cfg(feature = "ListResources")]
pub mod ListResources;
#[cfg(feature = "ListResourcesLevel")]
pub mod ListResourcesLevel;
#[cfg(feature = "ListResourcesLevelTags")]
pub mod ListResourcesLevelTags;
#[cfg(feature = "ListSupportedRegion")]
pub mod ListSupportedRegion;
#[cfg(feature = "ListTasks")]
pub mod ListTasks;
#[cfg(feature = "ListTemplates")]
pub mod ListTemplates;
#[cfg(feature = "ListVault")]
pub mod ListVault;
#[cfg(feature = "ListVaultTops")]
pub mod ListVaultTops;
#[cfg(feature = "ModifyResourceLevel")]
pub mod ModifyResourceLevel;
#[cfg(feature = "NotifyResourceChange")]
pub mod NotifyResourceChange;
#[cfg(feature = "RemoveResourceLevel")]
pub mod RemoveResourceLevel;
#[cfg(feature = "SetProtectionConfiguration")]
pub mod SetProtectionConfiguration;
#[cfg(feature = "ShowAlarmSummary")]
pub mod ShowAlarmSummary;
#[cfg(feature = "ShowComplianceRule")]
pub mod ShowComplianceRule;
#[cfg(feature = "ShowDomain")]
pub mod ShowDomain;
#[cfg(feature = "ShowOrganizationPolicy")]
pub mod ShowOrganizationPolicy;
#[cfg(feature = "ShowPolicy")]
pub mod ShowPolicy;
#[cfg(feature = "ShowReport")]
pub mod ShowReport;
#[cfg(feature = "ShowReportResourceDetailsData")]
pub mod ShowReportResourceDetailsData;
#[cfg(feature = "ShowReportSetting")]
pub mod ShowReportSetting;
#[cfg(feature = "ShowReportSummaryData")]
pub mod ShowReportSummaryData;
#[cfg(feature = "ShowReportTaskDetailsData")]
pub mod ShowReportTaskDetailsData;
#[cfg(feature = "ShowResourceCopiesSummary")]
pub mod ShowResourceCopiesSummary;
#[cfg(feature = "ShowResourceDetail")]
pub mod ShowResourceDetail;
#[cfg(feature = "ShowResourcesSummary")]
pub mod ShowResourcesSummary;
#[cfg(feature = "ShowTask")]
pub mod ShowTask;
#[cfg(feature = "ShowTaskStatusSummary")]
pub mod ShowTaskStatusSummary;
#[cfg(feature = "ShowTaskTypeSummary")]
pub mod ShowTaskTypeSummary;
#[cfg(feature = "ShowTemplate")]
pub mod ShowTemplate;
#[cfg(feature = "ShowVault")]
pub mod ShowVault;
#[cfg(feature = "ShowVaultSummary")]
pub mod ShowVaultSummary;
#[cfg(feature = "UnbindResourceLevelCompliance")]
pub mod UnbindResourceLevelCompliance;
#[cfg(feature = "UpdateComplianceRule")]
pub mod UpdateComplianceRule;
#[cfg(feature = "UpdatePolicy")]
pub mod UpdatePolicy;
#[cfg(feature = "UpdateReportSetting")]
pub mod UpdateReportSetting;
#[cfg(feature = "UpdateTemplate")]
pub mod UpdateTemplate;
