#[cfg(feature = "AuthorizeDomains")]
pub mod AuthorizeDomains;
#[cfg(feature = "CancelTasks")]
pub mod CancelTasks;
#[cfg(feature = "CreateDomains")]
pub mod CreateDomains;
#[cfg(feature = "CreateTasks")]
pub mod CreateTasks;
#[cfg(feature = "DeleteDomains")]
pub mod DeleteDomains;
#[cfg(feature = "DownloadTaskReport")]
pub mod DownloadTaskReport;
#[cfg(feature = "ExecuteGenerateReport")]
pub mod ExecuteGenerateReport;
#[cfg(feature = "ListBusinessRisks")]
pub mod ListBusinessRisks;
#[cfg(feature = "ListDomains")]
pub mod ListDomains;
#[cfg(feature = "ListPortResults")]
pub mod ListPortResults;
#[cfg(feature = "ListTaskHistories")]
pub mod ListTaskHistories;
#[cfg(feature = "ShowDomainSettings")]
pub mod ShowDomainSettings;
#[cfg(feature = "ShowReportStatus")]
pub mod ShowReportStatus;
#[cfg(feature = "ShowResults")]
pub mod ShowResults;
#[cfg(feature = "ShowTasks")]
pub mod ShowTasks;
#[cfg(feature = "UpdateDomainSettings")]
pub mod UpdateDomainSettings;
#[cfg(feature = "UpdateFalsePositive")]
pub mod UpdateFalsePositive;
