#[cfg(feature = "AddGroup")]
pub mod AddGroup;
#[cfg(feature = "AuthorizeDomains")]
pub mod AuthorizeDomains;
#[cfg(feature = "BatchCreateHosts")]
pub mod BatchCreateHosts;
#[cfg(feature = "BatchStartHostTasks")]
pub mod BatchStartHostTasks;
#[cfg(feature = "CancelTasks")]
pub mod CancelTasks;
#[cfg(feature = "CreateDomains")]
pub mod CreateDomains;
#[cfg(feature = "CreateTasks")]
pub mod CreateTasks;
#[cfg(feature = "DeleteDomains")]
pub mod DeleteDomains;
#[cfg(feature = "DeleteGroup")]
pub mod DeleteGroup;
#[cfg(feature = "DeleteHost")]
pub mod DeleteHost;
#[cfg(feature = "DownloadTaskReport")]
pub mod DownloadTaskReport;
#[cfg(feature = "ExecuteGenerateReport")]
pub mod ExecuteGenerateReport;
#[cfg(feature = "ListBusinessRisks")]
pub mod ListBusinessRisks;
#[cfg(feature = "ListDomains")]
pub mod ListDomains;
#[cfg(feature = "ListGroups")]
pub mod ListGroups;
#[cfg(feature = "ListHostResults")]
pub mod ListHostResults;
#[cfg(feature = "ListHosts")]
pub mod ListHosts;
#[cfg(feature = "ListPortResults")]
pub mod ListPortResults;
#[cfg(feature = "ListTaskHistories")]
pub mod ListTaskHistories;
#[cfg(feature = "ShowDomainSettings")]
pub mod ShowDomainSettings;
#[cfg(feature = "ShowReportStatus")]
pub mod ShowReportStatus;
#[cfg(feature = "ShowResults")]
pub mod ShowResults;
#[cfg(feature = "ShowTasks")]
pub mod ShowTasks;
#[cfg(feature = "UpdateDomainSettings")]
pub mod UpdateDomainSettings;
#[cfg(feature = "UpdateFalsePositive")]
pub mod UpdateFalsePositive;
