#[cfg(feature = "AddFavorite")]
pub mod AddFavorite;
#[cfg(feature = "AddIndependentNode")]
pub mod AddIndependentNode;
#[cfg(feature = "ChangeClusterSubnet")]
pub mod ChangeClusterSubnet;
#[cfg(feature = "ChangeMode")]
pub mod ChangeMode;
#[cfg(feature = "ChangeSecurityGroup")]
pub mod ChangeSecurityGroup;
#[cfg(feature = "CreateAgency")]
pub mod CreateAgency;
#[cfg(feature = "CreateAiOps")]
pub mod CreateAiOps;
#[cfg(feature = "CreateAutoCreatePolicy")]
pub mod CreateAutoCreatePolicy;
#[cfg(feature = "CreateBindPublic")]
pub mod CreateBindPublic;
#[cfg(feature = "CreateCluster")]
pub mod CreateCluster;
#[cfg(feature = "CreateClustersTags")]
pub mod CreateClustersTags;
#[cfg(feature = "CreateCnf")]
pub mod CreateCnf;
#[cfg(feature = "CreateElbListener")]
pub mod CreateElbListener;
#[cfg(feature = "CreateLoadIkThesaurus")]
pub mod CreateLoadIkThesaurus;
#[cfg(feature = "CreateLogBackup")]
pub mod CreateLogBackup;
#[cfg(feature = "CreateSnapshot")]
pub mod CreateSnapshot;
#[cfg(feature = "DeleteAiOps")]
pub mod DeleteAiOps;
#[cfg(feature = "DeleteCerts")]
pub mod DeleteCerts;
#[cfg(feature = "DeleteCluster")]
pub mod DeleteCluster;
#[cfg(feature = "DeleteClustersTags")]
pub mod DeleteClustersTags;
#[cfg(feature = "DeleteConf")]
pub mod DeleteConf;
#[cfg(feature = "DeleteIkThesaurus")]
pub mod DeleteIkThesaurus;
#[cfg(feature = "DeleteLogstashConf")]
pub mod DeleteLogstashConf;
#[cfg(feature = "DeleteLogstashTemplate")]
pub mod DeleteLogstashTemplate;
#[cfg(feature = "DeleteSnapshot")]
pub mod DeleteSnapshot;
#[cfg(feature = "DeleteTemplate")]
pub mod DeleteTemplate;
#[cfg(feature = "DownloadCert")]
pub mod DownloadCert;
#[cfg(feature = "EnableOrDisableElb")]
pub mod EnableOrDisableElb;
#[cfg(feature = "ListActions")]
pub mod ListActions;
#[cfg(feature = "ListAiOps")]
pub mod ListAiOps;
#[cfg(feature = "ListCerts")]
pub mod ListCerts;
#[cfg(feature = "ListClustersDetails")]
pub mod ListClustersDetails;
#[cfg(feature = "ListClustersTags")]
pub mod ListClustersTags;
#[cfg(feature = "ListConfs")]
pub mod ListConfs;
#[cfg(feature = "ListElbCerts")]
pub mod ListElbCerts;
#[cfg(feature = "ListElbs")]
pub mod ListElbs;
#[cfg(feature = "ListFlavors")]
pub mod ListFlavors;
#[cfg(feature = "ListImages")]
pub mod ListImages;
#[cfg(feature = "ListLogsJob")]
pub mod ListLogsJob;
#[cfg(feature = "ListPipelines")]
pub mod ListPipelines;
#[cfg(feature = "ListRoutes")]
pub mod ListRoutes;
#[cfg(feature = "ListSmnTopics")]
pub mod ListSmnTopics;
#[cfg(feature = "ListSnapshots")]
pub mod ListSnapshots;
#[cfg(feature = "ListTemplates")]
pub mod ListTemplates;
#[cfg(feature = "ListYmls")]
pub mod ListYmls;
#[cfg(feature = "ListYmlsJob")]
pub mod ListYmlsJob;
#[cfg(feature = "RebootCluster")]
pub mod RebootCluster;
#[cfg(feature = "ResetPassword")]
pub mod ResetPassword;
#[cfg(feature = "RestartCluster")]
pub mod RestartCluster;
#[cfg(feature = "RestoreSnapshot")]
pub mod RestoreSnapshot;
#[cfg(feature = "RetryUpgradeTask")]
pub mod RetryUpgradeTask;
#[cfg(feature = "RollingRestart")]
pub mod RollingRestart;
#[cfg(feature = "ShowAutoCreatePolicy")]
pub mod ShowAutoCreatePolicy;
#[cfg(feature = "ShowCertsDetail")]
pub mod ShowCertsDetail;
#[cfg(feature = "ShowClusterDetail")]
pub mod ShowClusterDetail;
#[cfg(feature = "ShowClusterTag")]
pub mod ShowClusterTag;
#[cfg(feature = "ShowClusterVolumeUsage")]
pub mod ShowClusterVolumeUsage;
#[cfg(feature = "ShowDataStoreFlavorDetail")]
pub mod ShowDataStoreFlavorDetail;
#[cfg(feature = "ShowElbDetail")]
pub mod ShowElbDetail;
#[cfg(feature = "ShowFlavorDetail")]
pub mod ShowFlavorDetail;
#[cfg(feature = "ShowGetConfDetail")]
pub mod ShowGetConfDetail;
#[cfg(feature = "ShowGetLogSetting")]
pub mod ShowGetLogSetting;
#[cfg(feature = "ShowIkThesaurus")]
pub mod ShowIkThesaurus;
#[cfg(feature = "ShowLogBackup")]
pub mod ShowLogBackup;
#[cfg(feature = "ShowResizeFlavors")]
pub mod ShowResizeFlavors;
#[cfg(feature = "ShowVpcepConnection")]
pub mod ShowVpcepConnection;
#[cfg(feature = "StartAutoCreateSnapshots")]
pub mod StartAutoCreateSnapshots;
#[cfg(feature = "StartAutoSetting")]
pub mod StartAutoSetting;
#[cfg(feature = "StartConnectivityTest")]
pub mod StartConnectivityTest;
#[cfg(feature = "StartHotPipeline")]
pub mod StartHotPipeline;
#[cfg(feature = "StartKibanaPublic")]
pub mod StartKibanaPublic;
#[cfg(feature = "StartLogAutoBackupPolicy")]
pub mod StartLogAutoBackupPolicy;
#[cfg(feature = "StartLogs")]
pub mod StartLogs;
#[cfg(feature = "StartPipeline")]
pub mod StartPipeline;
#[cfg(feature = "StartPublicWhitelist")]
pub mod StartPublicWhitelist;
#[cfg(feature = "StartTargetClusterConnectivityTest")]
pub mod StartTargetClusterConnectivityTest;
#[cfg(feature = "StartVpecp")]
pub mod StartVpecp;
#[cfg(feature = "StopAutoCreateSnapshots")]
pub mod StopAutoCreateSnapshots;
#[cfg(feature = "StopHotPipeline")]
pub mod StopHotPipeline;
#[cfg(feature = "StopLogAutoBackupPolicy")]
pub mod StopLogAutoBackupPolicy;
#[cfg(feature = "StopLogs")]
pub mod StopLogs;
#[cfg(feature = "StopPipeline")]
pub mod StopPipeline;
#[cfg(feature = "StopPublicKibanaWhitelist")]
pub mod StopPublicKibanaWhitelist;
#[cfg(feature = "StopPublicWhitelist")]
pub mod StopPublicWhitelist;
#[cfg(feature = "StopSnapshot")]
pub mod StopSnapshot;
#[cfg(feature = "StopVpecp")]
pub mod StopVpecp;
#[cfg(feature = "UpdateAlterKibana")]
pub mod UpdateAlterKibana;
#[cfg(feature = "UpdateAzByInstanceType")]
pub mod UpdateAzByInstanceType;
#[cfg(feature = "UpdateBatchClustersTags")]
pub mod UpdateBatchClustersTags;
#[cfg(feature = "UpdateCloseKibana")]
pub mod UpdateCloseKibana;
#[cfg(feature = "UpdateClusterName")]
pub mod UpdateClusterName;
#[cfg(feature = "UpdateCnf")]
pub mod UpdateCnf;
#[cfg(feature = "UpdateEsListener")]
pub mod UpdateEsListener;
#[cfg(feature = "UpdateExtendCluster")]
pub mod UpdateExtendCluster;
#[cfg(feature = "UpdateExtendInstanceStorage")]
pub mod UpdateExtendInstanceStorage;
#[cfg(feature = "UpdateFlavor")]
pub mod UpdateFlavor;
#[cfg(feature = "UpdateFlavorByType")]
pub mod UpdateFlavorByType;
#[cfg(feature = "UpdateInstance")]
pub mod UpdateInstance;
#[cfg(feature = "UpdateLogSetting")]
pub mod UpdateLogSetting;
#[cfg(feature = "UpdateOndemandClusterToPeriod")]
pub mod UpdateOndemandClusterToPeriod;
