#[cfg(feature = "AddTagToAsset")]
pub mod AddTagToAsset;
#[cfg(feature = "AddWorkSpaceUsers")]
pub mod AddWorkSpaceUsers;
#[cfg(feature = "AssociateClassificationToEntity")]
pub mod AssociateClassificationToEntity;
#[cfg(feature = "AssociateSecurityLevelToEntitie")]
pub mod AssociateSecurityLevelToEntitie;
#[cfg(feature = "AuthorizeActionApiToInstance")]
pub mod AuthorizeActionApiToInstance;
#[cfg(feature = "AuthorizeApiToInstance")]
pub mod AuthorizeApiToInstance;
#[cfg(feature = "BatchApproveApply")]
pub mod BatchApproveApply;
#[cfg(feature = "BatchAssociateClassificationToEntities")]
pub mod BatchAssociateClassificationToEntities;
#[cfg(feature = "BatchAssociateSecurityLevelToEntities")]
pub mod BatchAssociateSecurityLevelToEntities;
#[cfg(feature = "BatchDeleteSecurityDataClassificationRule")]
pub mod BatchDeleteSecurityDataClassificationRule;
#[cfg(feature = "BatchDeleteSecurityPermissionSetMembers")]
pub mod BatchDeleteSecurityPermissionSetMembers;
#[cfg(feature = "BatchDeleteSecurityPermissionSetPermissions")]
pub mod BatchDeleteSecurityPermissionSetPermissions;
#[cfg(feature = "BatchDeleteTemplates")]
pub mod BatchDeleteTemplates;
#[cfg(feature = "BatchOffline")]
pub mod BatchOffline;
#[cfg(feature = "BatchPublish")]
pub mod BatchPublish;
#[cfg(feature = "BatchSyncMetadata")]
pub mod BatchSyncMetadata;
#[cfg(feature = "ChangeCatalog")]
pub mod ChangeCatalog;
#[cfg(feature = "ChangeResource")]
pub mod ChangeResource;
#[cfg(feature = "ChangeSubjects")]
pub mod ChangeSubjects;
#[cfg(feature = "CheckDimensionStatus")]
pub mod CheckDimensionStatus;
#[cfg(feature = "CheckFactLogicTableStatus")]
pub mod CheckFactLogicTableStatus;
#[cfg(feature = "ConfirmApprovals")]
pub mod ConfirmApprovals;
#[cfg(feature = "ConfirmMessage")]
pub mod ConfirmMessage;
#[cfg(feature = "CountAllModels")]
pub mod CountAllModels;
#[cfg(feature = "CountOverviews")]
pub mod CountOverviews;
#[cfg(feature = "CountStandards")]
pub mod CountStandards;
#[cfg(feature = "CountTableModels")]
pub mod CountTableModels;
#[cfg(feature = "CreateApi")]
pub mod CreateApi;
#[cfg(feature = "CreateApp")]
pub mod CreateApp;
#[cfg(feature = "CreateApprover")]
pub mod CreateApprover;
#[cfg(feature = "CreateBizMetric")]
pub mod CreateBizMetric;
#[cfg(feature = "CreateCatalog")]
pub mod CreateCatalog;
#[cfg(feature = "CreateCodeTable")]
pub mod CreateCodeTable;
#[cfg(feature = "CreateConnections")]
pub mod CreateConnections;
#[cfg(feature = "CreateDirectory")]
pub mod CreateDirectory;
#[cfg(feature = "CreateFactorySupplementDataInstance")]
pub mod CreateFactorySupplementDataInstance;
#[cfg(feature = "CreateManagerWorkSpace")]
pub mod CreateManagerWorkSpace;
#[cfg(feature = "CreateOrUpdateAsset")]
pub mod CreateOrUpdateAsset;
#[cfg(feature = "CreateSecurityDataClassificationRule")]
pub mod CreateSecurityDataClassificationRule;
#[cfg(feature = "CreateSecurityPermissionSet")]
pub mod CreateSecurityPermissionSet;
#[cfg(feature = "CreateSecurityPermissionSetMember")]
pub mod CreateSecurityPermissionSetMember;
#[cfg(feature = "CreateSecurityPermissionSetPermission")]
pub mod CreateSecurityPermissionSetPermission;
#[cfg(feature = "CreateServiceCatalog")]
pub mod CreateServiceCatalog;
#[cfg(feature = "CreateStandard")]
pub mod CreateStandard;
#[cfg(feature = "CreateStandardTemplate")]
pub mod CreateStandardTemplate;
#[cfg(feature = "CreateSubject")]
pub mod CreateSubject;
#[cfg(feature = "CreateSubjectNew")]
pub mod CreateSubjectNew;
#[cfg(feature = "CreateTableModel")]
pub mod CreateTableModel;
#[cfg(feature = "CreateTask")]
pub mod CreateTask;
#[cfg(feature = "CreateTemplate")]
pub mod CreateTemplate;
#[cfg(feature = "CreateWorkspace")]
pub mod CreateWorkspace;
#[cfg(feature = "DebugApi")]
pub mod DebugApi;
#[cfg(feature = "DebugDataconnection")]
pub mod DebugDataconnection;
#[cfg(feature = "DeleteApi")]
pub mod DeleteApi;
#[cfg(feature = "DeleteApp")]
pub mod DeleteApp;
#[cfg(feature = "DeleteApprover")]
pub mod DeleteApprover;
#[cfg(feature = "DeleteAsset")]
pub mod DeleteAsset;
#[cfg(feature = "DeleteBizMetric")]
pub mod DeleteBizMetric;
#[cfg(feature = "DeleteCatalog")]
pub mod DeleteCatalog;
#[cfg(feature = "DeleteClassificationFromEntities")]
pub mod DeleteClassificationFromEntities;
#[cfg(feature = "DeleteCodeTable")]
pub mod DeleteCodeTable;
#[cfg(feature = "DeleteDataconnection")]
pub mod DeleteDataconnection;
#[cfg(feature = "DeleteDirectory")]
pub mod DeleteDirectory;
#[cfg(feature = "DeleteSecurityDataClassificationRule")]
pub mod DeleteSecurityDataClassificationRule;
#[cfg(feature = "DeleteSecurityLevelFromEntity")]
pub mod DeleteSecurityLevelFromEntity;
#[cfg(feature = "DeleteSecurityPermissionSet")]
pub mod DeleteSecurityPermissionSet;
#[cfg(feature = "DeleteServiceCatalog")]
pub mod DeleteServiceCatalog;
#[cfg(feature = "DeleteStandard")]
pub mod DeleteStandard;
#[cfg(feature = "DeleteStandardTemplate")]
pub mod DeleteStandardTemplate;
#[cfg(feature = "DeleteSubject")]
pub mod DeleteSubject;
#[cfg(feature = "DeleteSubjectNew")]
pub mod DeleteSubjectNew;
#[cfg(feature = "DeleteTableModel")]
pub mod DeleteTableModel;
#[cfg(feature = "DeleteTaskInfo")]
pub mod DeleteTaskInfo;
#[cfg(feature = "DeleteWorkspaces")]
pub mod DeleteWorkspaces;
#[cfg(feature = "DeleteWorkspaceusers")]
pub mod DeleteWorkspaceusers;
#[cfg(feature = "ExecuteApiToInstance")]
pub mod ExecuteApiToInstance;
#[cfg(feature = "ExecuteTaskAction")]
pub mod ExecuteTaskAction;
#[cfg(feature = "ImportCatalogs")]
pub mod ImportCatalogs;
#[cfg(feature = "ImportLineage")]
pub mod ImportLineage;
#[cfg(feature = "ImportModels")]
pub mod ImportModels;
#[cfg(feature = "ImportResult")]
pub mod ImportResult;
#[cfg(feature = "InitializeStandardTemplate")]
pub mod InitializeStandardTemplate;
#[cfg(feature = "ListAggregationLogicTables")]
pub mod ListAggregationLogicTables;
#[cfg(feature = "ListAllCatalogList")]
pub mod ListAllCatalogList;
#[cfg(feature = "ListAllStandards")]
pub mod ListAllStandards;
#[cfg(feature = "ListAllTables")]
pub mod ListAllTables;
#[cfg(feature = "ListApiCatalogList")]
pub mod ListApiCatalogList;
#[cfg(feature = "ListApicGroups")]
pub mod ListApicGroups;
#[cfg(feature = "ListApicInstances")]
pub mod ListApicInstances;
#[cfg(feature = "ListApis")]
pub mod ListApis;
#[cfg(feature = "ListApisTop")]
pub mod ListApisTop;
#[cfg(feature = "ListApiTopN")]
pub mod ListApiTopN;
#[cfg(feature = "ListApply")]
pub mod ListApply;
#[cfg(feature = "ListApprovers")]
pub mod ListApprovers;
#[cfg(feature = "ListApps")]
pub mod ListApps;
#[cfg(feature = "ListAppsTop")]
pub mod ListAppsTop;
#[cfg(feature = "ListBizMetricDimensions")]
pub mod ListBizMetricDimensions;
#[cfg(feature = "ListBizMetricOwners")]
pub mod ListBizMetricOwners;
#[cfg(feature = "ListBizMetrics")]
pub mod ListBizMetrics;
#[cfg(feature = "ListBusiness")]
pub mod ListBusiness;
