#[cfg(feature = "AcceptSecurityApplication")]
pub mod AcceptSecurityApplication;
#[cfg(feature = "AddDesignEntityTags")]
pub mod AddDesignEntityTags;
#[cfg(feature = "AddTagToAsset")]
pub mod AddTagToAsset;
#[cfg(feature = "AddWorkSpaceUsers")]
pub mod AddWorkSpaceUsers;
#[cfg(feature = "AssociateClassificationToEntity")]
pub mod AssociateClassificationToEntity;
#[cfg(feature = "AssociateSecurityLevelToEntitie")]
pub mod AssociateSecurityLevelToEntitie;
#[cfg(feature = "AuthorizeActionApiToInstance")]
pub mod AuthorizeActionApiToInstance;
#[cfg(feature = "AuthorizeApiToInstance")]
pub mod AuthorizeApiToInstance;
#[cfg(feature = "BatchApproveApply")]
pub mod BatchApproveApply;
#[cfg(feature = "BatchAssociateClassificationToEntities")]
pub mod BatchAssociateClassificationToEntities;
#[cfg(feature = "BatchAssociateSecurityLevelToEntities")]
pub mod BatchAssociateSecurityLevelToEntities;
#[cfg(feature = "BatchDeleteSecurityDataClassificationRule")]
pub mod BatchDeleteSecurityDataClassificationRule;
#[cfg(feature = "BatchDeleteSecurityDynamicMaskingPolicies")]
pub mod BatchDeleteSecurityDynamicMaskingPolicies;
#[cfg(feature = "BatchDeleteSecurityPermissionSetMembers")]
pub mod BatchDeleteSecurityPermissionSetMembers;
#[cfg(feature = "BatchDeleteSecurityPermissionSetPermissions")]
pub mod BatchDeleteSecurityPermissionSetPermissions;
#[cfg(feature = "BatchDeleteSecurityResourcePermissionPolicies")]
pub mod BatchDeleteSecurityResourcePermissionPolicies;
#[cfg(feature = "BatchDeleteSecuritySecrecyLevels")]
pub mod BatchDeleteSecuritySecrecyLevels;
#[cfg(feature = "BatchDeleteTemplates")]
pub mod BatchDeleteTemplates;
#[cfg(feature = "BatchOffline")]
pub mod BatchOffline;
#[cfg(feature = "BatchPublish")]
pub mod BatchPublish;
#[cfg(feature = "BatchSyncMetadata")]
pub mod BatchSyncMetadata;
#[cfg(feature = "BatchTag")]
pub mod BatchTag;
#[cfg(feature = "BatchUpdateSecurityDlfDataWareHouses")]
pub mod BatchUpdateSecurityDlfDataWareHouses;
#[cfg(feature = "CancelFactoryPackages")]
pub mod CancelFactoryPackages;
#[cfg(feature = "ChangeCatalog")]
pub mod ChangeCatalog;
#[cfg(feature = "ChangeResource")]
pub mod ChangeResource;
#[cfg(feature = "ChangeSubjects")]
pub mod ChangeSubjects;
#[cfg(feature = "CheckDimensionStatus")]
pub mod CheckDimensionStatus;
#[cfg(feature = "CheckFactLogicTableStatus")]
pub mod CheckFactLogicTableStatus;
#[cfg(feature = "CheckSecurityDataClassificationCombineRule")]
pub mod CheckSecurityDataClassificationCombineRule;
#[cfg(feature = "ConfirmApprovals")]
pub mod ConfirmApprovals;
#[cfg(feature = "ConfirmMessage")]
pub mod ConfirmMessage;
#[cfg(feature = "CountAllModels")]
pub mod CountAllModels;
#[cfg(feature = "CountOverviews")]
pub mod CountOverviews;
#[cfg(feature = "CountStandards")]
pub mod CountStandards;
#[cfg(feature = "CountTableModels")]
pub mod CountTableModels;
#[cfg(feature = "CreateApi")]
pub mod CreateApi;
#[cfg(feature = "CreateApp")]
pub mod CreateApp;
#[cfg(feature = "CreateApprover")]
pub mod CreateApprover;
#[cfg(feature = "CreateBizMetric")]
pub mod CreateBizMetric;
#[cfg(feature = "CreateCatalog")]
pub mod CreateCatalog;
#[cfg(feature = "CreateCodeTable")]
pub mod CreateCodeTable;
#[cfg(feature = "CreateConnections")]
pub mod CreateConnections;
#[cfg(feature = "CreateDesignAggregationLogicTable")]
pub mod CreateDesignAggregationLogicTable;
#[cfg(feature = "CreateDesignAtomicIndex")]
pub mod CreateDesignAtomicIndex;
#[cfg(feature = "CreateDirectory")]
pub mod CreateDirectory;
#[cfg(feature = "CreateFactorySupplementDataInstance")]
pub mod CreateFactorySupplementDataInstance;
#[cfg(feature = "CreateLineageInfo")]
pub mod CreateLineageInfo;
#[cfg(feature = "CreateManagerWorkSpace")]
pub mod CreateManagerWorkSpace;
#[cfg(feature = "CreateOrUpdateAsset")]
pub mod CreateOrUpdateAsset;
#[cfg(feature = "CreateOrUpdateEntities")]
pub mod CreateOrUpdateEntities;
#[cfg(feature = "CreateSecurityAssignedQueue")]
pub mod CreateSecurityAssignedQueue;
#[cfg(feature = "CreateSecurityDataClassificationCombineRule")]
pub mod CreateSecurityDataClassificationCombineRule;
#[cfg(feature = "CreateSecurityDataClassificationRule")]
pub mod CreateSecurityDataClassificationRule;
#[cfg(feature = "CreateSecurityDataClassificationRuleGroup")]
pub mod CreateSecurityDataClassificationRuleGroup;
#[cfg(feature = "CreateSecurityDynamicMaskingPolicy")]
pub mod CreateSecurityDynamicMaskingPolicy;
#[cfg(feature = "CreateSecurityPermissionSet")]
pub mod CreateSecurityPermissionSet;
#[cfg(feature = "CreateSecurityPermissionSetMember")]
pub mod CreateSecurityPermissionSetMember;
#[cfg(feature = "CreateSecurityPermissionSetPermission")]
pub mod CreateSecurityPermissionSetPermission;
#[cfg(feature = "CreateSecurityResourcePermissionPolicy")]
pub mod CreateSecurityResourcePermissionPolicy;
#[cfg(feature = "CreateSecuritySecrecyLevel")]
pub mod CreateSecuritySecrecyLevel;
#[cfg(feature = "CreateServiceCatalog")]
pub mod CreateServiceCatalog;
#[cfg(feature = "CreateStandard")]
pub mod CreateStandard;
#[cfg(feature = "CreateStandardTemplate")]
pub mod CreateStandardTemplate;
#[cfg(feature = "CreateSubject")]
pub mod CreateSubject;
#[cfg(feature = "CreateSubjectNew")]
pub mod CreateSubjectNew;
#[cfg(feature = "CreateTableModel")]
pub mod CreateTableModel;
#[cfg(feature = "CreateTask")]
pub mod CreateTask;
#[cfg(feature = "CreateTemplate")]
pub mod CreateTemplate;
#[cfg(feature = "CreateWorkspace")]
pub mod CreateWorkspace;
#[cfg(feature = "DebugApi")]
pub mod DebugApi;
#[cfg(feature = "DebugDataconnection")]
pub mod DebugDataconnection;
#[cfg(feature = "DebugSecurityDlfDataWareHouses")]
pub mod DebugSecurityDlfDataWareHouses;
#[cfg(feature = "DeclineSecurityApplication")]
pub mod DeclineSecurityApplication;
#[cfg(feature = "DeleteApi")]
pub mod DeleteApi;
#[cfg(feature = "DeleteApp")]
pub mod DeleteApp;
#[cfg(feature = "DeleteApprover")]
pub mod DeleteApprover;
#[cfg(feature = "DeleteAsset")]
pub mod DeleteAsset;
#[cfg(feature = "DeleteBizMetric")]
pub mod DeleteBizMetric;
#[cfg(feature = "DeleteCatalog")]
pub mod DeleteCatalog;
#[cfg(feature = "DeleteClassificationFromEntities")]
pub mod DeleteClassificationFromEntities;
#[cfg(feature = "DeleteCodeTable")]
pub mod DeleteCodeTable;
#[cfg(feature = "DeleteDataconnection")]
pub mod DeleteDataconnection;
#[cfg(feature = "DeleteDesignAggregationLogicTable")]
pub mod DeleteDesignAggregationLogicTable;
#[cfg(feature = "DeleteDesignAtomicIndex")]
pub mod DeleteDesignAtomicIndex;
#[cfg(feature = "DeleteDesignLatestApproval")]
pub mod DeleteDesignLatestApproval;
#[cfg(feature = "DeleteDirectory")]
pub mod DeleteDirectory;
#[cfg(feature = "DeleteSecurityAssignedQueue")]
pub mod DeleteSecurityAssignedQueue;
#[cfg(feature = "DeleteSecurityDataClassificationRule")]
pub mod DeleteSecurityDataClassificationRule;
#[cfg(feature = "DeleteSecurityDataClassificationRuleGroup")]
pub mod DeleteSecurityDataClassificationRuleGroup;
#[cfg(feature = "DeleteSecurityLevelFromEntity")]
pub mod DeleteSecurityLevelFromEntity;
#[cfg(feature = "DeleteSecurityPermissionSet")]
pub mod DeleteSecurityPermissionSet;
#[cfg(feature = "DeleteSecuritySecrecyLevel")]
pub mod DeleteSecuritySecrecyLevel;
#[cfg(feature = "DeleteServiceCatalog")]
pub mod DeleteServiceCatalog;
#[cfg(feature = "DeleteStandard")]
pub mod DeleteStandard;
#[cfg(feature = "DeleteStandardTemplate")]
pub mod DeleteStandardTemplate;
#[cfg(feature = "DeleteSubject")]
pub mod DeleteSubject;
#[cfg(feature = "DeleteSubjectNew")]
pub mod DeleteSubjectNew;
#[cfg(feature = "DeleteTableModel")]
pub mod DeleteTableModel;
#[cfg(feature = "DeleteTaskInfo")]
pub mod DeleteTaskInfo;
