#[cfg(feature = "AddAppId")]
pub mod AddAppId;
#[cfg(feature = "AddCorp")]
pub mod AddCorp;
#[cfg(feature = "AddCorpAdmin")]
pub mod AddCorpAdmin;
#[cfg(feature = "AddDepartment")]
pub mod AddDepartment;
#[cfg(feature = "AddDevice")]
pub mod AddDevice;
#[cfg(feature = "AddMaterial")]
pub mod AddMaterial;
#[cfg(feature = "AddProgram")]
pub mod AddProgram;
#[cfg(feature = "AddPublication")]
pub mod AddPublication;
#[cfg(feature = "AddResource")]
pub mod AddResource;
#[cfg(feature = "AddToPersonalSpace")]
pub mod AddToPersonalSpace;
#[cfg(feature = "AddUser")]
pub mod AddUser;
#[cfg(feature = "AllowAudienceJoin")]
pub mod AllowAudienceJoin;
#[cfg(feature = "AllowClientRecord")]
pub mod AllowClientRecord;
#[cfg(feature = "AllowGuestUnmute")]
pub mod AllowGuestUnmute;
#[cfg(feature = "AllowWaitingParticipant")]
pub mod AllowWaitingParticipant;
#[cfg(feature = "AssociateVmr")]
pub mod AssociateVmr;
#[cfg(feature = "BatchDeleteCorpAdmins")]
pub mod BatchDeleteCorpAdmins;
#[cfg(feature = "BatchDeleteDevices")]
pub mod BatchDeleteDevices;
#[cfg(feature = "BatchDeleteMaterials")]
pub mod BatchDeleteMaterials;
#[cfg(feature = "BatchDeletePrograms")]
pub mod BatchDeletePrograms;
#[cfg(feature = "BatchDeletePublications")]
pub mod BatchDeletePublications;
#[cfg(feature = "BatchDeleteUsers")]
pub mod BatchDeleteUsers;
#[cfg(feature = "BatchHand")]
pub mod BatchHand;
#[cfg(feature = "BatchMoveToWaitingRoom")]
pub mod BatchMoveToWaitingRoom;
#[cfg(feature = "BatchSearchAppId")]
pub mod BatchSearchAppId;
#[cfg(feature = "BatchShowUserDetails")]
pub mod BatchShowUserDetails;
#[cfg(feature = "BatchUpdateDevicesStatus")]
pub mod BatchUpdateDevicesStatus;
#[cfg(feature = "BatchUpdateUserStatus")]
pub mod BatchUpdateUserStatus;
#[cfg(feature = "BroadcastParticipant")]
pub mod BroadcastParticipant;
#[cfg(feature = "CancelBroadcast")]
pub mod CancelBroadcast;
#[cfg(feature = "CancelMeeting")]
pub mod CancelMeeting;
#[cfg(feature = "CancelRecurringMeeting")]
pub mod CancelRecurringMeeting;
#[cfg(feature = "CancelRecurringSubMeeting")]
pub mod CancelRecurringSubMeeting;
#[cfg(feature = "CheckCallNumberInConf")]
pub mod CheckCallNumberInConf;
#[cfg(feature = "CheckSlideVerifyCode")]
pub mod CheckSlideVerifyCode;
#[cfg(feature = "CheckToken")]
pub mod CheckToken;
#[cfg(feature = "CheckVeriCodeForUpdateUserInfo")]
pub mod CheckVeriCodeForUpdateUserInfo;
#[cfg(feature = "CheckVerifyCode")]
pub mod CheckVerifyCode;
#[cfg(feature = "CreateAnonymousAuthRandom")]
pub mod CreateAnonymousAuthRandom;
#[cfg(feature = "CreateAppIdToken")]
pub mod CreateAppIdToken;
#[cfg(feature = "CreateAuthRandom")]
pub mod CreateAuthRandom;
#[cfg(feature = "CreateConfToken")]
pub mod CreateConfToken;
#[cfg(feature = "CreateMeeting")]
pub mod CreateMeeting;
#[cfg(feature = "CreatePortalRefNonce")]
pub mod CreatePortalRefNonce;
#[cfg(feature = "CreateProxyToken")]
pub mod CreateProxyToken;
#[cfg(feature = "CreateRecurringMeeting")]
pub mod CreateRecurringMeeting;
#[cfg(feature = "CreateToken")]
pub mod CreateToken;
#[cfg(feature = "CreateVisionActiveCode")]
pub mod CreateVisionActiveCode;
#[cfg(feature = "CreateWebinar")]
pub mod CreateWebinar;
#[cfg(feature = "CreateWebSocketToken")]
pub mod CreateWebSocketToken;
#[cfg(feature = "DeleteAppId")]
pub mod DeleteAppId;
#[cfg(feature = "DeleteCorp")]
pub mod DeleteCorp;
#[cfg(feature = "DeleteCorpVmr")]
pub mod DeleteCorpVmr;
#[cfg(feature = "DeleteDepartment")]
pub mod DeleteDepartment;
#[cfg(feature = "DeleteLayout")]
pub mod DeleteLayout;
#[cfg(feature = "DeleteRecordings")]
pub mod DeleteRecordings;
#[cfg(feature = "DeleteResource")]
pub mod DeleteResource;
#[cfg(feature = "DeleteToken")]
pub mod DeleteToken;
#[cfg(feature = "DeleteVisionActiveCode")]
pub mod DeleteVisionActiveCode;
#[cfg(feature = "DeleteWebHookConfig")]
pub mod DeleteWebHookConfig;
#[cfg(feature = "DeleteWebinar")]
pub mod DeleteWebinar;
#[cfg(feature = "DisassociateVmr")]
pub mod DisassociateVmr;
#[cfg(feature = "Hand")]
pub mod Hand;
#[cfg(feature = "HangUp")]
pub mod HangUp;
#[cfg(feature = "InviteOperateVideo")]
pub mod InviteOperateVideo;
#[cfg(feature = "InviteParticipant")]
pub mod InviteParticipant;
#[cfg(feature = "InviteShare")]
pub mod InviteShare;
#[cfg(feature = "InviteUser")]
pub mod InviteUser;
#[cfg(feature = "InviteWithPwd")]
pub mod InviteWithPwd;
#[cfg(feature = "ListHistoryWebinars")]
pub mod ListHistoryWebinars;
#[cfg(feature = "ListNetworkQuality")]
pub mod ListNetworkQuality;
#[cfg(feature = "ListOngoingWebinars")]
pub mod ListOngoingWebinars;
#[cfg(feature = "ListOnlineConfAttendee")]
pub mod ListOnlineConfAttendee;
#[cfg(feature = "ListUpComingWebinars")]
pub mod ListUpComingWebinars;
#[cfg(feature = "Live")]
pub mod Live;
#[cfg(feature = "LockMeeting")]
pub mod LockMeeting;
#[cfg(feature = "LockView")]
pub mod LockView;
#[cfg(feature = "MoveToWaitingRoom")]
pub mod MoveToWaitingRoom;
#[cfg(feature = "MuteMeeting")]
pub mod MuteMeeting;
#[cfg(feature = "MuteParticipant")]
pub mod MuteParticipant;
#[cfg(feature = "PauseConference")]
pub mod PauseConference;
#[cfg(feature = "ProlongMeeting")]
pub mod ProlongMeeting;
#[cfg(feature = "Record")]
pub mod Record;
#[cfg(feature = "RenameParticipant")]
pub mod RenameParticipant;
#[cfg(feature = "ResetActivecode")]
pub mod ResetActivecode;
#[cfg(feature = "ResetAppKey")]
pub mod ResetAppKey;
#[cfg(feature = "ResetPwd")]
pub mod ResetPwd;
#[cfg(feature = "ResetPwdByAdmin")]
pub mod ResetPwdByAdmin;
#[cfg(feature = "ResetVisionActiveCode")]
pub mod ResetVisionActiveCode;
#[cfg(feature = "ResumeSimultaneousInterpretation")]
pub mod ResumeSimultaneousInterpretation;
#[cfg(feature = "RollcallParticipant")]
pub mod RollcallParticipant;
#[cfg(feature = "SaveLayout")]
pub mod SaveLayout;
#[cfg(feature = "SearchAttendanceRecordsOfHisMeeting")]
pub mod SearchAttendanceRecordsOfHisMeeting;
#[cfg(feature = "SearchCorp")]
pub mod SearchCorp;
#[cfg(feature = "SearchCorpAdmins")]
pub mod SearchCorpAdmins;
#[cfg(feature = "SearchCorpDir")]
pub mod SearchCorpDir;
#[cfg(feature = "SearchCorpExternalDir")]
pub mod SearchCorpExternalDir;
#[cfg(feature = "SearchCorpResources")]
pub mod SearchCorpResources;
#[cfg(feature = "SearchCorpVmr")]
pub mod SearchCorpVmr;
