[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddSubsetsToGateway = []
AddUserToApp = []
AddingBackendInstancesV2 = []
AssociateAppsForAppQuota = []
AssociateCertificateV2 = []
AssociateDomainV2 = []
AssociateRequestThrottlingPolicyV2 = []
AssociateSignatureKeyV2 = []
AttachApiToPlugin = []
AttachPluginToApi = []
BatchAddDeviceToGroup = []
BatchAssociateCertsV2 = []
BatchAssociateDomainsV2 = []
BatchDeleteAclV2 = []
BatchDeleteApiAclBindingV2 = []
BatchDeleteMqsInstanceTopic = []
BatchDeleteRules = []
BatchDeleteThrottlingPolicyV2 = []
BatchDisableMembers = []
BatchDisassociateCertsV2 = []
BatchDisassociateDomainsV2 = []
BatchDisassociateThrottlingPolicyV2 = []
BatchEnableMembers = []
BatchFreezeDevices = []
BatchPublishOrOfflineApiV2 = []
BatchStartOrStopTasks = []
CancelingAuthorizationV2 = []
ChangeApiVersionV2 = []
CheckApiGroupsV2 = []
CheckApisV2 = []
CheckAssetJobStatus = []
CheckAuthUsersOfApp = []
CheckCanAuthUsersOfApp = []
CheckDictionary = []
CheckLivedataApisV2 = []
CheckRomaAppDetails = []
CheckRomaAppSecret = []
CheckRomaInstanceListV2 = []
CheckVersion = []
CountTasks = []
CreateAclStrategyV2 = []
CreateApiAclBindingV2 = []
CreateApiGroupV2 = []
CreateApiV2 = []
CreateAppCodeAutoV2 = []
CreateAppCodeV2 = []
CreateAppConfigV2 = []
CreateAppQuota = []
CreateAuthorizingAppsV2 = []
CreateCertificateV2 = []
CreateCommand = []
CreateCommonTask = []
CreateCustomAuthorizerV2 = []
CreateDatasourceInfo = []
CreateDestination = []
CreateDevice = []
CreateDeviceGroup = []
CreateDictionary = []
CreateDispatches = []
CreateEnvironmentV2 = []
CreateEnvironmentVariableV2 = []
CreateFeatureV2 = []
CreateLiveDataApiScriptV2 = []
CreateLiveDataApiV2 = []
CreateMemberGroup = []
CreateMqsInstanceTopic = []
CreateMultiTaskMappings = []
CreateMultiTasks = []
CreateNotification = []
CreateOrDeletePublishRecordForApiV2 = []
CreatePlugin = []
CreateProduct = []
CreateProductTemplate = []
CreateProductTopic = []
CreateProjectVpcChannel = []
CreateProjectVpcChannelSyncs = []
CreateProperty = []
CreateRequestProperty = []
CreateRequestThrottlingPolicyV2 = []
CreateResponseProperty = []
CreateRomaApp = []
CreateRule = []
CreateService = []
CreateSignatureKeyV2 = []
CreateSource = []
CreateSpecialThrottlingConfigurationV2 = []
CreateVpcChannelV2 = []
DebugApiV2 = []
DebugLiveDataApiV2 = []
DebugRule = []
DeleteAclV2 = []
DeleteApiAclBindingV2 = []
DeleteApiByVersionIdV2 = []
DeleteApiGroupV2 = []
DeleteApiV2 = []
DeleteAppAcl = []
DeleteAppCodeV2 = []
DeleteAppConfigV2 = []
DeleteAppQuota = []
DeleteAsset = []
full = ["AddingBackendInstancesV2", "AddSubsetsToGateway", "AddUserToApp", "AssociateAppsForAppQuota", "AssociateCertificateV2", "AssociateDomainV2", "AssociateRequestThrottlingPolicyV2", "AssociateSignatureKeyV2", "AttachApiToPlugin", "AttachPluginToApi", "BatchAddDeviceToGroup", "BatchAssociateCertsV2", "BatchAssociateDomainsV2", "BatchDeleteAclV2", "BatchDeleteApiAclBindingV2", "BatchDeleteMqsInstanceTopic", "BatchDeleteRules", "BatchDeleteThrottlingPolicyV2", "BatchDisableMembers", "BatchDisassociateCertsV2", "BatchDisassociateDomainsV2", "BatchDisassociateThrottlingPolicyV2", "BatchEnableMembers", "BatchFreezeDevices", "BatchPublishOrOfflineApiV2", "BatchStartOrStopTasks", "CancelingAuthorizationV2", "ChangeApiVersionV2", "CheckApiGroupsV2", "CheckApisV2", "CheckAssetJobStatus", "CheckAuthUsersOfApp", "CheckCanAuthUsersOfApp", "CheckDictionary", "CheckLivedataApisV2", "CheckRomaAppDetails", "CheckRomaAppSecret", "CheckRomaInstanceListV2", "CheckVersion", "CountTasks", "CreateAclStrategyV2", "CreateApiAclBindingV2", "CreateApiGroupV2", "CreateApiV2", "CreateAppCodeAutoV2", "CreateAppCodeV2", "CreateAppConfigV2", "CreateAppQuota", "CreateAuthorizingAppsV2", "CreateCertificateV2", "CreateCommand", "CreateCommonTask", "CreateCustomAuthorizerV2", "CreateDatasourceInfo", "CreateDestination", "CreateDevice", "CreateDeviceGroup", "CreateDictionary", "CreateDispatches", "CreateEnvironmentV2", "CreateEnvironmentVariableV2", "CreateFeatureV2", "CreateLiveDataApiScriptV2", "CreateLiveDataApiV2", "CreateMemberGroup", "CreateMqsInstanceTopic", "CreateMultiTaskMappings", "CreateMultiTasks", "CreateNotification", "CreateOrDeletePublishRecordForApiV2", "CreatePlugin", "CreateProduct", "CreateProductTemplate", "CreateProductTopic", "CreateProjectVpcChannel", "CreateProjectVpcChannelSyncs", "CreateProperty", "CreateRequestProperty", "CreateRequestThrottlingPolicyV2", "CreateResponseProperty", "CreateRomaApp", "CreateRule", "CreateService", "CreateSignatureKeyV2", "CreateSource", "CreateSpecialThrottlingConfigurationV2", "CreateVpcChannelV2", "DebugApiV2", "DebugLiveDataApiV2", "DebugRule", "DeleteAclV2", "DeleteApiAclBindingV2", "DeleteApiByVersionIdV2", "DeleteApiGroupV2", "DeleteApiV2", "DeleteAppAcl", "DeleteAppCodeV2", "DeleteAppConfigV2", "DeleteAppQuota", "DeleteAsset"]

[lib]
name = "huawei_cloud_api_definitions_ROMA"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-ROMA"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "0.1.1"
