#[cfg(feature = "RecognizeAcceptanceBill")]
pub mod RecognizeAcceptanceBill;
#[cfg(feature = "RecognizeAutoClassification")]
pub mod RecognizeAutoClassification;
#[cfg(feature = "RecognizeBankcard")]
pub mod RecognizeBankcard;
#[cfg(feature = "RecognizeBankReceipt")]
pub mod RecognizeBankReceipt;
#[cfg(feature = "RecognizeBusinessCard")]
pub mod RecognizeBusinessCard;
#[cfg(feature = "RecognizeBusinessLicense")]
pub mod RecognizeBusinessLicense;
#[cfg(feature = "RecognizeColombiaIdCard")]
pub mod RecognizeColombiaIdCard;
#[cfg(feature = "RecognizeCustomTemplate")]
pub mod RecognizeCustomTemplate;
#[cfg(feature = "RecognizeDriverLicense")]
pub mod RecognizeDriverLicense;
#[cfg(feature = "RecognizeFinancialStatement")]
pub mod RecognizeFinancialStatement;
#[cfg(feature = "RecognizeFlightItinerary")]
pub mod RecognizeFlightItinerary;
#[cfg(feature = "RecognizeGeneralTable")]
pub mod RecognizeGeneralTable;
#[cfg(feature = "RecognizeGeneralText")]
pub mod RecognizeGeneralText;
#[cfg(feature = "RecognizeHandwriting")]
pub mod RecognizeHandwriting;
#[cfg(feature = "RecognizeHouseholdRegister")]
pub mod RecognizeHouseholdRegister;
#[cfg(feature = "RecognizeIdCard")]
pub mod RecognizeIdCard;
#[cfg(feature = "RecognizeInsurancePolicy")]
pub mod RecognizeInsurancePolicy;
#[cfg(feature = "RecognizeInvoiceVerification")]
pub mod RecognizeInvoiceVerification;
#[cfg(feature = "RecognizeLicensePlate")]
pub mod RecognizeLicensePlate;
#[cfg(feature = "RecognizeMvsInvoice")]
pub mod RecognizeMvsInvoice;
#[cfg(feature = "RecognizePassport")]
pub mod RecognizePassport;
#[cfg(feature = "RecognizeQualificationCertificate")]
pub mod RecognizeQualificationCertificate;
#[cfg(feature = "RecognizeQuotaInvoice")]
pub mod RecognizeQuotaInvoice;
#[cfg(feature = "RecognizeRealEstateCertificate")]
pub mod RecognizeRealEstateCertificate;
#[cfg(feature = "RecognizeSeal")]
pub mod RecognizeSeal;
#[cfg(feature = "RecognizeSmartDocumentRecognizer")]
pub mod RecognizeSmartDocumentRecognizer;
#[cfg(feature = "RecognizeTaxiInvoice")]
pub mod RecognizeTaxiInvoice;
#[cfg(feature = "RecognizeThailandIdcard")]
pub mod RecognizeThailandIdcard;
#[cfg(feature = "RecognizeThailandLicensePlate")]
pub mod RecognizeThailandLicensePlate;
#[cfg(feature = "RecognizeTollInvoice")]
pub mod RecognizeTollInvoice;
#[cfg(feature = "RecognizeTrainTicket")]
pub mod RecognizeTrainTicket;
#[cfg(feature = "RecognizeTransportationLicense")]
pub mod RecognizeTransportationLicense;
#[cfg(feature = "RecognizeVatInvoice")]
pub mod RecognizeVatInvoice;
#[cfg(feature = "RecognizeVehicleCertificate")]
pub mod RecognizeVehicleCertificate;
#[cfg(feature = "RecognizeVehicleLicense")]
pub mod RecognizeVehicleLicense;
#[cfg(feature = "RecognizeVin")]
pub mod RecognizeVin;
#[cfg(feature = "RecognizeWaybillElectronic")]
pub mod RecognizeWaybillElectronic;
#[cfg(feature = "RecognizeWebImage")]
pub mod RecognizeWebImage;
