#[cfg(feature = "AcceptDsmOperateLog")]
pub mod AcceptDsmOperateLog;
#[cfg(feature = "AddAccessSystem")]
pub mod AddAccessSystem;
#[cfg(feature = "AddAttributeOld")]
pub mod AddAttributeOld;
#[cfg(feature = "AddBackupServer")]
pub mod AddBackupServer;
#[cfg(feature = "AddServiceView")]
pub mod AddServiceView;
#[cfg(feature = "AuditCIInstance")]
pub mod AuditCIInstance;
#[cfg(feature = "BatchCreateCIInstance")]
pub mod BatchCreateCIInstance;
#[cfg(feature = "BatchCreateCIRelationInstance")]
pub mod BatchCreateCIRelationInstance;
#[cfg(feature = "BatchDeleteCIInstance")]
pub mod BatchDeleteCIInstance;
#[cfg(feature = "BatchDeleteCIRelationInstance")]
pub mod BatchDeleteCIRelationInstance;
#[cfg(feature = "BatchDeleteDevice")]
pub mod BatchDeleteDevice;
#[cfg(feature = "BatchPatchCIInstance")]
pub mod BatchPatchCIInstance;
#[cfg(feature = "BatchUpdateCIRelationInstance")]
pub mod BatchUpdateCIRelationInstance;
#[cfg(feature = "CheckCloudServiceOperate")]
pub mod CheckCloudServiceOperate;
#[cfg(feature = "CheckCts")]
pub mod CheckCts;
#[cfg(feature = "CountCIInstanceJob")]
pub mod CountCIInstanceJob;
#[cfg(feature = "CountCIInstances")]
pub mod CountCIInstances;
#[cfg(feature = "CountCSMCIInstances")]
pub mod CountCSMCIInstances;
#[cfg(feature = "CountCSMCIRelationInstances")]
pub mod CountCSMCIRelationInstances;
#[cfg(feature = "CountInstances")]
pub mod CountInstances;
#[cfg(feature = "CreateAlarmRule")]
pub mod CreateAlarmRule;
#[cfg(feature = "CreateAutoOpsJob")]
pub mod CreateAutoOpsJob;
#[cfg(feature = "CreateCICategory")]
pub mod CreateCICategory;
#[cfg(feature = "CreateCIInstance")]
pub mod CreateCIInstance;
#[cfg(feature = "CreateCIRelation")]
pub mod CreateCIRelation;
#[cfg(feature = "CreateCloudService")]
pub mod CreateCloudService;
#[cfg(feature = "CreateCloudServiceV3")]
pub mod CreateCloudServiceV3;
#[cfg(feature = "CreateDeployNode")]
pub mod CreateDeployNode;
#[cfg(feature = "CreateDevice")]
pub mod CreateDevice;
#[cfg(feature = "CreateIdP")]
pub mod CreateIdP;
#[cfg(feature = "CreateJob")]
pub mod CreateJob;
#[cfg(feature = "CreateJobV2")]
pub mod CreateJobV2;
#[cfg(feature = "CreateJobV3")]
pub mod CreateJobV3;
#[cfg(feature = "CreateMetricData")]
pub mod CreateMetricData;
#[cfg(feature = "CreateOperationV3")]
pub mod CreateOperationV3;
#[cfg(feature = "CreateRemoteInspectionTasks")]
pub mod CreateRemoteInspectionTasks;
#[cfg(feature = "CreatetCIInstanceTableAttrs")]
pub mod CreatetCIInstanceTableAttrs;
#[cfg(feature = "CreateToken")]
pub mod CreateToken;
#[cfg(feature = "DeleteAlarmRule")]
pub mod DeleteAlarmRule;
#[cfg(feature = "DeleteAppGroup")]
pub mod DeleteAppGroup;
#[cfg(feature = "DeleteAttribute")]
pub mod DeleteAttribute;
#[cfg(feature = "DeleteAutoOpsJob")]
pub mod DeleteAutoOpsJob;
#[cfg(feature = "DeleteCICategory")]
pub mod DeleteCICategory;
#[cfg(feature = "DeleteCIClass")]
pub mod DeleteCIClass;
#[cfg(feature = "DeleteCIInstance")]
pub mod DeleteCIInstance;
#[cfg(feature = "DeleteCIInstanceTableAttrs")]
pub mod DeleteCIInstanceTableAttrs;
#[cfg(feature = "DeleteCIRelation")]
pub mod DeleteCIRelation;
#[cfg(feature = "DeleteCIRelationByCondition")]
pub mod DeleteCIRelationByCondition;
#[cfg(feature = "DeleteCloudService")]
pub mod DeleteCloudService;
#[cfg(feature = "DeleteComponentsInCloudServiceV3")]
pub mod DeleteComponentsInCloudServiceV3;
#[cfg(feature = "DeleteDefinition")]
pub mod DeleteDefinition;
#[cfg(feature = "DeleteDeployNode")]
pub mod DeleteDeployNode;
#[cfg(feature = "DeleteIdP")]
pub mod DeleteIdP;
#[cfg(feature = "DeleteJob")]
pub mod DeleteJob;
#[cfg(feature = "DeleteNodeInfo")]
pub mod DeleteNodeInfo;
#[cfg(feature = "DeleteOperationV3")]
pub mod DeleteOperationV3;
#[cfg(feature = "DeleteReason")]
pub mod DeleteReason;
#[cfg(feature = "DeleteRegionInfo")]
pub mod DeleteRegionInfo;
#[cfg(feature = "DeleteServiceInCloudServiceV3")]
pub mod DeleteServiceInCloudServiceV3;
#[cfg(feature = "DownloadJobHistoryAgentFilesV3")]
pub mod DownloadJobHistoryAgentFilesV3;
#[cfg(feature = "DownloadJobHistoryFiles")]
pub mod DownloadJobHistoryFiles;
#[cfg(feature = "ExecuteEsOperation")]
pub mod ExecuteEsOperation;
#[cfg(feature = "ImportExtendPackage")]
pub mod ImportExtendPackage;
#[cfg(feature = "InstallAgentsV3")]
pub mod InstallAgentsV3;
#[cfg(feature = "ListAlarmRules")]
pub mod ListAlarmRules;
#[cfg(feature = "ListAllEnums")]
pub mod ListAllEnums;
#[cfg(feature = "ListAllObjectTypes")]
pub mod ListAllObjectTypes;
#[cfg(feature = "ListAllTags")]
pub mod ListAllTags;
#[cfg(feature = "ListAvailableZones")]
pub mod ListAvailableZones;
#[cfg(feature = "ListCICategory")]
pub mod ListCICategory;
#[cfg(feature = "ListCIClass")]
pub mod ListCIClass;
#[cfg(feature = "ListCIRelationInstances")]
pub mod ListCIRelationInstances;
#[cfg(feature = "ListCIView")]
pub mod ListCIView;
#[cfg(feature = "ListCloudChanges")]
pub mod ListCloudChanges;
#[cfg(feature = "ListCloudInfras")]
pub mod ListCloudInfras;
#[cfg(feature = "ListCloudService")]
pub mod ListCloudService;
#[cfg(feature = "ListCloudServiceInfoV3")]
pub mod ListCloudServiceInfoV3;
#[cfg(feature = "ListCloudServiceNodes")]
pub mod ListCloudServiceNodes;
#[cfg(feature = "ListCloudServices")]
pub mod ListCloudServices;
#[cfg(feature = "ListCSMCIInstances")]
pub mod ListCSMCIInstances;
#[cfg(feature = "ListCSMCIRelationInstances")]
pub mod ListCSMCIRelationInstances;
#[cfg(feature = "ListCustomChanges")]
pub mod ListCustomChanges;
#[cfg(feature = "ListDeployNode")]
pub mod ListDeployNode;
#[cfg(feature = "ListDeviceChanges")]
pub mod ListDeviceChanges;
#[cfg(feature = "ListDevices")]
pub mod ListDevices;
#[cfg(feature = "ListEndPoints")]
pub mod ListEndPoints;
#[cfg(feature = "ListExternalNetworks")]
pub mod ListExternalNetworks;
#[cfg(feature = "ListFusionCloudProviders")]
pub mod ListFusionCloudProviders;
#[cfg(feature = "ListHistoryAlarms")]
pub mod ListHistoryAlarms;
#[cfg(feature = "ListJobHistories")]
pub mod ListJobHistories;
#[cfg(feature = "ListJobs")]
pub mod ListJobs;
#[cfg(feature = "ListMicroService")]
pub mod ListMicroService;
#[cfg(feature = "ListOperations")]
pub mod ListOperations;
#[cfg(feature = "ListPeriodSubTasks")]
pub mod ListPeriodSubTasks;
#[cfg(feature = "ListPeriodTasks")]
pub mod ListPeriodTasks;
#[cfg(feature = "ListProductJoinSystem")]
pub mod ListProductJoinSystem;
#[cfg(feature = "ListPublicIps")]
pub mod ListPublicIps;
#[cfg(feature = "ListRegionDevicesInstallMaterials")]
pub mod ListRegionDevicesInstallMaterials;
#[cfg(feature = "ListRegionInstallMaterials")]
pub mod ListRegionInstallMaterials;
#[cfg(feature = "ListRegions")]
pub mod ListRegions;
