#[cfg(feature = "BatchSwitchMonitor")]
pub mod BatchSwitchMonitor;
#[cfg(feature = "CreateApplication")]
pub mod CreateApplication;
#[cfg(feature = "CreateDataSource")]
pub mod CreateDataSource;
#[cfg(feature = "CreateDataSyncTask")]
pub mod CreateDataSyncTask;
#[cfg(feature = "CreateDbConnectionPool")]
pub mod CreateDbConnectionPool;
#[cfg(feature = "CreateInstance")]
pub mod CreateInstance;
#[cfg(feature = "CreateMonitor")]
pub mod CreateMonitor;
#[cfg(feature = "CreateNamespace")]
pub mod CreateNamespace;
#[cfg(feature = "DeleteApplications")]
pub mod DeleteApplications;
#[cfg(feature = "DeleteAppSwitchJopNote")]
pub mod DeleteAppSwitchJopNote;
#[cfg(feature = "DeleteDataSource")]
pub mod DeleteDataSource;
#[cfg(feature = "DeleteDataSyncTask")]
pub mod DeleteDataSyncTask;
#[cfg(feature = "DeleteGlobalConf")]
pub mod DeleteGlobalConf;
#[cfg(feature = "DeleteInstance")]
pub mod DeleteInstance;
#[cfg(feature = "DeleteModule")]
pub mod DeleteModule;
#[cfg(feature = "DeleteSecret")]
pub mod DeleteSecret;
#[cfg(feature = "DeployInstance")]
pub mod DeployInstance;
#[cfg(feature = "DownloadEtcdCert")]
pub mod DownloadEtcdCert;
#[cfg(feature = "EnableActivateModule")]
pub mod EnableActivateModule;
#[cfg(feature = "ListApplications")]
pub mod ListApplications;
#[cfg(feature = "ListBatchSwitchDetail")]
pub mod ListBatchSwitchDetail;
#[cfg(feature = "ListInstances")]
pub mod ListInstances;
#[cfg(feature = "ListMonitors")]
pub mod ListMonitors;
#[cfg(feature = "ListSwitchJobs")]
pub mod ListSwitchJobs;
#[cfg(feature = "ResetDcMonitor")]
pub mod ResetDcMonitor;
#[cfg(feature = "SetGlobalConf")]
pub mod SetGlobalConf;
#[cfg(feature = "SetMonitorGlobalConfig")]
pub mod SetMonitorGlobalConfig;
#[cfg(feature = "SetSecret")]
pub mod SetSecret;
#[cfg(feature = "ShowDataSource")]
pub mod ShowDataSource;
#[cfg(feature = "ShowDataSources")]
pub mod ShowDataSources;
#[cfg(feature = "ShowDataSyncTask")]
pub mod ShowDataSyncTask;
#[cfg(feature = "ShowDataSyncTasks")]
pub mod ShowDataSyncTasks;
#[cfg(feature = "ShowDbConnectionPool")]
pub mod ShowDbConnectionPool;
#[cfg(feature = "ShowDcMonitor")]
pub mod ShowDcMonitor;
#[cfg(feature = "ShowGlobalConf")]
pub mod ShowGlobalConf;
#[cfg(feature = "ShowInstance")]
pub mod ShowInstance;
#[cfg(feature = "ShowModule")]
pub mod ShowModule;
#[cfg(feature = "ShowMonitor")]
pub mod ShowMonitor;
#[cfg(feature = "ShowMonitorGlobalConfig")]
pub mod ShowMonitorGlobalConfig;
#[cfg(feature = "ShowNameSpaceList")]
pub mod ShowNameSpaceList;
#[cfg(feature = "ShowNamespacesById")]
pub mod ShowNamespacesById;
#[cfg(feature = "ShowOverallMonitors")]
pub mod ShowOverallMonitors;
#[cfg(feature = "ShowSecret")]
pub mod ShowSecret;
#[cfg(feature = "ShowStatisticalData")]
pub mod ShowStatisticalData;
#[cfg(feature = "SwitchMonitor")]
pub mod SwitchMonitor;
#[cfg(feature = "SwitchoverDataSyncTask")]
pub mod SwitchoverDataSyncTask;
#[cfg(feature = "UpdateDataSource")]
pub mod UpdateDataSource;
#[cfg(feature = "UpdateDbConnectionPool")]
pub mod UpdateDbConnectionPool;
#[cfg(feature = "UpdateGlobalConf")]
pub mod UpdateGlobalConf;
#[cfg(feature = "UpdateInstance")]
pub mod UpdateInstance;
#[cfg(feature = "UpdateModule")]
pub mod UpdateModule;
#[cfg(feature = "UpdateMonitor")]
pub mod UpdateMonitor;
#[cfg(feature = "UpdateNameSpace")]
pub mod UpdateNameSpace;
