[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddNics = []
AssociateSubnet = []
AttachVipBandwidth = []
BatchRebootInstance = []
BatchStartInstance = []
BatchStopInstance = []
ChangeOs = []
CreateDeployment = []
CreateFirewall = []
CreateImage = []
CreateInstance = []
CreateKeypair = []
CreatePort = []
CreatePublicIp = []
CreateRoutes = []
CreateRoutetable = []
CreateSecurityGroup = []
CreateSecurityGroupRule = []
CreateSubnet = []
CreateVpc = []
DeleteBandwidth = []
DeleteDeployment = []
DeleteEdgeCloud = []
DeleteFirewall = []
DeleteImage = []
DeleteInstances = []
DeleteKeypair = []
DeleteNics = []
DeletePort = []
DeletePublicIp = []
DeleteRoutes = []
DeleteRoutetable = []
DeleteSecurityGroup = []
DeleteSecurityGroupRule = []
DeleteSubnet = []
DeleteVpc = []
DetachVipBandwidth = []
DisassociateSubnet = []
ExecuteDeployment = []
ExpandEdgecloud = []
ListBandwidthTypes = []
ListBandwidths = []
ListCloudImages = []
ListDeployments = []
ListEdgeCloud = []
ListFirewalls = []
ListFlavors = []
ListImages = []
ListInstances = []
ListKeypairs = []
ListPorts = []
ListPublicIps = []
ListQuota = []
ListRelatedRoutetables = []
ListRoutes = []
ListRoutetables = []
ListSecurityGroupRules = []
ListSecurityGroups = []
ListSites = []
ListSubnets = []
ListVolume = []
ListVpcs = []
RebuildImage = []
RegisterImage = []
ShowBandwidth = []
ShowEdgeCloud = []
ShowFirewall = []
ShowImage = []
ShowInstance = []
ShowKeypair = []
ShowPort = []
ShowPublicIp = []
ShowRoutetable = []
ShowSecurityGroup = []
ShowSecurityGroupRule = []
ShowSubnet = []
ShowVolume = []
ShowVolumeTypes = []
ShowVpc = []
UpdateBandwidth = []
UpdateFirewall = []
UpdateFirewallRule = []
UpdateInstance = []
UpdatePort = []
UpdatePublicIp = []
UpdateRoutes = []
UpdateRoutetable = []
UpdateSubnet = []
UpdateVpc = []
full = ["AddNics", "AssociateSubnet", "AttachVipBandwidth", "BatchRebootInstance", "BatchStartInstance", "BatchStopInstance", "ChangeOs", "CreateDeployment", "CreateFirewall", "CreateImage", "CreateInstance", "CreateKeypair", "CreatePort", "CreatePublicIp", "CreateRoutes", "CreateRoutetable", "CreateSecurityGroup", "CreateSecurityGroupRule", "CreateSubnet", "CreateVpc", "DeleteBandwidth", "DeleteDeployment", "DeleteEdgeCloud", "DeleteFirewall", "DeleteImage", "DeleteInstances", "DeleteKeypair", "DeleteNics", "DeletePort", "DeletePublicIp", "DeleteRoutes", "DeleteRoutetable", "DeleteSecurityGroup", "DeleteSecurityGroupRule", "DeleteSubnet", "DeleteVpc", "DetachVipBandwidth", "DisassociateSubnet", "ExecuteDeployment", "ExpandEdgecloud", "ListBandwidths", "ListBandwidthTypes", "ListCloudImages", "ListDeployments", "ListEdgeCloud", "ListFirewalls", "ListFlavors", "ListImages", "ListInstances", "ListKeypairs", "ListPorts", "ListPublicIps", "ListQuota", "ListRelatedRoutetables", "ListRoutes", "ListRoutetables", "ListSecurityGroupRules", "ListSecurityGroups", "ListSites", "ListSubnets", "ListVolume", "ListVpcs", "RebuildImage", "RegisterImage", "ShowBandwidth", "ShowEdgeCloud", "ShowFirewall", "ShowImage", "ShowInstance", "ShowKeypair", "ShowPort", "ShowPublicIp", "ShowRoutetable", "ShowSecurityGroup", "ShowSecurityGroupRule", "ShowSubnet", "ShowVolume", "ShowVolumeTypes", "ShowVpc", "UpdateBandwidth", "UpdateFirewall", "UpdateFirewallRule", "UpdateInstance", "UpdatePort", "UpdatePublicIp", "UpdateRoutes", "UpdateRoutetable", "UpdateSubnet", "UpdateVpc"]

[lib]
name = "huawei_cloud_api_definitions_IEC"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-IEC"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
