#[cfg(feature = "CollectTranscriberJob")]
pub mod CollectTranscriberJob;
#[cfg(feature = "CreateVocabulary")]
pub mod CreateVocabulary;
#[cfg(feature = "DeleteVocabulary")]
pub mod DeleteVocabulary;
#[cfg(feature = "PushTranscriberJobs")]
pub mod PushTranscriberJobs;
#[cfg(feature = "RecognizeFlashAsr")]
pub mod RecognizeFlashAsr;
#[cfg(feature = "RecognizeShortAudio")]
pub mod RecognizeShortAudio;
#[cfg(feature = "RunTts")]
pub mod RunTts;
#[cfg(feature = "ShowVocabularies")]
pub mod ShowVocabularies;
#[cfg(feature = "ShowVocabulary")]
pub mod ShowVocabulary;
#[cfg(feature = "UpdateVocabulary")]
pub mod UpdateVocabulary;
