#[cfg(feature = "BindVport")]
pub mod BindVport;
#[cfg(feature = "CreateConnection")]
pub mod CreateConnection;
#[cfg(feature = "CreateInstance")]
pub mod CreateInstance;
#[cfg(feature = "DeleteConnection")]
pub mod DeleteConnection;
#[cfg(feature = "DeleteInstance")]
pub mod DeleteInstance;
#[cfg(feature = "ListAvailabilityZones")]
pub mod ListAvailabilityZones;
#[cfg(feature = "ListConnections")]
pub mod ListConnections;
#[cfg(feature = "ListConnectionsAllInstances")]
pub mod ListConnectionsAllInstances;
#[cfg(feature = "ListFlavors")]
pub mod ListFlavors;
#[cfg(feature = "ListInstances")]
pub mod ListInstances;
#[cfg(feature = "ListQuotas")]
pub mod ListQuotas;
#[cfg(feature = "ListResourceJobs")]
pub mod ListResourceJobs;
#[cfg(feature = "ShowConnection")]
pub mod ShowConnection;
#[cfg(feature = "ShowInstance")]
pub mod ShowInstance;
#[cfg(feature = "UnbindVport")]
pub mod UnbindVport;
#[cfg(feature = "UpdateConnection")]
pub mod UpdateConnection;
#[cfg(feature = "UpdateInstance")]
pub mod UpdateInstance;
