#[cfg(feature = "CheckRepositoryDuplicateName")]
pub mod CheckRepositoryDuplicateName;
#[cfg(feature = "ConfirmDeploymentJob")]
pub mod ConfirmDeploymentJob;
#[cfg(feature = "CreateDeploymentJobs")]
pub mod CreateDeploymentJobs;
#[cfg(feature = "CreateTemplateViewHistories")]
pub mod CreateTemplateViewHistories;
#[cfg(feature = "DeleteApplicationV4")]
pub mod DeleteApplicationV4;
#[cfg(feature = "DownloadApplicationCode")]
pub mod DownloadApplicationCode;
#[cfg(feature = "ListApplicationsV6")]
pub mod ListApplicationsV6;
#[cfg(feature = "ListPipelineTemplates")]
pub mod ListPipelineTemplates;
#[cfg(feature = "ListProjectsV4")]
pub mod ListProjectsV4;
#[cfg(feature = "ListTemplates")]
pub mod ListTemplates;
#[cfg(feature = "ListTemplateViewHistories")]
pub mod ListTemplateViewHistories;
#[cfg(feature = "RunCodehubTemplateJob")]
pub mod RunCodehubTemplateJob;
#[cfg(feature = "RunDevstarTemplateJob")]
pub mod RunDevstarTemplateJob;
#[cfg(feature = "ShowApplicationDependentResources")]
pub mod ShowApplicationDependentResources;
#[cfg(feature = "ShowApplicationReleaseRepositories")]
pub mod ShowApplicationReleaseRepositories;
#[cfg(feature = "ShowApplicationResDeleteStatus")]
pub mod ShowApplicationResDeleteStatus;
#[cfg(feature = "ShowApplicationV3")]
pub mod ShowApplicationV3;
#[cfg(feature = "ShowDeploymentJobs")]
pub mod ShowDeploymentJobs;
#[cfg(feature = "ShowJobDetail")]
pub mod ShowJobDetail;
#[cfg(feature = "ShowPipelineLastStatusV2")]
pub mod ShowPipelineLastStatusV2;
#[cfg(feature = "ShowRepositoryByCloudIde")]
pub mod ShowRepositoryByCloudIde;
#[cfg(feature = "ShowRepositoryStatisticalDataV2")]
pub mod ShowRepositoryStatisticalDataV2;
#[cfg(feature = "ShowTemplateFile")]
pub mod ShowTemplateFile;
#[cfg(feature = "ShowTemplateV3")]
pub mod ShowTemplateV3;
#[cfg(feature = "StartPipeline")]
pub mod StartPipeline;
#[cfg(feature = "UpdateApplication")]
pub mod UpdateApplication;
