[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AcceptResourceShareInvitation = []
AssociateResourceShare = []
AssociateResourceSharePermission = []
BatchCreateResourceShareTags = []
BatchDeleteResourceShareTags = []
CreateResourceShare = []
DeleteResourceShare = []
DisableOrganizationShare = []
DisassociateResourceShare = []
DisassociateResourceSharePermission = []
EnableOrganizationShare = []
ListPermissions = []
ListQuota = []
ListResourceSharePermissions = []
ListResourceShareTags = []
ListResourceSharesByTags = []
ListResourceTypes = []
RejectResourceShareInvitation = []
SearchResourceShareAssociations = []
SearchResourceShareCountByTags = []
SearchResourceShareInvitation = []
SearchResourceShares = []
SearchSharedPrincipals = []
SearchSharedResources = []
ShowOrganizationShare = []
ShowPermission = []
UpdateResourceShare = []
full = ["AcceptResourceShareInvitation", "AssociateResourceShare", "AssociateResourceSharePermission", "BatchCreateResourceShareTags", "BatchDeleteResourceShareTags", "CreateResourceShare", "DeleteResourceShare", "DisableOrganizationShare", "DisassociateResourceShare", "DisassociateResourceSharePermission", "EnableOrganizationShare", "ListPermissions", "ListQuota", "ListResourceSharePermissions", "ListResourceSharesByTags", "ListResourceShareTags", "ListResourceTypes", "RejectResourceShareInvitation", "SearchResourceShareAssociations", "SearchResourceShareCountByTags", "SearchResourceShareInvitation", "SearchResourceShares", "SearchSharedPrincipals", "SearchSharedResources", "ShowOrganizationShare", "ShowPermission", "UpdateResourceShare"]

[lib]
name = "huawei_cloud_api_definitions_RAM"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-RAM"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
