#[cfg(feature = "AttachManagedPolicyToPermissionSet")]
pub mod AttachManagedPolicyToPermissionSet;
#[cfg(feature = "AttachManagedRoleToPermissionSet")]
pub mod AttachManagedRoleToPermissionSet;
#[cfg(feature = "CreateAccountAssignment")]
pub mod CreateAccountAssignment;
#[cfg(feature = "CreateAlias")]
pub mod CreateAlias;
#[cfg(feature = "CreateApplicationAssignment")]
pub mod CreateApplicationAssignment;
#[cfg(feature = "CreateApplicationInstance")]
pub mod CreateApplicationInstance;
#[cfg(feature = "CreateApplicationInstanceCertificate")]
pub mod CreateApplicationInstanceCertificate;
#[cfg(feature = "CreateInstanceAccessControlAttributeConfiguration")]
pub mod CreateInstanceAccessControlAttributeConfiguration;
#[cfg(feature = "CreatePermissionSet")]
pub mod CreatePermissionSet;
#[cfg(feature = "CreateTagResource")]
pub mod CreateTagResource;
#[cfg(feature = "DeleteAccountAssignment")]
pub mod DeleteAccountAssignment;
#[cfg(feature = "DeleteApplicationAssignment")]
pub mod DeleteApplicationAssignment;
#[cfg(feature = "DeleteApplicationInstance")]
pub mod DeleteApplicationInstance;
#[cfg(feature = "DeleteApplicationInstanceCertificate")]
pub mod DeleteApplicationInstanceCertificate;
#[cfg(feature = "DeleteCustomPolicyFromPermissionSet")]
pub mod DeleteCustomPolicyFromPermissionSet;
#[cfg(feature = "DeleteCustomRoleFromPermissionSet")]
pub mod DeleteCustomRoleFromPermissionSet;
#[cfg(feature = "DeleteIdentityCenter")]
pub mod DeleteIdentityCenter;
#[cfg(feature = "DeleteInstanceAccessControlAttributeConfiguration")]
pub mod DeleteInstanceAccessControlAttributeConfiguration;
#[cfg(feature = "DeletePermissionSet")]
pub mod DeletePermissionSet;
#[cfg(feature = "DeleteProfile")]
pub mod DeleteProfile;
#[cfg(feature = "DeleteTagResource")]
pub mod DeleteTagResource;
#[cfg(feature = "DescribeAccountAssignmentCreationStatus")]
pub mod DescribeAccountAssignmentCreationStatus;
#[cfg(feature = "DescribeAccountAssignmentDeletionStatus")]
pub mod DescribeAccountAssignmentDeletionStatus;
#[cfg(feature = "DescribeApplication")]
pub mod DescribeApplication;
#[cfg(feature = "DescribeApplicationProvider")]
pub mod DescribeApplicationProvider;
#[cfg(feature = "DescribeInstanceAccessControlAttributeConfiguration")]
pub mod DescribeInstanceAccessControlAttributeConfiguration;
#[cfg(feature = "DescribePermissionSet")]
pub mod DescribePermissionSet;
#[cfg(feature = "DescribePermissionSetProvisioningStatus")]
pub mod DescribePermissionSetProvisioningStatus;
#[cfg(feature = "DescribeRegisteredRegions")]
pub mod DescribeRegisteredRegions;
#[cfg(feature = "DetachManagedPolicyFromPermissionSet")]
pub mod DetachManagedPolicyFromPermissionSet;
#[cfg(feature = "DetachManagedRoleFromPermissionSet")]
pub mod DetachManagedRoleFromPermissionSet;
#[cfg(feature = "DisassociateProfile")]
pub mod DisassociateProfile;
#[cfg(feature = "GetApplicationAssignmentConfiguration")]
pub mod GetApplicationAssignmentConfiguration;
#[cfg(feature = "GetApplicationInstance")]
pub mod GetApplicationInstance;
#[cfg(feature = "GetCustomPolicyForPermissionSet")]
pub mod GetCustomPolicyForPermissionSet;
#[cfg(feature = "GetCustomRoleForPermissionSet")]
pub mod GetCustomRoleForPermissionSet;
#[cfg(feature = "GetHaConfiguration")]
pub mod GetHaConfiguration;
#[cfg(feature = "GetIdentityCenterServiceStatus")]
pub mod GetIdentityCenterServiceStatus;
#[cfg(feature = "GetMfaDeviceManagementForIdentityStore")]
pub mod GetMfaDeviceManagementForIdentityStore;
#[cfg(feature = "GetPermissionSetSummary")]
pub mod GetPermissionSetSummary;
#[cfg(feature = "GetSsoConfiguration")]
pub mod GetSsoConfiguration;
#[cfg(feature = "ImportApplicationInstanceServiceProviderMetadata")]
pub mod ImportApplicationInstanceServiceProviderMetadata;
#[cfg(feature = "ListAccountAssignmentCreationStatus")]
pub mod ListAccountAssignmentCreationStatus;
#[cfg(feature = "ListAccountAssignmentDeletionStatus")]
pub mod ListAccountAssignmentDeletionStatus;
#[cfg(feature = "ListAccountAssignments")]
pub mod ListAccountAssignments;
#[cfg(feature = "ListAccountAssignmentsForPrincipal")]
pub mod ListAccountAssignmentsForPrincipal;
#[cfg(feature = "ListAccountsForProvisionedPermissionSet")]
pub mod ListAccountsForProvisionedPermissionSet;
#[cfg(feature = "ListApplicationAssignments")]
pub mod ListApplicationAssignments;
#[cfg(feature = "ListApplicationAssignmentsForPrincipal")]
pub mod ListApplicationAssignmentsForPrincipal;
#[cfg(feature = "ListApplicationInstanceCertificates")]
pub mod ListApplicationInstanceCertificates;
#[cfg(feature = "ListApplicationInstances")]
pub mod ListApplicationInstances;
#[cfg(feature = "ListApplicationProviders")]
pub mod ListApplicationProviders;
#[cfg(feature = "ListApplications")]
pub mod ListApplications;
#[cfg(feature = "ListApplicationTemplates")]
pub mod ListApplicationTemplates;
#[cfg(feature = "ListCatalogApplications")]
pub mod ListCatalogApplications;
#[cfg(feature = "ListIdentityStoreAssociation")]
pub mod ListIdentityStoreAssociation;
#[cfg(feature = "ListInstances")]
pub mod ListInstances;
#[cfg(feature = "ListManagedPoliciesInPermissionSet")]
pub mod ListManagedPoliciesInPermissionSet;
#[cfg(feature = "ListManagedRolesInPermissionSet")]
pub mod ListManagedRolesInPermissionSet;
#[cfg(feature = "ListPermissionSetProvisioningStatus")]
pub mod ListPermissionSetProvisioningStatus;
#[cfg(feature = "ListPermissionSets")]
pub mod ListPermissionSets;
#[cfg(feature = "ListPermissionSetsProvisionedToAccount")]
pub mod ListPermissionSetsProvisionedToAccount;
#[cfg(feature = "ListProfiles")]
pub mod ListProfiles;
#[cfg(feature = "ListTagResources")]
pub mod ListTagResources;
#[cfg(feature = "ProvisionPermissionSet")]
pub mod ProvisionPermissionSet;
#[cfg(feature = "PutCustomPolicyToPermissionSet")]
pub mod PutCustomPolicyToPermissionSet;
#[cfg(feature = "PutCustomRoleToPermissionSet")]
pub mod PutCustomRoleToPermissionSet;
#[cfg(feature = "PutMfaDeviceManagementForIdentityStore")]
pub mod PutMfaDeviceManagementForIdentityStore;
#[cfg(feature = "RegisterRegion")]
pub mod RegisterRegion;
#[cfg(feature = "StartIdentityCenter")]
pub mod StartIdentityCenter;
#[cfg(feature = "UpdateApplicationInstanceActiveCertificate")]
pub mod UpdateApplicationInstanceActiveCertificate;
#[cfg(feature = "UpdateApplicationInstanceDisplayData")]
pub mod UpdateApplicationInstanceDisplayData;
#[cfg(feature = "UpdateApplicationInstanceResponseConfiguration")]
pub mod UpdateApplicationInstanceResponseConfiguration;
#[cfg(feature = "UpdateApplicationInstanceResponseSchemaConfiguration")]
pub mod UpdateApplicationInstanceResponseSchemaConfiguration;
#[cfg(feature = "UpdateApplicationInstanceSecurityConfiguration")]
pub mod UpdateApplicationInstanceSecurityConfiguration;
#[cfg(feature = "UpdateApplicationInstanceServiceProviderConfiguration")]
pub mod UpdateApplicationInstanceServiceProviderConfiguration;
#[cfg(feature = "UpdateApplicationInstanceStatus")]
pub mod UpdateApplicationInstanceStatus;
#[cfg(feature = "UpdateHaConfiguration")]
pub mod UpdateHaConfiguration;
#[cfg(feature = "UpdateInstanceAccessControlAttributeConfiguration")]
pub mod UpdateInstanceAccessControlAttributeConfiguration;
#[cfg(feature = "UpdatePermissionSet")]
pub mod UpdatePermissionSet;
#[cfg(feature = "UpdateSsoConfiguration")]
pub mod UpdateSsoConfiguration;
