#[cfg(feature = "AttachManagedPolicyToPermissionSet")]
pub mod AttachManagedPolicyToPermissionSet;
#[cfg(feature = "AttachRoleToPermissionSet")]
pub mod AttachRoleToPermissionSet;
#[cfg(feature = "CreateAccountAssignment")]
pub mod CreateAccountAssignment;
#[cfg(feature = "CreateInstanceAccessControlAttributeConfiguration")]
pub mod CreateInstanceAccessControlAttributeConfiguration;
#[cfg(feature = "CreatePermissionSet")]
pub mod CreatePermissionSet;
#[cfg(feature = "CreateTagResource")]
pub mod CreateTagResource;
#[cfg(feature = "DeleteAccountAssignment")]
pub mod DeleteAccountAssignment;
#[cfg(feature = "DeleteCustomPolicyFromPermissionSet")]
pub mod DeleteCustomPolicyFromPermissionSet;
#[cfg(feature = "DeleteCustomRoleFromPermissionSet")]
pub mod DeleteCustomRoleFromPermissionSet;
#[cfg(feature = "DeleteInstanceAccessControlAttributeConfiguration")]
pub mod DeleteInstanceAccessControlAttributeConfiguration;
#[cfg(feature = "DeletePermissionSet")]
pub mod DeletePermissionSet;
#[cfg(feature = "DeleteTagResource")]
pub mod DeleteTagResource;
#[cfg(feature = "DescribeAccountAssignmentCreationStatus")]
pub mod DescribeAccountAssignmentCreationStatus;
#[cfg(feature = "DescribeAccountAssignmentDeletionStatus")]
pub mod DescribeAccountAssignmentDeletionStatus;
#[cfg(feature = "DescribeInstanceAccessControlAttributeConfiguration")]
pub mod DescribeInstanceAccessControlAttributeConfiguration;
#[cfg(feature = "DescribePermissionSet")]
pub mod DescribePermissionSet;
#[cfg(feature = "DescribePermissionSetProvisioningStatus")]
pub mod DescribePermissionSetProvisioningStatus;
#[cfg(feature = "DetachManagedPolicyFromPermissionSet")]
pub mod DetachManagedPolicyFromPermissionSet;
#[cfg(feature = "DetachManagedRoleFromPermissionSet")]
pub mod DetachManagedRoleFromPermissionSet;
#[cfg(feature = "ListAccountAssignmentCreationStatus")]
pub mod ListAccountAssignmentCreationStatus;
#[cfg(feature = "ListAccountAssignmentDeletionStatus")]
pub mod ListAccountAssignmentDeletionStatus;
#[cfg(feature = "ListAccountAssignments")]
pub mod ListAccountAssignments;
#[cfg(feature = "ListAccountsForProvisionedPermissionSet")]
pub mod ListAccountsForProvisionedPermissionSet;
#[cfg(feature = "ListInstances")]
pub mod ListInstances;
#[cfg(feature = "ListManagedPoliciesInPermissionSet")]
pub mod ListManagedPoliciesInPermissionSet;
#[cfg(feature = "ListManagedRolesInPermissionSet")]
pub mod ListManagedRolesInPermissionSet;
#[cfg(feature = "ListPermissionSetProvisioningStatus")]
pub mod ListPermissionSetProvisioningStatus;
#[cfg(feature = "ListPermissionSets")]
pub mod ListPermissionSets;
#[cfg(feature = "ListPermissionSetsProvisionedToAccount")]
pub mod ListPermissionSetsProvisionedToAccount;
#[cfg(feature = "ListTagResources")]
pub mod ListTagResources;
#[cfg(feature = "PutCustomPolicyToPermissionSet")]
pub mod PutCustomPolicyToPermissionSet;
#[cfg(feature = "PutCustomRoleToPermissionSet")]
pub mod PutCustomRoleToPermissionSet;
#[cfg(feature = "UpdateInstanceAccessControlAttributeConfiguration")]
pub mod UpdateInstanceAccessControlAttributeConfiguration;
#[cfg(feature = "UpdatePermissionSet")]
pub mod UpdatePermissionSet;
