#[cfg(feature = "BatchCreateIrackTags")]
pub mod BatchCreateIrackTags;
#[cfg(feature = "BatchCreateTags")]
pub mod BatchCreateTags;
#[cfg(feature = "BatchDeleteIrackTags")]
pub mod BatchDeleteIrackTags;
#[cfg(feature = "BatchDeleteTags")]
pub mod BatchDeleteTags;
#[cfg(feature = "ChangeInstancePassword")]
pub mod ChangeInstancePassword;
#[cfg(feature = "ChangeServerPowerState")]
pub mod ChangeServerPowerState;
#[cfg(feature = "CreateInstance")]
pub mod CreateInstance;
#[cfg(feature = "DeleteInstance")]
pub mod DeleteInstance;
#[cfg(feature = "DeleteInstances")]
pub mod DeleteInstances;
#[cfg(feature = "DownloadServerLogs")]
pub mod DownloadServerLogs;
#[cfg(feature = "ExportServerLogs")]
pub mod ExportServerLogs;
#[cfg(feature = "ListAlarms")]
pub mod ListAlarms;
#[cfg(feature = "ListEvents")]
pub mod ListEvents;
#[cfg(feature = "ListIDcs")]
pub mod ListIDcs;
#[cfg(feature = "ListInstances")]
pub mod ListInstances;
#[cfg(feature = "ListIRack")]
pub mod ListIRack;
#[cfg(feature = "ListServers")]
pub mod ListServers;
#[cfg(feature = "ModifyInstanceIp")]
pub mod ModifyInstanceIp;
#[cfg(feature = "ReinstallOs")]
pub mod ReinstallOs;
#[cfg(feature = "RunInstances")]
pub mod RunInstances;
#[cfg(feature = "ShowAlarmSummary")]
pub mod ShowAlarmSummary;
#[cfg(feature = "ShowAlarmTrend")]
pub mod ShowAlarmTrend;
#[cfg(feature = "ShowEvent")]
pub mod ShowEvent;
#[cfg(feature = "ShowInstanceStatus")]
pub mod ShowInstanceStatus;
#[cfg(feature = "ShowLogsExportStatus")]
pub mod ShowLogsExportStatus;
#[cfg(feature = "ShowRemoteConsole")]
pub mod ShowRemoteConsole;
#[cfg(feature = "ShowServer")]
pub mod ShowServer;
#[cfg(feature = "ShowServerFirmwareAttributes")]
pub mod ShowServerFirmwareAttributes;
#[cfg(feature = "ShowServerHardwareAttributes")]
pub mod ShowServerHardwareAttributes;
#[cfg(feature = "ShowServerStatus")]
pub mod ShowServerStatus;
#[cfg(feature = "UpdateIDcs")]
pub mod UpdateIDcs;
#[cfg(feature = "UpdateIRack")]
pub mod UpdateIRack;
