#[cfg(feature = "CompleteResourceTokenAuth")]
pub mod CompleteResourceTokenAuth;
#[cfg(feature = "CreateApiKeyCredentialProvider")]
pub mod CreateApiKeyCredentialProvider;
#[cfg(feature = "CreateOauth2CredentialProvider")]
pub mod CreateOauth2CredentialProvider;
#[cfg(feature = "CreateStsCredentialProvider")]
pub mod CreateStsCredentialProvider;
#[cfg(feature = "CreateWorkloadAccessToken")]
pub mod CreateWorkloadAccessToken;
#[cfg(feature = "CreateWorkloadAccessTokenForJwt")]
pub mod CreateWorkloadAccessTokenForJwt;
#[cfg(feature = "CreateWorkloadAccessTokenForUserId")]
pub mod CreateWorkloadAccessTokenForUserId;
#[cfg(feature = "CreateWorkloadIdentity")]
pub mod CreateWorkloadIdentity;
#[cfg(feature = "DeleteApiKeyCredentialProvider")]
pub mod DeleteApiKeyCredentialProvider;
#[cfg(feature = "DeleteOauth2CredentialProvider")]
pub mod DeleteOauth2CredentialProvider;
#[cfg(feature = "DeleteStsCredentialProvider")]
pub mod DeleteStsCredentialProvider;
#[cfg(feature = "DeleteWorkloadIdentity")]
pub mod DeleteWorkloadIdentity;
#[cfg(feature = "GetApiKeyCredentialProvider")]
pub mod GetApiKeyCredentialProvider;
#[cfg(feature = "GetOauth2CredentialProvider")]
pub mod GetOauth2CredentialProvider;
#[cfg(feature = "GetResourceApiKey")]
pub mod GetResourceApiKey;
#[cfg(feature = "GetResourceOauth2Token")]
pub mod GetResourceOauth2Token;
#[cfg(feature = "GetResourceStsToken")]
pub mod GetResourceStsToken;
#[cfg(feature = "GetStsCredentialProvider")]
pub mod GetStsCredentialProvider;
#[cfg(feature = "GetTokenVault")]
pub mod GetTokenVault;
#[cfg(feature = "GetWorkloadIdentity")]
pub mod GetWorkloadIdentity;
#[cfg(feature = "GetWorkloadIdentityAuthorizerConfiguration")]
pub mod GetWorkloadIdentityAuthorizerConfiguration;
#[cfg(feature = "ListApiKeyCredentialProviders")]
pub mod ListApiKeyCredentialProviders;
#[cfg(feature = "ListOauth2CredentialProviders")]
pub mod ListOauth2CredentialProviders;
#[cfg(feature = "ListStsCredentialProviders")]
pub mod ListStsCredentialProviders;
#[cfg(feature = "ListWorkloadIdentities")]
pub mod ListWorkloadIdentities;
#[cfg(feature = "Oauth2Authorize")]
pub mod Oauth2Authorize;
#[cfg(feature = "Oauth2Callback")]
pub mod Oauth2Callback;
#[cfg(feature = "UpdateApiKeyCredentialProvider")]
pub mod UpdateApiKeyCredentialProvider;
#[cfg(feature = "UpdateOauth2CredentialProvider")]
pub mod UpdateOauth2CredentialProvider;
#[cfg(feature = "UpdateStsCredentialProvider")]
pub mod UpdateStsCredentialProvider;
#[cfg(feature = "UpdateWorkloadIdentity")]
pub mod UpdateWorkloadIdentity;
