#[cfg(feature = "CollectHotQuestions")]
pub mod CollectHotQuestions;
#[cfg(feature = "CollectKeyWords")]
pub mod CollectKeyWords;
#[cfg(feature = "CollectReplyRates")]
pub mod CollectReplyRates;
#[cfg(feature = "CollectSessionStats")]
pub mod CollectSessionStats;
#[cfg(feature = "CreateSession")]
pub mod CreateSession;
#[cfg(feature = "DeleteSession")]
pub mod DeleteSession;
#[cfg(feature = "ExecuteComposeVideo")]
pub mod ExecuteComposeVideo;
#[cfg(feature = "ExecuteComposeVideoOndemand")]
pub mod ExecuteComposeVideoOndemand;
#[cfg(feature = "ExecuteCreateVideo")]
pub mod ExecuteCreateVideo;
#[cfg(feature = "ExecuteDeleteimageById")]
pub mod ExecuteDeleteimageById;
#[cfg(feature = "ExecuteDeleteVideoById")]
pub mod ExecuteDeleteVideoById;
#[cfg(feature = "ExecuteGetCharacterInfoById")]
pub mod ExecuteGetCharacterInfoById;
#[cfg(feature = "ExecuteGetCharacters")]
pub mod ExecuteGetCharacters;
#[cfg(feature = "ExecuteGetFramsListByImagesId")]
pub mod ExecuteGetFramsListByImagesId;
#[cfg(feature = "ExecuteGetImagesList")]
pub mod ExecuteGetImagesList;
#[cfg(feature = "ExecuteGetVideoInfoById")]
pub mod ExecuteGetVideoInfoById;
#[cfg(feature = "ExecuteGetVideosList")]
pub mod ExecuteGetVideosList;
#[cfg(feature = "ExecutePostCreateImages")]
pub mod ExecutePostCreateImages;
#[cfg(feature = "ExecuteQaChat")]
pub mod ExecuteQaChat;
#[cfg(feature = "ExecuteSession")]
pub mod ExecuteSession;
#[cfg(feature = "ExecuteUpdateImageName")]
pub mod ExecuteUpdateImageName;
#[cfg(feature = "ExecuteUpdateVideoById")]
pub mod ExecuteUpdateVideoById;
#[cfg(feature = "ExecuteUpdateVideoInfoById")]
pub mod ExecuteUpdateVideoInfoById;
#[cfg(feature = "ExecuteUploadImage")]
pub mod ExecuteUploadImage;
#[cfg(feature = "ExecuteUploadPpt")]
pub mod ExecuteUploadPpt;
#[cfg(feature = "ListSuggestions")]
pub mod ListSuggestions;
#[cfg(feature = "PostRequests")]
pub mod PostRequests;
#[cfg(feature = "TagLabor")]
pub mod TagLabor;
#[cfg(feature = "TagSatisfaction")]
pub mod TagSatisfaction;
