[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddDeploymentNodes = []
BatchCreateNodeTags = []
CreateConfigMap = []
CreateDeployment = []
CreateNode = []
CreateOrderForm = []
CreateResourceTags = []
CreateSecret = []
CreateTask = []
CreateWorkSpace = []
DeleteConfigMap = []
DeleteDeployment = []
DeleteNode = []
DeletePod = []
DeleteResourceTag = []
DeleteSecret = []
DeleteTask = []
DeleteWorkSpace = []
FreezeNode = []
ListConfigMaps = []
ListDeviceAlarms = []
ListDevices = []
ListFirmwares = []
ListPlatformManager = []
ListResourceTags = []
ListSecrets = []
ListTasks = []
ListWorkSpaces = []
SetDefaultOrderForm = []
ShowConfigMap = []
ShowDeployment = []
ShowDeploymentPods = []
ShowDeployments = []
ShowNode = []
ShowNodeActivationRecords = []
ShowNodes = []
ShowResourceTags = []
ShowSecret = []
ShowSkillInfo = []
ShowSkillList = []
ShowSkillOrderInfo = []
ShowSkillOrderList = []
ShowTask = []
ShowUpgradeProgress = []
ShowWorkSpace = []
StartAndStopDeployment = []
StartAndStopDeploymentPod = []
SwitchNodeConnection = []
UnfreezeNode = []
UpdateConfigMap = []
UpdateDeployment = []
UpdateDeploymentUsingPatch = []
UpdateNode = []
UpdateNodeCert = []
UpdateNodeFirmware = []
UpdateSecret = []
UpdateTask = []
UpdateWorkSpace = []
full = ["AddDeploymentNodes", "BatchCreateNodeTags", "CreateConfigMap", "CreateDeployment", "CreateNode", "CreateOrderForm", "CreateResourceTags", "CreateSecret", "CreateTask", "CreateWorkSpace", "DeleteConfigMap", "DeleteDeployment", "DeleteNode", "DeletePod", "DeleteResourceTag", "DeleteSecret", "DeleteTask", "DeleteWorkSpace", "FreezeNode", "ListConfigMaps", "ListDeviceAlarms", "ListDevices", "ListFirmwares", "ListPlatformManager", "ListResourceTags", "ListSecrets", "ListTasks", "ListWorkSpaces", "SetDefaultOrderForm", "ShowConfigMap", "ShowDeployment", "ShowDeploymentPods", "ShowDeployments", "ShowNode", "ShowNodeActivationRecords", "ShowNodes", "ShowResourceTags", "ShowSecret", "ShowSkillInfo", "ShowSkillList", "ShowSkillOrderInfo", "ShowSkillOrderList", "ShowTask", "ShowUpgradeProgress", "ShowWorkSpace", "StartAndStopDeployment", "StartAndStopDeploymentPod", "SwitchNodeConnection", "UnfreezeNode", "UpdateConfigMap", "UpdateDeployment", "UpdateDeploymentUsingPatch", "UpdateNode", "UpdateNodeCert", "UpdateNodeFirmware", "UpdateSecret", "UpdateTask", "UpdateWorkSpace"]

[lib]
name = "huawei_cloud_api_definitions_HiLens"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-HiLens"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
