[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
CreatePredefineTags = []
CreateResourceTag = []
DeletePredefineTags = []
DeleteResourceTag = []
ListApiVersions = []
ListPredefineTags = []
ListProviders = []
ListResource = []
ListTagKeys = []
ListTagValues = []
ListTags = []
ShowApiVersion = []
ShowResourceTag = []
ShowTagQuota = []
UpdatePredefineTags = []
full = ["CreatePredefineTags", "CreateResourceTag", "DeletePredefineTags", "DeleteResourceTag", "ListApiVersions", "ListPredefineTags", "ListProviders", "ListResource", "ListTagKeys", "ListTags", "ListTagValues", "ShowApiVersion", "ShowResourceTag", "ShowTagQuota", "UpdatePredefineTags"]

[lib]
name = "huawei_cloud_api_definitions_TMS"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-TMS"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
