#[cfg(feature = "AcceptScheduledEvent")]
pub mod AcceptScheduledEvent;
#[cfg(feature = "ApigAppExists")]
pub mod ApigAppExists;
#[cfg(feature = "AttachObs")]
pub mod AttachObs;
#[cfg(feature = "AuthorizeApiToApigApps")]
pub mod AuthorizeApiToApigApps;
#[cfg(feature = "BatchCreateServiceTags")]
pub mod BatchCreateServiceTags;
#[cfg(feature = "BatchDeletePoolNodes")]
pub mod BatchDeletePoolNodes;
#[cfg(feature = "BatchDeleteServiceTags")]
pub mod BatchDeleteServiceTags;
#[cfg(feature = "BatchRebootPoolNodes")]
pub mod BatchRebootPoolNodes;
#[cfg(feature = "CancelObs")]
pub mod CancelObs;
#[cfg(feature = "ChangeAlgorithm")]
pub mod ChangeAlgorithm;
#[cfg(feature = "ChangeTrainingExperiment")]
pub mod ChangeTrainingExperiment;
#[cfg(feature = "ChangeTrainingJobDescription")]
pub mod ChangeTrainingJobDescription;
#[cfg(feature = "CreateAlgorithm")]
pub mod CreateAlgorithm;
#[cfg(feature = "CreateAndAuthAppAuthApi")]
pub mod CreateAndAuthAppAuthApi;
#[cfg(feature = "CreateApigApp")]
pub mod CreateApigApp;
#[cfg(feature = "CreateApigAppCode")]
pub mod CreateApigAppCode;
#[cfg(feature = "CreateAppAuthApi")]
pub mod CreateAppAuthApi;
#[cfg(feature = "CreateAuthorization")]
pub mod CreateAuthorization;
#[cfg(feature = "CreateDevServer")]
pub mod CreateDevServer;
#[cfg(feature = "CreateImage")]
pub mod CreateImage;
#[cfg(feature = "CreateInspectionJob")]
pub mod CreateInspectionJob;
#[cfg(feature = "CreateLogDiagnosisJob")]
pub mod CreateLogDiagnosisJob;
#[cfg(feature = "CreateModel")]
pub mod CreateModel;
#[cfg(feature = "CreateModelArtsAgency")]
pub mod CreateModelArtsAgency;
#[cfg(feature = "CreateNetwork")]
pub mod CreateNetwork;
#[cfg(feature = "CreateNetworkParameterDiagnosisJob")]
pub mod CreateNetworkParameterDiagnosisJob;
#[cfg(feature = "CreateNodePool")]
pub mod CreateNodePool;
#[cfg(feature = "CreateNotebook")]
pub mod CreateNotebook;
#[cfg(feature = "CreateNotebookTags")]
pub mod CreateNotebookTags;
#[cfg(feature = "CreatePool")]
pub mod CreatePool;
#[cfg(feature = "CreateProfilingDiagnosisJob")]
pub mod CreateProfilingDiagnosisJob;
#[cfg(feature = "CreateSaveImageJob")]
pub mod CreateSaveImageJob;
#[cfg(feature = "CreateService")]
pub mod CreateService;
#[cfg(feature = "CreateTrainingJob")]
pub mod CreateTrainingJob;
#[cfg(feature = "CreateTrainJobTags")]
pub mod CreateTrainJobTags;
#[cfg(feature = "CreateWorkflow")]
pub mod CreateWorkflow;
#[cfg(feature = "CreateWorkflowExecution")]
pub mod CreateWorkflowExecution;
#[cfg(feature = "CreateWorkflowExecutionsActions")]
pub mod CreateWorkflowExecutionsActions;
#[cfg(feature = "CreateWorkflowPurchasePool")]
pub mod CreateWorkflowPurchasePool;
#[cfg(feature = "CreateWorkflowSchedule")]
pub mod CreateWorkflowSchedule;
#[cfg(feature = "CreateWorkflowServiceAuth")]
pub mod CreateWorkflowServiceAuth;
#[cfg(feature = "CreateWorkflowStepExecutionsActions")]
pub mod CreateWorkflowStepExecutionsActions;
#[cfg(feature = "CreateWorkflowSubscriptions")]
pub mod CreateWorkflowSubscriptions;
#[cfg(feature = "CreateWorkspace")]
pub mod CreateWorkspace;
#[cfg(feature = "DeleteAlgorithm")]
pub mod DeleteAlgorithm;
#[cfg(feature = "DeleteApiAppAuth")]
pub mod DeleteApiAppAuth;
#[cfg(feature = "DeleteApigApp")]
pub mod DeleteApigApp;
#[cfg(feature = "DeleteApigAppCode")]
pub mod DeleteApigAppCode;
#[cfg(feature = "DeleteAppAuthApi")]
pub mod DeleteAppAuthApi;
#[cfg(feature = "DeleteAuthorizations")]
pub mod DeleteAuthorizations;
#[cfg(feature = "DeleteDevServer")]
pub mod DeleteDevServer;
#[cfg(feature = "DeleteImage")]
pub mod DeleteImage;
#[cfg(feature = "DeleteInspectionJob")]
pub mod DeleteInspectionJob;
#[cfg(feature = "DeleteLogDiagnosisJob")]
pub mod DeleteLogDiagnosisJob;
#[cfg(feature = "DeleteModel")]
pub mod DeleteModel;
#[cfg(feature = "DeleteNetwork")]
pub mod DeleteNetwork;
#[cfg(feature = "DeleteNetworkDiagnosisJob1")]
pub mod DeleteNetworkDiagnosisJob1;
#[cfg(feature = "DeleteNodePool")]
pub mod DeleteNodePool;
#[cfg(feature = "DeleteNotebook")]
pub mod DeleteNotebook;
#[cfg(feature = "DeleteNotebookTags")]
pub mod DeleteNotebookTags;
#[cfg(feature = "DeletePool")]
pub mod DeletePool;
#[cfg(feature = "DeleteProfilingDiagnosisJob")]
pub mod DeleteProfilingDiagnosisJob;
#[cfg(feature = "DeleteService")]
pub mod DeleteService;
#[cfg(feature = "DeleteTrainingJob")]
pub mod DeleteTrainingJob;
#[cfg(feature = "DeleteTrainJobTags")]
pub mod DeleteTrainJobTags;
#[cfg(feature = "DeleteWorkflow")]
pub mod DeleteWorkflow;
#[cfg(feature = "DeleteWorkflowExecution")]
pub mod DeleteWorkflowExecution;
#[cfg(feature = "DeleteWorkflowScheduleId")]
pub mod DeleteWorkflowScheduleId;
#[cfg(feature = "DeleteWorkflowSubscription")]
pub mod DeleteWorkflowSubscription;
#[cfg(feature = "DeleteWorkspace")]
pub mod DeleteWorkspace;
#[cfg(feature = "GetAppAuthApiInfo")]
pub mod GetAppAuthApiInfo;
#[cfg(feature = "GetAppAuthApisInfo")]
pub mod GetAppAuthApisInfo;
#[cfg(feature = "GetAuthorizations")]
pub mod GetAuthorizations;
#[cfg(feature = "GetServiceAppAuthApiAuthInfo")]
pub mod GetServiceAppAuthApiAuthInfo;
#[cfg(feature = "ListAlgorithms")]
pub mod ListAlgorithms;
#[cfg(feature = "ListAllNotebooks")]
pub mod ListAllNotebooks;
#[cfg(feature = "ListApigApps")]
pub mod ListApigApps;
#[cfg(feature = "ListAttachableObSs")]
pub mod ListAttachableObSs;
#[cfg(feature = "ListClusters")]
pub mod ListClusters;
#[cfg(feature = "ListDevServers")]
pub mod ListDevServers;
#[cfg(feature = "ListEvents")]
pub mod ListEvents;
#[cfg(feature = "ListFlavors")]
pub mod ListFlavors;
#[cfg(feature = "ListImage")]
pub mod ListImage;
#[cfg(feature = "ListImageGroup")]
pub mod ListImageGroup;
#[cfg(feature = "ListInspectionItems")]
pub mod ListInspectionItems;
#[cfg(feature = "ListInspectionJobs")]
pub mod ListInspectionJobs;
#[cfg(feature = "ListInspectionNodes")]
pub mod ListInspectionNodes;
#[cfg(feature = "ListLogDiagnosisJobs")]
pub mod ListLogDiagnosisJobs;
#[cfg(feature = "ListModels")]
pub mod ListModels;
#[cfg(feature = "ListNetworkDiagnosisJobAlarm")]
pub mod ListNetworkDiagnosisJobAlarm;
#[cfg(feature = "ListNetworkDiagnosisJobProxyResponseDelimit")]
pub mod ListNetworkDiagnosisJobProxyResponseDelimit;
#[cfg(feature = "ListNetworkDiagnosisJobs")]
pub mod ListNetworkDiagnosisJobs;
#[cfg(feature = "ListNetworks")]
pub mod ListNetworks;
#[cfg(feature = "ListNodePoolNodes")]
pub mod ListNodePoolNodes;
#[cfg(feature = "ListNodePools")]
pub mod ListNodePools;
#[cfg(feature = "ListNotebooks")]
pub mod ListNotebooks;
#[cfg(feature = "ListPoolNodes")]
pub mod ListPoolNodes;
#[cfg(feature = "ListPools")]
pub mod ListPools;
#[cfg(feature = "ListPoolTags")]
pub mod ListPoolTags;
#[cfg(feature = "ListProfilingDiagnosisJobs")]
pub mod ListProfilingDiagnosisJobs;
