#[cfg(feature = "AddAuditAgent")]
pub mod AddAuditAgent;
#[cfg(feature = "AddAuditAgentNew")]
pub mod AddAuditAgentNew;
#[cfg(feature = "AddAuditDatabase")]
pub mod AddAuditDatabase;
#[cfg(feature = "AddAuditDatabaseNew")]
pub mod AddAuditDatabaseNew;
#[cfg(feature = "AddRdsDatabase")]
pub mod AddRdsDatabase;
#[cfg(feature = "AddRdsDatabaseNew")]
pub mod AddRdsDatabaseNew;
#[cfg(feature = "AddRdsNoAgentDatabase")]
pub mod AddRdsNoAgentDatabase;
#[cfg(feature = "BatchAddAuditWhitelist")]
pub mod BatchAddAuditWhitelist;
#[cfg(feature = "BatchAddResourceTag")]
pub mod BatchAddResourceTag;
#[cfg(feature = "BatchDeleteAuditScope")]
pub mod BatchDeleteAuditScope;
#[cfg(feature = "BatchDeleteResourceTag")]
pub mod BatchDeleteResourceTag;
#[cfg(feature = "BatchSetAuditAlarmLogStatus")]
pub mod BatchSetAuditAlarmLogStatus;
#[cfg(feature = "BindDbEncryptEip")]
pub mod BindDbEncryptEip;
#[cfg(feature = "BindDbOmEip")]
pub mod BindDbOmEip;
#[cfg(feature = "ChangeDbEncryptSecurityGroup")]
pub mod ChangeDbEncryptSecurityGroup;
#[cfg(feature = "ChangeDbOmSecurityGroup")]
pub mod ChangeDbOmSecurityGroup;
#[cfg(feature = "ConfirmUpgradeAudit")]
pub mod ConfirmUpgradeAudit;
#[cfg(feature = "CountDbAccountSession")]
pub mod CountDbAccountSession;
#[cfg(feature = "CountDbClientSession")]
pub mod CountDbClientSession;
#[cfg(feature = "CountInjectionStatistics")]
pub mod CountInjectionStatistics;
#[cfg(feature = "CountOperationStatistics")]
pub mod CountOperationStatistics;
#[cfg(feature = "CountResourceInstanceByTag")]
pub mod CountResourceInstanceByTag;
#[cfg(feature = "CountRiskTrendStatistics")]
pub mod CountRiskTrendStatistics;
#[cfg(feature = "CountSessionStatistics")]
pub mod CountSessionStatistics;
#[cfg(feature = "CountSqlStatistics")]
pub mod CountSqlStatistics;
#[cfg(feature = "CountSqlTrendStatistics")]
pub mod CountSqlTrendStatistics;
#[cfg(feature = "CreateAuditDbAgent")]
pub mod CreateAuditDbAgent;
#[cfg(feature = "CreateAuditRiskRule")]
pub mod CreateAuditRiskRule;
#[cfg(feature = "CreateAuditScopeRule")]
pub mod CreateAuditScopeRule;
#[cfg(feature = "CreateAuditSqlRule")]
pub mod CreateAuditSqlRule;
#[cfg(feature = "CreateDbEncryptInstancePeriod")]
pub mod CreateDbEncryptInstancePeriod;
#[cfg(feature = "CreateDbOmInstancePeriod")]
pub mod CreateDbOmInstancePeriod;
#[cfg(feature = "CreateInstancesPeriodOrder")]
pub mod CreateInstancesPeriodOrder;
#[cfg(feature = "CreateInstancesPeriodOrderNew")]
pub mod CreateInstancesPeriodOrderNew;
#[cfg(feature = "CreateReport")]
pub mod CreateReport;
#[cfg(feature = "CreateSensitiveMaskRule")]
pub mod CreateSensitiveMaskRule;
#[cfg(feature = "DeleteAuditAgent")]
pub mod DeleteAuditAgent;
#[cfg(feature = "DeleteAuditAgentNew")]
pub mod DeleteAuditAgentNew;
#[cfg(feature = "DeleteAuditAlarmLog")]
pub mod DeleteAuditAlarmLog;
#[cfg(feature = "DeleteAuditBackupTask")]
pub mod DeleteAuditBackupTask;
#[cfg(feature = "DeleteAuditDatabase")]
pub mod DeleteAuditDatabase;
#[cfg(feature = "DeleteAuditDatabaseNew")]
pub mod DeleteAuditDatabaseNew;
#[cfg(feature = "DeleteAuditReport")]
pub mod DeleteAuditReport;
#[cfg(feature = "DeleteAuditRuleRisk")]
pub mod DeleteAuditRuleRisk;
#[cfg(feature = "DeleteAuditRuleSql")]
pub mod DeleteAuditRuleSql;
#[cfg(feature = "DeleteAuditScope")]
pub mod DeleteAuditScope;
#[cfg(feature = "DeleteAuditWhitelist")]
pub mod DeleteAuditWhitelist;
#[cfg(feature = "DeleteDbEncryptInstance")]
pub mod DeleteDbEncryptInstance;
#[cfg(feature = "DeleteDbOmInstance")]
pub mod DeleteDbOmInstance;
#[cfg(feature = "DeleteInstances")]
pub mod DeleteInstances;
#[cfg(feature = "DeleteInstancesNew")]
pub mod DeleteInstancesNew;
#[cfg(feature = "DeleteSensitiveRules")]
pub mod DeleteSensitiveRules;
#[cfg(feature = "DownloadAuditAgent")]
pub mod DownloadAuditAgent;
#[cfg(feature = "DownloadAuditAgentNew")]
pub mod DownloadAuditAgentNew;
#[cfg(feature = "DownloadAuditReport")]
pub mod DownloadAuditReport;
#[cfg(feature = "ListAlarmTopicConfigInfo")]
pub mod ListAlarmTopicConfigInfo;
#[cfg(feature = "ListAlarmTopicConfigInfoNew")]
pub mod ListAlarmTopicConfigInfoNew;
#[cfg(feature = "ListAuditAgent")]
pub mod ListAuditAgent;
#[cfg(feature = "ListAuditAgentNew")]
pub mod ListAuditAgentNew;
#[cfg(feature = "ListAuditAlarmLog")]
pub mod ListAuditAlarmLog;
#[cfg(feature = "ListAuditAlarmLogNew")]
pub mod ListAuditAlarmLogNew;
#[cfg(feature = "ListAuditBackupInfo")]
pub mod ListAuditBackupInfo;
#[cfg(feature = "ListAuditBackupRiskTemplates")]
pub mod ListAuditBackupRiskTemplates;
#[cfg(feature = "ListAuditDatabases")]
pub mod ListAuditDatabases;
#[cfg(feature = "ListAuditDatabasesNew")]
pub mod ListAuditDatabasesNew;
#[cfg(feature = "ListAuditInstanceJobs")]
pub mod ListAuditInstanceJobs;
#[cfg(feature = "ListAuditInstanceJobsNew")]
pub mod ListAuditInstanceJobsNew;
#[cfg(feature = "ListAuditInstances")]
pub mod ListAuditInstances;
#[cfg(feature = "ListAuditInstancesNew")]
pub mod ListAuditInstancesNew;
#[cfg(feature = "ListAuditObsBuckets")]
pub mod ListAuditObsBuckets;
#[cfg(feature = "ListAuditOperateLogs")]
pub mod ListAuditOperateLogs;
#[cfg(feature = "ListAuditOperateLogsNew")]
pub mod ListAuditOperateLogsNew;
#[cfg(feature = "ListAuditReports")]
pub mod ListAuditReports;
#[cfg(feature = "ListAuditReportTemplates")]
pub mod ListAuditReportTemplates;
#[cfg(feature = "ListAuditRuleRisks")]
pub mod ListAuditRuleRisks;
#[cfg(feature = "ListAuditRuleRisksNew")]
pub mod ListAuditRuleRisksNew;
#[cfg(feature = "ListAuditRuleScopes")]
pub mod ListAuditRuleScopes;
#[cfg(feature = "ListAuditRuleScopesNew")]
pub mod ListAuditRuleScopesNew;
#[cfg(feature = "ListAuditSensitiveMasks")]
pub mod ListAuditSensitiveMasks;
#[cfg(feature = "ListAuditSensitiveMasksNew")]
pub mod ListAuditSensitiveMasksNew;
#[cfg(feature = "ListAuditSqls")]
pub mod ListAuditSqls;
#[cfg(feature = "ListAuditSqlsNew")]
pub mod ListAuditSqlsNew;
#[cfg(feature = "ListAuditSummaryInfos")]
pub mod ListAuditSummaryInfos;
#[cfg(feature = "ListAuditTags")]
pub mod ListAuditTags;
#[cfg(feature = "ListAuditTrendHistory")]
pub mod ListAuditTrendHistory;
#[cfg(feature = "ListAvailabilityZoneInfos")]
pub mod ListAvailabilityZoneInfos;
#[cfg(feature = "ListAvailabilityZoneInfosNew")]
pub mod ListAvailabilityZoneInfosNew;
#[cfg(feature = "ListDbEncryptInstances")]
pub mod ListDbEncryptInstances;
#[cfg(feature = "ListEcsSpecification")]
pub mod ListEcsSpecification;
#[cfg(feature = "ListEcsSpecificationNew")]
pub mod ListEcsSpecificationNew;
#[cfg(feature = "ListInstances")]
pub mod ListInstances;
#[cfg(feature = "ListProjectResourceTags")]
pub mod ListProjectResourceTags;
#[cfg(feature = "ListRdsDatabases")]
pub mod ListRdsDatabases;
#[cfg(feature = "ListResourceInstanceByTag")]
pub mod ListResourceInstanceByTag;
#[cfg(feature = "ListSqlInjectionRules")]
pub mod ListSqlInjectionRules;
#[cfg(feature = "ListSqlInjectionRulesNew")]
pub mod ListSqlInjectionRulesNew;
#[cfg(feature = "ListWhitelists")]
pub mod ListWhitelists;
#[cfg(feature = "RebootAuditInstance")]
pub mod RebootAuditInstance;
#[cfg(feature = "RebootAuditInstanceNew")]
pub mod RebootAuditInstanceNew;
#[cfg(feature = "RebootDbEncryptInstance")]
pub mod RebootDbEncryptInstance;
