#[cfg(feature = "AddAuditAgent")]
pub mod AddAuditAgent;
#[cfg(feature = "AddAuditDatabase")]
pub mod AddAuditDatabase;
#[cfg(feature = "AddRdsDatabase")]
pub mod AddRdsDatabase;
#[cfg(feature = "AddRdsNoAgentDatabase")]
pub mod AddRdsNoAgentDatabase;
#[cfg(feature = "BatchAddResourceTag")]
pub mod BatchAddResourceTag;
#[cfg(feature = "BatchDeleteResourceTag")]
pub mod BatchDeleteResourceTag;
#[cfg(feature = "CountResourceInstanceByTag")]
pub mod CountResourceInstanceByTag;
#[cfg(feature = "CreateInstancesPeriodOrder")]
pub mod CreateInstancesPeriodOrder;
#[cfg(feature = "DeleteAuditAgent")]
pub mod DeleteAuditAgent;
#[cfg(feature = "DeleteAuditDatabase")]
pub mod DeleteAuditDatabase;
#[cfg(feature = "DeleteInstances")]
pub mod DeleteInstances;
#[cfg(feature = "DownloadAuditAgent")]
pub mod DownloadAuditAgent;
#[cfg(feature = "ListAuditAgent")]
pub mod ListAuditAgent;
#[cfg(feature = "ListAuditAlarmLog")]
pub mod ListAuditAlarmLog;
#[cfg(feature = "ListAuditDatabases")]
pub mod ListAuditDatabases;
#[cfg(feature = "ListAuditInstanceJobs")]
pub mod ListAuditInstanceJobs;
#[cfg(feature = "ListAuditInstances")]
pub mod ListAuditInstances;
#[cfg(feature = "ListAuditOperateLogs")]
pub mod ListAuditOperateLogs;
#[cfg(feature = "ListAuditRuleRisks")]
pub mod ListAuditRuleRisks;
#[cfg(feature = "ListAuditRuleScopes")]
pub mod ListAuditRuleScopes;
#[cfg(feature = "ListAuditSensitiveMasks")]
pub mod ListAuditSensitiveMasks;
#[cfg(feature = "ListAuditSqls")]
pub mod ListAuditSqls;
#[cfg(feature = "ListAuditSummaryInfos")]
pub mod ListAuditSummaryInfos;
#[cfg(feature = "ListAvailabilityZoneInfos")]
pub mod ListAvailabilityZoneInfos;
#[cfg(feature = "ListEcsSpecification")]
pub mod ListEcsSpecification;
#[cfg(feature = "ListProjectResourceTags")]
pub mod ListProjectResourceTags;
#[cfg(feature = "ListRdsDatabases")]
pub mod ListRdsDatabases;
#[cfg(feature = "ListResourceInstanceByTag")]
pub mod ListResourceInstanceByTag;
#[cfg(feature = "ListSqlInjectionRules")]
pub mod ListSqlInjectionRules;
#[cfg(feature = "RebootAuditInstance")]
pub mod RebootAuditInstance;
#[cfg(feature = "ShowAuditQuota")]
pub mod ShowAuditQuota;
#[cfg(feature = "ShowAuditRuleRisk")]
pub mod ShowAuditRuleRisk;
#[cfg(feature = "StartAuditInstance")]
pub mod StartAuditInstance;
#[cfg(feature = "StopAuditInstance")]
pub mod StopAuditInstance;
#[cfg(feature = "SwitchAgent")]
pub mod SwitchAgent;
#[cfg(feature = "SwitchAuditDatabase")]
pub mod SwitchAuditDatabase;
#[cfg(feature = "SwitchRiskRule")]
pub mod SwitchRiskRule;
#[cfg(feature = "UpdateAuditInstance")]
pub mod UpdateAuditInstance;
#[cfg(feature = "UpdateAuditSecurityGroup")]
pub mod UpdateAuditSecurityGroup;
