#[cfg(feature = "AddRdsNoAgentDatabase")]
pub mod AddRdsNoAgentDatabase;
#[cfg(feature = "BatchAddResourceTag")]
pub mod BatchAddResourceTag;
#[cfg(feature = "BatchDeleteResourceTag")]
pub mod BatchDeleteResourceTag;
#[cfg(feature = "CountResourceInstanceByTag")]
pub mod CountResourceInstanceByTag;
#[cfg(feature = "CreateInstancesPeriodOrder")]
pub mod CreateInstancesPeriodOrder;
#[cfg(feature = "ListAuditDatabases")]
pub mod ListAuditDatabases;
#[cfg(feature = "ListAuditInstanceJobs")]
pub mod ListAuditInstanceJobs;
#[cfg(feature = "ListAuditInstances")]
pub mod ListAuditInstances;
#[cfg(feature = "ListAuditOperateLogs")]
pub mod ListAuditOperateLogs;
#[cfg(feature = "ListAuditRuleRisks")]
pub mod ListAuditRuleRisks;
#[cfg(feature = "ListAuditRuleScopes")]
pub mod ListAuditRuleScopes;
#[cfg(feature = "ListAuditSensitiveMasks")]
pub mod ListAuditSensitiveMasks;
#[cfg(feature = "ListAvailabilityZoneInfos")]
pub mod ListAvailabilityZoneInfos;
#[cfg(feature = "ListEcsSpecification")]
pub mod ListEcsSpecification;
#[cfg(feature = "ListProjectResourceTags")]
pub mod ListProjectResourceTags;
#[cfg(feature = "ListResourceInstanceByTag")]
pub mod ListResourceInstanceByTag;
#[cfg(feature = "ListSqlInjectionRules")]
pub mod ListSqlInjectionRules;
#[cfg(feature = "ShowAuditQuota")]
pub mod ShowAuditQuota;
#[cfg(feature = "ShowAuditRuleRisk")]
pub mod ShowAuditRuleRisk;
#[cfg(feature = "SwitchAgent")]
pub mod SwitchAgent;
#[cfg(feature = "SwitchRiskRule")]
pub mod SwitchRiskRule;
#[cfg(feature = "UpdateAuditSecurityGroup")]
pub mod UpdateAuditSecurityGroup;
