#[cfg(feature = "BatchCreateOrDeleteRabbitMqTag")]
pub mod BatchCreateOrDeleteRabbitMqTag;
#[cfg(feature = "BatchDeleteExchanges")]
pub mod BatchDeleteExchanges;
#[cfg(feature = "BatchDeleteQueues")]
pub mod BatchDeleteQueues;
#[cfg(feature = "BatchDeleteVhosts")]
pub mod BatchDeleteVhosts;
#[cfg(feature = "BatchRestartOrDeleteInstances")]
pub mod BatchRestartOrDeleteInstances;
#[cfg(feature = "CreateBinding")]
pub mod CreateBinding;
#[cfg(feature = "CreateExchange")]
pub mod CreateExchange;
#[cfg(feature = "CreatePostPaidInstanceByEngine")]
pub mod CreatePostPaidInstanceByEngine;
#[cfg(feature = "CreateQueue")]
pub mod CreateQueue;
#[cfg(feature = "CreateUser")]
pub mod CreateUser;
#[cfg(feature = "CreateVhost")]
pub mod CreateVhost;
#[cfg(feature = "DeleteBackgroundTask")]
pub mod DeleteBackgroundTask;
#[cfg(feature = "DeleteBinding")]
pub mod DeleteBinding;
#[cfg(feature = "DeleteInstance")]
pub mod DeleteInstance;
#[cfg(feature = "DeleteQueueInfo")]
pub mod DeleteQueueInfo;
#[cfg(feature = "DeleteUser")]
pub mod DeleteUser;
#[cfg(feature = "EnableDns")]
pub mod EnableDns;
#[cfg(feature = "ListAvailableZones")]
pub mod ListAvailableZones;
#[cfg(feature = "ListBackgroundTasks")]
pub mod ListBackgroundTasks;
#[cfg(feature = "ListBindings")]
pub mod ListBindings;
#[cfg(feature = "ListEngineProducts")]
pub mod ListEngineProducts;
#[cfg(feature = "ListExchanges")]
pub mod ListExchanges;
#[cfg(feature = "ListInstancesDetails")]
pub mod ListInstancesDetails;
#[cfg(feature = "ListPlugins")]
pub mod ListPlugins;
#[cfg(feature = "ListQueues")]
pub mod ListQueues;
#[cfg(feature = "ListUser")]
pub mod ListUser;
#[cfg(feature = "ListVhosts")]
pub mod ListVhosts;
#[cfg(feature = "ResetPassword")]
pub mod ResetPassword;
#[cfg(feature = "ResizeEngineInstance")]
pub mod ResizeEngineInstance;
#[cfg(feature = "ShowBackgroundTask")]
pub mod ShowBackgroundTask;
#[cfg(feature = "ShowCesHierarchy")]
pub mod ShowCesHierarchy;
#[cfg(feature = "ShowEngineInstanceExtendProductInfo")]
pub mod ShowEngineInstanceExtendProductInfo;
#[cfg(feature = "ShowInstance")]
pub mod ShowInstance;
#[cfg(feature = "ShowMaintainWindows")]
pub mod ShowMaintainWindows;
#[cfg(feature = "ShowQueueDetails")]
pub mod ShowQueueDetails;
#[cfg(feature = "ShowRabbitMqProductCores")]
pub mod ShowRabbitMqProductCores;
#[cfg(feature = "ShowRabbitMqProjectTags")]
pub mod ShowRabbitMqProjectTags;
#[cfg(feature = "ShowRabbitMqTags")]
pub mod ShowRabbitMqTags;
#[cfg(feature = "UpdateInstance")]
pub mod UpdateInstance;
#[cfg(feature = "UpdatePlugins")]
pub mod UpdatePlugins;
#[cfg(feature = "UpdateUser")]
pub mod UpdateUser;
