name: daily-update
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}
env:
  CARGO_TERM_COLOR: always
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: OUT_DIR=$(pwd)/schemas cargo run --bin update
      - name: Get current date
        id: date
        run: |
          echo "{date}={$(date +'%Y-%m-%d')}" >> $GITHUB_STATE
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          author_email: mingyang91@qq.com
          author_name: mingyang91
          coauthor_email: github-actions[bot]@users.noreply.github.com
          coauthor_name: github-actions[bot]
          message: 'chore: auto-update ${{ env.date }}'
