name: daily-update
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}
env:
  CARGO_TERM_COLOR: always
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: OUT_DIR=$(pwd)/src/schemas cargo run
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
