name: publish
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to publish"
        required: true
        type: string
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish
        run: cargo publish
      - name: Publish
        run: |
          for dir in schemas/*/; do
            (cd "$dir" && cargo publish)
          done
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
