name: publish
on:
  workflow_dispatch:
    inputs:
      version:
        description: "version"
        required: true
        type: string
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 10
      - name: Publish
        run: sh publish.sh ${{ inputs.version }}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
