name: publish
on:
  # schedule:
  #   - cron: "0 * * * *"
  workflow_dispatch:
    inputs:
      version:
        description: "version"
        required: true
        type: string
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Publish
        run: bash publish.sh ${{ inputs.version || '0.1.' }}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
