#[cfg(feature = "BatchCreateResourceTags")]
pub mod BatchCreateResourceTags;
#[cfg(feature = "BindGlobalEips")]
pub mod BindGlobalEips;
#[cfg(feature = "CreateConnectGateway")]
pub mod CreateConnectGateway;
#[cfg(feature = "CreateGlobalDcGateway")]
pub mod CreateGlobalDcGateway;
#[cfg(feature = "CreateHostedDirectConnect")]
pub mod CreateHostedDirectConnect;
#[cfg(feature = "CreatePeerLink")]
pub mod CreatePeerLink;
#[cfg(feature = "CreateResourceTag")]
pub mod CreateResourceTag;
#[cfg(feature = "CreateVifPeer")]
pub mod CreateVifPeer;
#[cfg(feature = "CreateVifPeerDetection")]
pub mod CreateVifPeerDetection;
#[cfg(feature = "CreateVirtualGateway")]
pub mod CreateVirtualGateway;
#[cfg(feature = "CreateVirtualInterface")]
pub mod CreateVirtualInterface;
#[cfg(feature = "DeleteConnectGateway")]
pub mod DeleteConnectGateway;
#[cfg(feature = "DeleteDirectConnect")]
pub mod DeleteDirectConnect;
#[cfg(feature = "DeleteGlobalDcGateway")]
pub mod DeleteGlobalDcGateway;
#[cfg(feature = "DeleteHostedDirectConnect")]
pub mod DeleteHostedDirectConnect;
#[cfg(feature = "DeletePeerLink")]
pub mod DeletePeerLink;
#[cfg(feature = "DeleteResourceTag")]
pub mod DeleteResourceTag;
#[cfg(feature = "DeleteVifPeer")]
pub mod DeleteVifPeer;
#[cfg(feature = "DeleteVifPeerDetection")]
pub mod DeleteVifPeerDetection;
#[cfg(feature = "DeleteVirtualGateway")]
pub mod DeleteVirtualGateway;
#[cfg(feature = "DeleteVirtualInterface")]
pub mod DeleteVirtualInterface;
#[cfg(feature = "ListConnectGateways")]
pub mod ListConnectGateways;
#[cfg(feature = "ListDirectConnectLocations")]
pub mod ListDirectConnectLocations;
#[cfg(feature = "ListDirectConnects")]
pub mod ListDirectConnects;
#[cfg(feature = "ListGdgwRouteTables")]
pub mod ListGdgwRouteTables;
#[cfg(feature = "ListGlobalDcGateways")]
pub mod ListGlobalDcGateways;
#[cfg(feature = "ListGlobalEips")]
pub mod ListGlobalEips;
#[cfg(feature = "ListHostedDirectConnects")]
pub mod ListHostedDirectConnects;
#[cfg(feature = "ListPeerLinks")]
pub mod ListPeerLinks;
#[cfg(feature = "ListProjectTags")]
pub mod ListProjectTags;
#[cfg(feature = "ListSwitchoverTestRecords")]
pub mod ListSwitchoverTestRecords;
#[cfg(feature = "ListTagResourceInstances")]
pub mod ListTagResourceInstances;
#[cfg(feature = "ListVifPeerDetections")]
pub mod ListVifPeerDetections;
#[cfg(feature = "ListVirtualGateways")]
pub mod ListVirtualGateways;
#[cfg(feature = "ListVirtualInterfaces")]
pub mod ListVirtualInterfaces;
#[cfg(feature = "ShowConnectGateway")]
pub mod ShowConnectGateway;
#[cfg(feature = "ShowDirectConnect")]
pub mod ShowDirectConnect;
#[cfg(feature = "ShowDirectConnectLocation")]
pub mod ShowDirectConnectLocation;
#[cfg(feature = "ShowGlobalDcGateway")]
pub mod ShowGlobalDcGateway;
#[cfg(feature = "ShowHostedDirectConnect")]
pub mod ShowHostedDirectConnect;
#[cfg(feature = "ShowPeerLink")]
pub mod ShowPeerLink;
#[cfg(feature = "ShowQuotas")]
pub mod ShowQuotas;
#[cfg(feature = "ShowResourceTag")]
pub mod ShowResourceTag;
#[cfg(feature = "ShowVifPeerDetection")]
pub mod ShowVifPeerDetection;
#[cfg(feature = "ShowVirtualGateway")]
pub mod ShowVirtualGateway;
#[cfg(feature = "ShowVirtualInterface")]
pub mod ShowVirtualInterface;
#[cfg(feature = "SwitchoverTest")]
pub mod SwitchoverTest;
#[cfg(feature = "UnbindGlobalEips")]
pub mod UnbindGlobalEips;
#[cfg(feature = "UpdateConnectGateway")]
pub mod UpdateConnectGateway;
#[cfg(feature = "UpdateDirectConnect")]
pub mod UpdateDirectConnect;
#[cfg(feature = "UpdateExtendAttribute")]
pub mod UpdateExtendAttribute;
#[cfg(feature = "UpdateGdgwRouteTable")]
pub mod UpdateGdgwRouteTable;
#[cfg(feature = "UpdateGlobalDcGateway")]
pub mod UpdateGlobalDcGateway;
#[cfg(feature = "UpdateHostedDirectConnect")]
pub mod UpdateHostedDirectConnect;
#[cfg(feature = "UpdatePeerLink")]
pub mod UpdatePeerLink;
#[cfg(feature = "UpdateVifPeer")]
pub mod UpdateVifPeer;
#[cfg(feature = "UpdateVirtualGateway")]
pub mod UpdateVirtualGateway;
#[cfg(feature = "UpdateVirtualInterface")]
pub mod UpdateVirtualInterface;
