[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddComponent = []
BatchCreateClusterTags = []
BatchDeleteClusterTags = []
BatchDeleteJobs = []
CancelSql = []
CancelSyncIamUser = []
CreateAutoScalingPolicy = []
CreateCluster = []
CreateClusterTag = []
CreateDataConnector = []
CreateExecuteJob = []
CreateScalingPolicy = []
DeleteAutoScalingPolicy = []
DeleteCluster = []
DeleteClusterTag = []
DeleteDataConnector = []
ExecuteSql = []
ExpandCluster = []
ListAllTags = []
ListAvailableZones = []
ListClusterTags = []
ListClusters = []
ListClustersByTags = []
ListDataConnector = []
ListHosts = []
RunJobFlow = []
ShowAgencyMapping = []
ShowAutoScalingPolicy = []
ShowClusterDetails = []
ShowHdfsFileList = []
ShowJobExeListNew = []
ShowMrsFlavors = []
ShowMrsVersionList = []
ShowMrsVersionMetadata = []
ShowSingleJobExe = []
ShowSqlResult = []
ShowSqlResultWithJob = []
ShowSyncIamUser = []
ShowTagQuota = []
ShowTagStatus = []
ShrinkCluster = []
StopJob = []
SwitchClusterTags = []
UpdateAgencyMapping = []
UpdateAutoScalingPolicy = []
UpdateClusterName = []
UpdateClusterScaling = []
UpdateDataConnector = []
UpdateSyncIamUser = []
full = ["AddComponent", "BatchCreateClusterTags", "BatchDeleteClusterTags", "BatchDeleteJobs", "CancelSql", "CancelSyncIamUser", "CreateAutoScalingPolicy", "CreateCluster", "CreateClusterTag", "CreateDataConnector", "CreateExecuteJob", "CreateScalingPolicy", "DeleteAutoScalingPolicy", "DeleteCluster", "DeleteClusterTag", "DeleteDataConnector", "ExecuteSql", "ExpandCluster", "ListAllTags", "ListAvailableZones", "ListClusters", "ListClustersByTags", "ListClusterTags", "ListDataConnector", "ListHosts", "RunJobFlow", "ShowAgencyMapping", "ShowAutoScalingPolicy", "ShowClusterDetails", "ShowHdfsFileList", "ShowJobExeListNew", "ShowMrsFlavors", "ShowMrsVersionList", "ShowMrsVersionMetadata", "ShowSingleJobExe", "ShowSqlResult", "ShowSqlResultWithJob", "ShowSyncIamUser", "ShowTagQuota", "ShowTagStatus", "ShrinkCluster", "StopJob", "SwitchClusterTags", "UpdateAgencyMapping", "UpdateAutoScalingPolicy", "UpdateClusterName", "UpdateClusterScaling", "UpdateDataConnector", "UpdateSyncIamUser"]

[lib]
name = "huawei_cloud_api_definitions_MRS"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-MRS"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "0.1.0"
