#[cfg(feature = "BatchUpdateTasks")]
pub mod BatchUpdateTasks;
#[cfg(feature = "CheckPrefix")]
pub mod CheckPrefix;
#[cfg(feature = "CreateSyncEvents")]
pub mod CreateSyncEvents;
#[cfg(feature = "CreateSyncTask")]
pub mod CreateSyncTask;
#[cfg(feature = "CreateTask")]
pub mod CreateTask;
#[cfg(feature = "CreateTaskGroup")]
pub mod CreateTaskGroup;
#[cfg(feature = "DeleteSyncTask")]
pub mod DeleteSyncTask;
#[cfg(feature = "DeleteTask")]
pub mod DeleteTask;
#[cfg(feature = "DeleteTaskGroup")]
pub mod DeleteTaskGroup;
#[cfg(feature = "ListApiVersions")]
pub mod ListApiVersions;
#[cfg(feature = "ListSyncTasks")]
pub mod ListSyncTasks;
#[cfg(feature = "ListSyncTaskStatistic")]
pub mod ListSyncTaskStatistic;
#[cfg(feature = "ListTaskGroup")]
pub mod ListTaskGroup;
#[cfg(feature = "ListTasks")]
pub mod ListTasks;
#[cfg(feature = "RetryTaskGroup")]
pub mod RetryTaskGroup;
#[cfg(feature = "ShowApiInfo")]
pub mod ShowApiInfo;
#[cfg(feature = "ShowBucketList")]
pub mod ShowBucketList;
#[cfg(feature = "ShowBucketObjects")]
pub mod ShowBucketObjects;
#[cfg(feature = "ShowBucketRegion")]
pub mod ShowBucketRegion;
#[cfg(feature = "ShowCdnInfo")]
pub mod ShowCdnInfo;
#[cfg(feature = "ShowCloudType")]
pub mod ShowCloudType;
#[cfg(feature = "ShowRegionInfo")]
pub mod ShowRegionInfo;
#[cfg(feature = "ShowSyncTask")]
pub mod ShowSyncTask;
#[cfg(feature = "ShowTask")]
pub mod ShowTask;
#[cfg(feature = "ShowTaskGroup")]
pub mod ShowTaskGroup;
#[cfg(feature = "StartSyncTask")]
pub mod StartSyncTask;
#[cfg(feature = "StartTask")]
pub mod StartTask;
#[cfg(feature = "StartTaskGroup")]
pub mod StartTaskGroup;
#[cfg(feature = "StopSyncTask")]
pub mod StopSyncTask;
#[cfg(feature = "StopTask")]
pub mod StopTask;
#[cfg(feature = "StopTaskGroup")]
pub mod StopTaskGroup;
#[cfg(feature = "UpdateBandwidthPolicy")]
pub mod UpdateBandwidthPolicy;
#[cfg(feature = "UpdatePrivacyAgreementRecord")]
pub mod UpdatePrivacyAgreementRecord;
#[cfg(feature = "UpdateTaskGroup")]
pub mod UpdateTaskGroup;
